package typings.pulumiAws.anon

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait Accessanalyzer extends js.Object {
  var accessanalyzer: js.UndefOr[String] = js.native
  var acm: js.UndefOr[String] = js.native
  var acmpca: js.UndefOr[String] = js.native
  var amplify: js.UndefOr[String] = js.native
  var apigateway: js.UndefOr[String] = js.native
  var applicationautoscaling: js.UndefOr[String] = js.native
  var applicationinsights: js.UndefOr[String] = js.native
  var appmesh: js.UndefOr[String] = js.native
  var appstream: js.UndefOr[String] = js.native
  var appsync: js.UndefOr[String] = js.native
  var athena: js.UndefOr[String] = js.native
  var autoscaling: js.UndefOr[String] = js.native
  var autoscalingplans: js.UndefOr[String] = js.native
  var backup: js.UndefOr[String] = js.native
  var batch: js.UndefOr[String] = js.native
  var budgets: js.UndefOr[String] = js.native
  var cloud9: js.UndefOr[String] = js.native
  var cloudformation: js.UndefOr[String] = js.native
  var cloudfront: js.UndefOr[String] = js.native
  var cloudhsm: js.UndefOr[String] = js.native
  var cloudsearch: js.UndefOr[String] = js.native
  var cloudtrail: js.UndefOr[String] = js.native
  var cloudwatch: js.UndefOr[String] = js.native
  var cloudwatchevents: js.UndefOr[String] = js.native
  var cloudwatchlogs: js.UndefOr[String] = js.native
  var codebuild: js.UndefOr[String] = js.native
  var codecommit: js.UndefOr[String] = js.native
  var codedeploy: js.UndefOr[String] = js.native
  var codepipeline: js.UndefOr[String] = js.native
  var cognitoidentity: js.UndefOr[String] = js.native
  var cognitoidp: js.UndefOr[String] = js.native
  var configservice: js.UndefOr[String] = js.native
  var cur: js.UndefOr[String] = js.native
  var dataexchange: js.UndefOr[String] = js.native
  var datapipeline: js.UndefOr[String] = js.native
  var datasync: js.UndefOr[String] = js.native
  var dax: js.UndefOr[String] = js.native
  var devicefarm: js.UndefOr[String] = js.native
  var directconnect: js.UndefOr[String] = js.native
  var dlm: js.UndefOr[String] = js.native
  var dms: js.UndefOr[String] = js.native
  var docdb: js.UndefOr[String] = js.native
  var ds: js.UndefOr[String] = js.native
  var dynamodb: js.UndefOr[String] = js.native
  var ec2: js.UndefOr[String] = js.native
  var ecr: js.UndefOr[String] = js.native
  var ecs: js.UndefOr[String] = js.native
  var efs: js.UndefOr[String] = js.native
  var eks: js.UndefOr[String] = js.native
  var elasticache: js.UndefOr[String] = js.native
  var elasticbeanstalk: js.UndefOr[String] = js.native
  var elastictranscoder: js.UndefOr[String] = js.native
  var elb: js.UndefOr[String] = js.native
  var emr: js.UndefOr[String] = js.native
  var es: js.UndefOr[String] = js.native
  var firehose: js.UndefOr[String] = js.native
  var fms: js.UndefOr[String] = js.native
  var forecast: js.UndefOr[String] = js.native
  var fsx: js.UndefOr[String] = js.native
  var gamelift: js.UndefOr[String] = js.native
  var glacier: js.UndefOr[String] = js.native
  var globalaccelerator: js.UndefOr[String] = js.native
  var glue: js.UndefOr[String] = js.native
  var greengrass: js.UndefOr[String] = js.native
  var guardduty: js.UndefOr[String] = js.native
  var iam: js.UndefOr[String] = js.native
  var imagebuilder: js.UndefOr[String] = js.native
  var inspector: js.UndefOr[String] = js.native
  var iot: js.UndefOr[String] = js.native
  var iotanalytics: js.UndefOr[String] = js.native
  var iotevents: js.UndefOr[String] = js.native
  var kafka: js.UndefOr[String] = js.native
  var kinesis: js.UndefOr[String] = js.native
  var kinesisAnalytics: js.UndefOr[String] = js.native
  var kinesisanalytics: js.UndefOr[String] = js.native
  var kinesisvideo: js.UndefOr[String] = js.native
  var kms: js.UndefOr[String] = js.native
  var lakeformation: js.UndefOr[String] = js.native
  var lambda: js.UndefOr[String] = js.native
  var lexmodels: js.UndefOr[String] = js.native
  var licensemanager: js.UndefOr[String] = js.native
  var lightsail: js.UndefOr[String] = js.native
  var macie: js.UndefOr[String] = js.native
  var managedblockchain: js.UndefOr[String] = js.native
  var marketplacecatalog: js.UndefOr[String] = js.native
  var mediaconnect: js.UndefOr[String] = js.native
  var mediaconvert: js.UndefOr[String] = js.native
  var medialive: js.UndefOr[String] = js.native
  var mediapackage: js.UndefOr[String] = js.native
  var mediastore: js.UndefOr[String] = js.native
  var mediastoredata: js.UndefOr[String] = js.native
  var mq: js.UndefOr[String] = js.native
  var neptune: js.UndefOr[String] = js.native
  var opsworks: js.UndefOr[String] = js.native
  var organizations: js.UndefOr[String] = js.native
  var personalize: js.UndefOr[String] = js.native
  var pinpoint: js.UndefOr[String] = js.native
  var pricing: js.UndefOr[String] = js.native
  var qldb: js.UndefOr[String] = js.native
  var quicksight: js.UndefOr[String] = js.native
  var r53: js.UndefOr[String] = js.native
  var ram: js.UndefOr[String] = js.native
  var rds: js.UndefOr[String] = js.native
  var redshift: js.UndefOr[String] = js.native
  var resourcegroups: js.UndefOr[String] = js.native
  var route53: js.UndefOr[String] = js.native
  var route53resolver: js.UndefOr[String] = js.native
  var s3: js.UndefOr[String] = js.native
  var s3control: js.UndefOr[String] = js.native
  var sagemaker: js.UndefOr[String] = js.native
  var sdb: js.UndefOr[String] = js.native
  var secretsmanager: js.UndefOr[String] = js.native
  var securityhub: js.UndefOr[String] = js.native
  var serverlessrepo: js.UndefOr[String] = js.native
  var servicecatalog: js.UndefOr[String] = js.native
  var servicediscovery: js.UndefOr[String] = js.native
  var servicequotas: js.UndefOr[String] = js.native
  var ses: js.UndefOr[String] = js.native
  var shield: js.UndefOr[String] = js.native
  var sns: js.UndefOr[String] = js.native
  var sqs: js.UndefOr[String] = js.native
  var ssm: js.UndefOr[String] = js.native
  var stepfunctions: js.UndefOr[String] = js.native
  var storagegateway: js.UndefOr[String] = js.native
  var sts: js.UndefOr[String] = js.native
  var swf: js.UndefOr[String] = js.native
  var transfer: js.UndefOr[String] = js.native
  var waf: js.UndefOr[String] = js.native
  var wafregional: js.UndefOr[String] = js.native
  var wafv2: js.UndefOr[String] = js.native
  var worklink: js.UndefOr[String] = js.native
  var workmail: js.UndefOr[String] = js.native
  var workspaces: js.UndefOr[String] = js.native
  var xray: js.UndefOr[String] = js.native
}

object Accessanalyzer {
  @scala.inline
  def apply(
    accessanalyzer: String = null,
    acm: String = null,
    acmpca: String = null,
    amplify: String = null,
    apigateway: String = null,
    applicationautoscaling: String = null,
    applicationinsights: String = null,
    appmesh: String = null,
    appstream: String = null,
    appsync: String = null,
    athena: String = null,
    autoscaling: String = null,
    autoscalingplans: String = null,
    backup: String = null,
    batch: String = null,
    budgets: String = null,
    cloud9: String = null,
    cloudformation: String = null,
    cloudfront: String = null,
    cloudhsm: String = null,
    cloudsearch: String = null,
    cloudtrail: String = null,
    cloudwatch: String = null,
    cloudwatchevents: String = null,
    cloudwatchlogs: String = null,
    codebuild: String = null,
    codecommit: String = null,
    codedeploy: String = null,
    codepipeline: String = null,
    cognitoidentity: String = null,
    cognitoidp: String = null,
    configservice: String = null,
    cur: String = null,
    dataexchange: String = null,
    datapipeline: String = null,
    datasync: String = null,
    dax: String = null,
    devicefarm: String = null,
    directconnect: String = null,
    dlm: String = null,
    dms: String = null,
    docdb: String = null,
    ds: String = null,
    dynamodb: String = null,
    ec2: String = null,
    ecr: String = null,
    ecs: String = null,
    efs: String = null,
    eks: String = null,
    elasticache: String = null,
    elasticbeanstalk: String = null,
    elastictranscoder: String = null,
    elb: String = null,
    emr: String = null,
    es: String = null,
    firehose: String = null,
    fms: String = null,
    forecast: String = null,
    fsx: String = null,
    gamelift: String = null,
    glacier: String = null,
    globalaccelerator: String = null,
    glue: String = null,
    greengrass: String = null,
    guardduty: String = null,
    iam: String = null,
    imagebuilder: String = null,
    inspector: String = null,
    iot: String = null,
    iotanalytics: String = null,
    iotevents: String = null,
    kafka: String = null,
    kinesis: String = null,
    kinesisAnalytics: String = null,
    kinesisanalytics: String = null,
    kinesisvideo: String = null,
    kms: String = null,
    lakeformation: String = null,
    lambda: String = null,
    lexmodels: String = null,
    licensemanager: String = null,
    lightsail: String = null,
    macie: String = null,
    managedblockchain: String = null,
    marketplacecatalog: String = null,
    mediaconnect: String = null,
    mediaconvert: String = null,
    medialive: String = null,
    mediapackage: String = null,
    mediastore: String = null,
    mediastoredata: String = null,
    mq: String = null,
    neptune: String = null,
    opsworks: String = null,
    organizations: String = null,
    personalize: String = null,
    pinpoint: String = null,
    pricing: String = null,
    qldb: String = null,
    quicksight: String = null,
    r53: String = null,
    ram: String = null,
    rds: String = null,
    redshift: String = null,
    resourcegroups: String = null,
    route53: String = null,
    route53resolver: String = null,
    s3: String = null,
    s3control: String = null,
    sagemaker: String = null,
    sdb: String = null,
    secretsmanager: String = null,
    securityhub: String = null,
    serverlessrepo: String = null,
    servicecatalog: String = null,
    servicediscovery: String = null,
    servicequotas: String = null,
    ses: String = null,
    shield: String = null,
    sns: String = null,
    sqs: String = null,
    ssm: String = null,
    stepfunctions: String = null,
    storagegateway: String = null,
    sts: String = null,
    swf: String = null,
    transfer: String = null,
    waf: String = null,
    wafregional: String = null,
    wafv2: String = null,
    worklink: String = null,
    workmail: String = null,
    workspaces: String = null,
    xray: String = null
  ): Accessanalyzer = {
    val __obj = js.Dynamic.literal()
    if (accessanalyzer != null) __obj.updateDynamic("accessanalyzer")(accessanalyzer.asInstanceOf[js.Any])
    if (acm != null) __obj.updateDynamic("acm")(acm.asInstanceOf[js.Any])
    if (acmpca != null) __obj.updateDynamic("acmpca")(acmpca.asInstanceOf[js.Any])
    if (amplify != null) __obj.updateDynamic("amplify")(amplify.asInstanceOf[js.Any])
    if (apigateway != null) __obj.updateDynamic("apigateway")(apigateway.asInstanceOf[js.Any])
    if (applicationautoscaling != null) __obj.updateDynamic("applicationautoscaling")(applicationautoscaling.asInstanceOf[js.Any])
    if (applicationinsights != null) __obj.updateDynamic("applicationinsights")(applicationinsights.asInstanceOf[js.Any])
    if (appmesh != null) __obj.updateDynamic("appmesh")(appmesh.asInstanceOf[js.Any])
    if (appstream != null) __obj.updateDynamic("appstream")(appstream.asInstanceOf[js.Any])
    if (appsync != null) __obj.updateDynamic("appsync")(appsync.asInstanceOf[js.Any])
    if (athena != null) __obj.updateDynamic("athena")(athena.asInstanceOf[js.Any])
    if (autoscaling != null) __obj.updateDynamic("autoscaling")(autoscaling.asInstanceOf[js.Any])
    if (autoscalingplans != null) __obj.updateDynamic("autoscalingplans")(autoscalingplans.asInstanceOf[js.Any])
    if (backup != null) __obj.updateDynamic("backup")(backup.asInstanceOf[js.Any])
    if (batch != null) __obj.updateDynamic("batch")(batch.asInstanceOf[js.Any])
    if (budgets != null) __obj.updateDynamic("budgets")(budgets.asInstanceOf[js.Any])
    if (cloud9 != null) __obj.updateDynamic("cloud9")(cloud9.asInstanceOf[js.Any])
    if (cloudformation != null) __obj.updateDynamic("cloudformation")(cloudformation.asInstanceOf[js.Any])
    if (cloudfront != null) __obj.updateDynamic("cloudfront")(cloudfront.asInstanceOf[js.Any])
    if (cloudhsm != null) __obj.updateDynamic("cloudhsm")(cloudhsm.asInstanceOf[js.Any])
    if (cloudsearch != null) __obj.updateDynamic("cloudsearch")(cloudsearch.asInstanceOf[js.Any])
    if (cloudtrail != null) __obj.updateDynamic("cloudtrail")(cloudtrail.asInstanceOf[js.Any])
    if (cloudwatch != null) __obj.updateDynamic("cloudwatch")(cloudwatch.asInstanceOf[js.Any])
    if (cloudwatchevents != null) __obj.updateDynamic("cloudwatchevents")(cloudwatchevents.asInstanceOf[js.Any])
    if (cloudwatchlogs != null) __obj.updateDynamic("cloudwatchlogs")(cloudwatchlogs.asInstanceOf[js.Any])
    if (codebuild != null) __obj.updateDynamic("codebuild")(codebuild.asInstanceOf[js.Any])
    if (codecommit != null) __obj.updateDynamic("codecommit")(codecommit.asInstanceOf[js.Any])
    if (codedeploy != null) __obj.updateDynamic("codedeploy")(codedeploy.asInstanceOf[js.Any])
    if (codepipeline != null) __obj.updateDynamic("codepipeline")(codepipeline.asInstanceOf[js.Any])
    if (cognitoidentity != null) __obj.updateDynamic("cognitoidentity")(cognitoidentity.asInstanceOf[js.Any])
    if (cognitoidp != null) __obj.updateDynamic("cognitoidp")(cognitoidp.asInstanceOf[js.Any])
    if (configservice != null) __obj.updateDynamic("configservice")(configservice.asInstanceOf[js.Any])
    if (cur != null) __obj.updateDynamic("cur")(cur.asInstanceOf[js.Any])
    if (dataexchange != null) __obj.updateDynamic("dataexchange")(dataexchange.asInstanceOf[js.Any])
    if (datapipeline != null) __obj.updateDynamic("datapipeline")(datapipeline.asInstanceOf[js.Any])
    if (datasync != null) __obj.updateDynamic("datasync")(datasync.asInstanceOf[js.Any])
    if (dax != null) __obj.updateDynamic("dax")(dax.asInstanceOf[js.Any])
    if (devicefarm != null) __obj.updateDynamic("devicefarm")(devicefarm.asInstanceOf[js.Any])
    if (directconnect != null) __obj.updateDynamic("directconnect")(directconnect.asInstanceOf[js.Any])
    if (dlm != null) __obj.updateDynamic("dlm")(dlm.asInstanceOf[js.Any])
    if (dms != null) __obj.updateDynamic("dms")(dms.asInstanceOf[js.Any])
    if (docdb != null) __obj.updateDynamic("docdb")(docdb.asInstanceOf[js.Any])
    if (ds != null) __obj.updateDynamic("ds")(ds.asInstanceOf[js.Any])
    if (dynamodb != null) __obj.updateDynamic("dynamodb")(dynamodb.asInstanceOf[js.Any])
    if (ec2 != null) __obj.updateDynamic("ec2")(ec2.asInstanceOf[js.Any])
    if (ecr != null) __obj.updateDynamic("ecr")(ecr.asInstanceOf[js.Any])
    if (ecs != null) __obj.updateDynamic("ecs")(ecs.asInstanceOf[js.Any])
    if (efs != null) __obj.updateDynamic("efs")(efs.asInstanceOf[js.Any])
    if (eks != null) __obj.updateDynamic("eks")(eks.asInstanceOf[js.Any])
    if (elasticache != null) __obj.updateDynamic("elasticache")(elasticache.asInstanceOf[js.Any])
    if (elasticbeanstalk != null) __obj.updateDynamic("elasticbeanstalk")(elasticbeanstalk.asInstanceOf[js.Any])
    if (elastictranscoder != null) __obj.updateDynamic("elastictranscoder")(elastictranscoder.asInstanceOf[js.Any])
    if (elb != null) __obj.updateDynamic("elb")(elb.asInstanceOf[js.Any])
    if (emr != null) __obj.updateDynamic("emr")(emr.asInstanceOf[js.Any])
    if (es != null) __obj.updateDynamic("es")(es.asInstanceOf[js.Any])
    if (firehose != null) __obj.updateDynamic("firehose")(firehose.asInstanceOf[js.Any])
    if (fms != null) __obj.updateDynamic("fms")(fms.asInstanceOf[js.Any])
    if (forecast != null) __obj.updateDynamic("forecast")(forecast.asInstanceOf[js.Any])
    if (fsx != null) __obj.updateDynamic("fsx")(fsx.asInstanceOf[js.Any])
    if (gamelift != null) __obj.updateDynamic("gamelift")(gamelift.asInstanceOf[js.Any])
    if (glacier != null) __obj.updateDynamic("glacier")(glacier.asInstanceOf[js.Any])
    if (globalaccelerator != null) __obj.updateDynamic("globalaccelerator")(globalaccelerator.asInstanceOf[js.Any])
    if (glue != null) __obj.updateDynamic("glue")(glue.asInstanceOf[js.Any])
    if (greengrass != null) __obj.updateDynamic("greengrass")(greengrass.asInstanceOf[js.Any])
    if (guardduty != null) __obj.updateDynamic("guardduty")(guardduty.asInstanceOf[js.Any])
    if (iam != null) __obj.updateDynamic("iam")(iam.asInstanceOf[js.Any])
    if (imagebuilder != null) __obj.updateDynamic("imagebuilder")(imagebuilder.asInstanceOf[js.Any])
    if (inspector != null) __obj.updateDynamic("inspector")(inspector.asInstanceOf[js.Any])
    if (iot != null) __obj.updateDynamic("iot")(iot.asInstanceOf[js.Any])
    if (iotanalytics != null) __obj.updateDynamic("iotanalytics")(iotanalytics.asInstanceOf[js.Any])
    if (iotevents != null) __obj.updateDynamic("iotevents")(iotevents.asInstanceOf[js.Any])
    if (kafka != null) __obj.updateDynamic("kafka")(kafka.asInstanceOf[js.Any])
    if (kinesis != null) __obj.updateDynamic("kinesis")(kinesis.asInstanceOf[js.Any])
    if (kinesisAnalytics != null) __obj.updateDynamic("kinesisAnalytics")(kinesisAnalytics.asInstanceOf[js.Any])
    if (kinesisanalytics != null) __obj.updateDynamic("kinesisanalytics")(kinesisanalytics.asInstanceOf[js.Any])
    if (kinesisvideo != null) __obj.updateDynamic("kinesisvideo")(kinesisvideo.asInstanceOf[js.Any])
    if (kms != null) __obj.updateDynamic("kms")(kms.asInstanceOf[js.Any])
    if (lakeformation != null) __obj.updateDynamic("lakeformation")(lakeformation.asInstanceOf[js.Any])
    if (lambda != null) __obj.updateDynamic("lambda")(lambda.asInstanceOf[js.Any])
    if (lexmodels != null) __obj.updateDynamic("lexmodels")(lexmodels.asInstanceOf[js.Any])
    if (licensemanager != null) __obj.updateDynamic("licensemanager")(licensemanager.asInstanceOf[js.Any])
    if (lightsail != null) __obj.updateDynamic("lightsail")(lightsail.asInstanceOf[js.Any])
    if (macie != null) __obj.updateDynamic("macie")(macie.asInstanceOf[js.Any])
    if (managedblockchain != null) __obj.updateDynamic("managedblockchain")(managedblockchain.asInstanceOf[js.Any])
    if (marketplacecatalog != null) __obj.updateDynamic("marketplacecatalog")(marketplacecatalog.asInstanceOf[js.Any])
    if (mediaconnect != null) __obj.updateDynamic("mediaconnect")(mediaconnect.asInstanceOf[js.Any])
    if (mediaconvert != null) __obj.updateDynamic("mediaconvert")(mediaconvert.asInstanceOf[js.Any])
    if (medialive != null) __obj.updateDynamic("medialive")(medialive.asInstanceOf[js.Any])
    if (mediapackage != null) __obj.updateDynamic("mediapackage")(mediapackage.asInstanceOf[js.Any])
    if (mediastore != null) __obj.updateDynamic("mediastore")(mediastore.asInstanceOf[js.Any])
    if (mediastoredata != null) __obj.updateDynamic("mediastoredata")(mediastoredata.asInstanceOf[js.Any])
    if (mq != null) __obj.updateDynamic("mq")(mq.asInstanceOf[js.Any])
    if (neptune != null) __obj.updateDynamic("neptune")(neptune.asInstanceOf[js.Any])
    if (opsworks != null) __obj.updateDynamic("opsworks")(opsworks.asInstanceOf[js.Any])
    if (organizations != null) __obj.updateDynamic("organizations")(organizations.asInstanceOf[js.Any])
    if (personalize != null) __obj.updateDynamic("personalize")(personalize.asInstanceOf[js.Any])
    if (pinpoint != null) __obj.updateDynamic("pinpoint")(pinpoint.asInstanceOf[js.Any])
    if (pricing != null) __obj.updateDynamic("pricing")(pricing.asInstanceOf[js.Any])
    if (qldb != null) __obj.updateDynamic("qldb")(qldb.asInstanceOf[js.Any])
    if (quicksight != null) __obj.updateDynamic("quicksight")(quicksight.asInstanceOf[js.Any])
    if (r53 != null) __obj.updateDynamic("r53")(r53.asInstanceOf[js.Any])
    if (ram != null) __obj.updateDynamic("ram")(ram.asInstanceOf[js.Any])
    if (rds != null) __obj.updateDynamic("rds")(rds.asInstanceOf[js.Any])
    if (redshift != null) __obj.updateDynamic("redshift")(redshift.asInstanceOf[js.Any])
    if (resourcegroups != null) __obj.updateDynamic("resourcegroups")(resourcegroups.asInstanceOf[js.Any])
    if (route53 != null) __obj.updateDynamic("route53")(route53.asInstanceOf[js.Any])
    if (route53resolver != null) __obj.updateDynamic("route53resolver")(route53resolver.asInstanceOf[js.Any])
    if (s3 != null) __obj.updateDynamic("s3")(s3.asInstanceOf[js.Any])
    if (s3control != null) __obj.updateDynamic("s3control")(s3control.asInstanceOf[js.Any])
    if (sagemaker != null) __obj.updateDynamic("sagemaker")(sagemaker.asInstanceOf[js.Any])
    if (sdb != null) __obj.updateDynamic("sdb")(sdb.asInstanceOf[js.Any])
    if (secretsmanager != null) __obj.updateDynamic("secretsmanager")(secretsmanager.asInstanceOf[js.Any])
    if (securityhub != null) __obj.updateDynamic("securityhub")(securityhub.asInstanceOf[js.Any])
    if (serverlessrepo != null) __obj.updateDynamic("serverlessrepo")(serverlessrepo.asInstanceOf[js.Any])
    if (servicecatalog != null) __obj.updateDynamic("servicecatalog")(servicecatalog.asInstanceOf[js.Any])
    if (servicediscovery != null) __obj.updateDynamic("servicediscovery")(servicediscovery.asInstanceOf[js.Any])
    if (servicequotas != null) __obj.updateDynamic("servicequotas")(servicequotas.asInstanceOf[js.Any])
    if (ses != null) __obj.updateDynamic("ses")(ses.asInstanceOf[js.Any])
    if (shield != null) __obj.updateDynamic("shield")(shield.asInstanceOf[js.Any])
    if (sns != null) __obj.updateDynamic("sns")(sns.asInstanceOf[js.Any])
    if (sqs != null) __obj.updateDynamic("sqs")(sqs.asInstanceOf[js.Any])
    if (ssm != null) __obj.updateDynamic("ssm")(ssm.asInstanceOf[js.Any])
    if (stepfunctions != null) __obj.updateDynamic("stepfunctions")(stepfunctions.asInstanceOf[js.Any])
    if (storagegateway != null) __obj.updateDynamic("storagegateway")(storagegateway.asInstanceOf[js.Any])
    if (sts != null) __obj.updateDynamic("sts")(sts.asInstanceOf[js.Any])
    if (swf != null) __obj.updateDynamic("swf")(swf.asInstanceOf[js.Any])
    if (transfer != null) __obj.updateDynamic("transfer")(transfer.asInstanceOf[js.Any])
    if (waf != null) __obj.updateDynamic("waf")(waf.asInstanceOf[js.Any])
    if (wafregional != null) __obj.updateDynamic("wafregional")(wafregional.asInstanceOf[js.Any])
    if (wafv2 != null) __obj.updateDynamic("wafv2")(wafv2.asInstanceOf[js.Any])
    if (worklink != null) __obj.updateDynamic("worklink")(worklink.asInstanceOf[js.Any])
    if (workmail != null) __obj.updateDynamic("workmail")(workmail.asInstanceOf[js.Any])
    if (workspaces != null) __obj.updateDynamic("workspaces")(workspaces.asInstanceOf[js.Any])
    if (xray != null) __obj.updateDynamic("xray")(xray.asInstanceOf[js.Any])
    __obj.asInstanceOf[Accessanalyzer]
  }
}

