package typings.atAwsDashSdkClientDashCodecommitDashNode

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("@aws-sdk/client-codecommit-node/types/MergePullRequestByFastForwardExceptionsUnion", JSImport.Namespace)
@js.native
object typesMergePullRequestByFastForwardExceptionsUnionMod extends js.Object {
  /* Rewritten from type alias, can be one of: 
    - typings.atAwsDashSdkClientDashCodecommitDashNode.typesManualMergeRequiredExceptionMod.ManualMergeRequiredException
    - typings.atAwsDashSdkClientDashCodecommitDashNode.typesPullRequestAlreadyClosedExceptionMod.PullRequestAlreadyClosedException
    - typings.atAwsDashSdkClientDashCodecommitDashNode.typesPullRequestDoesNotExistExceptionMod.PullRequestDoesNotExistException
    - typings.atAwsDashSdkClientDashCodecommitDashNode.typesInvalidPullRequestIdExceptionMod.InvalidPullRequestIdException
    - typings.atAwsDashSdkClientDashCodecommitDashNode.typesPullRequestIdRequiredExceptionMod.PullRequestIdRequiredException
    - typings.atAwsDashSdkClientDashCodecommitDashNode.typesTipOfSourceReferenceIsDifferentExceptionMod.TipOfSourceReferenceIsDifferentException
    - typings.atAwsDashSdkClientDashCodecommitDashNode.typesReferenceDoesNotExistExceptionMod.ReferenceDoesNotExistException
    - typings.atAwsDashSdkClientDashCodecommitDashNode.typesInvalidCommitIdExceptionMod.InvalidCommitIdException
    - typings.atAwsDashSdkClientDashCodecommitDashNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
    - typings.atAwsDashSdkClientDashCodecommitDashNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
    - typings.atAwsDashSdkClientDashCodecommitDashNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
    - typings.atAwsDashSdkClientDashCodecommitDashNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
    - typings.atAwsDashSdkClientDashCodecommitDashNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
    - typings.atAwsDashSdkClientDashCodecommitDashNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
    - typings.atAwsDashSdkClientDashCodecommitDashNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
    - typings.atAwsDashSdkClientDashCodecommitDashNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
  */
  trait MergePullRequestByFastForwardExceptionsUnion extends js.Object
  
}

