package typings
package shopifyDashPrimeLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object distEnumsAuthUnderscoreScopeMod {
  type AuthScope = shopifyDashPrimeLib.shopifyDashPrimeLibStrings.read_content | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.write_content | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.read_themes | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.write_themes | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.read_products | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.write_products | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.read_customers | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.write_customers | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.read_orders | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.write_orders | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.read_script_tags | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.write_script_tags | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.read_fulfillments | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.write_fulfillments | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.read_shipping | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.write_shipping | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.read_analytics | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.read_users | shopifyDashPrimeLib.shopifyDashPrimeLibStrings.write_users | java.lang.String
}
