package typings
package reactDashSyntaxDashHighlighterLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait reactDashSyntaxDashHighlighterLibProps {
  @scala.inline
  def DefaultDashHighlightProps: reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps.type = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  type DefaultDashHighlightProps = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  @scala.inline
  def LightProps: reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps.type = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  type LightProps = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  @scala.inline
  def LightAsyncProps: reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps.type = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  type LightAsyncProps = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  @scala.inline
  def LightDashAsyncProps: reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps.type = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  type LightDashAsyncProps = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  @scala.inline
  def PrismProps: reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps.type = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  type PrismProps = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  @scala.inline
  def PrismAsyncProps: reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps.type = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  type PrismAsyncProps = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  @scala.inline
  def PrismAsyncLightProps: reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps.type = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  type PrismAsyncLightProps = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  @scala.inline
  def PrismDashAsyncProps: reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps.type = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  type PrismDashAsyncProps = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  @scala.inline
  def PrismDashAsyncDashLightProps: reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps.type = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  type PrismDashAsyncDashLightProps = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  @scala.inline
  def PrismDashLightProps: reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps.type = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  type PrismDashLightProps = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  @scala.inline
  def PrismLightProps: reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps.type = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  type PrismLightProps = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  @scala.inline
  def ReactDashSyntaxDashHighlighterProps: reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps.type = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
  type ReactDashSyntaxDashHighlighterProps = reactDashSyntaxDashHighlighterLib.reactDashSyntaxDashHighlighterMod.SyntaxHighlighterProps
}

