package typings.styledComponents

import typings.react.mod.ComponentClass
import typings.react.mod.ComponentState
import typings.react.mod.FunctionComponent
import typings.std.ReturnType
import typings.styledComponents.nativeDistTypesMod.ExoticComponentWithDisplayName
import typings.styledComponents.nativeDistTypesMod.IStyledComponentFactory
import typings.styledComponents.nativeDistTypesMod.RuleSet
import typings.styledComponents.nativeDistTypesMod.StyledOptions
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

object nativeDistModelsStyledComponentMod {
  
  @JSImport("styled-components/native/dist/models/StyledComponent", JSImport.Namespace)
  @js.native
  val ^ : js.Any = js.native
  
  @scala.annotation.targetName("default_feMorphology_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feMorphology", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feMorphology", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feMorphology", OuterProps, Statics]]]
  @scala.annotation.targetName("default_line_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "line", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "line", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "line", OuterProps, Statics]]]
  @scala.annotation.targetName("default_i_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "i", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "i", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "i", OuterProps, Statics]]]
  @scala.annotation.targetName("default_a_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "a", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "a", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "a", OuterProps, Statics]]]
  @scala.annotation.targetName("default_sup_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "sup", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "sup", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "sup", OuterProps, Statics]]]
  @scala.annotation.targetName("default_rt_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "rt", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "rt", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "rt", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feFuncB_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feFuncB", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feFuncB", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feFuncB", OuterProps, Statics]]]
  @scala.annotation.targetName("default_bdi_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "bdi", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "bdi", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "bdi", OuterProps, Statics]]]
  @scala.annotation.targetName("default_animateTransform_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "animateTransform", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "animateTransform", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "animateTransform", OuterProps, Statics]]]
  @scala.annotation.targetName("default_b_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "b", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "b", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "b", OuterProps, Statics]]]
  @scala.annotation.targetName("default_ul_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "ul", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "ul", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "ul", OuterProps, Statics]]]
  @scala.annotation.targetName("default_samp_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "samp", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "samp", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "samp", OuterProps, Statics]]]
  @scala.annotation.targetName("default_script_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "script", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "script", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "script", OuterProps, Statics]]]
  @scala.annotation.targetName("default_symbol_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "symbol", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "symbol", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "symbol", OuterProps, Statics]]]
  @scala.annotation.targetName("default_optgroup_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "optgroup", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "optgroup", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "optgroup", OuterProps, Statics]]]
  @scala.annotation.targetName("default_h2_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "h2", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "h2", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "h2", OuterProps, Statics]]]
  @scala.annotation.targetName("default_iframe_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "iframe", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "iframe", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "iframe", OuterProps, Statics]]]
  @scala.annotation.targetName("default_figcaption_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "figcaption", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "figcaption", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "figcaption", OuterProps, Statics]]]
  @scala.annotation.targetName("default_video_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "video", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "video", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "video", OuterProps, Statics]]]
  @scala.annotation.targetName("default_label_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "label", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "label", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "label", OuterProps, Statics]]]
  @scala.annotation.targetName("default_radialGradient_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "radialGradient", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "radialGradient", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "radialGradient", OuterProps, Statics]]]
  @scala.annotation.targetName("default_table_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "table", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "table", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "table", OuterProps, Statics]]]
  @scala.annotation.targetName("default_polyline_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "polyline", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "polyline", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "polyline", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feDropShadow_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feDropShadow", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feDropShadow", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feDropShadow", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feTurbulence_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feTurbulence", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feTurbulence", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feTurbulence", OuterProps, Statics]]]
  @scala.annotation.targetName("default_mask_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "mask", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "mask", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "mask", OuterProps, Statics]]]
  @scala.annotation.targetName("default_switch_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "switch", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "switch", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "switch", OuterProps, Statics]]]
  @scala.annotation.targetName("default_input_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "input", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "input", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "input", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feFuncR_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feFuncR", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feFuncR", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feFuncR", OuterProps, Statics]]]
  @scala.annotation.targetName("default_abbr_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "abbr", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "abbr", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "abbr", OuterProps, Statics]]]
  @scala.annotation.targetName("default_h3_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "h3", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "h3", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "h3", OuterProps, Statics]]]
  @scala.annotation.targetName("default_kbd_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "kbd", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "kbd", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "kbd", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feBlend_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feBlend", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feBlend", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feBlend", OuterProps, Statics]]]
  @scala.annotation.targetName("default_details_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "details", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "details", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "details", OuterProps, Statics]]]
  @scala.annotation.targetName("default_dd_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "dd", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "dd", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "dd", OuterProps, Statics]]]
  @scala.annotation.targetName("default_var_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "var", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "var", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "var", OuterProps, Statics]]]
  @scala.annotation.targetName("default_main_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "main", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "main", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "main", OuterProps, Statics]]]
  @scala.annotation.targetName("default_tfoot_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "tfoot", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "tfoot", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "tfoot", OuterProps, Statics]]]
  @scala.annotation.targetName("default_figure_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "figure", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "figure", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "figure", OuterProps, Statics]]]
  @scala.annotation.targetName("default_mark_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "mark", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "mark", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "mark", OuterProps, Statics]]]
  @scala.annotation.targetName("default_form_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "form", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "form", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "form", OuterProps, Statics]]]
  @scala.annotation.targetName("default_data_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "data", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "data", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "data", OuterProps, Statics]]]
  @scala.annotation.targetName("default_body_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "body", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "body", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "body", OuterProps, Statics]]]
  @scala.annotation.targetName("default_q_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "q", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "q", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "q", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feDisplacementMap_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feDisplacementMap", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feDisplacementMap", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feDisplacementMap", OuterProps, Statics]]]
  @scala.annotation.targetName("default_object_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "object", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "object", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "object", OuterProps, Statics]]]
  @scala.annotation.targetName("default_span_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "span", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "span", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "span", OuterProps, Statics]]]
  @scala.annotation.targetName("default_ol_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "ol", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "ol", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "ol", OuterProps, Statics]]]
  @scala.annotation.targetName("default_big_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "big", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "big", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "big", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feFuncG_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feFuncG", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feFuncG", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feFuncG", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feMerge_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feMerge", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feMerge", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feMerge", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feConvolveMatrix_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feConvolveMatrix", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feConvolveMatrix", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feConvolveMatrix", OuterProps, Statics]]]
  @scala.annotation.targetName("default_article_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "article", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "article", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "article", OuterProps, Statics]]]
  @scala.annotation.targetName("default_tr_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "tr", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "tr", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "tr", OuterProps, Statics]]]
  @scala.annotation.targetName("default_source_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "source", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "source", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "source", OuterProps, Statics]]]
  @scala.annotation.targetName("default_th_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "th", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "th", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "th", OuterProps, Statics]]]
  @scala.annotation.targetName("default_mpath_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "mpath", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "mpath", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "mpath", OuterProps, Statics]]]
  @scala.annotation.targetName("default_dfn_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "dfn", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "dfn", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "dfn", OuterProps, Statics]]]
  @scala.annotation.targetName("default_thead_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "thead", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "thead", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "thead", OuterProps, Statics]]]
  @scala.annotation.targetName("default_canvas_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "canvas", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "canvas", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "canvas", OuterProps, Statics]]]
  @scala.annotation.targetName("default_embed_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "embed", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "embed", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "embed", OuterProps, Statics]]]
  @scala.annotation.targetName("default_wbr_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "wbr", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "wbr", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "wbr", OuterProps, Statics]]]
  @scala.annotation.targetName("default_metadata_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "metadata", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "metadata", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "metadata", OuterProps, Statics]]]
  @scala.annotation.targetName("default_address_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "address", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "address", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "address", OuterProps, Statics]]]
  @scala.annotation.targetName("default_hr_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "hr", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "hr", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "hr", OuterProps, Statics]]]
  @scala.annotation.targetName("default_progress_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "progress", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "progress", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "progress", OuterProps, Statics]]]
  @scala.annotation.targetName("default_filter_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "filter", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "filter", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "filter", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feOffset_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feOffset", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feOffset", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feOffset", OuterProps, Statics]]]
  @scala.annotation.targetName("default_g_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "g", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "g", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "g", OuterProps, Statics]]]
  @scala.annotation.targetName("default_noscript_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "noscript", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "noscript", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "noscript", OuterProps, Statics]]]
  @scala.annotation.targetName("default_html_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "html", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "html", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "html", OuterProps, Statics]]]
  @scala.annotation.targetName("default_col_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "col", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "col", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "col", OuterProps, Statics]]]
  @scala.annotation.targetName("default_defs_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "defs", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "defs", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "defs", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feTile_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feTile", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feTile", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feTile", OuterProps, Statics]]]
  @scala.annotation.targetName("default_track_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "track", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "track", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "track", OuterProps, Statics]]]
  @scala.annotation.targetName("default_sub_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "sub", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "sub", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "sub", OuterProps, Statics]]]
  @scala.annotation.targetName("default_ruby_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "ruby", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "ruby", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "ruby", OuterProps, Statics]]]
  @scala.annotation.targetName("default_base_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "base", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "base", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "base", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feSpecularLighting_web")
  inline def default[OuterProps /* <: js.Object */, Statics](
    target: "feSpecularLighting",
    options: StyledOptions["web", OuterProps],
    rules: RuleSet[OuterProps]
  ): ReturnType[IStyledComponentFactory["web", "feSpecularLighting", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feSpecularLighting", OuterProps, Statics]]]
  @scala.annotation.targetName("default_footer_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "footer", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "footer", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "footer", OuterProps, Statics]]]
  @scala.annotation.targetName("default_noindex_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "noindex", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "noindex", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "noindex", OuterProps, Statics]]]
  @scala.annotation.targetName("default_fePointLight_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "fePointLight", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "fePointLight", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "fePointLight", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feMergeNode_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feMergeNode", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feMergeNode", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feMergeNode", OuterProps, Statics]]]
  @scala.annotation.targetName("default_clipPath_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "clipPath", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "clipPath", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "clipPath", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feColorMatrix_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feColorMatrix", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feColorMatrix", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feColorMatrix", OuterProps, Statics]]]
  @scala.annotation.targetName("default_animateMotion_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "animateMotion", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "animateMotion", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "animateMotion", OuterProps, Statics]]]
  @scala.annotation.targetName("default_output_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "output", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "output", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "output", OuterProps, Statics]]]
  @scala.annotation.targetName("default_bdo_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "bdo", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "bdo", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "bdo", OuterProps, Statics]]]
  @scala.annotation.targetName("default_template_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "template", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "template", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "template", OuterProps, Statics]]]
  @scala.annotation.targetName("default_tspan_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "tspan", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "tspan", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "tspan", OuterProps, Statics]]]
  @scala.annotation.targetName("default_image_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "image", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "image", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "image", OuterProps, Statics]]]
  @scala.annotation.targetName("default_small_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "small", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "small", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "small", OuterProps, Statics]]]
  @scala.annotation.targetName("default_datalist_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "datalist", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "datalist", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "datalist", OuterProps, Statics]]]
  @scala.annotation.targetName("default_s_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "s", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "s", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "s", OuterProps, Statics]]]
  @scala.annotation.targetName("default_param_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "param", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "param", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "param", OuterProps, Statics]]]
  @scala.annotation.targetName("default_path_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "path", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "path", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "path", OuterProps, Statics]]]
  @scala.annotation.targetName("default_cite_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "cite", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "cite", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "cite", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feImage_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feImage", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feImage", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feImage", OuterProps, Statics]]]
  @scala.annotation.targetName("default_rect_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "rect", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "rect", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "rect", OuterProps, Statics]]]
  @scala.annotation.targetName("default_keygen_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "keygen", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "keygen", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "keygen", OuterProps, Statics]]]
  @scala.annotation.targetName("default_caption_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "caption", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "caption", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "caption", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feGaussianBlur_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feGaussianBlur", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feGaussianBlur", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feGaussianBlur", OuterProps, Statics]]]
  @scala.annotation.targetName("default_tbody_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "tbody", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "tbody", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "tbody", OuterProps, Statics]]]
  @scala.annotation.targetName("default_u_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "u", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "u", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "u", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feComposite_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feComposite", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feComposite", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feComposite", OuterProps, Statics]]]
  @scala.annotation.targetName("default_linearGradient_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "linearGradient", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "linearGradient", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "linearGradient", OuterProps, Statics]]]
  @scala.annotation.targetName("default_pre_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "pre", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "pre", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "pre", OuterProps, Statics]]]
  @scala.annotation.targetName("default_h1_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "h1", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "h1", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "h1", OuterProps, Statics]]]
  @scala.annotation.targetName("default_animate_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "animate", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "animate", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "animate", OuterProps, Statics]]]
  @scala.annotation.targetName("default_dt_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "dt", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "dt", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "dt", OuterProps, Statics]]]
  @scala.annotation.targetName("default_menuitem_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "menuitem", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "menuitem", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "menuitem", OuterProps, Statics]]]
  @scala.annotation.targetName("default_legend_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "legend", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "legend", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "legend", OuterProps, Statics]]]
  @scala.annotation.targetName("default_title_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "title", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "title", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "title", OuterProps, Statics]]]
  @scala.annotation.targetName("default_h4_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "h4", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "h4", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "h4", OuterProps, Statics]]]
  @scala.annotation.targetName("default_use_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "use", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "use", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "use", OuterProps, Statics]]]
  @scala.annotation.targetName("default_picture_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "picture", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "picture", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "picture", OuterProps, Statics]]]
  @scala.annotation.targetName("default_h6_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "h6", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "h6", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "h6", OuterProps, Statics]]]
  @scala.annotation.targetName("default_polygon_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "polygon", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "polygon", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "polygon", OuterProps, Statics]]]
  @scala.annotation.targetName("default_button_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "button", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "button", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "button", OuterProps, Statics]]]
  @scala.annotation.targetName("default_textarea_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "textarea", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "textarea", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "textarea", OuterProps, Statics]]]
  @scala.annotation.targetName("default_colgroup_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "colgroup", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "colgroup", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "colgroup", OuterProps, Statics]]]
  @scala.annotation.targetName("default_desc_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "desc", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "desc", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "desc", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feDistantLight_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feDistantLight", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feDistantLight", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feDistantLight", OuterProps, Statics]]]
  @scala.annotation.targetName("default_pattern_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "pattern", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "pattern", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "pattern", OuterProps, Statics]]]
  @scala.annotation.targetName("default_slot_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "slot", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "slot", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "slot", OuterProps, Statics]]]
  @scala.annotation.targetName("default_nav_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "nav", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "nav", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "nav", OuterProps, Statics]]]
  @scala.annotation.targetName("default_ins_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "ins", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "ins", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "ins", OuterProps, Statics]]]
  @scala.annotation.targetName("default_textPath_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "textPath", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "textPath", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "textPath", OuterProps, Statics]]]
  @scala.annotation.targetName("default_audio_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "audio", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "audio", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "audio", OuterProps, Statics]]]
  @scala.annotation.targetName("default_img_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "img", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "img", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "img", OuterProps, Statics]]]
  @scala.annotation.targetName("default_area_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "area", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "area", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "area", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feFlood_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feFlood", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feFlood", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feFlood", OuterProps, Statics]]]
  @scala.annotation.targetName("default_marker_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "marker", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "marker", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "marker", OuterProps, Statics]]]
  @scala.annotation.targetName("default_hgroup_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "hgroup", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "hgroup", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "hgroup", OuterProps, Statics]]]
  @scala.annotation.targetName("default_view_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "view", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "view", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "view", OuterProps, Statics]]]
  @scala.annotation.targetName("default_text_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "text", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "text", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "text", OuterProps, Statics]]]
  @scala.annotation.targetName("default_br_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "br", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "br", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "br", OuterProps, Statics]]]
  @scala.annotation.targetName("default_td_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "td", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "td", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "td", OuterProps, Statics]]]
  @scala.annotation.targetName("default_option_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "option", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "option", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "option", OuterProps, Statics]]]
  @scala.annotation.targetName("default_map_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "map", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "map", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "map", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feDiffuseLighting_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feDiffuseLighting", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feDiffuseLighting", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feDiffuseLighting", OuterProps, Statics]]]
  @scala.annotation.targetName("default_del_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "del", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "del", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "del", OuterProps, Statics]]]
  @scala.annotation.targetName("default_summary_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "summary", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "summary", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "summary", OuterProps, Statics]]]
  @scala.annotation.targetName("default_time_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "time", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "time", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "time", OuterProps, Statics]]]
  @scala.annotation.targetName("default_circle_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "circle", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "circle", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "circle", OuterProps, Statics]]]
  @scala.annotation.targetName("default_head_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "head", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "head", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "head", OuterProps, Statics]]]
  @scala.annotation.targetName("default_aside_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "aside", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "aside", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "aside", OuterProps, Statics]]]
  @scala.annotation.targetName("default_select_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "select", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "select", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "select", OuterProps, Statics]]]
  @scala.annotation.targetName("default_svg_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "svg", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "svg", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "svg", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feComponentTransfer_web")
  inline def default[OuterProps /* <: js.Object */, Statics](
    target: "feComponentTransfer",
    options: StyledOptions["web", OuterProps],
    rules: RuleSet[OuterProps]
  ): ReturnType[IStyledComponentFactory["web", "feComponentTransfer", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feComponentTransfer", OuterProps, Statics]]]
  @scala.annotation.targetName("default_em_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "em", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "em", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "em", OuterProps, Statics]]]
  @scala.annotation.targetName("default_style_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "style", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "style", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "style", OuterProps, Statics]]]
  @scala.annotation.targetName("default_h5_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "h5", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "h5", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "h5", OuterProps, Statics]]]
  @scala.annotation.targetName("default_rp_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "rp", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "rp", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "rp", OuterProps, Statics]]]
  @scala.annotation.targetName("default_meter_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "meter", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "meter", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "meter", OuterProps, Statics]]]
  @scala.annotation.targetName("default_blockquote_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "blockquote", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "blockquote", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "blockquote", OuterProps, Statics]]]
  @scala.annotation.targetName("default_link_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "link", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "link", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "link", OuterProps, Statics]]]
  @scala.annotation.targetName("default_section_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "section", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "section", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "section", OuterProps, Statics]]]
  @scala.annotation.targetName("default_div_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "div", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "div", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "div", OuterProps, Statics]]]
  @scala.annotation.targetName("default_li_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "li", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "li", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "li", OuterProps, Statics]]]
  @scala.annotation.targetName("default_menu_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "menu", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "menu", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "menu", OuterProps, Statics]]]
  @scala.annotation.targetName("default_dialog_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "dialog", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "dialog", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "dialog", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feSpotLight_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feSpotLight", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feSpotLight", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feSpotLight", OuterProps, Statics]]]
  @scala.annotation.targetName("default_dl_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "dl", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "dl", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "dl", OuterProps, Statics]]]
  @scala.annotation.targetName("default_header_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "header", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "header", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "header", OuterProps, Statics]]]
  @scala.annotation.targetName("default_meta_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "meta", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "meta", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "meta", OuterProps, Statics]]]
  @scala.annotation.targetName("default_code_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "code", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "code", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "code", OuterProps, Statics]]]
  @scala.annotation.targetName("default_stop_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "stop", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "stop", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "stop", OuterProps, Statics]]]
  @scala.annotation.targetName("default_p_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "p", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "p", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "p", OuterProps, Statics]]]
  @scala.annotation.targetName("default_webview_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "webview", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "webview", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "webview", OuterProps, Statics]]]
  @scala.annotation.targetName("default_foreignObject_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "foreignObject", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "foreignObject", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "foreignObject", OuterProps, Statics]]]
  @scala.annotation.targetName("default_feFuncA_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "feFuncA", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "feFuncA", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "feFuncA", OuterProps, Statics]]]
  @scala.annotation.targetName("default_fieldset_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "fieldset", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "fieldset", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "fieldset", OuterProps, Statics]]]
  @scala.annotation.targetName("default_strong_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "strong", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "strong", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "strong", OuterProps, Statics]]]
  @scala.annotation.targetName("default_ellipse_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: "ellipse", options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", "ellipse", OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", "ellipse", OuterProps, Statics]]]
  @scala.annotation.targetName("default_web")
  inline def default[OuterProps /* <: js.Object */, Statics](target: String, options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", String, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", String, OuterProps, Statics]]]
  @scala.annotation.targetName("default_web")
  inline def default[Target /* <: ExoticComponentWithDisplayName[Any] | (ComponentClass[Any, ComponentState]) | FunctionComponent[Any] */, OuterProps /* <: js.Object */, Statics](target: Target, options: StyledOptions["web", OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory["web", Target, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory["web", Target, OuterProps, Statics]]]
}
