package typings
package csstypeLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object csstypeMod {
  type AlignContentProperty = _AlignContentProperty | java.lang.String
  type AlignItemsProperty = _AlignItemsProperty | java.lang.String
  type AlignSelfProperty = _AlignSelfProperty | java.lang.String
  type AnimationDirectionProperty = _AnimationDirectionProperty | java.lang.String
  type AnimationFillModeProperty = _AnimationFillModeProperty | java.lang.String
  type AnimationIterationCountProperty = _AnimationIterationCountProperty | java.lang.String | scala.Double
  type AnimationNameProperty = _AnimationNameProperty | java.lang.String
  type AnimationPlayStateProperty = _AnimationPlayStateProperty | java.lang.String
  type AnimationProperty = _AnimationProperty | java.lang.String
  type AnimationTimingFunctionProperty = _AnimationTimingFunctionProperty | java.lang.String
  type BackdropFilterProperty = _BackdropFilterProperty | java.lang.String
  type BackgroundAttachmentProperty = _BackgroundAttachmentProperty | java.lang.String
  type BackgroundBlendModeProperty = _BackgroundBlendModeProperty | java.lang.String
  type BackgroundClipProperty = _BackgroundClipProperty | java.lang.String
  type BackgroundImageProperty = _BackgroundImageProperty | java.lang.String
  type BackgroundOriginProperty = _BackgroundOriginProperty | java.lang.String
  type BackgroundPositionProperty[TLength] = _BackgroundPositionProperty[TLength] | java.lang.String
  type BackgroundPositionXProperty[TLength] = _BackgroundPositionXProperty[TLength] | TLength | java.lang.String
  type BackgroundPositionYProperty[TLength] = _BackgroundPositionYProperty[TLength] | TLength | java.lang.String
  type BackgroundProperty[TLength] = _BackgroundProperty[TLength] | java.lang.String
  type BackgroundRepeatProperty = _BackgroundRepeatProperty | java.lang.String
  type BackgroundSizeProperty[TLength] = _BackgroundSizeProperty[TLength] | java.lang.String
  type BaselineShiftProperty[TLength] = _BaselineShiftProperty[TLength] | TLength | java.lang.String
  type BlockOverflowProperty = _BlockOverflowProperty | java.lang.String
  type BlockSizeProperty[TLength] = _BlockSizeProperty[TLength] | TLength | java.lang.String
  type BorderBlockEndProperty[TLength] = _BorderBlockEndProperty[TLength] | java.lang.String
  type BorderBlockStartProperty[TLength] = _BorderBlockStartProperty[TLength] | java.lang.String
  type BorderBottomLeftRadiusProperty[TLength] = Globals | TLength | java.lang.String
  type BorderBottomProperty[TLength] = _BorderBottomProperty[TLength] | java.lang.String
  type BorderBottomRightRadiusProperty[TLength] = Globals | TLength | java.lang.String
  type BorderColorProperty = _BorderColorProperty | java.lang.String
  type BorderImageOutsetProperty[TLength] = Globals | TLength | java.lang.String | scala.Double
  type BorderImageProperty = _BorderImageProperty | java.lang.String | scala.Double
  type BorderImageRepeatProperty = _BorderImageRepeatProperty | java.lang.String
  type BorderImageSliceProperty = Globals | java.lang.String | scala.Double
  type BorderImageSourceProperty = _BorderImageSourceProperty | java.lang.String
  type BorderImageWidthProperty[TLength] = _BorderImageWidthProperty[TLength] | TLength | java.lang.String | scala.Double
  type BorderInlineEndProperty[TLength] = _BorderInlineEndProperty[TLength] | java.lang.String
  type BorderInlineStartProperty[TLength] = _BorderInlineStartProperty[TLength] | java.lang.String
  type BorderLeftProperty[TLength] = _BorderLeftProperty[TLength] | java.lang.String
  type BorderProperty[TLength] = _BorderProperty[TLength] | java.lang.String
  type BorderRadiusProperty[TLength] = Globals | TLength | java.lang.String
  type BorderRightProperty[TLength] = _BorderRightProperty[TLength] | java.lang.String
  type BorderSpacingProperty[TLength] = Globals | TLength | java.lang.String
  type BorderStyleProperty = _BorderStyleProperty | java.lang.String
  type BorderTopLeftRadiusProperty[TLength] = Globals | TLength | java.lang.String
  type BorderTopProperty[TLength] = _BorderTopProperty[TLength] | java.lang.String
  type BorderTopRightRadiusProperty[TLength] = Globals | TLength | java.lang.String
  type BorderWidthProperty[TLength] = _BorderWidthProperty[TLength] | java.lang.String
  type BottomProperty[TLength] = _BottomProperty[TLength] | TLength | java.lang.String
  type BoxShadowProperty = _BoxShadowProperty | java.lang.String
  type ClipPathProperty = _ClipPathProperty | java.lang.String
  type ClipProperty = _ClipProperty | java.lang.String
  type ColumnCountProperty = _ColumnCountProperty | scala.Double
  type ColumnGapProperty[TLength] = _ColumnGapProperty[TLength] | TLength | java.lang.String
  type ColumnRuleProperty[TLength] = _ColumnRuleProperty[TLength] | java.lang.String
  type ColumnRuleStyleProperty = _ColumnRuleStyleProperty | java.lang.String
  type ColumnRuleWidthProperty[TLength] = _ColumnRuleWidthProperty[TLength] | java.lang.String
  type ColumnWidthProperty[TLength] = _ColumnWidthProperty[TLength] | TLength
  type ColumnsProperty[TLength] = _ColumnsProperty[TLength] | TLength | java.lang.String | scala.Double
  type ContainProperty = _ContainProperty | java.lang.String
  type ContentProperty = _ContentProperty | java.lang.String
  type CounterIncrementProperty = _CounterIncrementProperty | java.lang.String
  type CounterResetProperty = _CounterResetProperty | java.lang.String
  type CursorProperty = _CursorProperty | java.lang.String
  type DisplayProperty = _DisplayProperty | java.lang.String
  type FilterProperty = _FilterProperty | java.lang.String
  type FlexBasisProperty[TLength] = _FlexBasisProperty[TLength] | TLength | java.lang.String
  type FlexFlowProperty = _FlexFlowProperty | java.lang.String
  type FlexProperty[TLength] = _FlexProperty[TLength] | TLength | java.lang.String | scala.Double
  type FontFamilyProperty = _FontFamilyProperty | java.lang.String
  type FontFeatureSettingsProperty = _FontFeatureSettingsProperty | java.lang.String
  type FontLanguageOverrideProperty = _FontLanguageOverrideProperty | java.lang.String
  type FontProperty = _FontProperty | java.lang.String
  type FontSizeAdjustProperty = _FontSizeAdjustProperty | scala.Double
  type FontSizeProperty[TLength] = _FontSizeProperty[TLength] | TLength | java.lang.String
  type FontStyleProperty = _FontStyleProperty | java.lang.String
  type FontSynthesisProperty = _FontSynthesisProperty | java.lang.String
  type FontVariantAlternatesProperty = _FontVariantAlternatesProperty | java.lang.String
  type FontVariantEastAsianProperty = _FontVariantEastAsianProperty | java.lang.String
  type FontVariantLigaturesProperty = _FontVariantLigaturesProperty | java.lang.String
  type FontVariantNumericProperty = _FontVariantNumericProperty | java.lang.String
  type FontVariantProperty = _FontVariantProperty | java.lang.String
  type FontVariationSettingsProperty = _FontVariationSettingsProperty | java.lang.String
  type GapProperty[TLength] = _GapProperty[TLength] | TLength | java.lang.String
  type GlyphOrientationVerticalProperty = _GlyphOrientationVerticalProperty | java.lang.String | scala.Double
  type GridAreaProperty = Globals | csstypeLib.GridLine | java.lang.String
  type GridAutoColumnsProperty[TLength] = _GridAutoColumnsProperty[TLength] | java.lang.String
  type GridAutoFlowProperty = _GridAutoFlowProperty | java.lang.String
  type GridAutoRowsProperty[TLength] = _GridAutoRowsProperty[TLength] | java.lang.String
  type GridColumnEndProperty = Globals | csstypeLib.GridLine
  type GridColumnGapProperty[TLength] = Globals | TLength | java.lang.String
  type GridColumnProperty = Globals | csstypeLib.GridLine | java.lang.String
  type GridColumnStartProperty = Globals | csstypeLib.GridLine
  type GridGapProperty[TLength] = Globals | TLength | java.lang.String
  type GridProperty = _GridProperty | java.lang.String
  type GridRowEndProperty = Globals | csstypeLib.GridLine
  type GridRowGapProperty[TLength] = Globals | TLength | java.lang.String
  type GridRowProperty = Globals | csstypeLib.GridLine | java.lang.String
  type GridRowStartProperty = Globals | csstypeLib.GridLine
  type GridTemplateAreasProperty = _GridTemplateAreasProperty | java.lang.String
  type GridTemplateColumnsProperty[TLength] = _GridTemplateColumnsProperty[TLength] | java.lang.String
  type GridTemplateProperty = _GridTemplateProperty | java.lang.String
  type GridTemplateRowsProperty[TLength] = _GridTemplateRowsProperty[TLength] | java.lang.String
  type HangingPunctuationProperty = _HangingPunctuationProperty | java.lang.String
  type HeightProperty[TLength] = _HeightProperty[TLength] | TLength | java.lang.String
  type ImageOrientationProperty = _ImageOrientationProperty | java.lang.String
  type ImageResolutionProperty = _ImageResolutionProperty | java.lang.String
  type InitialLetterProperty = _InitialLetterProperty | java.lang.String | scala.Double
  type InlineSizeProperty[TLength] = _InlineSizeProperty[TLength] | TLength | java.lang.String
  type InsetBlockEndProperty[TLength] = _InsetBlockEndProperty[TLength] | TLength | java.lang.String
  type InsetBlockStartProperty[TLength] = _InsetBlockStartProperty[TLength] | TLength | java.lang.String
  type InsetInlineEndProperty[TLength] = _InsetInlineEndProperty[TLength] | TLength | java.lang.String
  type InsetInlineStartProperty[TLength] = _InsetInlineStartProperty[TLength] | TLength | java.lang.String
  type JustifyContentProperty = _JustifyContentProperty | java.lang.String
  type JustifyItemsProperty = _JustifyItemsProperty | java.lang.String
  type JustifySelfProperty = _JustifySelfProperty | java.lang.String
  type LeftProperty[TLength] = _LeftProperty[TLength] | TLength | java.lang.String
  type LetterSpacingProperty[TLength] = _LetterSpacingProperty[TLength] | TLength
  type LineClampProperty = _LineClampProperty | scala.Double
  type LineHeightProperty[TLength] = _LineHeightProperty[TLength] | TLength | java.lang.String | scala.Double
  type LineHeightStepProperty[TLength] = Globals | TLength
  type ListStyleImageProperty = _ListStyleImageProperty | java.lang.String
  type ListStyleProperty = _ListStyleProperty | java.lang.String
  type ListStyleTypeProperty = _ListStyleTypeProperty | java.lang.String
  type MarginBlockEndProperty[TLength] = _MarginBlockEndProperty[TLength] | TLength | java.lang.String
  type MarginBlockStartProperty[TLength] = _MarginBlockStartProperty[TLength] | TLength | java.lang.String
  type MarginBottomProperty[TLength] = _MarginBottomProperty[TLength] | TLength | java.lang.String
  type MarginInlineEndProperty[TLength] = _MarginInlineEndProperty[TLength] | TLength | java.lang.String
  type MarginInlineStartProperty[TLength] = _MarginInlineStartProperty[TLength] | TLength | java.lang.String
  type MarginLeftProperty[TLength] = _MarginLeftProperty[TLength] | TLength | java.lang.String
  type MarginProperty[TLength] = _MarginProperty[TLength] | TLength | java.lang.String
  type MarginRightProperty[TLength] = _MarginRightProperty[TLength] | TLength | java.lang.String
  type MarginTopProperty[TLength] = _MarginTopProperty[TLength] | TLength | java.lang.String
  type MarkerEndProperty = _MarkerEndProperty | java.lang.String
  type MarkerMidProperty = _MarkerMidProperty | java.lang.String
  type MarkerProperty = _MarkerProperty | java.lang.String
  type MarkerStartProperty = _MarkerStartProperty | java.lang.String
  type MaskBorderOutsetProperty[TLength] = Globals | TLength | java.lang.String | scala.Double
  type MaskBorderProperty = _MaskBorderProperty | java.lang.String | scala.Double
  type MaskBorderRepeatProperty = _MaskBorderRepeatProperty | java.lang.String
  type MaskBorderSliceProperty = Globals | java.lang.String | scala.Double
  type MaskBorderSourceProperty = _MaskBorderSourceProperty | java.lang.String
  type MaskBorderWidthProperty[TLength] = _MaskBorderWidthProperty[TLength] | TLength | java.lang.String | scala.Double
  type MaskClipProperty = _MaskClipProperty | java.lang.String
  type MaskCompositeProperty = _MaskCompositeProperty | java.lang.String
  type MaskImageProperty = _MaskImageProperty | java.lang.String
  type MaskModeProperty = _MaskModeProperty | java.lang.String
  type MaskOriginProperty = _MaskOriginProperty | java.lang.String
  type MaskPositionProperty[TLength] = _MaskPositionProperty[TLength] | java.lang.String
  type MaskProperty[TLength] = _MaskProperty[TLength] | java.lang.String
  type MaskRepeatProperty = _MaskRepeatProperty | java.lang.String
  type MaskSizeProperty[TLength] = _MaskSizeProperty[TLength] | java.lang.String
  type MaxBlockSizeProperty[TLength] = _MaxBlockSizeProperty[TLength] | TLength | java.lang.String
  type MaxHeightProperty[TLength] = _MaxHeightProperty[TLength] | TLength | java.lang.String
  type MaxInlineSizeProperty[TLength] = _MaxInlineSizeProperty[TLength] | TLength | java.lang.String
  type MaxLinesProperty = _MaxLinesProperty | scala.Double
  type MaxWidthProperty[TLength] = _MaxWidthProperty[TLength] | TLength | java.lang.String
  type MinBlockSizeProperty[TLength] = _MinBlockSizeProperty[TLength] | TLength | java.lang.String
  type MinHeightProperty[TLength] = _MinHeightProperty[TLength] | TLength | java.lang.String
  type MinInlineSizeProperty[TLength] = _MinInlineSizeProperty[TLength] | TLength | java.lang.String
  type MinWidthProperty[TLength] = _MinWidthProperty[TLength] | TLength | java.lang.String
  type MozBindingProperty = _MozBindingProperty | java.lang.String
  type MozBorderBottomColorsProperty = _MozBorderBottomColorsProperty | java.lang.String
  type MozBorderLeftColorsProperty = _MozBorderLeftColorsProperty | java.lang.String
  type MozBorderRightColorsProperty = _MozBorderRightColorsProperty | java.lang.String
  type MozBorderTopColorsProperty = _MozBorderTopColorsProperty | java.lang.String
  type MozContextPropertiesProperty = _MozContextPropertiesProperty | java.lang.String
  type MozImageRegionProperty = _MozImageRegionProperty | java.lang.String
  type MozOutlineRadiusBottomleftProperty[TLength] = Globals | TLength | java.lang.String
  type MozOutlineRadiusBottomrightProperty[TLength] = Globals | TLength | java.lang.String
  type MozOutlineRadiusProperty[TLength] = Globals | TLength | java.lang.String
  type MozOutlineRadiusTopleftProperty[TLength] = Globals | TLength | java.lang.String
  type MozOutlineRadiusToprightProperty[TLength] = Globals | TLength | java.lang.String
  type MsContentZoomSnapProperty = _MsContentZoomSnapProperty | java.lang.String
  type MsFlowFromProperty = _MsFlowFromProperty | java.lang.String
  type MsFlowIntoProperty = _MsFlowIntoProperty | java.lang.String
  type MsHyphenateLimitCharsProperty = _MsHyphenateLimitCharsProperty | java.lang.String | scala.Double
  type MsHyphenateLimitLinesProperty = _MsHyphenateLimitLinesProperty | scala.Double
  type MsHyphenateLimitZoneProperty[TLength] = Globals | TLength | java.lang.String
  type MsScrollLimitXMaxProperty[TLength] = _MsScrollLimitXMaxProperty[TLength] | TLength
  type MsScrollLimitXMinProperty[TLength] = Globals | TLength
  type MsScrollLimitYMaxProperty[TLength] = _MsScrollLimitYMaxProperty[TLength] | TLength
  type MsScrollLimitYMinProperty[TLength] = Globals | TLength
  type MsWrapMarginProperty[TLength] = Globals | TLength
  type OffsetDistanceProperty[TLength] = Globals | TLength | java.lang.String
  type OffsetPathProperty = _OffsetPathProperty | java.lang.String
  type OffsetProperty[TLength] = _OffsetProperty[TLength] | java.lang.String
  type OffsetRotateProperty = _OffsetRotateProperty | java.lang.String
  type OutlineOffsetProperty[TLength] = Globals | TLength
  type OutlineProperty[TLength] = _OutlineProperty[TLength] | java.lang.String
  type OutlineStyleProperty = _OutlineStyleProperty | java.lang.String
  type OverflowBlockProperty = _OverflowBlockProperty | java.lang.String
  type OverflowInlineProperty = _OverflowInlineProperty | java.lang.String
  type OverflowProperty = _OverflowProperty | java.lang.String
  type OverscrollBehaviorProperty = _OverscrollBehaviorProperty | java.lang.String
  type PaddingBlockEndProperty[TLength] = Globals | TLength | java.lang.String
  type PaddingBlockStartProperty[TLength] = Globals | TLength | java.lang.String
  type PaddingBottomProperty[TLength] = Globals | TLength | java.lang.String
  type PaddingInlineEndProperty[TLength] = Globals | TLength | java.lang.String
  type PaddingInlineStartProperty[TLength] = Globals | TLength | java.lang.String
  type PaddingLeftProperty[TLength] = Globals | TLength | java.lang.String
  type PaddingProperty[TLength] = Globals | TLength | java.lang.String
  type PaddingRightProperty[TLength] = Globals | TLength | java.lang.String
  type PaddingTopProperty[TLength] = Globals | TLength | java.lang.String
  type PaintOrderProperty = _PaintOrderProperty | java.lang.String
  type PerspectiveProperty[TLength] = _PerspectiveProperty[TLength] | TLength
  type PlaceContentProperty = _PlaceContentProperty | java.lang.String
  type PlaceItemsProperty = _PlaceItemsProperty | java.lang.String
  type PlaceSelfProperty = _PlaceSelfProperty | java.lang.String
  type QuotesProperty = _QuotesProperty | java.lang.String
  type RightProperty[TLength] = _RightProperty[TLength] | TLength | java.lang.String
  type RotateProperty = _RotateProperty | java.lang.String
  type RowGapProperty[TLength] = _RowGapProperty[TLength] | TLength | java.lang.String
  type ScaleProperty = _ScaleProperty | java.lang.String | scala.Double
  type ScrollMarginBlockEndProperty[TLength] = _ScrollMarginBlockEndProperty[TLength] | TLength
  type ScrollMarginBlockProperty[TLength] = _ScrollMarginBlockProperty[TLength] | TLength | java.lang.String
  type ScrollMarginBlockStartProperty[TLength] = _ScrollMarginBlockStartProperty[TLength] | TLength
  type ScrollMarginBottomProperty[TLength] = _ScrollMarginBottomProperty[TLength] | TLength
  type ScrollMarginInlineEndProperty[TLength] = _ScrollMarginInlineEndProperty[TLength] | TLength
  type ScrollMarginInlineStartProperty[TLength] = _ScrollMarginInlineStartProperty[TLength] | TLength
  type ScrollMarginLeftProperty[TLength] = _ScrollMarginLeftProperty[TLength] | TLength
  type ScrollMarginProperty[TLength] = _ScrollMarginProperty[TLength] | TLength | java.lang.String
  type ScrollMarginRightProperty[TLength] = _ScrollMarginRightProperty[TLength] | TLength
  type ScrollMarginTopProperty[TLength] = _ScrollMarginTopProperty[TLength] | TLength
  type ScrollPaddingBlockEndProperty[TLength] = _ScrollPaddingBlockEndProperty[TLength] | TLength | java.lang.String
  type ScrollPaddingBlockProperty[TLength] = Globals | TLength | java.lang.String
  type ScrollPaddingBlockStartProperty[TLength] = _ScrollPaddingBlockStartProperty[TLength] | TLength | java.lang.String
  type ScrollPaddingBottomProperty[TLength] = _ScrollPaddingBottomProperty[TLength] | TLength | java.lang.String
  type ScrollPaddingInlineEndProperty[TLength] = _ScrollPaddingInlineEndProperty[TLength] | TLength | java.lang.String
  type ScrollPaddingInlineProperty[TLength] = Globals | TLength | java.lang.String
  type ScrollPaddingInlineStartProperty[TLength] = _ScrollPaddingInlineStartProperty[TLength] | TLength | java.lang.String
  type ScrollPaddingLeftProperty[TLength] = _ScrollPaddingLeftProperty[TLength] | TLength | java.lang.String
  type ScrollPaddingProperty[TLength] = _ScrollPaddingProperty[TLength] | TLength | java.lang.String
  type ScrollPaddingRightProperty[TLength] = _ScrollPaddingRightProperty[TLength] | TLength | java.lang.String
  type ScrollPaddingTopProperty[TLength] = _ScrollPaddingTopProperty[TLength] | TLength | java.lang.String
  type ScrollSnapAlignProperty = _ScrollSnapAlignProperty | java.lang.String
  type ScrollSnapCoordinateProperty[TLength] = _ScrollSnapCoordinateProperty[TLength] | java.lang.String
  type ScrollSnapPointsXProperty = _ScrollSnapPointsXProperty | java.lang.String
  type ScrollSnapPointsYProperty = _ScrollSnapPointsYProperty | java.lang.String
  type ScrollSnapTypeProperty = _ScrollSnapTypeProperty | java.lang.String
  type ShapeMarginProperty[TLength] = Globals | TLength | java.lang.String
  type ShapeOutsideProperty = _ShapeOutsideProperty | java.lang.String
  type StrokeDasharrayProperty[TLength] = _StrokeDasharrayProperty[TLength] | csstypeLib.Dasharray[TLength]
  type StrokeDashoffsetProperty[TLength] = Globals | TLength | java.lang.String
  type StrokeWidthProperty[TLength] = Globals | TLength | java.lang.String
  type TabSizeProperty[TLength] = Globals | TLength | scala.Double
  type TextCombineUprightProperty = _TextCombineUprightProperty | java.lang.String
  type TextDecorationLineProperty = _TextDecorationLineProperty | java.lang.String
  type TextDecorationProperty = _TextDecorationProperty | java.lang.String
  type TextDecorationSkipProperty = _TextDecorationSkipProperty | java.lang.String
  type TextEmphasisProperty = _TextEmphasisProperty | java.lang.String
  type TextEmphasisStyleProperty = _TextEmphasisStyleProperty | java.lang.String
  type TextIndentProperty[TLength] = Globals | TLength | java.lang.String
  type TextOverflowProperty = _TextOverflowProperty | java.lang.String
  type TextShadowProperty = _TextShadowProperty | java.lang.String
  type TextSizeAdjustProperty = _TextSizeAdjustProperty | java.lang.String
  type TextUnderlinePositionProperty = _TextUnderlinePositionProperty | java.lang.String
  type TopProperty[TLength] = _TopProperty[TLength] | TLength | java.lang.String
  type TouchActionProperty = _TouchActionProperty | java.lang.String
  type TransformOriginProperty[TLength] = _TransformOriginProperty[TLength] | TLength | java.lang.String
  type TransformProperty = _TransformProperty | java.lang.String
  type TransitionProperty = _TransitionProperty | java.lang.String
  type TransitionPropertyProperty = _TransitionPropertyProperty | java.lang.String
  type TransitionTimingFunctionProperty = _TransitionTimingFunctionProperty | java.lang.String
  type TranslateProperty[TLength] = _TranslateProperty[TLength] | TLength | java.lang.String
  type VerticalAlignProperty[TLength] = _VerticalAlignProperty[TLength] | TLength | java.lang.String
  type WebkitBorderBeforeProperty[TLength] = _WebkitBorderBeforeProperty[TLength] | java.lang.String
  type WebkitBorderBeforeStyleProperty = _WebkitBorderBeforeStyleProperty | java.lang.String
  type WebkitBorderBeforeWidthProperty[TLength] = _WebkitBorderBeforeWidthProperty[TLength] | java.lang.String
  type WebkitBoxReflectProperty[TLength] = _WebkitBoxReflectProperty[TLength] | TLength | java.lang.String
  type WebkitLineClampProperty = _WebkitLineClampProperty | scala.Double
  type WebkitMaskAttachmentProperty = _WebkitMaskAttachmentProperty | java.lang.String
  type WebkitMaskClipProperty = _WebkitMaskClipProperty | java.lang.String
  type WebkitMaskCompositeProperty = _WebkitMaskCompositeProperty | java.lang.String
  type WebkitMaskImageProperty = _WebkitMaskImageProperty | java.lang.String
  type WebkitMaskOriginProperty = _WebkitMaskOriginProperty | java.lang.String
  type WebkitMaskPositionProperty[TLength] = _WebkitMaskPositionProperty[TLength] | java.lang.String
  type WebkitMaskPositionXProperty[TLength] = _WebkitMaskPositionXProperty[TLength] | TLength | java.lang.String
  type WebkitMaskPositionYProperty[TLength] = _WebkitMaskPositionYProperty[TLength] | TLength | java.lang.String
  type WebkitMaskProperty[TLength] = _WebkitMaskProperty[TLength] | java.lang.String
  type WebkitMaskRepeatProperty = _WebkitMaskRepeatProperty | java.lang.String
  type WebkitMaskSizeProperty[TLength] = _WebkitMaskSizeProperty[TLength] | java.lang.String
  type WebkitTextStrokeProperty[TLength] = _WebkitTextStrokeProperty[TLength] | TLength | java.lang.String
  type WebkitTextStrokeWidthProperty[TLength] = Globals | TLength
  type WidthProperty[TLength] = _WidthProperty[TLength] | TLength | java.lang.String
  type WillChangeProperty = _WillChangeProperty | java.lang.String
  type WordSpacingProperty[TLength] = _WordSpacingProperty[TLength] | TLength | java.lang.String
  type ZIndexProperty = _ZIndexProperty | scala.Double
  type ZoomProperty = _ZoomProperty | java.lang.String | scala.Double
}
