package typings.cypress.JQuery_.Ajax

import org.scalablytyped.runtime.NumberDictionary
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

// region StatusCodeCallbacks
// #region StatusCodeCallbacks
trait StatusCodeCallbacks[TContext] extends // Status codes not listed require type annotations when defining the callback
/* index */ NumberDictionary[SuccessCallback[TContext] | ErrorCallback[TContext]] {
  // region Success Status Codes
  // #region Success Status Codes
  // jQuery treats 2xx and 304 status codes as a success
  var `200`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `201`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `202`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `203`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `204`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `205`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `206`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `207`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `208`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `209`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `210`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `211`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `212`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `213`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `214`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `215`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `216`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `217`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `218`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `219`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `220`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `221`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `222`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `223`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `224`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `225`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `226`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `227`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `228`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `229`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `230`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `231`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `232`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `233`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `234`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `235`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `236`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `237`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `238`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `239`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `240`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `241`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `242`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `243`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `244`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `245`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `246`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `247`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `248`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `249`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `250`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `251`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `252`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `253`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `254`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `255`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `256`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `257`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `258`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `259`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `260`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `261`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `262`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `263`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `264`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `265`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `266`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `267`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `268`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `269`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `270`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `271`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `272`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `273`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `274`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `275`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `276`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `277`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `278`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `279`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `280`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `281`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `282`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `283`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `284`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `285`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `286`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `287`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `288`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `289`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `290`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `291`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `292`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `293`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `294`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `295`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `296`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `297`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `298`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `299`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  // #endregion
  // region Error Status Codes
  // #region Error Status Codes
  var `300`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `301`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `302`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `303`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `304`: js.UndefOr[SuccessCallback[TContext]] = js.undefined
  var `305`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `306`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `307`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `308`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `309`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `310`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `311`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `312`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `313`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `314`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `315`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `316`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `317`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `318`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `319`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `320`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `321`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `322`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `323`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `324`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `325`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `326`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `327`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `328`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `329`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `330`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `331`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `332`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `333`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `334`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `335`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `336`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `337`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `338`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `339`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `340`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `341`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `342`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `343`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `344`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `345`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `346`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `347`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `348`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `349`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `350`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `351`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `352`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `353`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `354`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `355`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `356`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `357`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `358`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `359`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `360`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `361`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `362`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `363`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `364`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `365`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `366`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `367`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `368`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `369`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `370`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `371`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `372`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `373`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `374`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `375`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `376`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `377`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `378`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `379`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `380`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `381`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `382`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `383`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `384`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `385`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `386`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `387`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `388`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `389`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `390`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `391`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `392`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `393`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `394`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `395`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `396`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `397`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `398`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `399`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `400`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `401`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `402`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `403`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `404`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `405`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `406`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `407`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `408`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `409`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `410`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `411`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `412`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `413`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `414`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `415`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `416`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `417`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `418`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `419`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `420`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `421`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `422`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `423`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `424`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `425`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `426`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `427`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `428`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `429`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `430`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `431`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `432`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `433`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `434`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `435`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `436`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `437`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `438`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `439`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `440`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `441`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `442`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `443`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `444`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `445`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `446`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `447`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `448`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `449`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `450`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `451`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `452`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `453`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `454`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `455`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `456`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `457`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `458`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `459`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `460`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `461`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `462`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `463`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `464`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `465`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `466`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `467`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `468`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `469`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `470`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `471`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `472`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `473`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `474`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `475`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `476`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `477`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `478`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `479`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `480`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `481`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `482`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `483`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `484`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `485`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `486`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `487`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `488`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `489`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `490`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `491`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `492`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `493`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `494`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `495`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `496`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `497`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `498`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `499`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `500`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `501`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `502`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `503`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `504`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `505`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `506`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `507`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `508`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `509`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `510`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `511`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `512`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `513`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `514`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `515`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `516`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `517`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `518`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `519`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `520`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `521`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `522`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `523`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `524`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `525`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `526`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `527`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `528`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `529`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `530`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `531`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `532`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `533`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `534`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `535`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `536`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `537`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `538`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `539`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `540`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `541`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `542`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `543`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `544`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `545`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `546`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `547`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `548`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `549`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `550`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `551`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `552`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `553`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `554`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `555`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `556`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `557`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `558`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `559`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `560`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `561`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `562`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `563`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `564`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `565`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `566`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `567`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `568`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `569`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `570`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `571`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `572`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `573`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `574`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `575`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `576`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `577`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `578`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `579`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `580`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `581`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `582`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `583`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `584`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `585`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `586`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `587`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `588`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `589`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `590`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `591`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `592`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `593`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `594`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `595`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `596`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `597`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `598`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
  var `599`: js.UndefOr[ErrorCallback[TContext]] = js.undefined
}

object StatusCodeCallbacks {
  @scala.inline
  def apply[TContext](
    `200`: SuccessCallback[TContext] = null,
    `201`: SuccessCallback[TContext] = null,
    `202`: SuccessCallback[TContext] = null,
    `203`: SuccessCallback[TContext] = null,
    `204`: SuccessCallback[TContext] = null,
    `205`: SuccessCallback[TContext] = null,
    `206`: SuccessCallback[TContext] = null,
    `207`: SuccessCallback[TContext] = null,
    `208`: SuccessCallback[TContext] = null,
    `209`: SuccessCallback[TContext] = null,
    `210`: SuccessCallback[TContext] = null,
    `211`: SuccessCallback[TContext] = null,
    `212`: SuccessCallback[TContext] = null,
    `213`: SuccessCallback[TContext] = null,
    `214`: SuccessCallback[TContext] = null,
    `215`: SuccessCallback[TContext] = null,
    `216`: SuccessCallback[TContext] = null,
    `217`: SuccessCallback[TContext] = null,
    `218`: SuccessCallback[TContext] = null,
    `219`: SuccessCallback[TContext] = null,
    `220`: SuccessCallback[TContext] = null,
    `221`: SuccessCallback[TContext] = null,
    `222`: SuccessCallback[TContext] = null,
    `223`: SuccessCallback[TContext] = null,
    `224`: SuccessCallback[TContext] = null,
    `225`: SuccessCallback[TContext] = null,
    `226`: SuccessCallback[TContext] = null,
    `227`: SuccessCallback[TContext] = null,
    `228`: SuccessCallback[TContext] = null,
    `229`: SuccessCallback[TContext] = null,
    `230`: SuccessCallback[TContext] = null,
    `231`: SuccessCallback[TContext] = null,
    `232`: SuccessCallback[TContext] = null,
    `233`: SuccessCallback[TContext] = null,
    `234`: SuccessCallback[TContext] = null,
    `235`: SuccessCallback[TContext] = null,
    `236`: SuccessCallback[TContext] = null,
    `237`: SuccessCallback[TContext] = null,
    `238`: SuccessCallback[TContext] = null,
    `239`: SuccessCallback[TContext] = null,
    `240`: SuccessCallback[TContext] = null,
    `241`: SuccessCallback[TContext] = null,
    `242`: SuccessCallback[TContext] = null,
    `243`: SuccessCallback[TContext] = null,
    `244`: SuccessCallback[TContext] = null,
    `245`: SuccessCallback[TContext] = null,
    `246`: SuccessCallback[TContext] = null,
    `247`: SuccessCallback[TContext] = null,
    `248`: SuccessCallback[TContext] = null,
    `249`: SuccessCallback[TContext] = null,
    `250`: SuccessCallback[TContext] = null,
    `251`: SuccessCallback[TContext] = null,
    `252`: SuccessCallback[TContext] = null,
    `253`: SuccessCallback[TContext] = null,
    `254`: SuccessCallback[TContext] = null,
    `255`: SuccessCallback[TContext] = null,
    `256`: SuccessCallback[TContext] = null,
    `257`: SuccessCallback[TContext] = null,
    `258`: SuccessCallback[TContext] = null,
    `259`: SuccessCallback[TContext] = null,
    `260`: SuccessCallback[TContext] = null,
    `261`: SuccessCallback[TContext] = null,
    `262`: SuccessCallback[TContext] = null,
    `263`: SuccessCallback[TContext] = null,
    `264`: SuccessCallback[TContext] = null,
    `265`: SuccessCallback[TContext] = null,
    `266`: SuccessCallback[TContext] = null,
    `267`: SuccessCallback[TContext] = null,
    `268`: SuccessCallback[TContext] = null,
    `269`: SuccessCallback[TContext] = null,
    `270`: SuccessCallback[TContext] = null,
    `271`: SuccessCallback[TContext] = null,
    `272`: SuccessCallback[TContext] = null,
    `273`: SuccessCallback[TContext] = null,
    `274`: SuccessCallback[TContext] = null,
    `275`: SuccessCallback[TContext] = null,
    `276`: SuccessCallback[TContext] = null,
    `277`: SuccessCallback[TContext] = null,
    `278`: SuccessCallback[TContext] = null,
    `279`: SuccessCallback[TContext] = null,
    `280`: SuccessCallback[TContext] = null,
    `281`: SuccessCallback[TContext] = null,
    `282`: SuccessCallback[TContext] = null,
    `283`: SuccessCallback[TContext] = null,
    `284`: SuccessCallback[TContext] = null,
    `285`: SuccessCallback[TContext] = null,
    `286`: SuccessCallback[TContext] = null,
    `287`: SuccessCallback[TContext] = null,
    `288`: SuccessCallback[TContext] = null,
    `289`: SuccessCallback[TContext] = null,
    `290`: SuccessCallback[TContext] = null,
    `291`: SuccessCallback[TContext] = null,
    `292`: SuccessCallback[TContext] = null,
    `293`: SuccessCallback[TContext] = null,
    `294`: SuccessCallback[TContext] = null,
    `295`: SuccessCallback[TContext] = null,
    `296`: SuccessCallback[TContext] = null,
    `297`: SuccessCallback[TContext] = null,
    `298`: SuccessCallback[TContext] = null,
    `299`: SuccessCallback[TContext] = null,
    `300`: ErrorCallback[TContext] = null,
    `301`: ErrorCallback[TContext] = null,
    `302`: ErrorCallback[TContext] = null,
    `303`: ErrorCallback[TContext] = null,
    `304`: SuccessCallback[TContext] = null,
    `305`: ErrorCallback[TContext] = null,
    `306`: ErrorCallback[TContext] = null,
    `307`: ErrorCallback[TContext] = null,
    `308`: ErrorCallback[TContext] = null,
    `309`: ErrorCallback[TContext] = null,
    `310`: ErrorCallback[TContext] = null,
    `311`: ErrorCallback[TContext] = null,
    `312`: ErrorCallback[TContext] = null,
    `313`: ErrorCallback[TContext] = null,
    `314`: ErrorCallback[TContext] = null,
    `315`: ErrorCallback[TContext] = null,
    `316`: ErrorCallback[TContext] = null,
    `317`: ErrorCallback[TContext] = null,
    `318`: ErrorCallback[TContext] = null,
    `319`: ErrorCallback[TContext] = null,
    `320`: ErrorCallback[TContext] = null,
    `321`: ErrorCallback[TContext] = null,
    `322`: ErrorCallback[TContext] = null,
    `323`: ErrorCallback[TContext] = null,
    `324`: ErrorCallback[TContext] = null,
    `325`: ErrorCallback[TContext] = null,
    `326`: ErrorCallback[TContext] = null,
    `327`: ErrorCallback[TContext] = null,
    `328`: ErrorCallback[TContext] = null,
    `329`: ErrorCallback[TContext] = null,
    `330`: ErrorCallback[TContext] = null,
    `331`: ErrorCallback[TContext] = null,
    `332`: ErrorCallback[TContext] = null,
    `333`: ErrorCallback[TContext] = null,
    `334`: ErrorCallback[TContext] = null,
    `335`: ErrorCallback[TContext] = null,
    `336`: ErrorCallback[TContext] = null,
    `337`: ErrorCallback[TContext] = null,
    `338`: ErrorCallback[TContext] = null,
    `339`: ErrorCallback[TContext] = null,
    `340`: ErrorCallback[TContext] = null,
    `341`: ErrorCallback[TContext] = null,
    `342`: ErrorCallback[TContext] = null,
    `343`: ErrorCallback[TContext] = null,
    `344`: ErrorCallback[TContext] = null,
    `345`: ErrorCallback[TContext] = null,
    `346`: ErrorCallback[TContext] = null,
    `347`: ErrorCallback[TContext] = null,
    `348`: ErrorCallback[TContext] = null,
    `349`: ErrorCallback[TContext] = null,
    `350`: ErrorCallback[TContext] = null,
    `351`: ErrorCallback[TContext] = null,
    `352`: ErrorCallback[TContext] = null,
    `353`: ErrorCallback[TContext] = null,
    `354`: ErrorCallback[TContext] = null,
    `355`: ErrorCallback[TContext] = null,
    `356`: ErrorCallback[TContext] = null,
    `357`: ErrorCallback[TContext] = null,
    `358`: ErrorCallback[TContext] = null,
    `359`: ErrorCallback[TContext] = null,
    `360`: ErrorCallback[TContext] = null,
    `361`: ErrorCallback[TContext] = null,
    `362`: ErrorCallback[TContext] = null,
    `363`: ErrorCallback[TContext] = null,
    `364`: ErrorCallback[TContext] = null,
    `365`: ErrorCallback[TContext] = null,
    `366`: ErrorCallback[TContext] = null,
    `367`: ErrorCallback[TContext] = null,
    `368`: ErrorCallback[TContext] = null,
    `369`: ErrorCallback[TContext] = null,
    `370`: ErrorCallback[TContext] = null,
    `371`: ErrorCallback[TContext] = null,
    `372`: ErrorCallback[TContext] = null,
    `373`: ErrorCallback[TContext] = null,
    `374`: ErrorCallback[TContext] = null,
    `375`: ErrorCallback[TContext] = null,
    `376`: ErrorCallback[TContext] = null,
    `377`: ErrorCallback[TContext] = null,
    `378`: ErrorCallback[TContext] = null,
    `379`: ErrorCallback[TContext] = null,
    `380`: ErrorCallback[TContext] = null,
    `381`: ErrorCallback[TContext] = null,
    `382`: ErrorCallback[TContext] = null,
    `383`: ErrorCallback[TContext] = null,
    `384`: ErrorCallback[TContext] = null,
    `385`: ErrorCallback[TContext] = null,
    `386`: ErrorCallback[TContext] = null,
    `387`: ErrorCallback[TContext] = null,
    `388`: ErrorCallback[TContext] = null,
    `389`: ErrorCallback[TContext] = null,
    `390`: ErrorCallback[TContext] = null,
    `391`: ErrorCallback[TContext] = null,
    `392`: ErrorCallback[TContext] = null,
    `393`: ErrorCallback[TContext] = null,
    `394`: ErrorCallback[TContext] = null,
    `395`: ErrorCallback[TContext] = null,
    `396`: ErrorCallback[TContext] = null,
    `397`: ErrorCallback[TContext] = null,
    `398`: ErrorCallback[TContext] = null,
    `399`: ErrorCallback[TContext] = null,
    `400`: ErrorCallback[TContext] = null,
    `401`: ErrorCallback[TContext] = null,
    `402`: ErrorCallback[TContext] = null,
    `403`: ErrorCallback[TContext] = null,
    `404`: ErrorCallback[TContext] = null,
    `405`: ErrorCallback[TContext] = null,
    `406`: ErrorCallback[TContext] = null,
    `407`: ErrorCallback[TContext] = null,
    `408`: ErrorCallback[TContext] = null,
    `409`: ErrorCallback[TContext] = null,
    `410`: ErrorCallback[TContext] = null,
    `411`: ErrorCallback[TContext] = null,
    `412`: ErrorCallback[TContext] = null,
    `413`: ErrorCallback[TContext] = null,
    `414`: ErrorCallback[TContext] = null,
    `415`: ErrorCallback[TContext] = null,
    `416`: ErrorCallback[TContext] = null,
    `417`: ErrorCallback[TContext] = null,
    `418`: ErrorCallback[TContext] = null,
    `419`: ErrorCallback[TContext] = null,
    `420`: ErrorCallback[TContext] = null,
    `421`: ErrorCallback[TContext] = null,
    `422`: ErrorCallback[TContext] = null,
    `423`: ErrorCallback[TContext] = null,
    `424`: ErrorCallback[TContext] = null,
    `425`: ErrorCallback[TContext] = null,
    `426`: ErrorCallback[TContext] = null,
    `427`: ErrorCallback[TContext] = null,
    `428`: ErrorCallback[TContext] = null,
    `429`: ErrorCallback[TContext] = null,
    `430`: ErrorCallback[TContext] = null,
    `431`: ErrorCallback[TContext] = null,
    `432`: ErrorCallback[TContext] = null,
    `433`: ErrorCallback[TContext] = null,
    `434`: ErrorCallback[TContext] = null,
    `435`: ErrorCallback[TContext] = null,
    `436`: ErrorCallback[TContext] = null,
    `437`: ErrorCallback[TContext] = null,
    `438`: ErrorCallback[TContext] = null,
    `439`: ErrorCallback[TContext] = null,
    `440`: ErrorCallback[TContext] = null,
    `441`: ErrorCallback[TContext] = null,
    `442`: ErrorCallback[TContext] = null,
    `443`: ErrorCallback[TContext] = null,
    `444`: ErrorCallback[TContext] = null,
    `445`: ErrorCallback[TContext] = null,
    `446`: ErrorCallback[TContext] = null,
    `447`: ErrorCallback[TContext] = null,
    `448`: ErrorCallback[TContext] = null,
    `449`: ErrorCallback[TContext] = null,
    `450`: ErrorCallback[TContext] = null,
    `451`: ErrorCallback[TContext] = null,
    `452`: ErrorCallback[TContext] = null,
    NumberDictionary: // Status codes not listed require type annotations when defining the callback
  /* index */ NumberDictionary[SuccessCallback[TContext] | ErrorCallback[TContext]] = null
  ): StatusCodeCallbacks[TContext] = {
    val __obj = js.Dynamic.literal()
    if (`200` != null) __obj.updateDynamic("200")(`200`.asInstanceOf[js.Any])
    if (`201` != null) __obj.updateDynamic("201")(`201`.asInstanceOf[js.Any])
    if (`202` != null) __obj.updateDynamic("202")(`202`.asInstanceOf[js.Any])
    if (`203` != null) __obj.updateDynamic("203")(`203`.asInstanceOf[js.Any])
    if (`204` != null) __obj.updateDynamic("204")(`204`.asInstanceOf[js.Any])
    if (`205` != null) __obj.updateDynamic("205")(`205`.asInstanceOf[js.Any])
    if (`206` != null) __obj.updateDynamic("206")(`206`.asInstanceOf[js.Any])
    if (`207` != null) __obj.updateDynamic("207")(`207`.asInstanceOf[js.Any])
    if (`208` != null) __obj.updateDynamic("208")(`208`.asInstanceOf[js.Any])
    if (`209` != null) __obj.updateDynamic("209")(`209`.asInstanceOf[js.Any])
    if (`210` != null) __obj.updateDynamic("210")(`210`.asInstanceOf[js.Any])
    if (`211` != null) __obj.updateDynamic("211")(`211`.asInstanceOf[js.Any])
    if (`212` != null) __obj.updateDynamic("212")(`212`.asInstanceOf[js.Any])
    if (`213` != null) __obj.updateDynamic("213")(`213`.asInstanceOf[js.Any])
    if (`214` != null) __obj.updateDynamic("214")(`214`.asInstanceOf[js.Any])
    if (`215` != null) __obj.updateDynamic("215")(`215`.asInstanceOf[js.Any])
    if (`216` != null) __obj.updateDynamic("216")(`216`.asInstanceOf[js.Any])
    if (`217` != null) __obj.updateDynamic("217")(`217`.asInstanceOf[js.Any])
    if (`218` != null) __obj.updateDynamic("218")(`218`.asInstanceOf[js.Any])
    if (`219` != null) __obj.updateDynamic("219")(`219`.asInstanceOf[js.Any])
    if (`220` != null) __obj.updateDynamic("220")(`220`.asInstanceOf[js.Any])
    if (`221` != null) __obj.updateDynamic("221")(`221`.asInstanceOf[js.Any])
    if (`222` != null) __obj.updateDynamic("222")(`222`.asInstanceOf[js.Any])
    if (`223` != null) __obj.updateDynamic("223")(`223`.asInstanceOf[js.Any])
    if (`224` != null) __obj.updateDynamic("224")(`224`.asInstanceOf[js.Any])
    if (`225` != null) __obj.updateDynamic("225")(`225`.asInstanceOf[js.Any])
    if (`226` != null) __obj.updateDynamic("226")(`226`.asInstanceOf[js.Any])
    if (`227` != null) __obj.updateDynamic("227")(`227`.asInstanceOf[js.Any])
    if (`228` != null) __obj.updateDynamic("228")(`228`.asInstanceOf[js.Any])
    if (`229` != null) __obj.updateDynamic("229")(`229`.asInstanceOf[js.Any])
    if (`230` != null) __obj.updateDynamic("230")(`230`.asInstanceOf[js.Any])
    if (`231` != null) __obj.updateDynamic("231")(`231`.asInstanceOf[js.Any])
    if (`232` != null) __obj.updateDynamic("232")(`232`.asInstanceOf[js.Any])
    if (`233` != null) __obj.updateDynamic("233")(`233`.asInstanceOf[js.Any])
    if (`234` != null) __obj.updateDynamic("234")(`234`.asInstanceOf[js.Any])
    if (`235` != null) __obj.updateDynamic("235")(`235`.asInstanceOf[js.Any])
    if (`236` != null) __obj.updateDynamic("236")(`236`.asInstanceOf[js.Any])
    if (`237` != null) __obj.updateDynamic("237")(`237`.asInstanceOf[js.Any])
    if (`238` != null) __obj.updateDynamic("238")(`238`.asInstanceOf[js.Any])
    if (`239` != null) __obj.updateDynamic("239")(`239`.asInstanceOf[js.Any])
    if (`240` != null) __obj.updateDynamic("240")(`240`.asInstanceOf[js.Any])
    if (`241` != null) __obj.updateDynamic("241")(`241`.asInstanceOf[js.Any])
    if (`242` != null) __obj.updateDynamic("242")(`242`.asInstanceOf[js.Any])
    if (`243` != null) __obj.updateDynamic("243")(`243`.asInstanceOf[js.Any])
    if (`244` != null) __obj.updateDynamic("244")(`244`.asInstanceOf[js.Any])
    if (`245` != null) __obj.updateDynamic("245")(`245`.asInstanceOf[js.Any])
    if (`246` != null) __obj.updateDynamic("246")(`246`.asInstanceOf[js.Any])
    if (`247` != null) __obj.updateDynamic("247")(`247`.asInstanceOf[js.Any])
    if (`248` != null) __obj.updateDynamic("248")(`248`.asInstanceOf[js.Any])
    if (`249` != null) __obj.updateDynamic("249")(`249`.asInstanceOf[js.Any])
    if (`250` != null) __obj.updateDynamic("250")(`250`.asInstanceOf[js.Any])
    if (`251` != null) __obj.updateDynamic("251")(`251`.asInstanceOf[js.Any])
    if (`252` != null) __obj.updateDynamic("252")(`252`.asInstanceOf[js.Any])
    if (`253` != null) __obj.updateDynamic("253")(`253`.asInstanceOf[js.Any])
    if (`254` != null) __obj.updateDynamic("254")(`254`.asInstanceOf[js.Any])
    if (`255` != null) __obj.updateDynamic("255")(`255`.asInstanceOf[js.Any])
    if (`256` != null) __obj.updateDynamic("256")(`256`.asInstanceOf[js.Any])
    if (`257` != null) __obj.updateDynamic("257")(`257`.asInstanceOf[js.Any])
    if (`258` != null) __obj.updateDynamic("258")(`258`.asInstanceOf[js.Any])
    if (`259` != null) __obj.updateDynamic("259")(`259`.asInstanceOf[js.Any])
    if (`260` != null) __obj.updateDynamic("260")(`260`.asInstanceOf[js.Any])
    if (`261` != null) __obj.updateDynamic("261")(`261`.asInstanceOf[js.Any])
    if (`262` != null) __obj.updateDynamic("262")(`262`.asInstanceOf[js.Any])
    if (`263` != null) __obj.updateDynamic("263")(`263`.asInstanceOf[js.Any])
    if (`264` != null) __obj.updateDynamic("264")(`264`.asInstanceOf[js.Any])
    if (`265` != null) __obj.updateDynamic("265")(`265`.asInstanceOf[js.Any])
    if (`266` != null) __obj.updateDynamic("266")(`266`.asInstanceOf[js.Any])
    if (`267` != null) __obj.updateDynamic("267")(`267`.asInstanceOf[js.Any])
    if (`268` != null) __obj.updateDynamic("268")(`268`.asInstanceOf[js.Any])
    if (`269` != null) __obj.updateDynamic("269")(`269`.asInstanceOf[js.Any])
    if (`270` != null) __obj.updateDynamic("270")(`270`.asInstanceOf[js.Any])
    if (`271` != null) __obj.updateDynamic("271")(`271`.asInstanceOf[js.Any])
    if (`272` != null) __obj.updateDynamic("272")(`272`.asInstanceOf[js.Any])
    if (`273` != null) __obj.updateDynamic("273")(`273`.asInstanceOf[js.Any])
    if (`274` != null) __obj.updateDynamic("274")(`274`.asInstanceOf[js.Any])
    if (`275` != null) __obj.updateDynamic("275")(`275`.asInstanceOf[js.Any])
    if (`276` != null) __obj.updateDynamic("276")(`276`.asInstanceOf[js.Any])
    if (`277` != null) __obj.updateDynamic("277")(`277`.asInstanceOf[js.Any])
    if (`278` != null) __obj.updateDynamic("278")(`278`.asInstanceOf[js.Any])
    if (`279` != null) __obj.updateDynamic("279")(`279`.asInstanceOf[js.Any])
    if (`280` != null) __obj.updateDynamic("280")(`280`.asInstanceOf[js.Any])
    if (`281` != null) __obj.updateDynamic("281")(`281`.asInstanceOf[js.Any])
    if (`282` != null) __obj.updateDynamic("282")(`282`.asInstanceOf[js.Any])
    if (`283` != null) __obj.updateDynamic("283")(`283`.asInstanceOf[js.Any])
    if (`284` != null) __obj.updateDynamic("284")(`284`.asInstanceOf[js.Any])
    if (`285` != null) __obj.updateDynamic("285")(`285`.asInstanceOf[js.Any])
    if (`286` != null) __obj.updateDynamic("286")(`286`.asInstanceOf[js.Any])
    if (`287` != null) __obj.updateDynamic("287")(`287`.asInstanceOf[js.Any])
    if (`288` != null) __obj.updateDynamic("288")(`288`.asInstanceOf[js.Any])
    if (`289` != null) __obj.updateDynamic("289")(`289`.asInstanceOf[js.Any])
    if (`290` != null) __obj.updateDynamic("290")(`290`.asInstanceOf[js.Any])
    if (`291` != null) __obj.updateDynamic("291")(`291`.asInstanceOf[js.Any])
    if (`292` != null) __obj.updateDynamic("292")(`292`.asInstanceOf[js.Any])
    if (`293` != null) __obj.updateDynamic("293")(`293`.asInstanceOf[js.Any])
    if (`294` != null) __obj.updateDynamic("294")(`294`.asInstanceOf[js.Any])
    if (`295` != null) __obj.updateDynamic("295")(`295`.asInstanceOf[js.Any])
    if (`296` != null) __obj.updateDynamic("296")(`296`.asInstanceOf[js.Any])
    if (`297` != null) __obj.updateDynamic("297")(`297`.asInstanceOf[js.Any])
    if (`298` != null) __obj.updateDynamic("298")(`298`.asInstanceOf[js.Any])
    if (`299` != null) __obj.updateDynamic("299")(`299`.asInstanceOf[js.Any])
    if (`300` != null) __obj.updateDynamic("300")(`300`.asInstanceOf[js.Any])
    if (`301` != null) __obj.updateDynamic("301")(`301`.asInstanceOf[js.Any])
    if (`302` != null) __obj.updateDynamic("302")(`302`.asInstanceOf[js.Any])
    if (`303` != null) __obj.updateDynamic("303")(`303`.asInstanceOf[js.Any])
    if (`304` != null) __obj.updateDynamic("304")(`304`.asInstanceOf[js.Any])
    if (`305` != null) __obj.updateDynamic("305")(`305`.asInstanceOf[js.Any])
    if (`306` != null) __obj.updateDynamic("306")(`306`.asInstanceOf[js.Any])
    if (`307` != null) __obj.updateDynamic("307")(`307`.asInstanceOf[js.Any])
    if (`308` != null) __obj.updateDynamic("308")(`308`.asInstanceOf[js.Any])
    if (`309` != null) __obj.updateDynamic("309")(`309`.asInstanceOf[js.Any])
    if (`310` != null) __obj.updateDynamic("310")(`310`.asInstanceOf[js.Any])
    if (`311` != null) __obj.updateDynamic("311")(`311`.asInstanceOf[js.Any])
    if (`312` != null) __obj.updateDynamic("312")(`312`.asInstanceOf[js.Any])
    if (`313` != null) __obj.updateDynamic("313")(`313`.asInstanceOf[js.Any])
    if (`314` != null) __obj.updateDynamic("314")(`314`.asInstanceOf[js.Any])
    if (`315` != null) __obj.updateDynamic("315")(`315`.asInstanceOf[js.Any])
    if (`316` != null) __obj.updateDynamic("316")(`316`.asInstanceOf[js.Any])
    if (`317` != null) __obj.updateDynamic("317")(`317`.asInstanceOf[js.Any])
    if (`318` != null) __obj.updateDynamic("318")(`318`.asInstanceOf[js.Any])
    if (`319` != null) __obj.updateDynamic("319")(`319`.asInstanceOf[js.Any])
    if (`320` != null) __obj.updateDynamic("320")(`320`.asInstanceOf[js.Any])
    if (`321` != null) __obj.updateDynamic("321")(`321`.asInstanceOf[js.Any])
    if (`322` != null) __obj.updateDynamic("322")(`322`.asInstanceOf[js.Any])
    if (`323` != null) __obj.updateDynamic("323")(`323`.asInstanceOf[js.Any])
    if (`324` != null) __obj.updateDynamic("324")(`324`.asInstanceOf[js.Any])
    if (`325` != null) __obj.updateDynamic("325")(`325`.asInstanceOf[js.Any])
    if (`326` != null) __obj.updateDynamic("326")(`326`.asInstanceOf[js.Any])
    if (`327` != null) __obj.updateDynamic("327")(`327`.asInstanceOf[js.Any])
    if (`328` != null) __obj.updateDynamic("328")(`328`.asInstanceOf[js.Any])
    if (`329` != null) __obj.updateDynamic("329")(`329`.asInstanceOf[js.Any])
    if (`330` != null) __obj.updateDynamic("330")(`330`.asInstanceOf[js.Any])
    if (`331` != null) __obj.updateDynamic("331")(`331`.asInstanceOf[js.Any])
    if (`332` != null) __obj.updateDynamic("332")(`332`.asInstanceOf[js.Any])
    if (`333` != null) __obj.updateDynamic("333")(`333`.asInstanceOf[js.Any])
    if (`334` != null) __obj.updateDynamic("334")(`334`.asInstanceOf[js.Any])
    if (`335` != null) __obj.updateDynamic("335")(`335`.asInstanceOf[js.Any])
    if (`336` != null) __obj.updateDynamic("336")(`336`.asInstanceOf[js.Any])
    if (`337` != null) __obj.updateDynamic("337")(`337`.asInstanceOf[js.Any])
    if (`338` != null) __obj.updateDynamic("338")(`338`.asInstanceOf[js.Any])
    if (`339` != null) __obj.updateDynamic("339")(`339`.asInstanceOf[js.Any])
    if (`340` != null) __obj.updateDynamic("340")(`340`.asInstanceOf[js.Any])
    if (`341` != null) __obj.updateDynamic("341")(`341`.asInstanceOf[js.Any])
    if (`342` != null) __obj.updateDynamic("342")(`342`.asInstanceOf[js.Any])
    if (`343` != null) __obj.updateDynamic("343")(`343`.asInstanceOf[js.Any])
    if (`344` != null) __obj.updateDynamic("344")(`344`.asInstanceOf[js.Any])
    if (`345` != null) __obj.updateDynamic("345")(`345`.asInstanceOf[js.Any])
    if (`346` != null) __obj.updateDynamic("346")(`346`.asInstanceOf[js.Any])
    if (`347` != null) __obj.updateDynamic("347")(`347`.asInstanceOf[js.Any])
    if (`348` != null) __obj.updateDynamic("348")(`348`.asInstanceOf[js.Any])
    if (`349` != null) __obj.updateDynamic("349")(`349`.asInstanceOf[js.Any])
    if (`350` != null) __obj.updateDynamic("350")(`350`.asInstanceOf[js.Any])
    if (`351` != null) __obj.updateDynamic("351")(`351`.asInstanceOf[js.Any])
    if (`352` != null) __obj.updateDynamic("352")(`352`.asInstanceOf[js.Any])
    if (`353` != null) __obj.updateDynamic("353")(`353`.asInstanceOf[js.Any])
    if (`354` != null) __obj.updateDynamic("354")(`354`.asInstanceOf[js.Any])
    if (`355` != null) __obj.updateDynamic("355")(`355`.asInstanceOf[js.Any])
    if (`356` != null) __obj.updateDynamic("356")(`356`.asInstanceOf[js.Any])
    if (`357` != null) __obj.updateDynamic("357")(`357`.asInstanceOf[js.Any])
    if (`358` != null) __obj.updateDynamic("358")(`358`.asInstanceOf[js.Any])
    if (`359` != null) __obj.updateDynamic("359")(`359`.asInstanceOf[js.Any])
    if (`360` != null) __obj.updateDynamic("360")(`360`.asInstanceOf[js.Any])
    if (`361` != null) __obj.updateDynamic("361")(`361`.asInstanceOf[js.Any])
    if (`362` != null) __obj.updateDynamic("362")(`362`.asInstanceOf[js.Any])
    if (`363` != null) __obj.updateDynamic("363")(`363`.asInstanceOf[js.Any])
    if (`364` != null) __obj.updateDynamic("364")(`364`.asInstanceOf[js.Any])
    if (`365` != null) __obj.updateDynamic("365")(`365`.asInstanceOf[js.Any])
    if (`366` != null) __obj.updateDynamic("366")(`366`.asInstanceOf[js.Any])
    if (`367` != null) __obj.updateDynamic("367")(`367`.asInstanceOf[js.Any])
    if (`368` != null) __obj.updateDynamic("368")(`368`.asInstanceOf[js.Any])
    if (`369` != null) __obj.updateDynamic("369")(`369`.asInstanceOf[js.Any])
    if (`370` != null) __obj.updateDynamic("370")(`370`.asInstanceOf[js.Any])
    if (`371` != null) __obj.updateDynamic("371")(`371`.asInstanceOf[js.Any])
    if (`372` != null) __obj.updateDynamic("372")(`372`.asInstanceOf[js.Any])
    if (`373` != null) __obj.updateDynamic("373")(`373`.asInstanceOf[js.Any])
    if (`374` != null) __obj.updateDynamic("374")(`374`.asInstanceOf[js.Any])
    if (`375` != null) __obj.updateDynamic("375")(`375`.asInstanceOf[js.Any])
    if (`376` != null) __obj.updateDynamic("376")(`376`.asInstanceOf[js.Any])
    if (`377` != null) __obj.updateDynamic("377")(`377`.asInstanceOf[js.Any])
    if (`378` != null) __obj.updateDynamic("378")(`378`.asInstanceOf[js.Any])
    if (`379` != null) __obj.updateDynamic("379")(`379`.asInstanceOf[js.Any])
    if (`380` != null) __obj.updateDynamic("380")(`380`.asInstanceOf[js.Any])
    if (`381` != null) __obj.updateDynamic("381")(`381`.asInstanceOf[js.Any])
    if (`382` != null) __obj.updateDynamic("382")(`382`.asInstanceOf[js.Any])
    if (`383` != null) __obj.updateDynamic("383")(`383`.asInstanceOf[js.Any])
    if (`384` != null) __obj.updateDynamic("384")(`384`.asInstanceOf[js.Any])
    if (`385` != null) __obj.updateDynamic("385")(`385`.asInstanceOf[js.Any])
    if (`386` != null) __obj.updateDynamic("386")(`386`.asInstanceOf[js.Any])
    if (`387` != null) __obj.updateDynamic("387")(`387`.asInstanceOf[js.Any])
    if (`388` != null) __obj.updateDynamic("388")(`388`.asInstanceOf[js.Any])
    if (`389` != null) __obj.updateDynamic("389")(`389`.asInstanceOf[js.Any])
    if (`390` != null) __obj.updateDynamic("390")(`390`.asInstanceOf[js.Any])
    if (`391` != null) __obj.updateDynamic("391")(`391`.asInstanceOf[js.Any])
    if (`392` != null) __obj.updateDynamic("392")(`392`.asInstanceOf[js.Any])
    if (`393` != null) __obj.updateDynamic("393")(`393`.asInstanceOf[js.Any])
    if (`394` != null) __obj.updateDynamic("394")(`394`.asInstanceOf[js.Any])
    if (`395` != null) __obj.updateDynamic("395")(`395`.asInstanceOf[js.Any])
    if (`396` != null) __obj.updateDynamic("396")(`396`.asInstanceOf[js.Any])
    if (`397` != null) __obj.updateDynamic("397")(`397`.asInstanceOf[js.Any])
    if (`398` != null) __obj.updateDynamic("398")(`398`.asInstanceOf[js.Any])
    if (`399` != null) __obj.updateDynamic("399")(`399`.asInstanceOf[js.Any])
    if (`400` != null) __obj.updateDynamic("400")(`400`.asInstanceOf[js.Any])
    if (`401` != null) __obj.updateDynamic("401")(`401`.asInstanceOf[js.Any])
    if (`402` != null) __obj.updateDynamic("402")(`402`.asInstanceOf[js.Any])
    if (`403` != null) __obj.updateDynamic("403")(`403`.asInstanceOf[js.Any])
    if (`404` != null) __obj.updateDynamic("404")(`404`.asInstanceOf[js.Any])
    if (`405` != null) __obj.updateDynamic("405")(`405`.asInstanceOf[js.Any])
    if (`406` != null) __obj.updateDynamic("406")(`406`.asInstanceOf[js.Any])
    if (`407` != null) __obj.updateDynamic("407")(`407`.asInstanceOf[js.Any])
    if (`408` != null) __obj.updateDynamic("408")(`408`.asInstanceOf[js.Any])
    if (`409` != null) __obj.updateDynamic("409")(`409`.asInstanceOf[js.Any])
    if (`410` != null) __obj.updateDynamic("410")(`410`.asInstanceOf[js.Any])
    if (`411` != null) __obj.updateDynamic("411")(`411`.asInstanceOf[js.Any])
    if (`412` != null) __obj.updateDynamic("412")(`412`.asInstanceOf[js.Any])
    if (`413` != null) __obj.updateDynamic("413")(`413`.asInstanceOf[js.Any])
    if (`414` != null) __obj.updateDynamic("414")(`414`.asInstanceOf[js.Any])
    if (`415` != null) __obj.updateDynamic("415")(`415`.asInstanceOf[js.Any])
    if (`416` != null) __obj.updateDynamic("416")(`416`.asInstanceOf[js.Any])
    if (`417` != null) __obj.updateDynamic("417")(`417`.asInstanceOf[js.Any])
    if (`418` != null) __obj.updateDynamic("418")(`418`.asInstanceOf[js.Any])
    if (`419` != null) __obj.updateDynamic("419")(`419`.asInstanceOf[js.Any])
    if (`420` != null) __obj.updateDynamic("420")(`420`.asInstanceOf[js.Any])
    if (`421` != null) __obj.updateDynamic("421")(`421`.asInstanceOf[js.Any])
    if (`422` != null) __obj.updateDynamic("422")(`422`.asInstanceOf[js.Any])
    if (`423` != null) __obj.updateDynamic("423")(`423`.asInstanceOf[js.Any])
    if (`424` != null) __obj.updateDynamic("424")(`424`.asInstanceOf[js.Any])
    if (`425` != null) __obj.updateDynamic("425")(`425`.asInstanceOf[js.Any])
    if (`426` != null) __obj.updateDynamic("426")(`426`.asInstanceOf[js.Any])
    if (`427` != null) __obj.updateDynamic("427")(`427`.asInstanceOf[js.Any])
    if (`428` != null) __obj.updateDynamic("428")(`428`.asInstanceOf[js.Any])
    if (`429` != null) __obj.updateDynamic("429")(`429`.asInstanceOf[js.Any])
    if (`430` != null) __obj.updateDynamic("430")(`430`.asInstanceOf[js.Any])
    if (`431` != null) __obj.updateDynamic("431")(`431`.asInstanceOf[js.Any])
    if (`432` != null) __obj.updateDynamic("432")(`432`.asInstanceOf[js.Any])
    if (`433` != null) __obj.updateDynamic("433")(`433`.asInstanceOf[js.Any])
    if (`434` != null) __obj.updateDynamic("434")(`434`.asInstanceOf[js.Any])
    if (`435` != null) __obj.updateDynamic("435")(`435`.asInstanceOf[js.Any])
    if (`436` != null) __obj.updateDynamic("436")(`436`.asInstanceOf[js.Any])
    if (`437` != null) __obj.updateDynamic("437")(`437`.asInstanceOf[js.Any])
    if (`438` != null) __obj.updateDynamic("438")(`438`.asInstanceOf[js.Any])
    if (`439` != null) __obj.updateDynamic("439")(`439`.asInstanceOf[js.Any])
    if (`440` != null) __obj.updateDynamic("440")(`440`.asInstanceOf[js.Any])
    if (`441` != null) __obj.updateDynamic("441")(`441`.asInstanceOf[js.Any])
    if (`442` != null) __obj.updateDynamic("442")(`442`.asInstanceOf[js.Any])
    if (`443` != null) __obj.updateDynamic("443")(`443`.asInstanceOf[js.Any])
    if (`444` != null) __obj.updateDynamic("444")(`444`.asInstanceOf[js.Any])
    if (`445` != null) __obj.updateDynamic("445")(`445`.asInstanceOf[js.Any])
    if (`446` != null) __obj.updateDynamic("446")(`446`.asInstanceOf[js.Any])
    if (`447` != null) __obj.updateDynamic("447")(`447`.asInstanceOf[js.Any])
    if (`448` != null) __obj.updateDynamic("448")(`448`.asInstanceOf[js.Any])
    if (`449` != null) __obj.updateDynamic("449")(`449`.asInstanceOf[js.Any])
    if (`450` != null) __obj.updateDynamic("450")(`450`.asInstanceOf[js.Any])
    if (`451` != null) __obj.updateDynamic("451")(`451`.asInstanceOf[js.Any])
    if (`452` != null) __obj.updateDynamic("452")(`452`.asInstanceOf[js.Any])
    if (NumberDictionary != null) js.Dynamic.global.Object.assign(__obj, NumberDictionary)
    __obj.asInstanceOf[StatusCodeCallbacks[TContext]]
  }
}

