package typings
package reactDashNativeDashPopupDashDialogLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait reactDashNativeDashPopupDashDialogLibProps {
  @scala.inline
  def DialogButtonProps: reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.DialogButtonProps.type = reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.DialogButtonProps
  type DialogButtonProps = reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.DialogButtonProps
  @scala.inline
  def DialogContentProps: reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.DialogContentProps.type = reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.DialogContentProps
  type DialogContentProps = reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.DialogContentProps
  @scala.inline
  def DialogFooterProps: reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.DialogFooterProps.type = reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.DialogFooterProps
  type DialogFooterProps = reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.DialogFooterProps
  @scala.inline
  def DialogTitleProps: reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.DialogTitleProps.type = reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.DialogTitleProps
  type DialogTitleProps = reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.DialogTitleProps
  @scala.inline
  def OverlayProps: reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.OverlayProps.type = reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.OverlayProps
  type OverlayProps = reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.OverlayProps
  @scala.inline
  def ReactDashNativeDashPopupDashDialogProps: reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.DialogProps.type = reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.DialogProps
  type ReactDashNativeDashPopupDashDialogProps = reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogMod.DialogProps
}

