package typings.atAwsDashSdkClientDashCodecommitDashNode.typesPutFileExceptionsUnionMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesParentCommitIdRequiredExceptionMod.ParentCommitIdRequiredException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesInvalidParentCommitIdExceptionMod.InvalidParentCommitIdException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesParentCommitDoesNotExistExceptionMod.ParentCommitDoesNotExistException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesParentCommitIdOutdatedExceptionMod.ParentCommitIdOutdatedException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesFileContentRequiredExceptionMod.FileContentRequiredException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesFileContentSizeLimitExceededExceptionMod.FileContentSizeLimitExceededException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesPathRequiredExceptionMod.PathRequiredException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesInvalidPathExceptionMod.InvalidPathException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesBranchNameRequiredExceptionMod.BranchNameRequiredException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesInvalidBranchNameExceptionMod.InvalidBranchNameException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesBranchDoesNotExistExceptionMod.BranchDoesNotExistException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesBranchNameIsTagNameExceptionMod.BranchNameIsTagNameException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesInvalidFileModeExceptionMod.InvalidFileModeException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesNameLengthExceededExceptionMod.NameLengthExceededException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesInvalidEmailExceptionMod.InvalidEmailException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesCommitMessageLengthExceededExceptionMod.CommitMessageLengthExceededException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesInvalidDeletionParameterExceptionMod.InvalidDeletionParameterException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesSameFileContentExceptionMod.SameFileContentException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesFileNameConflictsWithDirectoryNameExceptionMod.FileNameConflictsWithDirectoryNameException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesDirectoryNameConflictsWithFileNameExceptionMod.DirectoryNameConflictsWithFileNameException
*/
trait PutFileExceptionsUnion extends js.Object

