package typings.reactDashNativeDashGestureDashHandler

import typings.react.reactMod.ComponentType
import typings.reactDashNative.reactDashNativeMod.DrawerLayoutAndroidProperties
import typings.reactDashNative.reactDashNativeMod.FlatListProperties
import typings.reactDashNative.reactDashNativeMod.ScrollViewProperties
import typings.reactDashNative.reactDashNativeMod.SwitchProperties
import typings.reactDashNative.reactDashNativeMod.TextInputProperties
import typings.reactDashNative.reactDashNativeMod.ToolbarAndroidProperties
import typings.reactDashNative.reactDashNativeMod.TouchableHighlightProperties
import typings.reactDashNative.reactDashNativeMod.TouchableNativeFeedbackProperties
import typings.reactDashNative.reactDashNativeMod.TouchableOpacityProperties
import typings.reactDashNative.reactDashNativeMod.TouchableWithoutFeedbackProperties
import typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.ContainedTouchableProperties
import typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.NativeViewGestureHandlerProperties
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

object reactDashNativeDashGestureDashHandlerComponents extends reactDashNativeDashGestureDashHandlerProps {
  @scala.inline
  def BaseButton: ComponentType[BaseButtonProps] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.BaseButton].asInstanceOf[typings.react.reactMod.ComponentType[BaseButtonProps]]
  @scala.inline
  def BorderlessButton: ComponentType[BorderlessButtonProps] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.BorderlessButton].asInstanceOf[typings.react.reactMod.ComponentType[BorderlessButtonProps]]
  @scala.inline
  def DrawerLayout: ComponentType[DrawerLayoutProps] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.drawerLayoutMod.default].asInstanceOf[typings.react.reactMod.ComponentType[DrawerLayoutProps]]
  @scala.inline
  def DrawerLayoutAndroid: ComponentType[NativeViewGestureHandlerProperties with DrawerLayoutAndroidProperties] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.DrawerLayoutAndroid].asInstanceOf[typings.react.reactMod.ComponentType[
  typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.NativeViewGestureHandlerProperties with typings.reactDashNative.reactDashNativeMod.DrawerLayoutAndroidProperties]]
  @scala.inline
  def FlatList[ItemT]: ComponentType[NativeViewGestureHandlerProperties with FlatListProperties[ItemT]] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.FlatList[ItemT]].asInstanceOf[typings.react.reactMod.ComponentType[
  typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.NativeViewGestureHandlerProperties with typings.reactDashNative.reactDashNativeMod.FlatListProperties[ItemT]]]
  @scala.inline
  def FlingGestureHandler: ComponentType[FlingGestureHandlerProps] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.FlingGestureHandler].asInstanceOf[typings.react.reactMod.ComponentType[FlingGestureHandlerProps]]
  @scala.inline
  def ForceTouchGestureHandler: ComponentType[ForceTouchGestureHandlerProps] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.ForceTouchGestureHandler].asInstanceOf[typings.react.reactMod.ComponentType[ForceTouchGestureHandlerProps]]
  @scala.inline
  def LongPressGestureHandler: ComponentType[LongPressGestureHandlerProps] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.LongPressGestureHandler].asInstanceOf[typings.react.reactMod.ComponentType[LongPressGestureHandlerProps]]
  @scala.inline
  def NativeViewGestureHandler: ComponentType[NativeViewGestureHandlerProps] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.NativeViewGestureHandler].asInstanceOf[typings.react.reactMod.ComponentType[NativeViewGestureHandlerProps]]
  @scala.inline
  def PanGestureHandler: ComponentType[PanGestureHandlerProps] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.PanGestureHandler].asInstanceOf[typings.react.reactMod.ComponentType[PanGestureHandlerProps]]
  @scala.inline
  def PinchGestureHandler: ComponentType[PinchGestureHandlerProps] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.PinchGestureHandler].asInstanceOf[typings.react.reactMod.ComponentType[PinchGestureHandlerProps]]
  @scala.inline
  def RawButton: ComponentType[RawButtonProps] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.RawButton].asInstanceOf[typings.react.reactMod.ComponentType[RawButtonProps]]
  @scala.inline
  def RectButton: ComponentType[RectButtonProps] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.RectButton].asInstanceOf[typings.react.reactMod.ComponentType[RectButtonProps]]
  @scala.inline
  def RotationGestureHandler: ComponentType[RotationGestureHandlerProps] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.RotationGestureHandler].asInstanceOf[typings.react.reactMod.ComponentType[RotationGestureHandlerProps]]
  @scala.inline
  def ScrollView: ComponentType[NativeViewGestureHandlerProperties with ScrollViewProperties] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.ScrollView].asInstanceOf[typings.react.reactMod.ComponentType[
  typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.NativeViewGestureHandlerProperties with typings.reactDashNative.reactDashNativeMod.ScrollViewProperties]]
  @scala.inline
  def Swipeable: ComponentType[SwipeableProps] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.swipeableMod.default].asInstanceOf[typings.react.reactMod.ComponentType[SwipeableProps]]
  @scala.inline
  def Switch: ComponentType[NativeViewGestureHandlerProperties with SwitchProperties] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.Switch].asInstanceOf[typings.react.reactMod.ComponentType[
  typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.NativeViewGestureHandlerProperties with typings.reactDashNative.reactDashNativeMod.SwitchProperties]]
  @scala.inline
  def TapGestureHandler: ComponentType[TapGestureHandlerProps] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.TapGestureHandler].asInstanceOf[typings.react.reactMod.ComponentType[TapGestureHandlerProps]]
  @scala.inline
  def TextInput: ComponentType[NativeViewGestureHandlerProperties with TextInputProperties] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.TextInput].asInstanceOf[typings.react.reactMod.ComponentType[
  typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.NativeViewGestureHandlerProperties with typings.reactDashNative.reactDashNativeMod.TextInputProperties]]
  @scala.inline
  def ToolbarAndroid: ComponentType[NativeViewGestureHandlerProperties with ToolbarAndroidProperties] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.ToolbarAndroid].asInstanceOf[typings.react.reactMod.ComponentType[
  typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.NativeViewGestureHandlerProperties with typings.reactDashNative.reactDashNativeMod.ToolbarAndroidProperties]]
  @scala.inline
  def TouchableHighlight: ComponentType[TouchableHighlightProperties | ContainedTouchableProperties] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.TouchableHighlight].asInstanceOf[typings.react.reactMod.ComponentType[
  typings.reactDashNative.reactDashNativeMod.TouchableHighlightProperties | typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.ContainedTouchableProperties]]
  @scala.inline
  def TouchableNativeFeedback: ComponentType[TouchableNativeFeedbackProperties | ContainedTouchableProperties] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.TouchableNativeFeedback].asInstanceOf[typings.react.reactMod.ComponentType[
  typings.reactDashNative.reactDashNativeMod.TouchableNativeFeedbackProperties | typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.ContainedTouchableProperties]]
  @scala.inline
  def TouchableOpacity: ComponentType[TouchableOpacityProperties | ContainedTouchableProperties] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.TouchableOpacity].asInstanceOf[typings.react.reactMod.ComponentType[
  typings.reactDashNative.reactDashNativeMod.TouchableOpacityProperties | typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.ContainedTouchableProperties]]
  @scala.inline
  def TouchableWithoutFeedback: ComponentType[TouchableWithoutFeedbackProperties | ContainedTouchableProperties] = js.constructorOf[typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.TouchableWithoutFeedback].asInstanceOf[typings.react.reactMod.ComponentType[
  typings.reactDashNative.reactDashNativeMod.TouchableWithoutFeedbackProperties | typings.reactDashNativeDashGestureDashHandler.reactDashNativeDashGestureDashHandlerMod.ContainedTouchableProperties]]
}

