package typings.atAwsDashSdkClientDashKmsDashBrowser.typesOutputTypesUnionMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesCancelKeyDeletionOutputMod.CancelKeyDeletionOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesCreateAliasOutputMod.CreateAliasOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesCreateGrantOutputMod.CreateGrantOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesCreateKeyOutputMod.CreateKeyOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesDecryptOutputMod.DecryptOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesDeleteAliasOutputMod.DeleteAliasOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesDeleteImportedKeyMaterialOutputMod.DeleteImportedKeyMaterialOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesDescribeKeyOutputMod.DescribeKeyOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesDisableKeyOutputMod.DisableKeyOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesDisableKeyRotationOutputMod.DisableKeyRotationOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesEnableKeyOutputMod.EnableKeyOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesEnableKeyRotationOutputMod.EnableKeyRotationOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesEncryptOutputMod.EncryptOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesGenerateDataKeyOutputMod.GenerateDataKeyOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesGenerateDataKeyWithoutPlaintextOutputMod.GenerateDataKeyWithoutPlaintextOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesGenerateRandomOutputMod.GenerateRandomOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesGetKeyPolicyOutputMod.GetKeyPolicyOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesGetKeyRotationStatusOutputMod.GetKeyRotationStatusOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesGetParametersForImportOutputMod.GetParametersForImportOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesImportKeyMaterialOutputMod.ImportKeyMaterialOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesListAliasesOutputMod.ListAliasesOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesListGrantsOutputMod.ListGrantsOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesListKeyPoliciesOutputMod.ListKeyPoliciesOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesListKeysOutputMod.ListKeysOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesListResourceTagsOutputMod.ListResourceTagsOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesListRetirableGrantsOutputMod.ListRetirableGrantsOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesPutKeyPolicyOutputMod.PutKeyPolicyOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesReEncryptOutputMod.ReEncryptOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesRetireGrantOutputMod.RetireGrantOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesRevokeGrantOutputMod.RevokeGrantOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesScheduleKeyDeletionOutputMod.ScheduleKeyDeletionOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesTagResourceOutputMod.TagResourceOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesUntagResourceOutputMod.UntagResourceOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesUpdateAliasOutputMod.UpdateAliasOutput
  - typings.atAwsDashSdkClientDashKmsDashBrowser.typesUpdateKeyDescriptionOutputMod.UpdateKeyDescriptionOutput
*/
trait OutputTypesUnion extends js.Object

