package typings
package adoneLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait Anon_DEFAULTSETTINGSENABLEPUSH extends js.Object {
  val DEFAULT_SETTINGS_ENABLE_PUSH: scala.Double
  val DEFAULT_SETTINGS_HEADER_TABLE_SIZE: scala.Double
  val DEFAULT_SETTINGS_INITIAL_WINDOW_SIZE: scala.Double
  val DEFAULT_SETTINGS_MAX_FRAME_SIZE: scala.Double
  val HTTP2_HEADER_ACCEPT: java.lang.String
  val HTTP2_HEADER_ACCEPT_CHARSET: java.lang.String
  val HTTP2_HEADER_ACCEPT_ENCODING: java.lang.String
  val HTTP2_HEADER_ACCEPT_LANGUAGE: java.lang.String
  val HTTP2_HEADER_ACCEPT_RANGES: java.lang.String
  val HTTP2_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN: java.lang.String
  val HTTP2_HEADER_AGE: java.lang.String
  val HTTP2_HEADER_ALLOW: java.lang.String
  val HTTP2_HEADER_AUTHORITY: java.lang.String
  val HTTP2_HEADER_AUTHORIZATION: java.lang.String
  val HTTP2_HEADER_CACHE_CONTROL: java.lang.String
  val HTTP2_HEADER_CONNECTION: java.lang.String
  val HTTP2_HEADER_CONTENT_DISPOSITION: java.lang.String
  val HTTP2_HEADER_CONTENT_ENCODING: java.lang.String
  val HTTP2_HEADER_CONTENT_LANGUAGE: java.lang.String
  val HTTP2_HEADER_CONTENT_LENGTH: java.lang.String
  val HTTP2_HEADER_CONTENT_LOCATION: java.lang.String
  val HTTP2_HEADER_CONTENT_MD5: java.lang.String
  val HTTP2_HEADER_CONTENT_RANGE: java.lang.String
  val HTTP2_HEADER_CONTENT_TYPE: java.lang.String
  val HTTP2_HEADER_COOKIE: java.lang.String
  val HTTP2_HEADER_DATE: java.lang.String
  val HTTP2_HEADER_ETAG: java.lang.String
  val HTTP2_HEADER_EXPECT: java.lang.String
  val HTTP2_HEADER_EXPIRES: java.lang.String
  val HTTP2_HEADER_FROM: java.lang.String
  val HTTP2_HEADER_HOST: java.lang.String
  val HTTP2_HEADER_HTTP2_SETTINGS: java.lang.String
  val HTTP2_HEADER_IF_MATCH: java.lang.String
  val HTTP2_HEADER_IF_MODIFIED_SINCE: java.lang.String
  val HTTP2_HEADER_IF_NONE_MATCH: java.lang.String
  val HTTP2_HEADER_IF_RANGE: java.lang.String
  val HTTP2_HEADER_IF_UNMODIFIED_SINCE: java.lang.String
  val HTTP2_HEADER_KEEP_ALIVE: java.lang.String
  val HTTP2_HEADER_LAST_MODIFIED: java.lang.String
  val HTTP2_HEADER_LINK: java.lang.String
  val HTTP2_HEADER_LOCATION: java.lang.String
  val HTTP2_HEADER_MAX_FORWARDS: java.lang.String
  val HTTP2_HEADER_METHOD: java.lang.String
  val HTTP2_HEADER_PATH: java.lang.String
  val HTTP2_HEADER_PREFER: java.lang.String
  val HTTP2_HEADER_PROXY_AUTHENTICATE: java.lang.String
  val HTTP2_HEADER_PROXY_AUTHORIZATION: java.lang.String
  val HTTP2_HEADER_PROXY_CONNECTION: java.lang.String
  val HTTP2_HEADER_RANGE: java.lang.String
  val HTTP2_HEADER_REFERER: java.lang.String
  val HTTP2_HEADER_REFRESH: java.lang.String
  val HTTP2_HEADER_RETRY_AFTER: java.lang.String
  val HTTP2_HEADER_SCHEME: java.lang.String
  val HTTP2_HEADER_SERVER: java.lang.String
  val HTTP2_HEADER_SET_COOKIE: java.lang.String
  val HTTP2_HEADER_STATUS: java.lang.String
  val HTTP2_HEADER_STRICT_TRANSPORT_SECURITY: java.lang.String
  val HTTP2_HEADER_TE: java.lang.String
  val HTTP2_HEADER_TRANSFER_ENCODING: java.lang.String
  val HTTP2_HEADER_UPGRADE: java.lang.String
  val HTTP2_HEADER_USER_AGENT: java.lang.String
  val HTTP2_HEADER_VARY: java.lang.String
  val HTTP2_HEADER_VIA: java.lang.String
  val HTTP2_HEADER_WWW_AUTHENTICATE: java.lang.String
  val HTTP2_METHOD_ACL: java.lang.String
  val HTTP2_METHOD_BASELINE_CONTROL: java.lang.String
  val HTTP2_METHOD_BIND: java.lang.String
  val HTTP2_METHOD_CHECKIN: java.lang.String
  val HTTP2_METHOD_CHECKOUT: java.lang.String
  val HTTP2_METHOD_CONNECT: java.lang.String
  val HTTP2_METHOD_COPY: java.lang.String
  val HTTP2_METHOD_DELETE: java.lang.String
  val HTTP2_METHOD_GET: java.lang.String
  val HTTP2_METHOD_HEAD: java.lang.String
  val HTTP2_METHOD_LABEL: java.lang.String
  val HTTP2_METHOD_LINK: java.lang.String
  val HTTP2_METHOD_LOCK: java.lang.String
  val HTTP2_METHOD_MERGE: java.lang.String
  val HTTP2_METHOD_MKACTIVITY: java.lang.String
  val HTTP2_METHOD_MKCALENDAR: java.lang.String
  val HTTP2_METHOD_MKCOL: java.lang.String
  val HTTP2_METHOD_MKREDIRECTREF: java.lang.String
  val HTTP2_METHOD_MKWORKSPACE: java.lang.String
  val HTTP2_METHOD_MOVE: java.lang.String
  val HTTP2_METHOD_OPTIONS: java.lang.String
  val HTTP2_METHOD_ORDERPATCH: java.lang.String
  val HTTP2_METHOD_PATCH: java.lang.String
  val HTTP2_METHOD_POST: java.lang.String
  val HTTP2_METHOD_PRI: java.lang.String
  val HTTP2_METHOD_PROPFIND: java.lang.String
  val HTTP2_METHOD_PROPPATCH: java.lang.String
  val HTTP2_METHOD_PUT: java.lang.String
  val HTTP2_METHOD_REBIND: java.lang.String
  val HTTP2_METHOD_REPORT: java.lang.String
  val HTTP2_METHOD_SEARCH: java.lang.String
  val HTTP2_METHOD_TRACE: java.lang.String
  val HTTP2_METHOD_UNBIND: java.lang.String
  val HTTP2_METHOD_UNCHECKOUT: java.lang.String
  val HTTP2_METHOD_UNLINK: java.lang.String
  val HTTP2_METHOD_UNLOCK: java.lang.String
  val HTTP2_METHOD_UPDATE: java.lang.String
  val HTTP2_METHOD_UPDATEREDIRECTREF: java.lang.String
  val HTTP2_METHOD_VERSION_CONTROL: java.lang.String
  val HTTP_STATUS_ACCEPTED: scala.Double
  val HTTP_STATUS_ALREADY_REPORTED: scala.Double
  val HTTP_STATUS_BAD_GATEWAY: scala.Double
  val HTTP_STATUS_BAD_REQUEST: scala.Double
  val HTTP_STATUS_BANDWIDTH_LIMIT_EXCEEDED: scala.Double
  val HTTP_STATUS_CONFLICT: scala.Double
  val HTTP_STATUS_CONTINUE: scala.Double
  val HTTP_STATUS_CREATED: scala.Double
  val HTTP_STATUS_EXPECTATION_FAILED: scala.Double
  val HTTP_STATUS_FAILED_DEPENDENCY: scala.Double
  val HTTP_STATUS_FORBIDDEN: scala.Double
  val HTTP_STATUS_FOUND: scala.Double
  val HTTP_STATUS_GATEWAY_TIMEOUT: scala.Double
  val HTTP_STATUS_GONE: scala.Double
  val HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED: scala.Double
  val HTTP_STATUS_IM_USED: scala.Double
  val HTTP_STATUS_INSUFFICIENT_STORAGE: scala.Double
  val HTTP_STATUS_INTERNAL_SERVER_ERROR: scala.Double
  val HTTP_STATUS_LENGTH_REQUIRED: scala.Double
  val HTTP_STATUS_LOCKED: scala.Double
  val HTTP_STATUS_LOOP_DETECTED: scala.Double
  val HTTP_STATUS_METHOD_NOT_ALLOWED: scala.Double
  val HTTP_STATUS_MISDIRECTED_REQUEST: scala.Double
  val HTTP_STATUS_MOVED_PERMANENTLY: scala.Double
  val HTTP_STATUS_MULTIPLE_CHOICES: scala.Double
  val HTTP_STATUS_MULTI_STATUS: scala.Double
  val HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED: scala.Double
  val HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION: scala.Double
  val HTTP_STATUS_NOT_ACCEPTABLE: scala.Double
  val HTTP_STATUS_NOT_EXTENDED: scala.Double
  val HTTP_STATUS_NOT_FOUND: scala.Double
  val HTTP_STATUS_NOT_IMPLEMENTED: scala.Double
  val HTTP_STATUS_NOT_MODIFIED: scala.Double
  val HTTP_STATUS_NO_CONTENT: scala.Double
  val HTTP_STATUS_OK: scala.Double
  val HTTP_STATUS_PARTIAL_CONTENT: scala.Double
  val HTTP_STATUS_PAYLOAD_TOO_LARGE: scala.Double
  val HTTP_STATUS_PAYMENT_REQUIRED: scala.Double
  val HTTP_STATUS_PERMANENT_REDIRECT: scala.Double
  val HTTP_STATUS_PRECONDITION_FAILED: scala.Double
  val HTTP_STATUS_PRECONDITION_REQUIRED: scala.Double
  val HTTP_STATUS_PROCESSING: scala.Double
  val HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED: scala.Double
  val HTTP_STATUS_RANGE_NOT_SATISFIABLE: scala.Double
  val HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE: scala.Double
  val HTTP_STATUS_REQUEST_TIMEOUT: scala.Double
  val HTTP_STATUS_RESET_CONTENT: scala.Double
  val HTTP_STATUS_SEE_OTHER: scala.Double
  val HTTP_STATUS_SERVICE_UNAVAILABLE: scala.Double
  val HTTP_STATUS_SWITCHING_PROTOCOLS: scala.Double
  val HTTP_STATUS_TEAPOT: scala.Double
  val HTTP_STATUS_TEMPORARY_REDIRECT: scala.Double
  val HTTP_STATUS_TOO_MANY_REQUESTS: scala.Double
  val HTTP_STATUS_UNAUTHORIZED: scala.Double
  val HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS: scala.Double
  val HTTP_STATUS_UNORDERED_COLLECTION: scala.Double
  val HTTP_STATUS_UNPROCESSABLE_ENTITY: scala.Double
  val HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE: scala.Double
  val HTTP_STATUS_UPGRADE_REQUIRED: scala.Double
  val HTTP_STATUS_URI_TOO_LONG: scala.Double
  val HTTP_STATUS_USE_PROXY: scala.Double
  val HTTP_STATUS_VARIANT_ALSO_NEGOTIATES: scala.Double
  val MAX_INITIAL_WINDOW_SIZE: scala.Double
  val MAX_MAX_FRAME_SIZE: scala.Double
  val MIN_MAX_FRAME_SIZE: scala.Double
  val NGHTTP2_CANCEL: scala.Double
  val NGHTTP2_COMPRESSION_ERROR: scala.Double
  val NGHTTP2_CONNECT_ERROR: scala.Double
  val NGHTTP2_DEFAULT_WEIGHT: scala.Double
  val NGHTTP2_ENHANCE_YOUR_CALM: scala.Double
  val NGHTTP2_ERR_FRAME_SIZE_ERROR: scala.Double
  val NGHTTP2_FLAG_ACK: scala.Double
  val NGHTTP2_FLAG_END_HEADERS: scala.Double
  val NGHTTP2_FLAG_END_STREAM: scala.Double
  val NGHTTP2_FLAG_NONE: scala.Double
  val NGHTTP2_FLAG_PADDED: scala.Double
  val NGHTTP2_FLAG_PRIORITY: scala.Double
  val NGHTTP2_FLOW_CONTROL_ERROR: scala.Double
  val NGHTTP2_FRAME_SIZE_ERROR: scala.Double
  val NGHTTP2_HTTP_1_1_REQUIRED: scala.Double
  val NGHTTP2_INADEQUATE_SECURITY: scala.Double
  val NGHTTP2_INTERNAL_ERROR: scala.Double
  val NGHTTP2_NO_ERROR: scala.Double
  val NGHTTP2_PROTOCOL_ERROR: scala.Double
  val NGHTTP2_REFUSED_STREAM: scala.Double
  val NGHTTP2_SESSION_CLIENT: scala.Double
  val NGHTTP2_SESSION_SERVER: scala.Double
  val NGHTTP2_SETTINGS_ENABLE_PUSH: scala.Double
  val NGHTTP2_SETTINGS_HEADER_TABLE_SIZE: scala.Double
  val NGHTTP2_SETTINGS_INITIAL_WINDOW_SIZE: scala.Double
  val NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS: scala.Double
  val NGHTTP2_SETTINGS_MAX_FRAME_SIZE: scala.Double
  val NGHTTP2_SETTINGS_MAX_HEADER_LIST_SIZE: scala.Double
  val NGHTTP2_SETTINGS_TIMEOUT: scala.Double
  val NGHTTP2_STREAM_CLOSED: scala.Double
  val NGHTTP2_STREAM_STATE_CLOSED: scala.Double
  val NGHTTP2_STREAM_STATE_HALF_CLOSED_LOCAL: scala.Double
  val NGHTTP2_STREAM_STATE_HALF_CLOSED_REMOTE: scala.Double
  val NGHTTP2_STREAM_STATE_IDLE: scala.Double
  val NGHTTP2_STREAM_STATE_OPEN: scala.Double
  val NGHTTP2_STREAM_STATE_RESERVED_LOCAL: scala.Double
  val NGHTTP2_STREAM_STATE_RESERVED_REMOTE: scala.Double
  val PADDING_STRATEGY_CALLBACK: scala.Double
  val PADDING_STRATEGY_MAX: scala.Double
  val PADDING_STRATEGY_NONE: scala.Double
}

object Anon_DEFAULTSETTINGSENABLEPUSH {
  @scala.inline
  def apply(
    DEFAULT_SETTINGS_ENABLE_PUSH: scala.Double,
    DEFAULT_SETTINGS_HEADER_TABLE_SIZE: scala.Double,
    DEFAULT_SETTINGS_INITIAL_WINDOW_SIZE: scala.Double,
    DEFAULT_SETTINGS_MAX_FRAME_SIZE: scala.Double,
    HTTP2_HEADER_ACCEPT: java.lang.String,
    HTTP2_HEADER_ACCEPT_CHARSET: java.lang.String,
    HTTP2_HEADER_ACCEPT_ENCODING: java.lang.String,
    HTTP2_HEADER_ACCEPT_LANGUAGE: java.lang.String,
    HTTP2_HEADER_ACCEPT_RANGES: java.lang.String,
    HTTP2_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN: java.lang.String,
    HTTP2_HEADER_AGE: java.lang.String,
    HTTP2_HEADER_ALLOW: java.lang.String,
    HTTP2_HEADER_AUTHORITY: java.lang.String,
    HTTP2_HEADER_AUTHORIZATION: java.lang.String,
    HTTP2_HEADER_CACHE_CONTROL: java.lang.String,
    HTTP2_HEADER_CONNECTION: java.lang.String,
    HTTP2_HEADER_CONTENT_DISPOSITION: java.lang.String,
    HTTP2_HEADER_CONTENT_ENCODING: java.lang.String,
    HTTP2_HEADER_CONTENT_LANGUAGE: java.lang.String,
    HTTP2_HEADER_CONTENT_LENGTH: java.lang.String,
    HTTP2_HEADER_CONTENT_LOCATION: java.lang.String,
    HTTP2_HEADER_CONTENT_MD5: java.lang.String,
    HTTP2_HEADER_CONTENT_RANGE: java.lang.String,
    HTTP2_HEADER_CONTENT_TYPE: java.lang.String,
    HTTP2_HEADER_COOKIE: java.lang.String,
    HTTP2_HEADER_DATE: java.lang.String,
    HTTP2_HEADER_ETAG: java.lang.String,
    HTTP2_HEADER_EXPECT: java.lang.String,
    HTTP2_HEADER_EXPIRES: java.lang.String,
    HTTP2_HEADER_FROM: java.lang.String,
    HTTP2_HEADER_HOST: java.lang.String,
    HTTP2_HEADER_HTTP2_SETTINGS: java.lang.String,
    HTTP2_HEADER_IF_MATCH: java.lang.String,
    HTTP2_HEADER_IF_MODIFIED_SINCE: java.lang.String,
    HTTP2_HEADER_IF_NONE_MATCH: java.lang.String,
    HTTP2_HEADER_IF_RANGE: java.lang.String,
    HTTP2_HEADER_IF_UNMODIFIED_SINCE: java.lang.String,
    HTTP2_HEADER_KEEP_ALIVE: java.lang.String,
    HTTP2_HEADER_LAST_MODIFIED: java.lang.String,
    HTTP2_HEADER_LINK: java.lang.String,
    HTTP2_HEADER_LOCATION: java.lang.String,
    HTTP2_HEADER_MAX_FORWARDS: java.lang.String,
    HTTP2_HEADER_METHOD: java.lang.String,
    HTTP2_HEADER_PATH: java.lang.String,
    HTTP2_HEADER_PREFER: java.lang.String,
    HTTP2_HEADER_PROXY_AUTHENTICATE: java.lang.String,
    HTTP2_HEADER_PROXY_AUTHORIZATION: java.lang.String,
    HTTP2_HEADER_PROXY_CONNECTION: java.lang.String,
    HTTP2_HEADER_RANGE: java.lang.String,
    HTTP2_HEADER_REFERER: java.lang.String,
    HTTP2_HEADER_REFRESH: java.lang.String,
    HTTP2_HEADER_RETRY_AFTER: java.lang.String,
    HTTP2_HEADER_SCHEME: java.lang.String,
    HTTP2_HEADER_SERVER: java.lang.String,
    HTTP2_HEADER_SET_COOKIE: java.lang.String,
    HTTP2_HEADER_STATUS: java.lang.String,
    HTTP2_HEADER_STRICT_TRANSPORT_SECURITY: java.lang.String,
    HTTP2_HEADER_TE: java.lang.String,
    HTTP2_HEADER_TRANSFER_ENCODING: java.lang.String,
    HTTP2_HEADER_UPGRADE: java.lang.String,
    HTTP2_HEADER_USER_AGENT: java.lang.String,
    HTTP2_HEADER_VARY: java.lang.String,
    HTTP2_HEADER_VIA: java.lang.String,
    HTTP2_HEADER_WWW_AUTHENTICATE: java.lang.String,
    HTTP2_METHOD_ACL: java.lang.String,
    HTTP2_METHOD_BASELINE_CONTROL: java.lang.String,
    HTTP2_METHOD_BIND: java.lang.String,
    HTTP2_METHOD_CHECKIN: java.lang.String,
    HTTP2_METHOD_CHECKOUT: java.lang.String,
    HTTP2_METHOD_CONNECT: java.lang.String,
    HTTP2_METHOD_COPY: java.lang.String,
    HTTP2_METHOD_DELETE: java.lang.String,
    HTTP2_METHOD_GET: java.lang.String,
    HTTP2_METHOD_HEAD: java.lang.String,
    HTTP2_METHOD_LABEL: java.lang.String,
    HTTP2_METHOD_LINK: java.lang.String,
    HTTP2_METHOD_LOCK: java.lang.String,
    HTTP2_METHOD_MERGE: java.lang.String,
    HTTP2_METHOD_MKACTIVITY: java.lang.String,
    HTTP2_METHOD_MKCALENDAR: java.lang.String,
    HTTP2_METHOD_MKCOL: java.lang.String,
    HTTP2_METHOD_MKREDIRECTREF: java.lang.String,
    HTTP2_METHOD_MKWORKSPACE: java.lang.String,
    HTTP2_METHOD_MOVE: java.lang.String,
    HTTP2_METHOD_OPTIONS: java.lang.String,
    HTTP2_METHOD_ORDERPATCH: java.lang.String,
    HTTP2_METHOD_PATCH: java.lang.String,
    HTTP2_METHOD_POST: java.lang.String,
    HTTP2_METHOD_PRI: java.lang.String,
    HTTP2_METHOD_PROPFIND: java.lang.String,
    HTTP2_METHOD_PROPPATCH: java.lang.String,
    HTTP2_METHOD_PUT: java.lang.String,
    HTTP2_METHOD_REBIND: java.lang.String,
    HTTP2_METHOD_REPORT: java.lang.String,
    HTTP2_METHOD_SEARCH: java.lang.String,
    HTTP2_METHOD_TRACE: java.lang.String,
    HTTP2_METHOD_UNBIND: java.lang.String,
    HTTP2_METHOD_UNCHECKOUT: java.lang.String,
    HTTP2_METHOD_UNLINK: java.lang.String,
    HTTP2_METHOD_UNLOCK: java.lang.String,
    HTTP2_METHOD_UPDATE: java.lang.String,
    HTTP2_METHOD_UPDATEREDIRECTREF: java.lang.String,
    HTTP2_METHOD_VERSION_CONTROL: java.lang.String,
    HTTP_STATUS_ACCEPTED: scala.Double,
    HTTP_STATUS_ALREADY_REPORTED: scala.Double,
    HTTP_STATUS_BAD_GATEWAY: scala.Double,
    HTTP_STATUS_BAD_REQUEST: scala.Double,
    HTTP_STATUS_BANDWIDTH_LIMIT_EXCEEDED: scala.Double,
    HTTP_STATUS_CONFLICT: scala.Double,
    HTTP_STATUS_CONTINUE: scala.Double,
    HTTP_STATUS_CREATED: scala.Double,
    HTTP_STATUS_EXPECTATION_FAILED: scala.Double,
    HTTP_STATUS_FAILED_DEPENDENCY: scala.Double,
    HTTP_STATUS_FORBIDDEN: scala.Double,
    HTTP_STATUS_FOUND: scala.Double,
    HTTP_STATUS_GATEWAY_TIMEOUT: scala.Double,
    HTTP_STATUS_GONE: scala.Double,
    HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED: scala.Double,
    HTTP_STATUS_IM_USED: scala.Double,
    HTTP_STATUS_INSUFFICIENT_STORAGE: scala.Double,
    HTTP_STATUS_INTERNAL_SERVER_ERROR: scala.Double,
    HTTP_STATUS_LENGTH_REQUIRED: scala.Double,
    HTTP_STATUS_LOCKED: scala.Double,
    HTTP_STATUS_LOOP_DETECTED: scala.Double,
    HTTP_STATUS_METHOD_NOT_ALLOWED: scala.Double,
    HTTP_STATUS_MISDIRECTED_REQUEST: scala.Double,
    HTTP_STATUS_MOVED_PERMANENTLY: scala.Double,
    HTTP_STATUS_MULTIPLE_CHOICES: scala.Double,
    HTTP_STATUS_MULTI_STATUS: scala.Double,
    HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED: scala.Double,
    HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION: scala.Double,
    HTTP_STATUS_NOT_ACCEPTABLE: scala.Double,
    HTTP_STATUS_NOT_EXTENDED: scala.Double,
    HTTP_STATUS_NOT_FOUND: scala.Double,
    HTTP_STATUS_NOT_IMPLEMENTED: scala.Double,
    HTTP_STATUS_NOT_MODIFIED: scala.Double,
    HTTP_STATUS_NO_CONTENT: scala.Double,
    HTTP_STATUS_OK: scala.Double,
    HTTP_STATUS_PARTIAL_CONTENT: scala.Double,
    HTTP_STATUS_PAYLOAD_TOO_LARGE: scala.Double,
    HTTP_STATUS_PAYMENT_REQUIRED: scala.Double,
    HTTP_STATUS_PERMANENT_REDIRECT: scala.Double,
    HTTP_STATUS_PRECONDITION_FAILED: scala.Double,
    HTTP_STATUS_PRECONDITION_REQUIRED: scala.Double,
    HTTP_STATUS_PROCESSING: scala.Double,
    HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED: scala.Double,
    HTTP_STATUS_RANGE_NOT_SATISFIABLE: scala.Double,
    HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE: scala.Double,
    HTTP_STATUS_REQUEST_TIMEOUT: scala.Double,
    HTTP_STATUS_RESET_CONTENT: scala.Double,
    HTTP_STATUS_SEE_OTHER: scala.Double,
    HTTP_STATUS_SERVICE_UNAVAILABLE: scala.Double,
    HTTP_STATUS_SWITCHING_PROTOCOLS: scala.Double,
    HTTP_STATUS_TEAPOT: scala.Double,
    HTTP_STATUS_TEMPORARY_REDIRECT: scala.Double,
    HTTP_STATUS_TOO_MANY_REQUESTS: scala.Double,
    HTTP_STATUS_UNAUTHORIZED: scala.Double,
    HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS: scala.Double,
    HTTP_STATUS_UNORDERED_COLLECTION: scala.Double,
    HTTP_STATUS_UNPROCESSABLE_ENTITY: scala.Double,
    HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE: scala.Double,
    HTTP_STATUS_UPGRADE_REQUIRED: scala.Double,
    HTTP_STATUS_URI_TOO_LONG: scala.Double,
    HTTP_STATUS_USE_PROXY: scala.Double,
    HTTP_STATUS_VARIANT_ALSO_NEGOTIATES: scala.Double,
    MAX_INITIAL_WINDOW_SIZE: scala.Double,
    MAX_MAX_FRAME_SIZE: scala.Double,
    MIN_MAX_FRAME_SIZE: scala.Double,
    NGHTTP2_CANCEL: scala.Double,
    NGHTTP2_COMPRESSION_ERROR: scala.Double,
    NGHTTP2_CONNECT_ERROR: scala.Double,
    NGHTTP2_DEFAULT_WEIGHT: scala.Double,
    NGHTTP2_ENHANCE_YOUR_CALM: scala.Double,
    NGHTTP2_ERR_FRAME_SIZE_ERROR: scala.Double,
    NGHTTP2_FLAG_ACK: scala.Double,
    NGHTTP2_FLAG_END_HEADERS: scala.Double,
    NGHTTP2_FLAG_END_STREAM: scala.Double,
    NGHTTP2_FLAG_NONE: scala.Double,
    NGHTTP2_FLAG_PADDED: scala.Double,
    NGHTTP2_FLAG_PRIORITY: scala.Double,
    NGHTTP2_FLOW_CONTROL_ERROR: scala.Double,
    NGHTTP2_FRAME_SIZE_ERROR: scala.Double,
    NGHTTP2_HTTP_1_1_REQUIRED: scala.Double,
    NGHTTP2_INADEQUATE_SECURITY: scala.Double,
    NGHTTP2_INTERNAL_ERROR: scala.Double,
    NGHTTP2_NO_ERROR: scala.Double,
    NGHTTP2_PROTOCOL_ERROR: scala.Double,
    NGHTTP2_REFUSED_STREAM: scala.Double,
    NGHTTP2_SESSION_CLIENT: scala.Double,
    NGHTTP2_SESSION_SERVER: scala.Double,
    NGHTTP2_SETTINGS_ENABLE_PUSH: scala.Double,
    NGHTTP2_SETTINGS_HEADER_TABLE_SIZE: scala.Double,
    NGHTTP2_SETTINGS_INITIAL_WINDOW_SIZE: scala.Double,
    NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS: scala.Double,
    NGHTTP2_SETTINGS_MAX_FRAME_SIZE: scala.Double,
    NGHTTP2_SETTINGS_MAX_HEADER_LIST_SIZE: scala.Double,
    NGHTTP2_SETTINGS_TIMEOUT: scala.Double,
    NGHTTP2_STREAM_CLOSED: scala.Double,
    NGHTTP2_STREAM_STATE_CLOSED: scala.Double,
    NGHTTP2_STREAM_STATE_HALF_CLOSED_LOCAL: scala.Double,
    NGHTTP2_STREAM_STATE_HALF_CLOSED_REMOTE: scala.Double,
    NGHTTP2_STREAM_STATE_IDLE: scala.Double,
    NGHTTP2_STREAM_STATE_OPEN: scala.Double,
    NGHTTP2_STREAM_STATE_RESERVED_LOCAL: scala.Double,
    NGHTTP2_STREAM_STATE_RESERVED_REMOTE: scala.Double,
    PADDING_STRATEGY_CALLBACK: scala.Double,
    PADDING_STRATEGY_MAX: scala.Double,
    PADDING_STRATEGY_NONE: scala.Double
  ): Anon_DEFAULTSETTINGSENABLEPUSH = {
    val __obj = js.Dynamic.literal(DEFAULT_SETTINGS_ENABLE_PUSH = DEFAULT_SETTINGS_ENABLE_PUSH, DEFAULT_SETTINGS_HEADER_TABLE_SIZE = DEFAULT_SETTINGS_HEADER_TABLE_SIZE, DEFAULT_SETTINGS_INITIAL_WINDOW_SIZE = DEFAULT_SETTINGS_INITIAL_WINDOW_SIZE, DEFAULT_SETTINGS_MAX_FRAME_SIZE = DEFAULT_SETTINGS_MAX_FRAME_SIZE, HTTP2_HEADER_ACCEPT = HTTP2_HEADER_ACCEPT, HTTP2_HEADER_ACCEPT_CHARSET = HTTP2_HEADER_ACCEPT_CHARSET, HTTP2_HEADER_ACCEPT_ENCODING = HTTP2_HEADER_ACCEPT_ENCODING, HTTP2_HEADER_ACCEPT_LANGUAGE = HTTP2_HEADER_ACCEPT_LANGUAGE, HTTP2_HEADER_ACCEPT_RANGES = HTTP2_HEADER_ACCEPT_RANGES, HTTP2_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN = HTTP2_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN, HTTP2_HEADER_AGE = HTTP2_HEADER_AGE, HTTP2_HEADER_ALLOW = HTTP2_HEADER_ALLOW, HTTP2_HEADER_AUTHORITY = HTTP2_HEADER_AUTHORITY, HTTP2_HEADER_AUTHORIZATION = HTTP2_HEADER_AUTHORIZATION, HTTP2_HEADER_CACHE_CONTROL = HTTP2_HEADER_CACHE_CONTROL, HTTP2_HEADER_CONNECTION = HTTP2_HEADER_CONNECTION, HTTP2_HEADER_CONTENT_DISPOSITION = HTTP2_HEADER_CONTENT_DISPOSITION, HTTP2_HEADER_CONTENT_ENCODING = HTTP2_HEADER_CONTENT_ENCODING, HTTP2_HEADER_CONTENT_LANGUAGE = HTTP2_HEADER_CONTENT_LANGUAGE, HTTP2_HEADER_CONTENT_LENGTH = HTTP2_HEADER_CONTENT_LENGTH, HTTP2_HEADER_CONTENT_LOCATION = HTTP2_HEADER_CONTENT_LOCATION, HTTP2_HEADER_CONTENT_MD5 = HTTP2_HEADER_CONTENT_MD5, HTTP2_HEADER_CONTENT_RANGE = HTTP2_HEADER_CONTENT_RANGE, HTTP2_HEADER_CONTENT_TYPE = HTTP2_HEADER_CONTENT_TYPE, HTTP2_HEADER_COOKIE = HTTP2_HEADER_COOKIE, HTTP2_HEADER_DATE = HTTP2_HEADER_DATE, HTTP2_HEADER_ETAG = HTTP2_HEADER_ETAG, HTTP2_HEADER_EXPECT = HTTP2_HEADER_EXPECT, HTTP2_HEADER_EXPIRES = HTTP2_HEADER_EXPIRES, HTTP2_HEADER_FROM = HTTP2_HEADER_FROM, HTTP2_HEADER_HOST = HTTP2_HEADER_HOST, HTTP2_HEADER_HTTP2_SETTINGS = HTTP2_HEADER_HTTP2_SETTINGS, HTTP2_HEADER_IF_MATCH = HTTP2_HEADER_IF_MATCH, HTTP2_HEADER_IF_MODIFIED_SINCE = HTTP2_HEADER_IF_MODIFIED_SINCE, HTTP2_HEADER_IF_NONE_MATCH = HTTP2_HEADER_IF_NONE_MATCH, HTTP2_HEADER_IF_RANGE = HTTP2_HEADER_IF_RANGE, HTTP2_HEADER_IF_UNMODIFIED_SINCE = HTTP2_HEADER_IF_UNMODIFIED_SINCE, HTTP2_HEADER_KEEP_ALIVE = HTTP2_HEADER_KEEP_ALIVE, HTTP2_HEADER_LAST_MODIFIED = HTTP2_HEADER_LAST_MODIFIED, HTTP2_HEADER_LINK = HTTP2_HEADER_LINK, HTTP2_HEADER_LOCATION = HTTP2_HEADER_LOCATION, HTTP2_HEADER_MAX_FORWARDS = HTTP2_HEADER_MAX_FORWARDS, HTTP2_HEADER_METHOD = HTTP2_HEADER_METHOD, HTTP2_HEADER_PATH = HTTP2_HEADER_PATH, HTTP2_HEADER_PREFER = HTTP2_HEADER_PREFER, HTTP2_HEADER_PROXY_AUTHENTICATE = HTTP2_HEADER_PROXY_AUTHENTICATE, HTTP2_HEADER_PROXY_AUTHORIZATION = HTTP2_HEADER_PROXY_AUTHORIZATION, HTTP2_HEADER_PROXY_CONNECTION = HTTP2_HEADER_PROXY_CONNECTION, HTTP2_HEADER_RANGE = HTTP2_HEADER_RANGE, HTTP2_HEADER_REFERER = HTTP2_HEADER_REFERER, HTTP2_HEADER_REFRESH = HTTP2_HEADER_REFRESH, HTTP2_HEADER_RETRY_AFTER = HTTP2_HEADER_RETRY_AFTER, HTTP2_HEADER_SCHEME = HTTP2_HEADER_SCHEME, HTTP2_HEADER_SERVER = HTTP2_HEADER_SERVER, HTTP2_HEADER_SET_COOKIE = HTTP2_HEADER_SET_COOKIE, HTTP2_HEADER_STATUS = HTTP2_HEADER_STATUS, HTTP2_HEADER_STRICT_TRANSPORT_SECURITY = HTTP2_HEADER_STRICT_TRANSPORT_SECURITY, HTTP2_HEADER_TE = HTTP2_HEADER_TE, HTTP2_HEADER_TRANSFER_ENCODING = HTTP2_HEADER_TRANSFER_ENCODING, HTTP2_HEADER_UPGRADE = HTTP2_HEADER_UPGRADE, HTTP2_HEADER_USER_AGENT = HTTP2_HEADER_USER_AGENT, HTTP2_HEADER_VARY = HTTP2_HEADER_VARY, HTTP2_HEADER_VIA = HTTP2_HEADER_VIA, HTTP2_HEADER_WWW_AUTHENTICATE = HTTP2_HEADER_WWW_AUTHENTICATE, HTTP2_METHOD_ACL = HTTP2_METHOD_ACL, HTTP2_METHOD_BASELINE_CONTROL = HTTP2_METHOD_BASELINE_CONTROL, HTTP2_METHOD_BIND = HTTP2_METHOD_BIND, HTTP2_METHOD_CHECKIN = HTTP2_METHOD_CHECKIN, HTTP2_METHOD_CHECKOUT = HTTP2_METHOD_CHECKOUT, HTTP2_METHOD_CONNECT = HTTP2_METHOD_CONNECT, HTTP2_METHOD_COPY = HTTP2_METHOD_COPY, HTTP2_METHOD_DELETE = HTTP2_METHOD_DELETE, HTTP2_METHOD_GET = HTTP2_METHOD_GET, HTTP2_METHOD_HEAD = HTTP2_METHOD_HEAD, HTTP2_METHOD_LABEL = HTTP2_METHOD_LABEL, HTTP2_METHOD_LINK = HTTP2_METHOD_LINK, HTTP2_METHOD_LOCK = HTTP2_METHOD_LOCK, HTTP2_METHOD_MERGE = HTTP2_METHOD_MERGE, HTTP2_METHOD_MKACTIVITY = HTTP2_METHOD_MKACTIVITY, HTTP2_METHOD_MKCALENDAR = HTTP2_METHOD_MKCALENDAR, HTTP2_METHOD_MKCOL = HTTP2_METHOD_MKCOL, HTTP2_METHOD_MKREDIRECTREF = HTTP2_METHOD_MKREDIRECTREF, HTTP2_METHOD_MKWORKSPACE = HTTP2_METHOD_MKWORKSPACE, HTTP2_METHOD_MOVE = HTTP2_METHOD_MOVE, HTTP2_METHOD_OPTIONS = HTTP2_METHOD_OPTIONS, HTTP2_METHOD_ORDERPATCH = HTTP2_METHOD_ORDERPATCH, HTTP2_METHOD_PATCH = HTTP2_METHOD_PATCH, HTTP2_METHOD_POST = HTTP2_METHOD_POST, HTTP2_METHOD_PRI = HTTP2_METHOD_PRI, HTTP2_METHOD_PROPFIND = HTTP2_METHOD_PROPFIND, HTTP2_METHOD_PROPPATCH = HTTP2_METHOD_PROPPATCH, HTTP2_METHOD_PUT = HTTP2_METHOD_PUT, HTTP2_METHOD_REBIND = HTTP2_METHOD_REBIND, HTTP2_METHOD_REPORT = HTTP2_METHOD_REPORT, HTTP2_METHOD_SEARCH = HTTP2_METHOD_SEARCH, HTTP2_METHOD_TRACE = HTTP2_METHOD_TRACE, HTTP2_METHOD_UNBIND = HTTP2_METHOD_UNBIND, HTTP2_METHOD_UNCHECKOUT = HTTP2_METHOD_UNCHECKOUT, HTTP2_METHOD_UNLINK = HTTP2_METHOD_UNLINK, HTTP2_METHOD_UNLOCK = HTTP2_METHOD_UNLOCK, HTTP2_METHOD_UPDATE = HTTP2_METHOD_UPDATE, HTTP2_METHOD_UPDATEREDIRECTREF = HTTP2_METHOD_UPDATEREDIRECTREF, HTTP2_METHOD_VERSION_CONTROL = HTTP2_METHOD_VERSION_CONTROL, HTTP_STATUS_ACCEPTED = HTTP_STATUS_ACCEPTED, HTTP_STATUS_ALREADY_REPORTED = HTTP_STATUS_ALREADY_REPORTED, HTTP_STATUS_BAD_GATEWAY = HTTP_STATUS_BAD_GATEWAY, HTTP_STATUS_BAD_REQUEST = HTTP_STATUS_BAD_REQUEST, HTTP_STATUS_BANDWIDTH_LIMIT_EXCEEDED = HTTP_STATUS_BANDWIDTH_LIMIT_EXCEEDED, HTTP_STATUS_CONFLICT = HTTP_STATUS_CONFLICT, HTTP_STATUS_CONTINUE = HTTP_STATUS_CONTINUE, HTTP_STATUS_CREATED = HTTP_STATUS_CREATED, HTTP_STATUS_EXPECTATION_FAILED = HTTP_STATUS_EXPECTATION_FAILED, HTTP_STATUS_FAILED_DEPENDENCY = HTTP_STATUS_FAILED_DEPENDENCY, HTTP_STATUS_FORBIDDEN = HTTP_STATUS_FORBIDDEN, HTTP_STATUS_FOUND = HTTP_STATUS_FOUND, HTTP_STATUS_GATEWAY_TIMEOUT = HTTP_STATUS_GATEWAY_TIMEOUT, HTTP_STATUS_GONE = HTTP_STATUS_GONE, HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED = HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED, HTTP_STATUS_IM_USED = HTTP_STATUS_IM_USED, HTTP_STATUS_INSUFFICIENT_STORAGE = HTTP_STATUS_INSUFFICIENT_STORAGE, HTTP_STATUS_INTERNAL_SERVER_ERROR = HTTP_STATUS_INTERNAL_SERVER_ERROR, HTTP_STATUS_LENGTH_REQUIRED = HTTP_STATUS_LENGTH_REQUIRED, HTTP_STATUS_LOCKED = HTTP_STATUS_LOCKED, HTTP_STATUS_LOOP_DETECTED = HTTP_STATUS_LOOP_DETECTED, HTTP_STATUS_METHOD_NOT_ALLOWED = HTTP_STATUS_METHOD_NOT_ALLOWED, HTTP_STATUS_MISDIRECTED_REQUEST = HTTP_STATUS_MISDIRECTED_REQUEST, HTTP_STATUS_MOVED_PERMANENTLY = HTTP_STATUS_MOVED_PERMANENTLY, HTTP_STATUS_MULTIPLE_CHOICES = HTTP_STATUS_MULTIPLE_CHOICES, HTTP_STATUS_MULTI_STATUS = HTTP_STATUS_MULTI_STATUS, HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED = HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED, HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION = HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION, HTTP_STATUS_NOT_ACCEPTABLE = HTTP_STATUS_NOT_ACCEPTABLE, HTTP_STATUS_NOT_EXTENDED = HTTP_STATUS_NOT_EXTENDED, HTTP_STATUS_NOT_FOUND = HTTP_STATUS_NOT_FOUND, HTTP_STATUS_NOT_IMPLEMENTED = HTTP_STATUS_NOT_IMPLEMENTED, HTTP_STATUS_NOT_MODIFIED = HTTP_STATUS_NOT_MODIFIED, HTTP_STATUS_NO_CONTENT = HTTP_STATUS_NO_CONTENT, HTTP_STATUS_OK = HTTP_STATUS_OK, HTTP_STATUS_PARTIAL_CONTENT = HTTP_STATUS_PARTIAL_CONTENT, HTTP_STATUS_PAYLOAD_TOO_LARGE = HTTP_STATUS_PAYLOAD_TOO_LARGE, HTTP_STATUS_PAYMENT_REQUIRED = HTTP_STATUS_PAYMENT_REQUIRED, HTTP_STATUS_PERMANENT_REDIRECT = HTTP_STATUS_PERMANENT_REDIRECT, HTTP_STATUS_PRECONDITION_FAILED = HTTP_STATUS_PRECONDITION_FAILED, HTTP_STATUS_PRECONDITION_REQUIRED = HTTP_STATUS_PRECONDITION_REQUIRED, HTTP_STATUS_PROCESSING = HTTP_STATUS_PROCESSING, HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED = HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED, HTTP_STATUS_RANGE_NOT_SATISFIABLE = HTTP_STATUS_RANGE_NOT_SATISFIABLE, HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE = HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE, HTTP_STATUS_REQUEST_TIMEOUT = HTTP_STATUS_REQUEST_TIMEOUT, HTTP_STATUS_RESET_CONTENT = HTTP_STATUS_RESET_CONTENT, HTTP_STATUS_SEE_OTHER = HTTP_STATUS_SEE_OTHER, HTTP_STATUS_SERVICE_UNAVAILABLE = HTTP_STATUS_SERVICE_UNAVAILABLE, HTTP_STATUS_SWITCHING_PROTOCOLS = HTTP_STATUS_SWITCHING_PROTOCOLS, HTTP_STATUS_TEAPOT = HTTP_STATUS_TEAPOT, HTTP_STATUS_TEMPORARY_REDIRECT = HTTP_STATUS_TEMPORARY_REDIRECT, HTTP_STATUS_TOO_MANY_REQUESTS = HTTP_STATUS_TOO_MANY_REQUESTS, HTTP_STATUS_UNAUTHORIZED = HTTP_STATUS_UNAUTHORIZED, HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS = HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS, HTTP_STATUS_UNORDERED_COLLECTION = HTTP_STATUS_UNORDERED_COLLECTION, HTTP_STATUS_UNPROCESSABLE_ENTITY = HTTP_STATUS_UNPROCESSABLE_ENTITY, HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE = HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE, HTTP_STATUS_UPGRADE_REQUIRED = HTTP_STATUS_UPGRADE_REQUIRED, HTTP_STATUS_URI_TOO_LONG = HTTP_STATUS_URI_TOO_LONG, HTTP_STATUS_USE_PROXY = HTTP_STATUS_USE_PROXY, HTTP_STATUS_VARIANT_ALSO_NEGOTIATES = HTTP_STATUS_VARIANT_ALSO_NEGOTIATES, MAX_INITIAL_WINDOW_SIZE = MAX_INITIAL_WINDOW_SIZE, MAX_MAX_FRAME_SIZE = MAX_MAX_FRAME_SIZE, MIN_MAX_FRAME_SIZE = MIN_MAX_FRAME_SIZE, NGHTTP2_CANCEL = NGHTTP2_CANCEL, NGHTTP2_COMPRESSION_ERROR = NGHTTP2_COMPRESSION_ERROR, NGHTTP2_CONNECT_ERROR = NGHTTP2_CONNECT_ERROR, NGHTTP2_DEFAULT_WEIGHT = NGHTTP2_DEFAULT_WEIGHT, NGHTTP2_ENHANCE_YOUR_CALM = NGHTTP2_ENHANCE_YOUR_CALM, NGHTTP2_ERR_FRAME_SIZE_ERROR = NGHTTP2_ERR_FRAME_SIZE_ERROR, NGHTTP2_FLAG_ACK = NGHTTP2_FLAG_ACK, NGHTTP2_FLAG_END_HEADERS = NGHTTP2_FLAG_END_HEADERS, NGHTTP2_FLAG_END_STREAM = NGHTTP2_FLAG_END_STREAM, NGHTTP2_FLAG_NONE = NGHTTP2_FLAG_NONE, NGHTTP2_FLAG_PADDED = NGHTTP2_FLAG_PADDED, NGHTTP2_FLAG_PRIORITY = NGHTTP2_FLAG_PRIORITY, NGHTTP2_FLOW_CONTROL_ERROR = NGHTTP2_FLOW_CONTROL_ERROR, NGHTTP2_FRAME_SIZE_ERROR = NGHTTP2_FRAME_SIZE_ERROR, NGHTTP2_HTTP_1_1_REQUIRED = NGHTTP2_HTTP_1_1_REQUIRED, NGHTTP2_INADEQUATE_SECURITY = NGHTTP2_INADEQUATE_SECURITY, NGHTTP2_INTERNAL_ERROR = NGHTTP2_INTERNAL_ERROR, NGHTTP2_NO_ERROR = NGHTTP2_NO_ERROR, NGHTTP2_PROTOCOL_ERROR = NGHTTP2_PROTOCOL_ERROR, NGHTTP2_REFUSED_STREAM = NGHTTP2_REFUSED_STREAM, NGHTTP2_SESSION_CLIENT = NGHTTP2_SESSION_CLIENT, NGHTTP2_SESSION_SERVER = NGHTTP2_SESSION_SERVER, NGHTTP2_SETTINGS_ENABLE_PUSH = NGHTTP2_SETTINGS_ENABLE_PUSH, NGHTTP2_SETTINGS_HEADER_TABLE_SIZE = NGHTTP2_SETTINGS_HEADER_TABLE_SIZE, NGHTTP2_SETTINGS_INITIAL_WINDOW_SIZE = NGHTTP2_SETTINGS_INITIAL_WINDOW_SIZE, NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS = NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS, NGHTTP2_SETTINGS_MAX_FRAME_SIZE = NGHTTP2_SETTINGS_MAX_FRAME_SIZE, NGHTTP2_SETTINGS_MAX_HEADER_LIST_SIZE = NGHTTP2_SETTINGS_MAX_HEADER_LIST_SIZE, NGHTTP2_SETTINGS_TIMEOUT = NGHTTP2_SETTINGS_TIMEOUT, NGHTTP2_STREAM_CLOSED = NGHTTP2_STREAM_CLOSED, NGHTTP2_STREAM_STATE_CLOSED = NGHTTP2_STREAM_STATE_CLOSED, NGHTTP2_STREAM_STATE_HALF_CLOSED_LOCAL = NGHTTP2_STREAM_STATE_HALF_CLOSED_LOCAL, NGHTTP2_STREAM_STATE_HALF_CLOSED_REMOTE = NGHTTP2_STREAM_STATE_HALF_CLOSED_REMOTE, NGHTTP2_STREAM_STATE_IDLE = NGHTTP2_STREAM_STATE_IDLE, NGHTTP2_STREAM_STATE_OPEN = NGHTTP2_STREAM_STATE_OPEN, NGHTTP2_STREAM_STATE_RESERVED_LOCAL = NGHTTP2_STREAM_STATE_RESERVED_LOCAL, NGHTTP2_STREAM_STATE_RESERVED_REMOTE = NGHTTP2_STREAM_STATE_RESERVED_REMOTE, PADDING_STRATEGY_CALLBACK = PADDING_STRATEGY_CALLBACK, PADDING_STRATEGY_MAX = PADDING_STRATEGY_MAX, PADDING_STRATEGY_NONE = PADDING_STRATEGY_NONE)
  
    __obj.asInstanceOf[Anon_DEFAULTSETTINGSENABLEPUSH]
  }
}

