package typings.gapiClientFirebaserules.gapi.client.firebaserules

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait Ruleset extends js.Object {
  /**
    * Time the `Ruleset` was created.
    * Output only.
    */
  var createTime: js.UndefOr[String] = js.native
  /**
    * Name of the `Ruleset`. The ruleset_id is auto generated by the service.
    * Format: `projects/{project_id}/rulesets/{ruleset_id}`
    * Output only.
    */
  var name: js.UndefOr[String] = js.native
  /** `Source` for the `Ruleset`. */
  var source: js.UndefOr[Source] = js.native
}

object Ruleset {
  @scala.inline
  def apply(): Ruleset = {
    val __obj = js.Dynamic.literal()
    __obj.asInstanceOf[Ruleset]
  }
  @scala.inline
  implicit class RulesetOps[Self <: Ruleset] (val x: Self) extends AnyVal {
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    @scala.inline
    def set(key: String, value: js.Any): Self = {
        x.asInstanceOf[js.Dynamic].updateDynamic(key)(value)
        x
    }
    @scala.inline
    def setCreateTime(value: String): Self = this.set("createTime", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteCreateTime: Self = this.set("createTime", js.undefined)
    @scala.inline
    def setName(value: String): Self = this.set("name", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteName: Self = this.set("name", js.undefined)
    @scala.inline
    def setSource(value: Source): Self = this.set("source", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteSource: Self = this.set("source", js.undefined)
  }
  
}

