package typings
package fastDashJsonDashPatchLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object libHelpersMod {
  type JsonPatchErrorName = fastDashJsonDashPatchLib.fastDashJsonDashPatchLibStrings.SEQUENCE_NOT_AN_ARRAY | fastDashJsonDashPatchLib.fastDashJsonDashPatchLibStrings.OPERATION_NOT_AN_OBJECT | fastDashJsonDashPatchLib.fastDashJsonDashPatchLibStrings.OPERATION_OP_INVALID | fastDashJsonDashPatchLib.fastDashJsonDashPatchLibStrings.OPERATION_PATH_INVALID | fastDashJsonDashPatchLib.fastDashJsonDashPatchLibStrings.OPERATION_FROM_REQUIRED | fastDashJsonDashPatchLib.fastDashJsonDashPatchLibStrings.OPERATION_VALUE_REQUIRED | fastDashJsonDashPatchLib.fastDashJsonDashPatchLibStrings.OPERATION_VALUE_CANNOT_CONTAIN_UNDEFINED | fastDashJsonDashPatchLib.fastDashJsonDashPatchLibStrings.OPERATION_PATH_CANNOT_ADD | fastDashJsonDashPatchLib.fastDashJsonDashPatchLibStrings.OPERATION_PATH_UNRESOLVABLE | fastDashJsonDashPatchLib.fastDashJsonDashPatchLibStrings.OPERATION_FROM_UNRESOLVABLE | fastDashJsonDashPatchLib.fastDashJsonDashPatchLibStrings.OPERATION_PATH_ILLEGAL_ARRAY_INDEX | fastDashJsonDashPatchLib.fastDashJsonDashPatchLibStrings.OPERATION_VALUE_OUT_OF_BOUNDS | fastDashJsonDashPatchLib.fastDashJsonDashPatchLibStrings.TEST_OPERATION_FAILED
}
