package typings.atAwsDashSdkClientDashDynamodbDashBrowser

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object typesUnderscoreAutoScalingTargetTrackingScalingPolicyConfigurationUpdateMod {
  type _UnmarshalledAutoScalingTargetTrackingScalingPolicyConfigurationUpdate = _AutoScalingTargetTrackingScalingPolicyConfigurationUpdate
}
