package typings
package reactDashContentDashLoaderLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait reactDashContentDashLoaderLibProps {
  @scala.inline
  def BulletListProps: reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps.type = reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps
  type BulletListProps = reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps
  @scala.inline
  def CodeProps: reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps.type = reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps
  type CodeProps = reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps
  @scala.inline
  def FacebookProps: reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps.type = reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps
  type FacebookProps = reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps
  @scala.inline
  def InstagramProps: reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps.type = reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps
  type InstagramProps = reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps
  @scala.inline
  def ListProps: reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps.type = reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps
  type ListProps = reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps
  @scala.inline
  def ReactDashContentDashLoaderProps: reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps.type = reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps
  type ReactDashContentDashLoaderProps = reactDashContentDashLoaderLib.reactDashContentDashLoaderMod.ContentLoaderProps
}

