package typings.actionsDashOnDashGoogle.distServiceActionssdkConversationConversationMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotPermissionValueSpec
  - typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotOptionValueSpec
  - typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotTransactionRequirementsCheckSpec
  - typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotDeliveryAddressValueSpec
  - typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotTransactionDecisionValueSpec
  - typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotConfirmationValueSpec
  - typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotDateTimeValueSpec
  - typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotNewSurfaceValueSpec
  - typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotRegisterUpdateValueSpec
  - typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotSignInValueSpec
  - typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotPlaceValueSpec
  - typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotLinkValueSpec
  - typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDottransactionsDotv3DotCompletePurchaseValueSpec
  - typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDottransactionsDotv3DotTransactionDecisionValueSpec
  - typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDottransactionsDotv3DotTransactionRequirementsCheckSpec
  - typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDottransactionsDotv3DotDigitalPurchaseCheckSpec
*/
trait InputValueSpec extends js.Object

object InputValueSpec {
  @scala.inline
  /* private */ def cast[T](in: js.Any): T = in.asInstanceOf[T]
  @scala.inline
  def typeDotgoogleapisDotcomSlashgoogleDotactionsDottransactionsDotv3DotCompletePurchaseValueSpec: typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDottransactionsDotv3DotCompletePurchaseValueSpec = this.cast("type.googleapis.com/google.actions.transactions.v3.CompletePurchaseValueSpec")
  @scala.inline
  def typeDotgoogleapisDotcomSlashgoogleDotactionsDottransactionsDotv3DotDigitalPurchaseCheckSpec: typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDottransactionsDotv3DotDigitalPurchaseCheckSpec = this.cast("type.googleapis.com/google.actions.transactions.v3.DigitalPurchaseCheckSpec")
  @scala.inline
  def typeDotgoogleapisDotcomSlashgoogleDotactionsDottransactionsDotv3DotTransactionDecisionValueSpec: typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDottransactionsDotv3DotTransactionDecisionValueSpec = this.cast("type.googleapis.com/google.actions.transactions.v3.TransactionDecisionValueSpec")
  @scala.inline
  def typeDotgoogleapisDotcomSlashgoogleDotactionsDottransactionsDotv3DotTransactionRequirementsCheckSpec: typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDottransactionsDotv3DotTransactionRequirementsCheckSpec = this.cast("type.googleapis.com/google.actions.transactions.v3.TransactionRequirementsCheckSpec")
  @scala.inline
  def typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotConfirmationValueSpec: typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotConfirmationValueSpec = this.cast("type.googleapis.com/google.actions.v2.ConfirmationValueSpec")
  @scala.inline
  def typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotDateTimeValueSpec: typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotDateTimeValueSpec = this.cast("type.googleapis.com/google.actions.v2.DateTimeValueSpec")
  @scala.inline
  def typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotDeliveryAddressValueSpec: typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotDeliveryAddressValueSpec = this.cast("type.googleapis.com/google.actions.v2.DeliveryAddressValueSpec")
  @scala.inline
  def typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotLinkValueSpec: typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotLinkValueSpec = this.cast("type.googleapis.com/google.actions.v2.LinkValueSpec")
  @scala.inline
  def typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotNewSurfaceValueSpec: typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotNewSurfaceValueSpec = this.cast("type.googleapis.com/google.actions.v2.NewSurfaceValueSpec")
  @scala.inline
  def typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotOptionValueSpec: typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotOptionValueSpec = this.cast("type.googleapis.com/google.actions.v2.OptionValueSpec")
  @scala.inline
  def typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotPermissionValueSpec: typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotPermissionValueSpec = this.cast("type.googleapis.com/google.actions.v2.PermissionValueSpec")
  @scala.inline
  def typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotPlaceValueSpec: typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotPlaceValueSpec = this.cast("type.googleapis.com/google.actions.v2.PlaceValueSpec")
  @scala.inline
  def typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotRegisterUpdateValueSpec: typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotRegisterUpdateValueSpec = this.cast("type.googleapis.com/google.actions.v2.RegisterUpdateValueSpec")
  @scala.inline
  def typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotSignInValueSpec: typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotSignInValueSpec = this.cast("type.googleapis.com/google.actions.v2.SignInValueSpec")
  @scala.inline
  def typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotTransactionDecisionValueSpec: typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotTransactionDecisionValueSpec = this.cast("type.googleapis.com/google.actions.v2.TransactionDecisionValueSpec")
  @scala.inline
  def typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotTransactionRequirementsCheckSpec: typings.actionsDashOnDashGoogle.actionsDashOnDashGoogleStrings.typeDotgoogleapisDotcomSlashgoogleDotactionsDotv2DotTransactionRequirementsCheckSpec = this.cast("type.googleapis.com/google.actions.v2.TransactionRequirementsCheckSpec")
}

