package typings.reactNativeFirebase

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait AnonCACHESDIRECTORYPATH extends js.Object {
  var CACHES_DIRECTORY_PATH: String
  var DOCUMENT_DIRECTORY_PATH: String
  var EXTERNAL_DIRECTORY_PATH: String
  var EXTERNAL_STORAGE_DIRECTORY_PATH: String
  var FILETYPE_DIRECTORY: String
  var FILETYPE_REGULAR: String
  var LIBRARY_DIRECTORY_PATH: String
  var MAIN_BUNDLE_PATH: String
  var TEMP_DIRECTORY_PATH: String
}

object AnonCACHESDIRECTORYPATH {
  @scala.inline
  def apply(
    CACHES_DIRECTORY_PATH: String,
    DOCUMENT_DIRECTORY_PATH: String,
    EXTERNAL_DIRECTORY_PATH: String,
    EXTERNAL_STORAGE_DIRECTORY_PATH: String,
    FILETYPE_DIRECTORY: String,
    FILETYPE_REGULAR: String,
    LIBRARY_DIRECTORY_PATH: String,
    MAIN_BUNDLE_PATH: String,
    TEMP_DIRECTORY_PATH: String
  ): AnonCACHESDIRECTORYPATH = {
    val __obj = js.Dynamic.literal(CACHES_DIRECTORY_PATH = CACHES_DIRECTORY_PATH.asInstanceOf[js.Any], DOCUMENT_DIRECTORY_PATH = DOCUMENT_DIRECTORY_PATH.asInstanceOf[js.Any], EXTERNAL_DIRECTORY_PATH = EXTERNAL_DIRECTORY_PATH.asInstanceOf[js.Any], EXTERNAL_STORAGE_DIRECTORY_PATH = EXTERNAL_STORAGE_DIRECTORY_PATH.asInstanceOf[js.Any], FILETYPE_DIRECTORY = FILETYPE_DIRECTORY.asInstanceOf[js.Any], FILETYPE_REGULAR = FILETYPE_REGULAR.asInstanceOf[js.Any], LIBRARY_DIRECTORY_PATH = LIBRARY_DIRECTORY_PATH.asInstanceOf[js.Any], MAIN_BUNDLE_PATH = MAIN_BUNDLE_PATH.asInstanceOf[js.Any], TEMP_DIRECTORY_PATH = TEMP_DIRECTORY_PATH.asInstanceOf[js.Any])
  
    __obj.asInstanceOf[AnonCACHESDIRECTORYPATH]
  }
}

