package typings
package qlikDashVisualizationextensionsLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object BackendAPINs {
  type DimensionType = qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.D | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.N | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.T
  type FieldAttributesType = qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.U | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.A | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.I | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.R | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.F | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.M | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.D | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.T | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.TS | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.IV
  type GroupingType = qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.N | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.H | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.C
  type PatchType = qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.Add | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.Remove | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.Replace
  type SortIndicatorType = qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.N | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.A | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.D
  type StateType = qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.L | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.S | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.O | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.D | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.A | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.X | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.XS | qlikDashVisualizationextensionsLib.qlikDashVisualizationextensionsLibStrings.XL
}
