package typings
package xtermLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._


trait HTMLElementTagNameMap extends js.Object {
  var a: HTMLAnchorElement
  var abbr: HTMLElement
  var address: HTMLElement
  var applet: HTMLAppletElement
  var area: HTMLAreaElement
  var article: HTMLElement
  var aside: HTMLElement
  var audio: HTMLAudioElement
  var b: HTMLElement
  var base: HTMLBaseElement
  var basefont: HTMLBaseFontElement
  var bdo: HTMLElement
  var blockquote: HTMLQuoteElement
  var body: HTMLBodyElement
  var br: HTMLBRElement
  var button: HTMLButtonElement
  var canvas: HTMLCanvasElement
  var caption: HTMLTableCaptionElement
  var cite: HTMLElement
  var code: HTMLElement
  var col: HTMLTableColElement
  var colgroup: HTMLTableColElement
  var data: HTMLDataElement
  var datalist: HTMLDataListElement
  var dd: HTMLElement
  var del: HTMLModElement
  var details: HTMLDetailsElement
  var dfn: HTMLElement
  var dialog: HTMLDialogElement
  var dir: HTMLDirectoryElement
  var div: HTMLDivElement
  var dl: HTMLDListElement
  var dt: HTMLElement
  var em: HTMLElement
  var embed: HTMLEmbedElement
  var fieldset: HTMLFieldSetElement
  var figcaption: HTMLElement
  var figure: HTMLElement
  var font: HTMLFontElement
  var footer: HTMLElement
  var form: HTMLFormElement
  var frame: HTMLFrameElement
  var frameset: HTMLFrameSetElement
  var h1: HTMLHeadingElement
  var h2: HTMLHeadingElement
  var h3: HTMLHeadingElement
  var h4: HTMLHeadingElement
  var h5: HTMLHeadingElement
  var h6: HTMLHeadingElement
  var head: HTMLHeadElement
  var header: HTMLElement
  var hgroup: HTMLElement
  var hr: HTMLHRElement
  var html: HTMLHtmlElement
  var i: HTMLElement
  var iframe: HTMLIFrameElement
  var img: HTMLImageElement
  var input: HTMLInputElement
  var ins: HTMLModElement
  var kbd: HTMLElement
  var label: HTMLLabelElement
  var legend: HTMLLegendElement
  var li: HTMLLIElement
  var link: HTMLLinkElement
  var map: HTMLMapElement
  var mark: HTMLElement
  var marquee: HTMLMarqueeElement
  var menu: HTMLMenuElement
  var meta: HTMLMetaElement
  var meter: HTMLMeterElement
  var nav: HTMLElement
  var noscript: HTMLElement
  var `object`: HTMLObjectElement
  var ol: HTMLOListElement
  var optgroup: HTMLOptGroupElement
  var option: HTMLOptionElement
  var output: HTMLOutputElement
  var p: HTMLParagraphElement
  var param: HTMLParamElement
  var picture: HTMLPictureElement
  var pre: HTMLPreElement
  var progress: HTMLProgressElement
  var q: HTMLQuoteElement
  var rt: HTMLElement
  var ruby: HTMLElement
  var s: HTMLElement
  var samp: HTMLElement
  var script: HTMLScriptElement
  var section: HTMLElement
  var select: HTMLSelectElement
  var slot: HTMLSlotElement
  var small: HTMLElement
  var source: HTMLSourceElement
  var span: HTMLSpanElement
  var strong: HTMLElement
  var style: HTMLStyleElement
  var sub: HTMLElement
  var sup: HTMLElement
  var table: HTMLTableElement
  var tbody: HTMLTableSectionElement
  var td: HTMLTableDataCellElement
  var template: HTMLTemplateElement
  var textarea: HTMLTextAreaElement
  var tfoot: HTMLTableSectionElement
  var th: HTMLTableHeaderCellElement
  var thead: HTMLTableSectionElement
  var time: HTMLTimeElement
  var title: HTMLTitleElement
  var tr: HTMLTableRowElement
  var track: HTMLTrackElement
  var u: HTMLElement
  var ul: HTMLUListElement
  var `var`: HTMLElement
  var video: HTMLVideoElement
  var wbr: HTMLElement
}

