package typings.semanticUiSearch.SemanticUI

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object SearchSettings {
  type Param = (typings.std.Pick[
    typings.semanticUiSearch.SemanticUI.SearchSettings.Impl, 
    typings.semanticUiSearch.semanticUiSearchStrings.apiSettings | typings.semanticUiSearch.semanticUiSearchStrings.`type` | typings.semanticUiSearch.semanticUiSearchStrings.minCharacters | typings.semanticUiSearch.semanticUiSearchStrings.transition | typings.semanticUiSearch.semanticUiSearchStrings.duration | typings.semanticUiSearch.semanticUiSearchStrings.maxResults | typings.semanticUiSearch.semanticUiSearchStrings.cache | typings.semanticUiSearch.semanticUiSearchStrings.source | typings.semanticUiSearch.semanticUiSearchStrings.selectFirstResult | typings.semanticUiSearch.semanticUiSearchStrings.showNoResults | typings.semanticUiSearch.semanticUiSearchStrings.searchFullText | typings.semanticUiSearch.semanticUiSearchStrings.fields | typings.semanticUiSearch.semanticUiSearchStrings.searchFields | typings.semanticUiSearch.semanticUiSearchStrings.hideDelay | typings.semanticUiSearch.semanticUiSearchStrings.searchDelay | typings.semanticUiSearch.semanticUiSearchStrings.easing | typings.semanticUiSearch.semanticUiSearchStrings.onSelect | typings.semanticUiSearch.semanticUiSearchStrings.onResultsAdd | typings.semanticUiSearch.semanticUiSearchStrings.onSearchQuery | typings.semanticUiSearch.semanticUiSearchStrings.onResults | typings.semanticUiSearch.semanticUiSearchStrings.onResultsOpen | typings.semanticUiSearch.semanticUiSearchStrings.onResultsClose | typings.semanticUiSearch.semanticUiSearchStrings.templates | typings.semanticUiSearch.semanticUiSearchStrings.regExp | typings.semanticUiSearch.semanticUiSearchStrings.selector | typings.semanticUiSearch.semanticUiSearchStrings.metadata | typings.semanticUiSearch.semanticUiSearchStrings.className | typings.semanticUiSearch.semanticUiSearchStrings.error | typings.semanticUiSearch.semanticUiSearchStrings.namespace | typings.semanticUiSearch.semanticUiSearchStrings.name | typings.semanticUiSearch.semanticUiSearchStrings.silent | typings.semanticUiSearch.semanticUiSearchStrings.debug | typings.semanticUiSearch.semanticUiSearchStrings.performance | typings.semanticUiSearch.semanticUiSearchStrings.verbose
  ]) with (typings.std.Partial[
    typings.std.Pick[
      typings.semanticUiSearch.SemanticUI.SearchSettings.Impl, 
      typings.semanticUiSearch.semanticUiSearchStrings.`type` | typings.semanticUiSearch.semanticUiSearchStrings.apiSettings | typings.semanticUiSearch.semanticUiSearchStrings.minCharacters | typings.semanticUiSearch.semanticUiSearchStrings.transition | typings.semanticUiSearch.semanticUiSearchStrings.duration | typings.semanticUiSearch.semanticUiSearchStrings.maxResults | typings.semanticUiSearch.semanticUiSearchStrings.cache | typings.semanticUiSearch.semanticUiSearchStrings.source | typings.semanticUiSearch.semanticUiSearchStrings.selectFirstResult | typings.semanticUiSearch.semanticUiSearchStrings.showNoResults | typings.semanticUiSearch.semanticUiSearchStrings.searchFullText | typings.semanticUiSearch.semanticUiSearchStrings.fields | typings.semanticUiSearch.semanticUiSearchStrings.searchFields | typings.semanticUiSearch.semanticUiSearchStrings.hideDelay | typings.semanticUiSearch.semanticUiSearchStrings.searchDelay | typings.semanticUiSearch.semanticUiSearchStrings.easing | typings.semanticUiSearch.semanticUiSearchStrings.templates | typings.semanticUiSearch.semanticUiSearchStrings.regExp | typings.semanticUiSearch.semanticUiSearchStrings.selector | typings.semanticUiSearch.semanticUiSearchStrings.metadata | typings.semanticUiSearch.semanticUiSearchStrings.className | typings.semanticUiSearch.semanticUiSearchStrings.error | typings.semanticUiSearch.semanticUiSearchStrings.namespace | typings.semanticUiSearch.semanticUiSearchStrings.name | typings.semanticUiSearch.semanticUiSearchStrings.silent | typings.semanticUiSearch.semanticUiSearchStrings.debug | typings.semanticUiSearch.semanticUiSearchStrings.performance | typings.semanticUiSearch.semanticUiSearchStrings.verbose
    ]
  ])
}
