package typings
package firefoxDashWebextDashBrowserLib.browserNs

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object underscoreManifestNs {
  type ExtensionID = java.lang.String
  type ExtensionURL = java.lang.String
  type HttpURL = java.lang.String
  type IconImageData = org.scalablytyped.runtime.NumberDictionary[ImageData] | ImageData
  type IconPath = org.scalablytyped.runtime.NumberDictionary[ExtensionURL] | ExtensionURL
  type ImageData = js.Any
  type ImageDataOrExtensionURL = java.lang.String
  type KeyName = java.lang.String
  type MatchPattern = MatchPatternRestricted | MatchPatternUnestricted | _MatchPattern
  /** Same as MatchPattern above, but excludes<all_urls></all_urls> */
  type MatchPatternRestricted = java.lang.String
  /**
    * Mostly unrestricted match patterns for privileged add-ons. This should technically be rejected for unprivileged
    * add-ons, but, reasons. The MatchPattern class will still refuse privileged schemes for those extensions.
    */
  type MatchPatternUnestricted = java.lang.String
  /** Represents a native manifest file */
  type NativeManifest = firefoxDashWebextDashBrowserLib.Anon_NamePathDescription | firefoxDashWebextDashBrowserLib.Anon_TypeStorage
  /* _manifest types */
  type OptionalPermission = _OptionalPermission
  type OptionalPermissionOrOrigin = OptionalPermission | MatchPattern
  type Permission = java.lang.String | OptionalPermission | _Permission
  type PermissionOrOrigin = Permission | MatchPattern
  /** @deprecated Event pages are not currently supported. This will run as a persistent background page. */
  type PersistentBackgroundProperty = scala.Boolean
  type ThemeColor = java.lang.String | (js.Tuple3[scala.Double, scala.Double, scala.Double]) | (js.Tuple4[scala.Double, scala.Double, scala.Double, scala.Double])
  /** @deprecated An unexpected property was found in the WebExtension manifest. */
  type UnrecognizedProperty = js.Any
  type _MatchPattern = firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.`<all_urls>`
  type _OptionalPermission = firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.browserSettings | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.cookies | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.downloads | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.downloadsDOTopen | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.clipboardRead | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.clipboardWrite | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.geolocation | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.idle | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.notifications | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.topSites | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.webNavigation | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.webRequest | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.webRequestBlocking | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.bookmarks | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.find | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.history | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.menusDOToverrideContext | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.search | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.activeTab | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.tabs | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.tabHide
  type _Permission = firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.contextualIdentities | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.dns | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.identity | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.management | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.alarms | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.mozillaAddons | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.storage | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.unlimitedStorage | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.privacy | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.proxy | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.nativeMessaging | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.telemetry | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.theme | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.browsingData | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.devtools | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.geckoProfiler | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.menus | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.contextMenus | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.pkcs11 | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.sessions
  type _ProtocolHandlerProtocol = firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.bitcoin | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.dat | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.dweb | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.geo | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.gopher | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.im | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.ipfs | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.ipns | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.irc | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.ircs | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.magnet | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.mailto | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.mms | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.news | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.nntp | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.sip | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.sms | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.smsto | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.ssb | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.ssh | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.tel | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.urn | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.webcal | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.wtai | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.xmpp
  type _ThemeTypeAdditionalBackgroundsAlignment = firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.bottom | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.center | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.left | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.right | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.top | (firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.`center bottom`) | (firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.`center center`) | (firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.`center top`) | (firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.`left bottom`) | (firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.`left center`) | (firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.`left top`) | (firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.`right bottom`) | (firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.`right center`) | (firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.`right top`)
  type _ThemeTypeAdditionalBackgroundsTiling = firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.`no-repeat` | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.repeat | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.`repeat-x` | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.`repeat-y`
  /** Defines the location the browserAction will appear by default. The default location is navbar. */
  type _WebExtensionManifestBrowserActionDefaultArea = firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.navbar | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.menupanel | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.tabstrip | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.personaltoolbar
  /** The type of param can be either "purpose" or "pref". */
  type _WebExtensionManifestChromeSettingsOverridesSearchProviderParamsCondition = firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.purpose | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.pref
  /** The context that initiates a search, required if condition is "purpose". */
  type _WebExtensionManifestChromeSettingsOverridesSearchProviderParamsPurpose = firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.contextmenu | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.searchbar | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.homepage | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.keyword | firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.newtab
  type _WebExtensionManifestIncognito = firefoxDashWebextDashBrowserLib.firefoxDashWebextDashBrowserLibStrings.spanning
}
