package typings
package nodeLib.zlibMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("zlib", "constants")
@js.native
object constantsNs extends js.Object {
  val BROTLI_DECODE: scala.Double = js.native
  val BROTLI_DECODER_ERROR_ALLOC_BLOCK_TYPE_TREES: scala.Double = js.native
  val BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MAP: scala.Double = js.native
  val BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MODES: scala.Double = js.native
  val BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_1: scala.Double = js.native
  val BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_2: scala.Double = js.native
  val BROTLI_DECODER_ERROR_ALLOC_TREE_GROUPS: scala.Double = js.native
  val BROTLI_DECODER_ERROR_DICTIONARY_NOT_SET: scala.Double = js.native
  val BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_1: scala.Double = js.native
  val BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_2: scala.Double = js.native
  val BROTLI_DECODER_ERROR_FORMAT_CL_SPACE: scala.Double = js.native
  val BROTLI_DECODER_ERROR_FORMAT_CONTEXT_MAP_REPEAT: scala.Double = js.native
  val BROTLI_DECODER_ERROR_FORMAT_DICTIONARY: scala.Double = js.native
  val BROTLI_DECODER_ERROR_FORMAT_DISTANCE: scala.Double = js.native
  val BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_META_NIBBLE: scala.Double = js.native
  val BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_NIBBLE: scala.Double = js.native
  val BROTLI_DECODER_ERROR_FORMAT_HUFFMAN_SPACE: scala.Double = js.native
  val BROTLI_DECODER_ERROR_FORMAT_PADDING_1: scala.Double = js.native
  val BROTLI_DECODER_ERROR_FORMAT_PADDING_2: scala.Double = js.native
  val BROTLI_DECODER_ERROR_FORMAT_RESERVED: scala.Double = js.native
  val BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_ALPHABET: scala.Double = js.native
  val BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_SAME: scala.Double = js.native
  val BROTLI_DECODER_ERROR_FORMAT_TRANSFORM: scala.Double = js.native
  val BROTLI_DECODER_ERROR_FORMAT_WINDOW_BITS: scala.Double = js.native
  val BROTLI_DECODER_ERROR_INVALID_ARGUMENTS: scala.Double = js.native
  val BROTLI_DECODER_ERROR_UNREACHABLE: scala.Double = js.native
  val BROTLI_DECODER_NEEDS_MORE_INPUT: scala.Double = js.native
  val BROTLI_DECODER_NEEDS_MORE_OUTPUT: scala.Double = js.native
  val BROTLI_DECODER_NO_ERROR: scala.Double = js.native
  val BROTLI_DECODER_PARAM_DISABLE_RING_BUFFER_REALLOCATION: scala.Double = js.native
  val BROTLI_DECODER_PARAM_LARGE_WINDOW: scala.Double = js.native
  val BROTLI_DECODER_RESULT_ERROR: scala.Double = js.native
  val BROTLI_DECODER_RESULT_NEEDS_MORE_INPUT: scala.Double = js.native
  val BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT: scala.Double = js.native
  val BROTLI_DECODER_RESULT_SUCCESS: scala.Double = js.native
  val BROTLI_DECODER_SUCCESS: scala.Double = js.native
  val BROTLI_DEFAULT_MODE: scala.Double = js.native
  val BROTLI_DEFAULT_QUALITY: scala.Double = js.native
  val BROTLI_DEFAULT_WINDOW: scala.Double = js.native
  val BROTLI_ENCODE: scala.Double = js.native
  val BROTLI_LARGE_MAX_WINDOW_BITS: scala.Double = js.native
  val BROTLI_MAX_INPUT_BLOCK_BITS: scala.Double = js.native
  val BROTLI_MAX_QUALITY: scala.Double = js.native
  val BROTLI_MAX_WINDOW_BITS: scala.Double = js.native
  val BROTLI_MIN_INPUT_BLOCK_BITS: scala.Double = js.native
  val BROTLI_MIN_QUALITY: scala.Double = js.native
  val BROTLI_MIN_WINDOW_BITS: scala.Double = js.native
  val BROTLI_MODE_FONT: scala.Double = js.native
  val BROTLI_MODE_GENERIC: scala.Double = js.native
  val BROTLI_MODE_TEXT: scala.Double = js.native
  val BROTLI_OPERATION_EMIT_METADATA: scala.Double = js.native
  val BROTLI_OPERATION_FINISH: scala.Double = js.native
  val BROTLI_OPERATION_FLUSH: scala.Double = js.native
  val BROTLI_OPERATION_PROCESS: scala.Double = js.native
  val BROTLI_PARAM_DISABLE_LITERAL_CONTEXT_MODELING: scala.Double = js.native
  val BROTLI_PARAM_LARGE_WINDOW: scala.Double = js.native
  val BROTLI_PARAM_LGBLOCK: scala.Double = js.native
  val BROTLI_PARAM_LGWIN: scala.Double = js.native
  val BROTLI_PARAM_MODE: scala.Double = js.native
  val BROTLI_PARAM_NDIRECT: scala.Double = js.native
  val BROTLI_PARAM_NPOSTFIX: scala.Double = js.native
  val BROTLI_PARAM_QUALITY: scala.Double = js.native
  val BROTLI_PARAM_SIZE_HINT: scala.Double = js.native
  val DEFLATE: scala.Double = js.native
  val DEFLATERAW: scala.Double = js.native
  val GUNZIP: scala.Double = js.native
  val GZIP: scala.Double = js.native
  val INFLATE: scala.Double = js.native
  val INFLATERAW: scala.Double = js.native
  val UNZIP: scala.Double = js.native
  val ZLIB_VERNUM: scala.Double = js.native
  val Z_BEST_COMPRESSION: scala.Double = js.native
  val Z_BEST_SPEED: scala.Double = js.native
  val Z_BLOCK: scala.Double = js.native
  val Z_BUF_ERROR: scala.Double = js.native
  val Z_DATA_ERROR: scala.Double = js.native
  val Z_DEFAULT_CHUNK: scala.Double = js.native
  val Z_DEFAULT_COMPRESSION: scala.Double = js.native
  val Z_DEFAULT_LEVEL: scala.Double = js.native
  val Z_DEFAULT_MEMLEVEL: scala.Double = js.native
  val Z_DEFAULT_STRATEGY: scala.Double = js.native
  val Z_DEFAULT_WINDOWBITS: scala.Double = js.native
  val Z_ERRNO: scala.Double = js.native
  val Z_FILTERED: scala.Double = js.native
  val Z_FINISH: scala.Double = js.native
  val Z_FIXED: scala.Double = js.native
  val Z_FULL_FLUSH: scala.Double = js.native
  val Z_HUFFMAN_ONLY: scala.Double = js.native
  val Z_MAX_CHUNK: scala.Double = js.native
  val Z_MAX_LEVEL: scala.Double = js.native
  val Z_MAX_MEMLEVEL: scala.Double = js.native
  val Z_MAX_WINDOWBITS: scala.Double = js.native
  val Z_MEM_ERROR: scala.Double = js.native
  val Z_MIN_CHUNK: scala.Double = js.native
  val Z_MIN_LEVEL: scala.Double = js.native
  val Z_MIN_MEMLEVEL: scala.Double = js.native
  val Z_MIN_WINDOWBITS: scala.Double = js.native
  val Z_NEED_DICT: scala.Double = js.native
  val Z_NO_COMPRESSION: scala.Double = js.native
  val Z_NO_FLUSH: scala.Double = js.native
  val Z_OK: scala.Double = js.native
  val Z_PARTIAL_FLUSH: scala.Double = js.native
  val Z_RLE: scala.Double = js.native
  val Z_STREAM_END: scala.Double = js.native
  val Z_STREAM_ERROR: scala.Double = js.native
  val Z_SYNC_FLUSH: scala.Double = js.native
  val Z_VERSION_ERROR: scala.Double = js.native
}

