package typings.seleniumDashWebdriver.libCommandMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait ICommandName extends js.Object {
  var ACCEPT_ALERT: String
  var ACTIONS: String
  var ADD_COOKIE: String
  var CLEAR_ACTIONS: String
  var CLEAR_APP_CACHE: String
  var CLEAR_ELEMENT: String
  var CLEAR_LOCAL_STORAGE: String
  var CLEAR_SESSION_STORAGE: String
  // These belong to the Advanced user interactions - an element is
  // optional for these commands.
  var CLICK: String
  var CLICK_ELEMENT: String
  var CLOSE: String
  var DELETE_ALL_COOKIES: String
  var DELETE_COOKIE: String
  var DESCRIBE_SESSION: String
  var DISMISS_ALERT: String
  var DOUBLE_CLICK: String
  var ELEMENT_EQUALS: String
  var EXECUTE_ASYNC_SCRIPT: String
  var EXECUTE_SCRIPT: String
  var EXECUTE_SQL: String
  var FIND_CHILD_ELEMENT: String
  var FIND_CHILD_ELEMENTS: String
  var FIND_ELEMENT: String
  var FIND_ELEMENTS: String
  var GET: String
  var GET_ACTIVE_ELEMENT: String
  var GET_ALERT_TEXT: String
  var GET_ALL_COOKIES: String
  var GET_APP_CACHE: String
  var GET_APP_CACHE_STATUS: String
  var GET_AVAILABLE_LOG_TYPES: String
  var GET_COOKIE: String
  var GET_CURRENT_URL: String
  var GET_CURRENT_WINDOW_HANDLE: String
  var GET_ELEMENT_ATTRIBUTE: String
  var GET_ELEMENT_LOCATION: String
  var GET_ELEMENT_LOCATION_IN_VIEW: String
  var GET_ELEMENT_SIZE: String
  var GET_ELEMENT_TAG_NAME: String
  var GET_ELEMENT_TEXT: String
  var GET_ELEMENT_VALUE_OF_CSS_PROPERTY: String
  var GET_LOCAL_STORAGE_ITEM: String
  var GET_LOCAL_STORAGE_KEYS: String
  var GET_LOCAL_STORAGE_SIZE: String
  var GET_LOCATION: String
  var GET_LOG: String
  var GET_PAGE_SOURCE: String
  var GET_SCREEN_ORIENTATION: String
  var GET_SERVER_STATUS: String
  var GET_SESSIONS: String
  var GET_SESSION_LOGS: String
  var GET_SESSION_STORAGE_ITEM: String
  var GET_SESSION_STORAGE_KEYS: String
  var GET_SESSION_STORAGE_SIZE: String
  var GET_TITLE: String
  var GET_WINDOW_HANDLES: String
  var GET_WINDOW_POSITION: String
  var GET_WINDOW_SIZE: String
  var GO_BACK: String
  var GO_FORWARD: String
  var IMPLICITLY_WAIT: String
  var IS_BROWSER_ONLINE: String
  var IS_ELEMENT_DISPLAYED: String
  var IS_ELEMENT_ENABLED: String
  var IS_ELEMENT_SELECTED: String
  var LEGACY_ACTION_CLICK: String
  var LEGACY_ACTION_DOUBLE_CLICK: String
  var LEGACY_ACTION_MOUSE_DOWN: String
  var LEGACY_ACTION_MOUSE_MOVE: String
  var LEGACY_ACTION_MOUSE_UP: String
  var LEGACY_ACTION_SEND_KEYS: String
  var LEGACY_ACTION_TOUCH_DOUBLE_TAP: String
  var LEGACY_ACTION_TOUCH_DOWN: String
  var LEGACY_ACTION_TOUCH_FLICK: String
  var LEGACY_ACTION_TOUCH_LONG_PRESS: String
  var LEGACY_ACTION_TOUCH_MOVE: String
  var LEGACY_ACTION_TOUCH_SCROLL: String
  var LEGACY_ACTION_TOUCH_SINGLE_TAP: String
  var LEGACY_ACTION_TOUCH_UP: String
  var MAXIMIZE_WINDOW: String
  var MOUSE_DOWN: String
  var MOUSE_UP: String
  var MOVE_TO: String
  var NEW_SESSION: String
  var QUIT: String
  var REFRESH: String
  var REMOVE_LOCAL_STORAGE_ITEM: String
  var REMOVE_SESSION_STORAGE_ITEM: String
  var SCREENSHOT: String
  var SEND_KEYS_TO_ACTIVE_ELEMENT: String
  var SEND_KEYS_TO_ELEMENT: String
  var SET_ALERT_TEXT: String
  var SET_BROWSER_ONLINE: String
  var SET_LOCAL_STORAGE_ITEM: String
  var SET_LOCATION: String
  var SET_SCREEN_ORIENTATION: String
  var SET_SCRIPT_TIMEOUT: String
  var SET_SESSION_STORAGE_ITEM: String
  var SET_TIMEOUT: String
  var SET_WINDOW_POSITION: String
  var SET_WINDOW_SIZE: String
  var SUBMIT_ELEMENT: String
  var SWITCH_TO_FRAME: String
  var SWITCH_TO_WINDOW: String
  var TOUCH_DOUBLE_TAP: String
  var TOUCH_DOWN: String
  var TOUCH_FLICK: String
  var TOUCH_LONG_PRESS: String
  var TOUCH_MOVE: String
  var TOUCH_SCROLL: String
  // These belong to the Advanced Touch API
  var TOUCH_SINGLE_TAP: String
  var TOUCH_UP: String
  var UPLOAD_FILE: String
}

object ICommandName {
  @scala.inline
  def apply(
    ACCEPT_ALERT: String,
    ACTIONS: String,
    ADD_COOKIE: String,
    CLEAR_ACTIONS: String,
    CLEAR_APP_CACHE: String,
    CLEAR_ELEMENT: String,
    CLEAR_LOCAL_STORAGE: String,
    CLEAR_SESSION_STORAGE: String,
    CLICK: String,
    CLICK_ELEMENT: String,
    CLOSE: String,
    DELETE_ALL_COOKIES: String,
    DELETE_COOKIE: String,
    DESCRIBE_SESSION: String,
    DISMISS_ALERT: String,
    DOUBLE_CLICK: String,
    ELEMENT_EQUALS: String,
    EXECUTE_ASYNC_SCRIPT: String,
    EXECUTE_SCRIPT: String,
    EXECUTE_SQL: String,
    FIND_CHILD_ELEMENT: String,
    FIND_CHILD_ELEMENTS: String,
    FIND_ELEMENT: String,
    FIND_ELEMENTS: String,
    GET: String,
    GET_ACTIVE_ELEMENT: String,
    GET_ALERT_TEXT: String,
    GET_ALL_COOKIES: String,
    GET_APP_CACHE: String,
    GET_APP_CACHE_STATUS: String,
    GET_AVAILABLE_LOG_TYPES: String,
    GET_COOKIE: String,
    GET_CURRENT_URL: String,
    GET_CURRENT_WINDOW_HANDLE: String,
    GET_ELEMENT_ATTRIBUTE: String,
    GET_ELEMENT_LOCATION: String,
    GET_ELEMENT_LOCATION_IN_VIEW: String,
    GET_ELEMENT_SIZE: String,
    GET_ELEMENT_TAG_NAME: String,
    GET_ELEMENT_TEXT: String,
    GET_ELEMENT_VALUE_OF_CSS_PROPERTY: String,
    GET_LOCAL_STORAGE_ITEM: String,
    GET_LOCAL_STORAGE_KEYS: String,
    GET_LOCAL_STORAGE_SIZE: String,
    GET_LOCATION: String,
    GET_LOG: String,
    GET_PAGE_SOURCE: String,
    GET_SCREEN_ORIENTATION: String,
    GET_SERVER_STATUS: String,
    GET_SESSIONS: String,
    GET_SESSION_LOGS: String,
    GET_SESSION_STORAGE_ITEM: String,
    GET_SESSION_STORAGE_KEYS: String,
    GET_SESSION_STORAGE_SIZE: String,
    GET_TITLE: String,
    GET_WINDOW_HANDLES: String,
    GET_WINDOW_POSITION: String,
    GET_WINDOW_SIZE: String,
    GO_BACK: String,
    GO_FORWARD: String,
    IMPLICITLY_WAIT: String,
    IS_BROWSER_ONLINE: String,
    IS_ELEMENT_DISPLAYED: String,
    IS_ELEMENT_ENABLED: String,
    IS_ELEMENT_SELECTED: String,
    LEGACY_ACTION_CLICK: String,
    LEGACY_ACTION_DOUBLE_CLICK: String,
    LEGACY_ACTION_MOUSE_DOWN: String,
    LEGACY_ACTION_MOUSE_MOVE: String,
    LEGACY_ACTION_MOUSE_UP: String,
    LEGACY_ACTION_SEND_KEYS: String,
    LEGACY_ACTION_TOUCH_DOUBLE_TAP: String,
    LEGACY_ACTION_TOUCH_DOWN: String,
    LEGACY_ACTION_TOUCH_FLICK: String,
    LEGACY_ACTION_TOUCH_LONG_PRESS: String,
    LEGACY_ACTION_TOUCH_MOVE: String,
    LEGACY_ACTION_TOUCH_SCROLL: String,
    LEGACY_ACTION_TOUCH_SINGLE_TAP: String,
    LEGACY_ACTION_TOUCH_UP: String,
    MAXIMIZE_WINDOW: String,
    MOUSE_DOWN: String,
    MOUSE_UP: String,
    MOVE_TO: String,
    NEW_SESSION: String,
    QUIT: String,
    REFRESH: String,
    REMOVE_LOCAL_STORAGE_ITEM: String,
    REMOVE_SESSION_STORAGE_ITEM: String,
    SCREENSHOT: String,
    SEND_KEYS_TO_ACTIVE_ELEMENT: String,
    SEND_KEYS_TO_ELEMENT: String,
    SET_ALERT_TEXT: String,
    SET_BROWSER_ONLINE: String,
    SET_LOCAL_STORAGE_ITEM: String,
    SET_LOCATION: String,
    SET_SCREEN_ORIENTATION: String,
    SET_SCRIPT_TIMEOUT: String,
    SET_SESSION_STORAGE_ITEM: String,
    SET_TIMEOUT: String,
    SET_WINDOW_POSITION: String,
    SET_WINDOW_SIZE: String,
    SUBMIT_ELEMENT: String,
    SWITCH_TO_FRAME: String,
    SWITCH_TO_WINDOW: String,
    TOUCH_DOUBLE_TAP: String,
    TOUCH_DOWN: String,
    TOUCH_FLICK: String,
    TOUCH_LONG_PRESS: String,
    TOUCH_MOVE: String,
    TOUCH_SCROLL: String,
    TOUCH_SINGLE_TAP: String,
    TOUCH_UP: String,
    UPLOAD_FILE: String
  ): ICommandName = {
    val __obj = js.Dynamic.literal(ACCEPT_ALERT = ACCEPT_ALERT, ACTIONS = ACTIONS, ADD_COOKIE = ADD_COOKIE, CLEAR_ACTIONS = CLEAR_ACTIONS, CLEAR_APP_CACHE = CLEAR_APP_CACHE, CLEAR_ELEMENT = CLEAR_ELEMENT, CLEAR_LOCAL_STORAGE = CLEAR_LOCAL_STORAGE, CLEAR_SESSION_STORAGE = CLEAR_SESSION_STORAGE, CLICK = CLICK, CLICK_ELEMENT = CLICK_ELEMENT, CLOSE = CLOSE, DELETE_ALL_COOKIES = DELETE_ALL_COOKIES, DELETE_COOKIE = DELETE_COOKIE, DESCRIBE_SESSION = DESCRIBE_SESSION, DISMISS_ALERT = DISMISS_ALERT, DOUBLE_CLICK = DOUBLE_CLICK, ELEMENT_EQUALS = ELEMENT_EQUALS, EXECUTE_ASYNC_SCRIPT = EXECUTE_ASYNC_SCRIPT, EXECUTE_SCRIPT = EXECUTE_SCRIPT, EXECUTE_SQL = EXECUTE_SQL, FIND_CHILD_ELEMENT = FIND_CHILD_ELEMENT, FIND_CHILD_ELEMENTS = FIND_CHILD_ELEMENTS, FIND_ELEMENT = FIND_ELEMENT, FIND_ELEMENTS = FIND_ELEMENTS, GET = GET, GET_ACTIVE_ELEMENT = GET_ACTIVE_ELEMENT, GET_ALERT_TEXT = GET_ALERT_TEXT, GET_ALL_COOKIES = GET_ALL_COOKIES, GET_APP_CACHE = GET_APP_CACHE, GET_APP_CACHE_STATUS = GET_APP_CACHE_STATUS, GET_AVAILABLE_LOG_TYPES = GET_AVAILABLE_LOG_TYPES, GET_COOKIE = GET_COOKIE, GET_CURRENT_URL = GET_CURRENT_URL, GET_CURRENT_WINDOW_HANDLE = GET_CURRENT_WINDOW_HANDLE, GET_ELEMENT_ATTRIBUTE = GET_ELEMENT_ATTRIBUTE, GET_ELEMENT_LOCATION = GET_ELEMENT_LOCATION, GET_ELEMENT_LOCATION_IN_VIEW = GET_ELEMENT_LOCATION_IN_VIEW, GET_ELEMENT_SIZE = GET_ELEMENT_SIZE, GET_ELEMENT_TAG_NAME = GET_ELEMENT_TAG_NAME, GET_ELEMENT_TEXT = GET_ELEMENT_TEXT, GET_ELEMENT_VALUE_OF_CSS_PROPERTY = GET_ELEMENT_VALUE_OF_CSS_PROPERTY, GET_LOCAL_STORAGE_ITEM = GET_LOCAL_STORAGE_ITEM, GET_LOCAL_STORAGE_KEYS = GET_LOCAL_STORAGE_KEYS, GET_LOCAL_STORAGE_SIZE = GET_LOCAL_STORAGE_SIZE, GET_LOCATION = GET_LOCATION, GET_LOG = GET_LOG, GET_PAGE_SOURCE = GET_PAGE_SOURCE, GET_SCREEN_ORIENTATION = GET_SCREEN_ORIENTATION, GET_SERVER_STATUS = GET_SERVER_STATUS, GET_SESSIONS = GET_SESSIONS, GET_SESSION_LOGS = GET_SESSION_LOGS, GET_SESSION_STORAGE_ITEM = GET_SESSION_STORAGE_ITEM, GET_SESSION_STORAGE_KEYS = GET_SESSION_STORAGE_KEYS, GET_SESSION_STORAGE_SIZE = GET_SESSION_STORAGE_SIZE, GET_TITLE = GET_TITLE, GET_WINDOW_HANDLES = GET_WINDOW_HANDLES, GET_WINDOW_POSITION = GET_WINDOW_POSITION, GET_WINDOW_SIZE = GET_WINDOW_SIZE, GO_BACK = GO_BACK, GO_FORWARD = GO_FORWARD, IMPLICITLY_WAIT = IMPLICITLY_WAIT, IS_BROWSER_ONLINE = IS_BROWSER_ONLINE, IS_ELEMENT_DISPLAYED = IS_ELEMENT_DISPLAYED, IS_ELEMENT_ENABLED = IS_ELEMENT_ENABLED, IS_ELEMENT_SELECTED = IS_ELEMENT_SELECTED, LEGACY_ACTION_CLICK = LEGACY_ACTION_CLICK, LEGACY_ACTION_DOUBLE_CLICK = LEGACY_ACTION_DOUBLE_CLICK, LEGACY_ACTION_MOUSE_DOWN = LEGACY_ACTION_MOUSE_DOWN, LEGACY_ACTION_MOUSE_MOVE = LEGACY_ACTION_MOUSE_MOVE, LEGACY_ACTION_MOUSE_UP = LEGACY_ACTION_MOUSE_UP, LEGACY_ACTION_SEND_KEYS = LEGACY_ACTION_SEND_KEYS, LEGACY_ACTION_TOUCH_DOUBLE_TAP = LEGACY_ACTION_TOUCH_DOUBLE_TAP, LEGACY_ACTION_TOUCH_DOWN = LEGACY_ACTION_TOUCH_DOWN, LEGACY_ACTION_TOUCH_FLICK = LEGACY_ACTION_TOUCH_FLICK, LEGACY_ACTION_TOUCH_LONG_PRESS = LEGACY_ACTION_TOUCH_LONG_PRESS, LEGACY_ACTION_TOUCH_MOVE = LEGACY_ACTION_TOUCH_MOVE, LEGACY_ACTION_TOUCH_SCROLL = LEGACY_ACTION_TOUCH_SCROLL, LEGACY_ACTION_TOUCH_SINGLE_TAP = LEGACY_ACTION_TOUCH_SINGLE_TAP, LEGACY_ACTION_TOUCH_UP = LEGACY_ACTION_TOUCH_UP, MAXIMIZE_WINDOW = MAXIMIZE_WINDOW, MOUSE_DOWN = MOUSE_DOWN, MOUSE_UP = MOUSE_UP, MOVE_TO = MOVE_TO, NEW_SESSION = NEW_SESSION, QUIT = QUIT, REFRESH = REFRESH, REMOVE_LOCAL_STORAGE_ITEM = REMOVE_LOCAL_STORAGE_ITEM, REMOVE_SESSION_STORAGE_ITEM = REMOVE_SESSION_STORAGE_ITEM, SCREENSHOT = SCREENSHOT, SEND_KEYS_TO_ACTIVE_ELEMENT = SEND_KEYS_TO_ACTIVE_ELEMENT, SEND_KEYS_TO_ELEMENT = SEND_KEYS_TO_ELEMENT, SET_ALERT_TEXT = SET_ALERT_TEXT, SET_BROWSER_ONLINE = SET_BROWSER_ONLINE, SET_LOCAL_STORAGE_ITEM = SET_LOCAL_STORAGE_ITEM, SET_LOCATION = SET_LOCATION, SET_SCREEN_ORIENTATION = SET_SCREEN_ORIENTATION, SET_SCRIPT_TIMEOUT = SET_SCRIPT_TIMEOUT, SET_SESSION_STORAGE_ITEM = SET_SESSION_STORAGE_ITEM, SET_TIMEOUT = SET_TIMEOUT, SET_WINDOW_POSITION = SET_WINDOW_POSITION, SET_WINDOW_SIZE = SET_WINDOW_SIZE, SUBMIT_ELEMENT = SUBMIT_ELEMENT, SWITCH_TO_FRAME = SWITCH_TO_FRAME, SWITCH_TO_WINDOW = SWITCH_TO_WINDOW, TOUCH_DOUBLE_TAP = TOUCH_DOUBLE_TAP, TOUCH_DOWN = TOUCH_DOWN, TOUCH_FLICK = TOUCH_FLICK, TOUCH_LONG_PRESS = TOUCH_LONG_PRESS, TOUCH_MOVE = TOUCH_MOVE, TOUCH_SCROLL = TOUCH_SCROLL, TOUCH_SINGLE_TAP = TOUCH_SINGLE_TAP, TOUCH_UP = TOUCH_UP, UPLOAD_FILE = UPLOAD_FILE)
  
    __obj.asInstanceOf[ICommandName]
  }
}

