package typings
package reactDashNotificationDashSystemDashReduxLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

object reactDashNotificationDashSystemDashReduxLibComponents {
  @scala.inline
  def ReactDashNotificationDashSystemDashRedux: reactLib.reactMod.ComponentType[
    reactDashNotificationDashSystemDashReduxLib.reactDashNotificationDashSystemDashReduxMod.NotificationsProps
  ] = js.constructorOf[reactDashNotificationDashSystemDashReduxLib.reactDashNotificationDashSystemDashReduxMod.^].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNotificationDashSystemDashReduxLib.reactDashNotificationDashSystemDashReduxMod.NotificationsProps]]
  @scala.inline
  def NotificationsProps: reactDashNotificationDashSystemDashReduxLib.reactDashNotificationDashSystemDashReduxMod.NotificationsProps.type = reactDashNotificationDashSystemDashReduxLib.reactDashNotificationDashSystemDashReduxMod.NotificationsProps
  type NotificationsProps = reactDashNotificationDashSystemDashReduxLib.reactDashNotificationDashSystemDashReduxMod.NotificationsProps
}

