package typings.antvDataSet

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

package object viewMod {
  
  type ConnectorOptions[T /* <: typings.antvDataSet.antvDataSetStrings.csv | typings.antvDataSet.antvDataSetStrings.tsv | typings.antvDataSet.antvDataSetStrings.dsv | typings.antvDataSet.antvDataSetStrings.graph | typings.antvDataSet.antvDataSetStrings.diagram | typings.antvDataSet.antvDataSetStrings.hex | typings.antvDataSet.antvDataSetStrings.hexjson_ | typings.antvDataSet.antvDataSetStrings.`hex-json` | typings.antvDataSet.antvDataSetStrings.HexJSON | typings.antvDataSet.antvDataSetStrings.geo | typings.antvDataSet.antvDataSetStrings.geojson_ | typings.antvDataSet.antvDataSetStrings.GeoJSON | typings.antvDataSet.antvDataSetStrings.hierarchy | typings.antvDataSet.antvDataSetStrings.tree | typings.antvDataSet.antvDataSetStrings.topojson_ | typings.antvDataSet.antvDataSetStrings.TopoJSON */] = typings.antvDataSet.anon.TypeT[T] with (/* import warning: importer.ImportType#apply Failed type conversion: @antv/data-set.@antv/data-set/lib/connector-params.ConnectorParams[T][1] */ js.Any)
  
  type TransformOptions[T /* <: typings.antvDataSet.antvDataSetStrings.filter | typings.antvDataSet.antvDataSetStrings.map | typings.antvDataSet.antvDataSetStrings.pick | typings.antvDataSet.antvDataSetStrings.rename | typings.antvDataSet.antvDataSetStrings.`rename-fields` | typings.antvDataSet.antvDataSetStrings.reverse | typings.antvDataSet.antvDataSetStrings.default | typings.antvDataSet.antvDataSetStrings.sort | typings.antvDataSet.antvDataSetStrings.sortBy | typings.antvDataSet.antvDataSetStrings.`sort-by` | typings.antvDataSet.antvDataSetStrings.subset | typings.antvDataSet.antvDataSetStrings.partition | typings.antvDataSet.antvDataSetStrings.group | typings.antvDataSet.antvDataSetStrings.groups | typings.antvDataSet.antvDataSetStrings.fold | typings.antvDataSet.antvDataSetStrings.`fill-rows` | typings.antvDataSet.antvDataSetStrings.fillRows | typings.antvDataSet.antvDataSetStrings.impute | typings.antvDataSet.antvDataSetStrings.aggregate | typings.antvDataSet.antvDataSetStrings.summary | typings.antvDataSet.antvDataSetStrings.percent | typings.antvDataSet.antvDataSetStrings.proportion | typings.antvDataSet.antvDataSetStrings.regression | typings.antvDataSet.antvDataSetStrings.kernelDotdensity | typings.antvDataSet.antvDataSetStrings.`kernel-smoothDotdensity` | typings.antvDataSet.antvDataSetStrings.kernelDotregression | typings.antvDataSet.antvDataSetStrings.`kernel-smoothDotregression` | typings.antvDataSet.antvDataSetStrings.binDothistogram | typings.antvDataSet.antvDataSetStrings.binDotdot | typings.antvDataSet.antvDataSetStrings.binDothexagon | typings.antvDataSet.antvDataSetStrings.binDothex | typings.antvDataSet.antvDataSetStrings.hexbin | typings.antvDataSet.antvDataSetStrings.binDotquantile | typings.antvDataSet.antvDataSetStrings.binDotrectangle | typings.antvDataSet.antvDataSetStrings.binDotrect | typings.antvDataSet.antvDataSetStrings.treemap | typings.antvDataSet.antvDataSetStrings.hierarchyDottreemap | typings.antvDataSet.antvDataSetStrings.adjacency | typings.antvDataSet.antvDataSetStrings.hierarchyDotpartition | typings.antvDataSet.antvDataSetStrings.voronoi | typings.antvDataSet.antvDataSetStrings.diagramDotvoronoi | typings.antvDataSet.antvDataSetStrings.diagramDotsankey | typings.antvDataSet.antvDataSetStrings.sankey | typings.antvDataSet.antvDataSetStrings.diagramDotarc | typings.antvDataSet.antvDataSetStrings.arc | typings.antvDataSet.antvDataSetStrings.geoDotregion | typings.antvDataSet.antvDataSetStrings.geoDotprojection | typings.antvDataSet.antvDataSetStrings.geoDotcentroid | typings.antvDataSet.antvDataSetStrings.`tag-cloud` | typings.antvDataSet.antvDataSetStrings.`word-cloud` */] = typings.antvDataSet.anon.Type[T] with (/* import warning: importer.ImportType#apply Failed type conversion: @antv/data-set.@antv/data-set/lib/transform-params.TransformsParams[T] */ js.Any)
}
