package typings.speakeasy.mod

import typings.node.Buffer
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

@js.native
trait HotpOptions extends DigestOptions {
  
  /**
    * The digest, automatically generated by default
    */
  var digest: js.UndefOr[Buffer] = js.native
  
  /**
    * The number of digits for the one-time passcode, defaults to 6
    */
  var digits: js.UndefOr[Double] = js.native
  
  /**
    * @deprecated use digits
    */
  var length: js.UndefOr[Double] = js.native
}
object HotpOptions {
  
  @scala.inline
  def apply(counter: Double, secret: String): HotpOptions = {
    val __obj = js.Dynamic.literal(counter = counter.asInstanceOf[js.Any], secret = secret.asInstanceOf[js.Any])
    __obj.asInstanceOf[HotpOptions]
  }
  
  @scala.inline
  implicit class HotpOptionsMutableBuilder[Self <: HotpOptions] (val x: Self) extends AnyVal {
    
    @scala.inline
    def setDigest(value: Buffer): Self = StObject.set(x, "digest", value.asInstanceOf[js.Any])
    
    @scala.inline
    def setDigestUndefined: Self = StObject.set(x, "digest", js.undefined)
    
    @scala.inline
    def setDigits(value: Double): Self = StObject.set(x, "digits", value.asInstanceOf[js.Any])
    
    @scala.inline
    def setDigitsUndefined: Self = StObject.set(x, "digits", js.undefined)
    
    @scala.inline
    def setLength(value: Double): Self = StObject.set(x, "length", value.asInstanceOf[js.Any])
    
    @scala.inline
    def setLengthUndefined: Self = StObject.set(x, "length", js.undefined)
  }
}
