package typings
package speakeasyLib.speakeasyMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait HotpOptions extends DigestOptions {
  /**
    * The digest, automatically generated by default
    */
  var digest: js.UndefOr[nodeLib.Buffer] = js.undefined
  /**
    * The number of digits for the one-time passcode, defaults to 6
    */
  var digits: js.UndefOr[scala.Double] = js.undefined
  /**
    * @deprecated use digits
    */
  var length: js.UndefOr[scala.Double] = js.undefined
}

object HotpOptions {
  @scala.inline
  def apply(
    counter: scala.Double,
    secret: java.lang.String,
    algorithm: Algorithm = null,
    digest: nodeLib.Buffer = null,
    digits: scala.Int | scala.Double = null,
    encoding: Encoding = null,
    key: java.lang.String = null,
    length: scala.Int | scala.Double = null
  ): HotpOptions = {
    val __obj = js.Dynamic.literal(counter = counter, secret = secret)
    if (algorithm != null) __obj.updateDynamic("algorithm")(algorithm)
    if (digest != null) __obj.updateDynamic("digest")(digest)
    if (digits != null) __obj.updateDynamic("digits")(digits.asInstanceOf[js.Any])
    if (encoding != null) __obj.updateDynamic("encoding")(encoding)
    if (key != null) __obj.updateDynamic("key")(key)
    if (length != null) __obj.updateDynamic("length")(length.asInstanceOf[js.Any])
    __obj.asInstanceOf[HotpOptions]
  }
}

