package typings.fridaGum

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/* Rewritten from type alias, can be one of: 
  - typings.fridaGum.PortableCpuContext
  - typings.fridaGum.Ia32CpuContext
  - typings.fridaGum.X64CpuContext
  - typings.fridaGum.ArmCpuContext
  - typings.fridaGum.Arm64CpuContext
  - typings.fridaGum.MipsCpuContext
*/
trait CpuContext extends StObject
object CpuContext {
  
  inline def Arm64CpuContext(
    d0: Double,
    d1: Double,
    d10: Double,
    d11: Double,
    d12: Double,
    d13: Double,
    d14: Double,
    d15: Double,
    d16: Double,
    d17: Double,
    d18: Double,
    d19: Double,
    d2: Double,
    d20: Double,
    d21: Double,
    d22: Double,
    d23: Double,
    d24: Double,
    d25: Double,
    d26: Double,
    d27: Double,
    d28: Double,
    d29: Double,
    d3: Double,
    d30: Double,
    d31: Double,
    d4: Double,
    d5: Double,
    d6: Double,
    d7: Double,
    d8: Double,
    d9: Double,
    fp: NativePointer,
    lr: NativePointer,
    nzcv: Double,
    pc: NativePointer,
    q0: ArrayBuffer,
    q1: ArrayBuffer,
    q10: ArrayBuffer,
    q11: ArrayBuffer,
    q12: ArrayBuffer,
    q13: ArrayBuffer,
    q14: ArrayBuffer,
    q15: ArrayBuffer,
    q16: ArrayBuffer,
    q17: ArrayBuffer,
    q18: ArrayBuffer,
    q19: ArrayBuffer,
    q2: ArrayBuffer,
    q20: ArrayBuffer,
    q21: ArrayBuffer,
    q22: ArrayBuffer,
    q23: ArrayBuffer,
    q24: ArrayBuffer,
    q25: ArrayBuffer,
    q26: ArrayBuffer,
    q27: ArrayBuffer,
    q28: ArrayBuffer,
    q29: ArrayBuffer,
    q3: ArrayBuffer,
    q30: ArrayBuffer,
    q31: ArrayBuffer,
    q4: ArrayBuffer,
    q5: ArrayBuffer,
    q6: ArrayBuffer,
    q7: ArrayBuffer,
    q8: ArrayBuffer,
    q9: ArrayBuffer,
    s0: Double,
    s1: Double,
    s10: Double,
    s11: Double,
    s12: Double,
    s13: Double,
    s14: Double,
    s15: Double,
    s16: Double,
    s17: Double,
    s18: Double,
    s19: Double,
    s2: Double,
    s20: Double,
    s21: Double,
    s22: Double,
    s23: Double,
    s24: Double,
    s25: Double,
    s26: Double,
    s27: Double,
    s28: Double,
    s29: Double,
    s3: Double,
    s30: Double,
    s31: Double,
    s4: Double,
    s5: Double,
    s6: Double,
    s7: Double,
    s8: Double,
    s9: Double,
    sp: NativePointer,
    x0: NativePointer,
    x1: NativePointer,
    x10: NativePointer,
    x11: NativePointer,
    x12: NativePointer,
    x13: NativePointer,
    x14: NativePointer,
    x15: NativePointer,
    x16: NativePointer,
    x17: NativePointer,
    x18: NativePointer,
    x19: NativePointer,
    x2: NativePointer,
    x20: NativePointer,
    x21: NativePointer,
    x22: NativePointer,
    x23: NativePointer,
    x24: NativePointer,
    x25: NativePointer,
    x26: NativePointer,
    x27: NativePointer,
    x28: NativePointer,
    x3: NativePointer,
    x4: NativePointer,
    x5: NativePointer,
    x6: NativePointer,
    x7: NativePointer,
    x8: NativePointer,
    x9: NativePointer
  ): typings.fridaGum.Arm64CpuContext = {
    val __obj = js.Dynamic.literal(d0 = d0.asInstanceOf[js.Any], d1 = d1.asInstanceOf[js.Any], d10 = d10.asInstanceOf[js.Any], d11 = d11.asInstanceOf[js.Any], d12 = d12.asInstanceOf[js.Any], d13 = d13.asInstanceOf[js.Any], d14 = d14.asInstanceOf[js.Any], d15 = d15.asInstanceOf[js.Any], d16 = d16.asInstanceOf[js.Any], d17 = d17.asInstanceOf[js.Any], d18 = d18.asInstanceOf[js.Any], d19 = d19.asInstanceOf[js.Any], d2 = d2.asInstanceOf[js.Any], d20 = d20.asInstanceOf[js.Any], d21 = d21.asInstanceOf[js.Any], d22 = d22.asInstanceOf[js.Any], d23 = d23.asInstanceOf[js.Any], d24 = d24.asInstanceOf[js.Any], d25 = d25.asInstanceOf[js.Any], d26 = d26.asInstanceOf[js.Any], d27 = d27.asInstanceOf[js.Any], d28 = d28.asInstanceOf[js.Any], d29 = d29.asInstanceOf[js.Any], d3 = d3.asInstanceOf[js.Any], d30 = d30.asInstanceOf[js.Any], d31 = d31.asInstanceOf[js.Any], d4 = d4.asInstanceOf[js.Any], d5 = d5.asInstanceOf[js.Any], d6 = d6.asInstanceOf[js.Any], d7 = d7.asInstanceOf[js.Any], d8 = d8.asInstanceOf[js.Any], d9 = d9.asInstanceOf[js.Any], fp = fp.asInstanceOf[js.Any], lr = lr.asInstanceOf[js.Any], nzcv = nzcv.asInstanceOf[js.Any], pc = pc.asInstanceOf[js.Any], q0 = q0.asInstanceOf[js.Any], q1 = q1.asInstanceOf[js.Any], q10 = q10.asInstanceOf[js.Any], q11 = q11.asInstanceOf[js.Any], q12 = q12.asInstanceOf[js.Any], q13 = q13.asInstanceOf[js.Any], q14 = q14.asInstanceOf[js.Any], q15 = q15.asInstanceOf[js.Any], q16 = q16.asInstanceOf[js.Any], q17 = q17.asInstanceOf[js.Any], q18 = q18.asInstanceOf[js.Any], q19 = q19.asInstanceOf[js.Any], q2 = q2.asInstanceOf[js.Any], q20 = q20.asInstanceOf[js.Any], q21 = q21.asInstanceOf[js.Any], q22 = q22.asInstanceOf[js.Any], q23 = q23.asInstanceOf[js.Any], q24 = q24.asInstanceOf[js.Any], q25 = q25.asInstanceOf[js.Any], q26 = q26.asInstanceOf[js.Any], q27 = q27.asInstanceOf[js.Any], q28 = q28.asInstanceOf[js.Any], q29 = q29.asInstanceOf[js.Any], q3 = q3.asInstanceOf[js.Any], q30 = q30.asInstanceOf[js.Any], q31 = q31.asInstanceOf[js.Any], q4 = q4.asInstanceOf[js.Any], q5 = q5.asInstanceOf[js.Any], q6 = q6.asInstanceOf[js.Any], q7 = q7.asInstanceOf[js.Any], q8 = q8.asInstanceOf[js.Any], q9 = q9.asInstanceOf[js.Any], s0 = s0.asInstanceOf[js.Any], s1 = s1.asInstanceOf[js.Any], s10 = s10.asInstanceOf[js.Any], s11 = s11.asInstanceOf[js.Any], s12 = s12.asInstanceOf[js.Any], s13 = s13.asInstanceOf[js.Any], s14 = s14.asInstanceOf[js.Any], s15 = s15.asInstanceOf[js.Any], s16 = s16.asInstanceOf[js.Any], s17 = s17.asInstanceOf[js.Any], s18 = s18.asInstanceOf[js.Any], s19 = s19.asInstanceOf[js.Any], s2 = s2.asInstanceOf[js.Any], s20 = s20.asInstanceOf[js.Any], s21 = s21.asInstanceOf[js.Any], s22 = s22.asInstanceOf[js.Any], s23 = s23.asInstanceOf[js.Any], s24 = s24.asInstanceOf[js.Any], s25 = s25.asInstanceOf[js.Any], s26 = s26.asInstanceOf[js.Any], s27 = s27.asInstanceOf[js.Any], s28 = s28.asInstanceOf[js.Any], s29 = s29.asInstanceOf[js.Any], s3 = s3.asInstanceOf[js.Any], s30 = s30.asInstanceOf[js.Any], s31 = s31.asInstanceOf[js.Any], s4 = s4.asInstanceOf[js.Any], s5 = s5.asInstanceOf[js.Any], s6 = s6.asInstanceOf[js.Any], s7 = s7.asInstanceOf[js.Any], s8 = s8.asInstanceOf[js.Any], s9 = s9.asInstanceOf[js.Any], sp = sp.asInstanceOf[js.Any], x0 = x0.asInstanceOf[js.Any], x1 = x1.asInstanceOf[js.Any], x10 = x10.asInstanceOf[js.Any], x11 = x11.asInstanceOf[js.Any], x12 = x12.asInstanceOf[js.Any], x13 = x13.asInstanceOf[js.Any], x14 = x14.asInstanceOf[js.Any], x15 = x15.asInstanceOf[js.Any], x16 = x16.asInstanceOf[js.Any], x17 = x17.asInstanceOf[js.Any], x18 = x18.asInstanceOf[js.Any], x19 = x19.asInstanceOf[js.Any], x2 = x2.asInstanceOf[js.Any], x20 = x20.asInstanceOf[js.Any], x21 = x21.asInstanceOf[js.Any], x22 = x22.asInstanceOf[js.Any], x23 = x23.asInstanceOf[js.Any], x24 = x24.asInstanceOf[js.Any], x25 = x25.asInstanceOf[js.Any], x26 = x26.asInstanceOf[js.Any], x27 = x27.asInstanceOf[js.Any], x28 = x28.asInstanceOf[js.Any], x3 = x3.asInstanceOf[js.Any], x4 = x4.asInstanceOf[js.Any], x5 = x5.asInstanceOf[js.Any], x6 = x6.asInstanceOf[js.Any], x7 = x7.asInstanceOf[js.Any], x8 = x8.asInstanceOf[js.Any], x9 = x9.asInstanceOf[js.Any])
    __obj.asInstanceOf[typings.fridaGum.Arm64CpuContext]
  }
  
  inline def ArmCpuContext(
    cpsr: Double,
    d0: Double,
    d1: Double,
    d10: Double,
    d11: Double,
    d12: Double,
    d13: Double,
    d14: Double,
    d15: Double,
    d16: Double,
    d17: Double,
    d18: Double,
    d19: Double,
    d2: Double,
    d20: Double,
    d21: Double,
    d22: Double,
    d23: Double,
    d24: Double,
    d25: Double,
    d26: Double,
    d27: Double,
    d28: Double,
    d29: Double,
    d3: Double,
    d30: Double,
    d31: Double,
    d4: Double,
    d5: Double,
    d6: Double,
    d7: Double,
    d8: Double,
    d9: Double,
    lr: NativePointer,
    pc: NativePointer,
    q0: ArrayBuffer,
    q1: ArrayBuffer,
    q10: ArrayBuffer,
    q11: ArrayBuffer,
    q12: ArrayBuffer,
    q13: ArrayBuffer,
    q14: ArrayBuffer,
    q15: ArrayBuffer,
    q2: ArrayBuffer,
    q3: ArrayBuffer,
    q4: ArrayBuffer,
    q5: ArrayBuffer,
    q6: ArrayBuffer,
    q7: ArrayBuffer,
    q8: ArrayBuffer,
    q9: ArrayBuffer,
    r0: NativePointer,
    r1: NativePointer,
    r10: NativePointer,
    r11: NativePointer,
    r12: NativePointer,
    r2: NativePointer,
    r3: NativePointer,
    r4: NativePointer,
    r5: NativePointer,
    r6: NativePointer,
    r7: NativePointer,
    r8: NativePointer,
    r9: NativePointer,
    s0: Double,
    s1: Double,
    s10: Double,
    s11: Double,
    s12: Double,
    s13: Double,
    s14: Double,
    s15: Double,
    s16: Double,
    s17: Double,
    s18: Double,
    s19: Double,
    s2: Double,
    s20: Double,
    s21: Double,
    s22: Double,
    s23: Double,
    s24: Double,
    s25: Double,
    s26: Double,
    s27: Double,
    s28: Double,
    s29: Double,
    s3: Double,
    s30: Double,
    s31: Double,
    s4: Double,
    s5: Double,
    s6: Double,
    s7: Double,
    s8: Double,
    s9: Double,
    sp: NativePointer
  ): typings.fridaGum.ArmCpuContext = {
    val __obj = js.Dynamic.literal(cpsr = cpsr.asInstanceOf[js.Any], d0 = d0.asInstanceOf[js.Any], d1 = d1.asInstanceOf[js.Any], d10 = d10.asInstanceOf[js.Any], d11 = d11.asInstanceOf[js.Any], d12 = d12.asInstanceOf[js.Any], d13 = d13.asInstanceOf[js.Any], d14 = d14.asInstanceOf[js.Any], d15 = d15.asInstanceOf[js.Any], d16 = d16.asInstanceOf[js.Any], d17 = d17.asInstanceOf[js.Any], d18 = d18.asInstanceOf[js.Any], d19 = d19.asInstanceOf[js.Any], d2 = d2.asInstanceOf[js.Any], d20 = d20.asInstanceOf[js.Any], d21 = d21.asInstanceOf[js.Any], d22 = d22.asInstanceOf[js.Any], d23 = d23.asInstanceOf[js.Any], d24 = d24.asInstanceOf[js.Any], d25 = d25.asInstanceOf[js.Any], d26 = d26.asInstanceOf[js.Any], d27 = d27.asInstanceOf[js.Any], d28 = d28.asInstanceOf[js.Any], d29 = d29.asInstanceOf[js.Any], d3 = d3.asInstanceOf[js.Any], d30 = d30.asInstanceOf[js.Any], d31 = d31.asInstanceOf[js.Any], d4 = d4.asInstanceOf[js.Any], d5 = d5.asInstanceOf[js.Any], d6 = d6.asInstanceOf[js.Any], d7 = d7.asInstanceOf[js.Any], d8 = d8.asInstanceOf[js.Any], d9 = d9.asInstanceOf[js.Any], lr = lr.asInstanceOf[js.Any], pc = pc.asInstanceOf[js.Any], q0 = q0.asInstanceOf[js.Any], q1 = q1.asInstanceOf[js.Any], q10 = q10.asInstanceOf[js.Any], q11 = q11.asInstanceOf[js.Any], q12 = q12.asInstanceOf[js.Any], q13 = q13.asInstanceOf[js.Any], q14 = q14.asInstanceOf[js.Any], q15 = q15.asInstanceOf[js.Any], q2 = q2.asInstanceOf[js.Any], q3 = q3.asInstanceOf[js.Any], q4 = q4.asInstanceOf[js.Any], q5 = q5.asInstanceOf[js.Any], q6 = q6.asInstanceOf[js.Any], q7 = q7.asInstanceOf[js.Any], q8 = q8.asInstanceOf[js.Any], q9 = q9.asInstanceOf[js.Any], r0 = r0.asInstanceOf[js.Any], r1 = r1.asInstanceOf[js.Any], r10 = r10.asInstanceOf[js.Any], r11 = r11.asInstanceOf[js.Any], r12 = r12.asInstanceOf[js.Any], r2 = r2.asInstanceOf[js.Any], r3 = r3.asInstanceOf[js.Any], r4 = r4.asInstanceOf[js.Any], r5 = r5.asInstanceOf[js.Any], r6 = r6.asInstanceOf[js.Any], r7 = r7.asInstanceOf[js.Any], r8 = r8.asInstanceOf[js.Any], r9 = r9.asInstanceOf[js.Any], s0 = s0.asInstanceOf[js.Any], s1 = s1.asInstanceOf[js.Any], s10 = s10.asInstanceOf[js.Any], s11 = s11.asInstanceOf[js.Any], s12 = s12.asInstanceOf[js.Any], s13 = s13.asInstanceOf[js.Any], s14 = s14.asInstanceOf[js.Any], s15 = s15.asInstanceOf[js.Any], s16 = s16.asInstanceOf[js.Any], s17 = s17.asInstanceOf[js.Any], s18 = s18.asInstanceOf[js.Any], s19 = s19.asInstanceOf[js.Any], s2 = s2.asInstanceOf[js.Any], s20 = s20.asInstanceOf[js.Any], s21 = s21.asInstanceOf[js.Any], s22 = s22.asInstanceOf[js.Any], s23 = s23.asInstanceOf[js.Any], s24 = s24.asInstanceOf[js.Any], s25 = s25.asInstanceOf[js.Any], s26 = s26.asInstanceOf[js.Any], s27 = s27.asInstanceOf[js.Any], s28 = s28.asInstanceOf[js.Any], s29 = s29.asInstanceOf[js.Any], s3 = s3.asInstanceOf[js.Any], s30 = s30.asInstanceOf[js.Any], s31 = s31.asInstanceOf[js.Any], s4 = s4.asInstanceOf[js.Any], s5 = s5.asInstanceOf[js.Any], s6 = s6.asInstanceOf[js.Any], s7 = s7.asInstanceOf[js.Any], s8 = s8.asInstanceOf[js.Any], s9 = s9.asInstanceOf[js.Any], sp = sp.asInstanceOf[js.Any])
    __obj.asInstanceOf[typings.fridaGum.ArmCpuContext]
  }
  
  inline def Ia32CpuContext(
    eax: NativePointer,
    ebp: NativePointer,
    ebx: NativePointer,
    ecx: NativePointer,
    edi: NativePointer,
    edx: NativePointer,
    eip: NativePointer,
    esi: NativePointer,
    esp: NativePointer,
    pc: NativePointer,
    sp: NativePointer
  ): typings.fridaGum.Ia32CpuContext = {
    val __obj = js.Dynamic.literal(eax = eax.asInstanceOf[js.Any], ebp = ebp.asInstanceOf[js.Any], ebx = ebx.asInstanceOf[js.Any], ecx = ecx.asInstanceOf[js.Any], edi = edi.asInstanceOf[js.Any], edx = edx.asInstanceOf[js.Any], eip = eip.asInstanceOf[js.Any], esi = esi.asInstanceOf[js.Any], esp = esp.asInstanceOf[js.Any], pc = pc.asInstanceOf[js.Any], sp = sp.asInstanceOf[js.Any])
    __obj.asInstanceOf[typings.fridaGum.Ia32CpuContext]
  }
  
  inline def MipsCpuContext(
    a0: NativePointer,
    a1: NativePointer,
    a2: NativePointer,
    a3: NativePointer,
    at: NativePointer,
    fp: NativePointer,
    gp: NativePointer,
    hi: NativePointer,
    k0: NativePointer,
    k1: NativePointer,
    lo: NativePointer,
    pc: NativePointer,
    ra: NativePointer,
    s0: NativePointer,
    s1: NativePointer,
    s2: NativePointer,
    s3: NativePointer,
    s4: NativePointer,
    s5: NativePointer,
    s6: NativePointer,
    s7: NativePointer,
    sp: NativePointer,
    t0: NativePointer,
    t1: NativePointer,
    t2: NativePointer,
    t3: NativePointer,
    t4: NativePointer,
    t5: NativePointer,
    t6: NativePointer,
    t7: NativePointer,
    t8: NativePointer,
    t9: NativePointer,
    v0: NativePointer,
    v1: NativePointer
  ): typings.fridaGum.MipsCpuContext = {
    val __obj = js.Dynamic.literal(a0 = a0.asInstanceOf[js.Any], a1 = a1.asInstanceOf[js.Any], a2 = a2.asInstanceOf[js.Any], a3 = a3.asInstanceOf[js.Any], at = at.asInstanceOf[js.Any], fp = fp.asInstanceOf[js.Any], gp = gp.asInstanceOf[js.Any], hi = hi.asInstanceOf[js.Any], k0 = k0.asInstanceOf[js.Any], k1 = k1.asInstanceOf[js.Any], lo = lo.asInstanceOf[js.Any], pc = pc.asInstanceOf[js.Any], ra = ra.asInstanceOf[js.Any], s0 = s0.asInstanceOf[js.Any], s1 = s1.asInstanceOf[js.Any], s2 = s2.asInstanceOf[js.Any], s3 = s3.asInstanceOf[js.Any], s4 = s4.asInstanceOf[js.Any], s5 = s5.asInstanceOf[js.Any], s6 = s6.asInstanceOf[js.Any], s7 = s7.asInstanceOf[js.Any], sp = sp.asInstanceOf[js.Any], t0 = t0.asInstanceOf[js.Any], t1 = t1.asInstanceOf[js.Any], t2 = t2.asInstanceOf[js.Any], t3 = t3.asInstanceOf[js.Any], t4 = t4.asInstanceOf[js.Any], t5 = t5.asInstanceOf[js.Any], t6 = t6.asInstanceOf[js.Any], t7 = t7.asInstanceOf[js.Any], t8 = t8.asInstanceOf[js.Any], t9 = t9.asInstanceOf[js.Any], v0 = v0.asInstanceOf[js.Any], v1 = v1.asInstanceOf[js.Any])
    __obj.asInstanceOf[typings.fridaGum.MipsCpuContext]
  }
  
  inline def PortableCpuContext(pc: NativePointer, sp: NativePointer): typings.fridaGum.PortableCpuContext = {
    val __obj = js.Dynamic.literal(pc = pc.asInstanceOf[js.Any], sp = sp.asInstanceOf[js.Any])
    __obj.asInstanceOf[typings.fridaGum.PortableCpuContext]
  }
  
  inline def X64CpuContext(
    pc: NativePointer,
    r10: NativePointer,
    r11: NativePointer,
    r12: NativePointer,
    r13: NativePointer,
    r14: NativePointer,
    r15: NativePointer,
    r8: NativePointer,
    r9: NativePointer,
    rax: NativePointer,
    rbp: NativePointer,
    rbx: NativePointer,
    rcx: NativePointer,
    rdi: NativePointer,
    rdx: NativePointer,
    rip: NativePointer,
    rsi: NativePointer,
    rsp: NativePointer,
    sp: NativePointer
  ): typings.fridaGum.X64CpuContext = {
    val __obj = js.Dynamic.literal(pc = pc.asInstanceOf[js.Any], r10 = r10.asInstanceOf[js.Any], r11 = r11.asInstanceOf[js.Any], r12 = r12.asInstanceOf[js.Any], r13 = r13.asInstanceOf[js.Any], r14 = r14.asInstanceOf[js.Any], r15 = r15.asInstanceOf[js.Any], r8 = r8.asInstanceOf[js.Any], r9 = r9.asInstanceOf[js.Any], rax = rax.asInstanceOf[js.Any], rbp = rbp.asInstanceOf[js.Any], rbx = rbx.asInstanceOf[js.Any], rcx = rcx.asInstanceOf[js.Any], rdi = rdi.asInstanceOf[js.Any], rdx = rdx.asInstanceOf[js.Any], rip = rip.asInstanceOf[js.Any], rsi = rsi.asInstanceOf[js.Any], rsp = rsp.asInstanceOf[js.Any], sp = sp.asInstanceOf[js.Any])
    __obj.asInstanceOf[typings.fridaGum.X64CpuContext]
  }
}
