package typings
package preactLib.preactMod.Global.JSXNs

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait DOMAttributes
  extends preactLib.preactMod.PreactDOMAttributes {
  // Media Events
  var onAbort: js.UndefOr[GenericEventHandler] = js.undefined
  var onAbortCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onAnimationEnd: js.UndefOr[AnimationEventHandler] = js.undefined
  var onAnimationEndCapture: js.UndefOr[AnimationEventHandler] = js.undefined
  var onAnimationIteration: js.UndefOr[AnimationEventHandler] = js.undefined
  var onAnimationIterationCapture: js.UndefOr[AnimationEventHandler] = js.undefined
  // Animation Events
  var onAnimationStart: js.UndefOr[AnimationEventHandler] = js.undefined
  var onAnimationStartCapture: js.UndefOr[AnimationEventHandler] = js.undefined
  var onBlur: js.UndefOr[FocusEventHandler] = js.undefined
  var onBlurCapture: js.UndefOr[FocusEventHandler] = js.undefined
  var onCanPlay: js.UndefOr[GenericEventHandler] = js.undefined
  var onCanPlayCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onCanPlayThrough: js.UndefOr[GenericEventHandler] = js.undefined
  var onCanPlayThroughCapture: js.UndefOr[GenericEventHandler] = js.undefined
  // Form Events
  var onChange: js.UndefOr[GenericEventHandler] = js.undefined
  var onChangeCapture: js.UndefOr[GenericEventHandler] = js.undefined
  // MouseEvents
  var onClick: js.UndefOr[MouseEventHandler] = js.undefined
  var onClickCapture: js.UndefOr[MouseEventHandler] = js.undefined
  // Composition Events
  var onCompositionEnd: js.UndefOr[CompositionEventHandler] = js.undefined
  var onCompositionEndCapture: js.UndefOr[CompositionEventHandler] = js.undefined
  var onCompositionStart: js.UndefOr[CompositionEventHandler] = js.undefined
  var onCompositionStartCapture: js.UndefOr[CompositionEventHandler] = js.undefined
  var onCompositionUpdate: js.UndefOr[CompositionEventHandler] = js.undefined
  var onCompositionUpdateCapture: js.UndefOr[CompositionEventHandler] = js.undefined
  var onContextMenu: js.UndefOr[MouseEventHandler] = js.undefined
  var onContextMenuCapture: js.UndefOr[MouseEventHandler] = js.undefined
  // Clipboard Events
  var onCopy: js.UndefOr[ClipboardEventHandler] = js.undefined
  var onCopyCapture: js.UndefOr[ClipboardEventHandler] = js.undefined
  var onCut: js.UndefOr[ClipboardEventHandler] = js.undefined
  var onCutCapture: js.UndefOr[ClipboardEventHandler] = js.undefined
  var onDblClick: js.UndefOr[MouseEventHandler] = js.undefined
  var onDblClickCapture: js.UndefOr[MouseEventHandler] = js.undefined
  var onDrag: js.UndefOr[DragEventHandler] = js.undefined
  var onDragCapture: js.UndefOr[DragEventHandler] = js.undefined
  var onDragEnd: js.UndefOr[DragEventHandler] = js.undefined
  var onDragEndCapture: js.UndefOr[DragEventHandler] = js.undefined
  var onDragEnter: js.UndefOr[DragEventHandler] = js.undefined
  var onDragEnterCapture: js.UndefOr[DragEventHandler] = js.undefined
  var onDragExit: js.UndefOr[DragEventHandler] = js.undefined
  var onDragExitCapture: js.UndefOr[DragEventHandler] = js.undefined
  var onDragLeave: js.UndefOr[DragEventHandler] = js.undefined
  var onDragLeaveCapture: js.UndefOr[DragEventHandler] = js.undefined
  var onDragOver: js.UndefOr[DragEventHandler] = js.undefined
  var onDragOverCapture: js.UndefOr[DragEventHandler] = js.undefined
  var onDragStart: js.UndefOr[DragEventHandler] = js.undefined
  var onDragStartCapture: js.UndefOr[DragEventHandler] = js.undefined
  var onDrop: js.UndefOr[DragEventHandler] = js.undefined
  var onDropCapture: js.UndefOr[DragEventHandler] = js.undefined
  var onDurationChange: js.UndefOr[GenericEventHandler] = js.undefined
  var onDurationChangeCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onEmptied: js.UndefOr[GenericEventHandler] = js.undefined
  var onEmptiedCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onEncrypted: js.UndefOr[GenericEventHandler] = js.undefined
  var onEncryptedCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onEnded: js.UndefOr[GenericEventHandler] = js.undefined
  var onEndedCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onError: js.UndefOr[GenericEventHandler] = js.undefined
  // Focus Events
  var onFocus: js.UndefOr[FocusEventHandler] = js.undefined
  var onFocusCapture: js.UndefOr[FocusEventHandler] = js.undefined
  var onGotPointerCapture: js.UndefOr[PointerEventHandler] = js.undefined
  var onGotPointerCaptureCapture: js.UndefOr[PointerEventHandler] = js.undefined
  var onInput: js.UndefOr[GenericEventHandler] = js.undefined
  var onInputCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onInvalid: js.UndefOr[GenericEventHandler] = js.undefined
  // Keyboard Events
  var onKeyDown: js.UndefOr[KeyboardEventHandler] = js.undefined
  var onKeyDownCapture: js.UndefOr[KeyboardEventHandler] = js.undefined
  var onKeyPress: js.UndefOr[KeyboardEventHandler] = js.undefined
  var onKeyPressCapture: js.UndefOr[KeyboardEventHandler] = js.undefined
  var onKeyUp: js.UndefOr[KeyboardEventHandler] = js.undefined
  var onKeyUpCapture: js.UndefOr[KeyboardEventHandler] = js.undefined
  // Image Events
  var onLoad: js.UndefOr[GenericEventHandler] = js.undefined
  var onLoadCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onLoadStart: js.UndefOr[GenericEventHandler] = js.undefined
  var onLoadStartCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onLoadedData: js.UndefOr[GenericEventHandler] = js.undefined
  var onLoadedDataCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onLoadedMetadata: js.UndefOr[GenericEventHandler] = js.undefined
  var onLoadedMetadataCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onLostPointerCapture: js.UndefOr[PointerEventHandler] = js.undefined
  var onLostPointerCaptureCapture: js.UndefOr[PointerEventHandler] = js.undefined
  var onMouseDown: js.UndefOr[MouseEventHandler] = js.undefined
  var onMouseDownCapture: js.UndefOr[MouseEventHandler] = js.undefined
  var onMouseEnter: js.UndefOr[MouseEventHandler] = js.undefined
  var onMouseEnterCapture: js.UndefOr[MouseEventHandler] = js.undefined
  var onMouseLeave: js.UndefOr[MouseEventHandler] = js.undefined
  var onMouseLeaveCapture: js.UndefOr[MouseEventHandler] = js.undefined
  var onMouseMove: js.UndefOr[MouseEventHandler] = js.undefined
  var onMouseMoveCapture: js.UndefOr[MouseEventHandler] = js.undefined
  var onMouseOut: js.UndefOr[MouseEventHandler] = js.undefined
  var onMouseOutCapture: js.UndefOr[MouseEventHandler] = js.undefined
  var onMouseOver: js.UndefOr[MouseEventHandler] = js.undefined
  var onMouseOverCapture: js.UndefOr[MouseEventHandler] = js.undefined
  var onMouseUp: js.UndefOr[MouseEventHandler] = js.undefined
  var onMouseUpCapture: js.UndefOr[MouseEventHandler] = js.undefined
  var onPaste: js.UndefOr[ClipboardEventHandler] = js.undefined
  var onPasteCapture: js.UndefOr[ClipboardEventHandler] = js.undefined
  var onPause: js.UndefOr[GenericEventHandler] = js.undefined
  var onPauseCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onPlay: js.UndefOr[GenericEventHandler] = js.undefined
  var onPlayCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onPlaying: js.UndefOr[GenericEventHandler] = js.undefined
  var onPlayingCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onPointerCancel: js.UndefOr[PointerEventHandler] = js.undefined
  var onPointerCancelCapture: js.UndefOr[PointerEventHandler] = js.undefined
  var onPointerDown: js.UndefOr[PointerEventHandler] = js.undefined
  var onPointerDownCapture: js.UndefOr[PointerEventHandler] = js.undefined
  var onPointerEnter: js.UndefOr[PointerEventHandler] = js.undefined
  var onPointerEnterCapture: js.UndefOr[PointerEventHandler] = js.undefined
  var onPointerLeave: js.UndefOr[PointerEventHandler] = js.undefined
  var onPointerLeaveCapture: js.UndefOr[PointerEventHandler] = js.undefined
  var onPointerMove: js.UndefOr[PointerEventHandler] = js.undefined
  var onPointerMoveCapture: js.UndefOr[PointerEventHandler] = js.undefined
  var onPointerOut: js.UndefOr[PointerEventHandler] = js.undefined
  var onPointerOutCapture: js.UndefOr[PointerEventHandler] = js.undefined
  // Pointer Events
  var onPointerOver: js.UndefOr[PointerEventHandler] = js.undefined
  var onPointerOverCapture: js.UndefOr[PointerEventHandler] = js.undefined
  var onPointerUp: js.UndefOr[PointerEventHandler] = js.undefined
  var onPointerUpCapture: js.UndefOr[PointerEventHandler] = js.undefined
  var onProgress: js.UndefOr[GenericEventHandler] = js.undefined
  var onProgressCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onRateChange: js.UndefOr[GenericEventHandler] = js.undefined
  var onRateChangeCapture: js.UndefOr[GenericEventHandler] = js.undefined
  // UI Events
  var onScroll: js.UndefOr[UIEventHandler] = js.undefined
  var onScrollCapture: js.UndefOr[UIEventHandler] = js.undefined
  var onSearch: js.UndefOr[GenericEventHandler] = js.undefined
  var onSearchCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onSeeked: js.UndefOr[GenericEventHandler] = js.undefined
  var onSeekedCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onSeeking: js.UndefOr[GenericEventHandler] = js.undefined
  var onSeekingCapture: js.UndefOr[GenericEventHandler] = js.undefined
  // Selection Events
  var onSelect: js.UndefOr[GenericEventHandler] = js.undefined
  var onSelectCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onStalled: js.UndefOr[GenericEventHandler] = js.undefined
  var onStalledCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onSubmit: js.UndefOr[GenericEventHandler] = js.undefined
  var onSubmitCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onSuspend: js.UndefOr[GenericEventHandler] = js.undefined
  var onSuspendCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onTimeUpdate: js.UndefOr[GenericEventHandler] = js.undefined
  var onTimeUpdateCapture: js.UndefOr[GenericEventHandler] = js.undefined
  // Touch Events
  var onTouchCancel: js.UndefOr[TouchEventHandler] = js.undefined
  var onTouchCancelCapture: js.UndefOr[TouchEventHandler] = js.undefined
  var onTouchEnd: js.UndefOr[TouchEventHandler] = js.undefined
  var onTouchEndCapture: js.UndefOr[TouchEventHandler] = js.undefined
  var onTouchMove: js.UndefOr[TouchEventHandler] = js.undefined
  var onTouchMoveCapture: js.UndefOr[TouchEventHandler] = js.undefined
  var onTouchStart: js.UndefOr[TouchEventHandler] = js.undefined
  var onTouchStartCapture: js.UndefOr[TouchEventHandler] = js.undefined
  // Transition Events
  var onTransitionEnd: js.UndefOr[TransitionEventHandler] = js.undefined
  var onTransitionEndCapture: js.UndefOr[TransitionEventHandler] = js.undefined
  var onVolumeChange: js.UndefOr[GenericEventHandler] = js.undefined
  var onVolumeChangeCapture: js.UndefOr[GenericEventHandler] = js.undefined
  var onWaiting: js.UndefOr[GenericEventHandler] = js.undefined
  var onWaitingCapture: js.UndefOr[GenericEventHandler] = js.undefined
  // Wheel Events
  var onWheel: js.UndefOr[WheelEventHandler] = js.undefined
  var onWheelCapture: js.UndefOr[WheelEventHandler] = js.undefined
}

object DOMAttributes {
  @scala.inline
  def apply(
    children: preactLib.preactMod.ComponentChildren = null,
    dangerouslySetInnerHTML: preactLib.Anon_Html = null,
    onAbort: GenericEventHandler = null,
    onAbortCapture: GenericEventHandler = null,
    onAnimationEnd: AnimationEventHandler = null,
    onAnimationEndCapture: AnimationEventHandler = null,
    onAnimationIteration: AnimationEventHandler = null,
    onAnimationIterationCapture: AnimationEventHandler = null,
    onAnimationStart: AnimationEventHandler = null,
    onAnimationStartCapture: AnimationEventHandler = null,
    onBlur: FocusEventHandler = null,
    onBlurCapture: FocusEventHandler = null,
    onCanPlay: GenericEventHandler = null,
    onCanPlayCapture: GenericEventHandler = null,
    onCanPlayThrough: GenericEventHandler = null,
    onCanPlayThroughCapture: GenericEventHandler = null,
    onChange: GenericEventHandler = null,
    onChangeCapture: GenericEventHandler = null,
    onClick: MouseEventHandler = null,
    onClickCapture: MouseEventHandler = null,
    onCompositionEnd: CompositionEventHandler = null,
    onCompositionEndCapture: CompositionEventHandler = null,
    onCompositionStart: CompositionEventHandler = null,
    onCompositionStartCapture: CompositionEventHandler = null,
    onCompositionUpdate: CompositionEventHandler = null,
    onCompositionUpdateCapture: CompositionEventHandler = null,
    onContextMenu: MouseEventHandler = null,
    onContextMenuCapture: MouseEventHandler = null,
    onCopy: ClipboardEventHandler = null,
    onCopyCapture: ClipboardEventHandler = null,
    onCut: ClipboardEventHandler = null,
    onCutCapture: ClipboardEventHandler = null,
    onDblClick: MouseEventHandler = null,
    onDblClickCapture: MouseEventHandler = null,
    onDrag: DragEventHandler = null,
    onDragCapture: DragEventHandler = null,
    onDragEnd: DragEventHandler = null,
    onDragEndCapture: DragEventHandler = null,
    onDragEnter: DragEventHandler = null,
    onDragEnterCapture: DragEventHandler = null,
    onDragExit: DragEventHandler = null,
    onDragExitCapture: DragEventHandler = null,
    onDragLeave: DragEventHandler = null,
    onDragLeaveCapture: DragEventHandler = null,
    onDragOver: DragEventHandler = null,
    onDragOverCapture: DragEventHandler = null,
    onDragStart: DragEventHandler = null,
    onDragStartCapture: DragEventHandler = null,
    onDrop: DragEventHandler = null,
    onDropCapture: DragEventHandler = null,
    onDurationChange: GenericEventHandler = null,
    onDurationChangeCapture: GenericEventHandler = null,
    onEmptied: GenericEventHandler = null,
    onEmptiedCapture: GenericEventHandler = null,
    onEncrypted: GenericEventHandler = null,
    onEncryptedCapture: GenericEventHandler = null,
    onEnded: GenericEventHandler = null,
    onEndedCapture: GenericEventHandler = null,
    onError: GenericEventHandler = null,
    onFocus: FocusEventHandler = null,
    onFocusCapture: FocusEventHandler = null,
    onGotPointerCapture: PointerEventHandler = null,
    onGotPointerCaptureCapture: PointerEventHandler = null,
    onInput: GenericEventHandler = null,
    onInputCapture: GenericEventHandler = null,
    onInvalid: GenericEventHandler = null,
    onKeyDown: KeyboardEventHandler = null,
    onKeyDownCapture: KeyboardEventHandler = null,
    onKeyPress: KeyboardEventHandler = null,
    onKeyPressCapture: KeyboardEventHandler = null,
    onKeyUp: KeyboardEventHandler = null,
    onKeyUpCapture: KeyboardEventHandler = null,
    onLoad: GenericEventHandler = null,
    onLoadCapture: GenericEventHandler = null,
    onLoadStart: GenericEventHandler = null,
    onLoadStartCapture: GenericEventHandler = null,
    onLoadedData: GenericEventHandler = null,
    onLoadedDataCapture: GenericEventHandler = null,
    onLoadedMetadata: GenericEventHandler = null,
    onLoadedMetadataCapture: GenericEventHandler = null,
    onLostPointerCapture: PointerEventHandler = null,
    onLostPointerCaptureCapture: PointerEventHandler = null,
    onMouseDown: MouseEventHandler = null,
    onMouseDownCapture: MouseEventHandler = null,
    onMouseEnter: MouseEventHandler = null,
    onMouseEnterCapture: MouseEventHandler = null,
    onMouseLeave: MouseEventHandler = null,
    onMouseLeaveCapture: MouseEventHandler = null,
    onMouseMove: MouseEventHandler = null,
    onMouseMoveCapture: MouseEventHandler = null,
    onMouseOut: MouseEventHandler = null,
    onMouseOutCapture: MouseEventHandler = null,
    onMouseOver: MouseEventHandler = null,
    onMouseOverCapture: MouseEventHandler = null,
    onMouseUp: MouseEventHandler = null,
    onMouseUpCapture: MouseEventHandler = null,
    onPaste: ClipboardEventHandler = null,
    onPasteCapture: ClipboardEventHandler = null,
    onPause: GenericEventHandler = null,
    onPauseCapture: GenericEventHandler = null,
    onPlay: GenericEventHandler = null,
    onPlayCapture: GenericEventHandler = null,
    onPlaying: GenericEventHandler = null,
    onPlayingCapture: GenericEventHandler = null,
    onPointerCancel: PointerEventHandler = null,
    onPointerCancelCapture: PointerEventHandler = null,
    onPointerDown: PointerEventHandler = null,
    onPointerDownCapture: PointerEventHandler = null,
    onPointerEnter: PointerEventHandler = null,
    onPointerEnterCapture: PointerEventHandler = null,
    onPointerLeave: PointerEventHandler = null,
    onPointerLeaveCapture: PointerEventHandler = null,
    onPointerMove: PointerEventHandler = null,
    onPointerMoveCapture: PointerEventHandler = null,
    onPointerOut: PointerEventHandler = null,
    onPointerOutCapture: PointerEventHandler = null,
    onPointerOver: PointerEventHandler = null,
    onPointerOverCapture: PointerEventHandler = null,
    onPointerUp: PointerEventHandler = null,
    onPointerUpCapture: PointerEventHandler = null,
    onProgress: GenericEventHandler = null,
    onProgressCapture: GenericEventHandler = null,
    onRateChange: GenericEventHandler = null,
    onRateChangeCapture: GenericEventHandler = null,
    onScroll: UIEventHandler = null,
    onScrollCapture: UIEventHandler = null,
    onSearch: GenericEventHandler = null,
    onSearchCapture: GenericEventHandler = null,
    onSeeked: GenericEventHandler = null,
    onSeekedCapture: GenericEventHandler = null,
    onSeeking: GenericEventHandler = null,
    onSeekingCapture: GenericEventHandler = null,
    onSelect: GenericEventHandler = null,
    onSelectCapture: GenericEventHandler = null,
    onStalled: GenericEventHandler = null,
    onStalledCapture: GenericEventHandler = null,
    onSubmit: GenericEventHandler = null,
    onSubmitCapture: GenericEventHandler = null,
    onSuspend: GenericEventHandler = null,
    onSuspendCapture: GenericEventHandler = null,
    onTimeUpdate: GenericEventHandler = null,
    onTimeUpdateCapture: GenericEventHandler = null,
    onTouchCancel: TouchEventHandler = null,
    onTouchCancelCapture: TouchEventHandler = null,
    onTouchEnd: TouchEventHandler = null,
    onTouchEndCapture: TouchEventHandler = null,
    onTouchMove: TouchEventHandler = null,
    onTouchMoveCapture: TouchEventHandler = null,
    onTouchStart: TouchEventHandler = null,
    onTouchStartCapture: TouchEventHandler = null,
    onTransitionEnd: TransitionEventHandler = null,
    onTransitionEndCapture: TransitionEventHandler = null,
    onVolumeChange: GenericEventHandler = null,
    onVolumeChangeCapture: GenericEventHandler = null,
    onWaiting: GenericEventHandler = null,
    onWaitingCapture: GenericEventHandler = null,
    onWheel: WheelEventHandler = null,
    onWheelCapture: WheelEventHandler = null
  ): DOMAttributes = {
    val __obj = js.Dynamic.literal()
    if (children != null) __obj.updateDynamic("children")(children.asInstanceOf[js.Any])
    if (dangerouslySetInnerHTML != null) __obj.updateDynamic("dangerouslySetInnerHTML")(dangerouslySetInnerHTML)
    if (onAbort != null) __obj.updateDynamic("onAbort")(onAbort)
    if (onAbortCapture != null) __obj.updateDynamic("onAbortCapture")(onAbortCapture)
    if (onAnimationEnd != null) __obj.updateDynamic("onAnimationEnd")(onAnimationEnd)
    if (onAnimationEndCapture != null) __obj.updateDynamic("onAnimationEndCapture")(onAnimationEndCapture)
    if (onAnimationIteration != null) __obj.updateDynamic("onAnimationIteration")(onAnimationIteration)
    if (onAnimationIterationCapture != null) __obj.updateDynamic("onAnimationIterationCapture")(onAnimationIterationCapture)
    if (onAnimationStart != null) __obj.updateDynamic("onAnimationStart")(onAnimationStart)
    if (onAnimationStartCapture != null) __obj.updateDynamic("onAnimationStartCapture")(onAnimationStartCapture)
    if (onBlur != null) __obj.updateDynamic("onBlur")(onBlur)
    if (onBlurCapture != null) __obj.updateDynamic("onBlurCapture")(onBlurCapture)
    if (onCanPlay != null) __obj.updateDynamic("onCanPlay")(onCanPlay)
    if (onCanPlayCapture != null) __obj.updateDynamic("onCanPlayCapture")(onCanPlayCapture)
    if (onCanPlayThrough != null) __obj.updateDynamic("onCanPlayThrough")(onCanPlayThrough)
    if (onCanPlayThroughCapture != null) __obj.updateDynamic("onCanPlayThroughCapture")(onCanPlayThroughCapture)
    if (onChange != null) __obj.updateDynamic("onChange")(onChange)
    if (onChangeCapture != null) __obj.updateDynamic("onChangeCapture")(onChangeCapture)
    if (onClick != null) __obj.updateDynamic("onClick")(onClick)
    if (onClickCapture != null) __obj.updateDynamic("onClickCapture")(onClickCapture)
    if (onCompositionEnd != null) __obj.updateDynamic("onCompositionEnd")(onCompositionEnd)
    if (onCompositionEndCapture != null) __obj.updateDynamic("onCompositionEndCapture")(onCompositionEndCapture)
    if (onCompositionStart != null) __obj.updateDynamic("onCompositionStart")(onCompositionStart)
    if (onCompositionStartCapture != null) __obj.updateDynamic("onCompositionStartCapture")(onCompositionStartCapture)
    if (onCompositionUpdate != null) __obj.updateDynamic("onCompositionUpdate")(onCompositionUpdate)
    if (onCompositionUpdateCapture != null) __obj.updateDynamic("onCompositionUpdateCapture")(onCompositionUpdateCapture)
    if (onContextMenu != null) __obj.updateDynamic("onContextMenu")(onContextMenu)
    if (onContextMenuCapture != null) __obj.updateDynamic("onContextMenuCapture")(onContextMenuCapture)
    if (onCopy != null) __obj.updateDynamic("onCopy")(onCopy)
    if (onCopyCapture != null) __obj.updateDynamic("onCopyCapture")(onCopyCapture)
    if (onCut != null) __obj.updateDynamic("onCut")(onCut)
    if (onCutCapture != null) __obj.updateDynamic("onCutCapture")(onCutCapture)
    if (onDblClick != null) __obj.updateDynamic("onDblClick")(onDblClick)
    if (onDblClickCapture != null) __obj.updateDynamic("onDblClickCapture")(onDblClickCapture)
    if (onDrag != null) __obj.updateDynamic("onDrag")(onDrag)
    if (onDragCapture != null) __obj.updateDynamic("onDragCapture")(onDragCapture)
    if (onDragEnd != null) __obj.updateDynamic("onDragEnd")(onDragEnd)
    if (onDragEndCapture != null) __obj.updateDynamic("onDragEndCapture")(onDragEndCapture)
    if (onDragEnter != null) __obj.updateDynamic("onDragEnter")(onDragEnter)
    if (onDragEnterCapture != null) __obj.updateDynamic("onDragEnterCapture")(onDragEnterCapture)
    if (onDragExit != null) __obj.updateDynamic("onDragExit")(onDragExit)
    if (onDragExitCapture != null) __obj.updateDynamic("onDragExitCapture")(onDragExitCapture)
    if (onDragLeave != null) __obj.updateDynamic("onDragLeave")(onDragLeave)
    if (onDragLeaveCapture != null) __obj.updateDynamic("onDragLeaveCapture")(onDragLeaveCapture)
    if (onDragOver != null) __obj.updateDynamic("onDragOver")(onDragOver)
    if (onDragOverCapture != null) __obj.updateDynamic("onDragOverCapture")(onDragOverCapture)
    if (onDragStart != null) __obj.updateDynamic("onDragStart")(onDragStart)
    if (onDragStartCapture != null) __obj.updateDynamic("onDragStartCapture")(onDragStartCapture)
    if (onDrop != null) __obj.updateDynamic("onDrop")(onDrop)
    if (onDropCapture != null) __obj.updateDynamic("onDropCapture")(onDropCapture)
    if (onDurationChange != null) __obj.updateDynamic("onDurationChange")(onDurationChange)
    if (onDurationChangeCapture != null) __obj.updateDynamic("onDurationChangeCapture")(onDurationChangeCapture)
    if (onEmptied != null) __obj.updateDynamic("onEmptied")(onEmptied)
    if (onEmptiedCapture != null) __obj.updateDynamic("onEmptiedCapture")(onEmptiedCapture)
    if (onEncrypted != null) __obj.updateDynamic("onEncrypted")(onEncrypted)
    if (onEncryptedCapture != null) __obj.updateDynamic("onEncryptedCapture")(onEncryptedCapture)
    if (onEnded != null) __obj.updateDynamic("onEnded")(onEnded)
    if (onEndedCapture != null) __obj.updateDynamic("onEndedCapture")(onEndedCapture)
    if (onError != null) __obj.updateDynamic("onError")(onError)
    if (onFocus != null) __obj.updateDynamic("onFocus")(onFocus)
    if (onFocusCapture != null) __obj.updateDynamic("onFocusCapture")(onFocusCapture)
    if (onGotPointerCapture != null) __obj.updateDynamic("onGotPointerCapture")(onGotPointerCapture)
    if (onGotPointerCaptureCapture != null) __obj.updateDynamic("onGotPointerCaptureCapture")(onGotPointerCaptureCapture)
    if (onInput != null) __obj.updateDynamic("onInput")(onInput)
    if (onInputCapture != null) __obj.updateDynamic("onInputCapture")(onInputCapture)
    if (onInvalid != null) __obj.updateDynamic("onInvalid")(onInvalid)
    if (onKeyDown != null) __obj.updateDynamic("onKeyDown")(onKeyDown)
    if (onKeyDownCapture != null) __obj.updateDynamic("onKeyDownCapture")(onKeyDownCapture)
    if (onKeyPress != null) __obj.updateDynamic("onKeyPress")(onKeyPress)
    if (onKeyPressCapture != null) __obj.updateDynamic("onKeyPressCapture")(onKeyPressCapture)
    if (onKeyUp != null) __obj.updateDynamic("onKeyUp")(onKeyUp)
    if (onKeyUpCapture != null) __obj.updateDynamic("onKeyUpCapture")(onKeyUpCapture)
    if (onLoad != null) __obj.updateDynamic("onLoad")(onLoad)
    if (onLoadCapture != null) __obj.updateDynamic("onLoadCapture")(onLoadCapture)
    if (onLoadStart != null) __obj.updateDynamic("onLoadStart")(onLoadStart)
    if (onLoadStartCapture != null) __obj.updateDynamic("onLoadStartCapture")(onLoadStartCapture)
    if (onLoadedData != null) __obj.updateDynamic("onLoadedData")(onLoadedData)
    if (onLoadedDataCapture != null) __obj.updateDynamic("onLoadedDataCapture")(onLoadedDataCapture)
    if (onLoadedMetadata != null) __obj.updateDynamic("onLoadedMetadata")(onLoadedMetadata)
    if (onLoadedMetadataCapture != null) __obj.updateDynamic("onLoadedMetadataCapture")(onLoadedMetadataCapture)
    if (onLostPointerCapture != null) __obj.updateDynamic("onLostPointerCapture")(onLostPointerCapture)
    if (onLostPointerCaptureCapture != null) __obj.updateDynamic("onLostPointerCaptureCapture")(onLostPointerCaptureCapture)
    if (onMouseDown != null) __obj.updateDynamic("onMouseDown")(onMouseDown)
    if (onMouseDownCapture != null) __obj.updateDynamic("onMouseDownCapture")(onMouseDownCapture)
    if (onMouseEnter != null) __obj.updateDynamic("onMouseEnter")(onMouseEnter)
    if (onMouseEnterCapture != null) __obj.updateDynamic("onMouseEnterCapture")(onMouseEnterCapture)
    if (onMouseLeave != null) __obj.updateDynamic("onMouseLeave")(onMouseLeave)
    if (onMouseLeaveCapture != null) __obj.updateDynamic("onMouseLeaveCapture")(onMouseLeaveCapture)
    if (onMouseMove != null) __obj.updateDynamic("onMouseMove")(onMouseMove)
    if (onMouseMoveCapture != null) __obj.updateDynamic("onMouseMoveCapture")(onMouseMoveCapture)
    if (onMouseOut != null) __obj.updateDynamic("onMouseOut")(onMouseOut)
    if (onMouseOutCapture != null) __obj.updateDynamic("onMouseOutCapture")(onMouseOutCapture)
    if (onMouseOver != null) __obj.updateDynamic("onMouseOver")(onMouseOver)
    if (onMouseOverCapture != null) __obj.updateDynamic("onMouseOverCapture")(onMouseOverCapture)
    if (onMouseUp != null) __obj.updateDynamic("onMouseUp")(onMouseUp)
    if (onMouseUpCapture != null) __obj.updateDynamic("onMouseUpCapture")(onMouseUpCapture)
    if (onPaste != null) __obj.updateDynamic("onPaste")(onPaste)
    if (onPasteCapture != null) __obj.updateDynamic("onPasteCapture")(onPasteCapture)
    if (onPause != null) __obj.updateDynamic("onPause")(onPause)
    if (onPauseCapture != null) __obj.updateDynamic("onPauseCapture")(onPauseCapture)
    if (onPlay != null) __obj.updateDynamic("onPlay")(onPlay)
    if (onPlayCapture != null) __obj.updateDynamic("onPlayCapture")(onPlayCapture)
    if (onPlaying != null) __obj.updateDynamic("onPlaying")(onPlaying)
    if (onPlayingCapture != null) __obj.updateDynamic("onPlayingCapture")(onPlayingCapture)
    if (onPointerCancel != null) __obj.updateDynamic("onPointerCancel")(onPointerCancel)
    if (onPointerCancelCapture != null) __obj.updateDynamic("onPointerCancelCapture")(onPointerCancelCapture)
    if (onPointerDown != null) __obj.updateDynamic("onPointerDown")(onPointerDown)
    if (onPointerDownCapture != null) __obj.updateDynamic("onPointerDownCapture")(onPointerDownCapture)
    if (onPointerEnter != null) __obj.updateDynamic("onPointerEnter")(onPointerEnter)
    if (onPointerEnterCapture != null) __obj.updateDynamic("onPointerEnterCapture")(onPointerEnterCapture)
    if (onPointerLeave != null) __obj.updateDynamic("onPointerLeave")(onPointerLeave)
    if (onPointerLeaveCapture != null) __obj.updateDynamic("onPointerLeaveCapture")(onPointerLeaveCapture)
    if (onPointerMove != null) __obj.updateDynamic("onPointerMove")(onPointerMove)
    if (onPointerMoveCapture != null) __obj.updateDynamic("onPointerMoveCapture")(onPointerMoveCapture)
    if (onPointerOut != null) __obj.updateDynamic("onPointerOut")(onPointerOut)
    if (onPointerOutCapture != null) __obj.updateDynamic("onPointerOutCapture")(onPointerOutCapture)
    if (onPointerOver != null) __obj.updateDynamic("onPointerOver")(onPointerOver)
    if (onPointerOverCapture != null) __obj.updateDynamic("onPointerOverCapture")(onPointerOverCapture)
    if (onPointerUp != null) __obj.updateDynamic("onPointerUp")(onPointerUp)
    if (onPointerUpCapture != null) __obj.updateDynamic("onPointerUpCapture")(onPointerUpCapture)
    if (onProgress != null) __obj.updateDynamic("onProgress")(onProgress)
    if (onProgressCapture != null) __obj.updateDynamic("onProgressCapture")(onProgressCapture)
    if (onRateChange != null) __obj.updateDynamic("onRateChange")(onRateChange)
    if (onRateChangeCapture != null) __obj.updateDynamic("onRateChangeCapture")(onRateChangeCapture)
    if (onScroll != null) __obj.updateDynamic("onScroll")(onScroll)
    if (onScrollCapture != null) __obj.updateDynamic("onScrollCapture")(onScrollCapture)
    if (onSearch != null) __obj.updateDynamic("onSearch")(onSearch)
    if (onSearchCapture != null) __obj.updateDynamic("onSearchCapture")(onSearchCapture)
    if (onSeeked != null) __obj.updateDynamic("onSeeked")(onSeeked)
    if (onSeekedCapture != null) __obj.updateDynamic("onSeekedCapture")(onSeekedCapture)
    if (onSeeking != null) __obj.updateDynamic("onSeeking")(onSeeking)
    if (onSeekingCapture != null) __obj.updateDynamic("onSeekingCapture")(onSeekingCapture)
    if (onSelect != null) __obj.updateDynamic("onSelect")(onSelect)
    if (onSelectCapture != null) __obj.updateDynamic("onSelectCapture")(onSelectCapture)
    if (onStalled != null) __obj.updateDynamic("onStalled")(onStalled)
    if (onStalledCapture != null) __obj.updateDynamic("onStalledCapture")(onStalledCapture)
    if (onSubmit != null) __obj.updateDynamic("onSubmit")(onSubmit)
    if (onSubmitCapture != null) __obj.updateDynamic("onSubmitCapture")(onSubmitCapture)
    if (onSuspend != null) __obj.updateDynamic("onSuspend")(onSuspend)
    if (onSuspendCapture != null) __obj.updateDynamic("onSuspendCapture")(onSuspendCapture)
    if (onTimeUpdate != null) __obj.updateDynamic("onTimeUpdate")(onTimeUpdate)
    if (onTimeUpdateCapture != null) __obj.updateDynamic("onTimeUpdateCapture")(onTimeUpdateCapture)
    if (onTouchCancel != null) __obj.updateDynamic("onTouchCancel")(onTouchCancel)
    if (onTouchCancelCapture != null) __obj.updateDynamic("onTouchCancelCapture")(onTouchCancelCapture)
    if (onTouchEnd != null) __obj.updateDynamic("onTouchEnd")(onTouchEnd)
    if (onTouchEndCapture != null) __obj.updateDynamic("onTouchEndCapture")(onTouchEndCapture)
    if (onTouchMove != null) __obj.updateDynamic("onTouchMove")(onTouchMove)
    if (onTouchMoveCapture != null) __obj.updateDynamic("onTouchMoveCapture")(onTouchMoveCapture)
    if (onTouchStart != null) __obj.updateDynamic("onTouchStart")(onTouchStart)
    if (onTouchStartCapture != null) __obj.updateDynamic("onTouchStartCapture")(onTouchStartCapture)
    if (onTransitionEnd != null) __obj.updateDynamic("onTransitionEnd")(onTransitionEnd)
    if (onTransitionEndCapture != null) __obj.updateDynamic("onTransitionEndCapture")(onTransitionEndCapture)
    if (onVolumeChange != null) __obj.updateDynamic("onVolumeChange")(onVolumeChange)
    if (onVolumeChangeCapture != null) __obj.updateDynamic("onVolumeChangeCapture")(onVolumeChangeCapture)
    if (onWaiting != null) __obj.updateDynamic("onWaiting")(onWaiting)
    if (onWaitingCapture != null) __obj.updateDynamic("onWaitingCapture")(onWaitingCapture)
    if (onWheel != null) __obj.updateDynamic("onWheel")(onWheel)
    if (onWheelCapture != null) __obj.updateDynamic("onWheelCapture")(onWheelCapture)
    __obj.asInstanceOf[DOMAttributes]
  }
}

