package typings
package activexDashAccessLib.AccessNs

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSGlobal("Access.Form")
@js.native
class Form protected () extends js.Object {
  var `Access.Form_typekey`: Form = js.native
  val ActiveControl: Control = js.native
  var AfterBeginTransaction: java.lang.String = js.native
  var AfterBeginTransactionMacro: java.lang.String = js.native
  var AfterCommitTransaction: java.lang.String = js.native
  var AfterCommitTransactionMacro: java.lang.String = js.native
  var AfterDelConfirm: java.lang.String = js.native
  var AfterDelConfirmMacro: java.lang.String = js.native
  var AfterFinalRender: java.lang.String = js.native
  var AfterFinalRenderMacro: java.lang.String = js.native
  var AfterInsert: java.lang.String = js.native
  var AfterInsertMacro: java.lang.String = js.native
  var AfterLayout: java.lang.String = js.native
  var AfterLayoutMacro: java.lang.String = js.native
  var AfterRender: java.lang.String = js.native
  var AfterRenderMacro: java.lang.String = js.native
  var AfterUpdate: java.lang.String = js.native
  var AfterUpdateMacro: java.lang.String = js.native
  var AllowAdditions: scala.Boolean = js.native
  var AllowDatasheetView: scala.Boolean = js.native
  var AllowDeletions: scala.Boolean = js.native
  var AllowDesignChanges: scala.Boolean = js.native
  var AllowEditing: scala.Boolean = js.native
  var AllowEdits: scala.Boolean = js.native
  var AllowFilters: scala.Boolean = js.native
  var AllowFormView: scala.Boolean = js.native
  var AllowLayoutView: scala.Boolean = js.native
  var AllowPivotChartView: scala.Boolean = js.native
  var AllowPivotTableView: scala.Boolean = js.native
  var AllowUpdating: scala.Double = js.native
  val Application: activexDashAccessLib.AccessNs.Application = js.native
  var AutoCenter: scala.Boolean = js.native
  var AutoResize: scala.Boolean = js.native
  var BatchUpdates: scala.Boolean = js.native
  var BeforeBeginTransaction: java.lang.String = js.native
  var BeforeBeginTransactionMacro: java.lang.String = js.native
  var BeforeCommitTransaction: java.lang.String = js.native
  var BeforeCommitTransactionMacro: java.lang.String = js.native
  var BeforeDelConfirm: java.lang.String = js.native
  var BeforeDelConfirmMacro: java.lang.String = js.native
  var BeforeInsert: java.lang.String = js.native
  var BeforeInsertMacro: java.lang.String = js.native
  var BeforeQuery: java.lang.String = js.native
  var BeforeQueryMacro: java.lang.String = js.native
  var BeforeRender: java.lang.String = js.native
  var BeforeRenderMacro: java.lang.String = js.native
  var BeforeScreenTip: java.lang.String = js.native
  var BeforeScreenTipMacro: java.lang.String = js.native
  var BeforeUpdate: java.lang.String = js.native
  var BeforeUpdateMacro: java.lang.String = js.native
  var BeginBatchEdit: java.lang.String = js.native
  var BeginBatchEditMacro: java.lang.String = js.native
  var Bookmark: activexDashAdodbLib.ADODBNs.Bookmark | activexDashDaoLib.DAONs.Bookmark = js.native
  var BorderStyle: scala.Double = js.native
  var Caption: java.lang.String = js.native
  val ChartSpace: js.Any = js.native
  var CloseButton: scala.Boolean = js.native
  var CommandBeforeExecute: java.lang.String = js.native
  var CommandBeforeExecuteMacro: java.lang.String = js.native
  var CommandChecked: java.lang.String = js.native
  var CommandCheckedMacro: java.lang.String = js.native
  var CommandEnabled: java.lang.String = js.native
  var CommandEnabledMacro: java.lang.String = js.native
  var CommandExecute: java.lang.String = js.native
  var CommandExecuteMacro: java.lang.String = js.native
  var CommitOnClose: scala.Double = js.native
  var CommitOnNavigation: scala.Boolean = js.native
  val ConnectControl: Control = js.native
  var ConnectSynch: scala.Double = js.native
  var ControlBox: scala.Boolean = js.native
  @JSName("Controls")
  val Controls_Original: Controls = js.native
  var Count: scala.Double = js.native
  var CurrentRecord: scala.Double = js.native
  var CurrentSectionLeft: scala.Double = js.native
  var CurrentSectionTop: scala.Double = js.native
  var CurrentView: scala.Double = js.native
  var Cycle: scala.Double = js.native
  var DataChange: java.lang.String = js.native
  var DataChangeMacro: java.lang.String = js.native
  var DataEntry: scala.Boolean = js.native
  var DataSetChange: java.lang.String = js.native
  var DataSetChangeMacro: java.lang.String = js.native
  var DatasheetAlternateBackColor: scala.Double = js.native
  var DatasheetBackColor: scala.Double = js.native
  var DatasheetBorderLineStyle: scala.Double = js.native
  var DatasheetCellsEffect: scala.Double = js.native
  var DatasheetColumnHeaderUnderlineStyle: scala.Double = js.native
  var DatasheetFontHeight: scala.Double = js.native
  var DatasheetFontItalic: scala.Boolean = js.native
  var DatasheetFontName: java.lang.String = js.native
  var DatasheetFontUnderline: scala.Boolean = js.native
  var DatasheetFontWeight: scala.Double = js.native
  var DatasheetForeColor: scala.Double = js.native
  var DatasheetGridlinesBehavior: scala.Double = js.native
  var DatasheetGridlinesColor: scala.Double = js.native
  var DefaultEditing: scala.Double = js.native
  var DefaultView: scala.Double = js.native
  var Dirty: scala.Boolean = js.native
  var DisplayOnSharePointSite: scala.Double = js.native
  var DividingLines: scala.Boolean = js.native
  val Dynaset: js.Any = js.native
  var FastLaserPrinting: scala.Boolean = js.native
  var FetchDefaults: scala.Boolean = js.native
  var Filter: java.lang.String = js.native
  var FilterOn: scala.Boolean = js.native
  var FilterOnLoad: scala.Boolean = js.native
  var FitToScreen: scala.Boolean = js.native
  val Form: activexDashAccessLib.AccessNs.Form = js.native
  var FormName: java.lang.String = js.native
  var FrozenColumns: scala.Double = js.native
  var GridX: scala.Double = js.native
  var GridY: scala.Double = js.native
  var HasModule: scala.Boolean = js.native
  var HelpContextId: scala.Double = js.native
  var HelpFile: java.lang.String = js.native
  var HorizontalDatasheetGridlineStyle: scala.Double = js.native
  var Hwnd: scala.Double = js.native
  var InputParameters: java.lang.String = js.native
  var InsideHeight: scala.Double = js.native
  var InsideWidth: scala.Double = js.native
  var KeyPreview: scala.Boolean = js.native
  var LayoutForPrint: scala.Boolean = js.native
  var LogicalPageHeight: scala.Double = js.native
  var LogicalPageWidth: scala.Double = js.native
  var MaxButton: scala.Boolean = js.native
  var MaxRecButton: scala.Boolean = js.native
  var MaxRecords: scala.Double = js.native
  var MenuBar: java.lang.String = js.native
  var MinButton: scala.Boolean = js.native
  var MinMaxButtons: scala.Double = js.native
  var Modal: scala.Boolean = js.native
  val Module: activexDashAccessLib.AccessNs.Module = js.native
  var MouseWheel: java.lang.String = js.native
  var MouseWheelMacro: java.lang.String = js.native
  var Moveable: scala.Boolean = js.native
  var Name: java.lang.String = js.native
  var NavigationButtons: scala.Boolean = js.native
  var NavigationCaption: java.lang.String = js.native
  val NewRecord: scala.Double = js.native
  var OnActivate: java.lang.String = js.native
  var OnActivateMacro: java.lang.String = js.native
  var OnApplyFilter: java.lang.String = js.native
  var OnApplyFilterMacro: java.lang.String = js.native
  var OnClick: java.lang.String = js.native
  var OnClickMacro: java.lang.String = js.native
  var OnClose: java.lang.String = js.native
  var OnCloseMacro: java.lang.String = js.native
  var OnConnect: java.lang.String = js.native
  var OnConnectMacro: java.lang.String = js.native
  var OnCurrent: java.lang.String = js.native
  var OnCurrentMacro: java.lang.String = js.native
  var OnDblClick: java.lang.String = js.native
  var OnDblClickMacro: java.lang.String = js.native
  var OnDeactivate: java.lang.String = js.native
  var OnDeactivateMacro: java.lang.String = js.native
  var OnDelete: java.lang.String = js.native
  var OnDeleteMacro: java.lang.String = js.native
  var OnDirty: java.lang.String = js.native
  var OnDirtyMacro: java.lang.String = js.native
  var OnDisconnect: java.lang.String = js.native
  var OnDisconnectMacro: java.lang.String = js.native
  var OnError: java.lang.String = js.native
  var OnErrorMacro: java.lang.String = js.native
  var OnFilter: java.lang.String = js.native
  var OnFilterMacro: java.lang.String = js.native
  var OnGotFocus: java.lang.String = js.native
  var OnGotFocusMacro: java.lang.String = js.native
  var OnInsert: java.lang.String = js.native
  var OnKeyDown: java.lang.String = js.native
  var OnKeyDownMacro: java.lang.String = js.native
  var OnKeyPress: java.lang.String = js.native
  var OnKeyPressMacro: java.lang.String = js.native
  var OnKeyUp: java.lang.String = js.native
  var OnKeyUpMacro: java.lang.String = js.native
  var OnLoad: java.lang.String = js.native
  var OnLoadMacro: java.lang.String = js.native
  var OnLostFocus: java.lang.String = js.native
  var OnLostFocusMacro: java.lang.String = js.native
  var OnMenu: java.lang.String = js.native
  var OnMouseDown: java.lang.String = js.native
  var OnMouseDownMacro: java.lang.String = js.native
  var OnMouseMove: java.lang.String = js.native
  var OnMouseMoveMacro: java.lang.String = js.native
  var OnMouseUp: java.lang.String = js.native
  var OnMouseUpMacro: java.lang.String = js.native
  var OnOpen: java.lang.String = js.native
  var OnOpenMacro: java.lang.String = js.native
  var OnRecordExit: java.lang.String = js.native
  var OnRecordExitMacro: java.lang.String = js.native
  var OnResize: java.lang.String = js.native
  var OnResizeMacro: java.lang.String = js.native
  var OnTimer: java.lang.String = js.native
  var OnTimerMacro: java.lang.String = js.native
  var OnUndo: java.lang.String = js.native
  var OnUndoMacro: java.lang.String = js.native
  var OnUnload: java.lang.String = js.native
  var OnUnloadMacro: java.lang.String = js.native
  var OpenArgs: java.lang.String = js.native
  var OrderBy: java.lang.String = js.native
  var OrderByOn: scala.Boolean = js.native
  var OrderByOnLoad: scala.Boolean = js.native
  var Orientation: scala.Double = js.native
  var Page: scala.Double = js.native
  var Pages: scala.Double = js.native
  var PaintPalette: js.Any = js.native
  var Painting: scala.Boolean = js.native
  var PaletteSource: java.lang.String = js.native
  val Parent: js.Any = js.native
  var Picture: java.lang.String = js.native
  var PictureAlignment: scala.Double = js.native
  var PictureData: js.Any = js.native
  var PicturePalette: js.Any = js.native
  var PictureSizeMode: scala.Double = js.native
  var PictureTiling: scala.Boolean = js.native
  var PictureType: scala.Double = js.native
  val PivotTable: js.Any = js.native
  var PivotTableChange: java.lang.String = js.native
  var PivotTableChangeMacro: java.lang.String = js.native
  var PopUp: scala.Boolean = js.native
  var Printer: activexDashAccessLib.AccessNs.Printer = js.native
  @JSName("Properties")
  val Properties_Original: Properties = js.native
  var PrtDevMode: js.Any = js.native
  var PrtDevNames: js.Any = js.native
  var PrtMip: js.Any = js.native
  var Query: java.lang.String = js.native
  var QueryMacro: java.lang.String = js.native
  var RecordLocks: scala.Double = js.native
  var RecordSelectors: scala.Boolean = js.native
  var RecordSource: java.lang.String = js.native
  var RecordSourceQualifier: java.lang.String = js.native
  var Recordset: activexDashDaoLib.DAONs.Recordset | activexDashAdodbLib.ADODBNs.Recordset | scala.Null = js.native
  val RecordsetClone: activexDashDaoLib.DAONs.Recordset | activexDashAdodbLib.ADODBNs.Recordset = js.native
  var RecordsetType: scala.Double = js.native
  var ResyncCommand: java.lang.String = js.native
  var RibbonName: java.lang.String = js.native
  var RollbackTransaction: java.lang.String = js.native
  var RollbackTransactionMacro: java.lang.String = js.native
  var RowHeight: scala.Double = js.native
  var ScrollBars: scala.Double = js.native
  var SelHeight: scala.Double = js.native
  var SelLeft: scala.Double = js.native
  var SelTop: scala.Double = js.native
  var SelWidth: scala.Double = js.native
  var SelectionChange: java.lang.String = js.native
  var SelectionChangeMacro: java.lang.String = js.native
  var ServerFilter: java.lang.String = js.native
  var ServerFilterByForm: scala.Boolean = js.native
  var ShortcutMenu: scala.Boolean = js.native
  var ShortcutMenuBar: java.lang.String = js.native
  var ShowGrid: scala.Boolean = js.native
  var SplitFormDatasheet: AcSplitFormDatasheet = js.native
  var SplitFormOrientation: AcSplitFormOrientation = js.native
  var SplitFormPrinting: AcSplitFormPrinting = js.native
  var SplitFormSize: scala.Double = js.native
  var SplitFormSplitterBar: scala.Boolean = js.native
  var SplitFormSplitterBarSave: scala.Boolean = js.native
  var SubdatasheetExpanded: scala.Boolean = js.native
  var SubdatasheetHeight: scala.Double = js.native
  var TabularCharSet: scala.Double = js.native
  var TabularFamily: scala.Double = js.native
  var Tag: java.lang.String = js.native
  var TimerInterval: scala.Double = js.native
  var Toolbar: java.lang.String = js.native
  var UndoBatchEdit: java.lang.String = js.native
  var UndoBatchEditMacro: java.lang.String = js.native
  var UniqueTable: java.lang.String = js.native
  var UseDefaultPrinter: scala.Boolean = js.native
  var VerticalDatasheetGridlineStyle: scala.Double = js.native
  var ViewChange: java.lang.String = js.native
  var ViewChangeMacro: java.lang.String = js.native
  var ViewsAllowed: scala.Double = js.native
  var Visible: scala.Boolean = js.native
  var WhatsThisButton: scala.Boolean = js.native
  var Width: scala.Double = js.native
  var WindowHeight: scala.Double = js.native
  val WindowLeft: scala.Double = js.native
  val WindowTop: scala.Double = js.native
  var WindowWidth: scala.Double = js.native
  var ZoomControl: scala.Double = js.native
  var _Name: java.lang.String = js.native
  var acHiddenCurrentPage: scala.Double = js.native
  val accChildCount: scala.Double = js.native
  val accFocus: js.Any = js.native
  val accParent: js.Any = js.native
  val accSelection: js.Any = js.native
  def Controls[T](Index: java.lang.String): T = js.native
  // tslint:disable-next-line:no-unnecessary-generics
  def Controls[T](Index: scala.Double): T = js.native
  def DefaultControl(ControlType: scala.Double): Control = js.native
  /**
    * @param Right [Right=0]
    * @param Down [Down=0]
    */
  def GoToPage(PageNumber: scala.Double): scala.Unit = js.native
  def GoToPage(PageNumber: scala.Double, Right: scala.Double): scala.Unit = js.native
  def GoToPage(PageNumber: scala.Double, Right: scala.Double, Down: scala.Double): scala.Unit = js.native
  def Move(Left: scala.Double): scala.Unit = js.native
  def Move(Left: scala.Double, Top: scala.Double): scala.Unit = js.native
  def Move(Left: scala.Double, Top: scala.Double, Width: scala.Double): scala.Unit = js.native
  def Move(Left: scala.Double, Top: scala.Double, Width: scala.Double, Height: scala.Double): scala.Unit = js.native
  def Properties(Index: java.lang.String): AccessProperty = js.native
  def Properties(Index: scala.Double): AccessProperty = js.native
  def Recalc(): scala.Unit = js.native
  def Refresh(): scala.Unit = js.native
  def Repaint(): scala.Unit = js.native
  def Requery(): scala.Unit = js.native
  def Section(Index: AcFormSection): activexDashAccessLib.AccessNs.Section = js.native
  def Section(Index: java.lang.String): activexDashAccessLib.AccessNs.Section = js.native
  def SectionOld(Index: js.Any): Section = js.native
  def SetFocus(): scala.Unit = js.native
  def Undo(): scala.Unit = js.native
  def _Evaluate(bstrExpr: java.lang.String, ppsa: js.Any*): js.Any = js.native
  def accChild(varChild: js.Any): js.Any = js.native
  def accDefaultAction(): java.lang.String = js.native
  def accDefaultAction(varChild: js.Any): java.lang.String = js.native
  def accDescription(): java.lang.String = js.native
  def accDescription(varChild: js.Any): java.lang.String = js.native
  def accDoDefaultAction(): scala.Unit = js.native
  def accDoDefaultAction(varChild: js.Any): scala.Unit = js.native
  def accHelp(): java.lang.String = js.native
  def accHelp(varChild: js.Any): java.lang.String = js.native
  def accHelpTopic(pszHelpFile: java.lang.String): scala.Double = js.native
  def accHelpTopic(pszHelpFile: java.lang.String, varChild: js.Any): scala.Double = js.native
  def accHitTest(xLeft: scala.Double, yTop: scala.Double): js.Any = js.native
  def accKeyboardShortcut(): java.lang.String = js.native
  def accKeyboardShortcut(varChild: js.Any): java.lang.String = js.native
  def accLocation(pxLeft: scala.Double, pyTop: scala.Double, pcxWidth: scala.Double, pcyHeight: scala.Double): scala.Unit = js.native
  def accLocation(
    pxLeft: scala.Double,
    pyTop: scala.Double,
    pcxWidth: scala.Double,
    pcyHeight: scala.Double,
    varChild: js.Any
  ): scala.Unit = js.native
  def accName(): java.lang.String = js.native
  def accName(varChild: js.Any): java.lang.String = js.native
  def accNavigate(navDir: scala.Double): js.Any = js.native
  def accNavigate(navDir: scala.Double, varStart: js.Any): js.Any = js.native
  def accRole(): js.Any = js.native
  def accRole(varChild: js.Any): js.Any = js.native
  def accSelect(flagsSelect: scala.Double): scala.Unit = js.native
  def accSelect(flagsSelect: scala.Double, varChild: js.Any): scala.Unit = js.native
  def accState(): js.Any = js.native
  def accState(varChild: js.Any): js.Any = js.native
  def accValue(): java.lang.String = js.native
  def accValue(varChild: js.Any): java.lang.String = js.native
}

