package typings.atUifabricStyling

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Inlined std.Partial<@uifabric/styling.@uifabric/styling/lib/interfaces/ISemanticColors.ISemanticColors> */
trait PartialISemanticColors extends js.Object {
  var accentButtonBackground: js.UndefOr[String] = js.undefined
  var accentButtonText: js.UndefOr[String] = js.undefined
  var actionLink: js.UndefOr[String] = js.undefined
  var actionLinkHovered: js.UndefOr[String] = js.undefined
  var blockingBackground: js.UndefOr[String] = js.undefined
  var bodyBackground: js.UndefOr[String] = js.undefined
  var bodyDivider: js.UndefOr[String] = js.undefined
  var bodyFrameBackground: js.UndefOr[String] = js.undefined
  var bodyFrameDivider: js.UndefOr[String] = js.undefined
  var bodyStandoutBackground: js.UndefOr[String] = js.undefined
  var bodySubtext: js.UndefOr[String] = js.undefined
  var bodyText: js.UndefOr[String] = js.undefined
  var bodyTextChecked: js.UndefOr[String] = js.undefined
  var buttonBackground: js.UndefOr[String] = js.undefined
  var buttonBackgroundChecked: js.UndefOr[String] = js.undefined
  var buttonBackgroundCheckedHovered: js.UndefOr[String] = js.undefined
  var buttonBackgroundDisabled: js.UndefOr[String] = js.undefined
  var buttonBackgroundHovered: js.UndefOr[String] = js.undefined
  var buttonBackgroundPressed: js.UndefOr[String] = js.undefined
  var buttonBorder: js.UndefOr[String] = js.undefined
  var buttonBorderDisabled: js.UndefOr[String] = js.undefined
  var buttonText: js.UndefOr[String] = js.undefined
  var buttonTextChecked: js.UndefOr[String] = js.undefined
  var buttonTextCheckedHovered: js.UndefOr[String] = js.undefined
  var buttonTextDisabled: js.UndefOr[String] = js.undefined
  var buttonTextHovered: js.UndefOr[String] = js.undefined
  var buttonTextPressed: js.UndefOr[String] = js.undefined
  var defaultStateBackground: js.UndefOr[String] = js.undefined
  var disabledBackground: js.UndefOr[String] = js.undefined
  var disabledBodySubtext: js.UndefOr[String] = js.undefined
  var disabledBodyText: js.UndefOr[String] = js.undefined
  var disabledBorder: js.UndefOr[String] = js.undefined
  var disabledSubtext: js.UndefOr[String] = js.undefined
  var disabledText: js.UndefOr[String] = js.undefined
  var errorBackground: js.UndefOr[String] = js.undefined
  var errorText: js.UndefOr[String] = js.undefined
  var focusBorder: js.UndefOr[String] = js.undefined
  var inputBackground: js.UndefOr[String] = js.undefined
  var inputBackgroundChecked: js.UndefOr[String] = js.undefined
  var inputBackgroundCheckedHovered: js.UndefOr[String] = js.undefined
  var inputBorder: js.UndefOr[String] = js.undefined
  var inputBorderHovered: js.UndefOr[String] = js.undefined
  var inputFocusBorderAlt: js.UndefOr[String] = js.undefined
  var inputForegroundChecked: js.UndefOr[String] = js.undefined
  var inputIcon: js.UndefOr[String] = js.undefined
  var inputIconDisabled: js.UndefOr[String] = js.undefined
  var inputIconHovered: js.UndefOr[String] = js.undefined
  var inputPlaceholderBackgroundChecked: js.UndefOr[String] = js.undefined
  var inputPlaceholderText: js.UndefOr[String] = js.undefined
  var inputText: js.UndefOr[String] = js.undefined
  var inputTextHovered: js.UndefOr[String] = js.undefined
  var link: js.UndefOr[String] = js.undefined
  var linkHovered: js.UndefOr[String] = js.undefined
  var listBackground: js.UndefOr[String] = js.undefined
  var listHeaderBackgroundHovered: js.UndefOr[String] = js.undefined
  var listHeaderBackgroundPressed: js.UndefOr[String] = js.undefined
  var listItemBackgroundChecked: js.UndefOr[String] = js.undefined
  var listItemBackgroundCheckedHovered: js.UndefOr[String] = js.undefined
  var listItemBackgroundHovered: js.UndefOr[String] = js.undefined
  var listText: js.UndefOr[String] = js.undefined
  var listTextColor: js.UndefOr[String] = js.undefined
  var menuBackground: js.UndefOr[String] = js.undefined
  var menuDivider: js.UndefOr[String] = js.undefined
  var menuHeader: js.UndefOr[String] = js.undefined
  var menuIcon: js.UndefOr[String] = js.undefined
  var menuItemBackgroundChecked: js.UndefOr[String] = js.undefined
  var menuItemBackgroundHovered: js.UndefOr[String] = js.undefined
  var menuItemBackgroundPressed: js.UndefOr[String] = js.undefined
  var menuItemText: js.UndefOr[String] = js.undefined
  var menuItemTextHovered: js.UndefOr[String] = js.undefined
  var primaryButtonBackground: js.UndefOr[String] = js.undefined
  var primaryButtonBackgroundDisabled: js.UndefOr[String] = js.undefined
  var primaryButtonBackgroundHovered: js.UndefOr[String] = js.undefined
  var primaryButtonBackgroundPressed: js.UndefOr[String] = js.undefined
  var primaryButtonBorder: js.UndefOr[String] = js.undefined
  var primaryButtonText: js.UndefOr[String] = js.undefined
  var primaryButtonTextDisabled: js.UndefOr[String] = js.undefined
  var primaryButtonTextHovered: js.UndefOr[String] = js.undefined
  var primaryButtonTextPressed: js.UndefOr[String] = js.undefined
  var smallInputBorder: js.UndefOr[String] = js.undefined
  var successBackground: js.UndefOr[String] = js.undefined
  var successText: js.UndefOr[String] = js.undefined
  var variantBorder: js.UndefOr[String] = js.undefined
  var variantBorderHovered: js.UndefOr[String] = js.undefined
  var warningBackground: js.UndefOr[String] = js.undefined
  var warningHighlight: js.UndefOr[String] = js.undefined
  var warningText: js.UndefOr[String] = js.undefined
}

object PartialISemanticColors {
  @scala.inline
  def apply(
    accentButtonBackground: String = null,
    accentButtonText: String = null,
    actionLink: String = null,
    actionLinkHovered: String = null,
    blockingBackground: String = null,
    bodyBackground: String = null,
    bodyDivider: String = null,
    bodyFrameBackground: String = null,
    bodyFrameDivider: String = null,
    bodyStandoutBackground: String = null,
    bodySubtext: String = null,
    bodyText: String = null,
    bodyTextChecked: String = null,
    buttonBackground: String = null,
    buttonBackgroundChecked: String = null,
    buttonBackgroundCheckedHovered: String = null,
    buttonBackgroundDisabled: String = null,
    buttonBackgroundHovered: String = null,
    buttonBackgroundPressed: String = null,
    buttonBorder: String = null,
    buttonBorderDisabled: String = null,
    buttonText: String = null,
    buttonTextChecked: String = null,
    buttonTextCheckedHovered: String = null,
    buttonTextDisabled: String = null,
    buttonTextHovered: String = null,
    buttonTextPressed: String = null,
    defaultStateBackground: String = null,
    disabledBackground: String = null,
    disabledBodySubtext: String = null,
    disabledBodyText: String = null,
    disabledBorder: String = null,
    disabledSubtext: String = null,
    disabledText: String = null,
    errorBackground: String = null,
    errorText: String = null,
    focusBorder: String = null,
    inputBackground: String = null,
    inputBackgroundChecked: String = null,
    inputBackgroundCheckedHovered: String = null,
    inputBorder: String = null,
    inputBorderHovered: String = null,
    inputFocusBorderAlt: String = null,
    inputForegroundChecked: String = null,
    inputIcon: String = null,
    inputIconDisabled: String = null,
    inputIconHovered: String = null,
    inputPlaceholderBackgroundChecked: String = null,
    inputPlaceholderText: String = null,
    inputText: String = null,
    inputTextHovered: String = null,
    link: String = null,
    linkHovered: String = null,
    listBackground: String = null,
    listHeaderBackgroundHovered: String = null,
    listHeaderBackgroundPressed: String = null,
    listItemBackgroundChecked: String = null,
    listItemBackgroundCheckedHovered: String = null,
    listItemBackgroundHovered: String = null,
    listText: String = null,
    listTextColor: String = null,
    menuBackground: String = null,
    menuDivider: String = null,
    menuHeader: String = null,
    menuIcon: String = null,
    menuItemBackgroundChecked: String = null,
    menuItemBackgroundHovered: String = null,
    menuItemBackgroundPressed: String = null,
    menuItemText: String = null,
    menuItemTextHovered: String = null,
    primaryButtonBackground: String = null,
    primaryButtonBackgroundDisabled: String = null,
    primaryButtonBackgroundHovered: String = null,
    primaryButtonBackgroundPressed: String = null,
    primaryButtonBorder: String = null,
    primaryButtonText: String = null,
    primaryButtonTextDisabled: String = null,
    primaryButtonTextHovered: String = null,
    primaryButtonTextPressed: String = null,
    smallInputBorder: String = null,
    successBackground: String = null,
    successText: String = null,
    variantBorder: String = null,
    variantBorderHovered: String = null,
    warningBackground: String = null,
    warningHighlight: String = null,
    warningText: String = null
  ): PartialISemanticColors = {
    val __obj = js.Dynamic.literal()
    if (accentButtonBackground != null) __obj.updateDynamic("accentButtonBackground")(accentButtonBackground)
    if (accentButtonText != null) __obj.updateDynamic("accentButtonText")(accentButtonText)
    if (actionLink != null) __obj.updateDynamic("actionLink")(actionLink)
    if (actionLinkHovered != null) __obj.updateDynamic("actionLinkHovered")(actionLinkHovered)
    if (blockingBackground != null) __obj.updateDynamic("blockingBackground")(blockingBackground)
    if (bodyBackground != null) __obj.updateDynamic("bodyBackground")(bodyBackground)
    if (bodyDivider != null) __obj.updateDynamic("bodyDivider")(bodyDivider)
    if (bodyFrameBackground != null) __obj.updateDynamic("bodyFrameBackground")(bodyFrameBackground)
    if (bodyFrameDivider != null) __obj.updateDynamic("bodyFrameDivider")(bodyFrameDivider)
    if (bodyStandoutBackground != null) __obj.updateDynamic("bodyStandoutBackground")(bodyStandoutBackground)
    if (bodySubtext != null) __obj.updateDynamic("bodySubtext")(bodySubtext)
    if (bodyText != null) __obj.updateDynamic("bodyText")(bodyText)
    if (bodyTextChecked != null) __obj.updateDynamic("bodyTextChecked")(bodyTextChecked)
    if (buttonBackground != null) __obj.updateDynamic("buttonBackground")(buttonBackground)
    if (buttonBackgroundChecked != null) __obj.updateDynamic("buttonBackgroundChecked")(buttonBackgroundChecked)
    if (buttonBackgroundCheckedHovered != null) __obj.updateDynamic("buttonBackgroundCheckedHovered")(buttonBackgroundCheckedHovered)
    if (buttonBackgroundDisabled != null) __obj.updateDynamic("buttonBackgroundDisabled")(buttonBackgroundDisabled)
    if (buttonBackgroundHovered != null) __obj.updateDynamic("buttonBackgroundHovered")(buttonBackgroundHovered)
    if (buttonBackgroundPressed != null) __obj.updateDynamic("buttonBackgroundPressed")(buttonBackgroundPressed)
    if (buttonBorder != null) __obj.updateDynamic("buttonBorder")(buttonBorder)
    if (buttonBorderDisabled != null) __obj.updateDynamic("buttonBorderDisabled")(buttonBorderDisabled)
    if (buttonText != null) __obj.updateDynamic("buttonText")(buttonText)
    if (buttonTextChecked != null) __obj.updateDynamic("buttonTextChecked")(buttonTextChecked)
    if (buttonTextCheckedHovered != null) __obj.updateDynamic("buttonTextCheckedHovered")(buttonTextCheckedHovered)
    if (buttonTextDisabled != null) __obj.updateDynamic("buttonTextDisabled")(buttonTextDisabled)
    if (buttonTextHovered != null) __obj.updateDynamic("buttonTextHovered")(buttonTextHovered)
    if (buttonTextPressed != null) __obj.updateDynamic("buttonTextPressed")(buttonTextPressed)
    if (defaultStateBackground != null) __obj.updateDynamic("defaultStateBackground")(defaultStateBackground)
    if (disabledBackground != null) __obj.updateDynamic("disabledBackground")(disabledBackground)
    if (disabledBodySubtext != null) __obj.updateDynamic("disabledBodySubtext")(disabledBodySubtext)
    if (disabledBodyText != null) __obj.updateDynamic("disabledBodyText")(disabledBodyText)
    if (disabledBorder != null) __obj.updateDynamic("disabledBorder")(disabledBorder)
    if (disabledSubtext != null) __obj.updateDynamic("disabledSubtext")(disabledSubtext)
    if (disabledText != null) __obj.updateDynamic("disabledText")(disabledText)
    if (errorBackground != null) __obj.updateDynamic("errorBackground")(errorBackground)
    if (errorText != null) __obj.updateDynamic("errorText")(errorText)
    if (focusBorder != null) __obj.updateDynamic("focusBorder")(focusBorder)
    if (inputBackground != null) __obj.updateDynamic("inputBackground")(inputBackground)
    if (inputBackgroundChecked != null) __obj.updateDynamic("inputBackgroundChecked")(inputBackgroundChecked)
    if (inputBackgroundCheckedHovered != null) __obj.updateDynamic("inputBackgroundCheckedHovered")(inputBackgroundCheckedHovered)
    if (inputBorder != null) __obj.updateDynamic("inputBorder")(inputBorder)
    if (inputBorderHovered != null) __obj.updateDynamic("inputBorderHovered")(inputBorderHovered)
    if (inputFocusBorderAlt != null) __obj.updateDynamic("inputFocusBorderAlt")(inputFocusBorderAlt)
    if (inputForegroundChecked != null) __obj.updateDynamic("inputForegroundChecked")(inputForegroundChecked)
    if (inputIcon != null) __obj.updateDynamic("inputIcon")(inputIcon)
    if (inputIconDisabled != null) __obj.updateDynamic("inputIconDisabled")(inputIconDisabled)
    if (inputIconHovered != null) __obj.updateDynamic("inputIconHovered")(inputIconHovered)
    if (inputPlaceholderBackgroundChecked != null) __obj.updateDynamic("inputPlaceholderBackgroundChecked")(inputPlaceholderBackgroundChecked)
    if (inputPlaceholderText != null) __obj.updateDynamic("inputPlaceholderText")(inputPlaceholderText)
    if (inputText != null) __obj.updateDynamic("inputText")(inputText)
    if (inputTextHovered != null) __obj.updateDynamic("inputTextHovered")(inputTextHovered)
    if (link != null) __obj.updateDynamic("link")(link)
    if (linkHovered != null) __obj.updateDynamic("linkHovered")(linkHovered)
    if (listBackground != null) __obj.updateDynamic("listBackground")(listBackground)
    if (listHeaderBackgroundHovered != null) __obj.updateDynamic("listHeaderBackgroundHovered")(listHeaderBackgroundHovered)
    if (listHeaderBackgroundPressed != null) __obj.updateDynamic("listHeaderBackgroundPressed")(listHeaderBackgroundPressed)
    if (listItemBackgroundChecked != null) __obj.updateDynamic("listItemBackgroundChecked")(listItemBackgroundChecked)
    if (listItemBackgroundCheckedHovered != null) __obj.updateDynamic("listItemBackgroundCheckedHovered")(listItemBackgroundCheckedHovered)
    if (listItemBackgroundHovered != null) __obj.updateDynamic("listItemBackgroundHovered")(listItemBackgroundHovered)
    if (listText != null) __obj.updateDynamic("listText")(listText)
    if (listTextColor != null) __obj.updateDynamic("listTextColor")(listTextColor)
    if (menuBackground != null) __obj.updateDynamic("menuBackground")(menuBackground)
    if (menuDivider != null) __obj.updateDynamic("menuDivider")(menuDivider)
    if (menuHeader != null) __obj.updateDynamic("menuHeader")(menuHeader)
    if (menuIcon != null) __obj.updateDynamic("menuIcon")(menuIcon)
    if (menuItemBackgroundChecked != null) __obj.updateDynamic("menuItemBackgroundChecked")(menuItemBackgroundChecked)
    if (menuItemBackgroundHovered != null) __obj.updateDynamic("menuItemBackgroundHovered")(menuItemBackgroundHovered)
    if (menuItemBackgroundPressed != null) __obj.updateDynamic("menuItemBackgroundPressed")(menuItemBackgroundPressed)
    if (menuItemText != null) __obj.updateDynamic("menuItemText")(menuItemText)
    if (menuItemTextHovered != null) __obj.updateDynamic("menuItemTextHovered")(menuItemTextHovered)
    if (primaryButtonBackground != null) __obj.updateDynamic("primaryButtonBackground")(primaryButtonBackground)
    if (primaryButtonBackgroundDisabled != null) __obj.updateDynamic("primaryButtonBackgroundDisabled")(primaryButtonBackgroundDisabled)
    if (primaryButtonBackgroundHovered != null) __obj.updateDynamic("primaryButtonBackgroundHovered")(primaryButtonBackgroundHovered)
    if (primaryButtonBackgroundPressed != null) __obj.updateDynamic("primaryButtonBackgroundPressed")(primaryButtonBackgroundPressed)
    if (primaryButtonBorder != null) __obj.updateDynamic("primaryButtonBorder")(primaryButtonBorder)
    if (primaryButtonText != null) __obj.updateDynamic("primaryButtonText")(primaryButtonText)
    if (primaryButtonTextDisabled != null) __obj.updateDynamic("primaryButtonTextDisabled")(primaryButtonTextDisabled)
    if (primaryButtonTextHovered != null) __obj.updateDynamic("primaryButtonTextHovered")(primaryButtonTextHovered)
    if (primaryButtonTextPressed != null) __obj.updateDynamic("primaryButtonTextPressed")(primaryButtonTextPressed)
    if (smallInputBorder != null) __obj.updateDynamic("smallInputBorder")(smallInputBorder)
    if (successBackground != null) __obj.updateDynamic("successBackground")(successBackground)
    if (successText != null) __obj.updateDynamic("successText")(successText)
    if (variantBorder != null) __obj.updateDynamic("variantBorder")(variantBorder)
    if (variantBorderHovered != null) __obj.updateDynamic("variantBorderHovered")(variantBorderHovered)
    if (warningBackground != null) __obj.updateDynamic("warningBackground")(warningBackground)
    if (warningHighlight != null) __obj.updateDynamic("warningHighlight")(warningHighlight)
    if (warningText != null) __obj.updateDynamic("warningText")(warningText)
    __obj.asInstanceOf[PartialISemanticColors]
  }
}

