package typings.csstype.csstypeMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait VendorPropertiesHyphenFallback[TLength]
  extends VendorLonghandPropertiesHyphenFallback[TLength]
     with VendorShorthandPropertiesHyphenFallback[TLength]

object VendorPropertiesHyphenFallback {
  @scala.inline
  def apply[TLength](
    `-moz-animation`: AnimationProperty | js.Array[AnimationProperty] = null,
    `-moz-animation-delay`: GlobalsString | js.Array[GlobalsString] = null,
    `-moz-animation-direction`: AnimationDirectionProperty | js.Array[AnimationDirectionProperty] = null,
    `-moz-animation-duration`: GlobalsString | js.Array[GlobalsString] = null,
    `-moz-animation-fill-mode`: AnimationFillModeProperty | js.Array[AnimationFillModeProperty] = null,
    `-moz-animation-iteration-count`: AnimationIterationCountProperty | js.Array[AnimationIterationCountProperty] = null,
    `-moz-animation-name`: AnimationNameProperty | js.Array[AnimationNameProperty] = null,
    `-moz-animation-play-state`: AnimationPlayStateProperty | js.Array[AnimationPlayStateProperty] = null,
    `-moz-animation-timing-function`: AnimationTimingFunctionProperty | js.Array[AnimationTimingFunctionProperty] = null,
    `-moz-appearance`: MozAppearanceProperty | js.Array[MozAppearanceProperty] = null,
    `-moz-backface-visibility`: BackfaceVisibilityProperty | js.Array[BackfaceVisibilityProperty] = null,
    `-moz-border-bottom-colors`: MozBorderBottomColorsProperty | js.Array[MozBorderBottomColorsProperty] = null,
    `-moz-border-end-color`: BorderInlineEndColorProperty | js.Array[BorderInlineEndColorProperty] = null,
    `-moz-border-end-style`: BorderInlineEndStyleProperty | js.Array[BorderInlineEndStyleProperty] = null,
    `-moz-border-end-width`: BorderInlineEndWidthProperty[TLength] | js.Array[BorderInlineEndWidthProperty[TLength]] = null,
    `-moz-border-image`: BorderImageProperty | js.Array[BorderImageProperty] = null,
    `-moz-border-left-colors`: MozBorderLeftColorsProperty | js.Array[MozBorderLeftColorsProperty] = null,
    `-moz-border-right-colors`: MozBorderRightColorsProperty | js.Array[MozBorderRightColorsProperty] = null,
    `-moz-border-start-color`: BorderInlineStartColorProperty | js.Array[BorderInlineStartColorProperty] = null,
    `-moz-border-start-style`: BorderInlineStartStyleProperty | js.Array[BorderInlineStartStyleProperty] = null,
    `-moz-border-top-colors`: MozBorderTopColorsProperty | js.Array[MozBorderTopColorsProperty] = null,
    `-moz-box-sizing`: BoxSizingProperty | js.Array[BoxSizingProperty] = null,
    `-moz-column-count`: ColumnCountProperty | js.Array[ColumnCountProperty] = null,
    `-moz-column-fill`: ColumnFillProperty | js.Array[ColumnFillProperty] = null,
    `-moz-column-gap`: ColumnGapProperty[TLength] | js.Array[ColumnGapProperty[TLength]] = null,
    `-moz-column-rule`: ColumnRuleProperty[TLength] | js.Array[ColumnRuleProperty[TLength]] = null,
    `-moz-column-rule-color`: ColumnRuleColorProperty | js.Array[ColumnRuleColorProperty] = null,
    `-moz-column-rule-style`: ColumnRuleStyleProperty | js.Array[ColumnRuleStyleProperty] = null,
    `-moz-column-rule-width`: ColumnRuleWidthProperty[TLength] | js.Array[ColumnRuleWidthProperty[TLength]] = null,
    `-moz-column-width`: ColumnWidthProperty[TLength] | js.Array[ColumnWidthProperty[TLength]] = null,
    `-moz-columns`: ColumnsProperty[TLength] | js.Array[ColumnsProperty[TLength]] = null,
    `-moz-context-properties`: MozContextPropertiesProperty | js.Array[MozContextPropertiesProperty] = null,
    `-moz-float-edge`: MozFloatEdgeProperty | js.Array[MozFloatEdgeProperty] = null,
    `-moz-font-feature-settings`: FontFeatureSettingsProperty | js.Array[FontFeatureSettingsProperty] = null,
    `-moz-font-language-override`: FontLanguageOverrideProperty | js.Array[FontLanguageOverrideProperty] = null,
    `-moz-force-broken-image-icon`: GlobalsNumber | js.Array[GlobalsNumber] = null,
    `-moz-hyphens`: HyphensProperty | js.Array[HyphensProperty] = null,
    `-moz-image-region`: MozImageRegionProperty | js.Array[MozImageRegionProperty] = null,
    `-moz-margin-end`: MarginInlineEndProperty[TLength] | js.Array[MarginInlineEndProperty[TLength]] = null,
    `-moz-margin-start`: MarginInlineStartProperty[TLength] | js.Array[MarginInlineStartProperty[TLength]] = null,
    `-moz-orient`: MozOrientProperty | js.Array[MozOrientProperty] = null,
    `-moz-outline-radius-bottomleft`: MozOutlineRadiusBottomleftProperty[TLength] | js.Array[MozOutlineRadiusBottomleftProperty[TLength]] = null,
    `-moz-outline-radius-bottomright`: MozOutlineRadiusBottomrightProperty[TLength] | js.Array[MozOutlineRadiusBottomrightProperty[TLength]] = null,
    `-moz-outline-radius-topleft`: MozOutlineRadiusTopleftProperty[TLength] | js.Array[MozOutlineRadiusTopleftProperty[TLength]] = null,
    `-moz-outline-radius-topright`: MozOutlineRadiusToprightProperty[TLength] | js.Array[MozOutlineRadiusToprightProperty[TLength]] = null,
    `-moz-padding-end`: PaddingInlineEndProperty[TLength] | js.Array[PaddingInlineEndProperty[TLength]] = null,
    `-moz-padding-start`: PaddingInlineStartProperty[TLength] | js.Array[PaddingInlineStartProperty[TLength]] = null,
    `-moz-perspective`: PerspectiveProperty[TLength] | js.Array[PerspectiveProperty[TLength]] = null,
    `-moz-perspective-origin`: PerspectiveOriginProperty[TLength] | js.Array[PerspectiveOriginProperty[TLength]] = null,
    `-moz-stack-sizing`: MozStackSizingProperty | js.Array[MozStackSizingProperty] = null,
    `-moz-tab-size`: TabSizeProperty[TLength] | js.Array[TabSizeProperty[TLength]] = null,
    `-moz-text-size-adjust`: TextSizeAdjustProperty | js.Array[TextSizeAdjustProperty] = null,
    `-moz-transform-origin`: TransformOriginProperty[TLength] | js.Array[TransformOriginProperty[TLength]] = null,
    `-moz-transform-style`: TransformStyleProperty | js.Array[TransformStyleProperty] = null,
    `-moz-transition`: TransitionProperty | js.Array[TransitionProperty] = null,
    `-moz-transition-delay`: GlobalsString | js.Array[GlobalsString] = null,
    `-moz-transition-duration`: GlobalsString | js.Array[GlobalsString] = null,
    `-moz-transition-property`: TransitionPropertyProperty | js.Array[TransitionPropertyProperty] = null,
    `-moz-transition-timing-function`: TransitionTimingFunctionProperty | js.Array[TransitionTimingFunctionProperty] = null,
    `-moz-user-focus`: MozUserFocusProperty | js.Array[MozUserFocusProperty] = null,
    `-moz-user-modify`: MozUserModifyProperty | js.Array[MozUserModifyProperty] = null,
    `-moz-user-select`: UserSelectProperty | js.Array[UserSelectProperty] = null,
    `-moz-window-dragging`: MozWindowDraggingProperty | js.Array[MozWindowDraggingProperty] = null,
    `-ms-accelerator`: MsAcceleratorProperty | js.Array[MsAcceleratorProperty] = null,
    `-ms-align-self`: AlignSelfProperty | js.Array[AlignSelfProperty] = null,
    `-ms-block-progression`: MsBlockProgressionProperty | js.Array[MsBlockProgressionProperty] = null,
    `-ms-content-zoom-chaining`: MsContentZoomChainingProperty | js.Array[MsContentZoomChainingProperty] = null,
    `-ms-content-zoom-limit`: GlobalsString | js.Array[GlobalsString] = null,
    `-ms-content-zoom-limit-max`: GlobalsString | js.Array[GlobalsString] = null,
    `-ms-content-zoom-limit-min`: GlobalsString | js.Array[GlobalsString] = null,
    `-ms-content-zoom-snap`: MsContentZoomSnapProperty | js.Array[MsContentZoomSnapProperty] = null,
    `-ms-content-zoom-snap-points`: GlobalsString | js.Array[GlobalsString] = null,
    `-ms-content-zoom-snap-type`: MsContentZoomSnapTypeProperty | js.Array[MsContentZoomSnapTypeProperty] = null,
    `-ms-content-zooming`: MsContentZoomingProperty | js.Array[MsContentZoomingProperty] = null,
    `-ms-filter`: GlobalsString | js.Array[GlobalsString] = null,
    `-ms-flex`: FlexProperty[TLength] | js.Array[FlexProperty[TLength]] = null,
    `-ms-flex-direction`: FlexDirectionProperty | js.Array[FlexDirectionProperty] = null,
    `-ms-flex-positive`: GlobalsNumber | js.Array[GlobalsNumber] = null,
    `-ms-flow-from`: MsFlowFromProperty | js.Array[MsFlowFromProperty] = null,
    `-ms-flow-into`: MsFlowIntoProperty | js.Array[MsFlowIntoProperty] = null,
    `-ms-grid-columns`: GridAutoColumnsProperty[TLength] | js.Array[GridAutoColumnsProperty[TLength]] = null,
    `-ms-grid-rows`: GridAutoRowsProperty[TLength] | js.Array[GridAutoRowsProperty[TLength]] = null,
    `-ms-high-contrast-adjust`: MsHighContrastAdjustProperty | js.Array[MsHighContrastAdjustProperty] = null,
    `-ms-hyphenate-limit-chars`: MsHyphenateLimitCharsProperty | js.Array[MsHyphenateLimitCharsProperty] = null,
    `-ms-hyphenate-limit-lines`: MsHyphenateLimitLinesProperty | js.Array[MsHyphenateLimitLinesProperty] = null,
    `-ms-hyphenate-limit-zone`: MsHyphenateLimitZoneProperty[TLength] | js.Array[MsHyphenateLimitZoneProperty[TLength]] = null,
    `-ms-hyphens`: HyphensProperty | js.Array[HyphensProperty] = null,
    `-ms-ime-align`: MsImeAlignProperty | js.Array[MsImeAlignProperty] = null,
    `-ms-line-break`: LineBreakProperty | js.Array[LineBreakProperty] = null,
    `-ms-order`: GlobalsNumber | js.Array[GlobalsNumber] = null,
    `-ms-overflow-style`: MsOverflowStyleProperty | js.Array[MsOverflowStyleProperty] = null,
    `-ms-overflow-x`: OverflowXProperty | js.Array[OverflowXProperty] = null,
    `-ms-overflow-y`: OverflowYProperty | js.Array[OverflowYProperty] = null,
    `-ms-scroll-chaining`: MsScrollChainingProperty | js.Array[MsScrollChainingProperty] = null,
    `-ms-scroll-limit`: GlobalsString | js.Array[GlobalsString] = null,
    `-ms-scroll-limit-x-max`: MsScrollLimitXMaxProperty[TLength] | js.Array[MsScrollLimitXMaxProperty[TLength]] = null,
    `-ms-scroll-limit-x-min`: MsScrollLimitXMinProperty[TLength] | js.Array[MsScrollLimitXMinProperty[TLength]] = null,
    `-ms-scroll-limit-y-max`: MsScrollLimitYMaxProperty[TLength] | js.Array[MsScrollLimitYMaxProperty[TLength]] = null,
    `-ms-scroll-limit-y-min`: MsScrollLimitYMinProperty[TLength] | js.Array[MsScrollLimitYMinProperty[TLength]] = null,
    `-ms-scroll-rails`: MsScrollRailsProperty | js.Array[MsScrollRailsProperty] = null,
    `-ms-scroll-snap-points-x`: GlobalsString | js.Array[GlobalsString] = null,
    `-ms-scroll-snap-points-y`: GlobalsString | js.Array[GlobalsString] = null,
    `-ms-scroll-snap-type`: MsScrollSnapTypeProperty | js.Array[MsScrollSnapTypeProperty] = null,
    `-ms-scroll-snap-x`: GlobalsString | js.Array[GlobalsString] = null,
    `-ms-scroll-snap-y`: GlobalsString | js.Array[GlobalsString] = null,
    `-ms-scroll-translation`: MsScrollTranslationProperty | js.Array[MsScrollTranslationProperty] = null,
    `-ms-scrollbar-3dlight-color`: MsScrollbar3dlightColorProperty | js.Array[MsScrollbar3dlightColorProperty] = null,
    `-ms-scrollbar-arrow-color`: MsScrollbarArrowColorProperty | js.Array[MsScrollbarArrowColorProperty] = null,
    `-ms-scrollbar-base-color`: MsScrollbarBaseColorProperty | js.Array[MsScrollbarBaseColorProperty] = null,
    `-ms-scrollbar-darkshadow-color`: MsScrollbarDarkshadowColorProperty | js.Array[MsScrollbarDarkshadowColorProperty] = null,
    `-ms-scrollbar-face-color`: MsScrollbarFaceColorProperty | js.Array[MsScrollbarFaceColorProperty] = null,
    `-ms-scrollbar-highlight-color`: MsScrollbarHighlightColorProperty | js.Array[MsScrollbarHighlightColorProperty] = null,
    `-ms-scrollbar-shadow-color`: MsScrollbarShadowColorProperty | js.Array[MsScrollbarShadowColorProperty] = null,
    `-ms-scrollbar-track-color`: MsScrollbarTrackColorProperty | js.Array[MsScrollbarTrackColorProperty] = null,
    `-ms-text-autospace`: MsTextAutospaceProperty | js.Array[MsTextAutospaceProperty] = null,
    `-ms-text-combine-horizontal`: TextCombineUprightProperty | js.Array[TextCombineUprightProperty] = null,
    `-ms-text-overflow`: TextOverflowProperty | js.Array[TextOverflowProperty] = null,
    `-ms-touch-action`: TouchActionProperty | js.Array[TouchActionProperty] = null,
    `-ms-touch-select`: MsTouchSelectProperty | js.Array[MsTouchSelectProperty] = null,
    `-ms-transform`: TransformProperty | js.Array[TransformProperty] = null,
    `-ms-transform-origin`: TransformOriginProperty[TLength] | js.Array[TransformOriginProperty[TLength]] = null,
    `-ms-transition`: TransitionProperty | js.Array[TransitionProperty] = null,
    `-ms-transition-delay`: GlobalsString | js.Array[GlobalsString] = null,
    `-ms-transition-duration`: GlobalsString | js.Array[GlobalsString] = null,
    `-ms-transition-property`: TransitionPropertyProperty | js.Array[TransitionPropertyProperty] = null,
    `-ms-transition-timing-function`: TransitionTimingFunctionProperty | js.Array[TransitionTimingFunctionProperty] = null,
    `-ms-user-select`: MsUserSelectProperty | js.Array[MsUserSelectProperty] = null,
    `-ms-word-break`: WordBreakProperty | js.Array[WordBreakProperty] = null,
    `-ms-wrap-flow`: MsWrapFlowProperty | js.Array[MsWrapFlowProperty] = null,
    `-ms-wrap-margin`: MsWrapMarginProperty[TLength] | js.Array[MsWrapMarginProperty[TLength]] = null,
    `-ms-wrap-through`: MsWrapThroughProperty | js.Array[MsWrapThroughProperty] = null,
    `-ms-writing-mode`: WritingModeProperty | js.Array[WritingModeProperty] = null,
    `-o-object-fit`: ObjectFitProperty | js.Array[ObjectFitProperty] = null,
    `-o-object-position`: ObjectPositionProperty[TLength] | js.Array[ObjectPositionProperty[TLength]] = null,
    `-o-tab-size`: TabSizeProperty[TLength] | js.Array[TabSizeProperty[TLength]] = null,
    `-o-text-overflow`: TextOverflowProperty | js.Array[TextOverflowProperty] = null,
    `-o-transform-origin`: TransformOriginProperty[TLength] | js.Array[TransformOriginProperty[TLength]] = null,
    `-webkit-align-content`: AlignContentProperty | js.Array[AlignContentProperty] = null,
    `-webkit-align-items`: AlignItemsProperty | js.Array[AlignItemsProperty] = null,
    `-webkit-align-self`: AlignSelfProperty | js.Array[AlignSelfProperty] = null,
    `-webkit-animation`: AnimationProperty | js.Array[AnimationProperty] = null,
    `-webkit-animation-delay`: GlobalsString | js.Array[GlobalsString] = null,
    `-webkit-animation-direction`: AnimationDirectionProperty | js.Array[AnimationDirectionProperty] = null,
    `-webkit-animation-duration`: GlobalsString | js.Array[GlobalsString] = null,
    `-webkit-animation-fill-mode`: AnimationFillModeProperty | js.Array[AnimationFillModeProperty] = null,
    `-webkit-animation-iteration-count`: AnimationIterationCountProperty | js.Array[AnimationIterationCountProperty] = null,
    `-webkit-animation-name`: AnimationNameProperty | js.Array[AnimationNameProperty] = null,
    `-webkit-animation-play-state`: AnimationPlayStateProperty | js.Array[AnimationPlayStateProperty] = null,
    `-webkit-animation-timing-function`: AnimationTimingFunctionProperty | js.Array[AnimationTimingFunctionProperty] = null,
    `-webkit-appearance`: WebkitAppearanceProperty | js.Array[WebkitAppearanceProperty] = null,
    `-webkit-backdrop-filter`: BackdropFilterProperty | js.Array[BackdropFilterProperty] = null,
    `-webkit-backface-visibility`: BackfaceVisibilityProperty | js.Array[BackfaceVisibilityProperty] = null,
    `-webkit-background-clip`: BackgroundClipProperty | js.Array[BackgroundClipProperty] = null,
    `-webkit-background-origin`: BackgroundOriginProperty | js.Array[BackgroundOriginProperty] = null,
    `-webkit-background-size`: BackgroundSizeProperty[TLength] | js.Array[BackgroundSizeProperty[TLength]] = null,
    `-webkit-border-before`: WebkitBorderBeforeProperty[TLength] | js.Array[WebkitBorderBeforeProperty[TLength]] = null,
    `-webkit-border-before-color`: WebkitBorderBeforeColorProperty | js.Array[WebkitBorderBeforeColorProperty] = null,
    `-webkit-border-before-style`: WebkitBorderBeforeStyleProperty | js.Array[WebkitBorderBeforeStyleProperty] = null,
    `-webkit-border-before-width`: WebkitBorderBeforeWidthProperty[TLength] | js.Array[WebkitBorderBeforeWidthProperty[TLength]] = null,
    `-webkit-border-bottom-left-radius`: BorderBottomLeftRadiusProperty[TLength] | js.Array[BorderBottomLeftRadiusProperty[TLength]] = null,
    `-webkit-border-bottom-right-radius`: BorderBottomRightRadiusProperty[TLength] | js.Array[BorderBottomRightRadiusProperty[TLength]] = null,
    `-webkit-border-image`: BorderImageProperty | js.Array[BorderImageProperty] = null,
    `-webkit-border-image-slice`: BorderImageSliceProperty | js.Array[BorderImageSliceProperty] = null,
    `-webkit-border-radius`: BorderRadiusProperty[TLength] | js.Array[BorderRadiusProperty[TLength]] = null,
    `-webkit-border-top-left-radius`: BorderTopLeftRadiusProperty[TLength] | js.Array[BorderTopLeftRadiusProperty[TLength]] = null,
    `-webkit-border-top-right-radius`: BorderTopRightRadiusProperty[TLength] | js.Array[BorderTopRightRadiusProperty[TLength]] = null,
    `-webkit-box-decoration-break`: BoxDecorationBreakProperty | js.Array[BoxDecorationBreakProperty] = null,
    `-webkit-box-reflect`: WebkitBoxReflectProperty[TLength] | js.Array[WebkitBoxReflectProperty[TLength]] = null,
    `-webkit-box-shadow`: BoxShadowProperty | js.Array[BoxShadowProperty] = null,
    `-webkit-box-sizing`: BoxSizingProperty | js.Array[BoxSizingProperty] = null,
    `-webkit-clip-path`: ClipPathProperty | js.Array[ClipPathProperty] = null,
    `-webkit-color-adjust`: ColorAdjustProperty | js.Array[ColorAdjustProperty] = null,
    `-webkit-column-count`: ColumnCountProperty | js.Array[ColumnCountProperty] = null,
    `-webkit-column-fill`: ColumnFillProperty | js.Array[ColumnFillProperty] = null,
    `-webkit-column-gap`: ColumnGapProperty[TLength] | js.Array[ColumnGapProperty[TLength]] = null,
    `-webkit-column-rule`: ColumnRuleProperty[TLength] | js.Array[ColumnRuleProperty[TLength]] = null,
    `-webkit-column-rule-color`: ColumnRuleColorProperty | js.Array[ColumnRuleColorProperty] = null,
    `-webkit-column-rule-style`: ColumnRuleStyleProperty | js.Array[ColumnRuleStyleProperty] = null,
    `-webkit-column-rule-width`: ColumnRuleWidthProperty[TLength] | js.Array[ColumnRuleWidthProperty[TLength]] = null,
    `-webkit-column-span`: ColumnSpanProperty | js.Array[ColumnSpanProperty] = null,
    `-webkit-column-width`: ColumnWidthProperty[TLength] | js.Array[ColumnWidthProperty[TLength]] = null,
    `-webkit-columns`: ColumnsProperty[TLength] | js.Array[ColumnsProperty[TLength]] = null,
    `-webkit-filter`: FilterProperty | js.Array[FilterProperty] = null,
    `-webkit-flex`: FlexProperty[TLength] | js.Array[FlexProperty[TLength]] = null,
    `-webkit-flex-basis`: FlexBasisProperty[TLength] | js.Array[FlexBasisProperty[TLength]] = null,
    `-webkit-flex-direction`: FlexDirectionProperty | js.Array[FlexDirectionProperty] = null,
    `-webkit-flex-flow`: FlexFlowProperty | js.Array[FlexFlowProperty] = null,
    `-webkit-flex-grow`: GlobalsNumber | js.Array[GlobalsNumber] = null,
    `-webkit-flex-shrink`: GlobalsNumber | js.Array[GlobalsNumber] = null,
    `-webkit-flex-wrap`: FlexWrapProperty | js.Array[FlexWrapProperty] = null,
    `-webkit-font-feature-settings`: FontFeatureSettingsProperty | js.Array[FontFeatureSettingsProperty] = null,
    `-webkit-font-kerning`: FontKerningProperty | js.Array[FontKerningProperty] = null,
    `-webkit-font-variant-ligatures`: FontVariantLigaturesProperty | js.Array[FontVariantLigaturesProperty] = null,
    `-webkit-hyphens`: HyphensProperty | js.Array[HyphensProperty] = null,
    `-webkit-justify-content`: JustifyContentProperty | js.Array[JustifyContentProperty] = null,
    `-webkit-line-break`: LineBreakProperty | js.Array[LineBreakProperty] = null,
    `-webkit-line-clamp`: WebkitLineClampProperty | js.Array[WebkitLineClampProperty] = null,
    `-webkit-margin-end`: MarginInlineEndProperty[TLength] | js.Array[MarginInlineEndProperty[TLength]] = null,
    `-webkit-margin-start`: MarginInlineStartProperty[TLength] | js.Array[MarginInlineStartProperty[TLength]] = null,
    `-webkit-mask`: WebkitMaskProperty[TLength] | js.Array[WebkitMaskProperty[TLength]] = null,
    `-webkit-mask-attachment`: WebkitMaskAttachmentProperty | js.Array[WebkitMaskAttachmentProperty] = null,
    `-webkit-mask-clip`: WebkitMaskClipProperty | js.Array[WebkitMaskClipProperty] = null,
    `-webkit-mask-composite`: WebkitMaskCompositeProperty | js.Array[WebkitMaskCompositeProperty] = null,
    `-webkit-mask-image`: WebkitMaskImageProperty | js.Array[WebkitMaskImageProperty] = null,
    `-webkit-mask-origin`: WebkitMaskOriginProperty | js.Array[WebkitMaskOriginProperty] = null,
    `-webkit-mask-position`: WebkitMaskPositionProperty[TLength] | js.Array[WebkitMaskPositionProperty[TLength]] = null,
    `-webkit-mask-position-x`: WebkitMaskPositionXProperty[TLength] | js.Array[WebkitMaskPositionXProperty[TLength]] = null,
    `-webkit-mask-position-y`: WebkitMaskPositionYProperty[TLength] | js.Array[WebkitMaskPositionYProperty[TLength]] = null,
    `-webkit-mask-repeat`: WebkitMaskRepeatProperty | js.Array[WebkitMaskRepeatProperty] = null,
    `-webkit-mask-repeat-x`: WebkitMaskRepeatXProperty | js.Array[WebkitMaskRepeatXProperty] = null,
    `-webkit-mask-repeat-y`: WebkitMaskRepeatYProperty | js.Array[WebkitMaskRepeatYProperty] = null,
    `-webkit-mask-size`: WebkitMaskSizeProperty[TLength] | js.Array[WebkitMaskSizeProperty[TLength]] = null,
    `-webkit-max-inline-size`: MaxInlineSizeProperty[TLength] | js.Array[MaxInlineSizeProperty[TLength]] = null,
    `-webkit-order`: GlobalsNumber | js.Array[GlobalsNumber] = null,
    `-webkit-overflow-scrolling`: WebkitOverflowScrollingProperty | js.Array[WebkitOverflowScrollingProperty] = null,
    `-webkit-padding-end`: PaddingInlineEndProperty[TLength] | js.Array[PaddingInlineEndProperty[TLength]] = null,
    `-webkit-padding-start`: PaddingInlineStartProperty[TLength] | js.Array[PaddingInlineStartProperty[TLength]] = null,
    `-webkit-perspective`: PerspectiveProperty[TLength] | js.Array[PerspectiveProperty[TLength]] = null,
    `-webkit-perspective-origin`: PerspectiveOriginProperty[TLength] | js.Array[PerspectiveOriginProperty[TLength]] = null,
    `-webkit-scroll-snap-type`: ScrollSnapTypeProperty | js.Array[ScrollSnapTypeProperty] = null,
    `-webkit-shape-margin`: ShapeMarginProperty[TLength] | js.Array[ShapeMarginProperty[TLength]] = null,
    `-webkit-tap-highlight-color`: WebkitTapHighlightColorProperty | js.Array[WebkitTapHighlightColorProperty] = null,
    `-webkit-text-combine`: TextCombineUprightProperty | js.Array[TextCombineUprightProperty] = null,
    `-webkit-text-decoration-color`: TextDecorationColorProperty | js.Array[TextDecorationColorProperty] = null,
    `-webkit-text-decoration-line`: TextDecorationLineProperty | js.Array[TextDecorationLineProperty] = null,
    `-webkit-text-decoration-skip`: TextDecorationSkipProperty | js.Array[TextDecorationSkipProperty] = null,
    `-webkit-text-decoration-style`: TextDecorationStyleProperty | js.Array[TextDecorationStyleProperty] = null,
    `-webkit-text-emphasis`: TextEmphasisProperty | js.Array[TextEmphasisProperty] = null,
    `-webkit-text-emphasis-color`: TextEmphasisColorProperty | js.Array[TextEmphasisColorProperty] = null,
    `-webkit-text-emphasis-position`: GlobalsString | js.Array[GlobalsString] = null,
    `-webkit-text-emphasis-style`: TextEmphasisStyleProperty | js.Array[TextEmphasisStyleProperty] = null,
    `-webkit-text-fill-color`: WebkitTextFillColorProperty | js.Array[WebkitTextFillColorProperty] = null,
    `-webkit-text-orientation`: TextOrientationProperty | js.Array[TextOrientationProperty] = null,
    `-webkit-text-size-adjust`: TextSizeAdjustProperty | js.Array[TextSizeAdjustProperty] = null,
    `-webkit-text-stroke`: WebkitTextStrokeProperty[TLength] | js.Array[WebkitTextStrokeProperty[TLength]] = null,
    `-webkit-text-stroke-color`: WebkitTextStrokeColorProperty | js.Array[WebkitTextStrokeColorProperty] = null,
    `-webkit-text-stroke-width`: WebkitTextStrokeWidthProperty[TLength] | js.Array[WebkitTextStrokeWidthProperty[TLength]] = null,
    `-webkit-touch-callout`: WebkitTouchCalloutProperty | js.Array[WebkitTouchCalloutProperty] = null,
    `-webkit-transform`: TransformProperty | js.Array[TransformProperty] = null,
    `-webkit-transform-origin`: TransformOriginProperty[TLength] | js.Array[TransformOriginProperty[TLength]] = null,
    `-webkit-transform-style`: TransformStyleProperty | js.Array[TransformStyleProperty] = null,
    `-webkit-transition`: TransitionProperty | js.Array[TransitionProperty] = null,
    `-webkit-transition-delay`: GlobalsString | js.Array[GlobalsString] = null,
    `-webkit-transition-duration`: GlobalsString | js.Array[GlobalsString] = null,
    `-webkit-transition-property`: TransitionPropertyProperty | js.Array[TransitionPropertyProperty] = null,
    `-webkit-transition-timing-function`: TransitionTimingFunctionProperty | js.Array[TransitionTimingFunctionProperty] = null,
    `-webkit-user-modify`: WebkitUserModifyProperty | js.Array[WebkitUserModifyProperty] = null,
    `-webkit-user-select`: UserSelectProperty | js.Array[UserSelectProperty] = null,
    `-webkit-writing-mode`: WritingModeProperty | js.Array[WritingModeProperty] = null
  ): VendorPropertiesHyphenFallback[TLength] = {
    val __obj = js.Dynamic.literal()
    if (`-moz-animation` != null) __obj.updateDynamic("-moz-animation")(`-moz-animation`.asInstanceOf[js.Any])
    if (`-moz-animation-delay` != null) __obj.updateDynamic("-moz-animation-delay")(`-moz-animation-delay`.asInstanceOf[js.Any])
    if (`-moz-animation-direction` != null) __obj.updateDynamic("-moz-animation-direction")(`-moz-animation-direction`.asInstanceOf[js.Any])
    if (`-moz-animation-duration` != null) __obj.updateDynamic("-moz-animation-duration")(`-moz-animation-duration`.asInstanceOf[js.Any])
    if (`-moz-animation-fill-mode` != null) __obj.updateDynamic("-moz-animation-fill-mode")(`-moz-animation-fill-mode`.asInstanceOf[js.Any])
    if (`-moz-animation-iteration-count` != null) __obj.updateDynamic("-moz-animation-iteration-count")(`-moz-animation-iteration-count`.asInstanceOf[js.Any])
    if (`-moz-animation-name` != null) __obj.updateDynamic("-moz-animation-name")(`-moz-animation-name`.asInstanceOf[js.Any])
    if (`-moz-animation-play-state` != null) __obj.updateDynamic("-moz-animation-play-state")(`-moz-animation-play-state`.asInstanceOf[js.Any])
    if (`-moz-animation-timing-function` != null) __obj.updateDynamic("-moz-animation-timing-function")(`-moz-animation-timing-function`.asInstanceOf[js.Any])
    if (`-moz-appearance` != null) __obj.updateDynamic("-moz-appearance")(`-moz-appearance`.asInstanceOf[js.Any])
    if (`-moz-backface-visibility` != null) __obj.updateDynamic("-moz-backface-visibility")(`-moz-backface-visibility`.asInstanceOf[js.Any])
    if (`-moz-border-bottom-colors` != null) __obj.updateDynamic("-moz-border-bottom-colors")(`-moz-border-bottom-colors`.asInstanceOf[js.Any])
    if (`-moz-border-end-color` != null) __obj.updateDynamic("-moz-border-end-color")(`-moz-border-end-color`.asInstanceOf[js.Any])
    if (`-moz-border-end-style` != null) __obj.updateDynamic("-moz-border-end-style")(`-moz-border-end-style`.asInstanceOf[js.Any])
    if (`-moz-border-end-width` != null) __obj.updateDynamic("-moz-border-end-width")(`-moz-border-end-width`.asInstanceOf[js.Any])
    if (`-moz-border-image` != null) __obj.updateDynamic("-moz-border-image")(`-moz-border-image`.asInstanceOf[js.Any])
    if (`-moz-border-left-colors` != null) __obj.updateDynamic("-moz-border-left-colors")(`-moz-border-left-colors`.asInstanceOf[js.Any])
    if (`-moz-border-right-colors` != null) __obj.updateDynamic("-moz-border-right-colors")(`-moz-border-right-colors`.asInstanceOf[js.Any])
    if (`-moz-border-start-color` != null) __obj.updateDynamic("-moz-border-start-color")(`-moz-border-start-color`.asInstanceOf[js.Any])
    if (`-moz-border-start-style` != null) __obj.updateDynamic("-moz-border-start-style")(`-moz-border-start-style`.asInstanceOf[js.Any])
    if (`-moz-border-top-colors` != null) __obj.updateDynamic("-moz-border-top-colors")(`-moz-border-top-colors`.asInstanceOf[js.Any])
    if (`-moz-box-sizing` != null) __obj.updateDynamic("-moz-box-sizing")(`-moz-box-sizing`.asInstanceOf[js.Any])
    if (`-moz-column-count` != null) __obj.updateDynamic("-moz-column-count")(`-moz-column-count`.asInstanceOf[js.Any])
    if (`-moz-column-fill` != null) __obj.updateDynamic("-moz-column-fill")(`-moz-column-fill`.asInstanceOf[js.Any])
    if (`-moz-column-gap` != null) __obj.updateDynamic("-moz-column-gap")(`-moz-column-gap`.asInstanceOf[js.Any])
    if (`-moz-column-rule` != null) __obj.updateDynamic("-moz-column-rule")(`-moz-column-rule`.asInstanceOf[js.Any])
    if (`-moz-column-rule-color` != null) __obj.updateDynamic("-moz-column-rule-color")(`-moz-column-rule-color`.asInstanceOf[js.Any])
    if (`-moz-column-rule-style` != null) __obj.updateDynamic("-moz-column-rule-style")(`-moz-column-rule-style`.asInstanceOf[js.Any])
    if (`-moz-column-rule-width` != null) __obj.updateDynamic("-moz-column-rule-width")(`-moz-column-rule-width`.asInstanceOf[js.Any])
    if (`-moz-column-width` != null) __obj.updateDynamic("-moz-column-width")(`-moz-column-width`.asInstanceOf[js.Any])
    if (`-moz-columns` != null) __obj.updateDynamic("-moz-columns")(`-moz-columns`.asInstanceOf[js.Any])
    if (`-moz-context-properties` != null) __obj.updateDynamic("-moz-context-properties")(`-moz-context-properties`.asInstanceOf[js.Any])
    if (`-moz-float-edge` != null) __obj.updateDynamic("-moz-float-edge")(`-moz-float-edge`.asInstanceOf[js.Any])
    if (`-moz-font-feature-settings` != null) __obj.updateDynamic("-moz-font-feature-settings")(`-moz-font-feature-settings`.asInstanceOf[js.Any])
    if (`-moz-font-language-override` != null) __obj.updateDynamic("-moz-font-language-override")(`-moz-font-language-override`.asInstanceOf[js.Any])
    if (`-moz-force-broken-image-icon` != null) __obj.updateDynamic("-moz-force-broken-image-icon")(`-moz-force-broken-image-icon`.asInstanceOf[js.Any])
    if (`-moz-hyphens` != null) __obj.updateDynamic("-moz-hyphens")(`-moz-hyphens`.asInstanceOf[js.Any])
    if (`-moz-image-region` != null) __obj.updateDynamic("-moz-image-region")(`-moz-image-region`.asInstanceOf[js.Any])
    if (`-moz-margin-end` != null) __obj.updateDynamic("-moz-margin-end")(`-moz-margin-end`.asInstanceOf[js.Any])
    if (`-moz-margin-start` != null) __obj.updateDynamic("-moz-margin-start")(`-moz-margin-start`.asInstanceOf[js.Any])
    if (`-moz-orient` != null) __obj.updateDynamic("-moz-orient")(`-moz-orient`.asInstanceOf[js.Any])
    if (`-moz-outline-radius-bottomleft` != null) __obj.updateDynamic("-moz-outline-radius-bottomleft")(`-moz-outline-radius-bottomleft`.asInstanceOf[js.Any])
    if (`-moz-outline-radius-bottomright` != null) __obj.updateDynamic("-moz-outline-radius-bottomright")(`-moz-outline-radius-bottomright`.asInstanceOf[js.Any])
    if (`-moz-outline-radius-topleft` != null) __obj.updateDynamic("-moz-outline-radius-topleft")(`-moz-outline-radius-topleft`.asInstanceOf[js.Any])
    if (`-moz-outline-radius-topright` != null) __obj.updateDynamic("-moz-outline-radius-topright")(`-moz-outline-radius-topright`.asInstanceOf[js.Any])
    if (`-moz-padding-end` != null) __obj.updateDynamic("-moz-padding-end")(`-moz-padding-end`.asInstanceOf[js.Any])
    if (`-moz-padding-start` != null) __obj.updateDynamic("-moz-padding-start")(`-moz-padding-start`.asInstanceOf[js.Any])
    if (`-moz-perspective` != null) __obj.updateDynamic("-moz-perspective")(`-moz-perspective`.asInstanceOf[js.Any])
    if (`-moz-perspective-origin` != null) __obj.updateDynamic("-moz-perspective-origin")(`-moz-perspective-origin`.asInstanceOf[js.Any])
    if (`-moz-stack-sizing` != null) __obj.updateDynamic("-moz-stack-sizing")(`-moz-stack-sizing`.asInstanceOf[js.Any])
    if (`-moz-tab-size` != null) __obj.updateDynamic("-moz-tab-size")(`-moz-tab-size`.asInstanceOf[js.Any])
    if (`-moz-text-size-adjust` != null) __obj.updateDynamic("-moz-text-size-adjust")(`-moz-text-size-adjust`.asInstanceOf[js.Any])
    if (`-moz-transform-origin` != null) __obj.updateDynamic("-moz-transform-origin")(`-moz-transform-origin`.asInstanceOf[js.Any])
    if (`-moz-transform-style` != null) __obj.updateDynamic("-moz-transform-style")(`-moz-transform-style`.asInstanceOf[js.Any])
    if (`-moz-transition` != null) __obj.updateDynamic("-moz-transition")(`-moz-transition`.asInstanceOf[js.Any])
    if (`-moz-transition-delay` != null) __obj.updateDynamic("-moz-transition-delay")(`-moz-transition-delay`.asInstanceOf[js.Any])
    if (`-moz-transition-duration` != null) __obj.updateDynamic("-moz-transition-duration")(`-moz-transition-duration`.asInstanceOf[js.Any])
    if (`-moz-transition-property` != null) __obj.updateDynamic("-moz-transition-property")(`-moz-transition-property`.asInstanceOf[js.Any])
    if (`-moz-transition-timing-function` != null) __obj.updateDynamic("-moz-transition-timing-function")(`-moz-transition-timing-function`.asInstanceOf[js.Any])
    if (`-moz-user-focus` != null) __obj.updateDynamic("-moz-user-focus")(`-moz-user-focus`.asInstanceOf[js.Any])
    if (`-moz-user-modify` != null) __obj.updateDynamic("-moz-user-modify")(`-moz-user-modify`.asInstanceOf[js.Any])
    if (`-moz-user-select` != null) __obj.updateDynamic("-moz-user-select")(`-moz-user-select`.asInstanceOf[js.Any])
    if (`-moz-window-dragging` != null) __obj.updateDynamic("-moz-window-dragging")(`-moz-window-dragging`.asInstanceOf[js.Any])
    if (`-ms-accelerator` != null) __obj.updateDynamic("-ms-accelerator")(`-ms-accelerator`.asInstanceOf[js.Any])
    if (`-ms-align-self` != null) __obj.updateDynamic("-ms-align-self")(`-ms-align-self`.asInstanceOf[js.Any])
    if (`-ms-block-progression` != null) __obj.updateDynamic("-ms-block-progression")(`-ms-block-progression`.asInstanceOf[js.Any])
    if (`-ms-content-zoom-chaining` != null) __obj.updateDynamic("-ms-content-zoom-chaining")(`-ms-content-zoom-chaining`.asInstanceOf[js.Any])
    if (`-ms-content-zoom-limit` != null) __obj.updateDynamic("-ms-content-zoom-limit")(`-ms-content-zoom-limit`.asInstanceOf[js.Any])
    if (`-ms-content-zoom-limit-max` != null) __obj.updateDynamic("-ms-content-zoom-limit-max")(`-ms-content-zoom-limit-max`.asInstanceOf[js.Any])
    if (`-ms-content-zoom-limit-min` != null) __obj.updateDynamic("-ms-content-zoom-limit-min")(`-ms-content-zoom-limit-min`.asInstanceOf[js.Any])
    if (`-ms-content-zoom-snap` != null) __obj.updateDynamic("-ms-content-zoom-snap")(`-ms-content-zoom-snap`.asInstanceOf[js.Any])
    if (`-ms-content-zoom-snap-points` != null) __obj.updateDynamic("-ms-content-zoom-snap-points")(`-ms-content-zoom-snap-points`.asInstanceOf[js.Any])
    if (`-ms-content-zoom-snap-type` != null) __obj.updateDynamic("-ms-content-zoom-snap-type")(`-ms-content-zoom-snap-type`.asInstanceOf[js.Any])
    if (`-ms-content-zooming` != null) __obj.updateDynamic("-ms-content-zooming")(`-ms-content-zooming`.asInstanceOf[js.Any])
    if (`-ms-filter` != null) __obj.updateDynamic("-ms-filter")(`-ms-filter`.asInstanceOf[js.Any])
    if (`-ms-flex` != null) __obj.updateDynamic("-ms-flex")(`-ms-flex`.asInstanceOf[js.Any])
    if (`-ms-flex-direction` != null) __obj.updateDynamic("-ms-flex-direction")(`-ms-flex-direction`.asInstanceOf[js.Any])
    if (`-ms-flex-positive` != null) __obj.updateDynamic("-ms-flex-positive")(`-ms-flex-positive`.asInstanceOf[js.Any])
    if (`-ms-flow-from` != null) __obj.updateDynamic("-ms-flow-from")(`-ms-flow-from`.asInstanceOf[js.Any])
    if (`-ms-flow-into` != null) __obj.updateDynamic("-ms-flow-into")(`-ms-flow-into`.asInstanceOf[js.Any])
    if (`-ms-grid-columns` != null) __obj.updateDynamic("-ms-grid-columns")(`-ms-grid-columns`.asInstanceOf[js.Any])
    if (`-ms-grid-rows` != null) __obj.updateDynamic("-ms-grid-rows")(`-ms-grid-rows`.asInstanceOf[js.Any])
    if (`-ms-high-contrast-adjust` != null) __obj.updateDynamic("-ms-high-contrast-adjust")(`-ms-high-contrast-adjust`.asInstanceOf[js.Any])
    if (`-ms-hyphenate-limit-chars` != null) __obj.updateDynamic("-ms-hyphenate-limit-chars")(`-ms-hyphenate-limit-chars`.asInstanceOf[js.Any])
    if (`-ms-hyphenate-limit-lines` != null) __obj.updateDynamic("-ms-hyphenate-limit-lines")(`-ms-hyphenate-limit-lines`.asInstanceOf[js.Any])
    if (`-ms-hyphenate-limit-zone` != null) __obj.updateDynamic("-ms-hyphenate-limit-zone")(`-ms-hyphenate-limit-zone`.asInstanceOf[js.Any])
    if (`-ms-hyphens` != null) __obj.updateDynamic("-ms-hyphens")(`-ms-hyphens`.asInstanceOf[js.Any])
    if (`-ms-ime-align` != null) __obj.updateDynamic("-ms-ime-align")(`-ms-ime-align`.asInstanceOf[js.Any])
    if (`-ms-line-break` != null) __obj.updateDynamic("-ms-line-break")(`-ms-line-break`.asInstanceOf[js.Any])
    if (`-ms-order` != null) __obj.updateDynamic("-ms-order")(`-ms-order`.asInstanceOf[js.Any])
    if (`-ms-overflow-style` != null) __obj.updateDynamic("-ms-overflow-style")(`-ms-overflow-style`.asInstanceOf[js.Any])
    if (`-ms-overflow-x` != null) __obj.updateDynamic("-ms-overflow-x")(`-ms-overflow-x`.asInstanceOf[js.Any])
    if (`-ms-overflow-y` != null) __obj.updateDynamic("-ms-overflow-y")(`-ms-overflow-y`.asInstanceOf[js.Any])
    if (`-ms-scroll-chaining` != null) __obj.updateDynamic("-ms-scroll-chaining")(`-ms-scroll-chaining`.asInstanceOf[js.Any])
    if (`-ms-scroll-limit` != null) __obj.updateDynamic("-ms-scroll-limit")(`-ms-scroll-limit`.asInstanceOf[js.Any])
    if (`-ms-scroll-limit-x-max` != null) __obj.updateDynamic("-ms-scroll-limit-x-max")(`-ms-scroll-limit-x-max`.asInstanceOf[js.Any])
    if (`-ms-scroll-limit-x-min` != null) __obj.updateDynamic("-ms-scroll-limit-x-min")(`-ms-scroll-limit-x-min`.asInstanceOf[js.Any])
    if (`-ms-scroll-limit-y-max` != null) __obj.updateDynamic("-ms-scroll-limit-y-max")(`-ms-scroll-limit-y-max`.asInstanceOf[js.Any])
    if (`-ms-scroll-limit-y-min` != null) __obj.updateDynamic("-ms-scroll-limit-y-min")(`-ms-scroll-limit-y-min`.asInstanceOf[js.Any])
    if (`-ms-scroll-rails` != null) __obj.updateDynamic("-ms-scroll-rails")(`-ms-scroll-rails`.asInstanceOf[js.Any])
    if (`-ms-scroll-snap-points-x` != null) __obj.updateDynamic("-ms-scroll-snap-points-x")(`-ms-scroll-snap-points-x`.asInstanceOf[js.Any])
    if (`-ms-scroll-snap-points-y` != null) __obj.updateDynamic("-ms-scroll-snap-points-y")(`-ms-scroll-snap-points-y`.asInstanceOf[js.Any])
    if (`-ms-scroll-snap-type` != null) __obj.updateDynamic("-ms-scroll-snap-type")(`-ms-scroll-snap-type`.asInstanceOf[js.Any])
    if (`-ms-scroll-snap-x` != null) __obj.updateDynamic("-ms-scroll-snap-x")(`-ms-scroll-snap-x`.asInstanceOf[js.Any])
    if (`-ms-scroll-snap-y` != null) __obj.updateDynamic("-ms-scroll-snap-y")(`-ms-scroll-snap-y`.asInstanceOf[js.Any])
    if (`-ms-scroll-translation` != null) __obj.updateDynamic("-ms-scroll-translation")(`-ms-scroll-translation`.asInstanceOf[js.Any])
    if (`-ms-scrollbar-3dlight-color` != null) __obj.updateDynamic("-ms-scrollbar-3dlight-color")(`-ms-scrollbar-3dlight-color`.asInstanceOf[js.Any])
    if (`-ms-scrollbar-arrow-color` != null) __obj.updateDynamic("-ms-scrollbar-arrow-color")(`-ms-scrollbar-arrow-color`.asInstanceOf[js.Any])
    if (`-ms-scrollbar-base-color` != null) __obj.updateDynamic("-ms-scrollbar-base-color")(`-ms-scrollbar-base-color`.asInstanceOf[js.Any])
    if (`-ms-scrollbar-darkshadow-color` != null) __obj.updateDynamic("-ms-scrollbar-darkshadow-color")(`-ms-scrollbar-darkshadow-color`.asInstanceOf[js.Any])
    if (`-ms-scrollbar-face-color` != null) __obj.updateDynamic("-ms-scrollbar-face-color")(`-ms-scrollbar-face-color`.asInstanceOf[js.Any])
    if (`-ms-scrollbar-highlight-color` != null) __obj.updateDynamic("-ms-scrollbar-highlight-color")(`-ms-scrollbar-highlight-color`.asInstanceOf[js.Any])
    if (`-ms-scrollbar-shadow-color` != null) __obj.updateDynamic("-ms-scrollbar-shadow-color")(`-ms-scrollbar-shadow-color`.asInstanceOf[js.Any])
    if (`-ms-scrollbar-track-color` != null) __obj.updateDynamic("-ms-scrollbar-track-color")(`-ms-scrollbar-track-color`.asInstanceOf[js.Any])
    if (`-ms-text-autospace` != null) __obj.updateDynamic("-ms-text-autospace")(`-ms-text-autospace`.asInstanceOf[js.Any])
    if (`-ms-text-combine-horizontal` != null) __obj.updateDynamic("-ms-text-combine-horizontal")(`-ms-text-combine-horizontal`.asInstanceOf[js.Any])
    if (`-ms-text-overflow` != null) __obj.updateDynamic("-ms-text-overflow")(`-ms-text-overflow`.asInstanceOf[js.Any])
    if (`-ms-touch-action` != null) __obj.updateDynamic("-ms-touch-action")(`-ms-touch-action`.asInstanceOf[js.Any])
    if (`-ms-touch-select` != null) __obj.updateDynamic("-ms-touch-select")(`-ms-touch-select`.asInstanceOf[js.Any])
    if (`-ms-transform` != null) __obj.updateDynamic("-ms-transform")(`-ms-transform`.asInstanceOf[js.Any])
    if (`-ms-transform-origin` != null) __obj.updateDynamic("-ms-transform-origin")(`-ms-transform-origin`.asInstanceOf[js.Any])
    if (`-ms-transition` != null) __obj.updateDynamic("-ms-transition")(`-ms-transition`.asInstanceOf[js.Any])
    if (`-ms-transition-delay` != null) __obj.updateDynamic("-ms-transition-delay")(`-ms-transition-delay`.asInstanceOf[js.Any])
    if (`-ms-transition-duration` != null) __obj.updateDynamic("-ms-transition-duration")(`-ms-transition-duration`.asInstanceOf[js.Any])
    if (`-ms-transition-property` != null) __obj.updateDynamic("-ms-transition-property")(`-ms-transition-property`.asInstanceOf[js.Any])
    if (`-ms-transition-timing-function` != null) __obj.updateDynamic("-ms-transition-timing-function")(`-ms-transition-timing-function`.asInstanceOf[js.Any])
    if (`-ms-user-select` != null) __obj.updateDynamic("-ms-user-select")(`-ms-user-select`.asInstanceOf[js.Any])
    if (`-ms-word-break` != null) __obj.updateDynamic("-ms-word-break")(`-ms-word-break`.asInstanceOf[js.Any])
    if (`-ms-wrap-flow` != null) __obj.updateDynamic("-ms-wrap-flow")(`-ms-wrap-flow`.asInstanceOf[js.Any])
    if (`-ms-wrap-margin` != null) __obj.updateDynamic("-ms-wrap-margin")(`-ms-wrap-margin`.asInstanceOf[js.Any])
    if (`-ms-wrap-through` != null) __obj.updateDynamic("-ms-wrap-through")(`-ms-wrap-through`.asInstanceOf[js.Any])
    if (`-ms-writing-mode` != null) __obj.updateDynamic("-ms-writing-mode")(`-ms-writing-mode`.asInstanceOf[js.Any])
    if (`-o-object-fit` != null) __obj.updateDynamic("-o-object-fit")(`-o-object-fit`.asInstanceOf[js.Any])
    if (`-o-object-position` != null) __obj.updateDynamic("-o-object-position")(`-o-object-position`.asInstanceOf[js.Any])
    if (`-o-tab-size` != null) __obj.updateDynamic("-o-tab-size")(`-o-tab-size`.asInstanceOf[js.Any])
    if (`-o-text-overflow` != null) __obj.updateDynamic("-o-text-overflow")(`-o-text-overflow`.asInstanceOf[js.Any])
    if (`-o-transform-origin` != null) __obj.updateDynamic("-o-transform-origin")(`-o-transform-origin`.asInstanceOf[js.Any])
    if (`-webkit-align-content` != null) __obj.updateDynamic("-webkit-align-content")(`-webkit-align-content`.asInstanceOf[js.Any])
    if (`-webkit-align-items` != null) __obj.updateDynamic("-webkit-align-items")(`-webkit-align-items`.asInstanceOf[js.Any])
    if (`-webkit-align-self` != null) __obj.updateDynamic("-webkit-align-self")(`-webkit-align-self`.asInstanceOf[js.Any])
    if (`-webkit-animation` != null) __obj.updateDynamic("-webkit-animation")(`-webkit-animation`.asInstanceOf[js.Any])
    if (`-webkit-animation-delay` != null) __obj.updateDynamic("-webkit-animation-delay")(`-webkit-animation-delay`.asInstanceOf[js.Any])
    if (`-webkit-animation-direction` != null) __obj.updateDynamic("-webkit-animation-direction")(`-webkit-animation-direction`.asInstanceOf[js.Any])
    if (`-webkit-animation-duration` != null) __obj.updateDynamic("-webkit-animation-duration")(`-webkit-animation-duration`.asInstanceOf[js.Any])
    if (`-webkit-animation-fill-mode` != null) __obj.updateDynamic("-webkit-animation-fill-mode")(`-webkit-animation-fill-mode`.asInstanceOf[js.Any])
    if (`-webkit-animation-iteration-count` != null) __obj.updateDynamic("-webkit-animation-iteration-count")(`-webkit-animation-iteration-count`.asInstanceOf[js.Any])
    if (`-webkit-animation-name` != null) __obj.updateDynamic("-webkit-animation-name")(`-webkit-animation-name`.asInstanceOf[js.Any])
    if (`-webkit-animation-play-state` != null) __obj.updateDynamic("-webkit-animation-play-state")(`-webkit-animation-play-state`.asInstanceOf[js.Any])
    if (`-webkit-animation-timing-function` != null) __obj.updateDynamic("-webkit-animation-timing-function")(`-webkit-animation-timing-function`.asInstanceOf[js.Any])
    if (`-webkit-appearance` != null) __obj.updateDynamic("-webkit-appearance")(`-webkit-appearance`.asInstanceOf[js.Any])
    if (`-webkit-backdrop-filter` != null) __obj.updateDynamic("-webkit-backdrop-filter")(`-webkit-backdrop-filter`.asInstanceOf[js.Any])
    if (`-webkit-backface-visibility` != null) __obj.updateDynamic("-webkit-backface-visibility")(`-webkit-backface-visibility`.asInstanceOf[js.Any])
    if (`-webkit-background-clip` != null) __obj.updateDynamic("-webkit-background-clip")(`-webkit-background-clip`.asInstanceOf[js.Any])
    if (`-webkit-background-origin` != null) __obj.updateDynamic("-webkit-background-origin")(`-webkit-background-origin`.asInstanceOf[js.Any])
    if (`-webkit-background-size` != null) __obj.updateDynamic("-webkit-background-size")(`-webkit-background-size`.asInstanceOf[js.Any])
    if (`-webkit-border-before` != null) __obj.updateDynamic("-webkit-border-before")(`-webkit-border-before`.asInstanceOf[js.Any])
    if (`-webkit-border-before-color` != null) __obj.updateDynamic("-webkit-border-before-color")(`-webkit-border-before-color`.asInstanceOf[js.Any])
    if (`-webkit-border-before-style` != null) __obj.updateDynamic("-webkit-border-before-style")(`-webkit-border-before-style`.asInstanceOf[js.Any])
    if (`-webkit-border-before-width` != null) __obj.updateDynamic("-webkit-border-before-width")(`-webkit-border-before-width`.asInstanceOf[js.Any])
    if (`-webkit-border-bottom-left-radius` != null) __obj.updateDynamic("-webkit-border-bottom-left-radius")(`-webkit-border-bottom-left-radius`.asInstanceOf[js.Any])
    if (`-webkit-border-bottom-right-radius` != null) __obj.updateDynamic("-webkit-border-bottom-right-radius")(`-webkit-border-bottom-right-radius`.asInstanceOf[js.Any])
    if (`-webkit-border-image` != null) __obj.updateDynamic("-webkit-border-image")(`-webkit-border-image`.asInstanceOf[js.Any])
    if (`-webkit-border-image-slice` != null) __obj.updateDynamic("-webkit-border-image-slice")(`-webkit-border-image-slice`.asInstanceOf[js.Any])
    if (`-webkit-border-radius` != null) __obj.updateDynamic("-webkit-border-radius")(`-webkit-border-radius`.asInstanceOf[js.Any])
    if (`-webkit-border-top-left-radius` != null) __obj.updateDynamic("-webkit-border-top-left-radius")(`-webkit-border-top-left-radius`.asInstanceOf[js.Any])
    if (`-webkit-border-top-right-radius` != null) __obj.updateDynamic("-webkit-border-top-right-radius")(`-webkit-border-top-right-radius`.asInstanceOf[js.Any])
    if (`-webkit-box-decoration-break` != null) __obj.updateDynamic("-webkit-box-decoration-break")(`-webkit-box-decoration-break`.asInstanceOf[js.Any])
    if (`-webkit-box-reflect` != null) __obj.updateDynamic("-webkit-box-reflect")(`-webkit-box-reflect`.asInstanceOf[js.Any])
    if (`-webkit-box-shadow` != null) __obj.updateDynamic("-webkit-box-shadow")(`-webkit-box-shadow`.asInstanceOf[js.Any])
    if (`-webkit-box-sizing` != null) __obj.updateDynamic("-webkit-box-sizing")(`-webkit-box-sizing`.asInstanceOf[js.Any])
    if (`-webkit-clip-path` != null) __obj.updateDynamic("-webkit-clip-path")(`-webkit-clip-path`.asInstanceOf[js.Any])
    if (`-webkit-color-adjust` != null) __obj.updateDynamic("-webkit-color-adjust")(`-webkit-color-adjust`.asInstanceOf[js.Any])
    if (`-webkit-column-count` != null) __obj.updateDynamic("-webkit-column-count")(`-webkit-column-count`.asInstanceOf[js.Any])
    if (`-webkit-column-fill` != null) __obj.updateDynamic("-webkit-column-fill")(`-webkit-column-fill`.asInstanceOf[js.Any])
    if (`-webkit-column-gap` != null) __obj.updateDynamic("-webkit-column-gap")(`-webkit-column-gap`.asInstanceOf[js.Any])
    if (`-webkit-column-rule` != null) __obj.updateDynamic("-webkit-column-rule")(`-webkit-column-rule`.asInstanceOf[js.Any])
    if (`-webkit-column-rule-color` != null) __obj.updateDynamic("-webkit-column-rule-color")(`-webkit-column-rule-color`.asInstanceOf[js.Any])
    if (`-webkit-column-rule-style` != null) __obj.updateDynamic("-webkit-column-rule-style")(`-webkit-column-rule-style`.asInstanceOf[js.Any])
    if (`-webkit-column-rule-width` != null) __obj.updateDynamic("-webkit-column-rule-width")(`-webkit-column-rule-width`.asInstanceOf[js.Any])
    if (`-webkit-column-span` != null) __obj.updateDynamic("-webkit-column-span")(`-webkit-column-span`.asInstanceOf[js.Any])
    if (`-webkit-column-width` != null) __obj.updateDynamic("-webkit-column-width")(`-webkit-column-width`.asInstanceOf[js.Any])
    if (`-webkit-columns` != null) __obj.updateDynamic("-webkit-columns")(`-webkit-columns`.asInstanceOf[js.Any])
    if (`-webkit-filter` != null) __obj.updateDynamic("-webkit-filter")(`-webkit-filter`.asInstanceOf[js.Any])
    if (`-webkit-flex` != null) __obj.updateDynamic("-webkit-flex")(`-webkit-flex`.asInstanceOf[js.Any])
    if (`-webkit-flex-basis` != null) __obj.updateDynamic("-webkit-flex-basis")(`-webkit-flex-basis`.asInstanceOf[js.Any])
    if (`-webkit-flex-direction` != null) __obj.updateDynamic("-webkit-flex-direction")(`-webkit-flex-direction`.asInstanceOf[js.Any])
    if (`-webkit-flex-flow` != null) __obj.updateDynamic("-webkit-flex-flow")(`-webkit-flex-flow`.asInstanceOf[js.Any])
    if (`-webkit-flex-grow` != null) __obj.updateDynamic("-webkit-flex-grow")(`-webkit-flex-grow`.asInstanceOf[js.Any])
    if (`-webkit-flex-shrink` != null) __obj.updateDynamic("-webkit-flex-shrink")(`-webkit-flex-shrink`.asInstanceOf[js.Any])
    if (`-webkit-flex-wrap` != null) __obj.updateDynamic("-webkit-flex-wrap")(`-webkit-flex-wrap`.asInstanceOf[js.Any])
    if (`-webkit-font-feature-settings` != null) __obj.updateDynamic("-webkit-font-feature-settings")(`-webkit-font-feature-settings`.asInstanceOf[js.Any])
    if (`-webkit-font-kerning` != null) __obj.updateDynamic("-webkit-font-kerning")(`-webkit-font-kerning`.asInstanceOf[js.Any])
    if (`-webkit-font-variant-ligatures` != null) __obj.updateDynamic("-webkit-font-variant-ligatures")(`-webkit-font-variant-ligatures`.asInstanceOf[js.Any])
    if (`-webkit-hyphens` != null) __obj.updateDynamic("-webkit-hyphens")(`-webkit-hyphens`.asInstanceOf[js.Any])
    if (`-webkit-justify-content` != null) __obj.updateDynamic("-webkit-justify-content")(`-webkit-justify-content`.asInstanceOf[js.Any])
    if (`-webkit-line-break` != null) __obj.updateDynamic("-webkit-line-break")(`-webkit-line-break`.asInstanceOf[js.Any])
    if (`-webkit-line-clamp` != null) __obj.updateDynamic("-webkit-line-clamp")(`-webkit-line-clamp`.asInstanceOf[js.Any])
    if (`-webkit-margin-end` != null) __obj.updateDynamic("-webkit-margin-end")(`-webkit-margin-end`.asInstanceOf[js.Any])
    if (`-webkit-margin-start` != null) __obj.updateDynamic("-webkit-margin-start")(`-webkit-margin-start`.asInstanceOf[js.Any])
    if (`-webkit-mask` != null) __obj.updateDynamic("-webkit-mask")(`-webkit-mask`.asInstanceOf[js.Any])
    if (`-webkit-mask-attachment` != null) __obj.updateDynamic("-webkit-mask-attachment")(`-webkit-mask-attachment`.asInstanceOf[js.Any])
    if (`-webkit-mask-clip` != null) __obj.updateDynamic("-webkit-mask-clip")(`-webkit-mask-clip`.asInstanceOf[js.Any])
    if (`-webkit-mask-composite` != null) __obj.updateDynamic("-webkit-mask-composite")(`-webkit-mask-composite`.asInstanceOf[js.Any])
    if (`-webkit-mask-image` != null) __obj.updateDynamic("-webkit-mask-image")(`-webkit-mask-image`.asInstanceOf[js.Any])
    if (`-webkit-mask-origin` != null) __obj.updateDynamic("-webkit-mask-origin")(`-webkit-mask-origin`.asInstanceOf[js.Any])
    if (`-webkit-mask-position` != null) __obj.updateDynamic("-webkit-mask-position")(`-webkit-mask-position`.asInstanceOf[js.Any])
    if (`-webkit-mask-position-x` != null) __obj.updateDynamic("-webkit-mask-position-x")(`-webkit-mask-position-x`.asInstanceOf[js.Any])
    if (`-webkit-mask-position-y` != null) __obj.updateDynamic("-webkit-mask-position-y")(`-webkit-mask-position-y`.asInstanceOf[js.Any])
    if (`-webkit-mask-repeat` != null) __obj.updateDynamic("-webkit-mask-repeat")(`-webkit-mask-repeat`.asInstanceOf[js.Any])
    if (`-webkit-mask-repeat-x` != null) __obj.updateDynamic("-webkit-mask-repeat-x")(`-webkit-mask-repeat-x`.asInstanceOf[js.Any])
    if (`-webkit-mask-repeat-y` != null) __obj.updateDynamic("-webkit-mask-repeat-y")(`-webkit-mask-repeat-y`.asInstanceOf[js.Any])
    if (`-webkit-mask-size` != null) __obj.updateDynamic("-webkit-mask-size")(`-webkit-mask-size`.asInstanceOf[js.Any])
    if (`-webkit-max-inline-size` != null) __obj.updateDynamic("-webkit-max-inline-size")(`-webkit-max-inline-size`.asInstanceOf[js.Any])
    if (`-webkit-order` != null) __obj.updateDynamic("-webkit-order")(`-webkit-order`.asInstanceOf[js.Any])
    if (`-webkit-overflow-scrolling` != null) __obj.updateDynamic("-webkit-overflow-scrolling")(`-webkit-overflow-scrolling`.asInstanceOf[js.Any])
    if (`-webkit-padding-end` != null) __obj.updateDynamic("-webkit-padding-end")(`-webkit-padding-end`.asInstanceOf[js.Any])
    if (`-webkit-padding-start` != null) __obj.updateDynamic("-webkit-padding-start")(`-webkit-padding-start`.asInstanceOf[js.Any])
    if (`-webkit-perspective` != null) __obj.updateDynamic("-webkit-perspective")(`-webkit-perspective`.asInstanceOf[js.Any])
    if (`-webkit-perspective-origin` != null) __obj.updateDynamic("-webkit-perspective-origin")(`-webkit-perspective-origin`.asInstanceOf[js.Any])
    if (`-webkit-scroll-snap-type` != null) __obj.updateDynamic("-webkit-scroll-snap-type")(`-webkit-scroll-snap-type`.asInstanceOf[js.Any])
    if (`-webkit-shape-margin` != null) __obj.updateDynamic("-webkit-shape-margin")(`-webkit-shape-margin`.asInstanceOf[js.Any])
    if (`-webkit-tap-highlight-color` != null) __obj.updateDynamic("-webkit-tap-highlight-color")(`-webkit-tap-highlight-color`.asInstanceOf[js.Any])
    if (`-webkit-text-combine` != null) __obj.updateDynamic("-webkit-text-combine")(`-webkit-text-combine`.asInstanceOf[js.Any])
    if (`-webkit-text-decoration-color` != null) __obj.updateDynamic("-webkit-text-decoration-color")(`-webkit-text-decoration-color`.asInstanceOf[js.Any])
    if (`-webkit-text-decoration-line` != null) __obj.updateDynamic("-webkit-text-decoration-line")(`-webkit-text-decoration-line`.asInstanceOf[js.Any])
    if (`-webkit-text-decoration-skip` != null) __obj.updateDynamic("-webkit-text-decoration-skip")(`-webkit-text-decoration-skip`.asInstanceOf[js.Any])
    if (`-webkit-text-decoration-style` != null) __obj.updateDynamic("-webkit-text-decoration-style")(`-webkit-text-decoration-style`.asInstanceOf[js.Any])
    if (`-webkit-text-emphasis` != null) __obj.updateDynamic("-webkit-text-emphasis")(`-webkit-text-emphasis`.asInstanceOf[js.Any])
    if (`-webkit-text-emphasis-color` != null) __obj.updateDynamic("-webkit-text-emphasis-color")(`-webkit-text-emphasis-color`.asInstanceOf[js.Any])
    if (`-webkit-text-emphasis-position` != null) __obj.updateDynamic("-webkit-text-emphasis-position")(`-webkit-text-emphasis-position`.asInstanceOf[js.Any])
    if (`-webkit-text-emphasis-style` != null) __obj.updateDynamic("-webkit-text-emphasis-style")(`-webkit-text-emphasis-style`.asInstanceOf[js.Any])
    if (`-webkit-text-fill-color` != null) __obj.updateDynamic("-webkit-text-fill-color")(`-webkit-text-fill-color`.asInstanceOf[js.Any])
    if (`-webkit-text-orientation` != null) __obj.updateDynamic("-webkit-text-orientation")(`-webkit-text-orientation`.asInstanceOf[js.Any])
    if (`-webkit-text-size-adjust` != null) __obj.updateDynamic("-webkit-text-size-adjust")(`-webkit-text-size-adjust`.asInstanceOf[js.Any])
    if (`-webkit-text-stroke` != null) __obj.updateDynamic("-webkit-text-stroke")(`-webkit-text-stroke`.asInstanceOf[js.Any])
    if (`-webkit-text-stroke-color` != null) __obj.updateDynamic("-webkit-text-stroke-color")(`-webkit-text-stroke-color`.asInstanceOf[js.Any])
    if (`-webkit-text-stroke-width` != null) __obj.updateDynamic("-webkit-text-stroke-width")(`-webkit-text-stroke-width`.asInstanceOf[js.Any])
    if (`-webkit-touch-callout` != null) __obj.updateDynamic("-webkit-touch-callout")(`-webkit-touch-callout`.asInstanceOf[js.Any])
    if (`-webkit-transform` != null) __obj.updateDynamic("-webkit-transform")(`-webkit-transform`.asInstanceOf[js.Any])
    if (`-webkit-transform-origin` != null) __obj.updateDynamic("-webkit-transform-origin")(`-webkit-transform-origin`.asInstanceOf[js.Any])
    if (`-webkit-transform-style` != null) __obj.updateDynamic("-webkit-transform-style")(`-webkit-transform-style`.asInstanceOf[js.Any])
    if (`-webkit-transition` != null) __obj.updateDynamic("-webkit-transition")(`-webkit-transition`.asInstanceOf[js.Any])
    if (`-webkit-transition-delay` != null) __obj.updateDynamic("-webkit-transition-delay")(`-webkit-transition-delay`.asInstanceOf[js.Any])
    if (`-webkit-transition-duration` != null) __obj.updateDynamic("-webkit-transition-duration")(`-webkit-transition-duration`.asInstanceOf[js.Any])
    if (`-webkit-transition-property` != null) __obj.updateDynamic("-webkit-transition-property")(`-webkit-transition-property`.asInstanceOf[js.Any])
    if (`-webkit-transition-timing-function` != null) __obj.updateDynamic("-webkit-transition-timing-function")(`-webkit-transition-timing-function`.asInstanceOf[js.Any])
    if (`-webkit-user-modify` != null) __obj.updateDynamic("-webkit-user-modify")(`-webkit-user-modify`.asInstanceOf[js.Any])
    if (`-webkit-user-select` != null) __obj.updateDynamic("-webkit-user-select")(`-webkit-user-select`.asInstanceOf[js.Any])
    if (`-webkit-writing-mode` != null) __obj.updateDynamic("-webkit-writing-mode")(`-webkit-writing-mode`.asInstanceOf[js.Any])
    __obj.asInstanceOf[VendorPropertiesHyphenFallback[TLength]]
  }
}

