package typings.atAwsDashSdkClientDashDynamodbDashNode.typesRestoreTableToPointInTimeExceptionsUnionMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typings.atAwsDashSdkClientDashDynamodbDashNode.typesTableAlreadyExistsExceptionMod.TableAlreadyExistsException
  - typings.atAwsDashSdkClientDashDynamodbDashNode.typesTableNotFoundExceptionMod.TableNotFoundException
  - typings.atAwsDashSdkClientDashDynamodbDashNode.typesTableInUseExceptionMod.TableInUseException
  - typings.atAwsDashSdkClientDashDynamodbDashNode.typesLimitExceededExceptionMod.LimitExceededException
  - typings.atAwsDashSdkClientDashDynamodbDashNode.typesInvalidRestoreTimeExceptionMod.InvalidRestoreTimeException
  - typings.atAwsDashSdkClientDashDynamodbDashNode.typesPointInTimeRecoveryUnavailableExceptionMod.PointInTimeRecoveryUnavailableException
  - typings.atAwsDashSdkClientDashDynamodbDashNode.typesInternalServerErrorMod.InternalServerError
*/
trait RestoreTableToPointInTimeExceptionsUnion extends js.Object

