package typings
package reactDashNativeDashElementsLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

object reactDashNativeDashElementsLibComponents {
  @scala.inline
  def AirbnbRating: reactLib.reactMod.ComponentType[reactDashNativeDashRatingsLib.reactDashNativeDashRatingsMod.AirbnbRatingProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.AirbnbRating].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashRatingsLib.reactDashNativeDashRatingsMod.AirbnbRatingProps]]
  @scala.inline
  def Avatar: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.AvatarProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.Avatar].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.AvatarProps]]
  @scala.inline
  def Badge: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.BadgeProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.Badge].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.BadgeProps]]
  @scala.inline
  def Button: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ButtonProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.Button].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ButtonProps]]
  @scala.inline
  def ButtonGroup: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ButtonGroupProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ButtonGroup].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ButtonGroupProps]]
  @scala.inline
  def Card: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.CardProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.Card].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.CardProps]]
  @scala.inline
  def CheckBox: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.CheckBoxProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.CheckBox].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.CheckBoxProps]]
  @scala.inline
  def Divider: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.DividerProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.Divider].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.DividerProps]]
  @scala.inline
  def Header: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.HeaderProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.Header].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.HeaderProps]]
  @scala.inline
  def Icon: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.IconProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.Icon].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.IconProps]]
  @scala.inline
  def Image: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ImageProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.Image].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ImageProps]]
  @scala.inline
  def Input: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.InputProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.Input].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.InputProps]]
  @scala.inline
  def ListItem: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ListItemProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ListItem].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ListItemProps]]
  @scala.inline
  def Overlay: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.OverlayProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.Overlay].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.OverlayProps]]
  @scala.inline
  def PricingCard: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.PricingCardProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.PricingCard].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.PricingCardProps]]
  @scala.inline
  def Rating: reactLib.reactMod.ComponentType[reactDashNativeDashRatingsLib.reactDashNativeDashRatingsMod.RatingProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.Rating].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashRatingsLib.reactDashNativeDashRatingsMod.RatingProps]]
  @scala.inline
  def SearchBar: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.SearchBarProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.SearchBar].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.SearchBarProps]]
  @scala.inline
  def Slider: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.SliderProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.Slider].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.SliderProps]]
  @scala.inline
  def SocialIcon: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.SocialIconProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.SocialIcon].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.SocialIconProps]]
  @scala.inline
  def Text: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.TextProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.Text].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.TextProps]]
  @scala.inline
  def ThemeConsumer[T]: reactLib.reactMod.ComponentType[
    reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ThemeConsumerProps[T]
  ] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ThemeConsumer[T]].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ThemeConsumerProps[T]]]
  @scala.inline
  def ThemeProvider[T]: reactLib.reactMod.ComponentType[
    reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ThemeProviderProps[T]
  ] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ThemeProvider[T]].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ThemeProviderProps[T]]]
  @scala.inline
  def Tile: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.TileProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.Tile].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.TileProps]]
  @scala.inline
  def Tooltip: reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.TooltipProps] = js.constructorOf[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.Tooltip].asInstanceOf[reactLib.reactMod.ComponentType[reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.TooltipProps]]
  @scala.inline
  def AirbnbRatingProps: reactDashNativeDashRatingsLib.reactDashNativeDashRatingsMod.AirbnbRatingProps.type = reactDashNativeDashRatingsLib.reactDashNativeDashRatingsMod.AirbnbRatingProps
  type AirbnbRatingProps = reactDashNativeDashRatingsLib.reactDashNativeDashRatingsMod.AirbnbRatingProps
  @scala.inline
  def AvatarProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.AvatarProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.AvatarProps
  type AvatarProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.AvatarProps
  @scala.inline
  def BadgeProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.BadgeProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.BadgeProps
  type BadgeProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.BadgeProps
  @scala.inline
  def ButtonGroupProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ButtonGroupProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ButtonGroupProps
  type ButtonGroupProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ButtonGroupProps
  @scala.inline
  def ButtonProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ButtonProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ButtonProps
  type ButtonProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ButtonProps
  @scala.inline
  def CardProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.CardProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.CardProps
  type CardProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.CardProps
  @scala.inline
  def CheckBoxProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.CheckBoxProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.CheckBoxProps
  type CheckBoxProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.CheckBoxProps
  type DividerProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.DividerProps
  @scala.inline
  def HeaderProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.HeaderProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.HeaderProps
  type HeaderProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.HeaderProps
  @scala.inline
  def IconProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.IconProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.IconProps
  type IconProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.IconProps
  @scala.inline
  def ImageProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ImageProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ImageProps
  type ImageProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ImageProps
  @scala.inline
  def InputProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.InputProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.InputProps
  type InputProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.InputProps
  @scala.inline
  def ListItemProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ListItemProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ListItemProps
  type ListItemProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ListItemProps
  @scala.inline
  def OverlayProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.OverlayProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.OverlayProps
  type OverlayProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.OverlayProps
  @scala.inline
  def PricingCardProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.PricingCardProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.PricingCardProps
  type PricingCardProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.PricingCardProps
  @scala.inline
  def RatingProps: reactDashNativeDashRatingsLib.reactDashNativeDashRatingsMod.RatingProps.type = reactDashNativeDashRatingsLib.reactDashNativeDashRatingsMod.RatingProps
  type RatingProps = reactDashNativeDashRatingsLib.reactDashNativeDashRatingsMod.RatingProps
  type SearchBarProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.SearchBarProps
  @scala.inline
  def SliderProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.SliderProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.SliderProps
  type SliderProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.SliderProps
  @scala.inline
  def SocialIconProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.SocialIconProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.SocialIconProps
  type SocialIconProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.SocialIconProps
  @scala.inline
  def TextProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.TextProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.TextProps
  type TextProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.TextProps
  @scala.inline
  def ThemeConsumerProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ThemeConsumerProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ThemeConsumerProps
  type ThemeConsumerProps[T] = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ThemeConsumerProps[T]
  @scala.inline
  def ThemeProviderProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ThemeProviderProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ThemeProviderProps
  type ThemeProviderProps[T] = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.ThemeProviderProps[T]
  @scala.inline
  def TileProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.TileProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.TileProps
  type TileProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.TileProps
  @scala.inline
  def TooltipProps: reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.TooltipProps.type = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.TooltipProps
  type TooltipProps = reactDashNativeDashElementsLib.reactDashNativeDashElementsMod.TooltipProps
}

