package typings.atStardustDashUiReactDashComponentDashEventDashListener

import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.abort
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.animationcancel
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.animationend
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.animationiteration
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.animationstart
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.auxclick
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.blur
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.cancel
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.canplay
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.canplaythrough
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.change
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.click
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.close
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.contextmenu
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.copy
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.cuechange
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.cut
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.dblclick
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.drag
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.dragend
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.dragenter
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.dragexit
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.dragleave
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.dragover
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.dragstart
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.drop
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.durationchange
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.emptied
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.ended
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.error
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.focus
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.focusin
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.focusout
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.fullscreenchange
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.fullscreenerror
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.gotpointercapture
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.input
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.invalid
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.keydown
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.keypress
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.keyup
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.load
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.loadeddata
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.loadedmetadata
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.loadend
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.loadstart
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.lostpointercapture
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.mousedown
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.mouseenter
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.mouseleave
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.mousemove
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.mouseout
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.mouseover
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.mouseup
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.paste
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pause
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.play
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.playing
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointercancel
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointerdown
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointerenter
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointerleave
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointerlockchange
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointerlockerror
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointermove
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointerout
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointerover
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointerup
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.progress
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.ratechange
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.readystatechange
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.reset
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.resize
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.scroll
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.securitypolicyviolation
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.seeked
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.seeking
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.select
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.selectionchange
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.selectstart
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.stalled
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.submit
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.suspend
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.timeupdate
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.toggle
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.touchcancel
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.touchend
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.touchmove
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.touchstart
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.transitioncancel
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.transitionend
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.transitionrun
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.transitionstart
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.visibilitychange
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.volumechange
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.waiting
import typings.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.wheel
import typings.atStardustDashUiReactDashComponentDashEventDashListener.distEsTypesMod.EventListenerOptions
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("@stardust-ui/react-component-event-listener/dist/es/EventListener", JSImport.Namespace)
@js.native
object distEsEventListenerMod extends js.Object {
  @js.native
  object default extends js.Object {
    var displayName: String = js.native
    var propTypes: Anon_Abort | Anon_Capture = js.native
    def apply(
      props: EventListenerOptions[
          abort | animationcancel | animationend | animationiteration | animationstart | auxclick | blur | cancel | canplay | canplaythrough | change | click | close | contextmenu | copy | cuechange | cut | dblclick | drag | dragend | dragenter | dragexit | dragleave | dragover | dragstart | drop | durationchange | emptied | ended | error | focus | focusin | focusout | fullscreenchange | fullscreenerror | gotpointercapture | input | invalid | keydown | keypress | keyup | load | loadeddata | loadedmetadata | loadend | loadstart | lostpointercapture | mousedown | mouseenter | mouseleave | mousemove | mouseout | mouseover | mouseup | paste | pause | play | playing | pointercancel | pointerdown | pointerenter | pointerleave | pointerlockchange | pointerlockerror | pointermove | pointerout | pointerover | pointerup | progress | ratechange | readystatechange | reset | resize | scroll | securitypolicyviolation | seeked | seeking | select | selectionchange | selectstart | stalled | submit | suspend | timeupdate | toggle | touchcancel | touchend | touchmove | touchstart | transitioncancel | transitionend | transitionrun | transitionstart | visibilitychange | volumechange | waiting | wheel
        ]
    ): js.Any = js.native
    @js.native
    object defaultProps extends js.Object {
      var capture: Boolean = js.native
    }
    
  }
  
}

