package typings.gapiClientAndroidmanagement.gapi.client.androidmanagement

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait WebToken extends js.Object {
  /** The name of the web token, which is generated by the server during creation, in the form enterprises/{enterpriseId}/webTokens/{webTokenId}. */
  var name: js.UndefOr[String] = js.undefined
  /**
    * The URL of the parent frame hosting the iframe with the embedded UI. To prevent XSS, the iframe may not be hosted at other URLs. The URL must use the
    * https scheme.
    */
  var parentFrameUrl: js.UndefOr[String] = js.undefined
  /** Permissions the admin may exercise in the embedded UI. The admin must have all of these permissions in order to view the UI. */
  var permissions: js.UndefOr[js.Array[String]] = js.undefined
  /** The token value which is used in the hosting page to generate the iframe with the embedded UI. This is a read-only field generated by the server. */
  var value: js.UndefOr[String] = js.undefined
}

object WebToken {
  @scala.inline
  def apply(
    name: String = null,
    parentFrameUrl: String = null,
    permissions: js.Array[String] = null,
    value: String = null
  ): WebToken = {
    val __obj = js.Dynamic.literal()
    if (name != null) __obj.updateDynamic("name")(name.asInstanceOf[js.Any])
    if (parentFrameUrl != null) __obj.updateDynamic("parentFrameUrl")(parentFrameUrl.asInstanceOf[js.Any])
    if (permissions != null) __obj.updateDynamic("permissions")(permissions.asInstanceOf[js.Any])
    if (value != null) __obj.updateDynamic("value")(value.asInstanceOf[js.Any])
    __obj.asInstanceOf[WebToken]
  }
}

