package typings
package reactDashEventDashListenerLib.reactDashEventDashListenerMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait EventListenerProps extends js.Object {
  var oNmsPointerUp: js.UndefOr[js.Function1[/* ev */ stdLib.MSPointerEvent, _]] = js.undefined
  var oNmsPointerUpCapture: js.UndefOr[js.Function1[/* ev */ stdLib.MSPointerEvent, _]] = js.undefined
  var onAbort: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onAbortCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onAfterPrint: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onAfterPrintCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onBeforePrint: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onBeforePrintCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onBeforeUnload: js.UndefOr[js.Function1[/* ev */ stdLib.BeforeUnloadEvent, _]] = js.undefined
  var onBeforeUnloadCapture: js.UndefOr[js.Function1[/* ev */ stdLib.BeforeUnloadEvent, _]] = js.undefined
  var onBlur: js.UndefOr[js.Function1[/* ev */ reactLib.FocusEvent, _]] = js.undefined
  var onBlurCapture: js.UndefOr[js.Function1[/* ev */ reactLib.FocusEvent, _]] = js.undefined
  var onCanPlay: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onCanPlayCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onCanPlayThrough: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onCanPlayThroughCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onChange: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onChangeCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onClick: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onClickCapture: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onCompassNeedsCalibration: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onCompassNeedsCalibrationCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onContextMenu: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onContextMenuCapture: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onDblClick: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onDblClickCapture: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onDeviceMotion: js.UndefOr[js.Function1[/* ev */ stdLib.DeviceMotionEvent, _]] = js.undefined
  var onDeviceMotionCapture: js.UndefOr[js.Function1[/* ev */ stdLib.DeviceMotionEvent, _]] = js.undefined
  var onDeviceOrientation: js.UndefOr[js.Function1[/* ev */ stdLib.DeviceOrientationEvent, _]] = js.undefined
  var onDeviceOrientationCapture: js.UndefOr[js.Function1[/* ev */ stdLib.DeviceOrientationEvent, _]] = js.undefined
  var onDrag: js.UndefOr[js.Function1[/* ev */ reactLib.DragEvent, _]] = js.undefined
  var onDragCapture: js.UndefOr[js.Function1[/* ev */ reactLib.DragEvent, _]] = js.undefined
  var onDragEnd: js.UndefOr[js.Function1[/* ev */ reactLib.DragEvent, _]] = js.undefined
  var onDragEndCapture: js.UndefOr[js.Function1[/* ev */ reactLib.DragEvent, _]] = js.undefined
  var onDragEnter: js.UndefOr[js.Function1[/* ev */ reactLib.DragEvent, _]] = js.undefined
  var onDragEnterCapture: js.UndefOr[js.Function1[/* ev */ reactLib.DragEvent, _]] = js.undefined
  var onDragLeave: js.UndefOr[js.Function1[/* ev */ reactLib.DragEvent, _]] = js.undefined
  var onDragLeaveCapture: js.UndefOr[js.Function1[/* ev */ reactLib.DragEvent, _]] = js.undefined
  var onDragOver: js.UndefOr[js.Function1[/* ev */ reactLib.DragEvent, _]] = js.undefined
  var onDragOverCapture: js.UndefOr[js.Function1[/* ev */ reactLib.DragEvent, _]] = js.undefined
  var onDragStart: js.UndefOr[js.Function1[/* ev */ reactLib.DragEvent, _]] = js.undefined
  var onDragStartCapture: js.UndefOr[js.Function1[/* ev */ reactLib.DragEvent, _]] = js.undefined
  var onDrop: js.UndefOr[js.Function1[/* ev */ reactLib.DragEvent, _]] = js.undefined
  var onDropCapture: js.UndefOr[js.Function1[/* ev */ reactLib.DragEvent, _]] = js.undefined
  var onDurationChange: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onDurationChangeCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onEmptied: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onEmptiedCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onEnded: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onEndedCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onError: js.UndefOr[stdLib.ErrorEventHandler] = js.undefined
  var onErrorCapture: js.UndefOr[stdLib.ErrorEventHandler] = js.undefined
  var onFocus: js.UndefOr[js.Function1[/* ev */ reactLib.FocusEvent, _]] = js.undefined
  var onFocusCapture: js.UndefOr[js.Function1[/* ev */ reactLib.FocusEvent, _]] = js.undefined
  var onHashChange: js.UndefOr[js.Function1[/* ev */ stdLib.HashChangeEvent, _]] = js.undefined
  var onHashChangeCapture: js.UndefOr[js.Function1[/* ev */ stdLib.HashChangeEvent, _]] = js.undefined
  var onInput: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onInputCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onKeyDown: js.UndefOr[js.Function1[/* ev */ reactLib.KeyboardEvent, _]] = js.undefined
  var onKeyDownCapture: js.UndefOr[js.Function1[/* ev */ reactLib.KeyboardEvent, _]] = js.undefined
  var onKeyPress: js.UndefOr[js.Function1[/* ev */ reactLib.KeyboardEvent, _]] = js.undefined
  var onKeyPressCapture: js.UndefOr[js.Function1[/* ev */ reactLib.KeyboardEvent, _]] = js.undefined
  var onKeyUp: js.UndefOr[js.Function1[/* ev */ reactLib.KeyboardEvent, _]] = js.undefined
  var onKeyUpCapture: js.UndefOr[js.Function1[/* ev */ reactLib.KeyboardEvent, _]] = js.undefined
  var onLoad: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onLoadCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onLoadStart: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onLoadStartCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onLoadedData: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onLoadedDataCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onLoadedMetadata: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onLoadedMetadataCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onMessage: js.UndefOr[js.Function1[/* ev */ stdLib.MessageEvent, _]] = js.undefined
  var onMessageCapture: js.UndefOr[js.Function1[/* ev */ stdLib.MessageEvent, _]] = js.undefined
  var onMouseDown: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onMouseDownCapture: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onMouseEnter: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onMouseEnterCapture: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onMouseLeave: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onMouseLeaveCapture: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onMouseMove: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onMouseMoveCapture: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onMouseOut: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onMouseOutCapture: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onMouseOver: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onMouseOverCapture: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onMouseUp: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onMouseUpCapture: js.UndefOr[js.Function1[/* ev */ reactLib.MouseEvent, _]] = js.undefined
  var onMouseWheel: js.UndefOr[js.Function1[/* ev */ reactLib.WheelEvent, _]] = js.undefined
  var onMouseWheelCapture: js.UndefOr[js.Function1[/* ev */ reactLib.WheelEvent, _]] = js.undefined
  var onMsGestureChange: js.UndefOr[js.Function1[/* ev */ stdLib.MSGestureEvent, _]] = js.undefined
  var onMsGestureChangeCapture: js.UndefOr[js.Function1[/* ev */ stdLib.MSGestureEvent, _]] = js.undefined
  var onMsGestureDoubleTap: js.UndefOr[js.Function1[/* ev */ stdLib.MSGestureEvent, _]] = js.undefined
  var onMsGestureDoubleTapCapture: js.UndefOr[js.Function1[/* ev */ stdLib.MSGestureEvent, _]] = js.undefined
  var onMsGestureEnd: js.UndefOr[js.Function1[/* ev */ stdLib.MSGestureEvent, _]] = js.undefined
  var onMsGestureEndCapture: js.UndefOr[js.Function1[/* ev */ stdLib.MSGestureEvent, _]] = js.undefined
  var onMsGestureHold: js.UndefOr[js.Function1[/* ev */ stdLib.MSGestureEvent, _]] = js.undefined
  var onMsGestureHoldCapture: js.UndefOr[js.Function1[/* ev */ stdLib.MSGestureEvent, _]] = js.undefined
  var onMsGestureStart: js.UndefOr[js.Function1[/* ev */ stdLib.MSGestureEvent, _]] = js.undefined
  var onMsGestureStartCapture: js.UndefOr[js.Function1[/* ev */ stdLib.MSGestureEvent, _]] = js.undefined
  var onMsGestureTap: js.UndefOr[js.Function1[/* ev */ stdLib.MSGestureEvent, _]] = js.undefined
  var onMsGestureTapCapture: js.UndefOr[js.Function1[/* ev */ stdLib.MSGestureEvent, _]] = js.undefined
  var onMsInertiaStart: js.UndefOr[js.Function1[/* ev */ stdLib.MSGestureEvent, _]] = js.undefined
  var onMsInertiaStartCapture: js.UndefOr[js.Function1[/* ev */ stdLib.MSGestureEvent, _]] = js.undefined
  var onMsPointerCancel: js.UndefOr[js.Function1[/* ev */ stdLib.MSPointerEvent, _]] = js.undefined
  var onMsPointerCancelCapture: js.UndefOr[js.Function1[/* ev */ stdLib.MSPointerEvent, _]] = js.undefined
  var onMsPointerDown: js.UndefOr[js.Function1[/* ev */ stdLib.MSPointerEvent, _]] = js.undefined
  var onMsPointerDownCapture: js.UndefOr[js.Function1[/* ev */ stdLib.MSPointerEvent, _]] = js.undefined
  var onMsPointerEnter: js.UndefOr[js.Function1[/* ev */ stdLib.MSPointerEvent, _]] = js.undefined
  var onMsPointerEnterCapture: js.UndefOr[js.Function1[/* ev */ stdLib.MSPointerEvent, _]] = js.undefined
  var onMsPointerLeave: js.UndefOr[js.Function1[/* ev */ stdLib.MSPointerEvent, _]] = js.undefined
  var onMsPointerLeaveCapture: js.UndefOr[js.Function1[/* ev */ stdLib.MSPointerEvent, _]] = js.undefined
  var onMsPointerMove: js.UndefOr[js.Function1[/* ev */ stdLib.MSPointerEvent, _]] = js.undefined
  var onMsPointerMoveCapture: js.UndefOr[js.Function1[/* ev */ stdLib.MSPointerEvent, _]] = js.undefined
  var onMsPointerOut: js.UndefOr[js.Function1[/* ev */ stdLib.MSPointerEvent, _]] = js.undefined
  var onMsPointerOutCapture: js.UndefOr[js.Function1[/* ev */ stdLib.MSPointerEvent, _]] = js.undefined
  var onMsPointerOver: js.UndefOr[js.Function1[/* ev */ stdLib.MSPointerEvent, _]] = js.undefined
  var onMsPointerOverCapture: js.UndefOr[js.Function1[/* ev */ stdLib.MSPointerEvent, _]] = js.undefined
  var onOffline: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onOfflineCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onOnline: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onOnlineCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onOrientationChange: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onOrientationChangeCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onPageHide: js.UndefOr[js.Function1[/* ev */ stdLib.PageTransitionEvent, _]] = js.undefined
  var onPageHideCapture: js.UndefOr[js.Function1[/* ev */ stdLib.PageTransitionEvent, _]] = js.undefined
  var onPageShow: js.UndefOr[js.Function1[/* ev */ stdLib.PageTransitionEvent, _]] = js.undefined
  var onPageShowCapture: js.UndefOr[js.Function1[/* ev */ stdLib.PageTransitionEvent, _]] = js.undefined
  var onPause: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onPauseCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onPlay: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onPlayCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onPlaying: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onPlayingCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  // Global events
  var onPointerCancel: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onPointerCancelCapture: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onPointerDown: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onPointerDownCapture: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onPointerEnter: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onPointerEnterCapture: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onPointerLeave: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onPointerLeaveCapture: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onPointerMove: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onPointerMoveCapture: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onPointerOut: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onPointerOutCapture: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onPointerOver: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onPointerOverCapture: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onPointerUp: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onPointerUpCapture: js.UndefOr[js.Function1[/* ev */ reactLib.PointerEvent, _]] = js.undefined
  var onPopState: js.UndefOr[js.Function1[/* ev */ stdLib.PopStateEvent, _]] = js.undefined
  var onPopStateCapture: js.UndefOr[js.Function1[/* ev */ stdLib.PopStateEvent, _]] = js.undefined
  var onProgress: js.UndefOr[js.Function1[/* ev */ stdLib.ProgressEvent, _]] = js.undefined
  var onProgressCapture: js.UndefOr[js.Function1[/* ev */ stdLib.ProgressEvent, _]] = js.undefined
  var onRateChange: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onRateChangeCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onReadyStateChange: js.UndefOr[js.Function1[/* ev */ stdLib.ProgressEvent, _]] = js.undefined
  var onReadyStateChangeCapture: js.UndefOr[js.Function1[/* ev */ stdLib.ProgressEvent, _]] = js.undefined
  var onReset: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onResetCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onResize: js.UndefOr[js.Function1[/* ev */ reactLib.UIEvent, _]] = js.undefined
  var onResizeCapture: js.UndefOr[js.Function1[/* ev */ reactLib.UIEvent, _]] = js.undefined
  var onScroll: js.UndefOr[js.Function1[/* ev */ reactLib.UIEvent, _]] = js.undefined
  var onScrollCapture: js.UndefOr[js.Function1[/* ev */ reactLib.UIEvent, _]] = js.undefined
  var onSeeked: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onSeekedCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onSeeking: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onSeekingCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onSelect: js.UndefOr[js.Function1[/* ev */ reactLib.UIEvent, _]] = js.undefined
  var onSelectCapture: js.UndefOr[js.Function1[/* ev */ reactLib.UIEvent, _]] = js.undefined
  var onSelectionChange: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onSelectionChangeCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onStalled: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onStalledCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onStorage: js.UndefOr[js.Function1[/* ev */ stdLib.StorageEvent, _]] = js.undefined
  var onStorageCapture: js.UndefOr[js.Function1[/* ev */ stdLib.StorageEvent, _]] = js.undefined
  var onSubmit: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onSubmitCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onSuspend: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onSuspendCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onTimeUpdate: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onTimeUpdateCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onTouchCancel: js.UndefOr[js.Any] = js.undefined
  var onTouchCancelCapture: js.UndefOr[js.Any] = js.undefined
  var onTouchEnd: js.UndefOr[js.Any] = js.undefined
  var onTouchEndCapture: js.UndefOr[js.Any] = js.undefined
  var onTouchMove: js.UndefOr[js.Any] = js.undefined
  var onTouchMoveCapture: js.UndefOr[js.Any] = js.undefined
  var onTouchStart: js.UndefOr[js.Any] = js.undefined
  var onTouchStartCapture: js.UndefOr[js.Any] = js.undefined
  var onUnload: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onUnloadCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onVolumeChange: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onVolumeChangeCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onWaiting: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onWaitingCapture: js.UndefOr[js.Function1[/* ev */ reactLib.Event, _]] = js.undefined
  var onWheel: js.UndefOr[js.Function1[/* ev */ reactLib.WheelEvent, _]] = js.undefined
  var onWheelCapture: js.UndefOr[js.Function1[/* ev */ reactLib.WheelEvent, _]] = js.undefined
  /**
    * Target (window or document)
    */
  var target: stdLib.Window | reactLib.Document | java.lang.String
}

