package typings
package activexDashPowerpointLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait EnumeratorConstructor
  extends org.scalablytyped.runtime.Instantiable1[
      (/* col */ activexDashPowerpointLib.PowerPointNs.ActionSettings) | (/* col */ activexDashPowerpointLib.PowerPointNs.AddIns) | (/* col */ activexDashPowerpointLib.PowerPointNs.AnimationBehaviors) | (/* col */ activexDashPowerpointLib.PowerPointNs.AnimationPoints) | (/* col */ activexDashPowerpointLib.PowerPointNs.Borders) | (/* col */ activexDashPowerpointLib.PowerPointNs.CanvasShapes) | (/* col */ activexDashPowerpointLib.PowerPointNs.CellRange) | (/* col */ activexDashPowerpointLib.PowerPointNs.ColorSchemes) | (/* col */ activexDashPowerpointLib.PowerPointNs.Columns) | (/* col */ activexDashPowerpointLib.PowerPointNs.Comments) | (/* col */ activexDashPowerpointLib.PowerPointNs.CustomLayouts) | (/* col */ activexDashPowerpointLib.PowerPointNs.CustomerData) | (/* col */ activexDashPowerpointLib.PowerPointNs.Designs) | (/* col */ activexDashPowerpointLib.PowerPointNs.DiagramNodeChildren) | (/* col */ activexDashPowerpointLib.PowerPointNs.DiagramNodes) | (/* col */ activexDashPowerpointLib.PowerPointNs.DocumentWindows) | (/* col */ activexDashPowerpointLib.PowerPointNs.ExtraColors) | (/* col */ activexDashPowerpointLib.PowerPointNs.FileConverters) | (/* col */ activexDashPowerpointLib.PowerPointNs.Fonts) | (/* col */ activexDashPowerpointLib.PowerPointNs.GroupShapes) | (/* col */ activexDashPowerpointLib.PowerPointNs.Hyperlinks) | (/* col */ activexDashPowerpointLib.PowerPointNs.MediaBookmarks) | (/* col */ activexDashPowerpointLib.PowerPointNs.NamedSlideShows) | (/* col */ activexDashPowerpointLib.PowerPointNs.ObjectVerbs) | (/* col */ activexDashPowerpointLib.PowerPointNs.Panes) | (/* col */ activexDashPowerpointLib.PowerPointNs.Placeholders) | (/* col */ activexDashPowerpointLib.PowerPointNs.Presentations) | (/* col */ activexDashPowerpointLib.PowerPointNs.PrintRanges) | (/* col */ activexDashPowerpointLib.PowerPointNs.ProtectedViewWindows) | (/* col */ activexDashPowerpointLib.PowerPointNs.PublishObjects) | (/* col */ activexDashPowerpointLib.PowerPointNs.ResampleMediaTasks) | (/* col */ activexDashPowerpointLib.PowerPointNs.Rows) | (/* col */ activexDashPowerpointLib.PowerPointNs.RulerLevels) | (/* col */ activexDashPowerpointLib.PowerPointNs.Sequence) | (/* col */ activexDashPowerpointLib.PowerPointNs.Sequences) | (/* col */ activexDashPowerpointLib.PowerPointNs.ShapeNodes) | (/* col */ activexDashPowerpointLib.PowerPointNs.ShapeRange) | (/* col */ activexDashPowerpointLib.PowerPointNs.Shapes) | (/* col */ activexDashPowerpointLib.PowerPointNs.SlideRange) | (/* col */ activexDashPowerpointLib.PowerPointNs.SlideShowWindows) | (/* col */ activexDashPowerpointLib.PowerPointNs.Slides) | (/* col */ activexDashPowerpointLib.PowerPointNs.TabStops) | (/* col */ activexDashPowerpointLib.PowerPointNs.Tags) | (/* col */ activexDashPowerpointLib.PowerPointNs.TextStyleLevels) | (/* col */ activexDashPowerpointLib.PowerPointNs.TextStyles), 
      stdLib.Enumerator[
        activexDashPowerpointLib.PowerPointNs.ActionSetting | activexDashPowerpointLib.PowerPointNs.AddIn | activexDashPowerpointLib.PowerPointNs.AnimationBehavior | activexDashPowerpointLib.PowerPointNs.AnimationPoint | activexDashPowerpointLib.PowerPointNs.Cell | activexDashPowerpointLib.PowerPointNs.ColorScheme | activexDashPowerpointLib.PowerPointNs.Column | activexDashPowerpointLib.PowerPointNs.Comment | activexDashPowerpointLib.PowerPointNs.CustomLayout | activexDashOfficeLib.OfficeNs.CustomXMLPart | activexDashPowerpointLib.PowerPointNs.Design | activexDashPowerpointLib.PowerPointNs.DiagramNode | activexDashPowerpointLib.PowerPointNs.DocumentWindow | activexDashPowerpointLib.PowerPointNs.Effect | activexDashPowerpointLib.PowerPointNs.FileConverter | activexDashPowerpointLib.PowerPointNs.Font | activexDashPowerpointLib.PowerPointNs.Hyperlink | activexDashPowerpointLib.PowerPointNs.LineFormat | activexDashPowerpointLib.PowerPointNs.MediaBookmark | activexDashOfficeLib.OfficeNs.MsoRGBType | activexDashPowerpointLib.PowerPointNs.NamedSlideShow | activexDashPowerpointLib.PowerPointNs.Pane | activexDashPowerpointLib.PowerPointNs.Presentation | activexDashPowerpointLib.PowerPointNs.PrintRange | activexDashPowerpointLib.PowerPointNs.ProtectedViewWindow | activexDashPowerpointLib.PowerPointNs.PublishObject | activexDashPowerpointLib.PowerPointNs.ResampleMediaTask | activexDashPowerpointLib.PowerPointNs.Row | activexDashPowerpointLib.PowerPointNs.RulerLevel | activexDashPowerpointLib.PowerPointNs.Sequence | activexDashPowerpointLib.PowerPointNs.Shape | activexDashPowerpointLib.PowerPointNs.ShapeNode | activexDashPowerpointLib.PowerPointNs.Slide | activexDashPowerpointLib.PowerPointNs.SlideShowWindow | java.lang.String | activexDashPowerpointLib.PowerPointNs.TabStop | activexDashPowerpointLib.PowerPointNs.TextStyle | activexDashPowerpointLib.PowerPointNs.TextStyleLevel
      ]
    ]

