package typings
package cryptoDashJsLib.cryptoDashJsMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait Hashes extends js.Object {
  var AES: CipherHelper = js.native
  var DES: CipherHelper = js.native
  var EvpKDF: CipherHelper = js.native
  var RC4: CipherHelper = js.native
  var RC4Drop: CipherHelper = js.native
  var Rabbit: CipherHelper = js.native
  var RabbitLegacy: CipherHelper = js.native
  var TripleDES: CipherHelper = js.native
  var algo: cryptoDashJsLib.Anon_AES = js.native
  var enc: cryptoDashJsLib.Anon_Base64 = js.native
  var format: cryptoDashJsLib.Anon_Hex = js.native
  var lib: cryptoDashJsLib.Anon_WordArray = js.native
  var mode: cryptoDashJsLib.Anon_CBC = js.native
  var pad: cryptoDashJsLib.Anon_AnsiX923 = js.native
  def HmacMD5(message: LibWordArray): WordArray = js.native
  def HmacMD5(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def HmacMD5(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacMD5(message: LibWordArray, options: js.Any*): WordArray = js.native
  def HmacMD5(message: java.lang.String): WordArray = js.native
  def HmacMD5(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def HmacMD5(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacMD5(message: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacRIPEMD160(message: LibWordArray): WordArray = js.native
  def HmacRIPEMD160(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def HmacRIPEMD160(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacRIPEMD160(message: LibWordArray, options: js.Any*): WordArray = js.native
  def HmacRIPEMD160(message: java.lang.String): WordArray = js.native
  def HmacRIPEMD160(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def HmacRIPEMD160(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacRIPEMD160(message: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA1(message: LibWordArray): WordArray = js.native
  def HmacSHA1(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def HmacSHA1(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA1(message: LibWordArray, options: js.Any*): WordArray = js.native
  def HmacSHA1(message: java.lang.String): WordArray = js.native
  def HmacSHA1(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def HmacSHA1(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA1(message: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA224(message: LibWordArray): WordArray = js.native
  def HmacSHA224(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def HmacSHA224(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA224(message: LibWordArray, options: js.Any*): WordArray = js.native
  def HmacSHA224(message: java.lang.String): WordArray = js.native
  def HmacSHA224(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def HmacSHA224(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA224(message: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA256(message: LibWordArray): WordArray = js.native
  def HmacSHA256(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def HmacSHA256(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA256(message: LibWordArray, options: js.Any*): WordArray = js.native
  def HmacSHA256(message: java.lang.String): WordArray = js.native
  def HmacSHA256(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def HmacSHA256(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA256(message: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA3(message: LibWordArray): WordArray = js.native
  def HmacSHA3(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def HmacSHA3(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA3(message: LibWordArray, options: js.Any*): WordArray = js.native
  def HmacSHA3(message: java.lang.String): WordArray = js.native
  def HmacSHA3(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def HmacSHA3(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA3(message: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA384(message: LibWordArray): WordArray = js.native
  def HmacSHA384(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def HmacSHA384(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA384(message: LibWordArray, options: js.Any*): WordArray = js.native
  def HmacSHA384(message: java.lang.String): WordArray = js.native
  def HmacSHA384(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def HmacSHA384(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA384(message: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA512(message: LibWordArray): WordArray = js.native
  def HmacSHA512(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def HmacSHA512(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA512(message: LibWordArray, options: js.Any*): WordArray = js.native
  def HmacSHA512(message: java.lang.String): WordArray = js.native
  def HmacSHA512(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def HmacSHA512(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def HmacSHA512(message: java.lang.String, options: js.Any*): WordArray = js.native
  def MD5(message: LibWordArray): WordArray = js.native
  def MD5(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def MD5(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def MD5(message: LibWordArray, options: js.Any*): WordArray = js.native
  def MD5(message: java.lang.String): WordArray = js.native
  def MD5(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def MD5(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def MD5(message: java.lang.String, options: js.Any*): WordArray = js.native
  def PBKDF2(message: LibWordArray): WordArray = js.native
  def PBKDF2(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def PBKDF2(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def PBKDF2(message: LibWordArray, options: js.Any*): WordArray = js.native
  def PBKDF2(message: java.lang.String): WordArray = js.native
  def PBKDF2(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def PBKDF2(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def PBKDF2(message: java.lang.String, options: js.Any*): WordArray = js.native
  def RIPEMD160(message: LibWordArray): WordArray = js.native
  def RIPEMD160(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def RIPEMD160(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def RIPEMD160(message: LibWordArray, options: js.Any*): WordArray = js.native
  def RIPEMD160(message: java.lang.String): WordArray = js.native
  def RIPEMD160(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def RIPEMD160(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def RIPEMD160(message: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA1(message: LibWordArray): WordArray = js.native
  def SHA1(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def SHA1(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA1(message: LibWordArray, options: js.Any*): WordArray = js.native
  def SHA1(message: java.lang.String): WordArray = js.native
  def SHA1(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def SHA1(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA1(message: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA224(message: LibWordArray): WordArray = js.native
  def SHA224(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def SHA224(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA224(message: LibWordArray, options: js.Any*): WordArray = js.native
  def SHA224(message: java.lang.String): WordArray = js.native
  def SHA224(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def SHA224(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA224(message: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA256(message: LibWordArray): WordArray = js.native
  def SHA256(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def SHA256(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA256(message: LibWordArray, options: js.Any*): WordArray = js.native
  def SHA256(message: java.lang.String): WordArray = js.native
  def SHA256(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def SHA256(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA256(message: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA3(message: LibWordArray): WordArray = js.native
  def SHA3(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def SHA3(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA3(message: LibWordArray, options: js.Any*): WordArray = js.native
  def SHA3(message: java.lang.String): WordArray = js.native
  def SHA3(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def SHA3(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA3(message: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA384(message: LibWordArray): WordArray = js.native
  def SHA384(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def SHA384(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA384(message: LibWordArray, options: js.Any*): WordArray = js.native
  def SHA384(message: java.lang.String): WordArray = js.native
  def SHA384(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def SHA384(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA384(message: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA512(message: LibWordArray): WordArray = js.native
  def SHA512(message: LibWordArray, key: WordArray, options: js.Any*): WordArray = js.native
  def SHA512(message: LibWordArray, key: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA512(message: LibWordArray, options: js.Any*): WordArray = js.native
  def SHA512(message: java.lang.String): WordArray = js.native
  def SHA512(message: java.lang.String, key: WordArray, options: js.Any*): WordArray = js.native
  def SHA512(message: java.lang.String, key: java.lang.String, options: js.Any*): WordArray = js.native
  def SHA512(message: java.lang.String, options: js.Any*): WordArray = js.native
}

