package typings
package googleDashAdwordsDashScriptsLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - googleDashAdwordsDashScriptsLib.googleDashAdwordsDashScriptsLibStrings.LESS_THAN_FIVE_HUNDRED
  - googleDashAdwordsDashScriptsLib.googleDashAdwordsDashScriptsLibStrings.LESS_THAN_ONE_THOUSAND
  - googleDashAdwordsDashScriptsLib.googleDashAdwordsDashScriptsLibStrings.ONE_THOUSAND_TO_TEN_THOUSAND
  - googleDashAdwordsDashScriptsLib.googleDashAdwordsDashScriptsLibStrings.TEN_THOUSAND_TO_FIFTY_THOUSAND
  - googleDashAdwordsDashScriptsLib.googleDashAdwordsDashScriptsLibStrings.FIFTY_THOUSAND_TO_ONE_HUNDRED_THOUSAND
  - googleDashAdwordsDashScriptsLib.googleDashAdwordsDashScriptsLibStrings.ONE_HUNDRED_THOUSAND_TO_THREE_HUNDRED_THOUSAND
  - googleDashAdwordsDashScriptsLib.googleDashAdwordsDashScriptsLibStrings.THREE_HUNDRED_THOUSAND_TO_FIVE_HUNDRED_THOUSAND
  - googleDashAdwordsDashScriptsLib.googleDashAdwordsDashScriptsLibStrings.FIVE_HUNDRED_THOUSAND_TO_ONE_MILLION
  - googleDashAdwordsDashScriptsLib.googleDashAdwordsDashScriptsLibStrings.ONE_MILLION_TO_TWO_MILLION
  - googleDashAdwordsDashScriptsLib.googleDashAdwordsDashScriptsLibStrings.TWO_MILLION_TO_THREE_MILLION
  - googleDashAdwordsDashScriptsLib.googleDashAdwordsDashScriptsLibStrings.THREE_MILLION_TO_FIVE_MILLION
  - googleDashAdwordsDashScriptsLib.googleDashAdwordsDashScriptsLibStrings.FIVE_MILLION_TO_TEN_MILLION
  - googleDashAdwordsDashScriptsLib.googleDashAdwordsDashScriptsLibStrings.TEN_MILLION_TO_TWENTY_MILLION
  - googleDashAdwordsDashScriptsLib.googleDashAdwordsDashScriptsLibStrings.TWENTY_MILLION_TO_THIRTY_MILLION
  - googleDashAdwordsDashScriptsLib.googleDashAdwordsDashScriptsLibStrings.THIRTY_MILLION_TO_FIFTY_MILLION
  - googleDashAdwordsDashScriptsLib.googleDashAdwordsDashScriptsLibStrings.OVER_FIFTY_MILLION
*/
trait UserListSizeRange extends js.Object

