package typings.reactDashNativeDashChartsDashWrapper

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait reactDashNativeDashChartsDashWrapperProps {
  @scala.inline
  def BarChartProps: typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.BarChartProps.type = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.BarChartProps
  type BarChartProps = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.BarChartProps
  @scala.inline
  def BubbleChartProps: typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.BubbleChartProps.type = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.BubbleChartProps
  type BubbleChartProps = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.BubbleChartProps
  @scala.inline
  def CandleStickChartProps: typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.CandleStickChartProps.type = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.CandleStickChartProps
  type CandleStickChartProps = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.CandleStickChartProps
  @scala.inline
  def CombinedChartProps: typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.CombinedChartProps.type = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.CombinedChartProps
  type CombinedChartProps = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.CombinedChartProps
  @scala.inline
  def HorizontalBarChartProps: typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.BarChartProps.type = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.BarChartProps
  type HorizontalBarChartProps = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.BarChartProps
  @scala.inline
  def LineChartProps: typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.LineChartProps.type = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.LineChartProps
  type LineChartProps = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.LineChartProps
  @scala.inline
  def PieChartProps: typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.PieChartProps.type = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.PieChartProps
  type PieChartProps = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.PieChartProps
  @scala.inline
  def RadarChartProps: typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.RadarChartProps.type = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.RadarChartProps
  type RadarChartProps = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.RadarChartProps
  @scala.inline
  def ScatterChartProps: typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.ScatterChartProps.type = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.ScatterChartProps
  type ScatterChartProps = typings.reactDashNativeDashChartsDashWrapper.reactDashNativeDashChartsDashWrapperMod.ScatterChartProps
}

