package typings
package atIonicCoreLib.distTypesComponentsMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object LocalJSXNs {
  type IonActionSheetController = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonActionSheetControllerElement]
  type IonAlertController = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonAlertControllerElement]
  type IonApp = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonAppElement]
  type IonAvatar = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonAvatarElement]
  type IonButtons = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonButtonsElement]
  type IonItemGroup = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonItemGroupElement]
  type IonLoadingController = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonLoadingControllerElement]
  type IonMenuController = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonMenuControllerElement]
  type IonModalController = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonModalControllerElement]
  type IonNavPop = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonNavPopElement]
  type IonPickerController = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonPickerControllerElement]
  type IonPopoverController = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonPopoverControllerElement]
  type IonReorder = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonReorderElement]
  type IonRow = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonRowElement]
  type IonSlide = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonSlideElement]
  type IonThumbnail = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonThumbnailElement]
  type IonToastController = atIonicCoreLib.distTypesStencilDotCoreMod.JSXBaseNs.HTMLAttributes[atIonicCoreLib.distTypesComponentsMod.Global.HTMLIonToastControllerElement]
}
