package typings
package blessedLib.blessedMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("blessed", "BlessedProgram")
@js.native
class BlessedProgram ()
  extends nodeLib.eventsMod.EventEmitter {
  def this(options: IBlessedProgramOptions) = this()
  var cols: scala.Double = js.native
  var input: nodeLib.streamMod.Readable = js.native
  var isLXDE: scala.Boolean = js.native
  var isOSXTerm: scala.Boolean = js.native
  var isRxvt: scala.Boolean = js.native
  var isTerminator: scala.Boolean = js.native
  var isVTE: scala.Boolean = js.native
  var isXFCE: scala.Boolean = js.native
  var isXterm: scala.Boolean = js.native
  var isiTerm2: scala.Boolean = js.native
  var options: IBlessedProgramOptions = js.native
  var output: nodeLib.streamMod.Writable = js.native
  var rows: scala.Double = js.native
  var savedX: scala.Double = js.native
  var savedY: scala.Double = js.native
  var scrollBottom: scala.Double = js.native
  var scrollTop: scala.Double = js.native
  var tmux: scala.Boolean = js.native
  var tmuxVersion: scala.Double = js.native
  var `type`: java.lang.String = js.native
  var useBuffer: scala.Boolean = js.native
  var x: scala.Double = js.native
  var y: scala.Double = js.native
  var zero: scala.Boolean = js.native
  def HPositionRelative(): scala.Boolean = js.native
  def HPositionRelative(param: scala.Double): scala.Boolean = js.native
  def HVPosition(): scala.Boolean = js.native
  def HVPosition(row: scala.Double): scala.Boolean = js.native
  def HVPosition(row: scala.Double, col: scala.Double): scala.Boolean = js.native
  def VPositionRelative(): scala.Boolean = js.native
  def VPositionRelative(param: scala.Double): scala.Boolean = js.native
  def ae(): scala.Boolean = js.native
  def alternate(): scala.Boolean = js.native
  def alternateBuffer(): scala.Boolean = js.native
  def as(): scala.Boolean = js.native
  def back(): scala.Boolean = js.native
  def back(param: scala.Double): scala.Boolean = js.native
  def backspace(): scala.Boolean = js.native
  def bel(): scala.Boolean = js.native
  def bell(): scala.Boolean = js.native
  def bg(color: java.lang.String): scala.Boolean = js.native
  def bg(color: java.lang.String, `val`: scala.Boolean): scala.Boolean = js.native
  def bindMouse(): scala.Unit = js.native
  def bindResponse(): scala.Unit = js.native
  def cbt(): scala.Boolean = js.native
  def cbt(param: scala.Double): scala.Boolean = js.native
  def cha(): scala.Boolean = js.native
  def cha(param: scala.Double): scala.Boolean = js.native
  def charAttributes(param: java.lang.String): scala.Boolean = js.native
  def charAttributes(param: java.lang.String, `val`: scala.Boolean): scala.Boolean = js.native
  def charAttributes(param: js.Array[java.lang.String]): scala.Boolean = js.native
  def charAttributes(param: js.Array[java.lang.String], `val`: scala.Boolean): scala.Boolean = js.native
  def charPosAbsolute(): scala.Boolean = js.native
  def charPosAbsolute(param: scala.Double): scala.Boolean = js.native
  def charset(): scala.Boolean = js.native
  def charset(`val`: java.lang.String): scala.Boolean = js.native
  def charset(`val`: java.lang.String, level: scala.Double): scala.Boolean = js.native
  def cht(): scala.Boolean = js.native
  def cht(param: scala.Double): scala.Boolean = js.native
  def civis(): scala.Boolean = js.native
  def clear(): scala.Boolean = js.native
  def cnl(): scala.Boolean = js.native
  def cnl(param: scala.Double): scala.Boolean = js.native
  def copyRectangle(args: java.lang.String*): scala.Boolean = js.native
  def copyToClipboard(text: java.lang.String): scala.Boolean = js.native
  def cpl(): scala.Boolean = js.native
  def cpl(param: scala.Double): scala.Boolean = js.native
  def cr(): scala.Boolean = js.native
  def csr(top: scala.Double, bottom: scala.Double): scala.Boolean = js.native
  def cub(): scala.Boolean = js.native
  def cub(param: scala.Double): scala.Boolean = js.native
  def cud(): scala.Boolean = js.native
  def cud(param: scala.Double): scala.Boolean = js.native
  def cuf(): scala.Boolean = js.native
  def cuf(param: scala.Double): scala.Boolean = js.native
  def cup(): scala.Boolean = js.native
  def cup(row: scala.Double): scala.Boolean = js.native
  def cup(row: scala.Double, col: scala.Double): scala.Boolean = js.native
  def cursorBackward(): scala.Boolean = js.native
  def cursorBackward(param: scala.Double): scala.Boolean = js.native
  def cursorBackwardTab(): scala.Boolean = js.native
  def cursorBackwardTab(param: scala.Double): scala.Boolean = js.native
  def cursorCharAbsolute(): scala.Boolean = js.native
  def cursorCharAbsolute(param: scala.Double): scala.Boolean = js.native
  def cursorColor(color: java.lang.String): scala.Boolean = js.native
  def cursorDown(): scala.Boolean = js.native
  def cursorDown(param: scala.Double): scala.Boolean = js.native
  def cursorForward(): scala.Boolean = js.native
  def cursorForward(param: scala.Double): scala.Boolean = js.native
  def cursorForwardTab(): scala.Boolean = js.native
  def cursorForwardTab(param: scala.Double): scala.Boolean = js.native
  def cursorNextLine(): scala.Boolean = js.native
  def cursorNextLine(param: scala.Double): scala.Boolean = js.native
  def cursorPos(): scala.Boolean = js.native
  def cursorPos(row: scala.Double): scala.Boolean = js.native
  def cursorPos(row: scala.Double, col: scala.Double): scala.Boolean = js.native
  def cursorPrecedingLine(): scala.Boolean = js.native
  def cursorPrecedingLine(param: scala.Double): scala.Boolean = js.native
  def cursorReset(): scala.Boolean = js.native
  def cursorShape(shape: java.lang.String): scala.Boolean = js.native
  def cursorShape(shape: java.lang.String, blink: scala.Boolean): scala.Boolean = js.native
  def cursorUp(): scala.Boolean = js.native
  def cursorUp(param: scala.Double): scala.Boolean = js.native
  def cursor_invisible(): scala.Boolean = js.native
  def cuu(): scala.Boolean = js.native
  def cuu(param: scala.Double): scala.Boolean = js.native
  def da(): scala.Boolean = js.native
  def da(param: scala.Double): scala.Boolean = js.native
  def da(param: scala.Double, callback: js.Function): scala.Boolean = js.native
  def dch(): scala.Boolean = js.native
  def dch(param: scala.Double): scala.Boolean = js.native
  def debug(): scala.Boolean = js.native
  def deccara(args: java.lang.String*): scala.Boolean = js.native
  def deccra(args: java.lang.String*): scala.Boolean = js.native
  def decdc(args: java.lang.String*): scala.Boolean = js.native
  def decefr(args: java.lang.String*): scala.Boolean = js.native
  def decelr(args: java.lang.String*): scala.Boolean = js.native
  def decera(args: java.lang.String*): scala.Boolean = js.native
  def decfra(args: java.lang.String*): scala.Boolean = js.native
  def decic(args: java.lang.String*): scala.Boolean = js.native
  def decll(): scala.Boolean = js.native
  def decll(param: scala.Double): scala.Boolean = js.native
  def decrara(args: java.lang.String*): scala.Boolean = js.native
  def decreqtparm(param: scala.Double): scala.Boolean = js.native
  def decrqlp(): scala.Boolean = js.native
  def decrqlp(param: java.lang.String): scala.Boolean = js.native
  def decrqlp(param: java.lang.String, callback: js.Function): scala.Boolean = js.native
  def decrqm(): scala.Boolean = js.native
  def decrqm(param: scala.Double): scala.Boolean = js.native
  def decrqmp(): scala.Boolean = js.native
  def decrqmp(param: scala.Double): scala.Boolean = js.native
  def decrst(args: java.lang.String*): scala.Boolean = js.native
  def decsace(): scala.Boolean = js.native
  def decsace(param: scala.Double): scala.Boolean = js.native
  def decsca(): scala.Boolean = js.native
  def decsca(param: scala.Double): scala.Boolean = js.native
  def decscl(args: java.lang.String*): scala.Boolean = js.native
  def decscursr(): scala.Boolean = js.native
  def decscursr(param: java.lang.String): scala.Boolean = js.native
  def decsera(args: java.lang.String*): scala.Boolean = js.native
  def decset(args: java.lang.String*): scala.Boolean = js.native
  def decsle(args: java.lang.String*): scala.Boolean = js.native
  def decstbm(top: scala.Double, bottom: scala.Double): scala.Boolean = js.native
  def decstr(): scala.Boolean = js.native
  def decswbv(): scala.Boolean = js.native
  def decswbv(param: scala.Double): scala.Boolean = js.native
  def dectcemh(): scala.Boolean = js.native
  def deleteChars(): scala.Boolean = js.native
  def deleteChars(param: scala.Double): scala.Boolean = js.native
  def deleteColumns(args: java.lang.String*): scala.Boolean = js.native
  def deleteLines(): scala.Boolean = js.native
  def deleteLines(param: scala.Double): scala.Boolean = js.native
  def destroy(): scala.Unit = js.native
  def deviceStatuses(): scala.Boolean = js.native
  def deviceStatuses(param: java.lang.String): scala.Boolean = js.native
  def deviceStatuses(param: java.lang.String, callback: js.Function): scala.Boolean = js.native
  def deviceStatuses(param: java.lang.String, callback: js.Function, dec: scala.Boolean): scala.Boolean = js.native
  def deviceStatuses(param: java.lang.String, callback: js.Function, dec: scala.Boolean, noBypass: scala.Boolean): scala.Boolean = js.native
  def disableGpm(): scala.Unit = js.native
  def disableModifieres(args: java.lang.String*): scala.Boolean = js.native
  def disableMouse(): scala.Unit = js.native
  def dl(): scala.Boolean = js.native
  def dl(param: scala.Double): scala.Boolean = js.native
  def down(): scala.Boolean = js.native
  def down(param: scala.Double): scala.Boolean = js.native
  def dsr(): scala.Boolean = js.native
  def dsr(param: java.lang.String): scala.Boolean = js.native
  def dsr(param: java.lang.String, callback: js.Function): scala.Boolean = js.native
  def dsr(param: java.lang.String, callback: js.Function, dec: scala.Boolean): scala.Boolean = js.native
  def dsr(param: java.lang.String, callback: js.Function, dec: scala.Boolean, noBypass: scala.Boolean): scala.Boolean = js.native
  def dynamicColors(): scala.Boolean = js.native
  def dynamicColors(param: java.lang.String): scala.Boolean = js.native
  def ech(): scala.Boolean = js.native
  def ech(param: scala.Double): scala.Boolean = js.native
  def echo(text: java.lang.String): scala.Boolean = js.native
  def echo(text: java.lang.String, attr: scala.Boolean): scala.Boolean = js.native
  def ed(): scala.Boolean = js.native
  def ed(param: java.lang.String): scala.Boolean = js.native
  def el(): scala.Boolean = js.native
  def el(param: java.lang.String): scala.Boolean = js.native
  def enableFilterRectangle(args: java.lang.String*): scala.Boolean = js.native
  def enableGpm(): scala.Unit = js.native
  def enableLocatorReporting(args: java.lang.String*): scala.Boolean = js.native
  def enableMouse(): scala.Unit = js.native
  def enter_alt_charset_mode(): scala.Boolean = js.native
  def eraseChars(): scala.Boolean = js.native
  def eraseChars(param: scala.Double): scala.Boolean = js.native
  def eraseInDisplay(): scala.Boolean = js.native
  def eraseInDisplay(param: java.lang.String): scala.Boolean = js.native
  def eraseInLine(): scala.Boolean = js.native
  def eraseInLine(param: java.lang.String): scala.Boolean = js.native
  def eraseRectangle(args: java.lang.String*): scala.Boolean = js.native
  def exit_alt_charset_mode(): scala.Boolean = js.native
  def feed(): scala.Boolean = js.native
  def ff(): scala.Boolean = js.native
  def fg(color: java.lang.String): scala.Boolean = js.native
  def fg(color: java.lang.String, `val`: scala.Boolean): scala.Boolean = js.native
  def fillRectangle(args: java.lang.String*): scala.Boolean = js.native
  def flush(): scala.Unit = js.native
  def form(): scala.Boolean = js.native
  def forward(): scala.Boolean = js.native
  def forward(param: scala.Double): scala.Boolean = js.native
  def getCursor(callback: js.Function): scala.Boolean = js.native
  def getCursorColor(callback: js.Function): scala.Boolean = js.native
  def getTextParams(param: java.lang.String, callback: js.Function): scala.Boolean = js.native
  def getWindowSize(): scala.Boolean = js.native
  def getWindowSize(callback: js.Function): scala.Boolean = js.native
  def has(name: java.lang.String): scala.Boolean = js.native
  def hideCursor(): scala.Boolean = js.native
  def hpa(): scala.Boolean = js.native
  def hpa(param: scala.Double): scala.Boolean = js.native
  def ht(): scala.Boolean = js.native
  def hvp(): scala.Boolean = js.native
  def hvp(row: scala.Double): scala.Boolean = js.native
  def hvp(row: scala.Double, col: scala.Double): scala.Boolean = js.native
  def ich(): scala.Boolean = js.native
  def ich(param: scala.Double): scala.Boolean = js.native
  def il(): scala.Boolean = js.native
  def il(param: scala.Double): scala.Boolean = js.native
  def ind(): scala.Boolean = js.native
  def index(): scala.Boolean = js.native
  def initMouseTracking(args: java.lang.String*): scala.Boolean = js.native
  def insertChars(): scala.Boolean = js.native
  def insertChars(param: scala.Double): scala.Boolean = js.native
  def insertColumns(args: java.lang.String*): scala.Boolean = js.native
  def insertLines(): scala.Boolean = js.native
  def insertLines(param: scala.Double): scala.Boolean = js.native
  def kbs(): scala.Boolean = js.native
  def key(key: java.lang.String, listener: js.Function): scala.Unit = js.native
  def key(key: js.Array[java.lang.String], listener: js.Function): scala.Unit = js.native
  def left(): scala.Boolean = js.native
  def left(param: scala.Double): scala.Boolean = js.native
  def lineHeight(): scala.Boolean = js.native
  def linePosAbsolute(): scala.Boolean = js.native
  def linePosAbsolute(param: scala.Double): scala.Boolean = js.native
  def listen(): scala.Unit = js.native
  def loadLEDs(): scala.Boolean = js.native
  def loadLEDs(param: scala.Double): scala.Boolean = js.native
  def log(): scala.Boolean = js.native
  def lrestoreCursor(): scala.Unit = js.native
  def lrestoreCursor(key: java.lang.String): scala.Unit = js.native
  def lrestoreCursor(key: java.lang.String, hide: scala.Boolean): scala.Unit = js.native
  def lsaveCursor(): scala.Unit = js.native
  def lsaveCursor(key: java.lang.String): scala.Unit = js.native
  def manipulateWindow(args: js.Any*): scala.Boolean = js.native
  def mc(args: java.lang.String*): scala.Boolean = js.native
  def mc0(): scala.Boolean = js.native
  def mc4(): scala.Boolean = js.native
  def mc5(): scala.Boolean = js.native
  def mc5p(): scala.Boolean = js.native
  def mediaCopy(args: java.lang.String*): scala.Boolean = js.native
  def move(x: scala.Double, y: scala.Double): scala.Boolean = js.native
  def newline(): scala.Boolean = js.native
  def nextLine(): scala.Boolean = js.native
  def nl(): scala.Boolean = js.native
  def normalBuffer(): scala.Boolean = js.native
  def nul(): scala.Boolean = js.native
  def omove(x: scala.Double, y: scala.Double): scala.Unit = js.native
  def onceKey(key: java.lang.String, listener: js.Function): scala.Unit = js.native
  def onceKey(key: js.Array[java.lang.String], listener: js.Function): scala.Unit = js.native
  def out(param: java.lang.String, args: js.Any*): scala.Boolean = js.native
  def p0(): scala.Boolean = js.native
  def pause(): js.Function = js.native
  def pause(callback: js.Function): js.Function = js.native
  def pf(): scala.Boolean = js.native
  def po(): scala.Boolean = js.native
  def pos(): scala.Boolean = js.native
  def pos(row: scala.Double): scala.Boolean = js.native
  def pos(row: scala.Double, col: scala.Double): scala.Boolean = js.native
  def print(text: java.lang.String): scala.Boolean = js.native
  def print(text: java.lang.String, attr: scala.Boolean): scala.Boolean = js.native
  def print_screen(): scala.Boolean = js.native
  def prtr_non(): scala.Boolean = js.native
  def prtr_off(): scala.Boolean = js.native
  def prtr_on(): scala.Boolean = js.native
  def ps(): scala.Boolean = js.native
  def rc(): scala.Boolean = js.native
  def rc(key: java.lang.String): scala.Boolean = js.native
  def rc(key: java.lang.String, hide: scala.Boolean): scala.Boolean = js.native
  def rcA(): scala.Boolean = js.native
  def removeKey(key: java.lang.String, listener: js.Function): scala.Unit = js.native
  def removeKey(key: js.Array[java.lang.String], listener: js.Function): scala.Unit = js.native
  def rep(): scala.Boolean = js.native
  def rep(param: scala.Double): scala.Boolean = js.native
  def repeat(ch: java.lang.String): java.lang.String = js.native
  def repeat(ch: java.lang.String, i: scala.Double): java.lang.String = js.native
  def repeatPrecedingCharacter(): scala.Boolean = js.native
  def repeatPrecedingCharacter(param: scala.Double): scala.Boolean = js.native
  def req_mouse_pos(): scala.Boolean = js.native
  def req_mouse_pos(param: java.lang.String): scala.Boolean = js.native
  def req_mouse_pos(param: java.lang.String, callback: js.Function): scala.Boolean = js.native
  def reqmp(): scala.Boolean = js.native
  def reqmp(param: java.lang.String): scala.Boolean = js.native
  def reqmp(param: java.lang.String, callback: js.Function): scala.Boolean = js.native
  def requestAnsiMode(): scala.Boolean = js.native
  def requestAnsiMode(param: scala.Double): scala.Boolean = js.native
  def requestLocatorPosition(): scala.Boolean = js.native
  def requestLocatorPosition(param: java.lang.String): scala.Boolean = js.native
  def requestLocatorPosition(param: java.lang.String, callback: js.Function): scala.Boolean = js.native
  def requestParameters(): scala.Boolean = js.native
  def requestParameters(param: scala.Double): scala.Boolean = js.native
  def requestPrivateMode(): scala.Boolean = js.native
  def requestPrivateMode(param: scala.Double): scala.Boolean = js.native
  def reset(): scala.Boolean = js.native
  def resetColors(): scala.Boolean = js.native
  def resetColors(param: java.lang.String): scala.Boolean = js.native
  def resetCursor(): scala.Boolean = js.native
  def resetMode(args: java.lang.String*): scala.Boolean = js.native
  def resetTitleModes(args: java.lang.String*): scala.Boolean = js.native
  def response(name: java.lang.String): scala.Boolean = js.native
  def response(name: java.lang.String, callback: js.Function): scala.Boolean = js.native
  def response(name: java.lang.String, text: java.lang.String, callback: js.Function): scala.Boolean = js.native
  def response(name: java.lang.String, text: java.lang.String, callback: js.Function, noBypass: scala.Boolean): scala.Boolean = js.native
  def restoreCursor(): scala.Boolean = js.native
  def restoreCursor(key: java.lang.String): scala.Boolean = js.native
  def restoreCursor(key: java.lang.String, hide: scala.Boolean): scala.Boolean = js.native
  def restoreCursorA(): scala.Boolean = js.native
  def restorePrivateValues(args: java.lang.String*): scala.Boolean = js.native
  def restoreReportedCursor(): scala.Boolean = js.native
  def resume(): scala.Unit = js.native
  def `return`(): scala.Boolean = js.native
  def reverse(): scala.Boolean = js.native
  def reverseAttrInRectangle(args: java.lang.String*): scala.Boolean = js.native
  def reverseIndex(): scala.Boolean = js.native
  def ri(): scala.Boolean = js.native
  def right(): scala.Boolean = js.native
  def right(param: scala.Double): scala.Boolean = js.native
  def rm(args: java.lang.String*): scala.Boolean = js.native
  def rmacs(): scala.Boolean = js.native
  def rmcup(): scala.Boolean = js.native
  def rmove(x: scala.Double, y: scala.Double): scala.Unit = js.native
  def rs2(): scala.Boolean = js.native
  def rsetx(x: scala.Double): scala.Boolean = js.native
  def rsety(y: scala.Double): scala.Boolean = js.native
  def saveCursor(key: java.lang.String): scala.Boolean = js.native
  def saveCursorA(): scala.Boolean = js.native
  def savePrivateValues(args: java.lang.String*): scala.Boolean = js.native
  def saveReportedCursor(callback: js.Function): scala.Unit = js.native
  def sc(key: java.lang.String): scala.Boolean = js.native
  def scA(): scala.Boolean = js.native
  def scrollDown(): scala.Boolean = js.native
  def scrollDown(param: scala.Double): scala.Boolean = js.native
  def scrollUp(): scala.Boolean = js.native
  def scrollUp(param: scala.Double): scala.Boolean = js.native
  def sd(): scala.Boolean = js.native
  def sd(param: scala.Double): scala.Boolean = js.native
  def selData(a: java.lang.String, b: java.lang.String): scala.Boolean = js.native
  def selectChangeExtent(): scala.Boolean = js.native
  def selectChangeExtent(param: scala.Double): scala.Boolean = js.native
  def selectiveEraseRectangle(args: java.lang.String*): scala.Boolean = js.native
  def sendDeviceAttributes(): scala.Boolean = js.native
  def sendDeviceAttributes(param: scala.Double): scala.Boolean = js.native
  def sendDeviceAttributes(param: scala.Double, callback: js.Function): scala.Boolean = js.native
  def setAttrInRectangle(args: java.lang.String*): scala.Boolean = js.native
  def setBackground(color: java.lang.String): scala.Boolean = js.native
  def setBackground(color: java.lang.String, `val`: scala.Boolean): scala.Boolean = js.native
  def setCharProtectionAttr(): scala.Boolean = js.native
  def setCharProtectionAttr(param: scala.Double): scala.Boolean = js.native
  def setConformanceLevel(args: java.lang.String*): scala.Boolean = js.native
  def setCursorStyle(): scala.Boolean = js.native
  def setCursorStyle(param: java.lang.String): scala.Boolean = js.native
  def setForeground(color: java.lang.String): scala.Boolean = js.native
  def setForeground(color: java.lang.String, `val`: scala.Boolean): scala.Boolean = js.native
  def setG(`val`: scala.Double): scala.Boolean = js.native
  def setLocatorEvents(args: java.lang.String*): scala.Boolean = js.native
  def setMarginBellVolume(): scala.Boolean = js.native
  def setMarginBellVolume(param: scala.Double): scala.Boolean = js.native
  def setMode(args: java.lang.String*): scala.Boolean = js.native
  def setMouse(): scala.Unit = js.native
  def setMouse(opt: js.Object): scala.Unit = js.native
  def setMouse(opt: js.Object, enable: scala.Boolean): scala.Unit = js.native
  def setPointerMode(args: java.lang.String*): scala.Boolean = js.native
  def setResources(args: java.lang.String*): scala.Boolean = js.native
  def setScrollRegion(top: scala.Double, bottom: scala.Double): scala.Boolean = js.native
  def setTerminal(terminal: java.lang.String): scala.Unit = js.native
  def setTitle(title: java.lang.String): scala.Boolean = js.native
  def setTitleModeFeature(args: java.lang.String*): scala.Boolean = js.native
  def setWarningBellVolume(): scala.Boolean = js.native
  def setWarningBellVolume(param: scala.Double): scala.Boolean = js.native
  def setupDump(): scala.Unit = js.native
  def setupTput(): scala.Unit = js.native
  def setx(x: scala.Double): scala.Boolean = js.native
  def sety(y: scala.Double): scala.Boolean = js.native
  def shiftIn(): scala.Boolean = js.native
  def shiftOut(): scala.Boolean = js.native
  def showCursor(): scala.Boolean = js.native
  def sigtstp(): scala.Boolean = js.native
  def sigtstp(callback: js.Function): scala.Boolean = js.native
  def simpleInsert(ch: java.lang.String): scala.Boolean = js.native
  def simpleInsert(ch: java.lang.String, i: scala.Double): scala.Boolean = js.native
  def simpleInsert(ch: java.lang.String, i: scala.Double, attr: scala.Boolean): scala.Boolean = js.native
  def sm(args: java.lang.String*): scala.Boolean = js.native
  def smacs(): scala.Boolean = js.native
  def smcup(): scala.Boolean = js.native
  def softReset(): scala.Boolean = js.native
  def su(): scala.Boolean = js.native
  def su(param: scala.Double): scala.Boolean = js.native
  def tab(): scala.Boolean = js.native
  def tabClear(): scala.Boolean = js.native
  def tabClear(param: scala.Double): scala.Boolean = js.native
  def tabSet(): scala.Boolean = js.native
  def tbc(): scala.Boolean = js.native
  def tbc(param: scala.Double): scala.Boolean = js.native
  def term(is: java.lang.String): scala.Boolean = js.native
  def unKey(key: java.lang.String, listener: js.Function): scala.Unit = js.native
  def unKey(key: js.Array[java.lang.String], listener: js.Function): scala.Unit = js.native
  def up(): scala.Boolean = js.native
  def up(param: scala.Double): scala.Boolean = js.native
  def vi(): scala.Boolean = js.native
  def vpa(): scala.Boolean = js.native
  def vpa(param: scala.Double): scala.Boolean = js.native
  def vpr(): scala.Boolean = js.native
  def vpr(param: scala.Double): scala.Boolean = js.native
  def vtab(): scala.Boolean = js.native
  def write(text: java.lang.String): scala.Boolean = js.native
}

