package typings
package reactDashRouterDashNavigationDashCoreLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait reactDashRouterDashNavigationDashCoreLibProps {
  @scala.inline
  def CardStackProps: reactDashRouterDashNavigationDashCoreLib.reactDashRouterDashNavigationDashCoreMod.CardStackProps.type = reactDashRouterDashNavigationDashCoreLib.reactDashRouterDashNavigationDashCoreMod.CardStackProps
  type CardStackProps = reactDashRouterDashNavigationDashCoreLib.reactDashRouterDashNavigationDashCoreMod.CardStackProps
  @scala.inline
  def TabStackProps: reactDashRouterDashNavigationDashCoreLib.reactDashRouterDashNavigationDashCoreMod.TabStackProps.type = reactDashRouterDashNavigationDashCoreLib.reactDashRouterDashNavigationDashCoreMod.TabStackProps
  type TabStackProps = reactDashRouterDashNavigationDashCoreLib.reactDashRouterDashNavigationDashCoreMod.TabStackProps
}

