package typings.akuminaCore.mod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

// tslint:disable-next-line interface-name
trait IConstants extends js.Object {
  var FORCETEMPLATEURL: Boolean
  var LOADER_STEPS_ENABLE_AUTOCLEAR: Boolean
  var LOADER_STEPS_ENABLE_AUTOLOGINTOAPPMANAGER: Boolean
  var LOADER_STEPS_ENABLE_DEBUGINFO: Boolean
  var LOADER_STEPS_ENABLE_DETECTMULTIPLEVISIBLELANGS: Boolean
  var LOADER_STEPS_ENABLE_DISPLAYLOADER: Boolean
  var LOADER_STEPS_ENABLE_DISPLAYSHAREPOINTBAR: Boolean
  var LOADER_STEPS_ENABLE_EVENTSUBSCRIPTION: Boolean
  var LOADER_STEPS_ENABLE_FETCHADGROUPS: Boolean
  var LOADER_STEPS_ENABLE_FETCHCONFIGCONTEXT: Boolean
  var LOADER_STEPS_ENABLE_FETCHLANGUAGENEUTRALLISTS: Boolean
  var LOADER_STEPS_ENABLE_FETCHLANGUAGES: Boolean
  var LOADER_STEPS_ENABLE_FETCHPAGEPERMISSIONS: Boolean
  var LOADER_STEPS_ENABLE_FETCHSPGROUPS: Boolean
  var LOADER_STEPS_ENABLE_FETCHUSERPROPERTIES: Boolean
  var LOADER_STEPS_ENABLE_FETCHWORKSPACECONTEXT: Boolean
  var LOADER_STEPS_ENABLE_GETADDITIONALMARKUP: Boolean
  var LOADER_STEPS_ENABLE_GETGRAPHTOKEN: Boolean
  var LOADER_STEPS_ENABLE_GETINDIVIDUALWIDGETSJS: Boolean
  var LOADER_STEPS_ENABLE_GETINTERCHANGELOGINURL: Boolean
  var LOADER_STEPS_ENABLE_GETLOADINGTEMPLATE: Boolean
  var LOADER_STEPS_ENABLE_GETWIDGETJS: Boolean
  var LOADER_STEPS_ENABLE_INDEXPAGEDATA: Boolean
  var LOADER_STEPS_ENABLE_INITSNIPPETS: Boolean
  var LOADER_STEPS_ENABLE_INITWIDGETS: Boolean
  var LOADER_STEPS_ENABLE_LOADDASHBOARDWIDGETS: Boolean
  var LOADER_STEPS_ENABLE_LOADUSERLANGSETTINGS: Boolean
  var LOADER_STEPS_ENABLE_LOADWIDGETSINSTANCES: Boolean
  var LOADER_STEPS_ENABLE_LOADWIDGETSTYPES: Boolean
  var LOADER_STEPS_ENABLE_PROVISIONDASHBOARD: Boolean
  var LOADER_STEPS_ENABLE_REFRESHAKTOKEN: Boolean
  var LOADER_STEPS_ENABLE_RESUMEMAINWINDOWLOADER: Boolean
  var LOADER_STEPS_ENABLE_SETSITETHEME: Boolean
  var LOADER_STEPS_ENABLE_TRAYMENU: Boolean
  var LOADER_STEPS_ENABLE_VALIDATEINTERCHANGEKEY: Boolean
  var LOADER_STEPS_ENABLE_VALIDATEWORKSPACECONFIG: Boolean
  var LOG_LEVEL: Double
  var REDIRECTONERROR: Boolean
  var WIDGET_OPTIONS_LOADFROMAPPMANAGER: Boolean
}

object IConstants {
  @scala.inline
  def apply(
    FORCETEMPLATEURL: Boolean,
    LOADER_STEPS_ENABLE_AUTOCLEAR: Boolean,
    LOADER_STEPS_ENABLE_AUTOLOGINTOAPPMANAGER: Boolean,
    LOADER_STEPS_ENABLE_DEBUGINFO: Boolean,
    LOADER_STEPS_ENABLE_DETECTMULTIPLEVISIBLELANGS: Boolean,
    LOADER_STEPS_ENABLE_DISPLAYLOADER: Boolean,
    LOADER_STEPS_ENABLE_DISPLAYSHAREPOINTBAR: Boolean,
    LOADER_STEPS_ENABLE_EVENTSUBSCRIPTION: Boolean,
    LOADER_STEPS_ENABLE_FETCHADGROUPS: Boolean,
    LOADER_STEPS_ENABLE_FETCHCONFIGCONTEXT: Boolean,
    LOADER_STEPS_ENABLE_FETCHLANGUAGENEUTRALLISTS: Boolean,
    LOADER_STEPS_ENABLE_FETCHLANGUAGES: Boolean,
    LOADER_STEPS_ENABLE_FETCHPAGEPERMISSIONS: Boolean,
    LOADER_STEPS_ENABLE_FETCHSPGROUPS: Boolean,
    LOADER_STEPS_ENABLE_FETCHUSERPROPERTIES: Boolean,
    LOADER_STEPS_ENABLE_FETCHWORKSPACECONTEXT: Boolean,
    LOADER_STEPS_ENABLE_GETADDITIONALMARKUP: Boolean,
    LOADER_STEPS_ENABLE_GETGRAPHTOKEN: Boolean,
    LOADER_STEPS_ENABLE_GETINDIVIDUALWIDGETSJS: Boolean,
    LOADER_STEPS_ENABLE_GETINTERCHANGELOGINURL: Boolean,
    LOADER_STEPS_ENABLE_GETLOADINGTEMPLATE: Boolean,
    LOADER_STEPS_ENABLE_GETWIDGETJS: Boolean,
    LOADER_STEPS_ENABLE_INDEXPAGEDATA: Boolean,
    LOADER_STEPS_ENABLE_INITSNIPPETS: Boolean,
    LOADER_STEPS_ENABLE_INITWIDGETS: Boolean,
    LOADER_STEPS_ENABLE_LOADDASHBOARDWIDGETS: Boolean,
    LOADER_STEPS_ENABLE_LOADUSERLANGSETTINGS: Boolean,
    LOADER_STEPS_ENABLE_LOADWIDGETSINSTANCES: Boolean,
    LOADER_STEPS_ENABLE_LOADWIDGETSTYPES: Boolean,
    LOADER_STEPS_ENABLE_PROVISIONDASHBOARD: Boolean,
    LOADER_STEPS_ENABLE_REFRESHAKTOKEN: Boolean,
    LOADER_STEPS_ENABLE_RESUMEMAINWINDOWLOADER: Boolean,
    LOADER_STEPS_ENABLE_SETSITETHEME: Boolean,
    LOADER_STEPS_ENABLE_TRAYMENU: Boolean,
    LOADER_STEPS_ENABLE_VALIDATEINTERCHANGEKEY: Boolean,
    LOADER_STEPS_ENABLE_VALIDATEWORKSPACECONFIG: Boolean,
    LOG_LEVEL: Double,
    REDIRECTONERROR: Boolean,
    WIDGET_OPTIONS_LOADFROMAPPMANAGER: Boolean
  ): IConstants = {
    val __obj = js.Dynamic.literal(FORCETEMPLATEURL = FORCETEMPLATEURL.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_AUTOCLEAR = LOADER_STEPS_ENABLE_AUTOCLEAR.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_AUTOLOGINTOAPPMANAGER = LOADER_STEPS_ENABLE_AUTOLOGINTOAPPMANAGER.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_DEBUGINFO = LOADER_STEPS_ENABLE_DEBUGINFO.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_DETECTMULTIPLEVISIBLELANGS = LOADER_STEPS_ENABLE_DETECTMULTIPLEVISIBLELANGS.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_DISPLAYLOADER = LOADER_STEPS_ENABLE_DISPLAYLOADER.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_DISPLAYSHAREPOINTBAR = LOADER_STEPS_ENABLE_DISPLAYSHAREPOINTBAR.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_EVENTSUBSCRIPTION = LOADER_STEPS_ENABLE_EVENTSUBSCRIPTION.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_FETCHADGROUPS = LOADER_STEPS_ENABLE_FETCHADGROUPS.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_FETCHCONFIGCONTEXT = LOADER_STEPS_ENABLE_FETCHCONFIGCONTEXT.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_FETCHLANGUAGENEUTRALLISTS = LOADER_STEPS_ENABLE_FETCHLANGUAGENEUTRALLISTS.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_FETCHLANGUAGES = LOADER_STEPS_ENABLE_FETCHLANGUAGES.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_FETCHPAGEPERMISSIONS = LOADER_STEPS_ENABLE_FETCHPAGEPERMISSIONS.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_FETCHSPGROUPS = LOADER_STEPS_ENABLE_FETCHSPGROUPS.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_FETCHUSERPROPERTIES = LOADER_STEPS_ENABLE_FETCHUSERPROPERTIES.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_FETCHWORKSPACECONTEXT = LOADER_STEPS_ENABLE_FETCHWORKSPACECONTEXT.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_GETADDITIONALMARKUP = LOADER_STEPS_ENABLE_GETADDITIONALMARKUP.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_GETGRAPHTOKEN = LOADER_STEPS_ENABLE_GETGRAPHTOKEN.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_GETINDIVIDUALWIDGETSJS = LOADER_STEPS_ENABLE_GETINDIVIDUALWIDGETSJS.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_GETINTERCHANGELOGINURL = LOADER_STEPS_ENABLE_GETINTERCHANGELOGINURL.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_GETLOADINGTEMPLATE = LOADER_STEPS_ENABLE_GETLOADINGTEMPLATE.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_GETWIDGETJS = LOADER_STEPS_ENABLE_GETWIDGETJS.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_INDEXPAGEDATA = LOADER_STEPS_ENABLE_INDEXPAGEDATA.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_INITSNIPPETS = LOADER_STEPS_ENABLE_INITSNIPPETS.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_INITWIDGETS = LOADER_STEPS_ENABLE_INITWIDGETS.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_LOADDASHBOARDWIDGETS = LOADER_STEPS_ENABLE_LOADDASHBOARDWIDGETS.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_LOADUSERLANGSETTINGS = LOADER_STEPS_ENABLE_LOADUSERLANGSETTINGS.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_LOADWIDGETSINSTANCES = LOADER_STEPS_ENABLE_LOADWIDGETSINSTANCES.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_LOADWIDGETSTYPES = LOADER_STEPS_ENABLE_LOADWIDGETSTYPES.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_PROVISIONDASHBOARD = LOADER_STEPS_ENABLE_PROVISIONDASHBOARD.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_REFRESHAKTOKEN = LOADER_STEPS_ENABLE_REFRESHAKTOKEN.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_RESUMEMAINWINDOWLOADER = LOADER_STEPS_ENABLE_RESUMEMAINWINDOWLOADER.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_SETSITETHEME = LOADER_STEPS_ENABLE_SETSITETHEME.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_TRAYMENU = LOADER_STEPS_ENABLE_TRAYMENU.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_VALIDATEINTERCHANGEKEY = LOADER_STEPS_ENABLE_VALIDATEINTERCHANGEKEY.asInstanceOf[js.Any], LOADER_STEPS_ENABLE_VALIDATEWORKSPACECONFIG = LOADER_STEPS_ENABLE_VALIDATEWORKSPACECONFIG.asInstanceOf[js.Any], LOG_LEVEL = LOG_LEVEL.asInstanceOf[js.Any], REDIRECTONERROR = REDIRECTONERROR.asInstanceOf[js.Any], WIDGET_OPTIONS_LOADFROMAPPMANAGER = WIDGET_OPTIONS_LOADFROMAPPMANAGER.asInstanceOf[js.Any])
  
    __obj.asInstanceOf[IConstants]
  }
}

