package typings
package w2uiLib.W2UINs

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait W2Grid
  extends W2Common
     with W2OnClickable {
  var autoLoad: scala.Boolean = js.native
  var buttons: js.Object = js.native
  var columnGroups: js.Array[js.Object] = js.native
  var columns: js.Array[js.Object] = js.native
  var fixedBody: scala.Boolean = js.native
  var header: java.lang.String = js.native
  var keyboard: scala.Boolean = js.native
  var last: js.Object = js.native
  var limit: scala.Double = js.native
  var markSearch: scala.Boolean = js.native
  var menu: js.Array[js.Object] = js.native
  var method: java.lang.String = js.native
  var msgAJAXerror: java.lang.String = js.native
  var msgDelete: java.lang.String = js.native
  var msgNotJSON: java.lang.String = js.native
  var msgRefresh: java.lang.String = js.native
  var multiSearch: scala.Boolean = js.native
  var multiSelect: scala.Boolean = js.native
  var multiSort: scala.Boolean = js.native
  var offset: scala.Double = js.native
  var parser: js.Function = js.native
  var postData: js.Object = js.native
  var ranges: js.Array[js.Object] = js.native
  var recid: java.lang.String = js.native
  var recordHeight: scala.Double = js.native
  var records: js.Array[js.Object] = js.native
  var reorderColumns: scala.Boolean = js.native
  var reorderRows: scala.Boolean = js.native
  var routeData: java.lang.String = js.native
  var searchData: js.Array[js.Object] = js.native
  var searches: js.Array[js.Object] = js.native
  var selectType: java.lang.String = js.native
  var show: js.Object = js.native
  var sortData: js.Array[js.Object] = js.native
  var summary: js.Array[js.Object] = js.native
  var toolbar: js.Object = js.native
  var total: scala.Double = js.native
  var url: java.lang.String = js.native
  def add(record: js.Array[w2uiLib.W2UINs.W2GridNs.Records]): scala.Double = js.native
  def add(record: w2uiLib.W2UINs.W2GridNs.Records): scala.Double = js.native
  def addColumn(before: java.lang.String, column: js.Array[w2uiLib.W2UINs.W2GridNs.Columns]): scala.Double = js.native
  def addColumn(before: java.lang.String, column: w2uiLib.W2UINs.W2GridNs.Columns): scala.Double = js.native
  def addColumn(before: scala.Double, column: js.Array[w2uiLib.W2UINs.W2GridNs.Columns]): scala.Double = js.native
  def addColumn(before: scala.Double, column: w2uiLib.W2UINs.W2GridNs.Columns): scala.Double = js.native
  def addColumn(column: js.Array[w2uiLib.W2UINs.W2GridNs.Columns]): scala.Double = js.native
  def addColumn(column: w2uiLib.W2UINs.W2GridNs.Columns): scala.Double = js.native
  def addRange(range: js.Array[w2uiLib.W2UINs.W2GridNs.Ranges]): scala.Double = js.native
  def addRange(range: w2uiLib.W2UINs.W2GridNs.Ranges): scala.Double = js.native
  def addSearch(before: java.lang.String, search: js.Array[js.Object]): scala.Double = js.native
  def addSearch(before: java.lang.String, search: js.Object): scala.Double = js.native
  def addSearch(before: scala.Double, search: js.Array[js.Object]): scala.Double = js.native
  def addSearch(before: scala.Double, search: js.Object): scala.Double = js.native
  def addSearch(search: js.Array[js.Object]): scala.Double = js.native
  def addSearch(search: js.Object): scala.Double = js.native
  def clear(): scala.Unit = js.native
  def clear(noRefresh: scala.Boolean): scala.Unit = js.native
  def click(recid: java.lang.String): scala.Unit = js.native
  def click(recid: java.lang.String, event: js.Object): scala.Unit = js.native
  def collapse(recid: java.lang.String): scala.Boolean = js.native
  def columnClick(field: java.lang.String): scala.Boolean = js.native
  def columnClick(field: java.lang.String, event: js.Object): scala.Boolean = js.native
  def columnOnOff(el: stdLib.HTMLElement, event: js.Object, field: java.lang.String, value: scala.Double): scala.Unit = js.native
  def contextMenu(recid: java.lang.String): scala.Unit = js.native
  def contextMenu(recid: java.lang.String, event: js.Object): scala.Unit = js.native
  def copy(): java.lang.String = js.native
  def dblClick(recid: java.lang.String): scala.Unit = js.native
  def dblClick(recid: java.lang.String, event: js.Object): scala.Unit = js.native
  def delete(force: scala.Boolean): scala.Unit = js.native
  def editField(recid: java.lang.String, column: scala.Double): scala.Unit = js.native
  def editField(recid: java.lang.String, column: scala.Double, value: java.lang.String): scala.Unit = js.native
  def editField(recid: java.lang.String, column: scala.Double, value: java.lang.String, event: js.Object): scala.Unit = js.native
  def error(msg: java.lang.String): scala.Unit = js.native
  def expand(recid: java.lang.String): scala.Boolean = js.native
  def find(`match`: js.Object): js.Array[js.Object] | js.Array[scala.Double] = js.native
  def find(`match`: js.Object, returnIndex: scala.Boolean): js.Array[js.Object] | js.Array[scala.Double] = js.native
  def get(recid: java.lang.String): js.Object | scala.Double | scala.Unit = js.native
  def get(recid: java.lang.String, returnIndex: scala.Boolean): js.Object | scala.Double | scala.Unit = js.native
  def getCellHTML(index: scala.Double, columnIndex: scala.Double): java.lang.String = js.native
  def getCellHTML(index: scala.Double, columnIndex: scala.Double, summary: scala.Boolean): java.lang.String = js.native
  def getCellValue(index: scala.Double, columnIndex: scala.Double): java.lang.String = js.native
  def getCellValue(index: scala.Double, columnIndex: scala.Double, summary: scala.Boolean): java.lang.String = js.native
  def getChanges(): js.Array[js.Object] = js.native
  def getColumn(field: java.lang.String): js.Object | scala.Double | scala.Unit = js.native
  def getColumn(field: java.lang.String, returnIndex: scala.Boolean): js.Object | scala.Double | scala.Unit = js.native
  def getColumnsHTML(): java.lang.String = js.native
  def getFooterHTML(): java.lang.String = js.native
  def getRangeData(range: js.Object): js.Array[js.Array[js.Object]] = js.native
  def getRangeData(range: js.Object, extra: scala.Boolean): js.Array[js.Array[js.Object]] = js.native
  def getRecordHTML(index: scala.Double, lineNumber: scala.Double): java.lang.String = js.native
  def getRecordHTML(index: scala.Double, lineNumber: scala.Double, summary: scala.Boolean): java.lang.String = js.native
  def getRecordsHTML(): java.lang.String = js.native
  def getSearch(field: java.lang.String): js.Object | scala.Double | scala.Unit = js.native
  def getSearch(field: java.lang.String, returnIndex: scala.Boolean): js.Object | scala.Double | scala.Unit = js.native
  def getSearchData(field: java.lang.String): js.Object | scala.Unit = js.native
  def getSearchesHTML(): java.lang.String = js.native
  def getSelection(): js.Array[js.Object] = js.native
   // the doc is weird here
  def getSummaryHTML(): java.lang.String = js.native
  def hideColumn(fields: java.lang.String*): scala.Double = js.native
  def hideSearch(fields: java.lang.String*): scala.Double = js.native
  def initAllField(field: java.lang.String): scala.Unit = js.native
  def initAllField(field: java.lang.String, value: java.lang.String): scala.Unit = js.native
  def initColumnOnOff(): scala.Unit = js.native
  //initOperator(el, searchInd): void; // this is used internally
  def initResize(): scala.Unit = js.native
  def initSearches(): scala.Unit = js.native
  def initToolbar(): scala.Unit = js.native
  def keydown(event: js.Object): scala.Unit = js.native
  def load(url: java.lang.String): scala.Unit = js.native
  def load(url: java.lang.String, callback: js.Function): scala.Unit = js.native
  def localSearch(): scala.Double = js.native
  def localSearch(silent: scala.Boolean): scala.Double = js.native
  def localSort(): scala.Double = js.native
  def localSort(silent: scala.Boolean): scala.Double = js.native
  def lock(message: java.lang.String): scala.Unit = js.native
  def lock(message: java.lang.String, showSpinner: scala.Boolean): scala.Unit = js.native
  def menuClick(recid: java.lang.String, index: scala.Double, event: js.Object): scala.Unit = js.native
  def mergeChanges(): scala.Unit = js.native
  def nextCell(colInd: scala.Double, editable: scala.Boolean): scala.Double | scala.Unit = js.native
  def nextRow(index: scala.Double): scala.Double | scala.Unit = js.native
  def parseField(obj: js.Object, field: java.lang.String): js.Any = js.native
  def paste(text: java.lang.String): scala.Unit = js.native
  def prevCell(colInd: scala.Double, editable: scala.Boolean): scala.Double | scala.Unit = js.native
  def prevRow(index: scala.Double): scala.Double | scala.Unit = js.native
  def refreshCell(recid: java.lang.String, field: java.lang.String): scala.Unit = js.native
  def refreshRanges(): scala.Double = js.native
  def refreshRow(recid: java.lang.String): scala.Unit = js.native
  def reload(): scala.Unit = js.native
  def reload(callback: js.Function): scala.Unit = js.native
  def remove(recids: java.lang.String*): scala.Double = js.native
  def removeColumn(fields: java.lang.String*): scala.Double = js.native
  def removeRange(rangeNames: java.lang.String*): scala.Double = js.native
  def removeSearch(fields: java.lang.String*): scala.Double = js.native
  def request(cmd: java.lang.String): scala.Unit = js.native
  def request(cmd: java.lang.String, params: js.Object): scala.Unit = js.native
  def request(cmd: java.lang.String, params: js.Object, url: java.lang.String): scala.Unit = js.native
  def request(cmd: java.lang.String, params: js.Object, url: java.lang.String, callback: js.Function): scala.Unit = js.native
  def requestComplete(status: java.lang.String, cmd: java.lang.String): scala.Unit = js.native
  def requestComplete(status: java.lang.String, cmd: java.lang.String, callback: js.Function): scala.Unit = js.native
  def reset(): scala.Unit = js.native
  def reset(noRefresh: scala.Boolean): scala.Unit = js.native
  def resizeBoxes(): scala.Unit = js.native
  def resizeRecords(): scala.Unit = js.native
  def save(): scala.Unit = js.native
  def scroll(event: js.Object): scala.Unit = js.native
  def scrollIntoView(ind: scala.Double): scala.Unit = js.native
  def search(field: java.lang.String, value: java.lang.String): scala.Unit = js.native
  def search(searches: js.Array[js.Object]): scala.Unit = js.native
  def search(searches: js.Array[js.Object], logic: java.lang.String): scala.Unit = js.native
  def searchClose(): scala.Unit = js.native
  def searchOpen(): scala.Unit = js.native
  def searchReset(): scala.Unit = js.native
  def searchReset(noRefresh: scala.Boolean): scala.Unit = js.native
  def searchShowFields(): scala.Unit = js.native
  def select(recids: java.lang.String*): scala.Double = js.native
  def selectAll(): scala.Unit = js.native
  def selectNone(): scala.Unit = js.native
  def set(recid: java.lang.String, record: js.Object): scala.Boolean = js.native
  def set(recid: java.lang.String, record: js.Object, noRefresh: scala.Boolean): scala.Boolean = js.native
  def set(record: js.Object): scala.Boolean = js.native
  def set(record: js.Object, noRefresh: scala.Boolean): scala.Boolean = js.native
  def showColumn(fields: java.lang.String*): scala.Double = js.native
  def showSearch(fields: java.lang.String*): scala.Double = js.native
  def skip(offset: scala.Double): scala.Double = js.native
  def sort(): scala.Unit = js.native
  def sort(field: java.lang.String): scala.Unit = js.native
  def sort(field: java.lang.String, direction: java.lang.String): scala.Unit = js.native
  def sort(field: java.lang.String, direction: java.lang.String, multiField: scala.Boolean): scala.Unit = js.native
  def stateReset(): scala.Unit = js.native
  def stateRestore(): js.Object | scala.Unit = js.native
  def stateRestore(stateObj: js.Object): js.Object | scala.Unit = js.native
  def stateSave(): js.Object | scala.Unit = js.native
  def stateSave(returnOnly: scala.Boolean): js.Object | scala.Unit = js.native
  def status(): scala.Unit = js.native
  def status(msg: java.lang.String): scala.Unit = js.native
  def toggle(recid: java.lang.String): scala.Unit = js.native
  def toggleColumn(fields: java.lang.String*): scala.Double = js.native
  def toggleSearch(fields: java.lang.String*): scala.Double = js.native
  def toolbarAdd(): scala.Unit = js.native
  def toolbarDelete(): scala.Unit = js.native
  def toolbarDelete(force: scala.Boolean): scala.Unit = js.native
  def unlock(): scala.Unit = js.native
  def unselect(recids: java.lang.String*): scala.Double = js.native
}

