package typings.atTensorflowTfjsDashCore

import typings.atTensorflowTfjsDashCore.atTensorflowTfjsDashCoreStrings.`Linefeed  SlashSlash vec4 one Equalssign vec4LeftparenthesisequalLeftparenthesisaComma bRightparenthesisRightparenthesisSemicolonLinefeed  SlashSlash return one Plussign Leftparenthesisvec4Leftparenthesis1Dot0Rightparenthesis - oneRightparenthesis Asterisk a Slash bSemicolonLinefeed  vec4 result Equalssign a Slash bSemicolonLinefeed  ifLeftparenthesisaDotx EqualssignEqualssign bDotxRightparenthesis LeftcurlybracketLinefeed    resultDotx Equalssign 1DotSemicolonLinefeed  RightcurlybracketLinefeed`
import typings.atTensorflowTfjsDashCore.atTensorflowTfjsDashCoreStrings.`Linefeed  ivec4 ia Equalssign roundLeftparenthesisaRightparenthesisSemicolonLinefeed  ivec4 ib Equalssign roundLeftparenthesisbRightparenthesisSemicolonLinefeed  bvec4 cond Equalssign notEqualLeftparenthesisibComma ivec4Leftparenthesis0RightparenthesisRightparenthesisSemicolonLinefeed  ivec4 result Equalssign ivec4Leftparenthesis0RightparenthesisSemicolonLinefeed  vec4 s Equalssign signLeftparenthesisaRightparenthesis Asterisk signLeftparenthesisbRightparenthesisSemicolonLinefeedLinefeed  SlashS`
import typings.atTensorflowTfjsDashCore.atTensorflowTfjsDashCoreStrings.`Linefeed  return minLeftparenthesisLinefeed    vec4LeftparenthesisgreaterThanEqualLeftparenthesisaComma vec4Leftparenthesis1Dot0RightparenthesisRightparenthesisRightparenthesis PlussignLinefeed    vec4LeftparenthesisgreaterThanEqualLeftparenthesisbComma vec4Leftparenthesis1Dot0RightparenthesisRightparenthesisRightparenthesisCommaLinefeed    vec4Leftparenthesis1Dot0RightparenthesisRightparenthesisSemicolonLinefeed`
import typings.atTensorflowTfjsDashCore.atTensorflowTfjsDashCoreStrings.`Linefeed  return vec4LeftparenthesisLinefeed    vec4LeftparenthesisgreaterThanEqualLeftparenthesisaComma vec4Leftparenthesis1Dot0RightparenthesisRightparenthesisRightparenthesis AsteriskLinefeed    vec4LeftparenthesisgreaterThanEqualLeftparenthesisbComma vec4Leftparenthesis1Dot0RightparenthesisRightparenthesisRightparenthesisRightparenthesisSemicolonLinefeed`
import typings.atTensorflowTfjsDashCore.atTensorflowTfjsDashCoreStrings.`Linefeed  return vec4LeftparenthesisequalLeftparenthesisaComma bRightparenthesisRightparenthesisSemicolonLinefeed`
import typings.atTensorflowTfjsDashCore.atTensorflowTfjsDashCoreStrings.`Linefeed  return vec4LeftparenthesisgreaterThanEqualLeftparenthesisaComma bRightparenthesisRightparenthesisSemicolonLinefeed`
import typings.atTensorflowTfjsDashCore.atTensorflowTfjsDashCoreStrings.`Linefeed  return vec4LeftparenthesisgreaterThanLeftparenthesisaComma bRightparenthesisRightparenthesisSemicolonLinefeed`
import typings.atTensorflowTfjsDashCore.atTensorflowTfjsDashCoreStrings.`Linefeed  return vec4LeftparenthesislessThanEqualLeftparenthesisaComma bRightparenthesisRightparenthesisSemicolonLinefeed`
import typings.atTensorflowTfjsDashCore.atTensorflowTfjsDashCoreStrings.`Linefeed  return vec4LeftparenthesislessThanLeftparenthesisaComma bRightparenthesisRightparenthesisSemicolonLinefeed`
import typings.atTensorflowTfjsDashCore.atTensorflowTfjsDashCoreStrings.`Linefeed  return vec4LeftparenthesisnotEqualLeftparenthesisaComma bRightparenthesisRightparenthesisSemicolonLinefeed`
import typings.atTensorflowTfjsDashCore.atTensorflowTfjsDashCoreStrings.`Linefeed  vec4 aLessThanZero Equalssign vec4LeftparenthesislessThanLeftparenthesisaComma vec4Leftparenthesis0DotRightparenthesisRightparenthesisRightparenthesisSemicolonLinefeed  return LeftparenthesisaLessThanZero Asterisk Leftparenthesisb Asterisk aRightparenthesisRightparenthesis Plussign LeftparenthesisLeftparenthesisvec4Leftparenthesis1Dot0Rightparenthesis - aLessThanZeroRightparenthesis Asterisk aRightparenthesisSemicolonLinefeed`
import typings.atTensorflowTfjsDashCore.atTensorflowTfjsDashCoreStrings.`Linefeed  vec4 bGTEZero Equalssign vec4LeftparenthesisgreaterThanEqualLeftparenthesisbComma vec4Leftparenthesis0DotRightparenthesisRightparenthesisRightparenthesisSemicolonLinefeed  return LeftparenthesisbGTEZero Asterisk aRightparenthesis Plussign LeftparenthesisLeftparenthesisvec4Leftparenthesis1Dot0Rightparenthesis - bGTEZeroRightparenthesis Asterisk Leftparenthesisa Asterisk Leftparenthesisb Plussign vec4Leftparenthesis1Dot0RightparenthesisRightparenthesisRightparenthesisRightparenthesisSemi`
import typings.atTensorflowTfjsDashCore.distBackendsWebglGpgpuUnderscoreMathMod.GPGPUProgram
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("@tensorflow/tfjs-core/dist/backends/webgl/binaryop_packed_gpu", JSImport.Namespace)
@js.native
object distBackendsWebglBinaryopUnderscorePackedUnderscoreGpuMod extends js.Object {
  @js.native
  class BinaryOpPackedProgram protected () extends GPGPUProgram {
    def this(op: String, aShape: js.Array[Double], bShape: js.Array[Double]) = this()
    def this(op: String, aShape: js.Array[Double], bShape: js.Array[Double], checkOutOfBounds: Boolean) = this()
    /* CompleteClass */
    override var outputShape: js.Array[Double] = js.native
    @JSName("packedInputs")
    var packedInputs_BinaryOpPackedProgram: Boolean = js.native
    @JSName("packedOutput")
    var packedOutput_BinaryOpPackedProgram: Boolean = js.native
    var supportsBroadcasting: Boolean = js.native
    /* CompleteClass */
    override var userCode: String = js.native
    /* CompleteClass */
    override var variableNames: js.Array[String] = js.native
  }
  
  val ATAN2: String = js.native
  val DIV: `Linefeed  SlashSlash vec4 one Equalssign vec4LeftparenthesisequalLeftparenthesisaComma bRightparenthesisRightparenthesisSemicolonLinefeed  SlashSlash return one Plussign Leftparenthesisvec4Leftparenthesis1Dot0Rightparenthesis - oneRightparenthesis Asterisk a Slash bSemicolonLinefeed  vec4 result Equalssign a Slash bSemicolonLinefeed  ifLeftparenthesisaDotx EqualssignEqualssign bDotxRightparenthesis LeftcurlybracketLinefeed    resultDotx Equalssign 1DotSemicolonLinefeed  RightcurlybracketLinefeed` = js.native
  val ELU_DER: `Linefeed  vec4 bGTEZero Equalssign vec4LeftparenthesisgreaterThanEqualLeftparenthesisbComma vec4Leftparenthesis0DotRightparenthesisRightparenthesisRightparenthesisSemicolonLinefeed  return LeftparenthesisbGTEZero Asterisk aRightparenthesis Plussign LeftparenthesisLeftparenthesisvec4Leftparenthesis1Dot0Rightparenthesis - bGTEZeroRightparenthesis Asterisk Leftparenthesisa Asterisk Leftparenthesisb Plussign vec4Leftparenthesis1Dot0RightparenthesisRightparenthesisRightparenthesisRightparenthesisSemi` = js.native
  val EQUAL: `Linefeed  return vec4LeftparenthesisequalLeftparenthesisaComma bRightparenthesisRightparenthesisSemicolonLinefeed` = js.native
  val GREATER: `Linefeed  return vec4LeftparenthesisgreaterThanLeftparenthesisaComma bRightparenthesisRightparenthesisSemicolonLinefeed` = js.native
  val GREATER_EQUAL: `Linefeed  return vec4LeftparenthesisgreaterThanEqualLeftparenthesisaComma bRightparenthesisRightparenthesisSemicolonLinefeed` = js.native
  val INT_DIV: `Linefeed  ivec4 ia Equalssign roundLeftparenthesisaRightparenthesisSemicolonLinefeed  ivec4 ib Equalssign roundLeftparenthesisbRightparenthesisSemicolonLinefeed  bvec4 cond Equalssign notEqualLeftparenthesisibComma ivec4Leftparenthesis0RightparenthesisRightparenthesisSemicolonLinefeed  ivec4 result Equalssign ivec4Leftparenthesis0RightparenthesisSemicolonLinefeed  vec4 s Equalssign signLeftparenthesisaRightparenthesis Asterisk signLeftparenthesisbRightparenthesisSemicolonLinefeedLinefeed  SlashS` = js.native
  val LESS: `Linefeed  return vec4LeftparenthesislessThanLeftparenthesisaComma bRightparenthesisRightparenthesisSemicolonLinefeed` = js.native
  val LESS_EQUAL: `Linefeed  return vec4LeftparenthesislessThanEqualLeftparenthesisaComma bRightparenthesisRightparenthesisSemicolonLinefeed` = js.native
  val LOGICAL_AND: `Linefeed  return vec4LeftparenthesisLinefeed    vec4LeftparenthesisgreaterThanEqualLeftparenthesisaComma vec4Leftparenthesis1Dot0RightparenthesisRightparenthesisRightparenthesis AsteriskLinefeed    vec4LeftparenthesisgreaterThanEqualLeftparenthesisbComma vec4Leftparenthesis1Dot0RightparenthesisRightparenthesisRightparenthesisRightparenthesisSemicolonLinefeed` = js.native
  val LOGICAL_OR: `Linefeed  return minLeftparenthesisLinefeed    vec4LeftparenthesisgreaterThanEqualLeftparenthesisaComma vec4Leftparenthesis1Dot0RightparenthesisRightparenthesisRightparenthesis PlussignLinefeed    vec4LeftparenthesisgreaterThanEqualLeftparenthesisbComma vec4Leftparenthesis1Dot0RightparenthesisRightparenthesisRightparenthesisCommaLinefeed    vec4Leftparenthesis1Dot0RightparenthesisRightparenthesisSemicolonLinefeed` = js.native
  val MAX: String = js.native
  val MIN: String = js.native
  val MOD: String = js.native
  val NOT_EQUAL: `Linefeed  return vec4LeftparenthesisnotEqualLeftparenthesisaComma bRightparenthesisRightparenthesisSemicolonLinefeed` = js.native
  val POW: String = js.native
  val PRELU: `Linefeed  vec4 aLessThanZero Equalssign vec4LeftparenthesislessThanLeftparenthesisaComma vec4Leftparenthesis0DotRightparenthesisRightparenthesisRightparenthesisSemicolonLinefeed  return LeftparenthesisaLessThanZero Asterisk Leftparenthesisb Asterisk aRightparenthesisRightparenthesis Plussign LeftparenthesisLeftparenthesisvec4Leftparenthesis1Dot0Rightparenthesis - aLessThanZeroRightparenthesis Asterisk aRightparenthesisSemicolonLinefeed` = js.native
}

