package typings
package reactDashVerticalDashTimelineDashComponentLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

object reactDashVerticalDashTimelineDashComponentLibComponents extends reactDashVerticalDashTimelineDashComponentLibProps {
  @scala.inline
  def VerticalTimeline: reactLib.reactMod.ComponentType[
    reactDashVerticalDashTimelineDashComponentLib.reactDashVerticalDashTimelineDashComponentMod.VerticalTimelineProps
  ] = js.constructorOf[reactDashVerticalDashTimelineDashComponentLib.reactDashVerticalDashTimelineDashComponentMod.VerticalTimeline].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashVerticalDashTimelineDashComponentLib.reactDashVerticalDashTimelineDashComponentMod.VerticalTimelineProps]]
  @scala.inline
  def VerticalTimelineElement: reactLib.reactMod.ComponentType[
    reactDashVerticalDashTimelineDashComponentLib.reactDashVerticalDashTimelineDashComponentMod.VerticalTimelineElementProps
  ] = js.constructorOf[reactDashVerticalDashTimelineDashComponentLib.reactDashVerticalDashTimelineDashComponentMod.VerticalTimelineElement].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashVerticalDashTimelineDashComponentLib.reactDashVerticalDashTimelineDashComponentMod.VerticalTimelineElementProps]]
}

