package typings
package atAngularCompilerLib.publicUnderscoreApiMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("@angular/compiler/public_api", "TmplAstTemplate")
@js.native
class TmplAstTemplate protected ()
  extends atAngularCompilerLib.srcCompilerMod.TmplAstTemplate {
  def this(tagName: java.lang.String, attributes: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.TextAttribute], inputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundAttribute], outputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundEvent], children: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Node], references: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Reference], variables: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Variable], sourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan) = this()
  def this(tagName: java.lang.String, attributes: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.TextAttribute], inputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundAttribute], outputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundEvent], children: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Node], references: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Reference], variables: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Variable], sourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, startSourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan) = this()
  def this(tagName: java.lang.String, attributes: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.TextAttribute], inputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundAttribute], outputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundEvent], children: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Node], references: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Reference], variables: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Variable], sourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, startSourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, endSourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan) = this()
  def this(tagName: java.lang.String, attributes: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.TextAttribute], inputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundAttribute], outputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundEvent], children: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Node], references: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Reference], variables: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Variable], sourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, startSourceSpan: scala.Null, endSourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan) = this()
  def this(tagName: java.lang.String, attributes: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.TextAttribute], inputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundAttribute], outputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundEvent], children: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Node], references: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Reference], variables: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Variable], sourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, startSourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, endSourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, i18n: atAngularCompilerLib.srcI18nI18nUnderscoreAstMod.Message) = this()
  def this(tagName: java.lang.String, attributes: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.TextAttribute], inputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundAttribute], outputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundEvent], children: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Node], references: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Reference], variables: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Variable], sourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, startSourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, endSourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, i18n: atAngularCompilerLib.srcI18nI18nUnderscoreAstMod.Node) = this()
  def this(tagName: java.lang.String, attributes: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.TextAttribute], inputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundAttribute], outputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundEvent], children: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Node], references: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Reference], variables: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Variable], sourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, startSourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, endSourceSpan: scala.Null, i18n: atAngularCompilerLib.srcI18nI18nUnderscoreAstMod.Message) = this()
  def this(tagName: java.lang.String, attributes: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.TextAttribute], inputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundAttribute], outputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundEvent], children: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Node], references: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Reference], variables: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Variable], sourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, startSourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, endSourceSpan: scala.Null, i18n: atAngularCompilerLib.srcI18nI18nUnderscoreAstMod.Node) = this()
  def this(tagName: java.lang.String, attributes: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.TextAttribute], inputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundAttribute], outputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundEvent], children: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Node], references: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Reference], variables: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Variable], sourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, startSourceSpan: scala.Null, endSourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, i18n: atAngularCompilerLib.srcI18nI18nUnderscoreAstMod.Message) = this()
  def this(tagName: java.lang.String, attributes: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.TextAttribute], inputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundAttribute], outputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundEvent], children: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Node], references: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Reference], variables: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Variable], sourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, startSourceSpan: scala.Null, endSourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, i18n: atAngularCompilerLib.srcI18nI18nUnderscoreAstMod.Node) = this()
  def this(tagName: java.lang.String, attributes: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.TextAttribute], inputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundAttribute], outputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundEvent], children: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Node], references: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Reference], variables: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Variable], sourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, startSourceSpan: scala.Null, endSourceSpan: scala.Null, i18n: atAngularCompilerLib.srcI18nI18nUnderscoreAstMod.Message) = this()
  def this(tagName: java.lang.String, attributes: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.TextAttribute], inputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundAttribute], outputs: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.BoundEvent], children: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Node], references: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Reference], variables: js.Array[atAngularCompilerLib.srcRender3R3UnderscoreAstMod.Variable], sourceSpan: atAngularCompilerLib.srcParseUnderscoreUtilMod.ParseSourceSpan, startSourceSpan: scala.Null, endSourceSpan: scala.Null, i18n: atAngularCompilerLib.srcI18nI18nUnderscoreAstMod.Node) = this()
}

