package typings

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object w3cDashScreenDashOrientationLib {
  type OrientationType = w3cDashScreenDashOrientationLib.w3cDashScreenDashOrientationLibStrings.`portrait-primary` | w3cDashScreenDashOrientationLib.w3cDashScreenDashOrientationLibStrings.`portrait-secondary` | w3cDashScreenDashOrientationLib.w3cDashScreenDashOrientationLibStrings.`landscape-primary` | w3cDashScreenDashOrientationLib.w3cDashScreenDashOrientationLibStrings.`landscape-secondary`
  type ScreenOrientationLockType = w3cDashScreenDashOrientationLib.w3cDashScreenDashOrientationLibStrings.any | w3cDashScreenDashOrientationLib.w3cDashScreenDashOrientationLibStrings.natural | w3cDashScreenDashOrientationLib.w3cDashScreenDashOrientationLibStrings.landscape | w3cDashScreenDashOrientationLib.w3cDashScreenDashOrientationLibStrings.portrait | w3cDashScreenDashOrientationLib.w3cDashScreenDashOrientationLibStrings.`portrait-primary` | w3cDashScreenDashOrientationLib.w3cDashScreenDashOrientationLibStrings.`portrait-secondary` | w3cDashScreenDashOrientationLib.w3cDashScreenDashOrientationLibStrings.`landscape-primary` | w3cDashScreenDashOrientationLib.w3cDashScreenDashOrientationLibStrings.`landscape-secondary`
}
