package typings
package intlDashTelDashInputLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object intlTelInputUtilsNs {
  type placeholderNumberType = intlDashTelDashInputLib.intlDashTelDashInputLibStrings.FIXED_LINE_OR_MOBILE | intlDashTelDashInputLib.intlDashTelDashInputLibStrings.FIXED_LINE | intlDashTelDashInputLib.intlDashTelDashInputLibStrings.MOBILE | intlDashTelDashInputLib.intlDashTelDashInputLibStrings.PAGER | intlDashTelDashInputLib.intlDashTelDashInputLibStrings.PERSONAL_NUMBER | intlDashTelDashInputLib.intlDashTelDashInputLibStrings.PREMIUM_RATE | intlDashTelDashInputLib.intlDashTelDashInputLibStrings.SHARED_COST | intlDashTelDashInputLib.intlDashTelDashInputLibStrings.TOLL_FREE | intlDashTelDashInputLib.intlDashTelDashInputLibStrings.UAN | intlDashTelDashInputLib.intlDashTelDashInputLibStrings.UNKNOWN | intlDashTelDashInputLib.intlDashTelDashInputLibStrings.VOICEMAIL | intlDashTelDashInputLib.intlDashTelDashInputLibStrings.VOIP
}
