package typings
package mfilesLib.MFilesNs

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSGlobal("MFiles")
@js.native
object MFilesNsMembers extends js.Object {
  val AccessControlEntry: mfilesLib.Anon_IAccessControlEntry = js.native
  val AccessControlEntryContainer: mfilesLib.Anon_IAccessControlEntryContainer = js.native
  val AccessControlEntryData: mfilesLib.Anon_IAccessControlEntryData = js.native
  val AccessControlEntryKey: mfilesLib.Anon_IAccessControlEntryKey = js.native
  val AccessControlEntryKeys: mfilesLib.Anon_IAccessControlEntryKeys = js.native
  val AccessControlList: mfilesLib.Anon_IAccessControlList = js.native
  val AccessControlListComponent: mfilesLib.Anon_IAccessControlListComponent = js.native
  val AccessControlListComponentContainer: mfilesLib.Anon_IAccessControlListComponentContainer = js.native
  val AccessControlListComponentKey: mfilesLib.Anon_IAccessControlListComponentKey = js.native
  val AccessControlListComponentKeys: mfilesLib.Anon_IAccessControlListComponentKeys = js.native
  val AccessControlLists: mfilesLib.Anon_IAccessControlLists = js.native
  val ActionConvertToPDF: mfilesLib.Anon_IActionConvertToPDF = js.native
  val ActionCreateAssignment: mfilesLib.Anon_IActionCreateAssignment = js.native
  val ActionDefinition: mfilesLib.Anon_IActionDefinition = js.native
  val ActionDefinitions: mfilesLib.Anon_IActionDefinitions = js.native
  val ActionSendNotification: mfilesLib.Anon_IActionSendNotification = js.native
  val ActionSetPermissions: mfilesLib.Anon_IActionSetPermissions = js.native
  val ActionSetProperties: mfilesLib.Anon_IActionSetProperties = js.native
  val AdditionalClassInfo: mfilesLib.Anon_IAdditionalClassInfo = js.native
  val AdditionalFolder: mfilesLib.Anon_IAdditionalFolder = js.native
  val AdditionalFolders: mfilesLib.Anon_IAdditionalFolders = js.native
  val ApplicationPath: java.lang.String = js.native
  val ApprovalAssignmentClassInfo: mfilesLib.Anon_IApprovalAssignmentClassInfo = js.native
  val ArchiveOldVersionsJob: mfilesLib.Anon_IArchiveOldVersionsJob = js.native
  val AssignmentClassInfo: mfilesLib.Anon_IAssignmentClassInfo = js.native
  val AssociatedPropertyDef: mfilesLib.Anon_IAssociatedPropertyDef = js.native
  val AssociatedPropertyDefs: mfilesLib.Anon_IAssociatedPropertyDefs = js.native
  val AttachVaultOptions: mfilesLib.Anon_IAttachVaultOptions = js.native
  val AuthenticationResult: mfilesLib.Anon_IAuthenticationResult = js.native
  val AuthenticationResultIntermediate: mfilesLib.Anon_IAuthenticationResultIntermediate = js.native
  val AuthenticationResultServerFinal: mfilesLib.Anon_IAuthenticationResultServerFinal = js.native
  val AuthenticationResultVaultFinal: mfilesLib.Anon_IAuthenticationResultVaultFinal = js.native
  val AutomaticMetadataResult: mfilesLib.Anon_IAutomaticMetadataResult = js.native
  val AutomaticPermissions: mfilesLib.Anon_IAutomaticPermissions = js.native
  val AutomaticValue: mfilesLib.Anon_IAutomaticValue = js.native
  val BackupJob: mfilesLib.Anon_IBackupJob = js.native
  val BooleanValue: mfilesLib.Anon_IBooleanValue = js.native
  val CLSID: mfilesLib.ICLSIDs = js.native
  val ClassGroup: mfilesLib.Anon_IClassGroup = js.native
  val ClassGroups: mfilesLib.Anon_IClassGroups = js.native
  val CopyVaultJob: mfilesLib.Anon_ICopyVaultJob = js.native
  val CopyVaultJobOutputInfo: mfilesLib.Anon_ICopyVaultJobOutputInfo = js.native
  val CurrentApplicationPlatform: js.Any = js.native
  val CustomApplication: mfilesLib.Anon_ICustomApplication = js.native
  val CustomApplications: mfilesLib.Anon_ICustomApplications = js.native
  val DailyTrigger: mfilesLib.Anon_IDailyTrigger = js.native
  val DataFunctionCall: mfilesLib.Anon_IDataFunctionCall = js.native
  val DataSet: mfilesLib.Anon_IDataSet = js.native
  val DataSetExportingStatus: mfilesLib.Anon_IDataSetExportingStatus = js.native
  val DataSets: mfilesLib.Anon_IDataSets = js.native
  val DefaultProperties: mfilesLib.Anon_IDefaultProperties = js.native
  val DefaultProperty: mfilesLib.Anon_IDefaultProperty = js.native
  val EmailMessageInformation: mfilesLib.Anon_IEmailMessageInformation = js.native
  val EventHandler: mfilesLib.Anon_IEventHandler = js.native
  val EventHandlers: mfilesLib.Anon_IEventHandlers = js.native
  val ExportContentJob: mfilesLib.Anon_IExportContentJob = js.native
  val ExportStructureItem: mfilesLib.Anon_IExportStructureItem = js.native
  val ExportStructureItems: mfilesLib.Anon_IExportStructureItems = js.native
  val Expression: mfilesLib.Anon_IExpression = js.native
  val ExpressionEx: mfilesLib.Anon_IExpressionEx = js.native
  val ExpressionExs: mfilesLib.Anon_IExpressionExs = js.native
  val Expressions: mfilesLib.Anon_IExpressions = js.native
  val FileClass: mfilesLib.Anon_IFileClass = js.native
  val FileClasses: mfilesLib.Anon_IFileClasses = js.native
  val FileDownloadSession: mfilesLib.Anon_IFileDownloadSession = js.native
  val FileInformation: mfilesLib.Anon_IFileInformation = js.native
  val FileVer: mfilesLib.Anon_IFileVer = js.native
  val FileVers: mfilesLib.Anon_IFileVers = js.native
  val FolderContentItem: mfilesLib.Anon_IFolderContentItem = js.native
  val FolderContentItems: mfilesLib.Anon_IFolderContentItems = js.native
  val FolderDef: mfilesLib.Anon_IFolderDef = js.native
  val FolderDefs: mfilesLib.Anon_IFolderDefs = js.native
  val FolderListingColumn: mfilesLib.Anon_IFolderListingColumn = js.native
  val FolderListingColumnSorting: mfilesLib.Anon_IFolderListingColumnSorting = js.native
  val FolderListingColumnSortings: mfilesLib.Anon_IFolderListingColumnSortings = js.native
  val FolderListingColumns: mfilesLib.Anon_IFolderListingColumns = js.native
  val FolderListingUIState: mfilesLib.Anon_IFolderListingUIState = js.native
  val FolderNameListing: mfilesLib.Anon_IFolderNameListing = js.native
  val FolderUIState: mfilesLib.Anon_IFolderUIState = js.native
  val IDRange: mfilesLib.Anon_IIDRange = js.native
  val IDs: mfilesLib.Anon_IIDs = js.native
  val Impersonation: mfilesLib.Anon_IImpersonation = js.native
  val ImportContentJob: mfilesLib.Anon_IImportContentJob = js.native
  val IndirectPropertyID: mfilesLib.Anon_IIndirectPropertyID = js.native
  val IndirectPropertyIDLevel: mfilesLib.Anon_IIndirectPropertyIDLevel = js.native
  val KeyNamePair: mfilesLib.Anon_IKeyNamePair = js.native
  val KeyNamePairs: mfilesLib.Anon_IKeyNamePairs = js.native
  val Language: mfilesLib.Anon_ILanguage = js.native
  val Languages: mfilesLib.Anon_ILanguages = js.native
  val LicenseStatus: mfilesLib.Anon_ILicenseStatus = js.native
  val LoginAccount: mfilesLib.Anon_ILoginAccount = js.native
  val LoginAccountPersonalInformation: mfilesLib.Anon_ILoginAccountPersonalInformation = js.native
  val LoginAccounts: mfilesLib.Anon_ILoginAccounts = js.native
  val Lookup: mfilesLib.Anon_ILookup = js.native
  val Lookups: mfilesLib.Anon_ILookups = js.native
  val MFResourceManager: mfilesLib.Anon_IMFResourceManager = js.native
  val MFShellDocListCtrl: mfilesLib.Anon_IMFDocListCtrl = js.native
  val MFilesClientApplication: mfilesLib.Anon_IMFilesClientApplication = js.native
  val MFilesServerApplication: mfilesLib.Anon_IMFilesServerApplication = js.native
  val MFilesVersion: mfilesLib.Anon_IMFilesVersion = js.native
  val MetadataStructureSelector: mfilesLib.Anon_IMetadataStructureSelector = js.native
  val MetadataStructureSelectors: mfilesLib.Anon_IMetadataStructureSelectors = js.native
  val MonthlyDOWTrigger: mfilesLib.Anon_IMonthlyDOWTrigger = js.native
  val MonthlyDateTrigger: mfilesLib.Anon_IMonthlyDateTrigger = js.native
  val NamedACL: mfilesLib.Anon_INamedACL = js.native
  val NamedACLAdmin: mfilesLib.Anon_INamedACLAdmin = js.native
  val NamedACLs: mfilesLib.Anon_INamedACLs = js.native
  val NamedACLsAdmin: mfilesLib.Anon_INamedACLsAdmin = js.native
  val NamedValueNamespace: mfilesLib.Anon_INamedValueNamespace = js.native
  val NamedValueNamespaces: mfilesLib.Anon_INamedValueNamespaces = js.native
  val NamedValues: mfilesLib.Anon_INamedValues = js.native
  val Number: mfilesLib.Anon_INumber = js.native
  val OCROptions: mfilesLib.Anon_IOCROptions = js.native
  val OCRPage: mfilesLib.Anon_IOCRPage = js.native
  val OCRPageResult: mfilesLib.Anon_IOCRPageResult = js.native
  val OCRPageResults: mfilesLib.Anon_IOCRPageResults = js.native
  val OCRPages: mfilesLib.Anon_IOCRPages = js.native
  val OCRZone: mfilesLib.Anon_IOCRZone = js.native
  val OCRZoneResult: mfilesLib.Anon_IOCRZoneResult = js.native
  val OCRZoneResults: mfilesLib.Anon_IOCRZoneResults = js.native
  val OCRZones: mfilesLib.Anon_IOCRZones = js.native
  val ObjID: mfilesLib.Anon_IObjID = js.native
  val ObjIDs: mfilesLib.Anon_IObjIDs = js.native
  val ObjOrFileVer: mfilesLib.Anon_IObjOrFileVer = js.native
  val ObjOrFileVers: mfilesLib.Anon_IObjOrFileVers = js.native
  val ObjType: mfilesLib.Anon_IObjectType = js.native
  val ObjTypeAdmin: mfilesLib.Anon_IObjectTypeAdmin = js.native
  val ObjTypeColumnMapping: mfilesLib.Anon_IObjectTypeColumnMapping = js.native
  val ObjTypeColumnMappings: mfilesLib.Anon_IObjectTypeColumnMappings = js.native
  val ObjTypes: mfilesLib.Anon_IObjectTypes = js.native
  val ObjTypesAdmin: mfilesLib.Anon_IObjectTypesAdmin = js.native
  val ObjVer: mfilesLib.Anon_IObjVer = js.native
  val ObjVers: mfilesLib.Anon_IObjVers = js.native
  val ObjectClass: mfilesLib.Anon_IObjectClass = js.native
  val ObjectClassAdmin: mfilesLib.Anon_IObjectClassAdmin = js.native
  val ObjectClasses: mfilesLib.Anon_IObjectClasses = js.native
  val ObjectClassesAdmin: mfilesLib.Anon_IObjectClassesAdmin = js.native
  val ObjectCreationInfo: mfilesLib.Anon_IObjectCreationInfo = js.native
  val ObjectFile: mfilesLib.Anon_IObjectFile = js.native
  val ObjectFileAndObjVer: mfilesLib.Anon_IObjectFileAndObjVer = js.native
  val ObjectFileAndObjVerOfMultipleFiles: mfilesLib.Anon_IObjectFileAndObjVerOfMultipleFiles = js.native
  val ObjectFiles: mfilesLib.Anon_IObjectFiles = js.native
  val ObjectSearchResults: mfilesLib.Anon_IObjectSearchResults = js.native
  val ObjectTypeTargetForBrowsing: mfilesLib.Anon_IObjectTypeTargetForBrowsing = js.native
  val ObjectTypeTargetsForBrowsing: mfilesLib.Anon_IObjectTypeTargetsForBrowsing = js.native
  val ObjectVersion: mfilesLib.Anon_IObjectVersion = js.native
  val ObjectVersionAndProperties: mfilesLib.Anon_IObjectVersionAndProperties = js.native
  val ObjectVersionAndPropertiesOfMultipleObjects: mfilesLib.Anon_IObjectVersionAndPropertiesOfMultipleObjects = js.native
  val ObjectVersionFile: mfilesLib.Anon_IObjectFileAndVersion = js.native
  val ObjectVersionPermissions: mfilesLib.Anon_IObjectVersionPermissions = js.native
  val ObjectVersionWorkflowState: mfilesLib.Anon_IObjectVersionWorkflowState = js.native
  val ObjectVersions: mfilesLib.Anon_IObjectVersions = js.native
  val ObjectWindowResult: mfilesLib.Anon_IObjectWindowResult = js.native
  val OptimizeVaultJob: mfilesLib.Anon_IOptimizeVaultJob = js.native
  val OwnerPropertyDef: mfilesLib.Anon_IOwnerPropertyDef = js.native
  val PluginInfo: mfilesLib.Anon_IPluginInfo = js.native
  val PluginInfos: mfilesLib.Anon_IPluginInfos = js.native
  val PreviewerActiveXCtrl: mfilesLib.Anon_IPreviewerActiveXCtrl = js.native
  val PropertyDef: mfilesLib.Anon_IPropertyDef = js.native
  val PropertyDefAdmin: mfilesLib.Anon_IPropertyDefAdmin = js.native
  val PropertyDefOrObjectType: mfilesLib.Anon_IPropertyDefOrObjectType = js.native
  val PropertyDefOrObjectTypes: mfilesLib.Anon_IPropertyDefOrObjectTypes = js.native
  val PropertyDefs: mfilesLib.Anon_IPropertyDefs = js.native
  val PropertyDefsAdmin: mfilesLib.Anon_IPropertyDefsAdmin = js.native
  val PropertyValue: mfilesLib.Anon_IPropertyValue = js.native
  val PropertyValueForDisplay: mfilesLib.Anon_IPropertyValueForDisplay = js.native
  val PropertyValueIconClue: mfilesLib.Anon_IPropertyValueIconClue = js.native
  val PropertyValueIconClues: mfilesLib.Anon_IPropertyValueIconClues = js.native
  val PropertyValueSuggestion: mfilesLib.Anon_IPropertyValueSuggestion = js.native
  val PropertyValueSuggestions: mfilesLib.Anon_IPropertyValueSuggestions = js.native
  val PropertyValues: mfilesLib.Anon_IPropertyValues = js.native
  val PropertyValuesForDisplay: mfilesLib.Anon_IPropertyValuesForDisplay = js.native
  val PropertyValuesOfMultipleObjects: mfilesLib.Anon_IPropertyValuesOfMultipleObjects = js.native
  val PropertyValuesWithIconClues: mfilesLib.Anon_IPropertyValuesWithIconClues = js.native
  val PropertyValuesWithIconCluesOfMultipleObjects: mfilesLib.Anon_IPropertyValuesWithIconCluesOfMultipleObjects = js.native
  val ReportAccessCredentials: mfilesLib.Anon_IReportAccessCredentials = js.native
  val RestoreJob: mfilesLib.Anon_IRestoreJob = js.native
  val SQLDatabase: mfilesLib.Anon_ISQLDatabase = js.native
  val ScheduledJob: mfilesLib.Anon_IScheduledJob = js.native
  val ScheduledJobOutputInfo: mfilesLib.Anon_IScheduledJobOutputInfo = js.native
  val ScheduledJobRunInfo: mfilesLib.Anon_IScheduledJobRunInfo = js.native
  val ScheduledJobTrigger: mfilesLib.Anon_IScheduledJobTrigger = js.native
  val ScheduledJobTriggers: mfilesLib.Anon_IScheduledJobTriggers = js.native
  val ScheduledJobs: mfilesLib.Anon_IScheduledJobs = js.native
  val SearchCondition: mfilesLib.Anon_ISearchCondition = js.native
  val SearchConditionEx: mfilesLib.Anon_ISearchConditionEx = js.native
  val SearchConditionExs: mfilesLib.Anon_ISearchConditionExs = js.native
  val SearchConditions: mfilesLib.Anon_ISearchConditions = js.native
  val SearchCriteria: mfilesLib.Anon_ISearchCriteria = js.native
  val SearchDef: mfilesLib.Anon_ISearchDef = js.native
  val SemanticAliases: mfilesLib.Anon_ISemanticAliases = js.native
  val ServerLicenseManagementOperations: mfilesLib.Anon_IServerLicenseManagementOperations = js.native
  val ServerLoginAccountOperations: mfilesLib.Anon_IServerLoginAccountOperations = js.native
  val ServerManagementOperations: mfilesLib.Anon_IServerManagementOperations = js.native
  val ServerScheduledJobManagementOperations: mfilesLib.Anon_IServerScheduledJobManagementOperations = js.native
  val ServerVaultManagementOperations: mfilesLib.Anon_IServerVaultManagementOperations = js.native
  val SessionInfo: mfilesLib.Anon_ISessionInfo = js.native
  val SetPropertiesParams: mfilesLib.Anon_ISetPropertiesParams = js.native
  val SetPropertiesParamsOfMultipleObjects: mfilesLib.Anon_ISetPropertiesParamsOfMultipleObjects = js.native
  val SharedFileInfo: mfilesLib.Anon_ISharedFileInfo = js.native
  val SharedLinkInfo: mfilesLib.Anon_ISharedLinkInfo = js.native
  val SharedLinkInfos: mfilesLib.Anon_ISharedLinkInfos = js.native
  val SharedLinkPublicOperations: mfilesLib.Anon_ISharedLinkPublicOperations = js.native
  val ShortcutMappingInfo: mfilesLib.Anon_IShortcutMappingInfo = js.native
  val SignaturePromptInfo: mfilesLib.Anon_ISignaturePromptInfo = js.native
  val SignaturePromptInfoMetadataBased: mfilesLib.Anon_ISignaturePromptInfoMetadataBased = js.native
  val SignaturePromptInfoSelectable: mfilesLib.Anon_ISignaturePromptInfoSelectable = js.native
  val SignaturePromptInfos: mfilesLib.Anon_ISignaturePromptInfos = js.native
  val SignatureSettings: mfilesLib.Anon_ISignatureSettings = js.native
  val SourceObjectFile: mfilesLib.Anon_ISourceObjectFile = js.native
  val SourceObjectFiles: mfilesLib.Anon_ISourceObjectFiles = js.native
  val State: mfilesLib.Anon_IState = js.native
  val StateAdmin: mfilesLib.Anon_IStateAdmin = js.native
  val StateConditions: mfilesLib.Anon_IStateConditions = js.native
  val StateTransition: mfilesLib.Anon_IStateTransition = js.native
  val StateTransitionForClient: mfilesLib.Anon_IStateTransitionForClient = js.native
  val StateTransitions: mfilesLib.Anon_IStateTransitions = js.native
  val StateTransitionsForClient: mfilesLib.Anon_IStateTransitionsForClient = js.native
  val States: mfilesLib.Anon_IStates = js.native
  val StatesAdmin: mfilesLib.Anon_IStatesAdmin = js.native
  val StringData: mfilesLib.Anon_IStringData = js.native
  val Strings: mfilesLib.Anon_IStrings = js.native
  val TaskAssignmentClassInfo: mfilesLib.Anon_ITaskAssignmentClassInfo = js.native
  val TemporarySearchView: mfilesLib.Anon_ITemporarySearchView = js.native
  val TimeZoneInformation: mfilesLib.Anon_ITimeZoneInformation = js.native
  val Timestamp: mfilesLib.Anon_ITimestamp = js.native
  val TraditionalFolder: mfilesLib.Anon_ITraditionalFolder = js.native
  val TraditionalFolderContents: mfilesLib.Anon_ITraditionalFolderContents = js.native
  val TraditionalFolders: mfilesLib.Anon_ITraditionalFolders = js.native
  val TriggerType: mfilesLib.Anon_ITriggerType = js.native
  val TypedValue: mfilesLib.Anon_ITypedValue = js.native
  val TypedValues: mfilesLib.Anon_ITypedValues = js.native
  val UserAccount: mfilesLib.Anon_IUserAccount = js.native
  val UserAccounts: mfilesLib.Anon_IUserAccounts = js.native
  val UserGroup: mfilesLib.Anon_IUserGroup = js.native
  val UserGroupAdmin: mfilesLib.Anon_IUserGroupAdmin = js.native
  val UserGroups: mfilesLib.Anon_IUserGroups = js.native
  val UserGroupsAdmin: mfilesLib.Anon_IUserGroupsAdmin = js.native
  val UserOrUserGroupID: mfilesLib.Anon_IUserOrUserGroupID = js.native
  val UserOrUserGroupIDEx: mfilesLib.Anon_IUserOrUserGroupIDEx = js.native
  val UserOrUserGroupIDExs: mfilesLib.Anon_IUserOrUserGroupIDExs = js.native
  val UserOrUserGroupIDs: mfilesLib.Anon_IUserOrUserGroupIDs = js.native
  val Validation: mfilesLib.Anon_IValidation = js.native
  val ValueListItem: mfilesLib.Anon_IValueListItem = js.native
  val ValueListItemSearchResults: mfilesLib.Anon_IValueListItemSearchResults = js.native
  val ValueListItemSearchResultsWithPermissions: mfilesLib.Anon_IValueListItemSearchResultsWithPermissions = js.native
  val ValueListItems: mfilesLib.Anon_IValueListItems = js.native
  val ValueListItemsWithPermissions: mfilesLib.Anon_IValueListItemsWithPermissions = js.native
  val Vault: mfilesLib.Anon_IVault = js.native
  val VaultAutomaticMetadataOperations: mfilesLib.Anon_IVaultAutomaticMetadataOperations = js.native
  val VaultClassGroupOperations: mfilesLib.Anon_IVaultClassGroupOperations = js.native
  val VaultClassOperations: mfilesLib.Anon_IVaultClassOperations = js.native
  val VaultClientOperations: mfilesLib.Anon_IVaultClientOperations = js.native
  val VaultConnection: mfilesLib.Anon_IVaultConnection = js.native
  val VaultConnections: mfilesLib.Anon_IVaultConnections = js.native
  val VaultCustomApplicationManagementOperations: mfilesLib.Anon_IVaultCustomApplicationManagementOperations = js.native
  val VaultDataSetOperations: mfilesLib.Anon_IVaultDataSetOperations = js.native
  val VaultElectronicSignatureOperations: mfilesLib.Anon_IVaultElectronicSignatureOperations = js.native
  val VaultEventLogOperations: mfilesLib.Anon_IVaultEventLogOperations = js.native
  val VaultExtensionMethodOperations: mfilesLib.Anon_IVaultExtensionMethodOperations = js.native
  val VaultExternalObjectOperations: mfilesLib.Anon_IVaultExternalObjectOperations = js.native
  val VaultLoginAccountOperations: mfilesLib.Anon_IVaultLoginAccountOperations = js.native
  val VaultManagementOperations: mfilesLib.Anon_IVaultManagementOperations = js.native
  val VaultNamedACLOperations: mfilesLib.Anon_IVaultNamedACLOperations = js.native
  val VaultNamedValueStorageOperations: mfilesLib.Anon_IVaultNamedValueStorageOperations = js.native
  val VaultNotificationOperations: mfilesLib.Anon_IVaultNotificationOperations = js.native
  val VaultObjectFileOperations: mfilesLib.Anon_IVaultObjectFileOperations = js.native
  val VaultObjectOperations: mfilesLib.Anon_IVaultObjectOperations = js.native
  val VaultObjectPropertyOperations: mfilesLib.Anon_IVaultObjectPropertyOperations = js.native
  val VaultObjectSearchOperations: mfilesLib.Anon_IVaultObjectSearchOperations = js.native
  val VaultObjectTypeOperations: mfilesLib.Anon_IVaultObjectTypeOperations = js.native
  val VaultOnServer: mfilesLib.Anon_IVaultOnServer = js.native
  val VaultProperties: mfilesLib.Anon_IVaultProperties = js.native
  val VaultPropertyDefOperations: mfilesLib.Anon_IVaultPropertyDefOperations = js.native
  val VaultScheduledJobManagementOperations: mfilesLib.Anon_IVaultScheduledJobManagementOperations = js.native
  val VaultServerDataPushOperations: mfilesLib.Anon_IVaultServerDataPushOperations = js.native
  val VaultSharedLinkOperations: mfilesLib.Anon_IVaultSharedLinkOperations = js.native
  val VaultTraditionalFolderOperations: mfilesLib.Anon_IVaultTraditionalFolderOperations = js.native
  val VaultUserGroupOperations: mfilesLib.Anon_IVaultUserGroupOperations = js.native
  val VaultUserOperations: mfilesLib.Anon_IVaultUserOperations = js.native
  val VaultUserSettingOperations: mfilesLib.Anon_IVaultUserSettingOperations = js.native
  val VaultValueListItemOperations: mfilesLib.Anon_IVaultValueListItemOperations = js.native
  val VaultValueListOperations: mfilesLib.Anon_IVaultValueListOperations = js.native
  val VaultViewOperations: mfilesLib.Anon_IVaultViewOperations = js.native
  val VaultWorkflowOperations: mfilesLib.Anon_IVaultWorkflowOperations = js.native
  val VaultsOnServer: mfilesLib.Anon_IVaultsOnServer = js.native
  val VerifyVaultJob: mfilesLib.Anon_IVerifyVaultJob = js.native
  val VerifyVaultJobOutput: mfilesLib.Anon_IVerifyVaultJobOutput = js.native
  val VersionComment: mfilesLib.Anon_IVersionComment = js.native
  val VersionComments: mfilesLib.Anon_IVersionComments = js.native
  val View: mfilesLib.Anon_IView = js.native
  val ViewLocation: mfilesLib.Anon_IViewLocation = js.native
  val Views: mfilesLib.Anon_IViews = js.native
  val WeeklyTrigger: mfilesLib.Anon_IWeeklyTrigger = js.native
  val Workflow: mfilesLib.Anon_IWorkflow = js.native
  val WorkflowAdmin: mfilesLib.Anon_IWorkflowAdmin = js.native
  val WorkflowAssignment: mfilesLib.Anon_IWorkflowAssignment = js.native
  val Workflows: mfilesLib.Anon_IWorkflows = js.native
  val WorkflowsAdmin: mfilesLib.Anon_IWorkflowsAdmin = js.native
  val XMLSearchResult: mfilesLib.Anon_IXMLSearchResult = js.native
  def CreateInstance(name: java.lang.String): js.Any = js.native
  def CreateObjectCLR(assemblyFile: java.lang.String, className: java.lang.String): js.Any = js.native
  def DeleteRegistryKey(userSpecific: scala.Boolean, key: java.lang.String): scala.Unit = js.native
  def DeleteRegistryValue(userSpecific: scala.Boolean, key: java.lang.String, valueName: java.lang.String): scala.Unit = js.native
  def EnableExceptionPropagation(exception: js.Any): scala.Unit = js.native
  def ExecuteURL(url: java.lang.String): scala.Unit = js.native
  def GetErrorDescription(exception: js.Any): java.lang.String = js.native
  def GetLongErrorDescription(exception: js.Any): java.lang.String = js.native
  def GetStringResource(resource: scala.Double): java.lang.String = js.native
  def KillTimer(timerId: scala.Double): scala.Unit = js.native
  def LaunchHelp(helpID: java.lang.String): scala.Unit = js.native
  def PersistStringData(name: java.lang.String, privateData: scala.Boolean, data: java.lang.String): scala.Unit = js.native
  def ReadFromRegistry(userSpecific: scala.Boolean, key: java.lang.String, valueName: java.lang.String): js.Any = js.native
  def ReadTextFile(filename: java.lang.String): java.lang.String = js.native
  def ReportException(exception: js.Any): scala.Unit = js.native
  def RetrieveStringData(name: java.lang.String, privateData: scala.Boolean): java.lang.String = js.native
  def SetTimer(timeoutInMs: scala.Double, callbackMethod: js.Function0[scala.Unit]): scala.Double = js.native
  def ThrowError(description: java.lang.String): scala.Unit = js.native
  def WriteToRegistry(
    userSpecific: scala.Boolean,
    key: java.lang.String,
    valueName: java.lang.String,
    value: js.Any,
    valueType: java.lang.String
  ): scala.Unit = js.native
}

