package typings.atAwsDashSdkClientDashLambdaDashNode.typesOutputTypesUnionMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesAddPermissionOutputMod.AddPermissionOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesCreateAliasOutputMod.CreateAliasOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesCreateEventSourceMappingOutputMod.CreateEventSourceMappingOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesCreateFunctionOutputMod.CreateFunctionOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesDeleteAliasOutputMod.DeleteAliasOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesDeleteEventSourceMappingOutputMod.DeleteEventSourceMappingOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesDeleteFunctionOutputMod.DeleteFunctionOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesDeleteFunctionConcurrencyOutputMod.DeleteFunctionConcurrencyOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesGetAccountSettingsOutputMod.GetAccountSettingsOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesGetAliasOutputMod.GetAliasOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesGetEventSourceMappingOutputMod.GetEventSourceMappingOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesGetFunctionOutputMod.GetFunctionOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesGetFunctionConfigurationOutputMod.GetFunctionConfigurationOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesGetPolicyOutputMod.GetPolicyOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesInvokeOutputMod.InvokeOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesInvokeAsyncOutputMod.InvokeAsyncOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesListAliasesOutputMod.ListAliasesOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesListEventSourceMappingsOutputMod.ListEventSourceMappingsOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesListFunctionsOutputMod.ListFunctionsOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesListTagsOutputMod.ListTagsOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesListVersionsByFunctionOutputMod.ListVersionsByFunctionOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesPublishVersionOutputMod.PublishVersionOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesPutFunctionConcurrencyOutputMod.PutFunctionConcurrencyOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesRemovePermissionOutputMod.RemovePermissionOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesTagResourceOutputMod.TagResourceOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesUntagResourceOutputMod.UntagResourceOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesUpdateAliasOutputMod.UpdateAliasOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesUpdateEventSourceMappingOutputMod.UpdateEventSourceMappingOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesUpdateFunctionCodeOutputMod.UpdateFunctionCodeOutput
  - typings.atAwsDashSdkClientDashLambdaDashNode.typesUpdateFunctionConfigurationOutputMod.UpdateFunctionConfigurationOutput
*/
trait OutputTypesUnion extends js.Object

