package typings.atAwsDashSdkClientDashPinpointDashBrowser.typesNotFoundExceptionMod

import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesCreateAppExceptionsUnionMod.CreateAppExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesCreateCampaignExceptionsUnionMod.CreateCampaignExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesCreateExportJobExceptionsUnionMod.CreateExportJobExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesCreateImportJobExceptionsUnionMod.CreateImportJobExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesCreateSegmentExceptionsUnionMod.CreateSegmentExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesDeleteAdmChannelExceptionsUnionMod.DeleteAdmChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesDeleteApnsChannelExceptionsUnionMod.DeleteApnsChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesDeleteApnsSandboxChannelExceptionsUnionMod.DeleteApnsSandboxChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesDeleteApnsVoipChannelExceptionsUnionMod.DeleteApnsVoipChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesDeleteApnsVoipSandboxChannelExceptionsUnionMod.DeleteApnsVoipSandboxChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesDeleteAppExceptionsUnionMod.DeleteAppExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesDeleteBaiduChannelExceptionsUnionMod.DeleteBaiduChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesDeleteCampaignExceptionsUnionMod.DeleteCampaignExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesDeleteEmailChannelExceptionsUnionMod.DeleteEmailChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesDeleteEndpointExceptionsUnionMod.DeleteEndpointExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesDeleteEventStreamExceptionsUnionMod.DeleteEventStreamExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesDeleteGcmChannelExceptionsUnionMod.DeleteGcmChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesDeleteSegmentExceptionsUnionMod.DeleteSegmentExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesDeleteSmsChannelExceptionsUnionMod.DeleteSmsChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesDeleteUserEndpointsExceptionsUnionMod.DeleteUserEndpointsExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetAdmChannelExceptionsUnionMod.GetAdmChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetApnsChannelExceptionsUnionMod.GetApnsChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetApnsSandboxChannelExceptionsUnionMod.GetApnsSandboxChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetApnsVoipChannelExceptionsUnionMod.GetApnsVoipChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetApnsVoipSandboxChannelExceptionsUnionMod.GetApnsVoipSandboxChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetAppExceptionsUnionMod.GetAppExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetApplicationSettingsExceptionsUnionMod.GetApplicationSettingsExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetAppsExceptionsUnionMod.GetAppsExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetBaiduChannelExceptionsUnionMod.GetBaiduChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetCampaignActivitiesExceptionsUnionMod.GetCampaignActivitiesExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetCampaignExceptionsUnionMod.GetCampaignExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetCampaignVersionExceptionsUnionMod.GetCampaignVersionExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetCampaignVersionsExceptionsUnionMod.GetCampaignVersionsExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetCampaignsExceptionsUnionMod.GetCampaignsExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetChannelsExceptionsUnionMod.GetChannelsExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetEmailChannelExceptionsUnionMod.GetEmailChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetEndpointExceptionsUnionMod.GetEndpointExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetEventStreamExceptionsUnionMod.GetEventStreamExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetExportJobExceptionsUnionMod.GetExportJobExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetExportJobsExceptionsUnionMod.GetExportJobsExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetGcmChannelExceptionsUnionMod.GetGcmChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetImportJobExceptionsUnionMod.GetImportJobExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetImportJobsExceptionsUnionMod.GetImportJobsExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetSegmentExceptionsUnionMod.GetSegmentExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetSegmentExportJobsExceptionsUnionMod.GetSegmentExportJobsExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetSegmentImportJobsExceptionsUnionMod.GetSegmentImportJobsExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetSegmentVersionExceptionsUnionMod.GetSegmentVersionExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetSegmentVersionsExceptionsUnionMod.GetSegmentVersionsExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetSegmentsExceptionsUnionMod.GetSegmentsExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetSmsChannelExceptionsUnionMod.GetSmsChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesGetUserEndpointsExceptionsUnionMod.GetUserEndpointsExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesPhoneNumberValidateExceptionsUnionMod.PhoneNumberValidateExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesPutEventStreamExceptionsUnionMod.PutEventStreamExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesPutEventsExceptionsUnionMod.PutEventsExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesRemoveAttributesExceptionsUnionMod.RemoveAttributesExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesSendMessagesExceptionsUnionMod.SendMessagesExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesSendUsersMessagesExceptionsUnionMod.SendUsersMessagesExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesUpdateAdmChannelExceptionsUnionMod.UpdateAdmChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesUpdateApnsChannelExceptionsUnionMod.UpdateApnsChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesUpdateApnsSandboxChannelExceptionsUnionMod.UpdateApnsSandboxChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesUpdateApnsVoipChannelExceptionsUnionMod.UpdateApnsVoipChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesUpdateApnsVoipSandboxChannelExceptionsUnionMod.UpdateApnsVoipSandboxChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesUpdateApplicationSettingsExceptionsUnionMod.UpdateApplicationSettingsExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesUpdateBaiduChannelExceptionsUnionMod.UpdateBaiduChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesUpdateCampaignExceptionsUnionMod.UpdateCampaignExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesUpdateEmailChannelExceptionsUnionMod.UpdateEmailChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesUpdateEndpointExceptionsUnionMod.UpdateEndpointExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesUpdateEndpointsBatchExceptionsUnionMod.UpdateEndpointsBatchExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesUpdateGcmChannelExceptionsUnionMod.UpdateGcmChannelExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesUpdateSegmentExceptionsUnionMod.UpdateSegmentExceptionsUnion
import typings.atAwsDashSdkClientDashPinpointDashBrowser.typesUpdateSmsChannelExceptionsUnionMod.UpdateSmsChannelExceptionsUnion
import typings.atAwsDashSdkTypes.buildExceptionMod.ServiceException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait NotFoundException
  extends ServiceException[_NotFoundExceptionDetails]
     with CreateAppExceptionsUnion
     with CreateCampaignExceptionsUnion
     with CreateExportJobExceptionsUnion
     with CreateImportJobExceptionsUnion
     with CreateSegmentExceptionsUnion
     with DeleteAdmChannelExceptionsUnion
     with DeleteApnsChannelExceptionsUnion
     with DeleteApnsSandboxChannelExceptionsUnion
     with DeleteApnsVoipChannelExceptionsUnion
     with DeleteApnsVoipSandboxChannelExceptionsUnion
     with DeleteAppExceptionsUnion
     with DeleteBaiduChannelExceptionsUnion
     with DeleteCampaignExceptionsUnion
     with DeleteEmailChannelExceptionsUnion
     with DeleteEndpointExceptionsUnion
     with DeleteEventStreamExceptionsUnion
     with DeleteGcmChannelExceptionsUnion
     with DeleteSegmentExceptionsUnion
     with DeleteSmsChannelExceptionsUnion
     with DeleteUserEndpointsExceptionsUnion
     with GetAdmChannelExceptionsUnion
     with GetApnsChannelExceptionsUnion
     with GetApnsSandboxChannelExceptionsUnion
     with GetApnsVoipChannelExceptionsUnion
     with GetApnsVoipSandboxChannelExceptionsUnion
     with GetAppExceptionsUnion
     with GetApplicationSettingsExceptionsUnion
     with GetAppsExceptionsUnion
     with GetBaiduChannelExceptionsUnion
     with GetCampaignActivitiesExceptionsUnion
     with GetCampaignExceptionsUnion
     with GetCampaignVersionExceptionsUnion
     with GetCampaignVersionsExceptionsUnion
     with GetCampaignsExceptionsUnion
     with GetChannelsExceptionsUnion
     with GetEmailChannelExceptionsUnion
     with GetEndpointExceptionsUnion
     with GetEventStreamExceptionsUnion
     with GetExportJobExceptionsUnion
     with GetExportJobsExceptionsUnion
     with GetGcmChannelExceptionsUnion
     with GetImportJobExceptionsUnion
     with GetImportJobsExceptionsUnion
     with GetSegmentExceptionsUnion
     with GetSegmentExportJobsExceptionsUnion
     with GetSegmentImportJobsExceptionsUnion
     with GetSegmentVersionExceptionsUnion
     with GetSegmentVersionsExceptionsUnion
     with GetSegmentsExceptionsUnion
     with GetSmsChannelExceptionsUnion
     with GetUserEndpointsExceptionsUnion
     with PhoneNumberValidateExceptionsUnion
     with PutEventStreamExceptionsUnion
     with PutEventsExceptionsUnion
     with RemoveAttributesExceptionsUnion
     with SendMessagesExceptionsUnion
     with SendUsersMessagesExceptionsUnion
     with UpdateAdmChannelExceptionsUnion
     with UpdateApnsChannelExceptionsUnion
     with UpdateApnsSandboxChannelExceptionsUnion
     with UpdateApnsVoipChannelExceptionsUnion
     with UpdateApnsVoipSandboxChannelExceptionsUnion
     with UpdateApplicationSettingsExceptionsUnion
     with UpdateBaiduChannelExceptionsUnion
     with UpdateCampaignExceptionsUnion
     with UpdateEmailChannelExceptionsUnion
     with UpdateEndpointExceptionsUnion
     with UpdateEndpointsBatchExceptionsUnion
     with UpdateGcmChannelExceptionsUnion
     with UpdateSegmentExceptionsUnion
     with UpdateSmsChannelExceptionsUnion {
  @JSName("name")
  var name_NotFoundException: typings.atAwsDashSdkClientDashPinpointDashBrowser.atAwsDashSdkClientDashPinpointDashBrowserStrings.NotFoundException
}

object NotFoundException {
  @scala.inline
  def apply(
    details: _NotFoundExceptionDetails,
    message: String,
    name: typings.atAwsDashSdkClientDashPinpointDashBrowser.atAwsDashSdkClientDashPinpointDashBrowserStrings.NotFoundException,
    stack: String = null
  ): NotFoundException = {
    val __obj = js.Dynamic.literal(details = details, message = message, name = name)
    if (stack != null) __obj.updateDynamic("stack")(stack)
    __obj.asInstanceOf[NotFoundException]
  }
}

