package typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.DataType

import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._AccentColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BackgroundColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._Border
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderBlock
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderBlockColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderBlockEnd
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderBlockEndColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderBlockStart
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderBlockStartColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderBottom
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderBottomColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderInline
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderInlineColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderInlineEnd
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderInlineEndColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderInlineStart
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderInlineStartColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderLeft
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderLeftColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderRight
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderRightColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderTop
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._BorderTopColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._CaretColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._ColumnRule
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._ColumnRuleColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._FloodColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._LightingColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._MozBorderBottomColors
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._MozBorderLeftColors
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._MozBorderRightColors
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._MozBorderTopColors
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._MsScrollbar3dlightColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._MsScrollbarArrowColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._MsScrollbarBaseColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._MsScrollbarDarkshadowColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._MsScrollbarFaceColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._MsScrollbarHighlightColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._MsScrollbarShadowColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._MsScrollbarTrackColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._Outline
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._OutlineColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._StopColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._TextDecoration
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._TextDecorationColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._TextEmphasis
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._TextEmphasisColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._WebkitBorderBefore
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._WebkitBorderBeforeColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._WebkitTapHighlightColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._WebkitTextFillColor
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._WebkitTextStroke
import typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._WebkitTextStrokeColor
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

trait _Color
  extends StObject
     with _AccentColor
     with _BackgroundColor
     with _Border[Any]
     with _BorderBlock[Any]
     with _BorderBlockColor
     with _BorderBlockEnd[Any]
     with _BorderBlockEndColor
     with _BorderBlockStart[Any]
     with _BorderBlockStartColor
     with _BorderBottom[Any]
     with _BorderBottomColor
     with _BorderColor
     with _BorderInline[Any]
     with _BorderInlineColor
     with _BorderInlineEnd[Any]
     with _BorderInlineEndColor
     with _BorderInlineStart[Any]
     with _BorderInlineStartColor
     with _BorderLeft[Any]
     with _BorderLeftColor
     with _BorderRight[Any]
     with _BorderRightColor
     with _BorderTop[Any]
     with _BorderTopColor
     with _CaretColor
     with typings.storybookTheming.emotionReactNodeModulesCsstypeIndexMod.Property._Color
     with _ColumnRule[Any]
     with _ColumnRuleColor
     with _FinalBgLayer[Any]
     with _FloodColor
     with _LightingColor
     with _MozBorderBottomColors
     with _MozBorderLeftColors
     with _MozBorderRightColors
     with _MozBorderTopColors
     with _MsScrollbar3dlightColor
     with _MsScrollbarArrowColor
     with _MsScrollbarBaseColor
     with _MsScrollbarDarkshadowColor
     with _MsScrollbarFaceColor
     with _MsScrollbarHighlightColor
     with _MsScrollbarShadowColor
     with _MsScrollbarTrackColor
     with _Outline[Any]
     with _OutlineColor
     with _Paint
     with _StopColor
     with _TextDecoration[Any]
     with _TextDecorationColor
     with _TextEmphasis
     with _TextEmphasisColor
     with _WebkitBorderBefore[Any]
     with _WebkitBorderBeforeColor
     with _WebkitTapHighlightColor
     with _WebkitTextFillColor
     with _WebkitTextStroke[Any]
     with _WebkitTextStrokeColor
