package typings
package expressDashValidatorLib.checkSchemaMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait ValidatorsSchema extends js.Object {
  var contains: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  @JSName("equals")
  var equals_FValidatorsSchema: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isAfter: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isAlpha: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isAlphanumeric: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isArray: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isAscii: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isBase64: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isBefore: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isBoolean: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isByteLength: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isCreditCard: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isCurrency: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isDataURI: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isDecimal: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isDivisibleBy: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isEmail: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isEmpty: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isFQDN: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isFloat: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isFullWidth: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isHalfWidth: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isHash: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isHexColor: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isHexadecimal: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isIP: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isIPRange: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isISBN: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isISIN: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isISO31661Alpha2: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isISO31661Alpha3: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isISO8601: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isISRC: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isISSN: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isIn: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isInt: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isJSON: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isLatLong: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isLength: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isLowercase: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isMACAddress: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isMD5: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isMimeType: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isMobilePhone: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isMongoId: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isMultibyte: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isNumeric: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isPort: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isPostalCode: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isString: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isSurrogatePair: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isURL: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isUUID: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isUppercase: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isVariableWidth: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var isWhitelisted: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
  var matches: js.UndefOr[ValidatorSchemaOptions[_]] = js.undefined
}

object ValidatorsSchema {
  @scala.inline
  def apply(
    contains: ValidatorSchemaOptions[_] = null,
    equals: ValidatorSchemaOptions[_] = null,
    isAfter: ValidatorSchemaOptions[_] = null,
    isAlpha: ValidatorSchemaOptions[_] = null,
    isAlphanumeric: ValidatorSchemaOptions[_] = null,
    isArray: ValidatorSchemaOptions[_] = null,
    isAscii: ValidatorSchemaOptions[_] = null,
    isBase64: ValidatorSchemaOptions[_] = null,
    isBefore: ValidatorSchemaOptions[_] = null,
    isBoolean: ValidatorSchemaOptions[_] = null,
    isByteLength: ValidatorSchemaOptions[_] = null,
    isCreditCard: ValidatorSchemaOptions[_] = null,
    isCurrency: ValidatorSchemaOptions[_] = null,
    isDataURI: ValidatorSchemaOptions[_] = null,
    isDecimal: ValidatorSchemaOptions[_] = null,
    isDivisibleBy: ValidatorSchemaOptions[_] = null,
    isEmail: ValidatorSchemaOptions[_] = null,
    isEmpty: ValidatorSchemaOptions[_] = null,
    isFQDN: ValidatorSchemaOptions[_] = null,
    isFloat: ValidatorSchemaOptions[_] = null,
    isFullWidth: ValidatorSchemaOptions[_] = null,
    isHalfWidth: ValidatorSchemaOptions[_] = null,
    isHash: ValidatorSchemaOptions[_] = null,
    isHexColor: ValidatorSchemaOptions[_] = null,
    isHexadecimal: ValidatorSchemaOptions[_] = null,
    isIP: ValidatorSchemaOptions[_] = null,
    isIPRange: ValidatorSchemaOptions[_] = null,
    isISBN: ValidatorSchemaOptions[_] = null,
    isISIN: ValidatorSchemaOptions[_] = null,
    isISO31661Alpha2: ValidatorSchemaOptions[_] = null,
    isISO31661Alpha3: ValidatorSchemaOptions[_] = null,
    isISO8601: ValidatorSchemaOptions[_] = null,
    isISRC: ValidatorSchemaOptions[_] = null,
    isISSN: ValidatorSchemaOptions[_] = null,
    isIn: ValidatorSchemaOptions[_] = null,
    isInt: ValidatorSchemaOptions[_] = null,
    isJSON: ValidatorSchemaOptions[_] = null,
    isLatLong: ValidatorSchemaOptions[_] = null,
    isLength: ValidatorSchemaOptions[_] = null,
    isLowercase: ValidatorSchemaOptions[_] = null,
    isMACAddress: ValidatorSchemaOptions[_] = null,
    isMD5: ValidatorSchemaOptions[_] = null,
    isMimeType: ValidatorSchemaOptions[_] = null,
    isMobilePhone: ValidatorSchemaOptions[_] = null,
    isMongoId: ValidatorSchemaOptions[_] = null,
    isMultibyte: ValidatorSchemaOptions[_] = null,
    isNumeric: ValidatorSchemaOptions[_] = null,
    isPort: ValidatorSchemaOptions[_] = null,
    isPostalCode: ValidatorSchemaOptions[_] = null,
    isString: ValidatorSchemaOptions[_] = null,
    isSurrogatePair: ValidatorSchemaOptions[_] = null,
    isURL: ValidatorSchemaOptions[_] = null,
    isUUID: ValidatorSchemaOptions[_] = null,
    isUppercase: ValidatorSchemaOptions[_] = null,
    isVariableWidth: ValidatorSchemaOptions[_] = null,
    isWhitelisted: ValidatorSchemaOptions[_] = null,
    matches: ValidatorSchemaOptions[_] = null
  ): ValidatorsSchema = {
    val __obj = js.Dynamic.literal()
    if (contains != null) __obj.updateDynamic("contains")(contains)
    if (equals != null) __obj.updateDynamic("equals")(equals)
    if (isAfter != null) __obj.updateDynamic("isAfter")(isAfter)
    if (isAlpha != null) __obj.updateDynamic("isAlpha")(isAlpha)
    if (isAlphanumeric != null) __obj.updateDynamic("isAlphanumeric")(isAlphanumeric)
    if (isArray != null) __obj.updateDynamic("isArray")(isArray)
    if (isAscii != null) __obj.updateDynamic("isAscii")(isAscii)
    if (isBase64 != null) __obj.updateDynamic("isBase64")(isBase64)
    if (isBefore != null) __obj.updateDynamic("isBefore")(isBefore)
    if (isBoolean != null) __obj.updateDynamic("isBoolean")(isBoolean)
    if (isByteLength != null) __obj.updateDynamic("isByteLength")(isByteLength)
    if (isCreditCard != null) __obj.updateDynamic("isCreditCard")(isCreditCard)
    if (isCurrency != null) __obj.updateDynamic("isCurrency")(isCurrency)
    if (isDataURI != null) __obj.updateDynamic("isDataURI")(isDataURI)
    if (isDecimal != null) __obj.updateDynamic("isDecimal")(isDecimal)
    if (isDivisibleBy != null) __obj.updateDynamic("isDivisibleBy")(isDivisibleBy)
    if (isEmail != null) __obj.updateDynamic("isEmail")(isEmail)
    if (isEmpty != null) __obj.updateDynamic("isEmpty")(isEmpty)
    if (isFQDN != null) __obj.updateDynamic("isFQDN")(isFQDN)
    if (isFloat != null) __obj.updateDynamic("isFloat")(isFloat)
    if (isFullWidth != null) __obj.updateDynamic("isFullWidth")(isFullWidth)
    if (isHalfWidth != null) __obj.updateDynamic("isHalfWidth")(isHalfWidth)
    if (isHash != null) __obj.updateDynamic("isHash")(isHash)
    if (isHexColor != null) __obj.updateDynamic("isHexColor")(isHexColor)
    if (isHexadecimal != null) __obj.updateDynamic("isHexadecimal")(isHexadecimal)
    if (isIP != null) __obj.updateDynamic("isIP")(isIP)
    if (isIPRange != null) __obj.updateDynamic("isIPRange")(isIPRange)
    if (isISBN != null) __obj.updateDynamic("isISBN")(isISBN)
    if (isISIN != null) __obj.updateDynamic("isISIN")(isISIN)
    if (isISO31661Alpha2 != null) __obj.updateDynamic("isISO31661Alpha2")(isISO31661Alpha2)
    if (isISO31661Alpha3 != null) __obj.updateDynamic("isISO31661Alpha3")(isISO31661Alpha3)
    if (isISO8601 != null) __obj.updateDynamic("isISO8601")(isISO8601)
    if (isISRC != null) __obj.updateDynamic("isISRC")(isISRC)
    if (isISSN != null) __obj.updateDynamic("isISSN")(isISSN)
    if (isIn != null) __obj.updateDynamic("isIn")(isIn)
    if (isInt != null) __obj.updateDynamic("isInt")(isInt)
    if (isJSON != null) __obj.updateDynamic("isJSON")(isJSON)
    if (isLatLong != null) __obj.updateDynamic("isLatLong")(isLatLong)
    if (isLength != null) __obj.updateDynamic("isLength")(isLength)
    if (isLowercase != null) __obj.updateDynamic("isLowercase")(isLowercase)
    if (isMACAddress != null) __obj.updateDynamic("isMACAddress")(isMACAddress)
    if (isMD5 != null) __obj.updateDynamic("isMD5")(isMD5)
    if (isMimeType != null) __obj.updateDynamic("isMimeType")(isMimeType)
    if (isMobilePhone != null) __obj.updateDynamic("isMobilePhone")(isMobilePhone)
    if (isMongoId != null) __obj.updateDynamic("isMongoId")(isMongoId)
    if (isMultibyte != null) __obj.updateDynamic("isMultibyte")(isMultibyte)
    if (isNumeric != null) __obj.updateDynamic("isNumeric")(isNumeric)
    if (isPort != null) __obj.updateDynamic("isPort")(isPort)
    if (isPostalCode != null) __obj.updateDynamic("isPostalCode")(isPostalCode)
    if (isString != null) __obj.updateDynamic("isString")(isString)
    if (isSurrogatePair != null) __obj.updateDynamic("isSurrogatePair")(isSurrogatePair)
    if (isURL != null) __obj.updateDynamic("isURL")(isURL)
    if (isUUID != null) __obj.updateDynamic("isUUID")(isUUID)
    if (isUppercase != null) __obj.updateDynamic("isUppercase")(isUppercase)
    if (isVariableWidth != null) __obj.updateDynamic("isVariableWidth")(isVariableWidth)
    if (isWhitelisted != null) __obj.updateDynamic("isWhitelisted")(isWhitelisted)
    if (matches != null) __obj.updateDynamic("matches")(matches)
    __obj.asInstanceOf[ValidatorsSchema]
  }
}

