package typings.vegaDashTypings

import typings.vegaDashTypings.typesSpecColorMod.ColorName
import typings.vegaDashTypings.typesSpecColorMod.HexColor
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("vega-typings/types/spec/color", JSImport.Namespace)
@js.native
object typesSpecColorMod extends js.Object {
  /* Rewritten from type alias, can be one of: 
    - typings.vegaDashTypings.vegaDashTypingsStrings.black
    - typings.vegaDashTypings.vegaDashTypingsStrings.silver
    - typings.vegaDashTypings.vegaDashTypingsStrings.gray
    - typings.vegaDashTypings.vegaDashTypingsStrings.white
    - typings.vegaDashTypings.vegaDashTypingsStrings.maroon
    - typings.vegaDashTypings.vegaDashTypingsStrings.red
    - typings.vegaDashTypings.vegaDashTypingsStrings.purple
    - typings.vegaDashTypings.vegaDashTypingsStrings.fuchsia
    - typings.vegaDashTypings.vegaDashTypingsStrings.green
    - typings.vegaDashTypings.vegaDashTypingsStrings.lime
    - typings.vegaDashTypings.vegaDashTypingsStrings.olive
    - typings.vegaDashTypings.vegaDashTypingsStrings.yellow
    - typings.vegaDashTypings.vegaDashTypingsStrings.navy
    - typings.vegaDashTypings.vegaDashTypingsStrings.blue
    - typings.vegaDashTypings.vegaDashTypingsStrings.teal
    - typings.vegaDashTypings.vegaDashTypingsStrings.aqua
    - typings.vegaDashTypings.vegaDashTypingsStrings.orange
    - typings.vegaDashTypings.vegaDashTypingsStrings.aliceblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.antiquewhite
    - typings.vegaDashTypings.vegaDashTypingsStrings.aquamarine
    - typings.vegaDashTypings.vegaDashTypingsStrings.azure
    - typings.vegaDashTypings.vegaDashTypingsStrings.beige
    - typings.vegaDashTypings.vegaDashTypingsStrings.bisque
    - typings.vegaDashTypings.vegaDashTypingsStrings.blanchedalmond
    - typings.vegaDashTypings.vegaDashTypingsStrings.blueviolet
    - typings.vegaDashTypings.vegaDashTypingsStrings.brown
    - typings.vegaDashTypings.vegaDashTypingsStrings.burlywood
    - typings.vegaDashTypings.vegaDashTypingsStrings.cadetblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.chartreuse
    - typings.vegaDashTypings.vegaDashTypingsStrings.chocolate
    - typings.vegaDashTypings.vegaDashTypingsStrings.coral
    - typings.vegaDashTypings.vegaDashTypingsStrings.cornflowerblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.cornsilk
    - typings.vegaDashTypings.vegaDashTypingsStrings.crimson
    - typings.vegaDashTypings.vegaDashTypingsStrings.cyan
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkcyan
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkgoldenrod
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkgray
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkgreen
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkgrey
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkkhaki
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkmagenta
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkolivegreen
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkorange
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkorchid
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkred
    - typings.vegaDashTypings.vegaDashTypingsStrings.darksalmon
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkseagreen
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkslateblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkslategray
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkslategrey
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkturquoise
    - typings.vegaDashTypings.vegaDashTypingsStrings.darkviolet
    - typings.vegaDashTypings.vegaDashTypingsStrings.deeppink
    - typings.vegaDashTypings.vegaDashTypingsStrings.deepskyblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.dimgray
    - typings.vegaDashTypings.vegaDashTypingsStrings.dimgrey
    - typings.vegaDashTypings.vegaDashTypingsStrings.dodgerblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.firebrick
    - typings.vegaDashTypings.vegaDashTypingsStrings.floralwhite
    - typings.vegaDashTypings.vegaDashTypingsStrings.forestgreen
    - typings.vegaDashTypings.vegaDashTypingsStrings.gainsboro
    - typings.vegaDashTypings.vegaDashTypingsStrings.ghostwhite
    - typings.vegaDashTypings.vegaDashTypingsStrings.gold
    - typings.vegaDashTypings.vegaDashTypingsStrings.goldenrod
    - typings.vegaDashTypings.vegaDashTypingsStrings.greenyellow
    - typings.vegaDashTypings.vegaDashTypingsStrings.grey
    - typings.vegaDashTypings.vegaDashTypingsStrings.honeydew
    - typings.vegaDashTypings.vegaDashTypingsStrings.hotpink
    - typings.vegaDashTypings.vegaDashTypingsStrings.indianred
    - typings.vegaDashTypings.vegaDashTypingsStrings.indigo
    - typings.vegaDashTypings.vegaDashTypingsStrings.ivory
    - typings.vegaDashTypings.vegaDashTypingsStrings.khaki
    - typings.vegaDashTypings.vegaDashTypingsStrings.lavender
    - typings.vegaDashTypings.vegaDashTypingsStrings.lavenderblush
    - typings.vegaDashTypings.vegaDashTypingsStrings.lawngreen
    - typings.vegaDashTypings.vegaDashTypingsStrings.lemonchiffon
    - typings.vegaDashTypings.vegaDashTypingsStrings.lightblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.lightcoral
    - typings.vegaDashTypings.vegaDashTypingsStrings.lightcyan
    - typings.vegaDashTypings.vegaDashTypingsStrings.lightgoldenrodyellow
    - typings.vegaDashTypings.vegaDashTypingsStrings.lightgray
    - typings.vegaDashTypings.vegaDashTypingsStrings.lightgreen
    - typings.vegaDashTypings.vegaDashTypingsStrings.lightgrey
    - typings.vegaDashTypings.vegaDashTypingsStrings.lightpink
    - typings.vegaDashTypings.vegaDashTypingsStrings.lightsalmon
    - typings.vegaDashTypings.vegaDashTypingsStrings.lightseagreen
    - typings.vegaDashTypings.vegaDashTypingsStrings.lightskyblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.lightslategray
    - typings.vegaDashTypings.vegaDashTypingsStrings.lightslategrey
    - typings.vegaDashTypings.vegaDashTypingsStrings.lightsteelblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.lightyellow
    - typings.vegaDashTypings.vegaDashTypingsStrings.limegreen
    - typings.vegaDashTypings.vegaDashTypingsStrings.linen
    - typings.vegaDashTypings.vegaDashTypingsStrings.magenta
    - typings.vegaDashTypings.vegaDashTypingsStrings.mediumaquamarine
    - typings.vegaDashTypings.vegaDashTypingsStrings.mediumblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.mediumorchid
    - typings.vegaDashTypings.vegaDashTypingsStrings.mediumpurple
    - typings.vegaDashTypings.vegaDashTypingsStrings.mediumseagreen
    - typings.vegaDashTypings.vegaDashTypingsStrings.mediumslateblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.mediumspringgreen
    - typings.vegaDashTypings.vegaDashTypingsStrings.mediumturquoise
    - typings.vegaDashTypings.vegaDashTypingsStrings.mediumvioletred
    - typings.vegaDashTypings.vegaDashTypingsStrings.midnightblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.mintcream
    - typings.vegaDashTypings.vegaDashTypingsStrings.mistyrose
    - typings.vegaDashTypings.vegaDashTypingsStrings.moccasin
    - typings.vegaDashTypings.vegaDashTypingsStrings.navajowhite
    - typings.vegaDashTypings.vegaDashTypingsStrings.oldlace
    - typings.vegaDashTypings.vegaDashTypingsStrings.olivedrab
    - typings.vegaDashTypings.vegaDashTypingsStrings.orangered
    - typings.vegaDashTypings.vegaDashTypingsStrings.orchid
    - typings.vegaDashTypings.vegaDashTypingsStrings.palegoldenrod
    - typings.vegaDashTypings.vegaDashTypingsStrings.palegreen
    - typings.vegaDashTypings.vegaDashTypingsStrings.paleturquoise
    - typings.vegaDashTypings.vegaDashTypingsStrings.palevioletred
    - typings.vegaDashTypings.vegaDashTypingsStrings.papayawhip
    - typings.vegaDashTypings.vegaDashTypingsStrings.peachpuff
    - typings.vegaDashTypings.vegaDashTypingsStrings.peru
    - typings.vegaDashTypings.vegaDashTypingsStrings.pink
    - typings.vegaDashTypings.vegaDashTypingsStrings.plum
    - typings.vegaDashTypings.vegaDashTypingsStrings.powderblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.rosybrown
    - typings.vegaDashTypings.vegaDashTypingsStrings.royalblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.saddlebrown
    - typings.vegaDashTypings.vegaDashTypingsStrings.salmon
    - typings.vegaDashTypings.vegaDashTypingsStrings.sandybrown
    - typings.vegaDashTypings.vegaDashTypingsStrings.seagreen
    - typings.vegaDashTypings.vegaDashTypingsStrings.seashell
    - typings.vegaDashTypings.vegaDashTypingsStrings.sienna
    - typings.vegaDashTypings.vegaDashTypingsStrings.skyblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.slateblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.slategray
    - typings.vegaDashTypings.vegaDashTypingsStrings.slategrey
    - typings.vegaDashTypings.vegaDashTypingsStrings.snow
    - typings.vegaDashTypings.vegaDashTypingsStrings.springgreen
    - typings.vegaDashTypings.vegaDashTypingsStrings.steelblue
    - typings.vegaDashTypings.vegaDashTypingsStrings.tan
    - typings.vegaDashTypings.vegaDashTypingsStrings.thistle
    - typings.vegaDashTypings.vegaDashTypingsStrings.tomato
    - typings.vegaDashTypings.vegaDashTypingsStrings.turquoise
    - typings.vegaDashTypings.vegaDashTypingsStrings.violet
    - typings.vegaDashTypings.vegaDashTypingsStrings.wheat
    - typings.vegaDashTypings.vegaDashTypingsStrings.whitesmoke
    - typings.vegaDashTypings.vegaDashTypingsStrings.yellowgreen
    - typings.vegaDashTypings.vegaDashTypingsStrings.rebeccapurple
  */
  trait ColorName extends js.Object
  
  type Color = ColorName | HexColor | String
  type HexColor = String
}

