package typings.xss.xssMod.Global.XSSNs

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait IWhiteList extends js.Object {
  var a: js.UndefOr[js.Array[String]] = js.undefined
  var abbr: js.UndefOr[js.Array[String]] = js.undefined
  var address: js.UndefOr[js.Array[String]] = js.undefined
  var area: js.UndefOr[js.Array[String]] = js.undefined
  var article: js.UndefOr[js.Array[String]] = js.undefined
  var aside: js.UndefOr[js.Array[String]] = js.undefined
  var audio: js.UndefOr[js.Array[String]] = js.undefined
  var b: js.UndefOr[js.Array[String]] = js.undefined
  var bdi: js.UndefOr[js.Array[String]] = js.undefined
  var bdo: js.UndefOr[js.Array[String]] = js.undefined
  var big: js.UndefOr[js.Array[String]] = js.undefined
  var blockquote: js.UndefOr[js.Array[String]] = js.undefined
  var br: js.UndefOr[js.Array[String]] = js.undefined
  var caption: js.UndefOr[js.Array[String]] = js.undefined
  var center: js.UndefOr[js.Array[String]] = js.undefined
  var cite: js.UndefOr[js.Array[String]] = js.undefined
  var code: js.UndefOr[js.Array[String]] = js.undefined
  var col: js.UndefOr[js.Array[String]] = js.undefined
  var colgroup: js.UndefOr[js.Array[String]] = js.undefined
  var dd: js.UndefOr[js.Array[String]] = js.undefined
  var del: js.UndefOr[js.Array[String]] = js.undefined
  var details: js.UndefOr[js.Array[String]] = js.undefined
  var div: js.UndefOr[js.Array[String]] = js.undefined
  var dl: js.UndefOr[js.Array[String]] = js.undefined
  var dt: js.UndefOr[js.Array[String]] = js.undefined
  var em: js.UndefOr[js.Array[String]] = js.undefined
  var font: js.UndefOr[js.Array[String]] = js.undefined
  var footer: js.UndefOr[js.Array[String]] = js.undefined
  var h1: js.UndefOr[js.Array[String]] = js.undefined
  var h2: js.UndefOr[js.Array[String]] = js.undefined
  var h3: js.UndefOr[js.Array[String]] = js.undefined
  var h4: js.UndefOr[js.Array[String]] = js.undefined
  var h5: js.UndefOr[js.Array[String]] = js.undefined
  var h6: js.UndefOr[js.Array[String]] = js.undefined
  var header: js.UndefOr[js.Array[String]] = js.undefined
  var hr: js.UndefOr[js.Array[String]] = js.undefined
  var i: js.UndefOr[js.Array[String]] = js.undefined
  var img: js.UndefOr[js.Array[String]] = js.undefined
  var ins: js.UndefOr[js.Array[String]] = js.undefined
  var li: js.UndefOr[js.Array[String]] = js.undefined
  var mark: js.UndefOr[js.Array[String]] = js.undefined
  var nav: js.UndefOr[js.Array[String]] = js.undefined
  var ol: js.UndefOr[js.Array[String]] = js.undefined
  var p: js.UndefOr[js.Array[String]] = js.undefined
  var pre: js.UndefOr[js.Array[String]] = js.undefined
  var s: js.UndefOr[js.Array[String]] = js.undefined
  var section: js.UndefOr[js.Array[String]] = js.undefined
  var small: js.UndefOr[js.Array[String]] = js.undefined
  var span: js.UndefOr[js.Array[String]] = js.undefined
  var strong: js.UndefOr[js.Array[String]] = js.undefined
  var sub: js.UndefOr[js.Array[String]] = js.undefined
  var sup: js.UndefOr[js.Array[String]] = js.undefined
  var table: js.UndefOr[js.Array[String]] = js.undefined
  var tbody: js.UndefOr[js.Array[String]] = js.undefined
  var td: js.UndefOr[js.Array[String]] = js.undefined
  var tfoot: js.UndefOr[js.Array[String]] = js.undefined
  var th: js.UndefOr[js.Array[String]] = js.undefined
  var thead: js.UndefOr[js.Array[String]] = js.undefined
  var tr: js.UndefOr[js.Array[String]] = js.undefined
  var tt: js.UndefOr[js.Array[String]] = js.undefined
  var u: js.UndefOr[js.Array[String]] = js.undefined
  var ul: js.UndefOr[js.Array[String]] = js.undefined
  var video: js.UndefOr[js.Array[String]] = js.undefined
}

object IWhiteList {
  @scala.inline
  def apply(
    a: js.Array[String] = null,
    abbr: js.Array[String] = null,
    address: js.Array[String] = null,
    area: js.Array[String] = null,
    article: js.Array[String] = null,
    aside: js.Array[String] = null,
    audio: js.Array[String] = null,
    b: js.Array[String] = null,
    bdi: js.Array[String] = null,
    bdo: js.Array[String] = null,
    big: js.Array[String] = null,
    blockquote: js.Array[String] = null,
    br: js.Array[String] = null,
    caption: js.Array[String] = null,
    center: js.Array[String] = null,
    cite: js.Array[String] = null,
    code: js.Array[String] = null,
    col: js.Array[String] = null,
    colgroup: js.Array[String] = null,
    dd: js.Array[String] = null,
    del: js.Array[String] = null,
    details: js.Array[String] = null,
    div: js.Array[String] = null,
    dl: js.Array[String] = null,
    dt: js.Array[String] = null,
    em: js.Array[String] = null,
    font: js.Array[String] = null,
    footer: js.Array[String] = null,
    h1: js.Array[String] = null,
    h2: js.Array[String] = null,
    h3: js.Array[String] = null,
    h4: js.Array[String] = null,
    h5: js.Array[String] = null,
    h6: js.Array[String] = null,
    header: js.Array[String] = null,
    hr: js.Array[String] = null,
    i: js.Array[String] = null,
    img: js.Array[String] = null,
    ins: js.Array[String] = null,
    li: js.Array[String] = null,
    mark: js.Array[String] = null,
    nav: js.Array[String] = null,
    ol: js.Array[String] = null,
    p: js.Array[String] = null,
    pre: js.Array[String] = null,
    s: js.Array[String] = null,
    section: js.Array[String] = null,
    small: js.Array[String] = null,
    span: js.Array[String] = null,
    strong: js.Array[String] = null,
    sub: js.Array[String] = null,
    sup: js.Array[String] = null,
    table: js.Array[String] = null,
    tbody: js.Array[String] = null,
    td: js.Array[String] = null,
    tfoot: js.Array[String] = null,
    th: js.Array[String] = null,
    thead: js.Array[String] = null,
    tr: js.Array[String] = null,
    tt: js.Array[String] = null,
    u: js.Array[String] = null,
    ul: js.Array[String] = null,
    video: js.Array[String] = null
  ): IWhiteList = {
    val __obj = js.Dynamic.literal()
    if (a != null) __obj.updateDynamic("a")(a)
    if (abbr != null) __obj.updateDynamic("abbr")(abbr)
    if (address != null) __obj.updateDynamic("address")(address)
    if (area != null) __obj.updateDynamic("area")(area)
    if (article != null) __obj.updateDynamic("article")(article)
    if (aside != null) __obj.updateDynamic("aside")(aside)
    if (audio != null) __obj.updateDynamic("audio")(audio)
    if (b != null) __obj.updateDynamic("b")(b)
    if (bdi != null) __obj.updateDynamic("bdi")(bdi)
    if (bdo != null) __obj.updateDynamic("bdo")(bdo)
    if (big != null) __obj.updateDynamic("big")(big)
    if (blockquote != null) __obj.updateDynamic("blockquote")(blockquote)
    if (br != null) __obj.updateDynamic("br")(br)
    if (caption != null) __obj.updateDynamic("caption")(caption)
    if (center != null) __obj.updateDynamic("center")(center)
    if (cite != null) __obj.updateDynamic("cite")(cite)
    if (code != null) __obj.updateDynamic("code")(code)
    if (col != null) __obj.updateDynamic("col")(col)
    if (colgroup != null) __obj.updateDynamic("colgroup")(colgroup)
    if (dd != null) __obj.updateDynamic("dd")(dd)
    if (del != null) __obj.updateDynamic("del")(del)
    if (details != null) __obj.updateDynamic("details")(details)
    if (div != null) __obj.updateDynamic("div")(div)
    if (dl != null) __obj.updateDynamic("dl")(dl)
    if (dt != null) __obj.updateDynamic("dt")(dt)
    if (em != null) __obj.updateDynamic("em")(em)
    if (font != null) __obj.updateDynamic("font")(font)
    if (footer != null) __obj.updateDynamic("footer")(footer)
    if (h1 != null) __obj.updateDynamic("h1")(h1)
    if (h2 != null) __obj.updateDynamic("h2")(h2)
    if (h3 != null) __obj.updateDynamic("h3")(h3)
    if (h4 != null) __obj.updateDynamic("h4")(h4)
    if (h5 != null) __obj.updateDynamic("h5")(h5)
    if (h6 != null) __obj.updateDynamic("h6")(h6)
    if (header != null) __obj.updateDynamic("header")(header)
    if (hr != null) __obj.updateDynamic("hr")(hr)
    if (i != null) __obj.updateDynamic("i")(i)
    if (img != null) __obj.updateDynamic("img")(img)
    if (ins != null) __obj.updateDynamic("ins")(ins)
    if (li != null) __obj.updateDynamic("li")(li)
    if (mark != null) __obj.updateDynamic("mark")(mark)
    if (nav != null) __obj.updateDynamic("nav")(nav)
    if (ol != null) __obj.updateDynamic("ol")(ol)
    if (p != null) __obj.updateDynamic("p")(p)
    if (pre != null) __obj.updateDynamic("pre")(pre)
    if (s != null) __obj.updateDynamic("s")(s)
    if (section != null) __obj.updateDynamic("section")(section)
    if (small != null) __obj.updateDynamic("small")(small)
    if (span != null) __obj.updateDynamic("span")(span)
    if (strong != null) __obj.updateDynamic("strong")(strong)
    if (sub != null) __obj.updateDynamic("sub")(sub)
    if (sup != null) __obj.updateDynamic("sup")(sup)
    if (table != null) __obj.updateDynamic("table")(table)
    if (tbody != null) __obj.updateDynamic("tbody")(tbody)
    if (td != null) __obj.updateDynamic("td")(td)
    if (tfoot != null) __obj.updateDynamic("tfoot")(tfoot)
    if (th != null) __obj.updateDynamic("th")(th)
    if (thead != null) __obj.updateDynamic("thead")(thead)
    if (tr != null) __obj.updateDynamic("tr")(tr)
    if (tt != null) __obj.updateDynamic("tt")(tt)
    if (u != null) __obj.updateDynamic("u")(u)
    if (ul != null) __obj.updateDynamic("ul")(ul)
    if (video != null) __obj.updateDynamic("video")(video)
    __obj.asInstanceOf[IWhiteList]
  }
}

