package typings.officeDashUiDashFabricDashReact

import typings.atUifabricFoundation.libThemeProviderMod.IThemeProviderProps
import typings.atUifabricUtilities.libCustomizationsCustomizerDotTypesMod.ICustomizerProps
import typings.atUifabricUtilities.libDelayedRenderMod.IDelayedRenderProps
import typings.officeDashUiDashFabricDashReact.libComponentsActivityItemActivityItemDotTypesMod.IActivityItemProps
import typings.officeDashUiDashFabricDashReact.libComponentsAnnouncedAnnouncedDotTypesMod.IAnnouncedProps
import typings.officeDashUiDashFabricDashReact.libComponentsAutofillAutofillDotTypesMod.IAutofillProps
import typings.officeDashUiDashFabricDashReact.libComponentsBreadcrumbBreadcrumbDotTypesMod.IBreadcrumbProps
import typings.officeDashUiDashFabricDashReact.libComponentsButtonBaseButtonMod.IBaseButtonProps
import typings.officeDashUiDashFabricDashReact.libComponentsButtonButtonDotTypesMod.IButtonProps
import typings.officeDashUiDashFabricDashReact.libComponentsCalendarCalendarDotTypesMod.ICalendarProps
import typings.officeDashUiDashFabricDashReact.libComponentsCalloutCalloutDotTypesMod.ICalloutProps
import typings.officeDashUiDashFabricDashReact.libComponentsCalloutFocusTrapCalloutDotTypesMod.IFocusTrapCalloutProps
import typings.officeDashUiDashFabricDashReact.libComponentsCheckCheckDotTypesMod.ICheckProps
import typings.officeDashUiDashFabricDashReact.libComponentsCheckboxCheckboxDotTypesMod.ICheckboxProps
import typings.officeDashUiDashFabricDashReact.libComponentsChoiceGroupChoiceGroupDotTypesMod.IChoiceGroupProps
import typings.officeDashUiDashFabricDashReact.libComponentsChoiceGroupChoiceGroupOptionChoiceGroupOptionDotTypesMod.IChoiceGroupOptionProps
import typings.officeDashUiDashFabricDashReact.libComponentsCoachmarkCoachmarkDotTypesMod.ICoachmarkProps
import typings.officeDashUiDashFabricDashReact.libComponentsCoachmarkPositioningContainerPositioningContainerDotTypesMod.IPositioningContainerProps
import typings.officeDashUiDashFabricDashReact.libComponentsColorPickerColorPickerDotTypesMod.IColorPickerProps
import typings.officeDashUiDashFabricDashReact.libComponentsComboBoxComboBoxDotTypesMod.IComboBoxProps
import typings.officeDashUiDashFabricDashReact.libComponentsCommandBarCommandBarDotTypesMod.ICommandBarProps
import typings.officeDashUiDashFabricDashReact.libComponentsContextualMenuContextualMenuDotTypesMod.IContextualMenuProps
import typings.officeDashUiDashFabricDashReact.libComponentsContextualMenuContextualMenuItemDotTypesMod.IContextualMenuItemProps
import typings.officeDashUiDashFabricDashReact.libComponentsDatePickerDatePickerDotTypesMod.IDatePickerProps
import typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsColumnDotTypesMod.IDetailsColumnProps
import typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsHeaderDotTypesMod.IDetailsHeaderBaseProps
import typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsListDotTypesMod.IDetailsListProps
import typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsRowCheckDotTypesMod.IDetailsRowCheckProps
import typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsRowDotTypesMod.IDetailsRowBaseProps
import typings.officeDashUiDashFabricDashReact.libComponentsDetailsListShimmeredDetailsListDotTypesMod.IShimmeredDetailsListProps
import typings.officeDashUiDashFabricDashReact.libComponentsDialogDialogContentDotTypesMod.IDialogContentProps
import typings.officeDashUiDashFabricDashReact.libComponentsDialogDialogDotTypesMod.IDialogProps
import typings.officeDashUiDashFabricDashReact.libComponentsDialogDialogFooterDotTypesMod.IDialogFooterProps
import typings.officeDashUiDashFabricDashReact.libComponentsDividerVerticalDividerDotTypesMod.IVerticalDividerProps
import typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardActionsDotTypesMod.IDocumentCardActionsProps
import typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardActivityDotTypesMod.IDocumentCardActivityProps
import typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardDetailsDotTypesMod.IDocumentCardDetailsProps
import typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardDotTypesMod.IDocumentCardProps
import typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardImageDotTypesMod.IDocumentCardImageProps
import typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardLocationDotTypesMod.IDocumentCardLocationProps
import typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardLogoDotTypesMod.IDocumentCardLogoProps
import typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardPreviewDotTypesMod.IDocumentCardPreviewProps
import typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardStatusDotTypesMod.IDocumentCardStatusProps
import typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardTitleDotTypesMod.IDocumentCardTitleProps
import typings.officeDashUiDashFabricDashReact.libComponentsDropdownDropdownDotBaseMod.IDropdownInternalProps
import typings.officeDashUiDashFabricDashReact.libComponentsDropdownDropdownDotTypesMod.IDropdownProps
import typings.officeDashUiDashFabricDashReact.libComponentsExtendedPickerPeoplePickerExtendedPeoplePickerMod.IExtendedPeoplePickerProps
import typings.officeDashUiDashFabricDashReact.libComponentsFabricFabricDotTypesMod.IFabricProps
import typings.officeDashUiDashFabricDashReact.libComponentsFacepileFacepileDotTypesMod.IFacepileProps
import typings.officeDashUiDashFabricDashReact.libComponentsFloatingPickerPeoplePickerFloatingPeoplePickerMod.IPeopleFloatingPickerProps
import typings.officeDashUiDashFabricDashReact.libComponentsFloatingPickerSuggestionsSuggestionsDotTypesMod.ISuggestionsControlProps
import typings.officeDashUiDashFabricDashReact.libComponentsFloatingPickerSuggestionsSuggestionsDotTypesMod.ISuggestionsCoreProps
import typings.officeDashUiDashFabricDashReact.libComponentsFloatingPickerSuggestionsSuggestionsDotTypesMod.ISuggestionsHeaderFooterItemProps
import typings.officeDashUiDashFabricDashReact.libComponentsFocusTrapZoneFocusTrapZoneDotTypesMod.IFocusTrapZoneProps
import typings.officeDashUiDashFabricDashReact.libComponentsFocusZoneFocusZoneDotTypesMod.IFocusZoneProps
import typings.officeDashUiDashFabricDashReact.libComponentsGroupedListGroupFooterDotTypesMod.IGroupFooterProps
import typings.officeDashUiDashFabricDashReact.libComponentsGroupedListGroupHeaderDotTypesMod.IGroupHeaderProps
import typings.officeDashUiDashFabricDashReact.libComponentsGroupedListGroupShowAllDotTypesMod.IGroupShowAllProps
import typings.officeDashUiDashFabricDashReact.libComponentsGroupedListGroupSpacerDotTypesMod.IGroupSpacerProps
import typings.officeDashUiDashFabricDashReact.libComponentsGroupedListGroupedListDotTypesMod.IGroupedListProps
import typings.officeDashUiDashFabricDashReact.libComponentsHoverCardExpandingCardDotTypesMod.IExpandingCardProps
import typings.officeDashUiDashFabricDashReact.libComponentsHoverCardHoverCardDotTypesMod.IHoverCardProps
import typings.officeDashUiDashFabricDashReact.libComponentsHoverCardPlainCardPlainCardDotTypesMod.IPlainCardProps
import typings.officeDashUiDashFabricDashReact.libComponentsIconIconDotTypesMod.IFontIconProps
import typings.officeDashUiDashFabricDashReact.libComponentsIconIconDotTypesMod.IIconProps
import typings.officeDashUiDashFabricDashReact.libComponentsIconIconDotTypesMod.IImageIconProps
import typings.officeDashUiDashFabricDashReact.libComponentsImageImageDotTypesMod.IImageProps
import typings.officeDashUiDashFabricDashReact.libComponentsKeytipKeytipDotTypesMod.IKeytipProps
import typings.officeDashUiDashFabricDashReact.libComponentsKeytipLayerKeytipLayerDotTypesMod.IKeytipLayerProps
import typings.officeDashUiDashFabricDashReact.libComponentsLabelLabelDotTypesMod.ILabelProps
import typings.officeDashUiDashFabricDashReact.libComponentsLayerLayerDotTypesMod.ILayerProps
import typings.officeDashUiDashFabricDashReact.libComponentsLayerLayerHostDotTypesMod.ILayerHostProps
import typings.officeDashUiDashFabricDashReact.libComponentsLinkLinkDotTypesMod.ILinkProps
import typings.officeDashUiDashFabricDashReact.libComponentsListListDotTypesMod.IListProps
import typings.officeDashUiDashFabricDashReact.libComponentsMarqueeSelectionMarqueeSelectionDotTypesMod.IMarqueeSelectionProps
import typings.officeDashUiDashFabricDashReact.libComponentsMessageBarMessageBarDotTypesMod.IMessageBarProps
import typings.officeDashUiDashFabricDashReact.libComponentsModalModalDotTypesMod.IModalProps
import typings.officeDashUiDashFabricDashReact.libComponentsNavNavDotTypesMod.INavProps
import typings.officeDashUiDashFabricDashReact.libComponentsOverflowSetOverflowSetDotTypesMod.IOverflowSetProps
import typings.officeDashUiDashFabricDashReact.libComponentsOverlayOverlayDotTypesMod.IOverlayProps
import typings.officeDashUiDashFabricDashReact.libComponentsPanelPanelDotTypesMod.IPanelProps
import typings.officeDashUiDashFabricDashReact.libComponentsPersonaPersonaDotTypesMod.IPersonaCoinProps
import typings.officeDashUiDashFabricDashReact.libComponentsPersonaPersonaDotTypesMod.IPersonaProps
import typings.officeDashUiDashFabricDashReact.libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemDotTypesMod.IPeoplePickerItemSelectedProps
import typings.officeDashUiDashFabricDashReact.libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemDotTypesMod.IPeoplePickerItemSuggestionProps
import typings.officeDashUiDashFabricDashReact.libComponentsPickersPeoplePickerPeoplePickerMod.IPeoplePickerProps
import typings.officeDashUiDashFabricDashReact.libComponentsPickersSuggestionsSuggestionsDotTypesMod.ISuggestionsProps
import typings.officeDashUiDashFabricDashReact.libComponentsPickersSuggestionsSuggestionsItemDotTypesMod.ISuggestionItemProps
import typings.officeDashUiDashFabricDashReact.libComponentsPickersTagPickerTagPickerDotTypesMod.ITagItemProps
import typings.officeDashUiDashFabricDashReact.libComponentsPickersTagPickerTagPickerDotTypesMod.ITagItemSuggestionProps
import typings.officeDashUiDashFabricDashReact.libComponentsPickersTagPickerTagPickerDotTypesMod.ITagPickerProps
import typings.officeDashUiDashFabricDashReact.libComponentsPivotPivotDotTypesMod.IPivotProps
import typings.officeDashUiDashFabricDashReact.libComponentsPivotPivotItemDotTypesMod.IPivotItemProps
import typings.officeDashUiDashFabricDashReact.libComponentsPopupPopupDotTypesMod.IPopupProps
import typings.officeDashUiDashFabricDashReact.libComponentsProgressIndicatorProgressIndicatorDotTypesMod.IProgressIndicatorProps
import typings.officeDashUiDashFabricDashReact.libComponentsRatingRatingDotTypesMod.IRatingProps
import typings.officeDashUiDashFabricDashReact.libComponentsResizeGroupResizeGroupDotTypesMod.IResizeGroupProps
import typings.officeDashUiDashFabricDashReact.libComponentsScrollablePaneScrollablePaneDotTypesMod.IScrollablePaneProps
import typings.officeDashUiDashFabricDashReact.libComponentsSearchBoxSearchBoxDotTypesMod.ISearchBoxProps
import typings.officeDashUiDashFabricDashReact.libComponentsSelectedItemsListSelectedPeopleListSelectedPeopleListMod.ISelectedPeopleItemProps
import typings.officeDashUiDashFabricDashReact.libComponentsSelectedItemsListSelectedPeopleListSelectedPeopleListMod.ISelectedPeopleProps
import typings.officeDashUiDashFabricDashReact.libComponentsSeparatorSeparatorDotTypesMod.ISeparatorProps
import typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerCircleShimmerCircleDotTypesMod.IShimmerCircleProps
import typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerDotTypesMod.IShimmerProps
import typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerElementsGroupShimmerElementsGroupDotTypesMod.IShimmerElementsGroupProps
import typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerGapShimmerGapDotTypesMod.IShimmerGapProps
import typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerLineShimmerLineDotTypesMod.IShimmerLineProps
import typings.officeDashUiDashFabricDashReact.libComponentsSliderSliderDotTypesMod.ISliderProps
import typings.officeDashUiDashFabricDashReact.libComponentsSpinButtonSpinButtonDotTypesMod.ISpinButtonProps
import typings.officeDashUiDashFabricDashReact.libComponentsSpinnerSpinnerDotTypesMod.ISpinnerProps
import typings.officeDashUiDashFabricDashReact.libComponentsStackStackItemStackItemDotTypesMod.IStackItemProps
import typings.officeDashUiDashFabricDashReact.libComponentsStickyStickyDotTypesMod.IStickyProps
import typings.officeDashUiDashFabricDashReact.libComponentsSwatchColorPickerColorPickerGridCellDotTypesMod.IColorPickerGridCellProps
import typings.officeDashUiDashFabricDashReact.libComponentsSwatchColorPickerSwatchColorPickerDotTypesMod.ISwatchColorPickerProps
import typings.officeDashUiDashFabricDashReact.libComponentsTeachingBubbleTeachingBubbleDotTypesMod.ITeachingBubbleProps
import typings.officeDashUiDashFabricDashReact.libComponentsTextFieldTextFieldDotTypesMod.ITextFieldProps
import typings.officeDashUiDashFabricDashReact.libComponentsTextTextDotTypesMod.ITextProps
import typings.officeDashUiDashFabricDashReact.libComponentsToggleToggleDotTypesMod.IToggleProps
import typings.officeDashUiDashFabricDashReact.libComponentsTooltipTooltipDotTypesMod.ITooltipProps
import typings.officeDashUiDashFabricDashReact.libComponentsTooltipTooltipHostDotTypesMod.ITooltipHostProps
import typings.officeDashUiDashFabricDashReact.libUtilitiesGridGridDotTypesMod.IGridProps
import typings.officeDashUiDashFabricDashReact.libUtilitiesSelectionSelectionZoneMod.ISelectionZoneProps
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait officeDashUiDashFabricDashReactProps {
  @scala.inline
  def ActionButtonProps: IButtonProps.type = typings.officeDashUiDashFabricDashReact.libComponentsButtonButtonDotTypesMod.IButtonProps
  type ActionButtonProps = IButtonProps
  @scala.inline
  def ActivityItemProps: IActivityItemProps.type = typings.officeDashUiDashFabricDashReact.libComponentsActivityItemActivityItemDotTypesMod.IActivityItemProps
  type ActivityItemProps = IActivityItemProps
  @scala.inline
  def AnnouncedProps: IAnnouncedProps.type = typings.officeDashUiDashFabricDashReact.libComponentsAnnouncedAnnouncedDotTypesMod.IAnnouncedProps
  type AnnouncedProps = IAnnouncedProps
  @scala.inline
  def AnnouncedBaseProps: IAnnouncedProps.type = typings.officeDashUiDashFabricDashReact.libComponentsAnnouncedAnnouncedDotTypesMod.IAnnouncedProps
  type AnnouncedBaseProps = IAnnouncedProps
  @scala.inline
  def AutofillProps: IAutofillProps.type = typings.officeDashUiDashFabricDashReact.libComponentsAutofillAutofillDotTypesMod.IAutofillProps
  type AutofillProps = IAutofillProps
  @scala.inline
  def BaseAutoFillProps: IAutofillProps.type = typings.officeDashUiDashFabricDashReact.libComponentsAutofillAutofillDotTypesMod.IAutofillProps
  type BaseAutoFillProps = IAutofillProps
  @scala.inline
  def BaseButtonProps: IBaseButtonProps.type = typings.officeDashUiDashFabricDashReact.libComponentsButtonBaseButtonMod.IBaseButtonProps
  type BaseButtonProps = IBaseButtonProps
  type BaseExtendedPeoplePickerProps = IExtendedPeoplePickerProps
  type BaseFloatingPeoplePickerProps = IPeopleFloatingPickerProps
  type BasePeoplePickerProps = IPeoplePickerProps
  @scala.inline
  def BasePeopleSelectedItemsListProps: ISelectedPeopleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSelectedItemsListSelectedPeopleListSelectedPeopleListMod.ISelectedPeopleProps
  type BasePeopleSelectedItemsListProps = ISelectedPeopleProps
  @scala.inline
  def BreadcrumbProps: IBreadcrumbProps.type = typings.officeDashUiDashFabricDashReact.libComponentsBreadcrumbBreadcrumbDotTypesMod.IBreadcrumbProps
  type BreadcrumbProps = IBreadcrumbProps
  @scala.inline
  def BreadcrumbBaseProps: IBreadcrumbProps.type = typings.officeDashUiDashFabricDashReact.libComponentsBreadcrumbBreadcrumbDotTypesMod.IBreadcrumbProps
  type BreadcrumbBaseProps = IBreadcrumbProps
  @scala.inline
  def ButtonProps: IButtonProps.type = typings.officeDashUiDashFabricDashReact.libComponentsButtonButtonDotTypesMod.IButtonProps
  type ButtonProps = IButtonProps
  @scala.inline
  def CalendarProps: ICalendarProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCalendarCalendarDotTypesMod.ICalendarProps
  type CalendarProps = ICalendarProps
  @scala.inline
  def CalloutProps: ICalloutProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCalloutCalloutDotTypesMod.ICalloutProps
  type CalloutProps = ICalloutProps
  @scala.inline
  def CalloutContentBaseProps: ICalloutProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCalloutCalloutDotTypesMod.ICalloutProps
  type CalloutContentBaseProps = ICalloutProps
  @scala.inline
  def CheckProps: ICheckProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCheckCheckDotTypesMod.ICheckProps
  type CheckProps = ICheckProps
  @scala.inline
  def CheckBaseProps: ICheckProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCheckCheckDotTypesMod.ICheckProps
  type CheckBaseProps = ICheckProps
  @scala.inline
  def CheckboxProps: ICheckboxProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCheckboxCheckboxDotTypesMod.ICheckboxProps
  type CheckboxProps = ICheckboxProps
  @scala.inline
  def CheckboxBaseProps: ICheckboxProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCheckboxCheckboxDotTypesMod.ICheckboxProps
  type CheckboxBaseProps = ICheckboxProps
  @scala.inline
  def ChoiceGroupProps: IChoiceGroupProps.type = typings.officeDashUiDashFabricDashReact.libComponentsChoiceGroupChoiceGroupDotTypesMod.IChoiceGroupProps
  type ChoiceGroupProps = IChoiceGroupProps
  @scala.inline
  def ChoiceGroupBaseProps: IChoiceGroupProps.type = typings.officeDashUiDashFabricDashReact.libComponentsChoiceGroupChoiceGroupDotTypesMod.IChoiceGroupProps
  type ChoiceGroupBaseProps = IChoiceGroupProps
  @scala.inline
  def ChoiceGroupOptionProps: IChoiceGroupOptionProps.type = typings.officeDashUiDashFabricDashReact.libComponentsChoiceGroupChoiceGroupOptionChoiceGroupOptionDotTypesMod.IChoiceGroupOptionProps
  type ChoiceGroupOptionProps = IChoiceGroupOptionProps
  @scala.inline
  def CoachmarkProps: ICoachmarkProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCoachmarkCoachmarkDotTypesMod.ICoachmarkProps
  type CoachmarkProps = ICoachmarkProps
  @scala.inline
  def CoachmarkBaseProps: ICoachmarkProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCoachmarkCoachmarkDotTypesMod.ICoachmarkProps
  type CoachmarkBaseProps = ICoachmarkProps
  @scala.inline
  def ColorPickerProps: IColorPickerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsColorPickerColorPickerDotTypesMod.IColorPickerProps
  type ColorPickerProps = IColorPickerProps
  @scala.inline
  def ColorPickerBaseProps: IColorPickerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsColorPickerColorPickerDotTypesMod.IColorPickerProps
  type ColorPickerBaseProps = IColorPickerProps
  @scala.inline
  def ColorPickerGridCellProps: IColorPickerGridCellProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSwatchColorPickerColorPickerGridCellDotTypesMod.IColorPickerGridCellProps
  type ColorPickerGridCellProps = IColorPickerGridCellProps
  @scala.inline
  def ColorPickerGridCellBaseProps: IColorPickerGridCellProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSwatchColorPickerColorPickerGridCellDotTypesMod.IColorPickerGridCellProps
  type ColorPickerGridCellBaseProps = IColorPickerGridCellProps
  @scala.inline
  def ComboBoxProps: IComboBoxProps.type = typings.officeDashUiDashFabricDashReact.libComponentsComboBoxComboBoxDotTypesMod.IComboBoxProps
  type ComboBoxProps = IComboBoxProps
  @scala.inline
  def CommandBarProps: ICommandBarProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCommandBarCommandBarDotTypesMod.ICommandBarProps
  type CommandBarProps = ICommandBarProps
  @scala.inline
  def CommandBarBaseProps: ICommandBarProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCommandBarCommandBarDotTypesMod.ICommandBarProps
  type CommandBarBaseProps = ICommandBarProps
  @scala.inline
  def CommandBarButtonProps: IButtonProps.type = typings.officeDashUiDashFabricDashReact.libComponentsButtonButtonDotTypesMod.IButtonProps
  type CommandBarButtonProps = IButtonProps
  type CompactPeoplePickerProps = IPeoplePickerProps
  type CompactPeoplePickerBaseProps = IPeoplePickerProps
  @scala.inline
  def CompoundButtonProps: IButtonProps.type = typings.officeDashUiDashFabricDashReact.libComponentsButtonButtonDotTypesMod.IButtonProps
  type CompoundButtonProps = IButtonProps
  @scala.inline
  def ContextualMenuProps: IContextualMenuProps.type = typings.officeDashUiDashFabricDashReact.libComponentsContextualMenuContextualMenuDotTypesMod.IContextualMenuProps
  type ContextualMenuProps = IContextualMenuProps
  @scala.inline
  def ContextualMenuBaseProps: IContextualMenuProps.type = typings.officeDashUiDashFabricDashReact.libComponentsContextualMenuContextualMenuDotTypesMod.IContextualMenuProps
  type ContextualMenuBaseProps = IContextualMenuProps
  @scala.inline
  def ContextualMenuItemProps: IContextualMenuItemProps.type = typings.officeDashUiDashFabricDashReact.libComponentsContextualMenuContextualMenuItemDotTypesMod.IContextualMenuItemProps
  type ContextualMenuItemProps = IContextualMenuItemProps
  @scala.inline
  def ContextualMenuItemBaseProps: IContextualMenuItemProps.type = typings.officeDashUiDashFabricDashReact.libComponentsContextualMenuContextualMenuItemDotTypesMod.IContextualMenuItemProps
  type ContextualMenuItemBaseProps = IContextualMenuItemProps
  @scala.inline
  def CustomizerProps: ICustomizerProps.type = typings.atUifabricUtilities.libCustomizationsCustomizerDotTypesMod.ICustomizerProps
  type CustomizerProps = ICustomizerProps
  @scala.inline
  def DatePickerProps: IDatePickerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDatePickerDatePickerDotTypesMod.IDatePickerProps
  type DatePickerProps = IDatePickerProps
  @scala.inline
  def DatePickerBaseProps: IDatePickerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDatePickerDatePickerDotTypesMod.IDatePickerProps
  type DatePickerBaseProps = IDatePickerProps
  @scala.inline
  def DefaultButtonProps: IButtonProps.type = typings.officeDashUiDashFabricDashReact.libComponentsButtonButtonDotTypesMod.IButtonProps
  type DefaultButtonProps = IButtonProps
  @scala.inline
  def DelayedRenderProps: IDelayedRenderProps.type = typings.atUifabricUtilities.libDelayedRenderMod.IDelayedRenderProps
  type DelayedRenderProps = IDelayedRenderProps
  @scala.inline
  def DetailsColumnBaseProps: IDetailsColumnProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsColumnDotTypesMod.IDetailsColumnProps
  type DetailsColumnBaseProps = IDetailsColumnProps
  @scala.inline
  def DetailsHeaderProps: IDetailsHeaderBaseProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsHeaderDotTypesMod.IDetailsHeaderBaseProps
  type DetailsHeaderProps = IDetailsHeaderBaseProps
  @scala.inline
  def DetailsHeaderBaseProps: IDetailsHeaderBaseProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsHeaderDotTypesMod.IDetailsHeaderBaseProps
  type DetailsHeaderBaseProps = IDetailsHeaderBaseProps
  @scala.inline
  def DetailsListProps: IDetailsListProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsListDotTypesMod.IDetailsListProps
  type DetailsListProps = IDetailsListProps
  @scala.inline
  def DetailsListBaseProps: IDetailsListProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsListDotTypesMod.IDetailsListProps
  type DetailsListBaseProps = IDetailsListProps
  @scala.inline
  def DetailsRowProps: IDetailsRowBaseProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsRowDotTypesMod.IDetailsRowBaseProps
  type DetailsRowProps = IDetailsRowBaseProps
  @scala.inline
  def DetailsRowBaseProps: IDetailsRowBaseProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsRowDotTypesMod.IDetailsRowBaseProps
  type DetailsRowBaseProps = IDetailsRowBaseProps
  @scala.inline
  def DetailsRowCheckProps: IDetailsRowCheckProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsRowCheckDotTypesMod.IDetailsRowCheckProps
  type DetailsRowCheckProps = IDetailsRowCheckProps
  @scala.inline
  def DialogProps: IDialogProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDialogDialogDotTypesMod.IDialogProps
  type DialogProps = IDialogProps
  @scala.inline
  def DialogBaseProps: IDialogProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDialogDialogDotTypesMod.IDialogProps
  type DialogBaseProps = IDialogProps
  @scala.inline
  def DialogContentProps: IDialogContentProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDialogDialogContentDotTypesMod.IDialogContentProps
  type DialogContentProps = IDialogContentProps
  @scala.inline
  def DialogContentBaseProps: IDialogContentProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDialogDialogContentDotTypesMod.IDialogContentProps
  type DialogContentBaseProps = IDialogContentProps
  @scala.inline
  def DialogFooterProps: IDialogFooterProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDialogDialogFooterDotTypesMod.IDialogFooterProps
  type DialogFooterProps = IDialogFooterProps
  @scala.inline
  def DialogFooterBaseProps: IDialogFooterProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDialogDialogFooterDotTypesMod.IDialogFooterProps
  type DialogFooterBaseProps = IDialogFooterProps
  @scala.inline
  def DocumentCardProps: IDocumentCardProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardDotTypesMod.IDocumentCardProps
  type DocumentCardProps = IDocumentCardProps
  @scala.inline
  def DocumentCardActionsProps: IDocumentCardActionsProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardActionsDotTypesMod.IDocumentCardActionsProps
  type DocumentCardActionsProps = IDocumentCardActionsProps
  @scala.inline
  def DocumentCardActionsBaseProps: IDocumentCardActionsProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardActionsDotTypesMod.IDocumentCardActionsProps
  type DocumentCardActionsBaseProps = IDocumentCardActionsProps
  @scala.inline
  def DocumentCardActivityProps: IDocumentCardActivityProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardActivityDotTypesMod.IDocumentCardActivityProps
  type DocumentCardActivityProps = IDocumentCardActivityProps
  @scala.inline
  def DocumentCardActivityBaseProps: IDocumentCardActivityProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardActivityDotTypesMod.IDocumentCardActivityProps
  type DocumentCardActivityBaseProps = IDocumentCardActivityProps
  @scala.inline
  def DocumentCardDetailsProps: IDocumentCardDetailsProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardDetailsDotTypesMod.IDocumentCardDetailsProps
  type DocumentCardDetailsProps = IDocumentCardDetailsProps
  @scala.inline
  def DocumentCardDetailsBaseProps: IDocumentCardDetailsProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardDetailsDotTypesMod.IDocumentCardDetailsProps
  type DocumentCardDetailsBaseProps = IDocumentCardDetailsProps
  @scala.inline
  def DocumentCardImageProps: IDocumentCardImageProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardImageDotTypesMod.IDocumentCardImageProps
  type DocumentCardImageProps = IDocumentCardImageProps
  @scala.inline
  def DocumentCardLocationProps: IDocumentCardLocationProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardLocationDotTypesMod.IDocumentCardLocationProps
  type DocumentCardLocationProps = IDocumentCardLocationProps
  @scala.inline
  def DocumentCardLocationBaseProps: IDocumentCardLocationProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardLocationDotTypesMod.IDocumentCardLocationProps
  type DocumentCardLocationBaseProps = IDocumentCardLocationProps
  @scala.inline
  def DocumentCardLogoProps: IDocumentCardLogoProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardLogoDotTypesMod.IDocumentCardLogoProps
  type DocumentCardLogoProps = IDocumentCardLogoProps
  @scala.inline
  def DocumentCardLogoBaseProps: IDocumentCardLogoProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardLogoDotTypesMod.IDocumentCardLogoProps
  type DocumentCardLogoBaseProps = IDocumentCardLogoProps
  @scala.inline
  def DocumentCardPreviewProps: IDocumentCardPreviewProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardPreviewDotTypesMod.IDocumentCardPreviewProps
  type DocumentCardPreviewProps = IDocumentCardPreviewProps
  @scala.inline
  def DocumentCardStatusProps: IDocumentCardStatusProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardStatusDotTypesMod.IDocumentCardStatusProps
  type DocumentCardStatusProps = IDocumentCardStatusProps
  @scala.inline
  def DocumentCardStatusBaseProps: IDocumentCardStatusProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardStatusDotTypesMod.IDocumentCardStatusProps
  type DocumentCardStatusBaseProps = IDocumentCardStatusProps
  @scala.inline
  def DocumentCardTitleProps: IDocumentCardTitleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardTitleDotTypesMod.IDocumentCardTitleProps
  type DocumentCardTitleProps = IDocumentCardTitleProps
  @scala.inline
  def DocumentCardTitleBaseProps: IDocumentCardTitleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardTitleDotTypesMod.IDocumentCardTitleProps
  type DocumentCardTitleBaseProps = IDocumentCardTitleProps
  @scala.inline
  def DropdownProps: IDropdownProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDropdownDropdownDotTypesMod.IDropdownProps
  type DropdownProps = IDropdownProps
  @scala.inline
  def DropdownBaseProps: IDropdownInternalProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDropdownDropdownDotBaseMod.IDropdownInternalProps
  type DropdownBaseProps = IDropdownInternalProps
  @scala.inline
  def ExpandingCardProps: IExpandingCardProps.type = typings.officeDashUiDashFabricDashReact.libComponentsHoverCardExpandingCardDotTypesMod.IExpandingCardProps
  type ExpandingCardProps = IExpandingCardProps
  @scala.inline
  def ExpandingCardBaseProps: IExpandingCardProps.type = typings.officeDashUiDashFabricDashReact.libComponentsHoverCardExpandingCardDotTypesMod.IExpandingCardProps
  type ExpandingCardBaseProps = IExpandingCardProps
  type ExtendedPeoplePickerProps = IExtendedPeoplePickerProps
  @scala.inline
  def ExtendedSelectedItemProps: ISelectedPeopleItemProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSelectedItemsListSelectedPeopleListSelectedPeopleListMod.ISelectedPeopleItemProps
  type ExtendedSelectedItemProps = ISelectedPeopleItemProps
  @scala.inline
  def FabricProps: IFabricProps.type = typings.officeDashUiDashFabricDashReact.libComponentsFabricFabricDotTypesMod.IFabricProps
  type FabricProps = IFabricProps
  @scala.inline
  def FabricBaseProps: IFabricProps.type = typings.officeDashUiDashFabricDashReact.libComponentsFabricFabricDotTypesMod.IFabricProps
  type FabricBaseProps = IFabricProps
  @scala.inline
  def FacepileProps: IFacepileProps.type = typings.officeDashUiDashFabricDashReact.libComponentsFacepileFacepileDotTypesMod.IFacepileProps
  type FacepileProps = IFacepileProps
  @scala.inline
  def FacepileBaseProps: IFacepileProps.type = typings.officeDashUiDashFabricDashReact.libComponentsFacepileFacepileDotTypesMod.IFacepileProps
  type FacepileBaseProps = IFacepileProps
  type FloatingPeoplePickerProps = IPeopleFloatingPickerProps
  @scala.inline
  def FocusTrapCalloutProps: IFocusTrapCalloutProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCalloutFocusTrapCalloutDotTypesMod.IFocusTrapCalloutProps
  type FocusTrapCalloutProps = IFocusTrapCalloutProps
  @scala.inline
  def FocusTrapZoneProps: IFocusTrapZoneProps.type = typings.officeDashUiDashFabricDashReact.libComponentsFocusTrapZoneFocusTrapZoneDotTypesMod.IFocusTrapZoneProps
  type FocusTrapZoneProps = IFocusTrapZoneProps
  @scala.inline
  def FocusZoneProps: IFocusZoneProps.type = typings.officeDashUiDashFabricDashReact.libComponentsFocusZoneFocusZoneDotTypesMod.IFocusZoneProps
  type FocusZoneProps = IFocusZoneProps
  @scala.inline
  def FontIconProps: IFontIconProps.type = typings.officeDashUiDashFabricDashReact.libComponentsIconIconDotTypesMod.IFontIconProps
  type FontIconProps = IFontIconProps
  @scala.inline
  def GridProps: IGridProps.type = typings.officeDashUiDashFabricDashReact.libUtilitiesGridGridDotTypesMod.IGridProps
  type GridProps = IGridProps
  @scala.inline
  def GroupFooterProps: IGroupFooterProps.type = typings.officeDashUiDashFabricDashReact.libComponentsGroupedListGroupFooterDotTypesMod.IGroupFooterProps
  type GroupFooterProps = IGroupFooterProps
  @scala.inline
  def GroupHeaderProps: IGroupHeaderProps.type = typings.officeDashUiDashFabricDashReact.libComponentsGroupedListGroupHeaderDotTypesMod.IGroupHeaderProps
  type GroupHeaderProps = IGroupHeaderProps
  @scala.inline
  def GroupShowAllProps: IGroupShowAllProps.type = typings.officeDashUiDashFabricDashReact.libComponentsGroupedListGroupShowAllDotTypesMod.IGroupShowAllProps
  type GroupShowAllProps = IGroupShowAllProps
  @scala.inline
  def GroupSpacerProps: IGroupSpacerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsGroupedListGroupSpacerDotTypesMod.IGroupSpacerProps
  type GroupSpacerProps = IGroupSpacerProps
  type GroupedListProps = IGroupedListProps
  type GroupedListBaseProps = IGroupedListProps
  @scala.inline
  def HoverCardProps: IHoverCardProps.type = typings.officeDashUiDashFabricDashReact.libComponentsHoverCardHoverCardDotTypesMod.IHoverCardProps
  type HoverCardProps = IHoverCardProps
  @scala.inline
  def HoverCardBaseProps: IHoverCardProps.type = typings.officeDashUiDashFabricDashReact.libComponentsHoverCardHoverCardDotTypesMod.IHoverCardProps
  type HoverCardBaseProps = IHoverCardProps
  @scala.inline
  def IconProps: IIconProps.type = typings.officeDashUiDashFabricDashReact.libComponentsIconIconDotTypesMod.IIconProps
  type IconProps = IIconProps
  @scala.inline
  def IconBaseProps: IIconProps.type = typings.officeDashUiDashFabricDashReact.libComponentsIconIconDotTypesMod.IIconProps
  type IconBaseProps = IIconProps
  @scala.inline
  def IconButtonProps: IButtonProps.type = typings.officeDashUiDashFabricDashReact.libComponentsButtonButtonDotTypesMod.IButtonProps
  type IconButtonProps = IButtonProps
  @scala.inline
  def ImageProps: IImageProps.type = typings.officeDashUiDashFabricDashReact.libComponentsImageImageDotTypesMod.IImageProps
  type ImageProps = IImageProps
  @scala.inline
  def ImageBaseProps: IImageProps.type = typings.officeDashUiDashFabricDashReact.libComponentsImageImageDotTypesMod.IImageProps
  type ImageBaseProps = IImageProps
  @scala.inline
  def ImageIconProps: IImageIconProps.type = typings.officeDashUiDashFabricDashReact.libComponentsIconIconDotTypesMod.IImageIconProps
  type ImageIconProps = IImageIconProps
  @scala.inline
  def KeytipProps: IKeytipProps.type = typings.officeDashUiDashFabricDashReact.libComponentsKeytipKeytipDotTypesMod.IKeytipProps
  type KeytipProps = IKeytipProps
  @scala.inline
  def KeytipLayerProps: IKeytipLayerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsKeytipLayerKeytipLayerDotTypesMod.IKeytipLayerProps
  type KeytipLayerProps = IKeytipLayerProps
  @scala.inline
  def KeytipLayerBaseProps: IKeytipLayerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsKeytipLayerKeytipLayerDotTypesMod.IKeytipLayerProps
  type KeytipLayerBaseProps = IKeytipLayerProps
  @scala.inline
  def LabelProps: ILabelProps.type = typings.officeDashUiDashFabricDashReact.libComponentsLabelLabelDotTypesMod.ILabelProps
  type LabelProps = ILabelProps
  @scala.inline
  def LabelBaseProps: ILabelProps.type = typings.officeDashUiDashFabricDashReact.libComponentsLabelLabelDotTypesMod.ILabelProps
  type LabelBaseProps = ILabelProps
  @scala.inline
  def LayerProps: ILayerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsLayerLayerDotTypesMod.ILayerProps
  type LayerProps = ILayerProps
  @scala.inline
  def LayerBaseProps: ILayerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsLayerLayerDotTypesMod.ILayerProps
  type LayerBaseProps = ILayerProps
  @scala.inline
  def LayerHostProps: ILayerHostProps.type = typings.officeDashUiDashFabricDashReact.libComponentsLayerLayerHostDotTypesMod.ILayerHostProps
  type LayerHostProps = ILayerHostProps
  @scala.inline
  def LinkProps: ILinkProps.type = typings.officeDashUiDashFabricDashReact.libComponentsLinkLinkDotTypesMod.ILinkProps
  type LinkProps = ILinkProps
  @scala.inline
  def LinkBaseProps: ILinkProps.type = typings.officeDashUiDashFabricDashReact.libComponentsLinkLinkDotTypesMod.ILinkProps
  type LinkBaseProps = ILinkProps
  @scala.inline
  def ListProps: IListProps.type = typings.officeDashUiDashFabricDashReact.libComponentsListListDotTypesMod.IListProps
  type ListProps[T] = IListProps[T]
  type ListPeoplePickerProps = IPeoplePickerProps
  type ListPeoplePickerBaseProps = IPeoplePickerProps
  @scala.inline
  def MarqueeSelectionProps: IMarqueeSelectionProps.type = typings.officeDashUiDashFabricDashReact.libComponentsMarqueeSelectionMarqueeSelectionDotTypesMod.IMarqueeSelectionProps
  type MarqueeSelectionProps = IMarqueeSelectionProps
  @scala.inline
  def MaskedTextFieldProps: ITextFieldProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTextFieldTextFieldDotTypesMod.ITextFieldProps
  type MaskedTextFieldProps = ITextFieldProps
  type MemberListPeoplePickerProps = IPeoplePickerProps
  @scala.inline
  def MessageBarProps: IMessageBarProps.type = typings.officeDashUiDashFabricDashReact.libComponentsMessageBarMessageBarDotTypesMod.IMessageBarProps
  type MessageBarProps = IMessageBarProps
  @scala.inline
  def MessageBarBaseProps: IMessageBarProps.type = typings.officeDashUiDashFabricDashReact.libComponentsMessageBarMessageBarDotTypesMod.IMessageBarProps
  type MessageBarBaseProps = IMessageBarProps
  @scala.inline
  def MessageBarButtonProps: IButtonProps.type = typings.officeDashUiDashFabricDashReact.libComponentsButtonButtonDotTypesMod.IButtonProps
  type MessageBarButtonProps = IButtonProps
  @scala.inline
  def ModalProps: IModalProps.type = typings.officeDashUiDashFabricDashReact.libComponentsModalModalDotTypesMod.IModalProps
  type ModalProps = IModalProps
  @scala.inline
  def ModalBaseProps: IModalProps.type = typings.officeDashUiDashFabricDashReact.libComponentsModalModalDotTypesMod.IModalProps
  type ModalBaseProps = IModalProps
  @scala.inline
  def NavProps: INavProps.type = typings.officeDashUiDashFabricDashReact.libComponentsNavNavDotTypesMod.INavProps
  type NavProps = INavProps
  @scala.inline
  def NavBaseProps: INavProps.type = typings.officeDashUiDashFabricDashReact.libComponentsNavNavDotTypesMod.INavProps
  type NavBaseProps = INavProps
  type NormalPeoplePickerProps = IPeoplePickerProps
  type NormalPeoplePickerBaseProps = IPeoplePickerProps
  @scala.inline
  def OverflowSetProps: IOverflowSetProps.type = typings.officeDashUiDashFabricDashReact.libComponentsOverflowSetOverflowSetDotTypesMod.IOverflowSetProps
  type OverflowSetProps = IOverflowSetProps
  @scala.inline
  def OverflowSetBaseProps: IOverflowSetProps.type = typings.officeDashUiDashFabricDashReact.libComponentsOverflowSetOverflowSetDotTypesMod.IOverflowSetProps
  type OverflowSetBaseProps = IOverflowSetProps
  @scala.inline
  def OverlayProps: IOverlayProps.type = typings.officeDashUiDashFabricDashReact.libComponentsOverlayOverlayDotTypesMod.IOverlayProps
  type OverlayProps = IOverlayProps
  @scala.inline
  def OverlayBaseProps: IOverlayProps.type = typings.officeDashUiDashFabricDashReact.libComponentsOverlayOverlayDotTypesMod.IOverlayProps
  type OverlayBaseProps = IOverlayProps
  @scala.inline
  def PanelProps: IPanelProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPanelPanelDotTypesMod.IPanelProps
  type PanelProps = IPanelProps
  @scala.inline
  def PanelBaseProps: IPanelProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPanelPanelDotTypesMod.IPanelProps
  type PanelBaseProps = IPanelProps
  @scala.inline
  def PeoplePickerItemProps: IPeoplePickerItemSelectedProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemDotTypesMod.IPeoplePickerItemSelectedProps
  type PeoplePickerItemProps = IPeoplePickerItemSelectedProps
  @scala.inline
  def PeoplePickerItemBaseProps: IPeoplePickerItemSelectedProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemDotTypesMod.IPeoplePickerItemSelectedProps
  type PeoplePickerItemBaseProps = IPeoplePickerItemSelectedProps
  @scala.inline
  def PeoplePickerItemSuggestionProps: IPeoplePickerItemSuggestionProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemDotTypesMod.IPeoplePickerItemSuggestionProps
  type PeoplePickerItemSuggestionProps = IPeoplePickerItemSuggestionProps
  @scala.inline
  def PeoplePickerItemSuggestionBaseProps: IPeoplePickerItemSuggestionProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemDotTypesMod.IPeoplePickerItemSuggestionProps
  type PeoplePickerItemSuggestionBaseProps = IPeoplePickerItemSuggestionProps
  @scala.inline
  def PersonaProps: IPersonaProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPersonaPersonaDotTypesMod.IPersonaProps
  type PersonaProps = IPersonaProps
  @scala.inline
  def PersonaBaseProps: IPersonaProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPersonaPersonaDotTypesMod.IPersonaProps
  type PersonaBaseProps = IPersonaProps
  @scala.inline
  def PersonaCoinProps: IPersonaCoinProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPersonaPersonaDotTypesMod.IPersonaCoinProps
  type PersonaCoinProps = IPersonaCoinProps
  @scala.inline
  def PersonaCoinBaseProps: IPersonaCoinProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPersonaPersonaDotTypesMod.IPersonaCoinProps
  type PersonaCoinBaseProps = IPersonaCoinProps
  @scala.inline
  def PivotProps: IPivotProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPivotPivotDotTypesMod.IPivotProps
  type PivotProps = IPivotProps
  @scala.inline
  def PivotBaseProps: IPivotProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPivotPivotDotTypesMod.IPivotProps
  type PivotBaseProps = IPivotProps
  @scala.inline
  def PivotItemProps: IPivotItemProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPivotPivotItemDotTypesMod.IPivotItemProps
  type PivotItemProps = IPivotItemProps
  @scala.inline
  def PlainCardProps: IPlainCardProps.type = typings.officeDashUiDashFabricDashReact.libComponentsHoverCardPlainCardPlainCardDotTypesMod.IPlainCardProps
  type PlainCardProps = IPlainCardProps
  @scala.inline
  def PlainCardBaseProps: IPlainCardProps.type = typings.officeDashUiDashFabricDashReact.libComponentsHoverCardPlainCardPlainCardDotTypesMod.IPlainCardProps
  type PlainCardBaseProps = IPlainCardProps
  @scala.inline
  def PopupProps: IPopupProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPopupPopupDotTypesMod.IPopupProps
  type PopupProps = IPopupProps
  @scala.inline
  def PositioningContainerProps: IPositioningContainerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCoachmarkPositioningContainerPositioningContainerDotTypesMod.IPositioningContainerProps
  type PositioningContainerProps = IPositioningContainerProps
  @scala.inline
  def PrimaryButtonProps: IButtonProps.type = typings.officeDashUiDashFabricDashReact.libComponentsButtonButtonDotTypesMod.IButtonProps
  type PrimaryButtonProps = IButtonProps
  @scala.inline
  def ProgressIndicatorProps: IProgressIndicatorProps.type = typings.officeDashUiDashFabricDashReact.libComponentsProgressIndicatorProgressIndicatorDotTypesMod.IProgressIndicatorProps
  type ProgressIndicatorProps = IProgressIndicatorProps
  @scala.inline
  def ProgressIndicatorBaseProps: IProgressIndicatorProps.type = typings.officeDashUiDashFabricDashReact.libComponentsProgressIndicatorProgressIndicatorDotTypesMod.IProgressIndicatorProps
  type ProgressIndicatorBaseProps = IProgressIndicatorProps
  @scala.inline
  def RatingProps: IRatingProps.type = typings.officeDashUiDashFabricDashReact.libComponentsRatingRatingDotTypesMod.IRatingProps
  type RatingProps = IRatingProps
  @scala.inline
  def RatingBaseProps: IRatingProps.type = typings.officeDashUiDashFabricDashReact.libComponentsRatingRatingDotTypesMod.IRatingProps
  type RatingBaseProps = IRatingProps
  @scala.inline
  def ResizeGroupBaseProps: IResizeGroupProps.type = typings.officeDashUiDashFabricDashReact.libComponentsResizeGroupResizeGroupDotTypesMod.IResizeGroupProps
  type ResizeGroupBaseProps = IResizeGroupProps
  @scala.inline
  def ScrollablePaneProps: IScrollablePaneProps.type = typings.officeDashUiDashFabricDashReact.libComponentsScrollablePaneScrollablePaneDotTypesMod.IScrollablePaneProps
  type ScrollablePaneProps = IScrollablePaneProps
  @scala.inline
  def ScrollablePaneBaseProps: IScrollablePaneProps.type = typings.officeDashUiDashFabricDashReact.libComponentsScrollablePaneScrollablePaneDotTypesMod.IScrollablePaneProps
  type ScrollablePaneBaseProps = IScrollablePaneProps
  @scala.inline
  def SearchBoxProps: ISearchBoxProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSearchBoxSearchBoxDotTypesMod.ISearchBoxProps
  type SearchBoxProps = ISearchBoxProps
  @scala.inline
  def SearchBoxBaseProps: ISearchBoxProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSearchBoxSearchBoxDotTypesMod.ISearchBoxProps
  type SearchBoxBaseProps = ISearchBoxProps
  @scala.inline
  def SelectedPeopleListProps: ISelectedPeopleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSelectedItemsListSelectedPeopleListSelectedPeopleListMod.ISelectedPeopleProps
  type SelectedPeopleListProps = ISelectedPeopleProps
  @scala.inline
  def SelectionZoneProps: ISelectionZoneProps.type = typings.officeDashUiDashFabricDashReact.libUtilitiesSelectionSelectionZoneMod.ISelectionZoneProps
  type SelectionZoneProps = ISelectionZoneProps
  @scala.inline
  def SeparatorProps: ISeparatorProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSeparatorSeparatorDotTypesMod.ISeparatorProps
  type SeparatorProps = ISeparatorProps
  @scala.inline
  def SeparatorBaseProps: ISeparatorProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSeparatorSeparatorDotTypesMod.ISeparatorProps
  type SeparatorBaseProps = ISeparatorProps
  @scala.inline
  def ShimmerProps: IShimmerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerDotTypesMod.IShimmerProps
  type ShimmerProps = IShimmerProps
  @scala.inline
  def ShimmerBaseProps: IShimmerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerDotTypesMod.IShimmerProps
  type ShimmerBaseProps = IShimmerProps
  @scala.inline
  def ShimmerCircleProps: IShimmerCircleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerCircleShimmerCircleDotTypesMod.IShimmerCircleProps
  type ShimmerCircleProps = IShimmerCircleProps
  @scala.inline
  def ShimmerCircleBaseProps: IShimmerCircleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerCircleShimmerCircleDotTypesMod.IShimmerCircleProps
  type ShimmerCircleBaseProps = IShimmerCircleProps
  @scala.inline
  def ShimmerElementsGroupProps: IShimmerElementsGroupProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerElementsGroupShimmerElementsGroupDotTypesMod.IShimmerElementsGroupProps
  type ShimmerElementsGroupProps = IShimmerElementsGroupProps
  @scala.inline
  def ShimmerElementsGroupBaseProps: IShimmerElementsGroupProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerElementsGroupShimmerElementsGroupDotTypesMod.IShimmerElementsGroupProps
  type ShimmerElementsGroupBaseProps = IShimmerElementsGroupProps
  @scala.inline
  def ShimmerGapProps: IShimmerGapProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerGapShimmerGapDotTypesMod.IShimmerGapProps
  type ShimmerGapProps = IShimmerGapProps
  @scala.inline
  def ShimmerGapBaseProps: IShimmerGapProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerGapShimmerGapDotTypesMod.IShimmerGapProps
  type ShimmerGapBaseProps = IShimmerGapProps
  @scala.inline
  def ShimmerLineProps: IShimmerLineProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerLineShimmerLineDotTypesMod.IShimmerLineProps
  type ShimmerLineProps = IShimmerLineProps
  @scala.inline
  def ShimmerLineBaseProps: IShimmerLineProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerLineShimmerLineDotTypesMod.IShimmerLineProps
  type ShimmerLineBaseProps = IShimmerLineProps
  @scala.inline
  def ShimmeredDetailsListProps: IShimmeredDetailsListProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDetailsListShimmeredDetailsListDotTypesMod.IShimmeredDetailsListProps
  type ShimmeredDetailsListProps = IShimmeredDetailsListProps
  @scala.inline
  def ShimmeredDetailsListBaseProps: IShimmeredDetailsListProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDetailsListShimmeredDetailsListDotTypesMod.IShimmeredDetailsListProps
  type ShimmeredDetailsListBaseProps = IShimmeredDetailsListProps
  @scala.inline
  def SliderProps: ISliderProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSliderSliderDotTypesMod.ISliderProps
  type SliderProps = ISliderProps
  @scala.inline
  def SliderBaseProps: ISliderProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSliderSliderDotTypesMod.ISliderProps
  type SliderBaseProps = ISliderProps
  @scala.inline
  def SpinButtonProps: ISpinButtonProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSpinButtonSpinButtonDotTypesMod.ISpinButtonProps
  type SpinButtonProps = ISpinButtonProps
  @scala.inline
  def SpinnerProps: ISpinnerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSpinnerSpinnerDotTypesMod.ISpinnerProps
  type SpinnerProps = ISpinnerProps
  @scala.inline
  def SpinnerBaseProps: ISpinnerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSpinnerSpinnerDotTypesMod.ISpinnerProps
  type SpinnerBaseProps = ISpinnerProps
  @scala.inline
  def StackItemProps: IStackItemProps.type = typings.officeDashUiDashFabricDashReact.libComponentsStackStackItemStackItemDotTypesMod.IStackItemProps
  type StackItemProps = IStackItemProps
  @scala.inline
  def StickyProps: IStickyProps.type = typings.officeDashUiDashFabricDashReact.libComponentsStickyStickyDotTypesMod.IStickyProps
  type StickyProps = IStickyProps
  type SuggestionsProps[T] = ISuggestionsProps[T]
  type SuggestionsControlProps[T] = ISuggestionsControlProps[T]
  type SuggestionsCoreProps[T] = ISuggestionsCoreProps[T]
  @scala.inline
  def SuggestionsHeaderFooterItemProps: ISuggestionsHeaderFooterItemProps.type = typings.officeDashUiDashFabricDashReact.libComponentsFloatingPickerSuggestionsSuggestionsDotTypesMod.ISuggestionsHeaderFooterItemProps
  type SuggestionsHeaderFooterItemProps = ISuggestionsHeaderFooterItemProps
  @scala.inline
  def SuggestionsItemProps: ISuggestionItemProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersSuggestionsSuggestionsItemDotTypesMod.ISuggestionItemProps
  type SuggestionsItemProps[T] = ISuggestionItemProps[T]
  @scala.inline
  def SwatchColorPickerProps: ISwatchColorPickerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSwatchColorPickerSwatchColorPickerDotTypesMod.ISwatchColorPickerProps
  type SwatchColorPickerProps = ISwatchColorPickerProps
  @scala.inline
  def SwatchColorPickerBaseProps: ISwatchColorPickerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSwatchColorPickerSwatchColorPickerDotTypesMod.ISwatchColorPickerProps
  type SwatchColorPickerBaseProps = ISwatchColorPickerProps
  @scala.inline
  def TagItemProps: ITagItemProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersTagPickerTagPickerDotTypesMod.ITagItemProps
  type TagItemProps = ITagItemProps
  @scala.inline
  def TagItemBaseProps: ITagItemProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersTagPickerTagPickerDotTypesMod.ITagItemProps
  type TagItemBaseProps = ITagItemProps
  @scala.inline
  def TagItemSuggestionProps: ITagItemSuggestionProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersTagPickerTagPickerDotTypesMod.ITagItemSuggestionProps
  type TagItemSuggestionProps = ITagItemSuggestionProps
  @scala.inline
  def TagItemSuggestionBaseProps: ITagItemSuggestionProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersTagPickerTagPickerDotTypesMod.ITagItemSuggestionProps
  type TagItemSuggestionBaseProps = ITagItemSuggestionProps
  type TagPickerProps = ITagPickerProps
  type TagPickerBaseProps = ITagPickerProps
  @scala.inline
  def TeachingBubbleProps: ITeachingBubbleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTeachingBubbleTeachingBubbleDotTypesMod.ITeachingBubbleProps
  type TeachingBubbleProps = ITeachingBubbleProps
  @scala.inline
  def TeachingBubbleBaseProps: ITeachingBubbleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTeachingBubbleTeachingBubbleDotTypesMod.ITeachingBubbleProps
  type TeachingBubbleBaseProps = ITeachingBubbleProps
  @scala.inline
  def TeachingBubbleContentProps: ITeachingBubbleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTeachingBubbleTeachingBubbleDotTypesMod.ITeachingBubbleProps
  type TeachingBubbleContentProps = ITeachingBubbleProps
  @scala.inline
  def TeachingBubbleContentBaseProps: ITeachingBubbleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTeachingBubbleTeachingBubbleDotTypesMod.ITeachingBubbleProps
  type TeachingBubbleContentBaseProps = ITeachingBubbleProps
  @scala.inline
  def TextProps: ITextProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTextTextDotTypesMod.ITextProps
  type TextProps = ITextProps
  @scala.inline
  def TextFieldProps: ITextFieldProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTextFieldTextFieldDotTypesMod.ITextFieldProps
  type TextFieldProps = ITextFieldProps
  @scala.inline
  def TextFieldBaseProps: ITextFieldProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTextFieldTextFieldDotTypesMod.ITextFieldProps
  type TextFieldBaseProps = ITextFieldProps
  @scala.inline
  def ToggleProps: IToggleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsToggleToggleDotTypesMod.IToggleProps
  type ToggleProps = IToggleProps
  @scala.inline
  def ToggleBaseProps: IToggleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsToggleToggleDotTypesMod.IToggleProps
  type ToggleBaseProps = IToggleProps
  @scala.inline
  def TooltipProps: ITooltipProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTooltipTooltipDotTypesMod.ITooltipProps
  type TooltipProps = ITooltipProps
  @scala.inline
  def TooltipBaseProps: ITooltipProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTooltipTooltipDotTypesMod.ITooltipProps
  type TooltipBaseProps = ITooltipProps
  @scala.inline
  def TooltipHostProps: ITooltipHostProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTooltipTooltipHostDotTypesMod.ITooltipHostProps
  type TooltipHostProps = ITooltipHostProps
  @scala.inline
  def TooltipHostBaseProps: ITooltipHostProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTooltipTooltipHostDotTypesMod.ITooltipHostProps
  type TooltipHostBaseProps = ITooltipHostProps
  @scala.inline
  def VerticalDividerProps: IVerticalDividerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDividerVerticalDividerDotTypesMod.IVerticalDividerProps
  type VerticalDividerProps = IVerticalDividerProps
  @scala.inline
  def VirtualizedComboBoxProps: IComboBoxProps.type = typings.officeDashUiDashFabricDashReact.libComponentsComboBoxComboBoxDotTypesMod.IComboBoxProps
  type VirtualizedComboBoxProps = IComboBoxProps
  @scala.inline
  def libCheckModCheckProps: ICheckProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCheckCheckDotTypesMod.ICheckProps
  type libCheckModCheckProps = ICheckProps
  @scala.inline
  def libCheckModCheckBaseProps: ICheckProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCheckCheckDotTypesMod.ICheckProps
  type libCheckModCheckBaseProps = ICheckProps
  @scala.inline
  def libChoiceGroupOptionModChoiceGroupOptionProps: IChoiceGroupOptionProps.type = typings.officeDashUiDashFabricDashReact.libComponentsChoiceGroupChoiceGroupOptionChoiceGroupOptionDotTypesMod.IChoiceGroupOptionProps
  type libChoiceGroupOptionModChoiceGroupOptionProps = IChoiceGroupOptionProps
  @scala.inline
  def libComponentsAnnouncedAnnouncedModAnnouncedProps: IAnnouncedProps.type = typings.officeDashUiDashFabricDashReact.libComponentsAnnouncedAnnouncedDotTypesMod.IAnnouncedProps
  type libComponentsAnnouncedAnnouncedModAnnouncedProps = IAnnouncedProps
  @scala.inline
  def libComponentsBreadcrumbBreadcrumbModBreadcrumbProps: IBreadcrumbProps.type = typings.officeDashUiDashFabricDashReact.libComponentsBreadcrumbBreadcrumbDotTypesMod.IBreadcrumbProps
  type libComponentsBreadcrumbBreadcrumbModBreadcrumbProps = IBreadcrumbProps
  @scala.inline
  def libComponentsCalloutFocusTrapCalloutModFocusTrapCalloutProps: IFocusTrapCalloutProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCalloutFocusTrapCalloutDotTypesMod.IFocusTrapCalloutProps
  type libComponentsCalloutFocusTrapCalloutModFocusTrapCalloutProps = IFocusTrapCalloutProps
  @scala.inline
  def libComponentsCheckCheckDotBaseModCheckBaseProps: ICheckProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCheckCheckDotTypesMod.ICheckProps
  type libComponentsCheckCheckDotBaseModCheckBaseProps = ICheckProps
  @scala.inline
  def libComponentsCheckCheckModCheckProps: ICheckProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCheckCheckDotTypesMod.ICheckProps
  type libComponentsCheckCheckModCheckProps = ICheckProps
  @scala.inline
  def libComponentsCheckModCheckProps: ICheckProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCheckCheckDotTypesMod.ICheckProps
  type libComponentsCheckModCheckProps = ICheckProps
  @scala.inline
  def libComponentsCheckModCheckBaseProps: ICheckProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCheckCheckDotTypesMod.ICheckProps
  type libComponentsCheckModCheckBaseProps = ICheckProps
  @scala.inline
  def libComponentsCheckboxCheckboxModCheckboxProps: ICheckboxProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCheckboxCheckboxDotTypesMod.ICheckboxProps
  type libComponentsCheckboxCheckboxModCheckboxProps = ICheckboxProps
  @scala.inline
  def libComponentsChoiceGroupChoiceGroupModChoiceGroupProps: IChoiceGroupProps.type = typings.officeDashUiDashFabricDashReact.libComponentsChoiceGroupChoiceGroupDotTypesMod.IChoiceGroupProps
  type libComponentsChoiceGroupChoiceGroupModChoiceGroupProps = IChoiceGroupProps
  @scala.inline
  def libComponentsChoiceGroupChoiceGroupOptionChoiceGroupOptionModChoiceGroupOptionProps: IChoiceGroupOptionProps.type = typings.officeDashUiDashFabricDashReact.libComponentsChoiceGroupChoiceGroupOptionChoiceGroupOptionDotTypesMod.IChoiceGroupOptionProps
  type libComponentsChoiceGroupChoiceGroupOptionChoiceGroupOptionModChoiceGroupOptionProps = IChoiceGroupOptionProps
  @scala.inline
  def libComponentsChoiceGroupChoiceGroupOptionModChoiceGroupOptionProps: IChoiceGroupOptionProps.type = typings.officeDashUiDashFabricDashReact.libComponentsChoiceGroupChoiceGroupOptionChoiceGroupOptionDotTypesMod.IChoiceGroupOptionProps
  type libComponentsChoiceGroupChoiceGroupOptionModChoiceGroupOptionProps = IChoiceGroupOptionProps
  @scala.inline
  def libComponentsCoachmarkCoachmarkModCoachmarkProps: ICoachmarkProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCoachmarkCoachmarkDotTypesMod.ICoachmarkProps
  type libComponentsCoachmarkCoachmarkModCoachmarkProps = ICoachmarkProps
  @scala.inline
  def libComponentsColorPickerColorPickerModColorPickerProps: IColorPickerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsColorPickerColorPickerDotTypesMod.IColorPickerProps
  type libComponentsColorPickerColorPickerModColorPickerProps = IColorPickerProps
  @scala.inline
  def libComponentsCommandBarCommandBarModCommandBarProps: ICommandBarProps.type = typings.officeDashUiDashFabricDashReact.libComponentsCommandBarCommandBarDotTypesMod.ICommandBarProps
  type libComponentsCommandBarCommandBarModCommandBarProps = ICommandBarProps
  @scala.inline
  def libComponentsContextualMenuContextualMenuItemModContextualMenuItemProps: IContextualMenuItemProps.type = typings.officeDashUiDashFabricDashReact.libComponentsContextualMenuContextualMenuItemDotTypesMod.IContextualMenuItemProps
  type libComponentsContextualMenuContextualMenuItemModContextualMenuItemProps = IContextualMenuItemProps
  @scala.inline
  def libComponentsContextualMenuContextualMenuModContextualMenuProps: IContextualMenuProps.type = typings.officeDashUiDashFabricDashReact.libComponentsContextualMenuContextualMenuDotTypesMod.IContextualMenuProps
  type libComponentsContextualMenuContextualMenuModContextualMenuProps = IContextualMenuProps
  @scala.inline
  def libComponentsDatePickerDatePickerModDatePickerProps: IDatePickerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDatePickerDatePickerDotTypesMod.IDatePickerProps
  type libComponentsDatePickerDatePickerModDatePickerProps = IDatePickerProps
  @scala.inline
  def libComponentsDetailsListDetailsColumnModDetailsColumnProps: IDetailsColumnProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsColumnDotTypesMod.IDetailsColumnProps
  type libComponentsDetailsListDetailsColumnModDetailsColumnProps = IDetailsColumnProps
  @scala.inline
  def libComponentsDetailsListDetailsHeaderModDetailsHeaderProps: IDetailsHeaderBaseProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsHeaderDotTypesMod.IDetailsHeaderBaseProps
  type libComponentsDetailsListDetailsHeaderModDetailsHeaderProps = IDetailsHeaderBaseProps
  @scala.inline
  def libComponentsDetailsListDetailsListModDetailsListProps: IDetailsListProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsListDotTypesMod.IDetailsListProps
  type libComponentsDetailsListDetailsListModDetailsListProps = IDetailsListProps
  @scala.inline
  def libComponentsDetailsListDetailsRowCheckModDetailsRowCheckProps: IDetailsRowCheckProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsRowCheckDotTypesMod.IDetailsRowCheckProps
  type libComponentsDetailsListDetailsRowCheckModDetailsRowCheckProps = IDetailsRowCheckProps
  @scala.inline
  def libComponentsDetailsListDetailsRowModDetailsRowProps: IDetailsRowBaseProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDetailsListDetailsRowDotTypesMod.IDetailsRowBaseProps
  type libComponentsDetailsListDetailsRowModDetailsRowProps = IDetailsRowBaseProps
  @scala.inline
  def libComponentsDetailsListShimmeredDetailsListModShimmeredDetailsListProps: IShimmeredDetailsListProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDetailsListShimmeredDetailsListDotTypesMod.IShimmeredDetailsListProps
  type libComponentsDetailsListShimmeredDetailsListModShimmeredDetailsListProps = IShimmeredDetailsListProps
  @scala.inline
  def libComponentsDialogDialogContentModDialogContentProps: IDialogContentProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDialogDialogContentDotTypesMod.IDialogContentProps
  type libComponentsDialogDialogContentModDialogContentProps = IDialogContentProps
  @scala.inline
  def libComponentsDialogDialogFooterModDialogFooterProps: IDialogFooterProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDialogDialogFooterDotTypesMod.IDialogFooterProps
  type libComponentsDialogDialogFooterModDialogFooterProps = IDialogFooterProps
  @scala.inline
  def libComponentsDialogDialogModDialogProps: IDialogProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDialogDialogDotTypesMod.IDialogProps
  type libComponentsDialogDialogModDialogProps = IDialogProps
  @scala.inline
  def libComponentsDividerModVerticalDividerProps: IVerticalDividerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDividerVerticalDividerDotTypesMod.IVerticalDividerProps
  type libComponentsDividerModVerticalDividerProps = IVerticalDividerProps
  @scala.inline
  def libComponentsDividerVerticalDividerModVerticalDividerProps: IVerticalDividerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDividerVerticalDividerDotTypesMod.IVerticalDividerProps
  type libComponentsDividerVerticalDividerModVerticalDividerProps = IVerticalDividerProps
  @scala.inline
  def libComponentsDocumentCardDocumentCardActionsModDocumentCardActionsProps: IDocumentCardActionsProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardActionsDotTypesMod.IDocumentCardActionsProps
  type libComponentsDocumentCardDocumentCardActionsModDocumentCardActionsProps = IDocumentCardActionsProps
  @scala.inline
  def libComponentsDocumentCardDocumentCardActivityModDocumentCardActivityProps: IDocumentCardActivityProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardActivityDotTypesMod.IDocumentCardActivityProps
  type libComponentsDocumentCardDocumentCardActivityModDocumentCardActivityProps = IDocumentCardActivityProps
  @scala.inline
  def libComponentsDocumentCardDocumentCardDetailsModDocumentCardDetailsProps: IDocumentCardDetailsProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardDetailsDotTypesMod.IDocumentCardDetailsProps
  type libComponentsDocumentCardDocumentCardDetailsModDocumentCardDetailsProps = IDocumentCardDetailsProps
  @scala.inline
  def libComponentsDocumentCardDocumentCardImageModDocumentCardImageProps: IDocumentCardImageProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardImageDotTypesMod.IDocumentCardImageProps
  type libComponentsDocumentCardDocumentCardImageModDocumentCardImageProps = IDocumentCardImageProps
  @scala.inline
  def libComponentsDocumentCardDocumentCardLocationModDocumentCardLocationProps: IDocumentCardLocationProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardLocationDotTypesMod.IDocumentCardLocationProps
  type libComponentsDocumentCardDocumentCardLocationModDocumentCardLocationProps = IDocumentCardLocationProps
  @scala.inline
  def libComponentsDocumentCardDocumentCardLogoModDocumentCardLogoProps: IDocumentCardLogoProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardLogoDotTypesMod.IDocumentCardLogoProps
  type libComponentsDocumentCardDocumentCardLogoModDocumentCardLogoProps = IDocumentCardLogoProps
  @scala.inline
  def libComponentsDocumentCardDocumentCardModDocumentCardProps: IDocumentCardProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardDotTypesMod.IDocumentCardProps
  type libComponentsDocumentCardDocumentCardModDocumentCardProps = IDocumentCardProps
  @scala.inline
  def libComponentsDocumentCardDocumentCardPreviewModDocumentCardPreviewProps: IDocumentCardPreviewProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardPreviewDotTypesMod.IDocumentCardPreviewProps
  type libComponentsDocumentCardDocumentCardPreviewModDocumentCardPreviewProps = IDocumentCardPreviewProps
  @scala.inline
  def libComponentsDocumentCardDocumentCardStatusModDocumentCardStatusProps: IDocumentCardStatusProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardStatusDotTypesMod.IDocumentCardStatusProps
  type libComponentsDocumentCardDocumentCardStatusModDocumentCardStatusProps = IDocumentCardStatusProps
  @scala.inline
  def libComponentsDocumentCardDocumentCardTitleModDocumentCardTitleProps: IDocumentCardTitleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDocumentCardDocumentCardTitleDotTypesMod.IDocumentCardTitleProps
  type libComponentsDocumentCardDocumentCardTitleModDocumentCardTitleProps = IDocumentCardTitleProps
  @scala.inline
  def libComponentsDropdownDropdownModDropdownProps: IDropdownProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDropdownDropdownDotTypesMod.IDropdownProps
  type libComponentsDropdownDropdownModDropdownProps = IDropdownProps
  @scala.inline
  def libComponentsFabricFabricModFabricProps: IFabricProps.type = typings.officeDashUiDashFabricDashReact.libComponentsFabricFabricDotTypesMod.IFabricProps
  type libComponentsFabricFabricModFabricProps = IFabricProps
  @scala.inline
  def libComponentsFacepileFacepileModFacepileProps: IFacepileProps.type = typings.officeDashUiDashFabricDashReact.libComponentsFacepileFacepileDotTypesMod.IFacepileProps
  type libComponentsFacepileFacepileModFacepileProps = IFacepileProps
  @scala.inline
  def libComponentsGroupedListGroupFooterModGroupFooterProps: IGroupFooterProps.type = typings.officeDashUiDashFabricDashReact.libComponentsGroupedListGroupFooterDotTypesMod.IGroupFooterProps
  type libComponentsGroupedListGroupFooterModGroupFooterProps = IGroupFooterProps
  @scala.inline
  def libComponentsGroupedListGroupHeaderModGroupHeaderProps: IGroupHeaderProps.type = typings.officeDashUiDashFabricDashReact.libComponentsGroupedListGroupHeaderDotTypesMod.IGroupHeaderProps
  type libComponentsGroupedListGroupHeaderModGroupHeaderProps = IGroupHeaderProps
  @scala.inline
  def libComponentsGroupedListGroupShowAllModGroupShowAllProps: IGroupShowAllProps.type = typings.officeDashUiDashFabricDashReact.libComponentsGroupedListGroupShowAllDotTypesMod.IGroupShowAllProps
  type libComponentsGroupedListGroupShowAllModGroupShowAllProps = IGroupShowAllProps
  @scala.inline
  def libComponentsGroupedListGroupSpacerModGroupSpacerProps: IGroupSpacerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsGroupedListGroupSpacerDotTypesMod.IGroupSpacerProps
  type libComponentsGroupedListGroupSpacerModGroupSpacerProps = IGroupSpacerProps
  type libComponentsGroupedListGroupedListModGroupedListProps = IGroupedListProps
  @scala.inline
  def libComponentsHoverCardExpandingCardModExpandingCardProps: IExpandingCardProps.type = typings.officeDashUiDashFabricDashReact.libComponentsHoverCardExpandingCardDotTypesMod.IExpandingCardProps
  type libComponentsHoverCardExpandingCardModExpandingCardProps = IExpandingCardProps
  @scala.inline
  def libComponentsHoverCardHoverCardModHoverCardProps: IHoverCardProps.type = typings.officeDashUiDashFabricDashReact.libComponentsHoverCardHoverCardDotTypesMod.IHoverCardProps
  type libComponentsHoverCardHoverCardModHoverCardProps = IHoverCardProps
  @scala.inline
  def libComponentsHoverCardPlainCardPlainCardModPlainCardProps: IPlainCardProps.type = typings.officeDashUiDashFabricDashReact.libComponentsHoverCardPlainCardPlainCardDotTypesMod.IPlainCardProps
  type libComponentsHoverCardPlainCardPlainCardModPlainCardProps = IPlainCardProps
  @scala.inline
  def libComponentsIconFontIconModFontIconProps: IFontIconProps.type = typings.officeDashUiDashFabricDashReact.libComponentsIconIconDotTypesMod.IFontIconProps
  type libComponentsIconFontIconModFontIconProps = IFontIconProps
  @scala.inline
  def libComponentsIconIconModIconProps: IIconProps.type = typings.officeDashUiDashFabricDashReact.libComponentsIconIconDotTypesMod.IIconProps
  type libComponentsIconIconModIconProps = IIconProps
  @scala.inline
  def libComponentsIconImageIconModImageIconProps: IImageIconProps.type = typings.officeDashUiDashFabricDashReact.libComponentsIconIconDotTypesMod.IImageIconProps
  type libComponentsIconImageIconModImageIconProps = IImageIconProps
  @scala.inline
  def libComponentsImageImageModImageProps: IImageProps.type = typings.officeDashUiDashFabricDashReact.libComponentsImageImageDotTypesMod.IImageProps
  type libComponentsImageImageModImageProps = IImageProps
  @scala.inline
  def libComponentsKeytipLayerKeytipLayerModKeytipLayerProps: IKeytipLayerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsKeytipLayerKeytipLayerDotTypesMod.IKeytipLayerProps
  type libComponentsKeytipLayerKeytipLayerModKeytipLayerProps = IKeytipLayerProps
  @scala.inline
  def libComponentsLabelLabelModLabelProps: ILabelProps.type = typings.officeDashUiDashFabricDashReact.libComponentsLabelLabelDotTypesMod.ILabelProps
  type libComponentsLabelLabelModLabelProps = ILabelProps
  @scala.inline
  def libComponentsLayerLayerModLayerProps: ILayerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsLayerLayerDotTypesMod.ILayerProps
  type libComponentsLayerLayerModLayerProps = ILayerProps
  @scala.inline
  def libComponentsLinkLinkModLinkProps: ILinkProps.type = typings.officeDashUiDashFabricDashReact.libComponentsLinkLinkDotTypesMod.ILinkProps
  type libComponentsLinkLinkModLinkProps = ILinkProps
  @scala.inline
  def libComponentsMarqueeSelectionMarqueeSelectionModMarqueeSelectionProps: IMarqueeSelectionProps.type = typings.officeDashUiDashFabricDashReact.libComponentsMarqueeSelectionMarqueeSelectionDotTypesMod.IMarqueeSelectionProps
  type libComponentsMarqueeSelectionMarqueeSelectionModMarqueeSelectionProps = IMarqueeSelectionProps
  @scala.inline
  def libComponentsMessageBarMessageBarModMessageBarProps: IMessageBarProps.type = typings.officeDashUiDashFabricDashReact.libComponentsMessageBarMessageBarDotTypesMod.IMessageBarProps
  type libComponentsMessageBarMessageBarModMessageBarProps = IMessageBarProps
  @scala.inline
  def libComponentsModalModalModModalProps: IModalProps.type = typings.officeDashUiDashFabricDashReact.libComponentsModalModalDotTypesMod.IModalProps
  type libComponentsModalModalModModalProps = IModalProps
  @scala.inline
  def libComponentsNavNavModNavProps: INavProps.type = typings.officeDashUiDashFabricDashReact.libComponentsNavNavDotTypesMod.INavProps
  type libComponentsNavNavModNavProps = INavProps
  @scala.inline
  def libComponentsOverflowSetOverflowSetModOverflowSetProps: IOverflowSetProps.type = typings.officeDashUiDashFabricDashReact.libComponentsOverflowSetOverflowSetDotTypesMod.IOverflowSetProps
  type libComponentsOverflowSetOverflowSetModOverflowSetProps = IOverflowSetProps
  @scala.inline
  def libComponentsOverlayOverlayModOverlayProps: IOverlayProps.type = typings.officeDashUiDashFabricDashReact.libComponentsOverlayOverlayDotTypesMod.IOverlayProps
  type libComponentsOverlayOverlayModOverlayProps = IOverlayProps
  @scala.inline
  def libComponentsPanelPanelModPanelProps: IPanelProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPanelPanelDotTypesMod.IPanelProps
  type libComponentsPanelPanelModPanelProps = IPanelProps
  @scala.inline
  def libComponentsPersonaPersonaCoinPersonaCoinModPersonaCoinProps: IPersonaCoinProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPersonaPersonaDotTypesMod.IPersonaCoinProps
  type libComponentsPersonaPersonaCoinPersonaCoinModPersonaCoinProps = IPersonaCoinProps
  @scala.inline
  def libComponentsPersonaPersonaModPersonaProps: IPersonaProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPersonaPersonaDotTypesMod.IPersonaProps
  type libComponentsPersonaPersonaModPersonaProps = IPersonaProps
  @scala.inline
  def libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemModPeoplePickerItemProps: IPeoplePickerItemSelectedProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemDotTypesMod.IPeoplePickerItemSelectedProps
  type libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemModPeoplePickerItemProps = IPeoplePickerItemSelectedProps
  @scala.inline
  def libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemModPeoplePickerItemBaseProps: IPeoplePickerItemSelectedProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemDotTypesMod.IPeoplePickerItemSelectedProps
  type libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemModPeoplePickerItemBaseProps = IPeoplePickerItemSelectedProps
  @scala.inline
  def libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemSuggestionModPeoplePickerItemSuggestionProps: IPeoplePickerItemSuggestionProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemDotTypesMod.IPeoplePickerItemSuggestionProps
  type libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemSuggestionModPeoplePickerItemSuggestionProps = IPeoplePickerItemSuggestionProps
  @scala.inline
  def libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemSuggestionModPeoplePickerItemSuggestionBaseProps: IPeoplePickerItemSuggestionProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemDotTypesMod.IPeoplePickerItemSuggestionProps
  type libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemSuggestionModPeoplePickerItemSuggestionBaseProps = IPeoplePickerItemSuggestionProps
  @scala.inline
  def libComponentsPickersTagPickerTagItemModTagItemProps: ITagItemProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersTagPickerTagPickerDotTypesMod.ITagItemProps
  type libComponentsPickersTagPickerTagItemModTagItemProps = ITagItemProps
  @scala.inline
  def libComponentsPickersTagPickerTagItemModTagItemBaseProps: ITagItemProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersTagPickerTagPickerDotTypesMod.ITagItemProps
  type libComponentsPickersTagPickerTagItemModTagItemBaseProps = ITagItemProps
  @scala.inline
  def libComponentsPickersTagPickerTagItemSuggestionModTagItemSuggestionProps: ITagItemSuggestionProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersTagPickerTagPickerDotTypesMod.ITagItemSuggestionProps
  type libComponentsPickersTagPickerTagItemSuggestionModTagItemSuggestionProps = ITagItemSuggestionProps
  @scala.inline
  def libComponentsPickersTagPickerTagItemSuggestionModTagItemSuggestionBaseProps: ITagItemSuggestionProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPickersTagPickerTagPickerDotTypesMod.ITagItemSuggestionProps
  type libComponentsPickersTagPickerTagItemSuggestionModTagItemSuggestionBaseProps = ITagItemSuggestionProps
  @scala.inline
  def libComponentsPivotPivotModPivotProps: IPivotProps.type = typings.officeDashUiDashFabricDashReact.libComponentsPivotPivotDotTypesMod.IPivotProps
  type libComponentsPivotPivotModPivotProps = IPivotProps
  @scala.inline
  def libComponentsProgressIndicatorProgressIndicatorModProgressIndicatorProps: IProgressIndicatorProps.type = typings.officeDashUiDashFabricDashReact.libComponentsProgressIndicatorProgressIndicatorDotTypesMod.IProgressIndicatorProps
  type libComponentsProgressIndicatorProgressIndicatorModProgressIndicatorProps = IProgressIndicatorProps
  @scala.inline
  def libComponentsRatingRatingModRatingProps: IRatingProps.type = typings.officeDashUiDashFabricDashReact.libComponentsRatingRatingDotTypesMod.IRatingProps
  type libComponentsRatingRatingModRatingProps = IRatingProps
  @scala.inline
  def libComponentsScrollablePaneScrollablePaneModScrollablePaneProps: IScrollablePaneProps.type = typings.officeDashUiDashFabricDashReact.libComponentsScrollablePaneScrollablePaneDotTypesMod.IScrollablePaneProps
  type libComponentsScrollablePaneScrollablePaneModScrollablePaneProps = IScrollablePaneProps
  @scala.inline
  def libComponentsSearchBoxSearchBoxModSearchBoxProps: ISearchBoxProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSearchBoxSearchBoxDotTypesMod.ISearchBoxProps
  type libComponentsSearchBoxSearchBoxModSearchBoxProps = ISearchBoxProps
  @scala.inline
  def libComponentsSeparatorModSeparatorProps: ISeparatorProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSeparatorSeparatorDotTypesMod.ISeparatorProps
  type libComponentsSeparatorModSeparatorProps = ISeparatorProps
  @scala.inline
  def libComponentsSeparatorModSeparatorBaseProps: ISeparatorProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSeparatorSeparatorDotTypesMod.ISeparatorProps
  type libComponentsSeparatorModSeparatorBaseProps = ISeparatorProps
  @scala.inline
  def libComponentsSeparatorSeparatorDotBaseModSeparatorBaseProps: ISeparatorProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSeparatorSeparatorDotTypesMod.ISeparatorProps
  type libComponentsSeparatorSeparatorDotBaseModSeparatorBaseProps = ISeparatorProps
  @scala.inline
  def libComponentsSeparatorSeparatorModSeparatorProps: ISeparatorProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSeparatorSeparatorDotTypesMod.ISeparatorProps
  type libComponentsSeparatorSeparatorModSeparatorProps = ISeparatorProps
  @scala.inline
  def libComponentsShimmerShimmerCircleShimmerCircleDotBaseModShimmerCircleBaseProps: IShimmerCircleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerCircleShimmerCircleDotTypesMod.IShimmerCircleProps
  type libComponentsShimmerShimmerCircleShimmerCircleDotBaseModShimmerCircleBaseProps = IShimmerCircleProps
  @scala.inline
  def libComponentsShimmerShimmerCircleShimmerCircleModShimmerCircleProps: IShimmerCircleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerCircleShimmerCircleDotTypesMod.IShimmerCircleProps
  type libComponentsShimmerShimmerCircleShimmerCircleModShimmerCircleProps = IShimmerCircleProps
  @scala.inline
  def libComponentsShimmerShimmerElementsGroupShimmerElementsGroupDotBaseModShimmerElementsGroupBaseProps: IShimmerElementsGroupProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerElementsGroupShimmerElementsGroupDotTypesMod.IShimmerElementsGroupProps
  type libComponentsShimmerShimmerElementsGroupShimmerElementsGroupDotBaseModShimmerElementsGroupBaseProps = IShimmerElementsGroupProps
  @scala.inline
  def libComponentsShimmerShimmerElementsGroupShimmerElementsGroupModShimmerElementsGroupProps: IShimmerElementsGroupProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerElementsGroupShimmerElementsGroupDotTypesMod.IShimmerElementsGroupProps
  type libComponentsShimmerShimmerElementsGroupShimmerElementsGroupModShimmerElementsGroupProps = IShimmerElementsGroupProps
  @scala.inline
  def libComponentsShimmerShimmerGapShimmerGapDotBaseModShimmerGapBaseProps: IShimmerGapProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerGapShimmerGapDotTypesMod.IShimmerGapProps
  type libComponentsShimmerShimmerGapShimmerGapDotBaseModShimmerGapBaseProps = IShimmerGapProps
  @scala.inline
  def libComponentsShimmerShimmerGapShimmerGapModShimmerGapProps: IShimmerGapProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerGapShimmerGapDotTypesMod.IShimmerGapProps
  type libComponentsShimmerShimmerGapShimmerGapModShimmerGapProps = IShimmerGapProps
  @scala.inline
  def libComponentsShimmerShimmerLineShimmerLineDotBaseModShimmerLineBaseProps: IShimmerLineProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerLineShimmerLineDotTypesMod.IShimmerLineProps
  type libComponentsShimmerShimmerLineShimmerLineDotBaseModShimmerLineBaseProps = IShimmerLineProps
  @scala.inline
  def libComponentsShimmerShimmerLineShimmerLineModShimmerLineProps: IShimmerLineProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerLineShimmerLineDotTypesMod.IShimmerLineProps
  type libComponentsShimmerShimmerLineShimmerLineModShimmerLineProps = IShimmerLineProps
  @scala.inline
  def libComponentsShimmerShimmerModShimmerProps: IShimmerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsShimmerShimmerDotTypesMod.IShimmerProps
  type libComponentsShimmerShimmerModShimmerProps = IShimmerProps
  @scala.inline
  def libComponentsSliderSliderModSliderProps: ISliderProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSliderSliderDotTypesMod.ISliderProps
  type libComponentsSliderSliderModSliderProps = ISliderProps
  @scala.inline
  def libComponentsSpinnerSpinnerModSpinnerProps: ISpinnerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSpinnerSpinnerDotTypesMod.ISpinnerProps
  type libComponentsSpinnerSpinnerModSpinnerProps = ISpinnerProps
  @scala.inline
  def libComponentsStackModStackItemProps: IStackItemProps.type = typings.officeDashUiDashFabricDashReact.libComponentsStackStackItemStackItemDotTypesMod.IStackItemProps
  type libComponentsStackModStackItemProps = IStackItemProps
  @scala.inline
  def libComponentsStackStackItemStackItemModStackItemProps: IStackItemProps.type = typings.officeDashUiDashFabricDashReact.libComponentsStackStackItemStackItemDotTypesMod.IStackItemProps
  type libComponentsStackStackItemStackItemModStackItemProps = IStackItemProps
  @scala.inline
  def libComponentsSwatchColorPickerColorPickerGridCellModColorPickerGridCellProps: IColorPickerGridCellProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSwatchColorPickerColorPickerGridCellDotTypesMod.IColorPickerGridCellProps
  type libComponentsSwatchColorPickerColorPickerGridCellModColorPickerGridCellProps = IColorPickerGridCellProps
  @scala.inline
  def libComponentsSwatchColorPickerSwatchColorPickerModSwatchColorPickerProps: ISwatchColorPickerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSwatchColorPickerSwatchColorPickerDotTypesMod.ISwatchColorPickerProps
  type libComponentsSwatchColorPickerSwatchColorPickerModSwatchColorPickerProps = ISwatchColorPickerProps
  @scala.inline
  def libComponentsTeachingBubbleTeachingBubbleContentModTeachingBubbleContentProps: ITeachingBubbleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTeachingBubbleTeachingBubbleDotTypesMod.ITeachingBubbleProps
  type libComponentsTeachingBubbleTeachingBubbleContentModTeachingBubbleContentProps = ITeachingBubbleProps
  @scala.inline
  def libComponentsTeachingBubbleTeachingBubbleModTeachingBubbleProps: ITeachingBubbleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTeachingBubbleTeachingBubbleDotTypesMod.ITeachingBubbleProps
  type libComponentsTeachingBubbleTeachingBubbleModTeachingBubbleProps = ITeachingBubbleProps
  @scala.inline
  def libComponentsTextFieldTextFieldModTextFieldProps: ITextFieldProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTextFieldTextFieldDotTypesMod.ITextFieldProps
  type libComponentsTextFieldTextFieldModTextFieldProps = ITextFieldProps
  @scala.inline
  def libComponentsTextModTextProps: ITextProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTextTextDotTypesMod.ITextProps
  type libComponentsTextModTextProps = ITextProps
  @scala.inline
  def libComponentsTextTextModTextProps: ITextProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTextTextDotTypesMod.ITextProps
  type libComponentsTextTextModTextProps = ITextProps
  @scala.inline
  def libComponentsToggleToggleModToggleProps: IToggleProps.type = typings.officeDashUiDashFabricDashReact.libComponentsToggleToggleDotTypesMod.IToggleProps
  type libComponentsToggleToggleModToggleProps = IToggleProps
  @scala.inline
  def libComponentsTooltipTooltipHostModTooltipHostProps: ITooltipHostProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTooltipTooltipHostDotTypesMod.ITooltipHostProps
  type libComponentsTooltipTooltipHostModTooltipHostProps = ITooltipHostProps
  @scala.inline
  def libComponentsTooltipTooltipModTooltipProps: ITooltipProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTooltipTooltipDotTypesMod.ITooltipProps
  type libComponentsTooltipTooltipModTooltipProps = ITooltipProps
  @scala.inline
  def libDividerModVerticalDividerProps: IVerticalDividerProps.type = typings.officeDashUiDashFabricDashReact.libComponentsDividerVerticalDividerDotTypesMod.IVerticalDividerProps
  type libDividerModVerticalDividerProps = IVerticalDividerProps
  @scala.inline
  def libFoundationModThemeProviderProps: IThemeProviderProps.type = typings.atUifabricFoundation.libThemeProviderMod.IThemeProviderProps
  type libFoundationModThemeProviderProps = IThemeProviderProps
  @scala.inline
  def libSeparatorModSeparatorProps: ISeparatorProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSeparatorSeparatorDotTypesMod.ISeparatorProps
  type libSeparatorModSeparatorProps = ISeparatorProps
  @scala.inline
  def libSeparatorModSeparatorBaseProps: ISeparatorProps.type = typings.officeDashUiDashFabricDashReact.libComponentsSeparatorSeparatorDotTypesMod.ISeparatorProps
  type libSeparatorModSeparatorBaseProps = ISeparatorProps
  @scala.inline
  def libStackModStackItemProps: IStackItemProps.type = typings.officeDashUiDashFabricDashReact.libComponentsStackStackItemStackItemDotTypesMod.IStackItemProps
  type libStackModStackItemProps = IStackItemProps
  @scala.inline
  def libTextModTextProps: ITextProps.type = typings.officeDashUiDashFabricDashReact.libComponentsTextTextDotTypesMod.ITextProps
  type libTextModTextProps = ITextProps
  @scala.inline
  def libUtilitiesGridGridModGridProps: IGridProps.type = typings.officeDashUiDashFabricDashReact.libUtilitiesGridGridDotTypesMod.IGridProps
  type libUtilitiesGridGridModGridProps = IGridProps
}

