package typings
package atMaterialDashUiCoreLib.svgIconSvgIconMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Inlined parent @material-ui/core.@material-ui/core.StandardProps<react.react.SVGProps<std.SVGSVGElement>, @material-ui/core.@material-ui/core/SvgIcon/SvgIcon.SvgIconClassKey, never> */
trait SvgIconProps extends js.Object {
  var accentHeight: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var accumulate: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.none | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.sum
  ] = js.undefined
  var additive: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.replace | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.sum
  ] = js.undefined
  var alignmentBaseline: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.auto | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.baseline | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.`before-edge` | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.`text-before-edge` | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.middle | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.central | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.`after-edge` | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.`text-after-edge` | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.ideographic | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.alphabetic | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.hanging | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.mathematical | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.inherit
  ] = js.undefined
  var allowReorder: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.no | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.yes
  ] = js.undefined
  var alphabetic: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var amplitude: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var arabicForm: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.initial | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.medial | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.terminal | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.isolated
  ] = js.undefined
  var `aria-activedescendant`: js.UndefOr[java.lang.String] = js.undefined
  var `aria-atomic`: js.UndefOr[scala.Boolean] = js.undefined
  var `aria-autocomplete`: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.none | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.`inline` | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.list | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.both
  ] = js.undefined
  var `aria-busy`: js.UndefOr[scala.Boolean] = js.undefined
  var `aria-checked`: js.UndefOr[scala.Boolean | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.mixed] = js.undefined
  var `aria-colcount`: js.UndefOr[scala.Double] = js.undefined
  var `aria-colindex`: js.UndefOr[scala.Double] = js.undefined
  var `aria-colspan`: js.UndefOr[scala.Double] = js.undefined
  var `aria-controls`: js.UndefOr[java.lang.String] = js.undefined
  var `aria-current`: js.UndefOr[
    scala.Boolean | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.page | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.step | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.location | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.date | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.time
  ] = js.undefined
  var `aria-describedby`: js.UndefOr[java.lang.String] = js.undefined
  var `aria-details`: js.UndefOr[java.lang.String] = js.undefined
  var `aria-disabled`: js.UndefOr[scala.Boolean] = js.undefined
  var `aria-dropeffect`: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.none | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.copy | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.execute | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.link | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.move | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.popup
  ] = js.undefined
  var `aria-errormessage`: js.UndefOr[java.lang.String] = js.undefined
  var `aria-expanded`: js.UndefOr[scala.Boolean] = js.undefined
  var `aria-flowto`: js.UndefOr[java.lang.String] = js.undefined
  var `aria-grabbed`: js.UndefOr[scala.Boolean] = js.undefined
  var `aria-haspopup`: js.UndefOr[
    scala.Boolean | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.menu | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.listbox | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.tree | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.grid | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.dialog
  ] = js.undefined
  var `aria-hidden`: js.UndefOr[scala.Boolean] = js.undefined
  var `aria-invalid`: js.UndefOr[
    scala.Boolean | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.grammar | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.spelling
  ] = js.undefined
  var `aria-keyshortcuts`: js.UndefOr[java.lang.String] = js.undefined
  var `aria-label`: js.UndefOr[java.lang.String] = js.undefined
  var `aria-labelledby`: js.UndefOr[java.lang.String] = js.undefined
  var `aria-level`: js.UndefOr[scala.Double] = js.undefined
  var `aria-live`: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.off | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.assertive | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.polite
  ] = js.undefined
  var `aria-modal`: js.UndefOr[scala.Boolean] = js.undefined
  var `aria-multiline`: js.UndefOr[scala.Boolean] = js.undefined
  var `aria-multiselectable`: js.UndefOr[scala.Boolean] = js.undefined
  var `aria-orientation`: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.horizontal | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.vertical
  ] = js.undefined
  var `aria-owns`: js.UndefOr[java.lang.String] = js.undefined
  var `aria-placeholder`: js.UndefOr[java.lang.String] = js.undefined
  var `aria-posinset`: js.UndefOr[scala.Double] = js.undefined
  var `aria-pressed`: js.UndefOr[scala.Boolean | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.mixed] = js.undefined
  var `aria-readonly`: js.UndefOr[scala.Boolean] = js.undefined
  var `aria-relevant`: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.additions | (atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.`additions text`) | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.all | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.removals | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.text
  ] = js.undefined
  var `aria-required`: js.UndefOr[scala.Boolean] = js.undefined
  var `aria-roledescription`: js.UndefOr[java.lang.String] = js.undefined
  var `aria-rowcount`: js.UndefOr[scala.Double] = js.undefined
  var `aria-rowindex`: js.UndefOr[scala.Double] = js.undefined
  var `aria-rowspan`: js.UndefOr[scala.Double] = js.undefined
  var `aria-selected`: js.UndefOr[scala.Boolean] = js.undefined
  var `aria-setsize`: js.UndefOr[scala.Double] = js.undefined
  var `aria-sort`: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.none | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.ascending | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.descending | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.other
  ] = js.undefined
  var `aria-valuemax`: js.UndefOr[scala.Double] = js.undefined
  var `aria-valuemin`: js.UndefOr[scala.Double] = js.undefined
  var `aria-valuenow`: js.UndefOr[scala.Double] = js.undefined
  var `aria-valuetext`: js.UndefOr[java.lang.String] = js.undefined
  var ascent: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var attributeName: js.UndefOr[java.lang.String] = js.undefined
  var attributeType: js.UndefOr[java.lang.String] = js.undefined
  var autoReverse: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var azimuth: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var baseFrequency: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var baseProfile: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var baselineShift: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var bbox: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var begin: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var bias: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var by: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var calcMode: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var capHeight: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var children: js.UndefOr[reactLib.reactMod.ReactNode] = js.undefined
  var className: js.UndefOr[java.lang.String] = js.undefined
  var classes: js.UndefOr[atMaterialDashUiCoreLib.PartialClassNameMapSvgIconClassKey] = js.undefined
  var clip: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var clipPath: js.UndefOr[java.lang.String] = js.undefined
  var clipPathUnits: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var clipRule: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var color: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreMod.PropTypesNs.Color | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.action | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.disabled | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.error
  ] = js.undefined
  var colorInterpolation: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var colorInterpolationFilters: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.auto | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.sRGB | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.linearRGB | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.inherit
  ] = js.undefined
  var colorProfile: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var colorRendering: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var component: js.UndefOr[reactLib.reactMod.ReactType[SvgIconProps]] = js.undefined
  var contentScriptType: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var contentStyleType: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var cursor: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var cx: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var cy: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var d: js.UndefOr[java.lang.String] = js.undefined
  var dangerouslySetInnerHTML: js.UndefOr[reactLib.Anon_Html] = js.undefined
  var decelerate: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var descent: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var diffuseConstant: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var direction: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var display: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var divisor: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var dominantBaseline: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var dur: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var dx: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var dy: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var edgeMode: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var elevation: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var enableBackground: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var end: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var exponent: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var externalResourcesRequired: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fill: js.UndefOr[java.lang.String] = js.undefined
  var fillOpacity: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fillRule: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.nonzero | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.evenodd | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.inherit
  ] = js.undefined
  var filter: js.UndefOr[java.lang.String] = js.undefined
  var filterRes: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var filterUnits: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var floodColor: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var floodOpacity: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var focusable: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fontFamily: js.UndefOr[java.lang.String] = js.undefined
  var fontSize: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.inherit | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.default | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.small | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.large
  ] = js.undefined
  var fontSizeAdjust: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fontStretch: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fontStyle: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fontVariant: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fontWeight: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var format: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var from: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fx: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fy: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var g1: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var g2: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var glyphName: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var glyphOrientationHorizontal: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var glyphOrientationVertical: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var glyphRef: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var gradientTransform: js.UndefOr[java.lang.String] = js.undefined
  var gradientUnits: js.UndefOr[java.lang.String] = js.undefined
  var hanging: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var height: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var horizAdvX: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var horizOriginX: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var href: js.UndefOr[java.lang.String] = js.undefined
  var id: js.UndefOr[java.lang.String] = js.undefined
  var ideographic: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var imageRendering: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var in: js.UndefOr[java.lang.String] = js.undefined
  var in2: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var innerRef: js.UndefOr[reactLib.reactMod.Ref[_] | reactLib.reactMod.RefObject[_]] = js.undefined
  var intercept: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var k: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var k1: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var k2: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var k3: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var k4: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var kernelMatrix: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var kernelUnitLength: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var kerning: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var key: js.UndefOr[reactLib.reactMod.Key] = js.undefined
  var keyPoints: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var keySplines: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var keyTimes: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var lang: js.UndefOr[java.lang.String] = js.undefined
  var lengthAdjust: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var letterSpacing: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var lightingColor: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var limitingConeAngle: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var local: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var markerEnd: js.UndefOr[java.lang.String] = js.undefined
  var markerHeight: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var markerMid: js.UndefOr[java.lang.String] = js.undefined
  var markerStart: js.UndefOr[java.lang.String] = js.undefined
  var markerUnits: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var markerWidth: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var mask: js.UndefOr[java.lang.String] = js.undefined
  var maskContentUnits: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var maskUnits: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var mathematical: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var max: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var media: js.UndefOr[java.lang.String] = js.undefined
  var method: js.UndefOr[java.lang.String] = js.undefined
  var min: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var mode: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var name: js.UndefOr[java.lang.String] = js.undefined
  var nativeColor: js.UndefOr[java.lang.String] = js.undefined
  var numOctaves: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var offset: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var onAbort: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onAbortCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onAnimationEnd: js.UndefOr[reactLib.reactMod.AnimationEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onAnimationEndCapture: js.UndefOr[reactLib.reactMod.AnimationEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onAnimationIteration: js.UndefOr[reactLib.reactMod.AnimationEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onAnimationIterationCapture: js.UndefOr[reactLib.reactMod.AnimationEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onAnimationStart: js.UndefOr[reactLib.reactMod.AnimationEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onAnimationStartCapture: js.UndefOr[reactLib.reactMod.AnimationEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onAuxClick: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onAuxClickCapture: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onBeforeInput: js.UndefOr[reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onBeforeInputCapture: js.UndefOr[reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onBlur: js.UndefOr[reactLib.reactMod.FocusEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onBlurCapture: js.UndefOr[reactLib.reactMod.FocusEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onCanPlay: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onCanPlayCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onCanPlayThrough: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onCanPlayThroughCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onChange: js.UndefOr[reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onChangeCapture: js.UndefOr[reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onClick: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onClickCapture: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onCompositionEnd: js.UndefOr[reactLib.reactMod.CompositionEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onCompositionEndCapture: js.UndefOr[reactLib.reactMod.CompositionEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onCompositionStart: js.UndefOr[reactLib.reactMod.CompositionEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onCompositionStartCapture: js.UndefOr[reactLib.reactMod.CompositionEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onCompositionUpdate: js.UndefOr[reactLib.reactMod.CompositionEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onCompositionUpdateCapture: js.UndefOr[reactLib.reactMod.CompositionEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onContextMenu: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onContextMenuCapture: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onCopy: js.UndefOr[reactLib.reactMod.ClipboardEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onCopyCapture: js.UndefOr[reactLib.reactMod.ClipboardEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onCut: js.UndefOr[reactLib.reactMod.ClipboardEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onCutCapture: js.UndefOr[reactLib.reactMod.ClipboardEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDoubleClick: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDoubleClickCapture: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDrag: js.UndefOr[reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDragCapture: js.UndefOr[reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDragEnd: js.UndefOr[reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDragEndCapture: js.UndefOr[reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDragEnter: js.UndefOr[reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDragEnterCapture: js.UndefOr[reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDragExit: js.UndefOr[reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDragExitCapture: js.UndefOr[reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDragLeave: js.UndefOr[reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDragLeaveCapture: js.UndefOr[reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDragOver: js.UndefOr[reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDragOverCapture: js.UndefOr[reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDragStart: js.UndefOr[reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDragStartCapture: js.UndefOr[reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDrop: js.UndefOr[reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDropCapture: js.UndefOr[reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDurationChange: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onDurationChangeCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onEmptied: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onEmptiedCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onEncrypted: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onEncryptedCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onEnded: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onEndedCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onError: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onErrorCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onFocus: js.UndefOr[reactLib.reactMod.FocusEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onFocusCapture: js.UndefOr[reactLib.reactMod.FocusEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onGotPointerCapture: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onGotPointerCaptureCapture: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onInput: js.UndefOr[reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onInputCapture: js.UndefOr[reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onInvalid: js.UndefOr[reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onInvalidCapture: js.UndefOr[reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onKeyDown: js.UndefOr[reactLib.reactMod.KeyboardEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onKeyDownCapture: js.UndefOr[reactLib.reactMod.KeyboardEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onKeyPress: js.UndefOr[reactLib.reactMod.KeyboardEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onKeyPressCapture: js.UndefOr[reactLib.reactMod.KeyboardEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onKeyUp: js.UndefOr[reactLib.reactMod.KeyboardEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onKeyUpCapture: js.UndefOr[reactLib.reactMod.KeyboardEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onLoad: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onLoadCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onLoadStart: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onLoadStartCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onLoadedData: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onLoadedDataCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onLoadedMetadata: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onLoadedMetadataCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onLostPointerCapture: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onLostPointerCaptureCapture: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onMouseDown: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onMouseDownCapture: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onMouseEnter: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onMouseLeave: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onMouseMove: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onMouseMoveCapture: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onMouseOut: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onMouseOutCapture: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onMouseOver: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onMouseOverCapture: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onMouseUp: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onMouseUpCapture: js.UndefOr[reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPaste: js.UndefOr[reactLib.reactMod.ClipboardEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPasteCapture: js.UndefOr[reactLib.reactMod.ClipboardEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPause: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPauseCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPlay: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPlayCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPlaying: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPlayingCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPointerCancel: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPointerCancelCapture: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPointerDown: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPointerDownCapture: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPointerEnter: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPointerEnterCapture: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPointerLeave: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPointerLeaveCapture: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPointerMove: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPointerMoveCapture: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPointerOut: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPointerOutCapture: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPointerOver: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPointerOverCapture: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPointerUp: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onPointerUpCapture: js.UndefOr[reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onProgress: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onProgressCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onRateChange: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onRateChangeCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onReset: js.UndefOr[reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onResetCapture: js.UndefOr[reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onScroll: js.UndefOr[reactLib.reactMod.UIEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onScrollCapture: js.UndefOr[reactLib.reactMod.UIEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onSeeked: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onSeekedCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onSeeking: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onSeekingCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onSelect: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onSelectCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onStalled: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onStalledCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onSubmit: js.UndefOr[reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onSubmitCapture: js.UndefOr[reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onSuspend: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onSuspendCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onTimeUpdate: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onTimeUpdateCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onTouchCancel: js.UndefOr[reactLib.reactMod.TouchEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onTouchCancelCapture: js.UndefOr[reactLib.reactMod.TouchEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onTouchEnd: js.UndefOr[reactLib.reactMod.TouchEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onTouchEndCapture: js.UndefOr[reactLib.reactMod.TouchEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onTouchMove: js.UndefOr[reactLib.reactMod.TouchEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onTouchMoveCapture: js.UndefOr[reactLib.reactMod.TouchEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onTouchStart: js.UndefOr[reactLib.reactMod.TouchEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onTouchStartCapture: js.UndefOr[reactLib.reactMod.TouchEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onTransitionEnd: js.UndefOr[reactLib.reactMod.TransitionEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onTransitionEndCapture: js.UndefOr[reactLib.reactMod.TransitionEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onVolumeChange: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onVolumeChangeCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onWaiting: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onWaitingCapture: js.UndefOr[reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onWheel: js.UndefOr[reactLib.reactMod.WheelEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var onWheelCapture: js.UndefOr[reactLib.reactMod.WheelEventHandler[stdLib.SVGSVGElement]] = js.undefined
  var opacity: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var operator: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var order: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var orient: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var orientation: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var origin: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var overflow: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var overlinePosition: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var overlineThickness: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var paintOrder: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var panose1: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var pathLength: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var patternContentUnits: js.UndefOr[java.lang.String] = js.undefined
  var patternTransform: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var patternUnits: js.UndefOr[java.lang.String] = js.undefined
  var pointerEvents: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var points: js.UndefOr[java.lang.String] = js.undefined
  var pointsAtX: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var pointsAtY: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var pointsAtZ: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var preserveAlpha: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var preserveAspectRatio: js.UndefOr[java.lang.String] = js.undefined
  var primitiveUnits: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var r: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var radius: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var ref: js.UndefOr[reactLib.reactMod.LegacyRef[stdLib.SVGSVGElement]] = js.undefined
  var refX: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var refY: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var renderingIntent: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var repeatCount: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var repeatDur: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var requiredExtensions: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var requiredFeatures: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var restart: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var result: js.UndefOr[java.lang.String] = js.undefined
  var role: js.UndefOr[java.lang.String] = js.undefined
  var rotate: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var rx: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var ry: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var scale: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var seed: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var shapeRendering: js.UndefOr[java.lang.String] = js.undefined
  var slope: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var spacing: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var specularConstant: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var specularExponent: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var speed: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var spreadMethod: js.UndefOr[java.lang.String] = js.undefined
  var startOffset: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var stdDeviation: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var stemh: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var stemv: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var stitchTiles: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var stopColor: js.UndefOr[java.lang.String] = js.undefined
  var stopOpacity: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var strikethroughPosition: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var strikethroughThickness: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var string: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var stroke: js.UndefOr[java.lang.String] = js.undefined
  var strokeDasharray: js.UndefOr[java.lang.String | scala.Double] = js.undefined
  var strokeDashoffset: js.UndefOr[java.lang.String | scala.Double] = js.undefined
  var strokeLinecap: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.butt | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.round | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.square | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.inherit
  ] = js.undefined
  var strokeLinejoin: js.UndefOr[
    atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.miter | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.round | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.bevel | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.inherit
  ] = js.undefined
  var strokeMiterlimit: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var strokeOpacity: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var strokeWidth: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var style: js.UndefOr[reactLib.reactMod.CSSProperties] = js.undefined
  var surfaceScale: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var systemLanguage: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var tabIndex: js.UndefOr[scala.Double] = js.undefined
  var tableValues: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var target: js.UndefOr[java.lang.String] = js.undefined
  var targetX: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var targetY: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var textAnchor: js.UndefOr[java.lang.String] = js.undefined
  var textDecoration: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var textLength: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var textRendering: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var titleAccess: js.UndefOr[java.lang.String] = js.undefined
  var to: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var transform: js.UndefOr[java.lang.String] = js.undefined
  var `type`: js.UndefOr[java.lang.String] = js.undefined
  var u1: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var u2: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var underlinePosition: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var underlineThickness: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var unicode: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var unicodeBidi: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var unicodeRange: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var unitsPerEm: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var vAlphabetic: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var vHanging: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var vIdeographic: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var vMathematical: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var values: js.UndefOr[java.lang.String] = js.undefined
  var vectorEffect: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var version: js.UndefOr[java.lang.String] = js.undefined
  var vertAdvY: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var vertOriginX: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var vertOriginY: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var viewBox: js.UndefOr[java.lang.String] = js.undefined
  var viewTarget: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var visibility: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var width: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var widths: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var wordSpacing: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var writingMode: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var x: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var x1: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var x2: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var xChannelSelector: js.UndefOr[java.lang.String] = js.undefined
  var xHeight: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var xlinkActuate: js.UndefOr[java.lang.String] = js.undefined
  var xlinkArcrole: js.UndefOr[java.lang.String] = js.undefined
  var xlinkHref: js.UndefOr[java.lang.String] = js.undefined
  var xlinkRole: js.UndefOr[java.lang.String] = js.undefined
  var xlinkShow: js.UndefOr[java.lang.String] = js.undefined
  var xlinkTitle: js.UndefOr[java.lang.String] = js.undefined
  var xlinkType: js.UndefOr[java.lang.String] = js.undefined
  var xmlBase: js.UndefOr[java.lang.String] = js.undefined
  var xmlLang: js.UndefOr[java.lang.String] = js.undefined
  var xmlSpace: js.UndefOr[java.lang.String] = js.undefined
  var xmlns: js.UndefOr[java.lang.String] = js.undefined
  var xmlnsXlink: js.UndefOr[java.lang.String] = js.undefined
  var y: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var y1: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var y2: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var yChannelSelector: js.UndefOr[java.lang.String] = js.undefined
  var z: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var zoomAndPan: js.UndefOr[java.lang.String] = js.undefined
}

object SvgIconProps {
  @scala.inline
  def apply(
    accentHeight: scala.Double | java.lang.String = null,
    accumulate: atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.none | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.sum = null,
    additive: atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.replace | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.sum = null,
    alignmentBaseline: atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.auto | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.baseline | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.`before-edge` | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.`text-before-edge` | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.middle | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.central | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.`after-edge` | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.`text-after-edge` | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.ideographic | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.alphabetic | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.hanging | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.mathematical | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.inherit = null,
    allowReorder: atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.no | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.yes = null,
    alphabetic: scala.Double | java.lang.String = null,
    amplitude: scala.Double | java.lang.String = null,
    arabicForm: atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.initial | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.medial | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.terminal | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.isolated = null,
    `aria-activedescendant`: java.lang.String = null,
    `aria-atomic`: js.UndefOr[scala.Boolean] = js.undefined,
    `aria-autocomplete`: atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.none | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.`inline` | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.list | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.both = null,
    `aria-busy`: js.UndefOr[scala.Boolean] = js.undefined,
    `aria-checked`: scala.Boolean | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.mixed = null,
    `aria-colcount`: scala.Int | scala.Double = null,
    `aria-colindex`: scala.Int | scala.Double = null,
    `aria-colspan`: scala.Int | scala.Double = null,
    `aria-controls`: java.lang.String = null,
    `aria-current`: scala.Boolean | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.page | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.step | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.location | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.date | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.time = null,
    `aria-describedby`: java.lang.String = null,
    `aria-details`: java.lang.String = null,
    `aria-disabled`: js.UndefOr[scala.Boolean] = js.undefined,
    `aria-dropeffect`: atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.none | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.copy | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.execute | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.link | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.move | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.popup = null,
    `aria-errormessage`: java.lang.String = null,
    `aria-expanded`: js.UndefOr[scala.Boolean] = js.undefined,
    `aria-flowto`: java.lang.String = null,
    `aria-grabbed`: js.UndefOr[scala.Boolean] = js.undefined,
    `aria-haspopup`: scala.Boolean | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.menu | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.listbox | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.tree | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.grid | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.dialog = null,
    `aria-hidden`: js.UndefOr[scala.Boolean] = js.undefined,
    `aria-invalid`: scala.Boolean | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.grammar | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.spelling = null,
    `aria-keyshortcuts`: java.lang.String = null,
    `aria-label`: java.lang.String = null,
    `aria-labelledby`: java.lang.String = null,
    `aria-level`: scala.Int | scala.Double = null,
    `aria-live`: atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.off | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.assertive | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.polite = null,
    `aria-modal`: js.UndefOr[scala.Boolean] = js.undefined,
    `aria-multiline`: js.UndefOr[scala.Boolean] = js.undefined,
    `aria-multiselectable`: js.UndefOr[scala.Boolean] = js.undefined,
    `aria-orientation`: atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.horizontal | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.vertical = null,
    `aria-owns`: java.lang.String = null,
    `aria-placeholder`: java.lang.String = null,
    `aria-posinset`: scala.Int | scala.Double = null,
    `aria-pressed`: scala.Boolean | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.mixed = null,
    `aria-readonly`: js.UndefOr[scala.Boolean] = js.undefined,
    `aria-relevant`: atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.additions | (atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.`additions text`) | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.all | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.removals | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.text = null,
    `aria-required`: js.UndefOr[scala.Boolean] = js.undefined,
    `aria-roledescription`: java.lang.String = null,
    `aria-rowcount`: scala.Int | scala.Double = null,
    `aria-rowindex`: scala.Int | scala.Double = null,
    `aria-rowspan`: scala.Int | scala.Double = null,
    `aria-selected`: js.UndefOr[scala.Boolean] = js.undefined,
    `aria-setsize`: scala.Int | scala.Double = null,
    `aria-sort`: atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.none | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.ascending | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.descending | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.other = null,
    `aria-valuemax`: scala.Int | scala.Double = null,
    `aria-valuemin`: scala.Int | scala.Double = null,
    `aria-valuenow`: scala.Int | scala.Double = null,
    `aria-valuetext`: java.lang.String = null,
    ascent: scala.Double | java.lang.String = null,
    attributeName: java.lang.String = null,
    attributeType: java.lang.String = null,
    autoReverse: scala.Double | java.lang.String = null,
    azimuth: scala.Double | java.lang.String = null,
    baseFrequency: scala.Double | java.lang.String = null,
    baseProfile: scala.Double | java.lang.String = null,
    baselineShift: scala.Double | java.lang.String = null,
    bbox: scala.Double | java.lang.String = null,
    begin: scala.Double | java.lang.String = null,
    bias: scala.Double | java.lang.String = null,
    by: scala.Double | java.lang.String = null,
    calcMode: scala.Double | java.lang.String = null,
    capHeight: scala.Double | java.lang.String = null,
    children: reactLib.reactMod.ReactNode = null,
    className: java.lang.String = null,
    classes: atMaterialDashUiCoreLib.PartialClassNameMapSvgIconClassKey = null,
    clip: scala.Double | java.lang.String = null,
    clipPath: java.lang.String = null,
    clipPathUnits: scala.Double | java.lang.String = null,
    clipRule: scala.Double | java.lang.String = null,
    color: atMaterialDashUiCoreLib.atMaterialDashUiCoreMod.PropTypesNs.Color | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.action | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.disabled | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.error = null,
    colorInterpolation: scala.Double | java.lang.String = null,
    colorInterpolationFilters: atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.auto | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.sRGB | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.linearRGB | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.inherit = null,
    colorProfile: scala.Double | java.lang.String = null,
    colorRendering: scala.Double | java.lang.String = null,
    component: reactLib.reactMod.ReactType[SvgIconProps] = null,
    contentScriptType: scala.Double | java.lang.String = null,
    contentStyleType: scala.Double | java.lang.String = null,
    cursor: scala.Double | java.lang.String = null,
    cx: scala.Double | java.lang.String = null,
    cy: scala.Double | java.lang.String = null,
    d: java.lang.String = null,
    dangerouslySetInnerHTML: reactLib.Anon_Html = null,
    decelerate: scala.Double | java.lang.String = null,
    descent: scala.Double | java.lang.String = null,
    diffuseConstant: scala.Double | java.lang.String = null,
    direction: scala.Double | java.lang.String = null,
    display: scala.Double | java.lang.String = null,
    divisor: scala.Double | java.lang.String = null,
    dominantBaseline: scala.Double | java.lang.String = null,
    dur: scala.Double | java.lang.String = null,
    dx: scala.Double | java.lang.String = null,
    dy: scala.Double | java.lang.String = null,
    edgeMode: scala.Double | java.lang.String = null,
    elevation: scala.Double | java.lang.String = null,
    enableBackground: scala.Double | java.lang.String = null,
    end: scala.Double | java.lang.String = null,
    exponent: scala.Double | java.lang.String = null,
    externalResourcesRequired: scala.Double | java.lang.String = null,
    fill: java.lang.String = null,
    fillOpacity: scala.Double | java.lang.String = null,
    fillRule: atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.nonzero | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.evenodd | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.inherit = null,
    filter: java.lang.String = null,
    filterRes: scala.Double | java.lang.String = null,
    filterUnits: scala.Double | java.lang.String = null,
    floodColor: scala.Double | java.lang.String = null,
    floodOpacity: scala.Double | java.lang.String = null,
    focusable: scala.Double | java.lang.String = null,
    fontFamily: java.lang.String = null,
    fontSize: atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.inherit | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.default | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.small | atMaterialDashUiCoreLib.atMaterialDashUiCoreLibStrings.large = null,
    fontSizeAdjust: scala.Double | java.lang.String = null,
    fontStretch: scala.Double | java.lang.String = null,
    fontStyle: scala.Double | java.lang.String = null,
    fontVariant: scala.Double | java.lang.String = null,
    fontWeight: scala.Double | java.lang.String = null,
    format: scala.Double | java.lang.String = null,
    from: scala.Double | java.lang.String = null,
    fx: scala.Double | java.lang.String = null,
    fy: scala.Double | java.lang.String = null,
    g1: scala.Double | java.lang.String = null,
    g2: scala.Double | java.lang.String = null,
    glyphName: scala.Double | java.lang.String = null,
    glyphOrientationHorizontal: scala.Double | java.lang.String = null,
    glyphOrientationVertical: scala.Double | java.lang.String = null,
    glyphRef: scala.Double | java.lang.String = null,
    gradientTransform: java.lang.String = null,
    gradientUnits: java.lang.String = null,
    hanging: scala.Double | java.lang.String = null,
    height: scala.Double | java.lang.String = null,
    horizAdvX: scala.Double | java.lang.String = null,
    horizOriginX: scala.Double | java.lang.String = null,
    href: java.lang.String = null,
    id: java.lang.String = null,
    ideographic: scala.Double | java.lang.String = null,
    imageRendering: scala.Double | java.lang.String = null,
    in: java.lang.String = null,
    in2: scala.Double | java.lang.String = null,
    innerRef: reactLib.reactMod.Ref[_] | reactLib.reactMod.RefObject[_] = null,
    intercept: scala.Double | java.lang.String = null,
    k: scala.Double | java.lang.String = null,
    k1: scala.Double | java.lang.String = null,
    k2: scala.Double | java.lang.String = null,
    k3: scala.Double | java.lang.String = null,
    k4: scala.Double | java.lang.String = null,
    kernelMatrix: scala.Double | java.lang.String = null,
    kernelUnitLength: scala.Double | java.lang.String = null,
    kerning: scala.Double | java.lang.String = null,
    key: reactLib.reactMod.Key = null,
    keyPoints: scala.Double | java.lang.String = null,
    keySplines: scala.Double | java.lang.String = null,
    keyTimes: scala.Double | java.lang.String = null,
    lang: java.lang.String = null,
    lengthAdjust: scala.Double | java.lang.String = null,
    letterSpacing: scala.Double | java.lang.String = null,
    lightingColor: scala.Double | java.lang.String = null,
    limitingConeAngle: scala.Double | java.lang.String = null,
    local: scala.Double | java.lang.String = null,
    markerEnd: java.lang.String = null,
    markerHeight: scala.Double | java.lang.String = null,
    markerMid: java.lang.String = null,
    markerStart: java.lang.String = null,
    markerUnits: scala.Double | java.lang.String = null,
    markerWidth: scala.Double | java.lang.String = null,
    mask: java.lang.String = null,
    maskContentUnits: scala.Double | java.lang.String = null,
    maskUnits: scala.Double | java.lang.String = null,
    mathematical: scala.Double | java.lang.String = null,
    max: scala.Double | java.lang.String = null,
    media: java.lang.String = null,
    method: java.lang.String = null,
    min: scala.Double | java.lang.String = null,
    mode: scala.Double | java.lang.String = null,
    name: java.lang.String = null,
    nativeColor: java.lang.String = null,
    numOctaves: scala.Double | java.lang.String = null,
    offset: scala.Double | java.lang.String = null,
    onAbort: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onAnimationEnd: reactLib.reactMod.AnimationEventHandler[stdLib.SVGSVGElement] = null,
    onAnimationIteration: reactLib.reactMod.AnimationEventHandler[stdLib.SVGSVGElement] = null,
    onAnimationStart: reactLib.reactMod.AnimationEventHandler[stdLib.SVGSVGElement] = null,
    onAuxClick: reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement] = null,
    onBeforeInput: reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement] = null,
    onBlur: reactLib.reactMod.FocusEventHandler[stdLib.SVGSVGElement] = null,
    onCanPlay: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onCanPlayThrough: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onChange: reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement] = null,
    onClick: reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement] = null,
    onCompositionEnd: reactLib.reactMod.CompositionEventHandler[stdLib.SVGSVGElement] = null,
    onCompositionStart: reactLib.reactMod.CompositionEventHandler[stdLib.SVGSVGElement] = null,
    onCompositionUpdate: reactLib.reactMod.CompositionEventHandler[stdLib.SVGSVGElement] = null,
    onContextMenu: reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement] = null,
    onCopy: reactLib.reactMod.ClipboardEventHandler[stdLib.SVGSVGElement] = null,
    onCut: reactLib.reactMod.ClipboardEventHandler[stdLib.SVGSVGElement] = null,
    onDoubleClick: reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement] = null,
    onDrag: reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement] = null,
    onDragEnd: reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement] = null,
    onDragEnter: reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement] = null,
    onDragExit: reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement] = null,
    onDragLeave: reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement] = null,
    onDragOver: reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement] = null,
    onDragStart: reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement] = null,
    onDrop: reactLib.reactMod.DragEventHandler[stdLib.SVGSVGElement] = null,
    onDurationChange: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onEmptied: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onEncrypted: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onEnded: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onError: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onFocus: reactLib.reactMod.FocusEventHandler[stdLib.SVGSVGElement] = null,
    onInput: reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement] = null,
    onInvalid: reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement] = null,
    onKeyDown: reactLib.reactMod.KeyboardEventHandler[stdLib.SVGSVGElement] = null,
    onKeyPress: reactLib.reactMod.KeyboardEventHandler[stdLib.SVGSVGElement] = null,
    onKeyUp: reactLib.reactMod.KeyboardEventHandler[stdLib.SVGSVGElement] = null,
    onLoad: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onLoadStart: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onLoadedData: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onLoadedMetadata: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onMouseDown: reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement] = null,
    onMouseEnter: reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement] = null,
    onMouseLeave: reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement] = null,
    onMouseMove: reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement] = null,
    onMouseOut: reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement] = null,
    onMouseOver: reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement] = null,
    onMouseUp: reactLib.reactMod.MouseEventHandler[stdLib.SVGSVGElement] = null,
    onPaste: reactLib.reactMod.ClipboardEventHandler[stdLib.SVGSVGElement] = null,
    onPause: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onPlay: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onPlaying: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onPointerCancel: reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement] = null,
    onPointerDown: reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement] = null,
    onPointerEnter: reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement] = null,
    onPointerLeave: reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement] = null,
    onPointerMove: reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement] = null,
    onPointerOut: reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement] = null,
    onPointerOver: reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement] = null,
    onPointerUp: reactLib.reactMod.PointerEventHandler[stdLib.SVGSVGElement] = null,
    onProgress: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onRateChange: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onReset: reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement] = null,
    onScroll: reactLib.reactMod.UIEventHandler[stdLib.SVGSVGElement] = null,
    onSeeked: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onSeeking: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onSelect: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onStalled: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onSubmit: reactLib.reactMod.FormEventHandler[stdLib.SVGSVGElement] = null,
    onSuspend: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null,
    onTimeUpdate: reactLib.reactMod.ReactEventHandler[stdLib.SVGSVGElement] = null
  ): SvgIconProps = {
    val __obj = js.Dynamic.literal()
    if (accentHeight != null) __obj.updateDynamic("accentHeight")(accentHeight.asInstanceOf[js.Any])
    if (accumulate != null) __obj.updateDynamic("accumulate")(accumulate.asInstanceOf[js.Any])
    if (additive != null) __obj.updateDynamic("additive")(additive.asInstanceOf[js.Any])
    if (alignmentBaseline != null) __obj.updateDynamic("alignmentBaseline")(alignmentBaseline.asInstanceOf[js.Any])
    if (allowReorder != null) __obj.updateDynamic("allowReorder")(allowReorder.asInstanceOf[js.Any])
    if (alphabetic != null) __obj.updateDynamic("alphabetic")(alphabetic.asInstanceOf[js.Any])
    if (amplitude != null) __obj.updateDynamic("amplitude")(amplitude.asInstanceOf[js.Any])
    if (arabicForm != null) __obj.updateDynamic("arabicForm")(arabicForm.asInstanceOf[js.Any])
    if (`aria-activedescendant` != null) __obj.updateDynamic("aria-activedescendant")(`aria-activedescendant`)
    if (!js.isUndefined(`aria-atomic`)) __obj.updateDynamic("aria-atomic")(`aria-atomic`)
    if (`aria-autocomplete` != null) __obj.updateDynamic("aria-autocomplete")(`aria-autocomplete`.asInstanceOf[js.Any])
    if (!js.isUndefined(`aria-busy`)) __obj.updateDynamic("aria-busy")(`aria-busy`)
    if (`aria-checked` != null) __obj.updateDynamic("aria-checked")(`aria-checked`.asInstanceOf[js.Any])
    if (`aria-colcount` != null) __obj.updateDynamic("aria-colcount")(`aria-colcount`.asInstanceOf[js.Any])
    if (`aria-colindex` != null) __obj.updateDynamic("aria-colindex")(`aria-colindex`.asInstanceOf[js.Any])
    if (`aria-colspan` != null) __obj.updateDynamic("aria-colspan")(`aria-colspan`.asInstanceOf[js.Any])
    if (`aria-controls` != null) __obj.updateDynamic("aria-controls")(`aria-controls`)
    if (`aria-current` != null) __obj.updateDynamic("aria-current")(`aria-current`.asInstanceOf[js.Any])
    if (`aria-describedby` != null) __obj.updateDynamic("aria-describedby")(`aria-describedby`)
    if (`aria-details` != null) __obj.updateDynamic("aria-details")(`aria-details`)
    if (!js.isUndefined(`aria-disabled`)) __obj.updateDynamic("aria-disabled")(`aria-disabled`)
    if (`aria-dropeffect` != null) __obj.updateDynamic("aria-dropeffect")(`aria-dropeffect`.asInstanceOf[js.Any])
    if (`aria-errormessage` != null) __obj.updateDynamic("aria-errormessage")(`aria-errormessage`)
    if (!js.isUndefined(`aria-expanded`)) __obj.updateDynamic("aria-expanded")(`aria-expanded`)
    if (`aria-flowto` != null) __obj.updateDynamic("aria-flowto")(`aria-flowto`)
    if (!js.isUndefined(`aria-grabbed`)) __obj.updateDynamic("aria-grabbed")(`aria-grabbed`)
    if (`aria-haspopup` != null) __obj.updateDynamic("aria-haspopup")(`aria-haspopup`.asInstanceOf[js.Any])
    if (!js.isUndefined(`aria-hidden`)) __obj.updateDynamic("aria-hidden")(`aria-hidden`)
    if (`aria-invalid` != null) __obj.updateDynamic("aria-invalid")(`aria-invalid`.asInstanceOf[js.Any])
    if (`aria-keyshortcuts` != null) __obj.updateDynamic("aria-keyshortcuts")(`aria-keyshortcuts`)
    if (`aria-label` != null) __obj.updateDynamic("aria-label")(`aria-label`)
    if (`aria-labelledby` != null) __obj.updateDynamic("aria-labelledby")(`aria-labelledby`)
    if (`aria-level` != null) __obj.updateDynamic("aria-level")(`aria-level`.asInstanceOf[js.Any])
    if (`aria-live` != null) __obj.updateDynamic("aria-live")(`aria-live`.asInstanceOf[js.Any])
    if (!js.isUndefined(`aria-modal`)) __obj.updateDynamic("aria-modal")(`aria-modal`)
    if (!js.isUndefined(`aria-multiline`)) __obj.updateDynamic("aria-multiline")(`aria-multiline`)
    if (!js.isUndefined(`aria-multiselectable`)) __obj.updateDynamic("aria-multiselectable")(`aria-multiselectable`)
    if (`aria-orientation` != null) __obj.updateDynamic("aria-orientation")(`aria-orientation`.asInstanceOf[js.Any])
    if (`aria-owns` != null) __obj.updateDynamic("aria-owns")(`aria-owns`)
    if (`aria-placeholder` != null) __obj.updateDynamic("aria-placeholder")(`aria-placeholder`)
    if (`aria-posinset` != null) __obj.updateDynamic("aria-posinset")(`aria-posinset`.asInstanceOf[js.Any])
    if (`aria-pressed` != null) __obj.updateDynamic("aria-pressed")(`aria-pressed`.asInstanceOf[js.Any])
    if (!js.isUndefined(`aria-readonly`)) __obj.updateDynamic("aria-readonly")(`aria-readonly`)
    if (`aria-relevant` != null) __obj.updateDynamic("aria-relevant")(`aria-relevant`.asInstanceOf[js.Any])
    if (!js.isUndefined(`aria-required`)) __obj.updateDynamic("aria-required")(`aria-required`)
    if (`aria-roledescription` != null) __obj.updateDynamic("aria-roledescription")(`aria-roledescription`)
    if (`aria-rowcount` != null) __obj.updateDynamic("aria-rowcount")(`aria-rowcount`.asInstanceOf[js.Any])
    if (`aria-rowindex` != null) __obj.updateDynamic("aria-rowindex")(`aria-rowindex`.asInstanceOf[js.Any])
    if (`aria-rowspan` != null) __obj.updateDynamic("aria-rowspan")(`aria-rowspan`.asInstanceOf[js.Any])
    if (!js.isUndefined(`aria-selected`)) __obj.updateDynamic("aria-selected")(`aria-selected`)
    if (`aria-setsize` != null) __obj.updateDynamic("aria-setsize")(`aria-setsize`.asInstanceOf[js.Any])
    if (`aria-sort` != null) __obj.updateDynamic("aria-sort")(`aria-sort`.asInstanceOf[js.Any])
    if (`aria-valuemax` != null) __obj.updateDynamic("aria-valuemax")(`aria-valuemax`.asInstanceOf[js.Any])
    if (`aria-valuemin` != null) __obj.updateDynamic("aria-valuemin")(`aria-valuemin`.asInstanceOf[js.Any])
    if (`aria-valuenow` != null) __obj.updateDynamic("aria-valuenow")(`aria-valuenow`.asInstanceOf[js.Any])
    if (`aria-valuetext` != null) __obj.updateDynamic("aria-valuetext")(`aria-valuetext`)
    if (ascent != null) __obj.updateDynamic("ascent")(ascent.asInstanceOf[js.Any])
    if (attributeName != null) __obj.updateDynamic("attributeName")(attributeName)
    if (attributeType != null) __obj.updateDynamic("attributeType")(attributeType)
    if (autoReverse != null) __obj.updateDynamic("autoReverse")(autoReverse.asInstanceOf[js.Any])
    if (azimuth != null) __obj.updateDynamic("azimuth")(azimuth.asInstanceOf[js.Any])
    if (baseFrequency != null) __obj.updateDynamic("baseFrequency")(baseFrequency.asInstanceOf[js.Any])
    if (baseProfile != null) __obj.updateDynamic("baseProfile")(baseProfile.asInstanceOf[js.Any])
    if (baselineShift != null) __obj.updateDynamic("baselineShift")(baselineShift.asInstanceOf[js.Any])
    if (bbox != null) __obj.updateDynamic("bbox")(bbox.asInstanceOf[js.Any])
    if (begin != null) __obj.updateDynamic("begin")(begin.asInstanceOf[js.Any])
    if (bias != null) __obj.updateDynamic("bias")(bias.asInstanceOf[js.Any])
    if (by != null) __obj.updateDynamic("by")(by.asInstanceOf[js.Any])
    if (calcMode != null) __obj.updateDynamic("calcMode")(calcMode.asInstanceOf[js.Any])
    if (capHeight != null) __obj.updateDynamic("capHeight")(capHeight.asInstanceOf[js.Any])
    if (children != null) __obj.updateDynamic("children")(children.asInstanceOf[js.Any])
    if (className != null) __obj.updateDynamic("className")(className)
    if (classes != null) __obj.updateDynamic("classes")(classes)
    if (clip != null) __obj.updateDynamic("clip")(clip.asInstanceOf[js.Any])
    if (clipPath != null) __obj.updateDynamic("clipPath")(clipPath)
    if (clipPathUnits != null) __obj.updateDynamic("clipPathUnits")(clipPathUnits.asInstanceOf[js.Any])
    if (clipRule != null) __obj.updateDynamic("clipRule")(clipRule.asInstanceOf[js.Any])
    if (color != null) __obj.updateDynamic("color")(color.asInstanceOf[js.Any])
    if (colorInterpolation != null) __obj.updateDynamic("colorInterpolation")(colorInterpolation.asInstanceOf[js.Any])
    if (colorInterpolationFilters != null) __obj.updateDynamic("colorInterpolationFilters")(colorInterpolationFilters.asInstanceOf[js.Any])
    if (colorProfile != null) __obj.updateDynamic("colorProfile")(colorProfile.asInstanceOf[js.Any])
    if (colorRendering != null) __obj.updateDynamic("colorRendering")(colorRendering.asInstanceOf[js.Any])
    if (component != null) __obj.updateDynamic("component")(component.asInstanceOf[js.Any])
    if (contentScriptType != null) __obj.updateDynamic("contentScriptType")(contentScriptType.asInstanceOf[js.Any])
    if (contentStyleType != null) __obj.updateDynamic("contentStyleType")(contentStyleType.asInstanceOf[js.Any])
    if (cursor != null) __obj.updateDynamic("cursor")(cursor.asInstanceOf[js.Any])
    if (cx != null) __obj.updateDynamic("cx")(cx.asInstanceOf[js.Any])
    if (cy != null) __obj.updateDynamic("cy")(cy.asInstanceOf[js.Any])
    if (d != null) __obj.updateDynamic("d")(d)
    if (dangerouslySetInnerHTML != null) __obj.updateDynamic("dangerouslySetInnerHTML")(dangerouslySetInnerHTML)
    if (decelerate != null) __obj.updateDynamic("decelerate")(decelerate.asInstanceOf[js.Any])
    if (descent != null) __obj.updateDynamic("descent")(descent.asInstanceOf[js.Any])
    if (diffuseConstant != null) __obj.updateDynamic("diffuseConstant")(diffuseConstant.asInstanceOf[js.Any])
    if (direction != null) __obj.updateDynamic("direction")(direction.asInstanceOf[js.Any])
    if (display != null) __obj.updateDynamic("display")(display.asInstanceOf[js.Any])
    if (divisor != null) __obj.updateDynamic("divisor")(divisor.asInstanceOf[js.Any])
    if (dominantBaseline != null) __obj.updateDynamic("dominantBaseline")(dominantBaseline.asInstanceOf[js.Any])
    if (dur != null) __obj.updateDynamic("dur")(dur.asInstanceOf[js.Any])
    if (dx != null) __obj.updateDynamic("dx")(dx.asInstanceOf[js.Any])
    if (dy != null) __obj.updateDynamic("dy")(dy.asInstanceOf[js.Any])
    if (edgeMode != null) __obj.updateDynamic("edgeMode")(edgeMode.asInstanceOf[js.Any])
    if (elevation != null) __obj.updateDynamic("elevation")(elevation.asInstanceOf[js.Any])
    if (enableBackground != null) __obj.updateDynamic("enableBackground")(enableBackground.asInstanceOf[js.Any])
    if (end != null) __obj.updateDynamic("end")(end.asInstanceOf[js.Any])
    if (exponent != null) __obj.updateDynamic("exponent")(exponent.asInstanceOf[js.Any])
    if (externalResourcesRequired != null) __obj.updateDynamic("externalResourcesRequired")(externalResourcesRequired.asInstanceOf[js.Any])
    if (fill != null) __obj.updateDynamic("fill")(fill)
    if (fillOpacity != null) __obj.updateDynamic("fillOpacity")(fillOpacity.asInstanceOf[js.Any])
    if (fillRule != null) __obj.updateDynamic("fillRule")(fillRule.asInstanceOf[js.Any])
    if (filter != null) __obj.updateDynamic("filter")(filter)
    if (filterRes != null) __obj.updateDynamic("filterRes")(filterRes.asInstanceOf[js.Any])
    if (filterUnits != null) __obj.updateDynamic("filterUnits")(filterUnits.asInstanceOf[js.Any])
    if (floodColor != null) __obj.updateDynamic("floodColor")(floodColor.asInstanceOf[js.Any])
    if (floodOpacity != null) __obj.updateDynamic("floodOpacity")(floodOpacity.asInstanceOf[js.Any])
    if (focusable != null) __obj.updateDynamic("focusable")(focusable.asInstanceOf[js.Any])
    if (fontFamily != null) __obj.updateDynamic("fontFamily")(fontFamily)
    if (fontSize != null) __obj.updateDynamic("fontSize")(fontSize.asInstanceOf[js.Any])
    if (fontSizeAdjust != null) __obj.updateDynamic("fontSizeAdjust")(fontSizeAdjust.asInstanceOf[js.Any])
    if (fontStretch != null) __obj.updateDynamic("fontStretch")(fontStretch.asInstanceOf[js.Any])
    if (fontStyle != null) __obj.updateDynamic("fontStyle")(fontStyle.asInstanceOf[js.Any])
    if (fontVariant != null) __obj.updateDynamic("fontVariant")(fontVariant.asInstanceOf[js.Any])
    if (fontWeight != null) __obj.updateDynamic("fontWeight")(fontWeight.asInstanceOf[js.Any])
    if (format != null) __obj.updateDynamic("format")(format.asInstanceOf[js.Any])
    if (from != null) __obj.updateDynamic("from")(from.asInstanceOf[js.Any])
    if (fx != null) __obj.updateDynamic("fx")(fx.asInstanceOf[js.Any])
    if (fy != null) __obj.updateDynamic("fy")(fy.asInstanceOf[js.Any])
    if (g1 != null) __obj.updateDynamic("g1")(g1.asInstanceOf[js.Any])
    if (g2 != null) __obj.updateDynamic("g2")(g2.asInstanceOf[js.Any])
    if (glyphName != null) __obj.updateDynamic("glyphName")(glyphName.asInstanceOf[js.Any])
    if (glyphOrientationHorizontal != null) __obj.updateDynamic("glyphOrientationHorizontal")(glyphOrientationHorizontal.asInstanceOf[js.Any])
    if (glyphOrientationVertical != null) __obj.updateDynamic("glyphOrientationVertical")(glyphOrientationVertical.asInstanceOf[js.Any])
    if (glyphRef != null) __obj.updateDynamic("glyphRef")(glyphRef.asInstanceOf[js.Any])
    if (gradientTransform != null) __obj.updateDynamic("gradientTransform")(gradientTransform)
    if (gradientUnits != null) __obj.updateDynamic("gradientUnits")(gradientUnits)
    if (hanging != null) __obj.updateDynamic("hanging")(hanging.asInstanceOf[js.Any])
    if (height != null) __obj.updateDynamic("height")(height.asInstanceOf[js.Any])
    if (horizAdvX != null) __obj.updateDynamic("horizAdvX")(horizAdvX.asInstanceOf[js.Any])
    if (horizOriginX != null) __obj.updateDynamic("horizOriginX")(horizOriginX.asInstanceOf[js.Any])
    if (href != null) __obj.updateDynamic("href")(href)
    if (id != null) __obj.updateDynamic("id")(id)
    if (ideographic != null) __obj.updateDynamic("ideographic")(ideographic.asInstanceOf[js.Any])
    if (imageRendering != null) __obj.updateDynamic("imageRendering")(imageRendering.asInstanceOf[js.Any])
    if (in != null) __obj.updateDynamic("in")(in)
    if (in2 != null) __obj.updateDynamic("in2")(in2.asInstanceOf[js.Any])
    if (innerRef != null) __obj.updateDynamic("innerRef")(innerRef.asInstanceOf[js.Any])
    if (intercept != null) __obj.updateDynamic("intercept")(intercept.asInstanceOf[js.Any])
    if (k != null) __obj.updateDynamic("k")(k.asInstanceOf[js.Any])
    if (k1 != null) __obj.updateDynamic("k1")(k1.asInstanceOf[js.Any])
    if (k2 != null) __obj.updateDynamic("k2")(k2.asInstanceOf[js.Any])
    if (k3 != null) __obj.updateDynamic("k3")(k3.asInstanceOf[js.Any])
    if (k4 != null) __obj.updateDynamic("k4")(k4.asInstanceOf[js.Any])
    if (kernelMatrix != null) __obj.updateDynamic("kernelMatrix")(kernelMatrix.asInstanceOf[js.Any])
    if (kernelUnitLength != null) __obj.updateDynamic("kernelUnitLength")(kernelUnitLength.asInstanceOf[js.Any])
    if (kerning != null) __obj.updateDynamic("kerning")(kerning.asInstanceOf[js.Any])
    if (key != null) __obj.updateDynamic("key")(key.asInstanceOf[js.Any])
    if (keyPoints != null) __obj.updateDynamic("keyPoints")(keyPoints.asInstanceOf[js.Any])
    if (keySplines != null) __obj.updateDynamic("keySplines")(keySplines.asInstanceOf[js.Any])
    if (keyTimes != null) __obj.updateDynamic("keyTimes")(keyTimes.asInstanceOf[js.Any])
    if (lang != null) __obj.updateDynamic("lang")(lang)
    if (lengthAdjust != null) __obj.updateDynamic("lengthAdjust")(lengthAdjust.asInstanceOf[js.Any])
    if (letterSpacing != null) __obj.updateDynamic("letterSpacing")(letterSpacing.asInstanceOf[js.Any])
    if (lightingColor != null) __obj.updateDynamic("lightingColor")(lightingColor.asInstanceOf[js.Any])
    if (limitingConeAngle != null) __obj.updateDynamic("limitingConeAngle")(limitingConeAngle.asInstanceOf[js.Any])
    if (local != null) __obj.updateDynamic("local")(local.asInstanceOf[js.Any])
    if (markerEnd != null) __obj.updateDynamic("markerEnd")(markerEnd)
    if (markerHeight != null) __obj.updateDynamic("markerHeight")(markerHeight.asInstanceOf[js.Any])
    if (markerMid != null) __obj.updateDynamic("markerMid")(markerMid)
    if (markerStart != null) __obj.updateDynamic("markerStart")(markerStart)
    if (markerUnits != null) __obj.updateDynamic("markerUnits")(markerUnits.asInstanceOf[js.Any])
    if (markerWidth != null) __obj.updateDynamic("markerWidth")(markerWidth.asInstanceOf[js.Any])
    if (mask != null) __obj.updateDynamic("mask")(mask)
    if (maskContentUnits != null) __obj.updateDynamic("maskContentUnits")(maskContentUnits.asInstanceOf[js.Any])
    if (maskUnits != null) __obj.updateDynamic("maskUnits")(maskUnits.asInstanceOf[js.Any])
    if (mathematical != null) __obj.updateDynamic("mathematical")(mathematical.asInstanceOf[js.Any])
    if (max != null) __obj.updateDynamic("max")(max.asInstanceOf[js.Any])
    if (media != null) __obj.updateDynamic("media")(media)
    if (method != null) __obj.updateDynamic("method")(method)
    if (min != null) __obj.updateDynamic("min")(min.asInstanceOf[js.Any])
    if (mode != null) __obj.updateDynamic("mode")(mode.asInstanceOf[js.Any])
    if (name != null) __obj.updateDynamic("name")(name)
    if (nativeColor != null) __obj.updateDynamic("nativeColor")(nativeColor)
    if (numOctaves != null) __obj.updateDynamic("numOctaves")(numOctaves.asInstanceOf[js.Any])
    if (offset != null) __obj.updateDynamic("offset")(offset.asInstanceOf[js.Any])
    if (onAbort != null) __obj.updateDynamic("onAbort")(onAbort)
    if (onAnimationEnd != null) __obj.updateDynamic("onAnimationEnd")(onAnimationEnd)
    if (onAnimationIteration != null) __obj.updateDynamic("onAnimationIteration")(onAnimationIteration)
    if (onAnimationStart != null) __obj.updateDynamic("onAnimationStart")(onAnimationStart)
    if (onAuxClick != null) __obj.updateDynamic("onAuxClick")(onAuxClick)
    if (onBeforeInput != null) __obj.updateDynamic("onBeforeInput")(onBeforeInput)
    if (onBlur != null) __obj.updateDynamic("onBlur")(onBlur)
    if (onCanPlay != null) __obj.updateDynamic("onCanPlay")(onCanPlay)
    if (onCanPlayThrough != null) __obj.updateDynamic("onCanPlayThrough")(onCanPlayThrough)
    if (onChange != null) __obj.updateDynamic("onChange")(onChange)
    if (onClick != null) __obj.updateDynamic("onClick")(onClick)
    if (onCompositionEnd != null) __obj.updateDynamic("onCompositionEnd")(onCompositionEnd)
    if (onCompositionStart != null) __obj.updateDynamic("onCompositionStart")(onCompositionStart)
    if (onCompositionUpdate != null) __obj.updateDynamic("onCompositionUpdate")(onCompositionUpdate)
    if (onContextMenu != null) __obj.updateDynamic("onContextMenu")(onContextMenu)
    if (onCopy != null) __obj.updateDynamic("onCopy")(onCopy)
    if (onCut != null) __obj.updateDynamic("onCut")(onCut)
    if (onDoubleClick != null) __obj.updateDynamic("onDoubleClick")(onDoubleClick)
    if (onDrag != null) __obj.updateDynamic("onDrag")(onDrag)
    if (onDragEnd != null) __obj.updateDynamic("onDragEnd")(onDragEnd)
    if (onDragEnter != null) __obj.updateDynamic("onDragEnter")(onDragEnter)
    if (onDragExit != null) __obj.updateDynamic("onDragExit")(onDragExit)
    if (onDragLeave != null) __obj.updateDynamic("onDragLeave")(onDragLeave)
    if (onDragOver != null) __obj.updateDynamic("onDragOver")(onDragOver)
    if (onDragStart != null) __obj.updateDynamic("onDragStart")(onDragStart)
    if (onDrop != null) __obj.updateDynamic("onDrop")(onDrop)
    if (onDurationChange != null) __obj.updateDynamic("onDurationChange")(onDurationChange)
    if (onEmptied != null) __obj.updateDynamic("onEmptied")(onEmptied)
    if (onEncrypted != null) __obj.updateDynamic("onEncrypted")(onEncrypted)
    if (onEnded != null) __obj.updateDynamic("onEnded")(onEnded)
    if (onError != null) __obj.updateDynamic("onError")(onError)
    if (onFocus != null) __obj.updateDynamic("onFocus")(onFocus)
    if (onInput != null) __obj.updateDynamic("onInput")(onInput)
    if (onInvalid != null) __obj.updateDynamic("onInvalid")(onInvalid)
    if (onKeyDown != null) __obj.updateDynamic("onKeyDown")(onKeyDown)
    if (onKeyPress != null) __obj.updateDynamic("onKeyPress")(onKeyPress)
    if (onKeyUp != null) __obj.updateDynamic("onKeyUp")(onKeyUp)
    if (onLoad != null) __obj.updateDynamic("onLoad")(onLoad)
    if (onLoadStart != null) __obj.updateDynamic("onLoadStart")(onLoadStart)
    if (onLoadedData != null) __obj.updateDynamic("onLoadedData")(onLoadedData)
    if (onLoadedMetadata != null) __obj.updateDynamic("onLoadedMetadata")(onLoadedMetadata)
    if (onMouseDown != null) __obj.updateDynamic("onMouseDown")(onMouseDown)
    if (onMouseEnter != null) __obj.updateDynamic("onMouseEnter")(onMouseEnter)
    if (onMouseLeave != null) __obj.updateDynamic("onMouseLeave")(onMouseLeave)
    if (onMouseMove != null) __obj.updateDynamic("onMouseMove")(onMouseMove)
    if (onMouseOut != null) __obj.updateDynamic("onMouseOut")(onMouseOut)
    if (onMouseOver != null) __obj.updateDynamic("onMouseOver")(onMouseOver)
    if (onMouseUp != null) __obj.updateDynamic("onMouseUp")(onMouseUp)
    if (onPaste != null) __obj.updateDynamic("onPaste")(onPaste)
    if (onPause != null) __obj.updateDynamic("onPause")(onPause)
    if (onPlay != null) __obj.updateDynamic("onPlay")(onPlay)
    if (onPlaying != null) __obj.updateDynamic("onPlaying")(onPlaying)
    if (onPointerCancel != null) __obj.updateDynamic("onPointerCancel")(onPointerCancel)
    if (onPointerDown != null) __obj.updateDynamic("onPointerDown")(onPointerDown)
    if (onPointerEnter != null) __obj.updateDynamic("onPointerEnter")(onPointerEnter)
    if (onPointerLeave != null) __obj.updateDynamic("onPointerLeave")(onPointerLeave)
    if (onPointerMove != null) __obj.updateDynamic("onPointerMove")(onPointerMove)
    if (onPointerOut != null) __obj.updateDynamic("onPointerOut")(onPointerOut)
    if (onPointerOver != null) __obj.updateDynamic("onPointerOver")(onPointerOver)
    if (onPointerUp != null) __obj.updateDynamic("onPointerUp")(onPointerUp)
    if (onProgress != null) __obj.updateDynamic("onProgress")(onProgress)
    if (onRateChange != null) __obj.updateDynamic("onRateChange")(onRateChange)
    if (onReset != null) __obj.updateDynamic("onReset")(onReset)
    if (onScroll != null) __obj.updateDynamic("onScroll")(onScroll)
    if (onSeeked != null) __obj.updateDynamic("onSeeked")(onSeeked)
    if (onSeeking != null) __obj.updateDynamic("onSeeking")(onSeeking)
    if (onSelect != null) __obj.updateDynamic("onSelect")(onSelect)
    if (onStalled != null) __obj.updateDynamic("onStalled")(onStalled)
    if (onSubmit != null) __obj.updateDynamic("onSubmit")(onSubmit)
    if (onSuspend != null) __obj.updateDynamic("onSuspend")(onSuspend)
    if (onTimeUpdate != null) __obj.updateDynamic("onTimeUpdate")(onTimeUpdate)
    __obj.asInstanceOf[SvgIconProps]
  }
}

