package typings
package semanticDashUiDashTabLib.SemanticUINs

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object TabSettingsNs {
  type Param = ((stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.auto]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.deactivate]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.history]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.ignoreFirstLoad]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.evaluateScripts]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.alwaysRefresh]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.cacheType]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.cache]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.apiSettings]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.historyType]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.path]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.context]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.childrenOnly]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.maxDepth]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.loadOnce]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.onFirstLoad]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.onLoad]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.onRequest]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.onVisible]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.templates]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.selector]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.metadata]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.className]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.error]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.namespace]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.name]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.silent]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.debug]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.performance]) | (stdLib.Pick[_Impl, semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.verbose])) with (stdLib.Partial[
    stdLib.Pick[
      _Impl, 
      semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.auto | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.deactivate | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.history | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.ignoreFirstLoad | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.evaluateScripts | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.alwaysRefresh | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.cacheType | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.cache | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.apiSettings | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.historyType | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.path | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.context | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.childrenOnly | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.maxDepth | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.loadOnce | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.templates | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.selector | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.metadata | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.className | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.error | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.namespace | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.name | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.silent | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.debug | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.performance | semanticDashUiDashTabLib.semanticDashUiDashTabLibStrings.verbose
    ]
  ])
}
