package typings
package astDashTypesLib.genKindsMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - astDashTypesLib.genNodesMod.Identifier
  - astDashTypesLib.genNodesMod.FunctionExpression
  - astDashTypesLib.genNodesMod.ThisExpression
  - astDashTypesLib.genNodesMod.ArrayExpression
  - astDashTypesLib.genNodesMod.ObjectExpression
  - astDashTypesLib.genNodesMod.Literal
  - astDashTypesLib.genNodesMod.SequenceExpression
  - astDashTypesLib.genNodesMod.UnaryExpression
  - astDashTypesLib.genNodesMod.BinaryExpression
  - astDashTypesLib.genNodesMod.AssignmentExpression
  - astDashTypesLib.genNodesMod.UpdateExpression
  - astDashTypesLib.genNodesMod.LogicalExpression
  - astDashTypesLib.genNodesMod.ConditionalExpression
  - astDashTypesLib.genNodesMod.NewExpression
  - astDashTypesLib.genNodesMod.CallExpression
  - astDashTypesLib.genNodesMod.MemberExpression
  - astDashTypesLib.genNodesMod.RestElement
  - astDashTypesLib.genNodesMod.SpreadElementPattern
  - astDashTypesLib.genNodesMod.ArrowFunctionExpression
  - astDashTypesLib.genNodesMod.YieldExpression
  - astDashTypesLib.genNodesMod.GeneratorExpression
  - astDashTypesLib.genNodesMod.ComprehensionExpression
  - astDashTypesLib.genNodesMod.PropertyPattern
  - astDashTypesLib.genNodesMod.ObjectPattern
  - astDashTypesLib.genNodesMod.ArrayPattern
  - astDashTypesLib.genNodesMod.AssignmentPattern
  - astDashTypesLib.genNodesMod.ClassExpression
  - astDashTypesLib.genNodesMod.TaggedTemplateExpression
  - astDashTypesLib.genNodesMod.TemplateLiteral
  - astDashTypesLib.genNodesMod.SpreadPropertyPattern
  - astDashTypesLib.genNodesMod.AwaitExpression
  - astDashTypesLib.genNodesMod.JSXIdentifier
  - astDashTypesLib.genNodesMod.JSXExpressionContainer
  - astDashTypesLib.genNodesMod.JSXMemberExpression
  - astDashTypesLib.genNodesMod.JSXElement
  - astDashTypesLib.genNodesMod.JSXFragment
  - astDashTypesLib.genNodesMod.JSXText
  - astDashTypesLib.genNodesMod.JSXEmptyExpression
  - astDashTypesLib.genNodesMod.JSXSpreadChild
  - astDashTypesLib.genNodesMod.TypeCastExpression
  - astDashTypesLib.genNodesMod.DoExpression
  - astDashTypesLib.genNodesMod.Super
  - astDashTypesLib.genNodesMod.BindExpression
  - astDashTypesLib.genNodesMod.MetaProperty
  - astDashTypesLib.genNodesMod.ParenthesizedExpression
  - astDashTypesLib.genNodesMod.DirectiveLiteral
  - astDashTypesLib.genNodesMod.StringLiteral
  - astDashTypesLib.genNodesMod.NumericLiteral
  - astDashTypesLib.genNodesMod.BigIntLiteral
  - astDashTypesLib.genNodesMod.NullLiteral
  - astDashTypesLib.genNodesMod.BooleanLiteral
  - astDashTypesLib.genNodesMod.RegExpLiteral
  - astDashTypesLib.genNodesMod.PrivateName
  - astDashTypesLib.genNodesMod.Import
  - astDashTypesLib.genNodesMod.TSAsExpression
  - astDashTypesLib.genNodesMod.TSNonNullExpression
  - astDashTypesLib.genNodesMod.TSTypeParameter
  - astDashTypesLib.genNodesMod.TSTypeAssertion
  - astDashTypesLib.genNodesMod.TSParameterProperty
  - astDashTypesLib.genNodesMod.OptionalMemberExpression
  - astDashTypesLib.genNodesMod.OptionalCallExpression
*/
trait PatternKind extends js.Object

