package typings.typescriptNn5FuAjk

import typings.std.HTMLElementEventMap
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

trait HTMLBodyElementEventMap
  extends StObject
     with HTMLElementEventMap
     with WindowEventHandlersEventMap {
  
  var orientationchange: Event
}
object HTMLBodyElementEventMap {
  
  inline def apply(
    abort: typings.std.UIEvent,
    afterprint: Event,
    animationcancel: typings.std.AnimationEvent,
    animationend: typings.std.AnimationEvent,
    animationiteration: typings.std.AnimationEvent,
    animationstart: typings.std.AnimationEvent,
    auxclick: typings.std.MouseEvent,
    beforeinput: typings.std.InputEvent,
    beforeprint: Event,
    beforeunload: BeforeUnloadEvent,
    blur: typings.std.FocusEvent,
    canplay: typings.std.Event,
    canplaythrough: typings.std.Event,
    change: typings.std.Event,
    click: typings.std.MouseEvent,
    close: typings.std.Event,
    compositionend: typings.std.CompositionEvent,
    compositionstart: typings.std.CompositionEvent,
    compositionupdate: typings.std.CompositionEvent,
    contextmenu: typings.std.MouseEvent,
    copy: typings.std.ClipboardEvent,
    cuechange: typings.std.Event,
    cut: typings.std.ClipboardEvent,
    dblclick: typings.std.MouseEvent,
    drag: typings.std.DragEvent,
    dragend: typings.std.DragEvent,
    dragenter: typings.std.DragEvent,
    dragleave: typings.std.DragEvent,
    dragover: typings.std.DragEvent,
    dragstart: typings.std.DragEvent,
    drop: typings.std.DragEvent,
    durationchange: typings.std.Event,
    emptied: typings.std.Event,
    ended: typings.std.Event,
    error: typings.std.ErrorEvent,
    focus: typings.std.FocusEvent,
    focusin: typings.std.FocusEvent,
    focusout: typings.std.FocusEvent,
    formdata: typings.std.FormDataEvent,
    fullscreenchange: typings.std.Event,
    fullscreenerror: typings.std.Event,
    gamepadconnected: GamepadEvent,
    gamepaddisconnected: GamepadEvent,
    gotpointercapture: typings.std.PointerEvent,
    hashchange: HashChangeEvent,
    input: typings.std.Event,
    invalid: typings.std.Event,
    keydown: typings.std.KeyboardEvent,
    keypress: typings.std.KeyboardEvent,
    keyup: typings.std.KeyboardEvent,
    languagechange: Event,
    load: typings.std.Event,
    loadeddata: typings.std.Event,
    loadedmetadata: typings.std.Event,
    loadstart: typings.std.Event,
    lostpointercapture: typings.std.PointerEvent,
    message: MessageEvent[Any],
    messageerror: MessageEvent[Any],
    mousedown: typings.std.MouseEvent,
    mouseenter: typings.std.MouseEvent,
    mouseleave: typings.std.MouseEvent,
    mousemove: typings.std.MouseEvent,
    mouseout: typings.std.MouseEvent,
    mouseover: typings.std.MouseEvent,
    mouseup: typings.std.MouseEvent,
    offline: Event,
    online: Event,
    orientationchange: Event,
    pagehide: PageTransitionEvent,
    pageshow: PageTransitionEvent,
    paste: typings.std.ClipboardEvent,
    pause: typings.std.Event,
    play: typings.std.Event,
    playing: typings.std.Event,
    pointercancel: typings.std.PointerEvent,
    pointerdown: typings.std.PointerEvent,
    pointerenter: typings.std.PointerEvent,
    pointerleave: typings.std.PointerEvent,
    pointermove: typings.std.PointerEvent,
    pointerout: typings.std.PointerEvent,
    pointerover: typings.std.PointerEvent,
    pointerup: typings.std.PointerEvent,
    popstate: PopStateEvent,
    progress: typings.std.ProgressEvent[typings.std.EventTarget],
    ratechange: typings.std.Event,
    rejectionhandled: PromiseRejectionEvent,
    reset: typings.std.Event,
    resize: typings.std.UIEvent,
    scroll: typings.std.Event,
    securitypolicyviolation: typings.std.SecurityPolicyViolationEvent,
    seeked: typings.std.Event,
    seeking: typings.std.Event,
    select: typings.std.Event,
    selectionchange: typings.std.Event,
    selectstart: typings.std.Event,
    slotchange: typings.std.Event,
    stalled: typings.std.Event,
    storage: StorageEvent,
    submit: typings.std.SubmitEvent,
    suspend: typings.std.Event,
    timeupdate: typings.std.Event,
    toggle: typings.std.Event,
    touchcancel: typings.std.TouchEvent,
    touchend: typings.std.TouchEvent,
    touchmove: typings.std.TouchEvent,
    touchstart: typings.std.TouchEvent,
    transitioncancel: typings.std.TransitionEvent,
    transitionend: typings.std.TransitionEvent,
    transitionrun: typings.std.TransitionEvent,
    transitionstart: typings.std.TransitionEvent,
    unhandledrejection: PromiseRejectionEvent,
    unload: Event,
    volumechange: typings.std.Event,
    waiting: typings.std.Event,
    webkitanimationend: typings.std.Event,
    webkitanimationiteration: typings.std.Event,
    webkitanimationstart: typings.std.Event,
    webkittransitionend: typings.std.Event,
    wheel: typings.std.WheelEvent
  ): HTMLBodyElementEventMap = {
    val __obj = js.Dynamic.literal(abort = abort.asInstanceOf[js.Any], afterprint = afterprint.asInstanceOf[js.Any], animationcancel = animationcancel.asInstanceOf[js.Any], animationend = animationend.asInstanceOf[js.Any], animationiteration = animationiteration.asInstanceOf[js.Any], animationstart = animationstart.asInstanceOf[js.Any], auxclick = auxclick.asInstanceOf[js.Any], beforeinput = beforeinput.asInstanceOf[js.Any], beforeprint = beforeprint.asInstanceOf[js.Any], beforeunload = beforeunload.asInstanceOf[js.Any], blur = blur.asInstanceOf[js.Any], canplay = canplay.asInstanceOf[js.Any], canplaythrough = canplaythrough.asInstanceOf[js.Any], change = change.asInstanceOf[js.Any], click = click.asInstanceOf[js.Any], close = close.asInstanceOf[js.Any], compositionend = compositionend.asInstanceOf[js.Any], compositionstart = compositionstart.asInstanceOf[js.Any], compositionupdate = compositionupdate.asInstanceOf[js.Any], contextmenu = contextmenu.asInstanceOf[js.Any], copy = copy.asInstanceOf[js.Any], cuechange = cuechange.asInstanceOf[js.Any], cut = cut.asInstanceOf[js.Any], dblclick = dblclick.asInstanceOf[js.Any], drag = drag.asInstanceOf[js.Any], dragend = dragend.asInstanceOf[js.Any], dragenter = dragenter.asInstanceOf[js.Any], dragleave = dragleave.asInstanceOf[js.Any], dragover = dragover.asInstanceOf[js.Any], dragstart = dragstart.asInstanceOf[js.Any], drop = drop.asInstanceOf[js.Any], durationchange = durationchange.asInstanceOf[js.Any], emptied = emptied.asInstanceOf[js.Any], ended = ended.asInstanceOf[js.Any], error = error.asInstanceOf[js.Any], focus = focus.asInstanceOf[js.Any], focusin = focusin.asInstanceOf[js.Any], focusout = focusout.asInstanceOf[js.Any], formdata = formdata.asInstanceOf[js.Any], fullscreenchange = fullscreenchange.asInstanceOf[js.Any], fullscreenerror = fullscreenerror.asInstanceOf[js.Any], gamepadconnected = gamepadconnected.asInstanceOf[js.Any], gamepaddisconnected = gamepaddisconnected.asInstanceOf[js.Any], gotpointercapture = gotpointercapture.asInstanceOf[js.Any], hashchange = hashchange.asInstanceOf[js.Any], input = input.asInstanceOf[js.Any], invalid = invalid.asInstanceOf[js.Any], keydown = keydown.asInstanceOf[js.Any], keypress = keypress.asInstanceOf[js.Any], keyup = keyup.asInstanceOf[js.Any], languagechange = languagechange.asInstanceOf[js.Any], load = load.asInstanceOf[js.Any], loadeddata = loadeddata.asInstanceOf[js.Any], loadedmetadata = loadedmetadata.asInstanceOf[js.Any], loadstart = loadstart.asInstanceOf[js.Any], lostpointercapture = lostpointercapture.asInstanceOf[js.Any], message = message.asInstanceOf[js.Any], messageerror = messageerror.asInstanceOf[js.Any], mousedown = mousedown.asInstanceOf[js.Any], mouseenter = mouseenter.asInstanceOf[js.Any], mouseleave = mouseleave.asInstanceOf[js.Any], mousemove = mousemove.asInstanceOf[js.Any], mouseout = mouseout.asInstanceOf[js.Any], mouseover = mouseover.asInstanceOf[js.Any], mouseup = mouseup.asInstanceOf[js.Any], offline = offline.asInstanceOf[js.Any], online = online.asInstanceOf[js.Any], orientationchange = orientationchange.asInstanceOf[js.Any], pagehide = pagehide.asInstanceOf[js.Any], pageshow = pageshow.asInstanceOf[js.Any], paste = paste.asInstanceOf[js.Any], pause = pause.asInstanceOf[js.Any], play = play.asInstanceOf[js.Any], playing = playing.asInstanceOf[js.Any], pointercancel = pointercancel.asInstanceOf[js.Any], pointerdown = pointerdown.asInstanceOf[js.Any], pointerenter = pointerenter.asInstanceOf[js.Any], pointerleave = pointerleave.asInstanceOf[js.Any], pointermove = pointermove.asInstanceOf[js.Any], pointerout = pointerout.asInstanceOf[js.Any], pointerover = pointerover.asInstanceOf[js.Any], pointerup = pointerup.asInstanceOf[js.Any], popstate = popstate.asInstanceOf[js.Any], progress = progress.asInstanceOf[js.Any], ratechange = ratechange.asInstanceOf[js.Any], rejectionhandled = rejectionhandled.asInstanceOf[js.Any], reset = reset.asInstanceOf[js.Any], resize = resize.asInstanceOf[js.Any], scroll = scroll.asInstanceOf[js.Any], securitypolicyviolation = securitypolicyviolation.asInstanceOf[js.Any], seeked = seeked.asInstanceOf[js.Any], seeking = seeking.asInstanceOf[js.Any], select = select.asInstanceOf[js.Any], selectionchange = selectionchange.asInstanceOf[js.Any], selectstart = selectstart.asInstanceOf[js.Any], slotchange = slotchange.asInstanceOf[js.Any], stalled = stalled.asInstanceOf[js.Any], storage = storage.asInstanceOf[js.Any], submit = submit.asInstanceOf[js.Any], suspend = suspend.asInstanceOf[js.Any], timeupdate = timeupdate.asInstanceOf[js.Any], toggle = toggle.asInstanceOf[js.Any], touchcancel = touchcancel.asInstanceOf[js.Any], touchend = touchend.asInstanceOf[js.Any], touchmove = touchmove.asInstanceOf[js.Any], touchstart = touchstart.asInstanceOf[js.Any], transitioncancel = transitioncancel.asInstanceOf[js.Any], transitionend = transitionend.asInstanceOf[js.Any], transitionrun = transitionrun.asInstanceOf[js.Any], transitionstart = transitionstart.asInstanceOf[js.Any], unhandledrejection = unhandledrejection.asInstanceOf[js.Any], unload = unload.asInstanceOf[js.Any], volumechange = volumechange.asInstanceOf[js.Any], waiting = waiting.asInstanceOf[js.Any], webkitanimationend = webkitanimationend.asInstanceOf[js.Any], webkitanimationiteration = webkitanimationiteration.asInstanceOf[js.Any], webkitanimationstart = webkitanimationstart.asInstanceOf[js.Any], webkittransitionend = webkittransitionend.asInstanceOf[js.Any], wheel = wheel.asInstanceOf[js.Any])
    __obj.asInstanceOf[HTMLBodyElementEventMap]
  }
  
  extension [Self <: HTMLBodyElementEventMap](x: Self) {
    
    inline def setOrientationchange(value: Event): Self = StObject.set(x, "orientationchange", value.asInstanceOf[js.Any])
  }
}
