package typings
package reactLib.reactMod.ReactNs

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

// this list is "complete" in that it contains every SVG attribute
// that React supports, but the types can be improved.
// Full list here: https://facebook.github.io/react/docs/dom-elements.html
//
// The three broad type categories are (in order of restrictiveness):
//   - "number | string"
//   - "string"
//   - union of string literals
trait SVGAttributes[T] extends DOMAttributes[T] {
  // SVG Specific attributes
  var accentHeight: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var accumulate: js.UndefOr[reactLib.reactLibStrings.none | reactLib.reactLibStrings.sum] = js.undefined
  var additive: js.UndefOr[reactLib.reactLibStrings.replace | reactLib.reactLibStrings.sum] = js.undefined
  var alignmentBaseline: js.UndefOr[
    reactLib.reactLibStrings.auto | reactLib.reactLibStrings.baseline | reactLib.reactLibStrings.`before-edge` | reactLib.reactLibStrings.`text-before-edge` | reactLib.reactLibStrings.middle | reactLib.reactLibStrings.central | reactLib.reactLibStrings.`after-edge` | reactLib.reactLibStrings.`text-after-edge` | reactLib.reactLibStrings.ideographic | reactLib.reactLibStrings.alphabetic | reactLib.reactLibStrings.hanging | reactLib.reactLibStrings.mathematical | reactLib.reactLibStrings.inherit
  ] = js.undefined
  var allowReorder: js.UndefOr[reactLib.reactLibStrings.no | reactLib.reactLibStrings.yes] = js.undefined
  var alphabetic: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var amplitude: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var arabicForm: js.UndefOr[
    reactLib.reactLibStrings.initial | reactLib.reactLibStrings.medial | reactLib.reactLibStrings.terminal | reactLib.reactLibStrings.isolated
  ] = js.undefined
  var ascent: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var attributeName: js.UndefOr[java.lang.String] = js.undefined
  var attributeType: js.UndefOr[java.lang.String] = js.undefined
  var autoReverse: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var azimuth: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var baseFrequency: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var baseProfile: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var baselineShift: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var bbox: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var begin: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var bias: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var by: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var calcMode: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var capHeight: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  // Attributes which also defined in HTMLAttributes
  // See comment in SVGDOMPropertyConfig.js
  var className: js.UndefOr[java.lang.String] = js.undefined
  var clip: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var clipPath: js.UndefOr[java.lang.String] = js.undefined
  var clipPathUnits: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var clipRule: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var color: js.UndefOr[java.lang.String] = js.undefined
  var colorInterpolation: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var colorInterpolationFilters: js.UndefOr[
    reactLib.reactLibStrings.auto | reactLib.reactLibStrings.sRGB | reactLib.reactLibStrings.linearRGB | reactLib.reactLibStrings.inherit
  ] = js.undefined
  var colorProfile: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var colorRendering: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var contentScriptType: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var contentStyleType: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var cursor: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var cx: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var cy: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var d: js.UndefOr[java.lang.String] = js.undefined
  var decelerate: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var descent: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var diffuseConstant: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var direction: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var display: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var divisor: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var dominantBaseline: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var dur: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var dx: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var dy: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var edgeMode: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var elevation: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var enableBackground: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var end: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var exponent: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var externalResourcesRequired: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fill: js.UndefOr[java.lang.String] = js.undefined
  var fillOpacity: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fillRule: js.UndefOr[
    reactLib.reactLibStrings.nonzero | reactLib.reactLibStrings.evenodd | reactLib.reactLibStrings.inherit
  ] = js.undefined
  var filter: js.UndefOr[java.lang.String] = js.undefined
  var filterRes: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var filterUnits: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var floodColor: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var floodOpacity: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var focusable: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fontFamily: js.UndefOr[java.lang.String] = js.undefined
  var fontSize: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fontSizeAdjust: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fontStretch: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fontStyle: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fontVariant: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fontWeight: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var format: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var from: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fx: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var fy: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var g1: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var g2: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var glyphName: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var glyphOrientationHorizontal: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var glyphOrientationVertical: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var glyphRef: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var gradientTransform: js.UndefOr[java.lang.String] = js.undefined
  var gradientUnits: js.UndefOr[java.lang.String] = js.undefined
  var hanging: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var height: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var horizAdvX: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var horizOriginX: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var href: js.UndefOr[java.lang.String] = js.undefined
  var id: js.UndefOr[java.lang.String] = js.undefined
  var ideographic: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var imageRendering: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var in: js.UndefOr[java.lang.String] = js.undefined
  var in2: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var intercept: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var k: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var k1: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var k2: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var k3: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var k4: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var kernelMatrix: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var kernelUnitLength: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var kerning: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var keyPoints: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var keySplines: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var keyTimes: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var lang: js.UndefOr[java.lang.String] = js.undefined
  var lengthAdjust: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var letterSpacing: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var lightingColor: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var limitingConeAngle: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var local: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var markerEnd: js.UndefOr[java.lang.String] = js.undefined
  var markerHeight: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var markerMid: js.UndefOr[java.lang.String] = js.undefined
  var markerStart: js.UndefOr[java.lang.String] = js.undefined
  var markerUnits: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var markerWidth: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var mask: js.UndefOr[java.lang.String] = js.undefined
  var maskContentUnits: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var maskUnits: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var mathematical: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var max: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var media: js.UndefOr[java.lang.String] = js.undefined
  var method: js.UndefOr[java.lang.String] = js.undefined
  var min: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var mode: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var name: js.UndefOr[java.lang.String] = js.undefined
  var numOctaves: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var offset: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var opacity: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var operator: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var order: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var orient: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var orientation: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var origin: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var overflow: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var overlinePosition: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var overlineThickness: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var paintOrder: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var panose1: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var pathLength: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var patternContentUnits: js.UndefOr[java.lang.String] = js.undefined
  var patternTransform: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var patternUnits: js.UndefOr[java.lang.String] = js.undefined
  var pointerEvents: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var points: js.UndefOr[java.lang.String] = js.undefined
  var pointsAtX: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var pointsAtY: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var pointsAtZ: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var preserveAlpha: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var preserveAspectRatio: js.UndefOr[java.lang.String] = js.undefined
  var primitiveUnits: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var r: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var radius: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var refX: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var refY: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var renderingIntent: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var repeatCount: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var repeatDur: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var requiredExtensions: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var requiredFeatures: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var restart: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var result: js.UndefOr[java.lang.String] = js.undefined
  // Other HTML properties supported by SVG elements in browsers
  var role: js.UndefOr[java.lang.String] = js.undefined
  var rotate: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var rx: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var ry: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var scale: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var seed: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var shapeRendering: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var slope: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var spacing: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var specularConstant: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var specularExponent: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var speed: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var spreadMethod: js.UndefOr[java.lang.String] = js.undefined
  var startOffset: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var stdDeviation: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var stemh: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var stemv: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var stitchTiles: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var stopColor: js.UndefOr[java.lang.String] = js.undefined
  var stopOpacity: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var strikethroughPosition: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var strikethroughThickness: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var string: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var stroke: js.UndefOr[java.lang.String] = js.undefined
  var strokeDasharray: js.UndefOr[java.lang.String | scala.Double] = js.undefined
  var strokeDashoffset: js.UndefOr[java.lang.String | scala.Double] = js.undefined
  var strokeLinecap: js.UndefOr[
    reactLib.reactLibStrings.butt | reactLib.reactLibStrings.round | reactLib.reactLibStrings.square | reactLib.reactLibStrings.inherit
  ] = js.undefined
  var strokeLinejoin: js.UndefOr[
    reactLib.reactLibStrings.miter | reactLib.reactLibStrings.round | reactLib.reactLibStrings.bevel | reactLib.reactLibStrings.inherit
  ] = js.undefined
  var strokeMiterlimit: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var strokeOpacity: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var strokeWidth: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var style: js.UndefOr[CSSProperties] = js.undefined
  var surfaceScale: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var systemLanguage: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var tabIndex: js.UndefOr[scala.Double] = js.undefined
  var tableValues: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var target: js.UndefOr[java.lang.String] = js.undefined
  var targetX: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var targetY: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var textAnchor: js.UndefOr[java.lang.String] = js.undefined
  var textDecoration: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var textLength: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var textRendering: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var to: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var transform: js.UndefOr[java.lang.String] = js.undefined
  var `type`: js.UndefOr[java.lang.String] = js.undefined
  var u1: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var u2: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var underlinePosition: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var underlineThickness: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var unicode: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var unicodeBidi: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var unicodeRange: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var unitsPerEm: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var vAlphabetic: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var vHanging: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var vIdeographic: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var vMathematical: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var values: js.UndefOr[java.lang.String] = js.undefined
  var vectorEffect: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var version: js.UndefOr[java.lang.String] = js.undefined
  var vertAdvY: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var vertOriginX: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var vertOriginY: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var viewBox: js.UndefOr[java.lang.String] = js.undefined
  var viewTarget: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var visibility: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var width: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var widths: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var wordSpacing: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var writingMode: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var x: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var x1: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var x2: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var xChannelSelector: js.UndefOr[java.lang.String] = js.undefined
  var xHeight: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var xlinkActuate: js.UndefOr[java.lang.String] = js.undefined
  var xlinkArcrole: js.UndefOr[java.lang.String] = js.undefined
  var xlinkHref: js.UndefOr[java.lang.String] = js.undefined
  var xlinkRole: js.UndefOr[java.lang.String] = js.undefined
  var xlinkShow: js.UndefOr[java.lang.String] = js.undefined
  var xlinkTitle: js.UndefOr[java.lang.String] = js.undefined
  var xlinkType: js.UndefOr[java.lang.String] = js.undefined
  var xmlBase: js.UndefOr[java.lang.String] = js.undefined
  var xmlLang: js.UndefOr[java.lang.String] = js.undefined
  var xmlSpace: js.UndefOr[java.lang.String] = js.undefined
  var xmlns: js.UndefOr[java.lang.String] = js.undefined
  var xmlnsXlink: js.UndefOr[java.lang.String] = js.undefined
  var y: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var y1: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var y2: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var yChannelSelector: js.UndefOr[java.lang.String] = js.undefined
  var z: js.UndefOr[scala.Double | java.lang.String] = js.undefined
  var zoomAndPan: js.UndefOr[java.lang.String] = js.undefined
}

object SVGAttributes {
  @scala.inline
  def apply[T](
    DOMAttributes: DOMAttributes[T] = null,
    accentHeight: scala.Double | java.lang.String = null,
    accumulate: reactLib.reactLibStrings.none | reactLib.reactLibStrings.sum = null,
    additive: reactLib.reactLibStrings.replace | reactLib.reactLibStrings.sum = null,
    alignmentBaseline: reactLib.reactLibStrings.auto | reactLib.reactLibStrings.baseline | reactLib.reactLibStrings.`before-edge` | reactLib.reactLibStrings.`text-before-edge` | reactLib.reactLibStrings.middle | reactLib.reactLibStrings.central | reactLib.reactLibStrings.`after-edge` | reactLib.reactLibStrings.`text-after-edge` | reactLib.reactLibStrings.ideographic | reactLib.reactLibStrings.alphabetic | reactLib.reactLibStrings.hanging | reactLib.reactLibStrings.mathematical | reactLib.reactLibStrings.inherit = null,
    allowReorder: reactLib.reactLibStrings.no | reactLib.reactLibStrings.yes = null,
    alphabetic: scala.Double | java.lang.String = null,
    amplitude: scala.Double | java.lang.String = null,
    arabicForm: reactLib.reactLibStrings.initial | reactLib.reactLibStrings.medial | reactLib.reactLibStrings.terminal | reactLib.reactLibStrings.isolated = null,
    ascent: scala.Double | java.lang.String = null,
    attributeName: java.lang.String = null,
    attributeType: java.lang.String = null,
    autoReverse: scala.Double | java.lang.String = null,
    azimuth: scala.Double | java.lang.String = null,
    baseFrequency: scala.Double | java.lang.String = null,
    baseProfile: scala.Double | java.lang.String = null,
    baselineShift: scala.Double | java.lang.String = null,
    bbox: scala.Double | java.lang.String = null,
    begin: scala.Double | java.lang.String = null,
    bias: scala.Double | java.lang.String = null,
    by: scala.Double | java.lang.String = null,
    calcMode: scala.Double | java.lang.String = null,
    capHeight: scala.Double | java.lang.String = null,
    className: java.lang.String = null,
    clip: scala.Double | java.lang.String = null,
    clipPath: java.lang.String = null,
    clipPathUnits: scala.Double | java.lang.String = null,
    clipRule: scala.Double | java.lang.String = null,
    color: java.lang.String = null,
    colorInterpolation: scala.Double | java.lang.String = null,
    colorInterpolationFilters: reactLib.reactLibStrings.auto | reactLib.reactLibStrings.sRGB | reactLib.reactLibStrings.linearRGB | reactLib.reactLibStrings.inherit = null,
    colorProfile: scala.Double | java.lang.String = null,
    colorRendering: scala.Double | java.lang.String = null,
    contentScriptType: scala.Double | java.lang.String = null,
    contentStyleType: scala.Double | java.lang.String = null,
    cursor: scala.Double | java.lang.String = null,
    cx: scala.Double | java.lang.String = null,
    cy: scala.Double | java.lang.String = null,
    d: java.lang.String = null,
    decelerate: scala.Double | java.lang.String = null,
    descent: scala.Double | java.lang.String = null,
    diffuseConstant: scala.Double | java.lang.String = null,
    direction: scala.Double | java.lang.String = null,
    display: scala.Double | java.lang.String = null,
    divisor: scala.Double | java.lang.String = null,
    dominantBaseline: scala.Double | java.lang.String = null,
    dur: scala.Double | java.lang.String = null,
    dx: scala.Double | java.lang.String = null,
    dy: scala.Double | java.lang.String = null,
    edgeMode: scala.Double | java.lang.String = null,
    elevation: scala.Double | java.lang.String = null,
    enableBackground: scala.Double | java.lang.String = null,
    end: scala.Double | java.lang.String = null,
    exponent: scala.Double | java.lang.String = null,
    externalResourcesRequired: scala.Double | java.lang.String = null,
    fill: java.lang.String = null,
    fillOpacity: scala.Double | java.lang.String = null,
    fillRule: reactLib.reactLibStrings.nonzero | reactLib.reactLibStrings.evenodd | reactLib.reactLibStrings.inherit = null,
    filter: java.lang.String = null,
    filterRes: scala.Double | java.lang.String = null,
    filterUnits: scala.Double | java.lang.String = null,
    floodColor: scala.Double | java.lang.String = null,
    floodOpacity: scala.Double | java.lang.String = null,
    focusable: scala.Double | java.lang.String = null,
    fontFamily: java.lang.String = null,
    fontSize: scala.Double | java.lang.String = null,
    fontSizeAdjust: scala.Double | java.lang.String = null,
    fontStretch: scala.Double | java.lang.String = null,
    fontStyle: scala.Double | java.lang.String = null,
    fontVariant: scala.Double | java.lang.String = null,
    fontWeight: scala.Double | java.lang.String = null,
    format: scala.Double | java.lang.String = null,
    from: scala.Double | java.lang.String = null,
    fx: scala.Double | java.lang.String = null,
    fy: scala.Double | java.lang.String = null,
    g1: scala.Double | java.lang.String = null,
    g2: scala.Double | java.lang.String = null,
    glyphName: scala.Double | java.lang.String = null,
    glyphOrientationHorizontal: scala.Double | java.lang.String = null,
    glyphOrientationVertical: scala.Double | java.lang.String = null,
    glyphRef: scala.Double | java.lang.String = null,
    gradientTransform: java.lang.String = null,
    gradientUnits: java.lang.String = null,
    hanging: scala.Double | java.lang.String = null,
    height: scala.Double | java.lang.String = null,
    horizAdvX: scala.Double | java.lang.String = null,
    horizOriginX: scala.Double | java.lang.String = null,
    href: java.lang.String = null,
    id: java.lang.String = null,
    ideographic: scala.Double | java.lang.String = null,
    imageRendering: scala.Double | java.lang.String = null,
    in: java.lang.String = null,
    in2: scala.Double | java.lang.String = null,
    intercept: scala.Double | java.lang.String = null,
    k: scala.Double | java.lang.String = null,
    k1: scala.Double | java.lang.String = null,
    k2: scala.Double | java.lang.String = null,
    k3: scala.Double | java.lang.String = null,
    k4: scala.Double | java.lang.String = null,
    kernelMatrix: scala.Double | java.lang.String = null,
    kernelUnitLength: scala.Double | java.lang.String = null,
    kerning: scala.Double | java.lang.String = null,
    keyPoints: scala.Double | java.lang.String = null,
    keySplines: scala.Double | java.lang.String = null,
    keyTimes: scala.Double | java.lang.String = null,
    lang: java.lang.String = null,
    lengthAdjust: scala.Double | java.lang.String = null,
    letterSpacing: scala.Double | java.lang.String = null,
    lightingColor: scala.Double | java.lang.String = null,
    limitingConeAngle: scala.Double | java.lang.String = null,
    local: scala.Double | java.lang.String = null,
    markerEnd: java.lang.String = null,
    markerHeight: scala.Double | java.lang.String = null,
    markerMid: java.lang.String = null,
    markerStart: java.lang.String = null,
    markerUnits: scala.Double | java.lang.String = null,
    markerWidth: scala.Double | java.lang.String = null,
    mask: java.lang.String = null,
    maskContentUnits: scala.Double | java.lang.String = null,
    maskUnits: scala.Double | java.lang.String = null,
    mathematical: scala.Double | java.lang.String = null,
    max: scala.Double | java.lang.String = null,
    media: java.lang.String = null,
    method: java.lang.String = null,
    min: scala.Double | java.lang.String = null,
    mode: scala.Double | java.lang.String = null,
    name: java.lang.String = null,
    numOctaves: scala.Double | java.lang.String = null,
    offset: scala.Double | java.lang.String = null,
    opacity: scala.Double | java.lang.String = null,
    operator: scala.Double | java.lang.String = null,
    order: scala.Double | java.lang.String = null,
    orient: scala.Double | java.lang.String = null,
    orientation: scala.Double | java.lang.String = null,
    origin: scala.Double | java.lang.String = null,
    overflow: scala.Double | java.lang.String = null,
    overlinePosition: scala.Double | java.lang.String = null,
    overlineThickness: scala.Double | java.lang.String = null,
    paintOrder: scala.Double | java.lang.String = null,
    panose1: scala.Double | java.lang.String = null,
    pathLength: scala.Double | java.lang.String = null,
    patternContentUnits: java.lang.String = null,
    patternTransform: scala.Double | java.lang.String = null,
    patternUnits: java.lang.String = null,
    pointerEvents: scala.Double | java.lang.String = null,
    points: java.lang.String = null,
    pointsAtX: scala.Double | java.lang.String = null,
    pointsAtY: scala.Double | java.lang.String = null,
    pointsAtZ: scala.Double | java.lang.String = null,
    preserveAlpha: scala.Double | java.lang.String = null
  ): SVGAttributes[T] = {
    val __obj = js.Dynamic.literal()
    js.Dynamic.global.Object.assign(__obj, DOMAttributes)
    if (accentHeight != null) __obj.updateDynamic("accentHeight")(accentHeight.asInstanceOf[js.Any])
    if (accumulate != null) __obj.updateDynamic("accumulate")(accumulate.asInstanceOf[js.Any])
    if (additive != null) __obj.updateDynamic("additive")(additive.asInstanceOf[js.Any])
    if (alignmentBaseline != null) __obj.updateDynamic("alignmentBaseline")(alignmentBaseline.asInstanceOf[js.Any])
    if (allowReorder != null) __obj.updateDynamic("allowReorder")(allowReorder.asInstanceOf[js.Any])
    if (alphabetic != null) __obj.updateDynamic("alphabetic")(alphabetic.asInstanceOf[js.Any])
    if (amplitude != null) __obj.updateDynamic("amplitude")(amplitude.asInstanceOf[js.Any])
    if (arabicForm != null) __obj.updateDynamic("arabicForm")(arabicForm.asInstanceOf[js.Any])
    if (ascent != null) __obj.updateDynamic("ascent")(ascent.asInstanceOf[js.Any])
    if (attributeName != null) __obj.updateDynamic("attributeName")(attributeName)
    if (attributeType != null) __obj.updateDynamic("attributeType")(attributeType)
    if (autoReverse != null) __obj.updateDynamic("autoReverse")(autoReverse.asInstanceOf[js.Any])
    if (azimuth != null) __obj.updateDynamic("azimuth")(azimuth.asInstanceOf[js.Any])
    if (baseFrequency != null) __obj.updateDynamic("baseFrequency")(baseFrequency.asInstanceOf[js.Any])
    if (baseProfile != null) __obj.updateDynamic("baseProfile")(baseProfile.asInstanceOf[js.Any])
    if (baselineShift != null) __obj.updateDynamic("baselineShift")(baselineShift.asInstanceOf[js.Any])
    if (bbox != null) __obj.updateDynamic("bbox")(bbox.asInstanceOf[js.Any])
    if (begin != null) __obj.updateDynamic("begin")(begin.asInstanceOf[js.Any])
    if (bias != null) __obj.updateDynamic("bias")(bias.asInstanceOf[js.Any])
    if (by != null) __obj.updateDynamic("by")(by.asInstanceOf[js.Any])
    if (calcMode != null) __obj.updateDynamic("calcMode")(calcMode.asInstanceOf[js.Any])
    if (capHeight != null) __obj.updateDynamic("capHeight")(capHeight.asInstanceOf[js.Any])
    if (className != null) __obj.updateDynamic("className")(className)
    if (clip != null) __obj.updateDynamic("clip")(clip.asInstanceOf[js.Any])
    if (clipPath != null) __obj.updateDynamic("clipPath")(clipPath)
    if (clipPathUnits != null) __obj.updateDynamic("clipPathUnits")(clipPathUnits.asInstanceOf[js.Any])
    if (clipRule != null) __obj.updateDynamic("clipRule")(clipRule.asInstanceOf[js.Any])
    if (color != null) __obj.updateDynamic("color")(color)
    if (colorInterpolation != null) __obj.updateDynamic("colorInterpolation")(colorInterpolation.asInstanceOf[js.Any])
    if (colorInterpolationFilters != null) __obj.updateDynamic("colorInterpolationFilters")(colorInterpolationFilters.asInstanceOf[js.Any])
    if (colorProfile != null) __obj.updateDynamic("colorProfile")(colorProfile.asInstanceOf[js.Any])
    if (colorRendering != null) __obj.updateDynamic("colorRendering")(colorRendering.asInstanceOf[js.Any])
    if (contentScriptType != null) __obj.updateDynamic("contentScriptType")(contentScriptType.asInstanceOf[js.Any])
    if (contentStyleType != null) __obj.updateDynamic("contentStyleType")(contentStyleType.asInstanceOf[js.Any])
    if (cursor != null) __obj.updateDynamic("cursor")(cursor.asInstanceOf[js.Any])
    if (cx != null) __obj.updateDynamic("cx")(cx.asInstanceOf[js.Any])
    if (cy != null) __obj.updateDynamic("cy")(cy.asInstanceOf[js.Any])
    if (d != null) __obj.updateDynamic("d")(d)
    if (decelerate != null) __obj.updateDynamic("decelerate")(decelerate.asInstanceOf[js.Any])
    if (descent != null) __obj.updateDynamic("descent")(descent.asInstanceOf[js.Any])
    if (diffuseConstant != null) __obj.updateDynamic("diffuseConstant")(diffuseConstant.asInstanceOf[js.Any])
    if (direction != null) __obj.updateDynamic("direction")(direction.asInstanceOf[js.Any])
    if (display != null) __obj.updateDynamic("display")(display.asInstanceOf[js.Any])
    if (divisor != null) __obj.updateDynamic("divisor")(divisor.asInstanceOf[js.Any])
    if (dominantBaseline != null) __obj.updateDynamic("dominantBaseline")(dominantBaseline.asInstanceOf[js.Any])
    if (dur != null) __obj.updateDynamic("dur")(dur.asInstanceOf[js.Any])
    if (dx != null) __obj.updateDynamic("dx")(dx.asInstanceOf[js.Any])
    if (dy != null) __obj.updateDynamic("dy")(dy.asInstanceOf[js.Any])
    if (edgeMode != null) __obj.updateDynamic("edgeMode")(edgeMode.asInstanceOf[js.Any])
    if (elevation != null) __obj.updateDynamic("elevation")(elevation.asInstanceOf[js.Any])
    if (enableBackground != null) __obj.updateDynamic("enableBackground")(enableBackground.asInstanceOf[js.Any])
    if (end != null) __obj.updateDynamic("end")(end.asInstanceOf[js.Any])
    if (exponent != null) __obj.updateDynamic("exponent")(exponent.asInstanceOf[js.Any])
    if (externalResourcesRequired != null) __obj.updateDynamic("externalResourcesRequired")(externalResourcesRequired.asInstanceOf[js.Any])
    if (fill != null) __obj.updateDynamic("fill")(fill)
    if (fillOpacity != null) __obj.updateDynamic("fillOpacity")(fillOpacity.asInstanceOf[js.Any])
    if (fillRule != null) __obj.updateDynamic("fillRule")(fillRule.asInstanceOf[js.Any])
    if (filter != null) __obj.updateDynamic("filter")(filter)
    if (filterRes != null) __obj.updateDynamic("filterRes")(filterRes.asInstanceOf[js.Any])
    if (filterUnits != null) __obj.updateDynamic("filterUnits")(filterUnits.asInstanceOf[js.Any])
    if (floodColor != null) __obj.updateDynamic("floodColor")(floodColor.asInstanceOf[js.Any])
    if (floodOpacity != null) __obj.updateDynamic("floodOpacity")(floodOpacity.asInstanceOf[js.Any])
    if (focusable != null) __obj.updateDynamic("focusable")(focusable.asInstanceOf[js.Any])
    if (fontFamily != null) __obj.updateDynamic("fontFamily")(fontFamily)
    if (fontSize != null) __obj.updateDynamic("fontSize")(fontSize.asInstanceOf[js.Any])
    if (fontSizeAdjust != null) __obj.updateDynamic("fontSizeAdjust")(fontSizeAdjust.asInstanceOf[js.Any])
    if (fontStretch != null) __obj.updateDynamic("fontStretch")(fontStretch.asInstanceOf[js.Any])
    if (fontStyle != null) __obj.updateDynamic("fontStyle")(fontStyle.asInstanceOf[js.Any])
    if (fontVariant != null) __obj.updateDynamic("fontVariant")(fontVariant.asInstanceOf[js.Any])
    if (fontWeight != null) __obj.updateDynamic("fontWeight")(fontWeight.asInstanceOf[js.Any])
    if (format != null) __obj.updateDynamic("format")(format.asInstanceOf[js.Any])
    if (from != null) __obj.updateDynamic("from")(from.asInstanceOf[js.Any])
    if (fx != null) __obj.updateDynamic("fx")(fx.asInstanceOf[js.Any])
    if (fy != null) __obj.updateDynamic("fy")(fy.asInstanceOf[js.Any])
    if (g1 != null) __obj.updateDynamic("g1")(g1.asInstanceOf[js.Any])
    if (g2 != null) __obj.updateDynamic("g2")(g2.asInstanceOf[js.Any])
    if (glyphName != null) __obj.updateDynamic("glyphName")(glyphName.asInstanceOf[js.Any])
    if (glyphOrientationHorizontal != null) __obj.updateDynamic("glyphOrientationHorizontal")(glyphOrientationHorizontal.asInstanceOf[js.Any])
    if (glyphOrientationVertical != null) __obj.updateDynamic("glyphOrientationVertical")(glyphOrientationVertical.asInstanceOf[js.Any])
    if (glyphRef != null) __obj.updateDynamic("glyphRef")(glyphRef.asInstanceOf[js.Any])
    if (gradientTransform != null) __obj.updateDynamic("gradientTransform")(gradientTransform)
    if (gradientUnits != null) __obj.updateDynamic("gradientUnits")(gradientUnits)
    if (hanging != null) __obj.updateDynamic("hanging")(hanging.asInstanceOf[js.Any])
    if (height != null) __obj.updateDynamic("height")(height.asInstanceOf[js.Any])
    if (horizAdvX != null) __obj.updateDynamic("horizAdvX")(horizAdvX.asInstanceOf[js.Any])
    if (horizOriginX != null) __obj.updateDynamic("horizOriginX")(horizOriginX.asInstanceOf[js.Any])
    if (href != null) __obj.updateDynamic("href")(href)
    if (id != null) __obj.updateDynamic("id")(id)
    if (ideographic != null) __obj.updateDynamic("ideographic")(ideographic.asInstanceOf[js.Any])
    if (imageRendering != null) __obj.updateDynamic("imageRendering")(imageRendering.asInstanceOf[js.Any])
    if (in != null) __obj.updateDynamic("in")(in)
    if (in2 != null) __obj.updateDynamic("in2")(in2.asInstanceOf[js.Any])
    if (intercept != null) __obj.updateDynamic("intercept")(intercept.asInstanceOf[js.Any])
    if (k != null) __obj.updateDynamic("k")(k.asInstanceOf[js.Any])
    if (k1 != null) __obj.updateDynamic("k1")(k1.asInstanceOf[js.Any])
    if (k2 != null) __obj.updateDynamic("k2")(k2.asInstanceOf[js.Any])
    if (k3 != null) __obj.updateDynamic("k3")(k3.asInstanceOf[js.Any])
    if (k4 != null) __obj.updateDynamic("k4")(k4.asInstanceOf[js.Any])
    if (kernelMatrix != null) __obj.updateDynamic("kernelMatrix")(kernelMatrix.asInstanceOf[js.Any])
    if (kernelUnitLength != null) __obj.updateDynamic("kernelUnitLength")(kernelUnitLength.asInstanceOf[js.Any])
    if (kerning != null) __obj.updateDynamic("kerning")(kerning.asInstanceOf[js.Any])
    if (keyPoints != null) __obj.updateDynamic("keyPoints")(keyPoints.asInstanceOf[js.Any])
    if (keySplines != null) __obj.updateDynamic("keySplines")(keySplines.asInstanceOf[js.Any])
    if (keyTimes != null) __obj.updateDynamic("keyTimes")(keyTimes.asInstanceOf[js.Any])
    if (lang != null) __obj.updateDynamic("lang")(lang)
    if (lengthAdjust != null) __obj.updateDynamic("lengthAdjust")(lengthAdjust.asInstanceOf[js.Any])
    if (letterSpacing != null) __obj.updateDynamic("letterSpacing")(letterSpacing.asInstanceOf[js.Any])
    if (lightingColor != null) __obj.updateDynamic("lightingColor")(lightingColor.asInstanceOf[js.Any])
    if (limitingConeAngle != null) __obj.updateDynamic("limitingConeAngle")(limitingConeAngle.asInstanceOf[js.Any])
    if (local != null) __obj.updateDynamic("local")(local.asInstanceOf[js.Any])
    if (markerEnd != null) __obj.updateDynamic("markerEnd")(markerEnd)
    if (markerHeight != null) __obj.updateDynamic("markerHeight")(markerHeight.asInstanceOf[js.Any])
    if (markerMid != null) __obj.updateDynamic("markerMid")(markerMid)
    if (markerStart != null) __obj.updateDynamic("markerStart")(markerStart)
    if (markerUnits != null) __obj.updateDynamic("markerUnits")(markerUnits.asInstanceOf[js.Any])
    if (markerWidth != null) __obj.updateDynamic("markerWidth")(markerWidth.asInstanceOf[js.Any])
    if (mask != null) __obj.updateDynamic("mask")(mask)
    if (maskContentUnits != null) __obj.updateDynamic("maskContentUnits")(maskContentUnits.asInstanceOf[js.Any])
    if (maskUnits != null) __obj.updateDynamic("maskUnits")(maskUnits.asInstanceOf[js.Any])
    if (mathematical != null) __obj.updateDynamic("mathematical")(mathematical.asInstanceOf[js.Any])
    if (max != null) __obj.updateDynamic("max")(max.asInstanceOf[js.Any])
    if (media != null) __obj.updateDynamic("media")(media)
    if (method != null) __obj.updateDynamic("method")(method)
    if (min != null) __obj.updateDynamic("min")(min.asInstanceOf[js.Any])
    if (mode != null) __obj.updateDynamic("mode")(mode.asInstanceOf[js.Any])
    if (name != null) __obj.updateDynamic("name")(name)
    if (numOctaves != null) __obj.updateDynamic("numOctaves")(numOctaves.asInstanceOf[js.Any])
    if (offset != null) __obj.updateDynamic("offset")(offset.asInstanceOf[js.Any])
    if (opacity != null) __obj.updateDynamic("opacity")(opacity.asInstanceOf[js.Any])
    if (operator != null) __obj.updateDynamic("operator")(operator.asInstanceOf[js.Any])
    if (order != null) __obj.updateDynamic("order")(order.asInstanceOf[js.Any])
    if (orient != null) __obj.updateDynamic("orient")(orient.asInstanceOf[js.Any])
    if (orientation != null) __obj.updateDynamic("orientation")(orientation.asInstanceOf[js.Any])
    if (origin != null) __obj.updateDynamic("origin")(origin.asInstanceOf[js.Any])
    if (overflow != null) __obj.updateDynamic("overflow")(overflow.asInstanceOf[js.Any])
    if (overlinePosition != null) __obj.updateDynamic("overlinePosition")(overlinePosition.asInstanceOf[js.Any])
    if (overlineThickness != null) __obj.updateDynamic("overlineThickness")(overlineThickness.asInstanceOf[js.Any])
    if (paintOrder != null) __obj.updateDynamic("paintOrder")(paintOrder.asInstanceOf[js.Any])
    if (panose1 != null) __obj.updateDynamic("panose1")(panose1.asInstanceOf[js.Any])
    if (pathLength != null) __obj.updateDynamic("pathLength")(pathLength.asInstanceOf[js.Any])
    if (patternContentUnits != null) __obj.updateDynamic("patternContentUnits")(patternContentUnits)
    if (patternTransform != null) __obj.updateDynamic("patternTransform")(patternTransform.asInstanceOf[js.Any])
    if (patternUnits != null) __obj.updateDynamic("patternUnits")(patternUnits)
    if (pointerEvents != null) __obj.updateDynamic("pointerEvents")(pointerEvents.asInstanceOf[js.Any])
    if (points != null) __obj.updateDynamic("points")(points)
    if (pointsAtX != null) __obj.updateDynamic("pointsAtX")(pointsAtX.asInstanceOf[js.Any])
    if (pointsAtY != null) __obj.updateDynamic("pointsAtY")(pointsAtY.asInstanceOf[js.Any])
    if (pointsAtZ != null) __obj.updateDynamic("pointsAtZ")(pointsAtZ.asInstanceOf[js.Any])
    if (preserveAlpha != null) __obj.updateDynamic("preserveAlpha")(preserveAlpha.asInstanceOf[js.Any])
    __obj.asInstanceOf[SVGAttributes[T]]
  }
}

