package typings.astDashTypes.genKindsMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.BlockStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.EmptyStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ExpressionStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.IfStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.LabeledStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.BreakStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ContinueStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.WithStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.SwitchStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ReturnStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ThrowStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TryStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.WhileStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.DoWhileStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ForStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.VariableDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ForInStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.DebuggerStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.FunctionDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ForOfStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.MethodDefinition
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ClassPropertyDefinition
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ClassProperty
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ClassBody
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ClassDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ImportDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TSTypeParameterDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.InterfaceDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.DeclareInterface
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TypeAlias
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.OpaqueType
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.DeclareTypeAlias
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.DeclareOpaqueType
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.DeclareVariable
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.DeclareFunction
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.DeclareClass
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.DeclareModule
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.DeclareModuleExports
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.DeclareExportDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.DeclareExportAllDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ExportDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.Noop
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ExportDefaultDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ExportNamedDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ExportAllDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ClassPrivateProperty
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ClassMethod
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ClassPrivateMethod
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.ForAwaitStatement
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TSDeclareFunction
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TSDeclareMethod
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TSIndexSignature
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TSPropertySignature
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TSMethodSignature
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TSCallSignatureDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TSConstructSignatureDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TSEnumDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TSTypeAliasDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TSModuleDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TSImportEqualsDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TSExternalModuleReference
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TSExportAssignment
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TSNamespaceExportDeclaration
  - typings.astDashTypes.genNamedTypesMod.namedTypesNs.TSInterfaceDeclaration
*/
trait StatementKind extends js.Object

