package typings.officeJs.Office

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/**
  * Provides options for configuring the binding that is created.
  */
trait AddBindingFromNamedItemOptions extends StObject {
  
  /**
    * A user-defined item of any type that is returned, unchanged, in the asyncContext property of the AsyncResult object that is passed to a callback.
    */
  var asyncContext: js.UndefOr[js.Any] = js.undefined
  
  /**
    * The unique ID of the binding. Autogenerated if not supplied.
    */
  var id: js.UndefOr[String] = js.undefined
}
object AddBindingFromNamedItemOptions {
  
  @scala.inline
  def apply(): AddBindingFromNamedItemOptions = {
    val __obj = js.Dynamic.literal()
    __obj.asInstanceOf[AddBindingFromNamedItemOptions]
  }
  
  @scala.inline
  implicit class AddBindingFromNamedItemOptionsMutableBuilder[Self <: AddBindingFromNamedItemOptions] (val x: Self) extends AnyVal {
    
    @scala.inline
    def setAsyncContext(value: js.Any): Self = StObject.set(x, "asyncContext", value.asInstanceOf[js.Any])
    
    @scala.inline
    def setAsyncContextUndefined: Self = StObject.set(x, "asyncContext", js.undefined)
    
    @scala.inline
    def setId(value: String): Self = StObject.set(x, "id", value.asInstanceOf[js.Any])
    
    @scala.inline
    def setIdUndefined: Self = StObject.set(x, "id", js.undefined)
  }
}
