package typings
package fridaDashGumLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - fridaDashGumLib.fridaDashGumLibStrings.v0
  - fridaDashGumLib.fridaDashGumLibStrings.v1
  - fridaDashGumLib.fridaDashGumLibStrings.a0
  - fridaDashGumLib.fridaDashGumLibStrings.a1
  - fridaDashGumLib.fridaDashGumLibStrings.a2
  - fridaDashGumLib.fridaDashGumLibStrings.a3
  - fridaDashGumLib.fridaDashGumLibStrings.t0
  - fridaDashGumLib.fridaDashGumLibStrings.t1
  - fridaDashGumLib.fridaDashGumLibStrings.t2
  - fridaDashGumLib.fridaDashGumLibStrings.t3
  - fridaDashGumLib.fridaDashGumLibStrings.t4
  - fridaDashGumLib.fridaDashGumLibStrings.t5
  - fridaDashGumLib.fridaDashGumLibStrings.t6
  - fridaDashGumLib.fridaDashGumLibStrings.t7
  - fridaDashGumLib.fridaDashGumLibStrings.s0
  - fridaDashGumLib.fridaDashGumLibStrings.s1
  - fridaDashGumLib.fridaDashGumLibStrings.s2
  - fridaDashGumLib.fridaDashGumLibStrings.s3
  - fridaDashGumLib.fridaDashGumLibStrings.s4
  - fridaDashGumLib.fridaDashGumLibStrings.s5
  - fridaDashGumLib.fridaDashGumLibStrings.s6
  - fridaDashGumLib.fridaDashGumLibStrings.s7
  - fridaDashGumLib.fridaDashGumLibStrings.t8
  - fridaDashGumLib.fridaDashGumLibStrings.t9
  - fridaDashGumLib.fridaDashGumLibStrings.k0
  - fridaDashGumLib.fridaDashGumLibStrings.k1
  - fridaDashGumLib.fridaDashGumLibStrings.gp
  - fridaDashGumLib.fridaDashGumLibStrings.sp
  - fridaDashGumLib.fridaDashGumLibStrings.fp
  - fridaDashGumLib.fridaDashGumLibStrings.s8
  - fridaDashGumLib.fridaDashGumLibStrings.ra
  - fridaDashGumLib.fridaDashGumLibStrings.hi
  - fridaDashGumLib.fridaDashGumLibStrings.lo
  - fridaDashGumLib.fridaDashGumLibStrings.zero
  - fridaDashGumLib.fridaDashGumLibStrings.at
  - fridaDashGumLib.fridaDashGumLibStrings.`0`
  - fridaDashGumLib.fridaDashGumLibStrings.`1`
  - fridaDashGumLib.fridaDashGumLibStrings.`2`
  - fridaDashGumLib.fridaDashGumLibStrings.`3`
  - fridaDashGumLib.fridaDashGumLibStrings.`4`
  - fridaDashGumLib.fridaDashGumLibStrings.`5`
  - fridaDashGumLib.fridaDashGumLibStrings.`6`
  - fridaDashGumLib.fridaDashGumLibStrings.`7`
  - fridaDashGumLib.fridaDashGumLibStrings.`8`
  - fridaDashGumLib.fridaDashGumLibStrings.`9`
  - fridaDashGumLib.fridaDashGumLibStrings.`10`
  - fridaDashGumLib.fridaDashGumLibStrings.`11`
  - fridaDashGumLib.fridaDashGumLibStrings.`12`
  - fridaDashGumLib.fridaDashGumLibStrings.`13`
  - fridaDashGumLib.fridaDashGumLibStrings.`14`
  - fridaDashGumLib.fridaDashGumLibStrings.`15`
  - fridaDashGumLib.fridaDashGumLibStrings.`16`
  - fridaDashGumLib.fridaDashGumLibStrings.`17`
  - fridaDashGumLib.fridaDashGumLibStrings.`18`
  - fridaDashGumLib.fridaDashGumLibStrings.`19`
  - fridaDashGumLib.fridaDashGumLibStrings.`20`
  - fridaDashGumLib.fridaDashGumLibStrings.`21`
  - fridaDashGumLib.fridaDashGumLibStrings.`22`
  - fridaDashGumLib.fridaDashGumLibStrings.`23`
  - fridaDashGumLib.fridaDashGumLibStrings.`24`
  - fridaDashGumLib.fridaDashGumLibStrings.`25`
  - fridaDashGumLib.fridaDashGumLibStrings.`26`
  - fridaDashGumLib.fridaDashGumLibStrings.`27`
  - fridaDashGumLib.fridaDashGumLibStrings.`28`
  - fridaDashGumLib.fridaDashGumLibStrings.`29`
  - fridaDashGumLib.fridaDashGumLibStrings.`30`
  - fridaDashGumLib.fridaDashGumLibStrings.`31`
*/
trait MipsRegister extends _MipsCallArgument

