package typings
package atUifabricMergeDashStylesLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object libIRawStyleBaseMod {
  type ICSSBaselinePositionRule = atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.baseline | (atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`last baseline`) | (atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`first baseline`)
  type ICSSOverflowAndSelfPositionRule = atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.center | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.start | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.end | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`self-start` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`self-end` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`flex-start` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`flex-end` | (atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`safe center`) | (atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`safe start`) | (atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`safe end`) | (atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`safe self-start`) | (atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`safe self-end`) | (atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`safe flex-start`) | (atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`safe flex-end`) | (atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`unsafe center`) | (atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`unsafe start`) | (atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`unsafe end`) | (atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`unsafe self-start`) | (atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`unsafe self-end`) | (atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`unsafe flex-start`) | (atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`unsafe flex-end`)
  type ICSSPercentageRule = java.lang.String
  type ICSSPixelUnitRule = java.lang.String | scala.Double
  type ICSSRule = atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.initial | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.inherit | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.unset
  type IFontWeight = ICSSRule | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.normal | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.bold | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.bolder | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.lighter | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`100` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibNumbers.`100` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`200` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibNumbers.`200` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`300` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibNumbers.`300` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`400` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibNumbers.`400` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`500` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibNumbers.`500` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`600` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibNumbers.`600` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`700` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibNumbers.`700` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`800` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibNumbers.`800` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`900` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibNumbers.`900`
  type IMixBlendModes = ICSSRule | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.normal | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.multiply | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.screen | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.overlay | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.darken | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.lighten | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`color-dodge` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`color-burn` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`hard-light` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.`soft-light` | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.difference | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.exclusion | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.hue | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.saturation | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.color | atUifabricMergeDashStylesLib.atUifabricMergeDashStylesLibStrings.luminosity
}
