package typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod

import org.scalablytyped.runtime.StringDictionary
import typings.firebaseFirestore.anon.Seconds
import typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.^
import typings.firebaseFirestore.firebaseFirestoreStrings.NULL_VALUE
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}


inline def CompositeFilterOpEnum: ICompositeFilterOpEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("CompositeFilterOpEnum").asInstanceOf[ICompositeFilterOpEnum]

inline def FieldFilterOpEnum: IFieldFilterOpEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("FieldFilterOpEnum").asInstanceOf[IFieldFilterOpEnum]

inline def FieldTransformSetToServerValueEnum: IFieldTransformSetToServerValueEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("FieldTransformSetToServerValueEnum").asInstanceOf[IFieldTransformSetToServerValueEnum]

inline def IndexFieldModeEnum: IIndexFieldModeEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("IndexFieldModeEnum").asInstanceOf[IIndexFieldModeEnum]

inline def IndexStateEnum: IIndexStateEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("IndexStateEnum").asInstanceOf[IIndexStateEnum]

inline def OrderDirectionEnum: IOrderDirectionEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("OrderDirectionEnum").asInstanceOf[IOrderDirectionEnum]

inline def ProjectsDatabasesDocumentsApiClientAltEnum: IProjectsDatabasesDocumentsApiClientAltEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("ProjectsDatabasesDocumentsApiClientAltEnum").asInstanceOf[IProjectsDatabasesDocumentsApiClientAltEnum]

inline def ProjectsDatabasesDocumentsApiClientXgafvEnum: IProjectsDatabasesDocumentsApiClientXgafvEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("ProjectsDatabasesDocumentsApiClient$XgafvEnum").asInstanceOf[IProjectsDatabasesDocumentsApiClientXgafvEnum]

inline def ProjectsDatabasesIndexesApiClientAltEnum: IProjectsDatabasesIndexesApiClientAltEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("ProjectsDatabasesIndexesApiClientAltEnum").asInstanceOf[IProjectsDatabasesIndexesApiClientAltEnum]

inline def ProjectsDatabasesIndexesApiClientXgafvEnum: IProjectsDatabasesIndexesApiClientXgafvEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("ProjectsDatabasesIndexesApiClient$XgafvEnum").asInstanceOf[IProjectsDatabasesIndexesApiClientXgafvEnum]

inline def TargetChangeTargetChangeTypeEnum: ITargetChangeTargetChangeTypeEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("TargetChangeTargetChangeTypeEnum").asInstanceOf[ITargetChangeTargetChangeTypeEnum]

inline def UnaryFilterOpEnum: IUnaryFilterOpEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("UnaryFilterOpEnum").asInstanceOf[IUnaryFilterOpEnum]

inline def ValueNullValueEnum: IValueNullValueEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("ValueNullValueEnum").asInstanceOf[IValueNullValueEnum]

type Aggregation = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Aggregation

type ApiClientHookFactory = Any

type ApiClientObjectMap[T] = StringDictionary[T]

type ArrayValue = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ArrayValue

type BatchGetDocumentsRequest = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.BatchGetDocumentsRequest

type BatchGetDocumentsResponse = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.BatchGetDocumentsResponse

type BeginTransactionRequest = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.BeginTransactionRequest

type BeginTransactionResponse = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.BeginTransactionResponse

type BloomFilter = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.BloomFilter

type CollectionSelector = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.CollectionSelector

type CommitRequest = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.CommitRequest

type CommitResponse = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.CommitResponse

type CompositeFilter = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.CompositeFilter

type Cursor = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Cursor

type Document = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Document

type DocumentChange = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.DocumentChange

type DocumentDelete = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.DocumentDelete

type DocumentMask = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.DocumentMask

type DocumentRemove = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.DocumentRemove

type DocumentTransform = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.DocumentTransform

type DocumentsTarget = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.DocumentsTarget

type Empty = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Empty

type ExistenceFilter = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ExistenceFilter

type FieldFilter = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.FieldFilter

type FieldReference = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.FieldReference

type FieldTransform = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.FieldTransform

type Filter = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Filter

type Index = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Index

type IndexField = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.IndexField

type LatLng = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.LatLng

type ListCollectionIdsRequest = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ListCollectionIdsRequest

type ListCollectionIdsResponse = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ListCollectionIdsResponse

type ListDocumentsResponse = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ListDocumentsResponse

type ListIndexesResponse = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ListIndexesResponse

type ListenRequest = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ListenRequest

type ListenResponse = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ListenResponse

type MapValue = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.MapValue

type Operation = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Operation

type Order = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Order

type Precondition = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Precondition

type Projection = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Projection

type PromiseRequestService = Any

type QueryTarget = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.QueryTarget

type ReadOnly = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ReadOnly

type ReadWrite = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ReadWrite

type RollbackRequest = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.RollbackRequest

type RunAggregationQueryRequest = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.RunAggregationQueryRequest

type RunAggregationQueryResponse = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.RunAggregationQueryResponse

type RunQueryRequest = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.RunQueryRequest

type RunQueryResponse = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.RunQueryResponse

type Status = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Status

type StructuredQuery = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.StructuredQuery

type Target = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Target

type TargetChange = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.TargetChange

type Timestamp = String | Seconds

type TransactionOptions = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.TransactionOptions

type UnaryFilter = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.UnaryFilter

type Value = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Value

type ValueNullValue = NULL_VALUE

type Write = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Write

type WriteRequest = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.WriteRequest

type WriteResponse = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.WriteResponse

type WriteResult = typings.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.WriteResult
