package typings
package screepsLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSGlobalScope
@js.native
object screepsLibMembers extends js.Object {
  val ATTACK: screepsLib.screepsLibStrings.attack = js.native
  val ATTACK_POWER: screepsLib.screepsLibNumbers.`30` = js.native
  val BODYPARTS_ALL: js.Array[BodyPartConstant] = js.native
  val BODYPART_COST: stdLib.Record[BodyPartConstant, scala.Double] = js.native
  val BOTTOM: screepsLib.screepsLibNumbers.`5` = js.native
  val BOTTOM_LEFT: screepsLib.screepsLibNumbers.`6` = js.native
  val BOTTOM_RIGHT: screepsLib.screepsLibNumbers.`4` = js.native
  val BUILD_POWER: screepsLib.screepsLibNumbers.`5` = js.native
  val CARRY: screepsLib.screepsLibStrings.carry = js.native
  val CARRY_CAPACITY: screepsLib.screepsLibNumbers.`50` = js.native
  val CLAIM: screepsLib.screepsLibStrings.claim = js.native
  val COLORS_ALL: js.Array[ColorConstant] = js.native
  val COLOR_BLUE: screepsLib.screepsLibNumbers.`3` = js.native
  val COLOR_BROWN: screepsLib.screepsLibNumbers.`8` = js.native
  val COLOR_CYAN: screepsLib.screepsLibNumbers.`4` = js.native
  val COLOR_GREEN: screepsLib.screepsLibNumbers.`5` = js.native
  val COLOR_GREY: screepsLib.screepsLibNumbers.`9` = js.native
  val COLOR_ORANGE: screepsLib.screepsLibNumbers.`7` = js.native
  val COLOR_PURPLE: screepsLib.screepsLibNumbers.`2` = js.native
  val COLOR_RED: screepsLib.screepsLibNumbers.`1` = js.native
  val COLOR_WHITE: screepsLib.screepsLibNumbers.`10` = js.native
  val COLOR_YELLOW: screepsLib.screepsLibNumbers.`6` = js.native
  val CONSTRUCTION_COST: stdLib.Record[BuildableStructureConstant, scala.Double] = js.native
  val CONSTRUCTION_COST_ROAD_SWAMP_RATIO: screepsLib.screepsLibNumbers.`5` = js.native
  val CONTAINER_CAPACITY: scala.Double = js.native
  val CONTAINER_DECAY: scala.Double = js.native
  val CONTAINER_DECAY_TIME: scala.Double = js.native
  val CONTAINER_DECAY_TIME_OWNED: scala.Double = js.native
  val CONTAINER_HITS: scala.Double = js.native
  val CONTROLLER_ATTACK_BLOCKED_UPGRADE: scala.Double = js.native
  val CONTROLLER_CLAIM_DOWNGRADE: scala.Double = js.native
  val CONTROLLER_DOWNGRADE_RESTORE: scala.Double = js.native
  val CONTROLLER_DOWNGRADE_SAFEMODE_THRESHOLD: scala.Double = js.native
  val CONTROLLER_MAX_UPGRADE_PER_TICK: scala.Double = js.native
  val CONTROLLER_NUKE_BLOCKED_UPGRADE: scala.Double = js.native
  val CONTROLLER_RESERVE: scala.Double = js.native
  val CONTROLLER_RESERVE_MAX: scala.Double = js.native
  val CONTROLLER_STRUCTURES: stdLib.Record[
    BuildableStructureConstant, 
    org.scalablytyped.runtime.NumberDictionary[scala.Double]
  ] = js.native
  val CREEP_CLAIM_LIFE_TIME: screepsLib.screepsLibNumbers.`600` = js.native
  val CREEP_CORPSE_RATE: screepsLib.screepsLibNumbers.`0DOT2` = js.native
  val CREEP_LIFE_TIME: screepsLib.screepsLibNumbers.`1500` = js.native
  val CREEP_SPAWN_TIME: screepsLib.screepsLibNumbers.`3` = js.native
  val ConstructionSite: ConstructionSiteConstructor = js.native
  val Creep: CreepConstructor = js.native
  val DENSITY_HIGH: scala.Double = js.native
  val DENSITY_LOW: scala.Double = js.native
  val DENSITY_MODERATE: scala.Double = js.native
  val DENSITY_ULTRA: scala.Double = js.native
  val DISMANTLE_COST: screepsLib.screepsLibNumbers.`0DOT005` = js.native
  val DISMANTLE_POWER: screepsLib.screepsLibNumbers.`50` = js.native
  val ENERGY_DECAY: screepsLib.screepsLibNumbers.`1000` = js.native
  val ENERGY_REGEN_TIME: screepsLib.screepsLibNumbers.`300` = js.native
  val ERR_BUSY: screepsLib.screepsLibNumbers.`-4` = js.native
  val ERR_FULL: screepsLib.screepsLibNumbers.`-8` = js.native
  val ERR_GCL_NOT_ENOUGH: screepsLib.screepsLibNumbers.`-15` = js.native
  val ERR_INVALID_ARGS: screepsLib.screepsLibNumbers.`-10` = js.native
  val ERR_INVALID_TARGET: screepsLib.screepsLibNumbers.`-7` = js.native
  val ERR_NAME_EXISTS: screepsLib.screepsLibNumbers.`-3` = js.native
  val ERR_NOT_ENOUGH_ENERGY: screepsLib.screepsLibNumbers.`-6` = js.native
  val ERR_NOT_ENOUGH_EXTENSIONS: screepsLib.screepsLibNumbers.`-6` = js.native
  val ERR_NOT_ENOUGH_RESOURCES: screepsLib.screepsLibNumbers.`-6` = js.native
  val ERR_NOT_FOUND: screepsLib.screepsLibNumbers.`-5` = js.native
  val ERR_NOT_IN_RANGE: screepsLib.screepsLibNumbers.`-9` = js.native
  val ERR_NOT_OWNER: screepsLib.screepsLibNumbers.`-1` = js.native
  val ERR_NO_BODYPART: screepsLib.screepsLibNumbers.`-12` = js.native
  val ERR_NO_PATH: screepsLib.screepsLibNumbers.`-2` = js.native
  val ERR_RCL_NOT_ENOUGH: screepsLib.screepsLibNumbers.`-14` = js.native
  val ERR_TIRED: screepsLib.screepsLibNumbers.`-11` = js.native
  val EVENT_ATTACK: screepsLib.screepsLibNumbers.`1` = js.native
  val EVENT_ATTACK_CONTROLLER: screepsLib.screepsLibNumbers.`3` = js.native
  val EVENT_ATTACK_TYPE_DISMANTLE: screepsLib.screepsLibNumbers.`4` = js.native
  val EVENT_ATTACK_TYPE_HIT_BACK: screepsLib.screepsLibNumbers.`5` = js.native
  val EVENT_ATTACK_TYPE_MELEE: screepsLib.screepsLibNumbers.`1` = js.native
  val EVENT_ATTACK_TYPE_NUKE: screepsLib.screepsLibNumbers.`6` = js.native
  val EVENT_ATTACK_TYPE_RANGED: screepsLib.screepsLibNumbers.`2` = js.native
  val EVENT_ATTACK_TYPE_RANGED_MASS: screepsLib.screepsLibNumbers.`3` = js.native
  val EVENT_BUILD: screepsLib.screepsLibNumbers.`4` = js.native
  val EVENT_EXIT: screepsLib.screepsLibNumbers.`10` = js.native
  val EVENT_HARVEST: screepsLib.screepsLibNumbers.`5` = js.native
  val EVENT_HEAL: screepsLib.screepsLibNumbers.`6` = js.native
  val EVENT_HEAL_TYPE_MELEE: screepsLib.screepsLibNumbers.`1` = js.native
  val EVENT_HEAL_TYPE_RANGED: screepsLib.screepsLibNumbers.`2` = js.native
  val EVENT_OBJECT_DESTROYED: screepsLib.screepsLibNumbers.`2` = js.native
  val EVENT_REPAIR: screepsLib.screepsLibNumbers.`7` = js.native
  val EVENT_RESERVE_CONTROLLER: screepsLib.screepsLibNumbers.`8` = js.native
  val EVENT_UPGRADE_CONTROLLER: screepsLib.screepsLibNumbers.`9` = js.native
  val EXTENSION_HITS: screepsLib.screepsLibNumbers.`1000` = js.native
  val EXTRACTOR_COOLDOWN: scala.Double = js.native
  val EXTRACTOR_HITS: scala.Double = js.native
  val FIND_CONSTRUCTION_SITES: screepsLib.screepsLibNumbers.`111` = js.native
  val FIND_CREEPS: screepsLib.screepsLibNumbers.`101` = js.native
  /** `FIND_DROPPED_ENERGY` is deprecated the return value is the same as `FIND_DROPPED_RESOURCES` */
  val FIND_DROPPED_ENERGY: screepsLib.screepsLibNumbers.`-106` = js.native
  val FIND_DROPPED_RESOURCES: screepsLib.screepsLibNumbers.`106` = js.native
  val FIND_EXIT: screepsLib.screepsLibNumbers.`10` = js.native
  val FIND_EXIT_BOTTOM: screepsLib.screepsLibNumbers.`5` = js.native
  val FIND_EXIT_LEFT: screepsLib.screepsLibNumbers.`7` = js.native
  val FIND_EXIT_RIGHT: screepsLib.screepsLibNumbers.`3` = js.native
  val FIND_EXIT_TOP: screepsLib.screepsLibNumbers.`1` = js.native
  val FIND_FLAGS: screepsLib.screepsLibNumbers.`110` = js.native
  val FIND_HOSTILE_CONSTRUCTION_SITES: screepsLib.screepsLibNumbers.`115` = js.native
  val FIND_HOSTILE_CREEPS: screepsLib.screepsLibNumbers.`103` = js.native
  val FIND_HOSTILE_SPAWNS: screepsLib.screepsLibNumbers.`113` = js.native
  val FIND_HOSTILE_STRUCTURES: screepsLib.screepsLibNumbers.`109` = js.native
  val FIND_MINERALS: screepsLib.screepsLibNumbers.`116` = js.native
  val FIND_MY_CONSTRUCTION_SITES: screepsLib.screepsLibNumbers.`114` = js.native
  val FIND_MY_CREEPS: screepsLib.screepsLibNumbers.`102` = js.native
  val FIND_MY_SPAWNS: screepsLib.screepsLibNumbers.`112` = js.native
  val FIND_MY_STRUCTURES: screepsLib.screepsLibNumbers.`108` = js.native
  val FIND_NUKES: screepsLib.screepsLibNumbers.`117` = js.native
  val FIND_SOURCES: screepsLib.screepsLibNumbers.`105` = js.native
  val FIND_SOURCES_ACTIVE: screepsLib.screepsLibNumbers.`104` = js.native
  val FIND_STRUCTURES: screepsLib.screepsLibNumbers.`107` = js.native
  val FIND_TOMBSTONES: screepsLib.screepsLibNumbers.`118` = js.native
  val Flag: FlagConstructor = js.native
  val GCL_MULTIPLY: scala.Double = js.native
  val GCL_NOVICE: scala.Double = js.native
  val GCL_POW: scala.Double = js.native
  var Game: Game = js.native
  val HARVEST_MINERAL_POWER: screepsLib.screepsLibNumbers.`1` = js.native
  val HARVEST_POWER: screepsLib.screepsLibNumbers.`2` = js.native
  val HEAL: screepsLib.screepsLibStrings.heal = js.native
  val HEAL_POWER: screepsLib.screepsLibNumbers.`12` = js.native
  val INVADERS_ENERGY_GOAL: scala.Double = js.native
  val LAB_BOOST_ENERGY: scala.Double = js.native
  val LAB_BOOST_MINERAL: scala.Double = js.native
  val LAB_COOLDOWN: scala.Double = js.native
  val LAB_ENERGY_CAPACITY: scala.Double = js.native
  val LAB_HITS: scala.Double = js.native
  val LAB_MINERAL_CAPACITY: scala.Double = js.native
  val LAB_REACTION_AMOUNT: scala.Double = js.native
  val LEFT: screepsLib.screepsLibNumbers.`7` = js.native
  val LINK_CAPACITY: screepsLib.screepsLibNumbers.`800` = js.native
  val LINK_COOLDOWN: screepsLib.screepsLibNumbers.`1` = js.native
  val LINK_HITS: screepsLib.screepsLibNumbers.`1000` = js.native
  val LINK_HITS_MAX: screepsLib.screepsLibNumbers.`1000` = js.native
  val LINK_LOSS_RATIO: screepsLib.screepsLibNumbers.`0DOT03` = js.native
  val LOOK_CONSTRUCTION_SITES: screepsLib.screepsLibStrings.constructionSite = js.native
  val LOOK_CREEPS: screepsLib.screepsLibStrings.creep = js.native
  val LOOK_ENERGY: screepsLib.screepsLibStrings.energy = js.native
  val LOOK_FLAGS: screepsLib.screepsLibStrings.flag = js.native
  val LOOK_MINERALS: screepsLib.screepsLibStrings.mineral = js.native
  val LOOK_NUKES: screepsLib.screepsLibStrings.nuke = js.native
  val LOOK_RESOURCES: screepsLib.screepsLibStrings.resource = js.native
  val LOOK_SOURCES: screepsLib.screepsLibStrings.source = js.native
  val LOOK_STRUCTURES: screepsLib.screepsLibStrings.structure = js.native
  val LOOK_TERRAIN: screepsLib.screepsLibStrings.terrain = js.native
  val LOOK_TOMBSTONES: screepsLib.screepsLibStrings.tombstone = js.native
  val MAX_CONSTRUCTION_SITES: scala.Double = js.native
  val MAX_CREEP_SIZE: scala.Double = js.native
  val MINERAL_DENSITY_CHANGE: scala.Double = js.native
  val MINERAL_MIN_AMOUNT: stdLib.Record[MineralConstant, scala.Double] = js.native
  val MINERAL_RANDOM_FACTOR: scala.Double = js.native
  val MINERAL_REGEN_TIME: scala.Double = js.native
  val MODE_ARENA: java.lang.String = js.native
  val MODE_SIMULATION: java.lang.String = js.native
  val MODE_SURVIVAL: java.lang.String = js.native
  val MODE_WORLD: java.lang.String = js.native
  val MOVE: screepsLib.screepsLibStrings.move = js.native
  val Memory: Memory = js.native
  val Mineral: MineralConstructor = js.native
  val NUKER_COOLDOWN: scala.Double = js.native
  val NUKER_ENERGY_CAPACITY: scala.Double = js.native
  val NUKER_GHODIUM_CAPACITY: scala.Double = js.native
  val NUKER_HITS: scala.Double = js.native
  val NUKE_LAND_TIME: scala.Double = js.native
  val NUKE_RANGE: scala.Double = js.native
  val Nuke: NukeConstructor = js.native
  val OBSERVER_HITS: scala.Double = js.native
  val OBSERVER_RANGE: scala.Double = js.native
  val OBSTACLE_OBJECT_TYPES: js.Tuple15[
    screepsLib.screepsLibStrings.spawn, 
    screepsLib.screepsLibStrings.creep, 
    screepsLib.screepsLibStrings.wall, 
    screepsLib.screepsLibStrings.source, 
    screepsLib.screepsLibStrings.constructedWall, 
    screepsLib.screepsLibStrings.extension, 
    screepsLib.screepsLibStrings.link, 
    screepsLib.screepsLibStrings.storage, 
    screepsLib.screepsLibStrings.tower, 
    screepsLib.screepsLibStrings.observer, 
    screepsLib.screepsLibStrings.powerSpawn, 
    screepsLib.screepsLibStrings.powerBank, 
    screepsLib.screepsLibStrings.lab, 
    screepsLib.screepsLibStrings.terminal, 
    screepsLib.screepsLibStrings.nuker
  ] = js.native
  val OK: screepsLib.screepsLibNumbers.`0` = js.native
  val ORDER_BUY: screepsLib.screepsLibStrings.buy = js.native
  val ORDER_SELL: screepsLib.screepsLibStrings.sell = js.native
  val OwnedStructure: OwnedStructureConstructor = js.native
  val POWER_BANK_CAPACITY_CRIT: scala.Double = js.native
  val POWER_BANK_CAPACITY_MAX: scala.Double = js.native
  val POWER_BANK_CAPACITY_MIN: scala.Double = js.native
  val POWER_BANK_DECAY: scala.Double = js.native
  val POWER_BANK_HITS: scala.Double = js.native
  val POWER_BANK_HIT_BACK: scala.Double = js.native
  val POWER_SPAWN_ENERGY_CAPACITY: scala.Double = js.native
  val POWER_SPAWN_ENERGY_RATIO: scala.Double = js.native
  val POWER_SPAWN_HITS: scala.Double = js.native
  val POWER_SPAWN_POWER_CAPACITY: scala.Double = js.native
  val PathFinder: PathFinder = js.native
  val RAMPART_DECAY_AMOUNT: screepsLib.screepsLibNumbers.`300` = js.native
  val RAMPART_DECAY_TIME: screepsLib.screepsLibNumbers.`100` = js.native
  val RAMPART_HITS: screepsLib.screepsLibNumbers.`1` = js.native
  val RANGED_ATTACK: screepsLib.screepsLibStrings.ranged_attack = js.native
  val RANGED_ATTACK_POWER: screepsLib.screepsLibNumbers.`10` = js.native
  val RANGED_HEAL_POWER: screepsLib.screepsLibNumbers.`4` = js.native
  val REPAIR_COST: screepsLib.screepsLibNumbers.`0DOT01` = js.native
  val REPAIR_POWER: screepsLib.screepsLibNumbers.`100` = js.native
  val RESOURCES_ALL: js.Array[ResourceConstant] = js.native
  val RESOURCE_CATALYST: screepsLib.screepsLibStrings.X = js.native
  val RESOURCE_CATALYZED_GHODIUM_ACID: screepsLib.screepsLibStrings.XGH2O = js.native
  val RESOURCE_CATALYZED_GHODIUM_ALKALIDE: screepsLib.screepsLibStrings.XGHO2 = js.native
  val RESOURCE_CATALYZED_KEANIUM_ACID: screepsLib.screepsLibStrings.XKH2O = js.native
  val RESOURCE_CATALYZED_KEANIUM_ALKALIDE: screepsLib.screepsLibStrings.XKHO2 = js.native
  val RESOURCE_CATALYZED_LEMERGIUM_ACID: screepsLib.screepsLibStrings.XLH2O = js.native
  val RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE: screepsLib.screepsLibStrings.XLHO2 = js.native
  val RESOURCE_CATALYZED_UTRIUM_ACID: screepsLib.screepsLibStrings.XUH2O = js.native
  val RESOURCE_CATALYZED_UTRIUM_ALKALIDE: screepsLib.screepsLibStrings.XUHO2 = js.native
  val RESOURCE_CATALYZED_ZYNTHIUM_ACID: screepsLib.screepsLibStrings.XZH2O = js.native
  val RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE: screepsLib.screepsLibStrings.XZHO2 = js.native
  val RESOURCE_ENERGY: screepsLib.screepsLibStrings.energy = js.native
  val RESOURCE_GHODIUM: screepsLib.screepsLibStrings.G = js.native
  val RESOURCE_GHODIUM_ACID: screepsLib.screepsLibStrings.GH2O = js.native
  val RESOURCE_GHODIUM_ALKALIDE: screepsLib.screepsLibStrings.GHO2 = js.native
  val RESOURCE_GHODIUM_HYDRIDE: screepsLib.screepsLibStrings.GH = js.native
  val RESOURCE_GHODIUM_OXIDE: screepsLib.screepsLibStrings.GO = js.native
  val RESOURCE_HYDROGEN: screepsLib.screepsLibStrings.H = js.native
  val RESOURCE_HYDROXIDE: screepsLib.screepsLibStrings.OH = js.native
  val RESOURCE_KEANIUM: screepsLib.screepsLibStrings.K = js.native
  val RESOURCE_KEANIUM_ACID: screepsLib.screepsLibStrings.KH2O = js.native
  val RESOURCE_KEANIUM_ALKALIDE: screepsLib.screepsLibStrings.KHO2 = js.native
  val RESOURCE_KEANIUM_HYDRIDE: screepsLib.screepsLibStrings.KH = js.native
  val RESOURCE_KEANIUM_OXIDE: screepsLib.screepsLibStrings.KO = js.native
  val RESOURCE_LEMERGIUM: screepsLib.screepsLibStrings.L = js.native
  val RESOURCE_LEMERGIUM_ACID: screepsLib.screepsLibStrings.LH2O = js.native
  val RESOURCE_LEMERGIUM_ALKALIDE: screepsLib.screepsLibStrings.LHO2 = js.native
  val RESOURCE_LEMERGIUM_HYDRIDE: screepsLib.screepsLibStrings.LH = js.native
  val RESOURCE_LEMERGIUM_OXIDE: screepsLib.screepsLibStrings.LO = js.native
  val RESOURCE_OXYGEN: screepsLib.screepsLibStrings.O = js.native
  val RESOURCE_POWER: screepsLib.screepsLibStrings.power = js.native
  val RESOURCE_UTRIUM: screepsLib.screepsLibStrings.U = js.native
  val RESOURCE_UTRIUM_ACID: screepsLib.screepsLibStrings.UH2O = js.native
  val RESOURCE_UTRIUM_ALKALIDE: screepsLib.screepsLibStrings.UHO2 = js.native
  val RESOURCE_UTRIUM_HYDRIDE: screepsLib.screepsLibStrings.UH = js.native
  val RESOURCE_UTRIUM_LEMERGITE: screepsLib.screepsLibStrings.UL = js.native
  val RESOURCE_UTRIUM_OXIDE: screepsLib.screepsLibStrings.UO = js.native
  val RESOURCE_ZYNTHIUM: screepsLib.screepsLibStrings.Z = js.native
  val RESOURCE_ZYNTHIUM_ACID: screepsLib.screepsLibStrings.ZH2O = js.native
  val RESOURCE_ZYNTHIUM_ALKALIDE: screepsLib.screepsLibStrings.ZHO2 = js.native
  val RESOURCE_ZYNTHIUM_HYDRIDE: screepsLib.screepsLibStrings.ZH = js.native
  val RESOURCE_ZYNTHIUM_KEANITE: screepsLib.screepsLibStrings.ZK = js.native
  val RESOURCE_ZYNTHIUM_OXIDE: screepsLib.screepsLibStrings.ZO = js.native
  val RIGHT: screepsLib.screepsLibNumbers.`3` = js.native
  val ROAD_DECAY_AMOUNT: screepsLib.screepsLibNumbers.`100` = js.native
  val ROAD_DECAY_TIME: screepsLib.screepsLibNumbers.`1000` = js.native
  val ROAD_HITS: screepsLib.screepsLibNumbers.`5000` = js.native
  val ROAD_WEAROUT: screepsLib.screepsLibNumbers.`1` = js.native
  val RawMemory: RawMemory = js.native
  val Resource: ResourceConstructor = js.native
  val Room: RoomConstructor = js.native
  val RoomObject: RoomObjectConstructor = js.native
  val RoomPosition: RoomPositionConstructor = js.native
  val SAFE_MODE_COOLDOWN: screepsLib.screepsLibNumbers.`50000` = js.native
  val SAFE_MODE_COST: screepsLib.screepsLibNumbers.`1000` = js.native
  val SAFE_MODE_DURATION: screepsLib.screepsLibNumbers.`20000` = js.native
  val SOURCE_ENERGY_CAPACITY: screepsLib.screepsLibNumbers.`3000` = js.native
  val SOURCE_ENERGY_KEEPER_CAPACITY: screepsLib.screepsLibNumbers.`4000` = js.native
  val SOURCE_ENERGY_NEUTRAL_CAPACITY: screepsLib.screepsLibNumbers.`1500` = js.native
  val SPAWN_ENERGY_CAPACITY: screepsLib.screepsLibNumbers.`300` = js.native
  val SPAWN_ENERGY_START: screepsLib.screepsLibNumbers.`300` = js.native
  val SPAWN_HITS: screepsLib.screepsLibNumbers.`5000` = js.native
  val STORAGE_CAPACITY: screepsLib.screepsLibNumbers.`1000000` = js.native
  val STORAGE_HITS: screepsLib.screepsLibNumbers.`10000` = js.native
  val STRUCTURE_CONTAINER: screepsLib.screepsLibStrings.container = js.native
  val STRUCTURE_CONTROLLER: screepsLib.screepsLibStrings.controller = js.native
  val STRUCTURE_EXTENSION: screepsLib.screepsLibStrings.extension = js.native
  val STRUCTURE_EXTRACTOR: screepsLib.screepsLibStrings.extractor = js.native
  val STRUCTURE_KEEPER_LAIR: screepsLib.screepsLibStrings.keeperLair = js.native
  val STRUCTURE_LAB: screepsLib.screepsLibStrings.lab = js.native
  val STRUCTURE_LINK: screepsLib.screepsLibStrings.link = js.native
  val STRUCTURE_NUKER: screepsLib.screepsLibStrings.nuker = js.native
  val STRUCTURE_OBSERVER: screepsLib.screepsLibStrings.observer = js.native
  val STRUCTURE_PORTAL: screepsLib.screepsLibStrings.portal = js.native
  val STRUCTURE_POWER_BANK: screepsLib.screepsLibStrings.powerBank = js.native
  val STRUCTURE_POWER_SPAWN: screepsLib.screepsLibStrings.powerSpawn = js.native
  val STRUCTURE_RAMPART: screepsLib.screepsLibStrings.rampart = js.native
  val STRUCTURE_ROAD: screepsLib.screepsLibStrings.road = js.native
  val STRUCTURE_SPAWN: screepsLib.screepsLibStrings.spawn = js.native
  val STRUCTURE_STORAGE: screepsLib.screepsLibStrings.storage = js.native
  val STRUCTURE_TERMINAL: screepsLib.screepsLibStrings.terminal = js.native
  val STRUCTURE_TOWER: screepsLib.screepsLibStrings.tower = js.native
  val STRUCTURE_WALL: screepsLib.screepsLibStrings.constructedWall = js.native
  val SUBSCRIPTION_TOKEN: screepsLib.screepsLibStrings.token = js.native
  val SYSTEM_USERNAME: java.lang.String = js.native
  val Source: SourceConstructor = js.native
  val Spawn: StructureSpawnConstructor = js.native
  val Structure: StructureConstructor = js.native
  val StructureContainer: StructureContainerConstructor = js.native
  val StructureController: StructureControllerConstructor = js.native
  val StructureExtension: StructureExtensionConstructor = js.native
  val StructureExtractor: StructureExtractorConstructor = js.native
  val StructureKeeperLair: StructureKeeperLairConstructor = js.native
  val StructureLab: StructureLabConstructor = js.native
  val StructureLink: StructureLinkConstructor = js.native
  val StructureNuker: StructureNukerConstructor = js.native
  val StructureObserver: StructureObserverConstructor = js.native
  val StructurePortal: StructurePortalConstructor = js.native
  val StructurePowerBank: StructurePowerBankConstructor = js.native
  val StructurePowerSpawn: StructurePowerSpawnConstructor = js.native
  val StructureRampart: StructureRampartConstructor = js.native
  val StructureRoad: StructureRoadConstructor = js.native
  val StructureSpawn: StructureSpawnConstructor = js.native
  val StructureStorage: StructureStorageConstructor = js.native
  val StructureTerminal: StructureTerminalConstructor = js.native
  val StructureTower: StructureTowerConstructor = js.native
  val StructureWall: StructureWallConstructor = js.native
  val TERMINAL_CAPACITY: scala.Double = js.native
  val TERMINAL_COOLDOWN: scala.Double = js.native
  val TERMINAL_HITS: scala.Double = js.native
  val TERMINAL_MIN_SEND: scala.Double = js.native
  val TERMINAL_SEND_COST: scala.Double = js.native
  val TERRAIN_MASK_LAVA: scala.Double = js.native
  val TERRAIN_MASK_SWAMP: scala.Double = js.native
  val TERRAIN_MASK_WALL: scala.Double = js.native
  val TOMBSTONE_DECAY_PER_PART: screepsLib.screepsLibNumbers.`5` = js.native
  val TOP: screepsLib.screepsLibNumbers.`1` = js.native
  val TOP_LEFT: screepsLib.screepsLibNumbers.`8` = js.native
  val TOP_RIGHT: screepsLib.screepsLibNumbers.`2` = js.native
  val TOUGH: screepsLib.screepsLibStrings.tough = js.native
  val TOWER_CAPACITY: scala.Double = js.native
  val TOWER_ENERGY_COST: scala.Double = js.native
  val TOWER_FALLOFF: scala.Double = js.native
  val TOWER_FALLOFF_RANGE: scala.Double = js.native
  val TOWER_HITS: scala.Double = js.native
  val TOWER_OPTIMAL_RANGE: scala.Double = js.native
  val TOWER_POWER_ATTACK: scala.Double = js.native
  val TOWER_POWER_HEAL: scala.Double = js.native
  val TOWER_POWER_REPAIR: scala.Double = js.native
  val Tombstone: TombstoneConstructor = js.native
  val UPGRADE_CONTROLLER_POWER: screepsLib.screepsLibNumbers.`1` = js.native
  val WALL_HITS: screepsLib.screepsLibNumbers.`1` = js.native
  val WALL_HITS_MAX: screepsLib.screepsLibNumbers.`300000000` = js.native
  val WORK: screepsLib.screepsLibStrings.work = js.native
}

