package typings.atPulumiAws.apigatewayApiKeyMod

import typings.atPulumiPulumi.outputMod.Input
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait ApiKeyState extends js.Object {
  /**
    * The creation date of the API key
    */
  val createdDate: js.UndefOr[Input[String]] = js.undefined
  val description: js.UndefOr[Input[String]] = js.undefined
  /**
    * Specifies whether the API key can be used by callers. Defaults to `true`.
    */
  val enabled: js.UndefOr[Input[Boolean]] = js.undefined
  /**
    * The last update date of the API key
    */
  val lastUpdatedDate: js.UndefOr[Input[String]] = js.undefined
  /**
    * The name of the API key
    */
  val name: js.UndefOr[Input[String]] = js.undefined
  /**
    * The value of the API key. If not specified, it will be automatically generated by AWS on creation.
    */
  val value: js.UndefOr[Input[String]] = js.undefined
}

object ApiKeyState {
  @scala.inline
  def apply(
    createdDate: Input[String] = null,
    description: Input[String] = null,
    enabled: Input[Boolean] = null,
    lastUpdatedDate: Input[String] = null,
    name: Input[String] = null,
    value: Input[String] = null
  ): ApiKeyState = {
    val __obj = js.Dynamic.literal()
    if (createdDate != null) __obj.updateDynamic("createdDate")(createdDate.asInstanceOf[js.Any])
    if (description != null) __obj.updateDynamic("description")(description.asInstanceOf[js.Any])
    if (enabled != null) __obj.updateDynamic("enabled")(enabled.asInstanceOf[js.Any])
    if (lastUpdatedDate != null) __obj.updateDynamic("lastUpdatedDate")(lastUpdatedDate.asInstanceOf[js.Any])
    if (name != null) __obj.updateDynamic("name")(name.asInstanceOf[js.Any])
    if (value != null) __obj.updateDynamic("value")(value.asInstanceOf[js.Any])
    __obj.asInstanceOf[ApiKeyState]
  }
}

