package typings
package reactDashNativeDashMaterialDashUiLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

object reactDashNativeDashMaterialDashUiLibComponents {
  @scala.inline
  def Account: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerHeaderAccountProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerNs.HeaderNs.Account].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerHeaderAccountProps]]
  @scala.inline
  def Action: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BottomNavigationAction
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BottomNavigationNs.Action].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BottomNavigationAction]]
  @scala.inline
  def ActionButton: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ActionButtonProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ActionButton].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ActionButtonProps]]
  @scala.inline
  def Actions: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogActionsProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogNs.Actions].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogActionsProps]]
  @scala.inline
  def Avatar: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.AvatarProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.Avatar].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.AvatarProps]]
  @scala.inline
  def Badge: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BadgeProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.Badge].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BadgeProps]]
  @scala.inline
  def BottomNavigation: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BottomNavigationProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BottomNavigation].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BottomNavigationProps]]
  @scala.inline
  def Button: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ButtonProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.Button].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ButtonProps]]
  @scala.inline
  def Card: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.CardProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.Card].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.CardProps]]
  @scala.inline
  def Checkbox: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.CheckBoxProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.Checkbox].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.CheckBoxProps]]
  @scala.inline
  def Consumer: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ThemeConsumerProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ThemeContextNs.Consumer].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ThemeConsumerProps]]
  @scala.inline
  def Content: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogContentProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogNs.Content].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogContentProps]]
  @scala.inline
  def Dialog: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.Dialog].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogProps]]
  @scala.inline
  def DialogDefaultActions: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogDefaultActionsProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogDefaultActions].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogDefaultActionsProps]]
  @scala.inline
  def DialogStackedActions: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogStackedActionsProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogStackedActions].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogStackedActionsProps]]
  @scala.inline
  def Divider: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DividerProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.Divider].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DividerProps]]
  @scala.inline
  def Drawer: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.Drawer].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerProps]]
  @scala.inline
  def Header: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerHeaderProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerNs.Header].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerHeaderProps]]
  @scala.inline
  def Icon: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.IconProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.Icon].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.IconProps]]
  @scala.inline
  def IconToggle: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.IconToggleProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.IconToggle].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.IconToggleProps]]
  @scala.inline
  def ListItem: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ListItemProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ListItem].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ListItemProps]]
  @scala.inline
  def Provider: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ThemeProviderProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ThemeContextNs.Provider].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ThemeProviderProps]]
  @scala.inline
  def RadioButton: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.RadioButtonProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.RadioButton].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.RadioButtonProps]]
  @scala.inline
  def RippleFeedback: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.RippleFeedbackProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.RippleFeedback].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.RippleFeedbackProps]]
  @scala.inline
  def Section: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerSectionProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerNs.Section].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerSectionProps]]
  @scala.inline
  def Snackbar: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.SnackbarProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.Snackbar].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.SnackbarProps]]
  @scala.inline
  def Subheader: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.SubheaderProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.Subheader].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.SubheaderProps]]
  @scala.inline
  def Title: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogTitleProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogNs.Title].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogTitleProps]]
  @scala.inline
  def Toolbar: reactLib.reactMod.ComponentType[
    reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ToolbarProps
  ] = js.constructorOf[reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.Toolbar].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ToolbarProps]]
  @scala.inline
  def ActionButtonProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ActionButtonProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ActionButtonProps
  type ActionButtonProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ActionButtonProps
  @scala.inline
  def AvatarProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.AvatarProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.AvatarProps
  type AvatarProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.AvatarProps
  @scala.inline
  def BadgeProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BadgeProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BadgeProps
  type BadgeProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BadgeProps
  @scala.inline
  def BottomNavigationAction: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BottomNavigationAction.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BottomNavigationAction
  type BottomNavigationAction = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BottomNavigationAction
  @scala.inline
  def BottomNavigationProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BottomNavigationProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BottomNavigationProps
  type BottomNavigationProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.BottomNavigationProps
  @scala.inline
  def ButtonProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ButtonProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ButtonProps
  type ButtonProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ButtonProps
  @scala.inline
  def CardProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.CardProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.CardProps
  type CardProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.CardProps
  @scala.inline
  def CheckBoxProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.CheckBoxProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.CheckBoxProps
  type CheckBoxProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.CheckBoxProps
  @scala.inline
  def DialogActionsProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogActionsProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogActionsProps
  type DialogActionsProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogActionsProps
  @scala.inline
  def DialogContentProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogContentProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogContentProps
  type DialogContentProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogContentProps
  @scala.inline
  def DialogDefaultActionsProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogDefaultActionsProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogDefaultActionsProps
  type DialogDefaultActionsProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogDefaultActionsProps
  @scala.inline
  def DialogProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogProps
  type DialogProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogProps
  @scala.inline
  def DialogStackedActionsProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogStackedActionsProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogStackedActionsProps
  type DialogStackedActionsProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogStackedActionsProps
  @scala.inline
  def DialogTitleProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogTitleProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogTitleProps
  type DialogTitleProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DialogTitleProps
  @scala.inline
  def DividerProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DividerProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DividerProps
  type DividerProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DividerProps
  @scala.inline
  def DrawerHeaderAccountProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerHeaderAccountProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerHeaderAccountProps
  type DrawerHeaderAccountProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerHeaderAccountProps
  @scala.inline
  def DrawerHeaderProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerHeaderProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerHeaderProps
  type DrawerHeaderProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerHeaderProps
  @scala.inline
  def DrawerProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerProps
  type DrawerProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerProps
  @scala.inline
  def DrawerSectionProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerSectionProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerSectionProps
  type DrawerSectionProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.DrawerSectionProps
  @scala.inline
  def IconProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.IconProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.IconProps
  type IconProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.IconProps
  @scala.inline
  def IconToggleProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.IconToggleProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.IconToggleProps
  type IconToggleProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.IconToggleProps
  @scala.inline
  def ListItemProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ListItemProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ListItemProps
  type ListItemProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ListItemProps
  @scala.inline
  def RadioButtonProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.RadioButtonProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.RadioButtonProps
  type RadioButtonProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.RadioButtonProps
  @scala.inline
  def RippleFeedbackProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.RippleFeedbackProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.RippleFeedbackProps
  type RippleFeedbackProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.RippleFeedbackProps
  @scala.inline
  def SnackbarProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.SnackbarProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.SnackbarProps
  type SnackbarProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.SnackbarProps
  @scala.inline
  def SubheaderProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.SubheaderProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.SubheaderProps
  type SubheaderProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.SubheaderProps
  @scala.inline
  def ThemeConsumerProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ThemeConsumerProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ThemeConsumerProps
  type ThemeConsumerProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ThemeConsumerProps
  @scala.inline
  def ThemeProviderProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ThemeProviderProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ThemeProviderProps
  type ThemeProviderProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ThemeProviderProps
  @scala.inline
  def ToolbarProps: reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ToolbarProps.type = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ToolbarProps
  type ToolbarProps = reactDashNativeDashMaterialDashUiLib.reactDashNativeDashMaterialDashUiMod.ToolbarProps
}

