package typings
package semanticDashUiDashAccordionLib.SemanticUINs

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object AccordionSettingsNs {
  type Param = (stdLib.Pick[
    _Impl, 
    semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.exclusive | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.on | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.animateChildren | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.closeNested | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.collapsible | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.duration | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.easing | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.observeChanges | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.onOpening | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.onOpen | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.onClosing | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.onClose | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.onChange | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.selector | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.className | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.error | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.namespace | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.name | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.silent | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.debug | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.performance | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.verbose
  ]) with (stdLib.Partial[
    stdLib.Pick[
      _Impl, 
      semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.exclusive | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.on | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.animateChildren | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.closeNested | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.collapsible | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.duration | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.easing | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.observeChanges | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.selector | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.className | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.error | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.namespace | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.name | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.silent | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.debug | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.performance | semanticDashUiDashAccordionLib.semanticDashUiDashAccordionLibStrings.verbose
    ]
  ])
}
