package typings.ionicCore.virtualScrollUtilsMod

import typings.ionicCore.virtualScrollInterfaceMod.Cell
import typings.ionicCore.virtualScrollInterfaceMod.FooterHeightFn
import typings.ionicCore.virtualScrollInterfaceMod.HeaderFn
import typings.ionicCore.virtualScrollInterfaceMod.HeaderHeightFn
import typings.ionicCore.virtualScrollInterfaceMod.ItemHeightFn
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

@JSImport("@ionic/core/dist/types/components/virtual-scroll/virtual-scroll-utils", "calcCells")
@js.native
object calcCells extends js.Object {
  
  def apply(
    items: js.Array[_],
    itemHeight: js.UndefOr[scala.Nothing],
    headerHeight: js.UndefOr[scala.Nothing],
    footerHeight: js.UndefOr[scala.Nothing],
    headerFn: js.UndefOr[scala.Nothing],
    footerFn: js.UndefOr[scala.Nothing],
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: js.UndefOr[scala.Nothing],
    headerHeight: js.UndefOr[scala.Nothing],
    footerHeight: js.UndefOr[scala.Nothing],
    headerFn: js.UndefOr[scala.Nothing],
    footerFn: HeaderFn,
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: js.UndefOr[scala.Nothing],
    headerHeight: js.UndefOr[scala.Nothing],
    footerHeight: js.UndefOr[scala.Nothing],
    headerFn: HeaderFn,
    footerFn: js.UndefOr[scala.Nothing],
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: js.UndefOr[scala.Nothing],
    headerHeight: js.UndefOr[scala.Nothing],
    footerHeight: js.UndefOr[scala.Nothing],
    headerFn: HeaderFn,
    footerFn: HeaderFn,
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: js.UndefOr[scala.Nothing],
    headerHeight: js.UndefOr[scala.Nothing],
    footerHeight: FooterHeightFn,
    headerFn: js.UndefOr[scala.Nothing],
    footerFn: js.UndefOr[scala.Nothing],
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: js.UndefOr[scala.Nothing],
    headerHeight: js.UndefOr[scala.Nothing],
    footerHeight: FooterHeightFn,
    headerFn: js.UndefOr[scala.Nothing],
    footerFn: HeaderFn,
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: js.UndefOr[scala.Nothing],
    headerHeight: js.UndefOr[scala.Nothing],
    footerHeight: FooterHeightFn,
    headerFn: HeaderFn,
    footerFn: js.UndefOr[scala.Nothing],
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: js.UndefOr[scala.Nothing],
    headerHeight: js.UndefOr[scala.Nothing],
    footerHeight: FooterHeightFn,
    headerFn: HeaderFn,
    footerFn: HeaderFn,
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: js.UndefOr[scala.Nothing],
    headerHeight: HeaderHeightFn,
    footerHeight: js.UndefOr[scala.Nothing],
    headerFn: js.UndefOr[scala.Nothing],
    footerFn: js.UndefOr[scala.Nothing],
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: js.UndefOr[scala.Nothing],
    headerHeight: HeaderHeightFn,
    footerHeight: js.UndefOr[scala.Nothing],
    headerFn: js.UndefOr[scala.Nothing],
    footerFn: HeaderFn,
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: js.UndefOr[scala.Nothing],
    headerHeight: HeaderHeightFn,
    footerHeight: js.UndefOr[scala.Nothing],
    headerFn: HeaderFn,
    footerFn: js.UndefOr[scala.Nothing],
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: js.UndefOr[scala.Nothing],
    headerHeight: HeaderHeightFn,
    footerHeight: js.UndefOr[scala.Nothing],
    headerFn: HeaderFn,
    footerFn: HeaderFn,
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: js.UndefOr[scala.Nothing],
    headerHeight: HeaderHeightFn,
    footerHeight: FooterHeightFn,
    headerFn: js.UndefOr[scala.Nothing],
    footerFn: js.UndefOr[scala.Nothing],
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: js.UndefOr[scala.Nothing],
    headerHeight: HeaderHeightFn,
    footerHeight: FooterHeightFn,
    headerFn: js.UndefOr[scala.Nothing],
    footerFn: HeaderFn,
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: js.UndefOr[scala.Nothing],
    headerHeight: HeaderHeightFn,
    footerHeight: FooterHeightFn,
    headerFn: HeaderFn,
    footerFn: js.UndefOr[scala.Nothing],
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: js.UndefOr[scala.Nothing],
    headerHeight: HeaderHeightFn,
    footerHeight: FooterHeightFn,
    headerFn: HeaderFn,
    footerFn: HeaderFn,
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: ItemHeightFn,
    headerHeight: js.UndefOr[scala.Nothing],
    footerHeight: js.UndefOr[scala.Nothing],
    headerFn: js.UndefOr[scala.Nothing],
    footerFn: js.UndefOr[scala.Nothing],
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: ItemHeightFn,
    headerHeight: js.UndefOr[scala.Nothing],
    footerHeight: js.UndefOr[scala.Nothing],
    headerFn: js.UndefOr[scala.Nothing],
    footerFn: HeaderFn,
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: ItemHeightFn,
    headerHeight: js.UndefOr[scala.Nothing],
    footerHeight: js.UndefOr[scala.Nothing],
    headerFn: HeaderFn,
    footerFn: js.UndefOr[scala.Nothing],
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: ItemHeightFn,
    headerHeight: js.UndefOr[scala.Nothing],
    footerHeight: js.UndefOr[scala.Nothing],
    headerFn: HeaderFn,
    footerFn: HeaderFn,
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: ItemHeightFn,
    headerHeight: js.UndefOr[scala.Nothing],
    footerHeight: FooterHeightFn,
    headerFn: js.UndefOr[scala.Nothing],
    footerFn: js.UndefOr[scala.Nothing],
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: ItemHeightFn,
    headerHeight: js.UndefOr[scala.Nothing],
    footerHeight: FooterHeightFn,
    headerFn: js.UndefOr[scala.Nothing],
    footerFn: HeaderFn,
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: ItemHeightFn,
    headerHeight: js.UndefOr[scala.Nothing],
    footerHeight: FooterHeightFn,
    headerFn: HeaderFn,
    footerFn: js.UndefOr[scala.Nothing],
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: ItemHeightFn,
    headerHeight: js.UndefOr[scala.Nothing],
    footerHeight: FooterHeightFn,
    headerFn: HeaderFn,
    footerFn: HeaderFn,
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: ItemHeightFn,
    headerHeight: HeaderHeightFn,
    footerHeight: js.UndefOr[scala.Nothing],
    headerFn: js.UndefOr[scala.Nothing],
    footerFn: js.UndefOr[scala.Nothing],
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: ItemHeightFn,
    headerHeight: HeaderHeightFn,
    footerHeight: js.UndefOr[scala.Nothing],
    headerFn: js.UndefOr[scala.Nothing],
    footerFn: HeaderFn,
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: ItemHeightFn,
    headerHeight: HeaderHeightFn,
    footerHeight: js.UndefOr[scala.Nothing],
    headerFn: HeaderFn,
    footerFn: js.UndefOr[scala.Nothing],
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: ItemHeightFn,
    headerHeight: HeaderHeightFn,
    footerHeight: js.UndefOr[scala.Nothing],
    headerFn: HeaderFn,
    footerFn: HeaderFn,
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: ItemHeightFn,
    headerHeight: HeaderHeightFn,
    footerHeight: FooterHeightFn,
    headerFn: js.UndefOr[scala.Nothing],
    footerFn: js.UndefOr[scala.Nothing],
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: ItemHeightFn,
    headerHeight: HeaderHeightFn,
    footerHeight: FooterHeightFn,
    headerFn: js.UndefOr[scala.Nothing],
    footerFn: HeaderFn,
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: ItemHeightFn,
    headerHeight: HeaderHeightFn,
    footerHeight: FooterHeightFn,
    headerFn: HeaderFn,
    footerFn: js.UndefOr[scala.Nothing],
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
  def apply(
    items: js.Array[_],
    itemHeight: ItemHeightFn,
    headerHeight: HeaderHeightFn,
    footerHeight: FooterHeightFn,
    headerFn: HeaderFn,
    footerFn: HeaderFn,
    approxHeaderHeight: Double,
    approxFooterHeight: Double,
    approxItemHeight: Double,
    j: Double,
    offset: Double,
    len: Double
  ): js.Array[Cell] = js.native
}
