package typings
package reactDashGoogleDashPlacesDashSuggestLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

object reactDashGoogleDashPlacesDashSuggestLibComponents {
  @scala.inline
  def ReactDashGoogleDashPlacesDashSuggest: reactLib.reactMod.ComponentType[
    reactDashGoogleDashPlacesDashSuggestLib.reactDashGoogleDashPlacesDashSuggestMod.ReactGooglePlacesSuggestNs.Props
  ] = js.constructorOf[reactDashGoogleDashPlacesDashSuggestLib.reactDashGoogleDashPlacesDashSuggestMod.default].asInstanceOf[reactLib.reactMod.ComponentType[
  reactDashGoogleDashPlacesDashSuggestLib.reactDashGoogleDashPlacesDashSuggestMod.ReactGooglePlacesSuggestNs.Props]]
  @scala.inline
  def ReactDashGoogleDashPlacesDashSuggestProps: reactDashGoogleDashPlacesDashSuggestLib.reactDashGoogleDashPlacesDashSuggestMod.ReactGooglePlacesSuggestNs.Props.type = reactDashGoogleDashPlacesDashSuggestLib.reactDashGoogleDashPlacesDashSuggestMod.ReactGooglePlacesSuggestNs.Props
  type ReactDashGoogleDashPlacesDashSuggestProps = reactDashGoogleDashPlacesDashSuggestLib.reactDashGoogleDashPlacesDashSuggestMod.ReactGooglePlacesSuggestNs.Props
}

