package typings.awsDashSdk.libConfigUnderscoreServiceUnderscorePlaceholdersMod

import typings.awsDashSdk.clientsAcmMod.apiVersion
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait ConfigurationServiceApiVersions extends js.Object {
  var acm: js.UndefOr[apiVersion] = js.undefined
  var acmpca: js.UndefOr[typings.awsDashSdk.clientsAcmpcaMod.apiVersion] = js.undefined
  var alexaforbusiness: js.UndefOr[typings.awsDashSdk.clientsAlexaforbusinessMod.apiVersion] = js.undefined
  var amplify: js.UndefOr[typings.awsDashSdk.clientsAmplifyMod.apiVersion] = js.undefined
  var apigateway: js.UndefOr[typings.awsDashSdk.clientsApigatewayMod.apiVersion] = js.undefined
  var apigatewaymanagementapi: js.UndefOr[typings.awsDashSdk.clientsApigatewaymanagementapiMod.apiVersion] = js.undefined
  var apigatewayv2: js.UndefOr[typings.awsDashSdk.clientsApigatewayv2Mod.apiVersion] = js.undefined
  var applicationautoscaling: js.UndefOr[typings.awsDashSdk.clientsApplicationautoscalingMod.apiVersion] = js.undefined
  var applicationinsights: js.UndefOr[typings.awsDashSdk.clientsApplicationinsightsMod.apiVersion] = js.undefined
  var appmesh: js.UndefOr[typings.awsDashSdk.clientsAppmeshMod.apiVersion] = js.undefined
  var appstream: js.UndefOr[typings.awsDashSdk.clientsAppstreamMod.apiVersion] = js.undefined
  var appsync: js.UndefOr[typings.awsDashSdk.clientsAppsyncMod.apiVersion] = js.undefined
  var athena: js.UndefOr[typings.awsDashSdk.clientsAthenaMod.apiVersion] = js.undefined
  var autoscaling: js.UndefOr[typings.awsDashSdk.clientsAutoscalingMod.apiVersion] = js.undefined
  var autoscalingplans: js.UndefOr[typings.awsDashSdk.clientsAutoscalingplansMod.apiVersion] = js.undefined
  var backup: js.UndefOr[typings.awsDashSdk.clientsBackupMod.apiVersion] = js.undefined
  var batch: js.UndefOr[typings.awsDashSdk.clientsBatchMod.apiVersion] = js.undefined
  var budgets: js.UndefOr[typings.awsDashSdk.clientsBudgetsMod.apiVersion] = js.undefined
  var chime: js.UndefOr[typings.awsDashSdk.clientsChimeMod.apiVersion] = js.undefined
  var cloud9: js.UndefOr[typings.awsDashSdk.clientsCloud9Mod.apiVersion] = js.undefined
  var clouddirectory: js.UndefOr[typings.awsDashSdk.clientsClouddirectoryMod.apiVersion] = js.undefined
  var cloudformation: js.UndefOr[typings.awsDashSdk.clientsCloudformationMod.apiVersion] = js.undefined
  var cloudfront: js.UndefOr[typings.awsDashSdk.clientsCloudfrontMod.apiVersion] = js.undefined
  var cloudhsm: js.UndefOr[typings.awsDashSdk.clientsCloudhsmMod.apiVersion] = js.undefined
  var cloudhsmv2: js.UndefOr[typings.awsDashSdk.clientsCloudhsmv2Mod.apiVersion] = js.undefined
  var cloudsearch: js.UndefOr[typings.awsDashSdk.clientsCloudsearchMod.apiVersion] = js.undefined
  var cloudsearchdomain: js.UndefOr[typings.awsDashSdk.clientsCloudsearchdomainMod.apiVersion] = js.undefined
  var cloudtrail: js.UndefOr[typings.awsDashSdk.clientsCloudtrailMod.apiVersion] = js.undefined
  var cloudwatch: js.UndefOr[typings.awsDashSdk.clientsCloudwatchMod.apiVersion] = js.undefined
  var cloudwatchevents: js.UndefOr[typings.awsDashSdk.clientsCloudwatcheventsMod.apiVersion] = js.undefined
  var cloudwatchlogs: js.UndefOr[typings.awsDashSdk.clientsCloudwatchlogsMod.apiVersion] = js.undefined
  var codebuild: js.UndefOr[typings.awsDashSdk.clientsCodebuildMod.apiVersion] = js.undefined
  var codecommit: js.UndefOr[typings.awsDashSdk.clientsCodecommitMod.apiVersion] = js.undefined
  var codedeploy: js.UndefOr[typings.awsDashSdk.clientsCodedeployMod.apiVersion] = js.undefined
  var codepipeline: js.UndefOr[typings.awsDashSdk.clientsCodepipelineMod.apiVersion] = js.undefined
  var codestar: js.UndefOr[typings.awsDashSdk.clientsCodestarMod.apiVersion] = js.undefined
  var cognitoidentity: js.UndefOr[typings.awsDashSdk.clientsCognitoidentityMod.apiVersion] = js.undefined
  var cognitoidentityserviceprovider: js.UndefOr[typings.awsDashSdk.clientsCognitoidentityserviceproviderMod.apiVersion] = js.undefined
  var cognitosync: js.UndefOr[typings.awsDashSdk.clientsCognitosyncMod.apiVersion] = js.undefined
  var comprehend: js.UndefOr[typings.awsDashSdk.clientsComprehendMod.apiVersion] = js.undefined
  var comprehendmedical: js.UndefOr[typings.awsDashSdk.clientsComprehendmedicalMod.apiVersion] = js.undefined
  var configservice: js.UndefOr[typings.awsDashSdk.clientsConfigserviceMod.apiVersion] = js.undefined
  var connect: js.UndefOr[typings.awsDashSdk.clientsConnectMod.apiVersion] = js.undefined
  var costexplorer: js.UndefOr[typings.awsDashSdk.clientsCostexplorerMod.apiVersion] = js.undefined
  var cur: js.UndefOr[typings.awsDashSdk.clientsCurMod.apiVersion] = js.undefined
  var datapipeline: js.UndefOr[typings.awsDashSdk.clientsDatapipelineMod.apiVersion] = js.undefined
  var datasync: js.UndefOr[typings.awsDashSdk.clientsDatasyncMod.apiVersion] = js.undefined
  var dax: js.UndefOr[typings.awsDashSdk.clientsDaxMod.apiVersion] = js.undefined
  var devicefarm: js.UndefOr[typings.awsDashSdk.clientsDevicefarmMod.apiVersion] = js.undefined
  var directconnect: js.UndefOr[typings.awsDashSdk.clientsDirectconnectMod.apiVersion] = js.undefined
  var directoryservice: js.UndefOr[typings.awsDashSdk.clientsDirectoryserviceMod.apiVersion] = js.undefined
  var discovery: js.UndefOr[typings.awsDashSdk.clientsDiscoveryMod.apiVersion] = js.undefined
  var dlm: js.UndefOr[typings.awsDashSdk.clientsDlmMod.apiVersion] = js.undefined
  var dms: js.UndefOr[typings.awsDashSdk.clientsDmsMod.apiVersion] = js.undefined
  var docdb: js.UndefOr[typings.awsDashSdk.clientsDocdbMod.apiVersion] = js.undefined
  var dynamodb: js.UndefOr[typings.awsDashSdk.clientsDynamodbMod.apiVersion] = js.undefined
  var dynamodbstreams: js.UndefOr[typings.awsDashSdk.clientsDynamodbstreamsMod.apiVersion] = js.undefined
  var ec2: js.UndefOr[typings.awsDashSdk.clientsEc2Mod.apiVersion] = js.undefined
  var ec2instanceconnect: js.UndefOr[typings.awsDashSdk.clientsEc2instanceconnectMod.apiVersion] = js.undefined
  var ecr: js.UndefOr[typings.awsDashSdk.clientsEcrMod.apiVersion] = js.undefined
  var ecs: js.UndefOr[typings.awsDashSdk.clientsEcsMod.apiVersion] = js.undefined
  var efs: js.UndefOr[typings.awsDashSdk.clientsEfsMod.apiVersion] = js.undefined
  var eks: js.UndefOr[typings.awsDashSdk.clientsEksMod.apiVersion] = js.undefined
  var elasticache: js.UndefOr[typings.awsDashSdk.clientsElasticacheMod.apiVersion] = js.undefined
  var elasticbeanstalk: js.UndefOr[typings.awsDashSdk.clientsElasticbeanstalkMod.apiVersion] = js.undefined
  var elastictranscoder: js.UndefOr[typings.awsDashSdk.clientsElastictranscoderMod.apiVersion] = js.undefined
  var elb: js.UndefOr[typings.awsDashSdk.clientsElbMod.apiVersion] = js.undefined
  var elbv2: js.UndefOr[typings.awsDashSdk.clientsElbv2Mod.apiVersion] = js.undefined
  var emr: js.UndefOr[typings.awsDashSdk.clientsEmrMod.apiVersion] = js.undefined
  var es: js.UndefOr[typings.awsDashSdk.clientsEsMod.apiVersion] = js.undefined
  var eventbridge: js.UndefOr[typings.awsDashSdk.clientsEventbridgeMod.apiVersion] = js.undefined
  var firehose: js.UndefOr[typings.awsDashSdk.clientsFirehoseMod.apiVersion] = js.undefined
  var fms: js.UndefOr[typings.awsDashSdk.clientsFmsMod.apiVersion] = js.undefined
  var forecastqueryservice: js.UndefOr[typings.awsDashSdk.clientsForecastqueryserviceMod.apiVersion] = js.undefined
  var forecastservice: js.UndefOr[typings.awsDashSdk.clientsForecastserviceMod.apiVersion] = js.undefined
  var fsx: js.UndefOr[typings.awsDashSdk.clientsFsxMod.apiVersion] = js.undefined
  var gamelift: js.UndefOr[typings.awsDashSdk.clientsGameliftMod.apiVersion] = js.undefined
  var glacier: js.UndefOr[typings.awsDashSdk.clientsGlacierMod.apiVersion] = js.undefined
  var globalaccelerator: js.UndefOr[typings.awsDashSdk.clientsGlobalacceleratorMod.apiVersion] = js.undefined
  var glue: js.UndefOr[typings.awsDashSdk.clientsGlueMod.apiVersion] = js.undefined
  var greengrass: js.UndefOr[typings.awsDashSdk.clientsGreengrassMod.apiVersion] = js.undefined
  var groundstation: js.UndefOr[typings.awsDashSdk.clientsGroundstationMod.apiVersion] = js.undefined
  var guardduty: js.UndefOr[typings.awsDashSdk.clientsGuarddutyMod.apiVersion] = js.undefined
  var health: js.UndefOr[typings.awsDashSdk.clientsHealthMod.apiVersion] = js.undefined
  var iam: js.UndefOr[typings.awsDashSdk.clientsIamMod.apiVersion] = js.undefined
  var importexport: js.UndefOr[typings.awsDashSdk.clientsImportexportMod.apiVersion] = js.undefined
  var inspector: js.UndefOr[typings.awsDashSdk.clientsInspectorMod.apiVersion] = js.undefined
  var iot: js.UndefOr[typings.awsDashSdk.clientsIotMod.apiVersion] = js.undefined
  var iot1clickdevicesservice: js.UndefOr[typings.awsDashSdk.clientsIot1clickdevicesserviceMod.apiVersion] = js.undefined
  var iot1clickprojects: js.UndefOr[typings.awsDashSdk.clientsIot1clickprojectsMod.apiVersion] = js.undefined
  var iotanalytics: js.UndefOr[typings.awsDashSdk.clientsIotanalyticsMod.apiVersion] = js.undefined
  var iotdata: js.UndefOr[typings.awsDashSdk.clientsIotdataMod.apiVersion] = js.undefined
  var iotevents: js.UndefOr[typings.awsDashSdk.clientsIoteventsMod.apiVersion] = js.undefined
  var ioteventsdata: js.UndefOr[typings.awsDashSdk.clientsIoteventsdataMod.apiVersion] = js.undefined
  var iotjobsdataplane: js.UndefOr[typings.awsDashSdk.clientsIotjobsdataplaneMod.apiVersion] = js.undefined
  var iotthingsgraph: js.UndefOr[typings.awsDashSdk.clientsIotthingsgraphMod.apiVersion] = js.undefined
  var kafka: js.UndefOr[typings.awsDashSdk.clientsKafkaMod.apiVersion] = js.undefined
  var kinesis: js.UndefOr[typings.awsDashSdk.clientsKinesisMod.apiVersion] = js.undefined
  var kinesisanalytics: js.UndefOr[typings.awsDashSdk.clientsKinesisanalyticsMod.apiVersion] = js.undefined
  var kinesisanalyticsv2: js.UndefOr[typings.awsDashSdk.clientsKinesisanalyticsv2Mod.apiVersion] = js.undefined
  var kinesisvideo: js.UndefOr[typings.awsDashSdk.clientsKinesisvideoMod.apiVersion] = js.undefined
  var kinesisvideoarchivedmedia: js.UndefOr[typings.awsDashSdk.clientsKinesisvideoarchivedmediaMod.apiVersion] = js.undefined
  var kinesisvideomedia: js.UndefOr[typings.awsDashSdk.clientsKinesisvideomediaMod.apiVersion] = js.undefined
  var kms: js.UndefOr[typings.awsDashSdk.clientsKmsMod.apiVersion] = js.undefined
  var lakeformation: js.UndefOr[typings.awsDashSdk.clientsLakeformationMod.apiVersion] = js.undefined
  var lambda: js.UndefOr[typings.awsDashSdk.clientsLambdaMod.apiVersion] = js.undefined
  var lexmodelbuildingservice: js.UndefOr[typings.awsDashSdk.clientsLexmodelbuildingserviceMod.apiVersion] = js.undefined
  var lexruntime: js.UndefOr[typings.awsDashSdk.clientsLexruntimeMod.apiVersion] = js.undefined
  var licensemanager: js.UndefOr[typings.awsDashSdk.clientsLicensemanagerMod.apiVersion] = js.undefined
  var lightsail: js.UndefOr[typings.awsDashSdk.clientsLightsailMod.apiVersion] = js.undefined
  var machinelearning: js.UndefOr[typings.awsDashSdk.clientsMachinelearningMod.apiVersion] = js.undefined
  var macie: js.UndefOr[typings.awsDashSdk.clientsMacieMod.apiVersion] = js.undefined
  var managedblockchain: js.UndefOr[typings.awsDashSdk.clientsManagedblockchainMod.apiVersion] = js.undefined
  var marketplacecommerceanalytics: js.UndefOr[typings.awsDashSdk.clientsMarketplacecommerceanalyticsMod.apiVersion] = js.undefined
  var marketplaceentitlementservice: js.UndefOr[typings.awsDashSdk.clientsMarketplaceentitlementserviceMod.apiVersion] = js.undefined
  var marketplacemetering: js.UndefOr[typings.awsDashSdk.clientsMarketplacemeteringMod.apiVersion] = js.undefined
  var mediaconnect: js.UndefOr[typings.awsDashSdk.clientsMediaconnectMod.apiVersion] = js.undefined
  var mediaconvert: js.UndefOr[typings.awsDashSdk.clientsMediaconvertMod.apiVersion] = js.undefined
  var medialive: js.UndefOr[typings.awsDashSdk.clientsMedialiveMod.apiVersion] = js.undefined
  var mediapackage: js.UndefOr[typings.awsDashSdk.clientsMediapackageMod.apiVersion] = js.undefined
  var mediapackagevod: js.UndefOr[typings.awsDashSdk.clientsMediapackagevodMod.apiVersion] = js.undefined
  var mediastore: js.UndefOr[typings.awsDashSdk.clientsMediastoreMod.apiVersion] = js.undefined
  var mediastoredata: js.UndefOr[typings.awsDashSdk.clientsMediastoredataMod.apiVersion] = js.undefined
  var mediatailor: js.UndefOr[typings.awsDashSdk.clientsMediatailorMod.apiVersion] = js.undefined
  var migrationhub: js.UndefOr[typings.awsDashSdk.clientsMigrationhubMod.apiVersion] = js.undefined
  var mobile: js.UndefOr[typings.awsDashSdk.clientsMobileMod.apiVersion] = js.undefined
  var mobileanalytics: js.UndefOr[typings.awsDashSdk.clientsMobileanalyticsMod.apiVersion] = js.undefined
  var mq: js.UndefOr[typings.awsDashSdk.clientsMqMod.apiVersion] = js.undefined
  var mturk: js.UndefOr[typings.awsDashSdk.clientsMturkMod.apiVersion] = js.undefined
  var neptune: js.UndefOr[typings.awsDashSdk.clientsNeptuneMod.apiVersion] = js.undefined
  var opsworks: js.UndefOr[typings.awsDashSdk.clientsOpsworksMod.apiVersion] = js.undefined
  var opsworkscm: js.UndefOr[typings.awsDashSdk.clientsOpsworkscmMod.apiVersion] = js.undefined
  var organizations: js.UndefOr[typings.awsDashSdk.clientsOrganizationsMod.apiVersion] = js.undefined
  var personalize: js.UndefOr[typings.awsDashSdk.clientsPersonalizeMod.apiVersion] = js.undefined
  var personalizeevents: js.UndefOr[typings.awsDashSdk.clientsPersonalizeeventsMod.apiVersion] = js.undefined
  var personalizeruntime: js.UndefOr[typings.awsDashSdk.clientsPersonalizeruntimeMod.apiVersion] = js.undefined
  var pi: js.UndefOr[typings.awsDashSdk.clientsPiMod.apiVersion] = js.undefined
  var pinpoint: js.UndefOr[typings.awsDashSdk.clientsPinpointMod.apiVersion] = js.undefined
  var pinpointemail: js.UndefOr[typings.awsDashSdk.clientsPinpointemailMod.apiVersion] = js.undefined
  var pinpointsmsvoice: js.UndefOr[typings.awsDashSdk.clientsPinpointsmsvoiceMod.apiVersion] = js.undefined
  var polly: js.UndefOr[typings.awsDashSdk.clientsPollyMod.apiVersion] = js.undefined
  var pricing: js.UndefOr[typings.awsDashSdk.clientsPricingMod.apiVersion] = js.undefined
  var qldb: js.UndefOr[typings.awsDashSdk.clientsQldbMod.apiVersion] = js.undefined
  var qldbsession: js.UndefOr[typings.awsDashSdk.clientsQldbsessionMod.apiVersion] = js.undefined
  var quicksight: js.UndefOr[typings.awsDashSdk.clientsQuicksightMod.apiVersion] = js.undefined
  var ram: js.UndefOr[typings.awsDashSdk.clientsRamMod.apiVersion] = js.undefined
  var rds: js.UndefOr[typings.awsDashSdk.clientsRdsMod.apiVersion] = js.undefined
  var rdsdataservice: js.UndefOr[typings.awsDashSdk.clientsRdsdataserviceMod.apiVersion] = js.undefined
  var redshift: js.UndefOr[typings.awsDashSdk.clientsRedshiftMod.apiVersion] = js.undefined
  var rekognition: js.UndefOr[typings.awsDashSdk.clientsRekognitionMod.apiVersion] = js.undefined
  var resourcegroups: js.UndefOr[typings.awsDashSdk.clientsResourcegroupsMod.apiVersion] = js.undefined
  var resourcegroupstaggingapi: js.UndefOr[typings.awsDashSdk.clientsResourcegroupstaggingapiMod.apiVersion] = js.undefined
  var robomaker: js.UndefOr[typings.awsDashSdk.clientsRobomakerMod.apiVersion] = js.undefined
  var route53: js.UndefOr[typings.awsDashSdk.clientsRoute53Mod.apiVersion] = js.undefined
  var route53domains: js.UndefOr[typings.awsDashSdk.clientsRoute53domainsMod.apiVersion] = js.undefined
  var route53resolver: js.UndefOr[typings.awsDashSdk.clientsRoute53resolverMod.apiVersion] = js.undefined
  var s3: js.UndefOr[typings.awsDashSdk.clientsS3Mod.apiVersion] = js.undefined
  var s3control: js.UndefOr[typings.awsDashSdk.clientsS3controlMod.apiVersion] = js.undefined
  var sagemaker: js.UndefOr[typings.awsDashSdk.clientsSagemakerMod.apiVersion] = js.undefined
  var sagemakerruntime: js.UndefOr[typings.awsDashSdk.clientsSagemakerruntimeMod.apiVersion] = js.undefined
  var secretsmanager: js.UndefOr[typings.awsDashSdk.clientsSecretsmanagerMod.apiVersion] = js.undefined
  var securityhub: js.UndefOr[typings.awsDashSdk.clientsSecurityhubMod.apiVersion] = js.undefined
  var serverlessapplicationrepository: js.UndefOr[typings.awsDashSdk.clientsServerlessapplicationrepositoryMod.apiVersion] = js.undefined
  var servicecatalog: js.UndefOr[typings.awsDashSdk.clientsServicecatalogMod.apiVersion] = js.undefined
  var servicediscovery: js.UndefOr[typings.awsDashSdk.clientsServicediscoveryMod.apiVersion] = js.undefined
  var servicequotas: js.UndefOr[typings.awsDashSdk.clientsServicequotasMod.apiVersion] = js.undefined
  var ses: js.UndefOr[typings.awsDashSdk.clientsSesMod.apiVersion] = js.undefined
  var shield: js.UndefOr[typings.awsDashSdk.clientsShieldMod.apiVersion] = js.undefined
  var signer: js.UndefOr[typings.awsDashSdk.clientsSignerMod.apiVersion] = js.undefined
  var simpledb: js.UndefOr[typings.awsDashSdk.clientsSimpledbMod.apiVersion] = js.undefined
  var sms: js.UndefOr[typings.awsDashSdk.clientsSmsMod.apiVersion] = js.undefined
  var snowball: js.UndefOr[typings.awsDashSdk.clientsSnowballMod.apiVersion] = js.undefined
  var sns: js.UndefOr[typings.awsDashSdk.clientsSnsMod.apiVersion] = js.undefined
  var sqs: js.UndefOr[typings.awsDashSdk.clientsSqsMod.apiVersion] = js.undefined
  var ssm: js.UndefOr[typings.awsDashSdk.clientsSsmMod.apiVersion] = js.undefined
  var stepfunctions: js.UndefOr[typings.awsDashSdk.clientsStepfunctionsMod.apiVersion] = js.undefined
  var storagegateway: js.UndefOr[typings.awsDashSdk.clientsStoragegatewayMod.apiVersion] = js.undefined
  var sts: js.UndefOr[typings.awsDashSdk.clientsStsMod.apiVersion] = js.undefined
  var support: js.UndefOr[typings.awsDashSdk.clientsSupportMod.apiVersion] = js.undefined
  var swf: js.UndefOr[typings.awsDashSdk.clientsSwfMod.apiVersion] = js.undefined
  var textract: js.UndefOr[typings.awsDashSdk.clientsTextractMod.apiVersion] = js.undefined
  var transcribeservice: js.UndefOr[typings.awsDashSdk.clientsTranscribeserviceMod.apiVersion] = js.undefined
  var transfer: js.UndefOr[typings.awsDashSdk.clientsTransferMod.apiVersion] = js.undefined
  var translate: js.UndefOr[typings.awsDashSdk.clientsTranslateMod.apiVersion] = js.undefined
  var waf: js.UndefOr[typings.awsDashSdk.clientsWafMod.apiVersion] = js.undefined
  var wafregional: js.UndefOr[typings.awsDashSdk.clientsWafregionalMod.apiVersion] = js.undefined
  var workdocs: js.UndefOr[typings.awsDashSdk.clientsWorkdocsMod.apiVersion] = js.undefined
  var worklink: js.UndefOr[typings.awsDashSdk.clientsWorklinkMod.apiVersion] = js.undefined
  var workmail: js.UndefOr[typings.awsDashSdk.clientsWorkmailMod.apiVersion] = js.undefined
  var workspaces: js.UndefOr[typings.awsDashSdk.clientsWorkspacesMod.apiVersion] = js.undefined
  var xray: js.UndefOr[typings.awsDashSdk.clientsXrayMod.apiVersion] = js.undefined
}

object ConfigurationServiceApiVersions {
  @scala.inline
  def apply(
    acm: apiVersion = null,
    acmpca: typings.awsDashSdk.clientsAcmpcaMod.apiVersion = null,
    alexaforbusiness: typings.awsDashSdk.clientsAlexaforbusinessMod.apiVersion = null,
    amplify: typings.awsDashSdk.clientsAmplifyMod.apiVersion = null,
    apigateway: typings.awsDashSdk.clientsApigatewayMod.apiVersion = null,
    apigatewaymanagementapi: typings.awsDashSdk.clientsApigatewaymanagementapiMod.apiVersion = null,
    apigatewayv2: typings.awsDashSdk.clientsApigatewayv2Mod.apiVersion = null,
    applicationautoscaling: typings.awsDashSdk.clientsApplicationautoscalingMod.apiVersion = null,
    applicationinsights: typings.awsDashSdk.clientsApplicationinsightsMod.apiVersion = null,
    appmesh: typings.awsDashSdk.clientsAppmeshMod.apiVersion = null,
    appstream: typings.awsDashSdk.clientsAppstreamMod.apiVersion = null,
    appsync: typings.awsDashSdk.clientsAppsyncMod.apiVersion = null,
    athena: typings.awsDashSdk.clientsAthenaMod.apiVersion = null,
    autoscaling: typings.awsDashSdk.clientsAutoscalingMod.apiVersion = null,
    autoscalingplans: typings.awsDashSdk.clientsAutoscalingplansMod.apiVersion = null,
    backup: typings.awsDashSdk.clientsBackupMod.apiVersion = null,
    batch: typings.awsDashSdk.clientsBatchMod.apiVersion = null,
    budgets: typings.awsDashSdk.clientsBudgetsMod.apiVersion = null,
    chime: typings.awsDashSdk.clientsChimeMod.apiVersion = null,
    cloud9: typings.awsDashSdk.clientsCloud9Mod.apiVersion = null,
    clouddirectory: typings.awsDashSdk.clientsClouddirectoryMod.apiVersion = null,
    cloudformation: typings.awsDashSdk.clientsCloudformationMod.apiVersion = null,
    cloudfront: typings.awsDashSdk.clientsCloudfrontMod.apiVersion = null,
    cloudhsm: typings.awsDashSdk.clientsCloudhsmMod.apiVersion = null,
    cloudhsmv2: typings.awsDashSdk.clientsCloudhsmv2Mod.apiVersion = null,
    cloudsearch: typings.awsDashSdk.clientsCloudsearchMod.apiVersion = null,
    cloudsearchdomain: typings.awsDashSdk.clientsCloudsearchdomainMod.apiVersion = null,
    cloudtrail: typings.awsDashSdk.clientsCloudtrailMod.apiVersion = null,
    cloudwatch: typings.awsDashSdk.clientsCloudwatchMod.apiVersion = null,
    cloudwatchevents: typings.awsDashSdk.clientsCloudwatcheventsMod.apiVersion = null,
    cloudwatchlogs: typings.awsDashSdk.clientsCloudwatchlogsMod.apiVersion = null,
    codebuild: typings.awsDashSdk.clientsCodebuildMod.apiVersion = null,
    codecommit: typings.awsDashSdk.clientsCodecommitMod.apiVersion = null,
    codedeploy: typings.awsDashSdk.clientsCodedeployMod.apiVersion = null,
    codepipeline: typings.awsDashSdk.clientsCodepipelineMod.apiVersion = null,
    codestar: typings.awsDashSdk.clientsCodestarMod.apiVersion = null,
    cognitoidentity: typings.awsDashSdk.clientsCognitoidentityMod.apiVersion = null,
    cognitoidentityserviceprovider: typings.awsDashSdk.clientsCognitoidentityserviceproviderMod.apiVersion = null,
    cognitosync: typings.awsDashSdk.clientsCognitosyncMod.apiVersion = null,
    comprehend: typings.awsDashSdk.clientsComprehendMod.apiVersion = null,
    comprehendmedical: typings.awsDashSdk.clientsComprehendmedicalMod.apiVersion = null,
    configservice: typings.awsDashSdk.clientsConfigserviceMod.apiVersion = null,
    connect: typings.awsDashSdk.clientsConnectMod.apiVersion = null,
    costexplorer: typings.awsDashSdk.clientsCostexplorerMod.apiVersion = null,
    cur: typings.awsDashSdk.clientsCurMod.apiVersion = null,
    datapipeline: typings.awsDashSdk.clientsDatapipelineMod.apiVersion = null,
    datasync: typings.awsDashSdk.clientsDatasyncMod.apiVersion = null,
    dax: typings.awsDashSdk.clientsDaxMod.apiVersion = null,
    devicefarm: typings.awsDashSdk.clientsDevicefarmMod.apiVersion = null,
    directconnect: typings.awsDashSdk.clientsDirectconnectMod.apiVersion = null,
    directoryservice: typings.awsDashSdk.clientsDirectoryserviceMod.apiVersion = null,
    discovery: typings.awsDashSdk.clientsDiscoveryMod.apiVersion = null,
    dlm: typings.awsDashSdk.clientsDlmMod.apiVersion = null,
    dms: typings.awsDashSdk.clientsDmsMod.apiVersion = null,
    docdb: typings.awsDashSdk.clientsDocdbMod.apiVersion = null,
    dynamodb: typings.awsDashSdk.clientsDynamodbMod.apiVersion = null,
    dynamodbstreams: typings.awsDashSdk.clientsDynamodbstreamsMod.apiVersion = null,
    ec2: typings.awsDashSdk.clientsEc2Mod.apiVersion = null,
    ec2instanceconnect: typings.awsDashSdk.clientsEc2instanceconnectMod.apiVersion = null,
    ecr: typings.awsDashSdk.clientsEcrMod.apiVersion = null,
    ecs: typings.awsDashSdk.clientsEcsMod.apiVersion = null,
    efs: typings.awsDashSdk.clientsEfsMod.apiVersion = null,
    eks: typings.awsDashSdk.clientsEksMod.apiVersion = null,
    elasticache: typings.awsDashSdk.clientsElasticacheMod.apiVersion = null,
    elasticbeanstalk: typings.awsDashSdk.clientsElasticbeanstalkMod.apiVersion = null,
    elastictranscoder: typings.awsDashSdk.clientsElastictranscoderMod.apiVersion = null,
    elb: typings.awsDashSdk.clientsElbMod.apiVersion = null,
    elbv2: typings.awsDashSdk.clientsElbv2Mod.apiVersion = null,
    emr: typings.awsDashSdk.clientsEmrMod.apiVersion = null,
    es: typings.awsDashSdk.clientsEsMod.apiVersion = null,
    eventbridge: typings.awsDashSdk.clientsEventbridgeMod.apiVersion = null,
    firehose: typings.awsDashSdk.clientsFirehoseMod.apiVersion = null,
    fms: typings.awsDashSdk.clientsFmsMod.apiVersion = null,
    forecastqueryservice: typings.awsDashSdk.clientsForecastqueryserviceMod.apiVersion = null,
    forecastservice: typings.awsDashSdk.clientsForecastserviceMod.apiVersion = null,
    fsx: typings.awsDashSdk.clientsFsxMod.apiVersion = null,
    gamelift: typings.awsDashSdk.clientsGameliftMod.apiVersion = null,
    glacier: typings.awsDashSdk.clientsGlacierMod.apiVersion = null,
    globalaccelerator: typings.awsDashSdk.clientsGlobalacceleratorMod.apiVersion = null,
    glue: typings.awsDashSdk.clientsGlueMod.apiVersion = null,
    greengrass: typings.awsDashSdk.clientsGreengrassMod.apiVersion = null,
    groundstation: typings.awsDashSdk.clientsGroundstationMod.apiVersion = null,
    guardduty: typings.awsDashSdk.clientsGuarddutyMod.apiVersion = null,
    health: typings.awsDashSdk.clientsHealthMod.apiVersion = null,
    iam: typings.awsDashSdk.clientsIamMod.apiVersion = null,
    importexport: typings.awsDashSdk.clientsImportexportMod.apiVersion = null,
    inspector: typings.awsDashSdk.clientsInspectorMod.apiVersion = null,
    iot: typings.awsDashSdk.clientsIotMod.apiVersion = null,
    iot1clickdevicesservice: typings.awsDashSdk.clientsIot1clickdevicesserviceMod.apiVersion = null,
    iot1clickprojects: typings.awsDashSdk.clientsIot1clickprojectsMod.apiVersion = null,
    iotanalytics: typings.awsDashSdk.clientsIotanalyticsMod.apiVersion = null,
    iotdata: typings.awsDashSdk.clientsIotdataMod.apiVersion = null,
    iotevents: typings.awsDashSdk.clientsIoteventsMod.apiVersion = null,
    ioteventsdata: typings.awsDashSdk.clientsIoteventsdataMod.apiVersion = null,
    iotjobsdataplane: typings.awsDashSdk.clientsIotjobsdataplaneMod.apiVersion = null,
    iotthingsgraph: typings.awsDashSdk.clientsIotthingsgraphMod.apiVersion = null,
    kafka: typings.awsDashSdk.clientsKafkaMod.apiVersion = null,
    kinesis: typings.awsDashSdk.clientsKinesisMod.apiVersion = null,
    kinesisanalytics: typings.awsDashSdk.clientsKinesisanalyticsMod.apiVersion = null,
    kinesisanalyticsv2: typings.awsDashSdk.clientsKinesisanalyticsv2Mod.apiVersion = null,
    kinesisvideo: typings.awsDashSdk.clientsKinesisvideoMod.apiVersion = null,
    kinesisvideoarchivedmedia: typings.awsDashSdk.clientsKinesisvideoarchivedmediaMod.apiVersion = null,
    kinesisvideomedia: typings.awsDashSdk.clientsKinesisvideomediaMod.apiVersion = null,
    kms: typings.awsDashSdk.clientsKmsMod.apiVersion = null,
    lakeformation: typings.awsDashSdk.clientsLakeformationMod.apiVersion = null,
    lambda: typings.awsDashSdk.clientsLambdaMod.apiVersion = null,
    lexmodelbuildingservice: typings.awsDashSdk.clientsLexmodelbuildingserviceMod.apiVersion = null,
    lexruntime: typings.awsDashSdk.clientsLexruntimeMod.apiVersion = null,
    licensemanager: typings.awsDashSdk.clientsLicensemanagerMod.apiVersion = null,
    lightsail: typings.awsDashSdk.clientsLightsailMod.apiVersion = null,
    machinelearning: typings.awsDashSdk.clientsMachinelearningMod.apiVersion = null,
    macie: typings.awsDashSdk.clientsMacieMod.apiVersion = null,
    managedblockchain: typings.awsDashSdk.clientsManagedblockchainMod.apiVersion = null,
    marketplacecommerceanalytics: typings.awsDashSdk.clientsMarketplacecommerceanalyticsMod.apiVersion = null,
    marketplaceentitlementservice: typings.awsDashSdk.clientsMarketplaceentitlementserviceMod.apiVersion = null,
    marketplacemetering: typings.awsDashSdk.clientsMarketplacemeteringMod.apiVersion = null,
    mediaconnect: typings.awsDashSdk.clientsMediaconnectMod.apiVersion = null,
    mediaconvert: typings.awsDashSdk.clientsMediaconvertMod.apiVersion = null,
    medialive: typings.awsDashSdk.clientsMedialiveMod.apiVersion = null,
    mediapackage: typings.awsDashSdk.clientsMediapackageMod.apiVersion = null,
    mediapackagevod: typings.awsDashSdk.clientsMediapackagevodMod.apiVersion = null,
    mediastore: typings.awsDashSdk.clientsMediastoreMod.apiVersion = null,
    mediastoredata: typings.awsDashSdk.clientsMediastoredataMod.apiVersion = null,
    mediatailor: typings.awsDashSdk.clientsMediatailorMod.apiVersion = null,
    migrationhub: typings.awsDashSdk.clientsMigrationhubMod.apiVersion = null,
    mobile: typings.awsDashSdk.clientsMobileMod.apiVersion = null,
    mobileanalytics: typings.awsDashSdk.clientsMobileanalyticsMod.apiVersion = null,
    mq: typings.awsDashSdk.clientsMqMod.apiVersion = null,
    mturk: typings.awsDashSdk.clientsMturkMod.apiVersion = null,
    neptune: typings.awsDashSdk.clientsNeptuneMod.apiVersion = null,
    opsworks: typings.awsDashSdk.clientsOpsworksMod.apiVersion = null,
    opsworkscm: typings.awsDashSdk.clientsOpsworkscmMod.apiVersion = null,
    organizations: typings.awsDashSdk.clientsOrganizationsMod.apiVersion = null,
    personalize: typings.awsDashSdk.clientsPersonalizeMod.apiVersion = null,
    personalizeevents: typings.awsDashSdk.clientsPersonalizeeventsMod.apiVersion = null,
    personalizeruntime: typings.awsDashSdk.clientsPersonalizeruntimeMod.apiVersion = null,
    pi: typings.awsDashSdk.clientsPiMod.apiVersion = null,
    pinpoint: typings.awsDashSdk.clientsPinpointMod.apiVersion = null,
    pinpointemail: typings.awsDashSdk.clientsPinpointemailMod.apiVersion = null,
    pinpointsmsvoice: typings.awsDashSdk.clientsPinpointsmsvoiceMod.apiVersion = null,
    polly: typings.awsDashSdk.clientsPollyMod.apiVersion = null,
    pricing: typings.awsDashSdk.clientsPricingMod.apiVersion = null,
    qldb: typings.awsDashSdk.clientsQldbMod.apiVersion = null,
    qldbsession: typings.awsDashSdk.clientsQldbsessionMod.apiVersion = null,
    quicksight: typings.awsDashSdk.clientsQuicksightMod.apiVersion = null,
    ram: typings.awsDashSdk.clientsRamMod.apiVersion = null,
    rds: typings.awsDashSdk.clientsRdsMod.apiVersion = null,
    rdsdataservice: typings.awsDashSdk.clientsRdsdataserviceMod.apiVersion = null,
    redshift: typings.awsDashSdk.clientsRedshiftMod.apiVersion = null,
    rekognition: typings.awsDashSdk.clientsRekognitionMod.apiVersion = null,
    resourcegroups: typings.awsDashSdk.clientsResourcegroupsMod.apiVersion = null,
    resourcegroupstaggingapi: typings.awsDashSdk.clientsResourcegroupstaggingapiMod.apiVersion = null,
    robomaker: typings.awsDashSdk.clientsRobomakerMod.apiVersion = null,
    route53: typings.awsDashSdk.clientsRoute53Mod.apiVersion = null,
    route53domains: typings.awsDashSdk.clientsRoute53domainsMod.apiVersion = null,
    route53resolver: typings.awsDashSdk.clientsRoute53resolverMod.apiVersion = null,
    s3: typings.awsDashSdk.clientsS3Mod.apiVersion = null,
    s3control: typings.awsDashSdk.clientsS3controlMod.apiVersion = null,
    sagemaker: typings.awsDashSdk.clientsSagemakerMod.apiVersion = null,
    sagemakerruntime: typings.awsDashSdk.clientsSagemakerruntimeMod.apiVersion = null,
    secretsmanager: typings.awsDashSdk.clientsSecretsmanagerMod.apiVersion = null,
    securityhub: typings.awsDashSdk.clientsSecurityhubMod.apiVersion = null,
    serverlessapplicationrepository: typings.awsDashSdk.clientsServerlessapplicationrepositoryMod.apiVersion = null,
    servicecatalog: typings.awsDashSdk.clientsServicecatalogMod.apiVersion = null,
    servicediscovery: typings.awsDashSdk.clientsServicediscoveryMod.apiVersion = null,
    servicequotas: typings.awsDashSdk.clientsServicequotasMod.apiVersion = null,
    ses: typings.awsDashSdk.clientsSesMod.apiVersion = null,
    shield: typings.awsDashSdk.clientsShieldMod.apiVersion = null,
    signer: typings.awsDashSdk.clientsSignerMod.apiVersion = null,
    simpledb: typings.awsDashSdk.clientsSimpledbMod.apiVersion = null,
    sms: typings.awsDashSdk.clientsSmsMod.apiVersion = null,
    snowball: typings.awsDashSdk.clientsSnowballMod.apiVersion = null,
    sns: typings.awsDashSdk.clientsSnsMod.apiVersion = null,
    sqs: typings.awsDashSdk.clientsSqsMod.apiVersion = null,
    ssm: typings.awsDashSdk.clientsSsmMod.apiVersion = null,
    stepfunctions: typings.awsDashSdk.clientsStepfunctionsMod.apiVersion = null,
    storagegateway: typings.awsDashSdk.clientsStoragegatewayMod.apiVersion = null,
    sts: typings.awsDashSdk.clientsStsMod.apiVersion = null,
    support: typings.awsDashSdk.clientsSupportMod.apiVersion = null,
    swf: typings.awsDashSdk.clientsSwfMod.apiVersion = null,
    textract: typings.awsDashSdk.clientsTextractMod.apiVersion = null,
    transcribeservice: typings.awsDashSdk.clientsTranscribeserviceMod.apiVersion = null,
    transfer: typings.awsDashSdk.clientsTransferMod.apiVersion = null,
    translate: typings.awsDashSdk.clientsTranslateMod.apiVersion = null,
    waf: typings.awsDashSdk.clientsWafMod.apiVersion = null,
    wafregional: typings.awsDashSdk.clientsWafregionalMod.apiVersion = null,
    workdocs: typings.awsDashSdk.clientsWorkdocsMod.apiVersion = null,
    worklink: typings.awsDashSdk.clientsWorklinkMod.apiVersion = null,
    workmail: typings.awsDashSdk.clientsWorkmailMod.apiVersion = null,
    workspaces: typings.awsDashSdk.clientsWorkspacesMod.apiVersion = null,
    xray: typings.awsDashSdk.clientsXrayMod.apiVersion = null
  ): ConfigurationServiceApiVersions = {
    val __obj = js.Dynamic.literal()
    if (acm != null) __obj.updateDynamic("acm")(acm.asInstanceOf[js.Any])
    if (acmpca != null) __obj.updateDynamic("acmpca")(acmpca.asInstanceOf[js.Any])
    if (alexaforbusiness != null) __obj.updateDynamic("alexaforbusiness")(alexaforbusiness.asInstanceOf[js.Any])
    if (amplify != null) __obj.updateDynamic("amplify")(amplify.asInstanceOf[js.Any])
    if (apigateway != null) __obj.updateDynamic("apigateway")(apigateway.asInstanceOf[js.Any])
    if (apigatewaymanagementapi != null) __obj.updateDynamic("apigatewaymanagementapi")(apigatewaymanagementapi.asInstanceOf[js.Any])
    if (apigatewayv2 != null) __obj.updateDynamic("apigatewayv2")(apigatewayv2.asInstanceOf[js.Any])
    if (applicationautoscaling != null) __obj.updateDynamic("applicationautoscaling")(applicationautoscaling.asInstanceOf[js.Any])
    if (applicationinsights != null) __obj.updateDynamic("applicationinsights")(applicationinsights.asInstanceOf[js.Any])
    if (appmesh != null) __obj.updateDynamic("appmesh")(appmesh.asInstanceOf[js.Any])
    if (appstream != null) __obj.updateDynamic("appstream")(appstream.asInstanceOf[js.Any])
    if (appsync != null) __obj.updateDynamic("appsync")(appsync.asInstanceOf[js.Any])
    if (athena != null) __obj.updateDynamic("athena")(athena.asInstanceOf[js.Any])
    if (autoscaling != null) __obj.updateDynamic("autoscaling")(autoscaling.asInstanceOf[js.Any])
    if (autoscalingplans != null) __obj.updateDynamic("autoscalingplans")(autoscalingplans.asInstanceOf[js.Any])
    if (backup != null) __obj.updateDynamic("backup")(backup.asInstanceOf[js.Any])
    if (batch != null) __obj.updateDynamic("batch")(batch.asInstanceOf[js.Any])
    if (budgets != null) __obj.updateDynamic("budgets")(budgets.asInstanceOf[js.Any])
    if (chime != null) __obj.updateDynamic("chime")(chime.asInstanceOf[js.Any])
    if (cloud9 != null) __obj.updateDynamic("cloud9")(cloud9.asInstanceOf[js.Any])
    if (clouddirectory != null) __obj.updateDynamic("clouddirectory")(clouddirectory.asInstanceOf[js.Any])
    if (cloudformation != null) __obj.updateDynamic("cloudformation")(cloudformation.asInstanceOf[js.Any])
    if (cloudfront != null) __obj.updateDynamic("cloudfront")(cloudfront.asInstanceOf[js.Any])
    if (cloudhsm != null) __obj.updateDynamic("cloudhsm")(cloudhsm.asInstanceOf[js.Any])
    if (cloudhsmv2 != null) __obj.updateDynamic("cloudhsmv2")(cloudhsmv2.asInstanceOf[js.Any])
    if (cloudsearch != null) __obj.updateDynamic("cloudsearch")(cloudsearch.asInstanceOf[js.Any])
    if (cloudsearchdomain != null) __obj.updateDynamic("cloudsearchdomain")(cloudsearchdomain.asInstanceOf[js.Any])
    if (cloudtrail != null) __obj.updateDynamic("cloudtrail")(cloudtrail.asInstanceOf[js.Any])
    if (cloudwatch != null) __obj.updateDynamic("cloudwatch")(cloudwatch.asInstanceOf[js.Any])
    if (cloudwatchevents != null) __obj.updateDynamic("cloudwatchevents")(cloudwatchevents.asInstanceOf[js.Any])
    if (cloudwatchlogs != null) __obj.updateDynamic("cloudwatchlogs")(cloudwatchlogs.asInstanceOf[js.Any])
    if (codebuild != null) __obj.updateDynamic("codebuild")(codebuild.asInstanceOf[js.Any])
    if (codecommit != null) __obj.updateDynamic("codecommit")(codecommit.asInstanceOf[js.Any])
    if (codedeploy != null) __obj.updateDynamic("codedeploy")(codedeploy.asInstanceOf[js.Any])
    if (codepipeline != null) __obj.updateDynamic("codepipeline")(codepipeline.asInstanceOf[js.Any])
    if (codestar != null) __obj.updateDynamic("codestar")(codestar.asInstanceOf[js.Any])
    if (cognitoidentity != null) __obj.updateDynamic("cognitoidentity")(cognitoidentity.asInstanceOf[js.Any])
    if (cognitoidentityserviceprovider != null) __obj.updateDynamic("cognitoidentityserviceprovider")(cognitoidentityserviceprovider.asInstanceOf[js.Any])
    if (cognitosync != null) __obj.updateDynamic("cognitosync")(cognitosync.asInstanceOf[js.Any])
    if (comprehend != null) __obj.updateDynamic("comprehend")(comprehend.asInstanceOf[js.Any])
    if (comprehendmedical != null) __obj.updateDynamic("comprehendmedical")(comprehendmedical.asInstanceOf[js.Any])
    if (configservice != null) __obj.updateDynamic("configservice")(configservice.asInstanceOf[js.Any])
    if (connect != null) __obj.updateDynamic("connect")(connect.asInstanceOf[js.Any])
    if (costexplorer != null) __obj.updateDynamic("costexplorer")(costexplorer.asInstanceOf[js.Any])
    if (cur != null) __obj.updateDynamic("cur")(cur.asInstanceOf[js.Any])
    if (datapipeline != null) __obj.updateDynamic("datapipeline")(datapipeline.asInstanceOf[js.Any])
    if (datasync != null) __obj.updateDynamic("datasync")(datasync.asInstanceOf[js.Any])
    if (dax != null) __obj.updateDynamic("dax")(dax.asInstanceOf[js.Any])
    if (devicefarm != null) __obj.updateDynamic("devicefarm")(devicefarm.asInstanceOf[js.Any])
    if (directconnect != null) __obj.updateDynamic("directconnect")(directconnect.asInstanceOf[js.Any])
    if (directoryservice != null) __obj.updateDynamic("directoryservice")(directoryservice.asInstanceOf[js.Any])
    if (discovery != null) __obj.updateDynamic("discovery")(discovery.asInstanceOf[js.Any])
    if (dlm != null) __obj.updateDynamic("dlm")(dlm.asInstanceOf[js.Any])
    if (dms != null) __obj.updateDynamic("dms")(dms.asInstanceOf[js.Any])
    if (docdb != null) __obj.updateDynamic("docdb")(docdb.asInstanceOf[js.Any])
    if (dynamodb != null) __obj.updateDynamic("dynamodb")(dynamodb.asInstanceOf[js.Any])
    if (dynamodbstreams != null) __obj.updateDynamic("dynamodbstreams")(dynamodbstreams.asInstanceOf[js.Any])
    if (ec2 != null) __obj.updateDynamic("ec2")(ec2.asInstanceOf[js.Any])
    if (ec2instanceconnect != null) __obj.updateDynamic("ec2instanceconnect")(ec2instanceconnect.asInstanceOf[js.Any])
    if (ecr != null) __obj.updateDynamic("ecr")(ecr.asInstanceOf[js.Any])
    if (ecs != null) __obj.updateDynamic("ecs")(ecs.asInstanceOf[js.Any])
    if (efs != null) __obj.updateDynamic("efs")(efs.asInstanceOf[js.Any])
    if (eks != null) __obj.updateDynamic("eks")(eks.asInstanceOf[js.Any])
    if (elasticache != null) __obj.updateDynamic("elasticache")(elasticache.asInstanceOf[js.Any])
    if (elasticbeanstalk != null) __obj.updateDynamic("elasticbeanstalk")(elasticbeanstalk.asInstanceOf[js.Any])
    if (elastictranscoder != null) __obj.updateDynamic("elastictranscoder")(elastictranscoder.asInstanceOf[js.Any])
    if (elb != null) __obj.updateDynamic("elb")(elb.asInstanceOf[js.Any])
    if (elbv2 != null) __obj.updateDynamic("elbv2")(elbv2.asInstanceOf[js.Any])
    if (emr != null) __obj.updateDynamic("emr")(emr.asInstanceOf[js.Any])
    if (es != null) __obj.updateDynamic("es")(es.asInstanceOf[js.Any])
    if (eventbridge != null) __obj.updateDynamic("eventbridge")(eventbridge.asInstanceOf[js.Any])
    if (firehose != null) __obj.updateDynamic("firehose")(firehose.asInstanceOf[js.Any])
    if (fms != null) __obj.updateDynamic("fms")(fms.asInstanceOf[js.Any])
    if (forecastqueryservice != null) __obj.updateDynamic("forecastqueryservice")(forecastqueryservice.asInstanceOf[js.Any])
    if (forecastservice != null) __obj.updateDynamic("forecastservice")(forecastservice.asInstanceOf[js.Any])
    if (fsx != null) __obj.updateDynamic("fsx")(fsx.asInstanceOf[js.Any])
    if (gamelift != null) __obj.updateDynamic("gamelift")(gamelift.asInstanceOf[js.Any])
    if (glacier != null) __obj.updateDynamic("glacier")(glacier.asInstanceOf[js.Any])
    if (globalaccelerator != null) __obj.updateDynamic("globalaccelerator")(globalaccelerator.asInstanceOf[js.Any])
    if (glue != null) __obj.updateDynamic("glue")(glue.asInstanceOf[js.Any])
    if (greengrass != null) __obj.updateDynamic("greengrass")(greengrass.asInstanceOf[js.Any])
    if (groundstation != null) __obj.updateDynamic("groundstation")(groundstation.asInstanceOf[js.Any])
    if (guardduty != null) __obj.updateDynamic("guardduty")(guardduty.asInstanceOf[js.Any])
    if (health != null) __obj.updateDynamic("health")(health.asInstanceOf[js.Any])
    if (iam != null) __obj.updateDynamic("iam")(iam.asInstanceOf[js.Any])
    if (importexport != null) __obj.updateDynamic("importexport")(importexport.asInstanceOf[js.Any])
    if (inspector != null) __obj.updateDynamic("inspector")(inspector.asInstanceOf[js.Any])
    if (iot != null) __obj.updateDynamic("iot")(iot.asInstanceOf[js.Any])
    if (iot1clickdevicesservice != null) __obj.updateDynamic("iot1clickdevicesservice")(iot1clickdevicesservice.asInstanceOf[js.Any])
    if (iot1clickprojects != null) __obj.updateDynamic("iot1clickprojects")(iot1clickprojects.asInstanceOf[js.Any])
    if (iotanalytics != null) __obj.updateDynamic("iotanalytics")(iotanalytics.asInstanceOf[js.Any])
    if (iotdata != null) __obj.updateDynamic("iotdata")(iotdata.asInstanceOf[js.Any])
    if (iotevents != null) __obj.updateDynamic("iotevents")(iotevents.asInstanceOf[js.Any])
    if (ioteventsdata != null) __obj.updateDynamic("ioteventsdata")(ioteventsdata.asInstanceOf[js.Any])
    if (iotjobsdataplane != null) __obj.updateDynamic("iotjobsdataplane")(iotjobsdataplane.asInstanceOf[js.Any])
    if (iotthingsgraph != null) __obj.updateDynamic("iotthingsgraph")(iotthingsgraph.asInstanceOf[js.Any])
    if (kafka != null) __obj.updateDynamic("kafka")(kafka.asInstanceOf[js.Any])
    if (kinesis != null) __obj.updateDynamic("kinesis")(kinesis.asInstanceOf[js.Any])
    if (kinesisanalytics != null) __obj.updateDynamic("kinesisanalytics")(kinesisanalytics.asInstanceOf[js.Any])
    if (kinesisanalyticsv2 != null) __obj.updateDynamic("kinesisanalyticsv2")(kinesisanalyticsv2.asInstanceOf[js.Any])
    if (kinesisvideo != null) __obj.updateDynamic("kinesisvideo")(kinesisvideo.asInstanceOf[js.Any])
    if (kinesisvideoarchivedmedia != null) __obj.updateDynamic("kinesisvideoarchivedmedia")(kinesisvideoarchivedmedia.asInstanceOf[js.Any])
    if (kinesisvideomedia != null) __obj.updateDynamic("kinesisvideomedia")(kinesisvideomedia.asInstanceOf[js.Any])
    if (kms != null) __obj.updateDynamic("kms")(kms.asInstanceOf[js.Any])
    if (lakeformation != null) __obj.updateDynamic("lakeformation")(lakeformation.asInstanceOf[js.Any])
    if (lambda != null) __obj.updateDynamic("lambda")(lambda.asInstanceOf[js.Any])
    if (lexmodelbuildingservice != null) __obj.updateDynamic("lexmodelbuildingservice")(lexmodelbuildingservice.asInstanceOf[js.Any])
    if (lexruntime != null) __obj.updateDynamic("lexruntime")(lexruntime.asInstanceOf[js.Any])
    if (licensemanager != null) __obj.updateDynamic("licensemanager")(licensemanager.asInstanceOf[js.Any])
    if (lightsail != null) __obj.updateDynamic("lightsail")(lightsail.asInstanceOf[js.Any])
    if (machinelearning != null) __obj.updateDynamic("machinelearning")(machinelearning.asInstanceOf[js.Any])
    if (macie != null) __obj.updateDynamic("macie")(macie.asInstanceOf[js.Any])
    if (managedblockchain != null) __obj.updateDynamic("managedblockchain")(managedblockchain.asInstanceOf[js.Any])
    if (marketplacecommerceanalytics != null) __obj.updateDynamic("marketplacecommerceanalytics")(marketplacecommerceanalytics.asInstanceOf[js.Any])
    if (marketplaceentitlementservice != null) __obj.updateDynamic("marketplaceentitlementservice")(marketplaceentitlementservice.asInstanceOf[js.Any])
    if (marketplacemetering != null) __obj.updateDynamic("marketplacemetering")(marketplacemetering.asInstanceOf[js.Any])
    if (mediaconnect != null) __obj.updateDynamic("mediaconnect")(mediaconnect.asInstanceOf[js.Any])
    if (mediaconvert != null) __obj.updateDynamic("mediaconvert")(mediaconvert.asInstanceOf[js.Any])
    if (medialive != null) __obj.updateDynamic("medialive")(medialive.asInstanceOf[js.Any])
    if (mediapackage != null) __obj.updateDynamic("mediapackage")(mediapackage.asInstanceOf[js.Any])
    if (mediapackagevod != null) __obj.updateDynamic("mediapackagevod")(mediapackagevod.asInstanceOf[js.Any])
    if (mediastore != null) __obj.updateDynamic("mediastore")(mediastore.asInstanceOf[js.Any])
    if (mediastoredata != null) __obj.updateDynamic("mediastoredata")(mediastoredata.asInstanceOf[js.Any])
    if (mediatailor != null) __obj.updateDynamic("mediatailor")(mediatailor.asInstanceOf[js.Any])
    if (migrationhub != null) __obj.updateDynamic("migrationhub")(migrationhub.asInstanceOf[js.Any])
    if (mobile != null) __obj.updateDynamic("mobile")(mobile.asInstanceOf[js.Any])
    if (mobileanalytics != null) __obj.updateDynamic("mobileanalytics")(mobileanalytics.asInstanceOf[js.Any])
    if (mq != null) __obj.updateDynamic("mq")(mq.asInstanceOf[js.Any])
    if (mturk != null) __obj.updateDynamic("mturk")(mturk.asInstanceOf[js.Any])
    if (neptune != null) __obj.updateDynamic("neptune")(neptune.asInstanceOf[js.Any])
    if (opsworks != null) __obj.updateDynamic("opsworks")(opsworks.asInstanceOf[js.Any])
    if (opsworkscm != null) __obj.updateDynamic("opsworkscm")(opsworkscm.asInstanceOf[js.Any])
    if (organizations != null) __obj.updateDynamic("organizations")(organizations.asInstanceOf[js.Any])
    if (personalize != null) __obj.updateDynamic("personalize")(personalize.asInstanceOf[js.Any])
    if (personalizeevents != null) __obj.updateDynamic("personalizeevents")(personalizeevents.asInstanceOf[js.Any])
    if (personalizeruntime != null) __obj.updateDynamic("personalizeruntime")(personalizeruntime.asInstanceOf[js.Any])
    if (pi != null) __obj.updateDynamic("pi")(pi.asInstanceOf[js.Any])
    if (pinpoint != null) __obj.updateDynamic("pinpoint")(pinpoint.asInstanceOf[js.Any])
    if (pinpointemail != null) __obj.updateDynamic("pinpointemail")(pinpointemail.asInstanceOf[js.Any])
    if (pinpointsmsvoice != null) __obj.updateDynamic("pinpointsmsvoice")(pinpointsmsvoice.asInstanceOf[js.Any])
    if (polly != null) __obj.updateDynamic("polly")(polly.asInstanceOf[js.Any])
    if (pricing != null) __obj.updateDynamic("pricing")(pricing.asInstanceOf[js.Any])
    if (qldb != null) __obj.updateDynamic("qldb")(qldb.asInstanceOf[js.Any])
    if (qldbsession != null) __obj.updateDynamic("qldbsession")(qldbsession.asInstanceOf[js.Any])
    if (quicksight != null) __obj.updateDynamic("quicksight")(quicksight.asInstanceOf[js.Any])
    if (ram != null) __obj.updateDynamic("ram")(ram.asInstanceOf[js.Any])
    if (rds != null) __obj.updateDynamic("rds")(rds.asInstanceOf[js.Any])
    if (rdsdataservice != null) __obj.updateDynamic("rdsdataservice")(rdsdataservice.asInstanceOf[js.Any])
    if (redshift != null) __obj.updateDynamic("redshift")(redshift.asInstanceOf[js.Any])
    if (rekognition != null) __obj.updateDynamic("rekognition")(rekognition.asInstanceOf[js.Any])
    if (resourcegroups != null) __obj.updateDynamic("resourcegroups")(resourcegroups.asInstanceOf[js.Any])
    if (resourcegroupstaggingapi != null) __obj.updateDynamic("resourcegroupstaggingapi")(resourcegroupstaggingapi.asInstanceOf[js.Any])
    if (robomaker != null) __obj.updateDynamic("robomaker")(robomaker.asInstanceOf[js.Any])
    if (route53 != null) __obj.updateDynamic("route53")(route53.asInstanceOf[js.Any])
    if (route53domains != null) __obj.updateDynamic("route53domains")(route53domains.asInstanceOf[js.Any])
    if (route53resolver != null) __obj.updateDynamic("route53resolver")(route53resolver.asInstanceOf[js.Any])
    if (s3 != null) __obj.updateDynamic("s3")(s3.asInstanceOf[js.Any])
    if (s3control != null) __obj.updateDynamic("s3control")(s3control.asInstanceOf[js.Any])
    if (sagemaker != null) __obj.updateDynamic("sagemaker")(sagemaker.asInstanceOf[js.Any])
    if (sagemakerruntime != null) __obj.updateDynamic("sagemakerruntime")(sagemakerruntime.asInstanceOf[js.Any])
    if (secretsmanager != null) __obj.updateDynamic("secretsmanager")(secretsmanager.asInstanceOf[js.Any])
    if (securityhub != null) __obj.updateDynamic("securityhub")(securityhub.asInstanceOf[js.Any])
    if (serverlessapplicationrepository != null) __obj.updateDynamic("serverlessapplicationrepository")(serverlessapplicationrepository.asInstanceOf[js.Any])
    if (servicecatalog != null) __obj.updateDynamic("servicecatalog")(servicecatalog.asInstanceOf[js.Any])
    if (servicediscovery != null) __obj.updateDynamic("servicediscovery")(servicediscovery.asInstanceOf[js.Any])
    if (servicequotas != null) __obj.updateDynamic("servicequotas")(servicequotas.asInstanceOf[js.Any])
    if (ses != null) __obj.updateDynamic("ses")(ses.asInstanceOf[js.Any])
    if (shield != null) __obj.updateDynamic("shield")(shield.asInstanceOf[js.Any])
    if (signer != null) __obj.updateDynamic("signer")(signer.asInstanceOf[js.Any])
    if (simpledb != null) __obj.updateDynamic("simpledb")(simpledb.asInstanceOf[js.Any])
    if (sms != null) __obj.updateDynamic("sms")(sms.asInstanceOf[js.Any])
    if (snowball != null) __obj.updateDynamic("snowball")(snowball.asInstanceOf[js.Any])
    if (sns != null) __obj.updateDynamic("sns")(sns.asInstanceOf[js.Any])
    if (sqs != null) __obj.updateDynamic("sqs")(sqs.asInstanceOf[js.Any])
    if (ssm != null) __obj.updateDynamic("ssm")(ssm.asInstanceOf[js.Any])
    if (stepfunctions != null) __obj.updateDynamic("stepfunctions")(stepfunctions.asInstanceOf[js.Any])
    if (storagegateway != null) __obj.updateDynamic("storagegateway")(storagegateway.asInstanceOf[js.Any])
    if (sts != null) __obj.updateDynamic("sts")(sts.asInstanceOf[js.Any])
    if (support != null) __obj.updateDynamic("support")(support.asInstanceOf[js.Any])
    if (swf != null) __obj.updateDynamic("swf")(swf.asInstanceOf[js.Any])
    if (textract != null) __obj.updateDynamic("textract")(textract.asInstanceOf[js.Any])
    if (transcribeservice != null) __obj.updateDynamic("transcribeservice")(transcribeservice.asInstanceOf[js.Any])
    if (transfer != null) __obj.updateDynamic("transfer")(transfer.asInstanceOf[js.Any])
    if (translate != null) __obj.updateDynamic("translate")(translate.asInstanceOf[js.Any])
    if (waf != null) __obj.updateDynamic("waf")(waf.asInstanceOf[js.Any])
    if (wafregional != null) __obj.updateDynamic("wafregional")(wafregional.asInstanceOf[js.Any])
    if (workdocs != null) __obj.updateDynamic("workdocs")(workdocs.asInstanceOf[js.Any])
    if (worklink != null) __obj.updateDynamic("worklink")(worklink.asInstanceOf[js.Any])
    if (workmail != null) __obj.updateDynamic("workmail")(workmail.asInstanceOf[js.Any])
    if (workspaces != null) __obj.updateDynamic("workspaces")(workspaces.asInstanceOf[js.Any])
    if (xray != null) __obj.updateDynamic("xray")(xray.asInstanceOf[js.Any])
    __obj.asInstanceOf[ConfigurationServiceApiVersions]
  }
}

