package typings.atAwsDashSdkClientDashCodecommitDashNode.typesGetFolderExceptionsUnionMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesInvalidCommitExceptionMod.InvalidCommitException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesCommitDoesNotExistExceptionMod.CommitDoesNotExistException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesPathRequiredExceptionMod.PathRequiredException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesInvalidPathExceptionMod.InvalidPathException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesFolderDoesNotExistExceptionMod.FolderDoesNotExistException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
  - typings.atAwsDashSdkClientDashCodecommitDashNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
*/
trait GetFolderExceptionsUnion extends js.Object

