package typings
package googleDashAppsDashScriptLib.GoogleAppsScriptNs.ContentNs.SchemaNs

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait Product extends js.Object {
  var additionalImageLinks: js.UndefOr[js.Array[java.lang.String]] = js.undefined
  var additionalProductTypes: js.UndefOr[js.Array[java.lang.String]] = js.undefined
  var adult: js.UndefOr[scala.Boolean] = js.undefined
  var adwordsGrouping: js.UndefOr[java.lang.String] = js.undefined
  var adwordsLabels: js.UndefOr[js.Array[java.lang.String]] = js.undefined
  var adwordsRedirect: js.UndefOr[java.lang.String] = js.undefined
  var ageGroup: js.UndefOr[java.lang.String] = js.undefined
  var aspects: js.UndefOr[js.Array[ProductAspect]] = js.undefined
  var availability: js.UndefOr[java.lang.String] = js.undefined
  var availabilityDate: js.UndefOr[java.lang.String] = js.undefined
  var brand: js.UndefOr[java.lang.String] = js.undefined
  var channel: js.UndefOr[java.lang.String] = js.undefined
  var color: js.UndefOr[java.lang.String] = js.undefined
  var condition: js.UndefOr[java.lang.String] = js.undefined
  var contentLanguage: js.UndefOr[java.lang.String] = js.undefined
  var costOfGoodsSold: js.UndefOr[Price] = js.undefined
  var customAttributes: js.UndefOr[js.Array[CustomAttribute]] = js.undefined
  var customGroups: js.UndefOr[js.Array[CustomGroup]] = js.undefined
  var customLabel0: js.UndefOr[java.lang.String] = js.undefined
  var customLabel1: js.UndefOr[java.lang.String] = js.undefined
  var customLabel2: js.UndefOr[java.lang.String] = js.undefined
  var customLabel3: js.UndefOr[java.lang.String] = js.undefined
  var customLabel4: js.UndefOr[java.lang.String] = js.undefined
  var description: js.UndefOr[java.lang.String] = js.undefined
  var destinations: js.UndefOr[js.Array[ProductDestination]] = js.undefined
  var displayAdsId: js.UndefOr[java.lang.String] = js.undefined
  var displayAdsLink: js.UndefOr[java.lang.String] = js.undefined
  var displayAdsSimilarIds: js.UndefOr[js.Array[java.lang.String]] = js.undefined
  var displayAdsTitle: js.UndefOr[java.lang.String] = js.undefined
  var displayAdsValue: js.UndefOr[scala.Double] = js.undefined
  var energyEfficiencyClass: js.UndefOr[java.lang.String] = js.undefined
  var expirationDate: js.UndefOr[java.lang.String] = js.undefined
  var gender: js.UndefOr[java.lang.String] = js.undefined
  var googleProductCategory: js.UndefOr[java.lang.String] = js.undefined
  var gtin: js.UndefOr[java.lang.String] = js.undefined
  var id: js.UndefOr[java.lang.String] = js.undefined
  var identifierExists: js.UndefOr[scala.Boolean] = js.undefined
  var imageLink: js.UndefOr[java.lang.String] = js.undefined
  var installment: js.UndefOr[Installment] = js.undefined
  var isBundle: js.UndefOr[scala.Boolean] = js.undefined
  var itemGroupId: js.UndefOr[java.lang.String] = js.undefined
  var kind: js.UndefOr[java.lang.String] = js.undefined
  var link: js.UndefOr[java.lang.String] = js.undefined
  var loyaltyPoints: js.UndefOr[LoyaltyPoints] = js.undefined
  var material: js.UndefOr[java.lang.String] = js.undefined
  var maxEnergyEfficiencyClass: js.UndefOr[java.lang.String] = js.undefined
  var maxHandlingTime: js.UndefOr[java.lang.String] = js.undefined
  var minEnergyEfficiencyClass: js.UndefOr[java.lang.String] = js.undefined
  var minHandlingTime: js.UndefOr[java.lang.String] = js.undefined
  var mobileLink: js.UndefOr[java.lang.String] = js.undefined
  var mpn: js.UndefOr[java.lang.String] = js.undefined
  var multipack: js.UndefOr[java.lang.String] = js.undefined
  var offerId: js.UndefOr[java.lang.String] = js.undefined
  var onlineOnly: js.UndefOr[scala.Boolean] = js.undefined
  var pattern: js.UndefOr[java.lang.String] = js.undefined
  var price: js.UndefOr[Price] = js.undefined
  var productType: js.UndefOr[java.lang.String] = js.undefined
  var promotionIds: js.UndefOr[js.Array[java.lang.String]] = js.undefined
  var salePrice: js.UndefOr[Price] = js.undefined
  var salePriceEffectiveDate: js.UndefOr[java.lang.String] = js.undefined
  var sellOnGoogleQuantity: js.UndefOr[java.lang.String] = js.undefined
  var shipping: js.UndefOr[js.Array[ProductShipping]] = js.undefined
  var shippingHeight: js.UndefOr[ProductShippingDimension] = js.undefined
  var shippingLabel: js.UndefOr[java.lang.String] = js.undefined
  var shippingLength: js.UndefOr[ProductShippingDimension] = js.undefined
  var shippingWeight: js.UndefOr[ProductShippingWeight] = js.undefined
  var shippingWidth: js.UndefOr[ProductShippingDimension] = js.undefined
  var sizeSystem: js.UndefOr[java.lang.String] = js.undefined
  var sizeType: js.UndefOr[java.lang.String] = js.undefined
  var sizes: js.UndefOr[js.Array[java.lang.String]] = js.undefined
  var source: js.UndefOr[java.lang.String] = js.undefined
  var targetCountry: js.UndefOr[java.lang.String] = js.undefined
  var taxes: js.UndefOr[js.Array[ProductTax]] = js.undefined
  var title: js.UndefOr[java.lang.String] = js.undefined
  var unitPricingBaseMeasure: js.UndefOr[ProductUnitPricingBaseMeasure] = js.undefined
  var unitPricingMeasure: js.UndefOr[ProductUnitPricingMeasure] = js.undefined
  var validatedDestinations: js.UndefOr[js.Array[java.lang.String]] = js.undefined
  var warnings: js.UndefOr[js.Array[Error]] = js.undefined
}

object Product {
  @scala.inline
  def apply(
    additionalImageLinks: js.Array[java.lang.String] = null,
    additionalProductTypes: js.Array[java.lang.String] = null,
    adult: js.UndefOr[scala.Boolean] = js.undefined,
    adwordsGrouping: java.lang.String = null,
    adwordsLabels: js.Array[java.lang.String] = null,
    adwordsRedirect: java.lang.String = null,
    ageGroup: java.lang.String = null,
    aspects: js.Array[ProductAspect] = null,
    availability: java.lang.String = null,
    availabilityDate: java.lang.String = null,
    brand: java.lang.String = null,
    channel: java.lang.String = null,
    color: java.lang.String = null,
    condition: java.lang.String = null,
    contentLanguage: java.lang.String = null,
    costOfGoodsSold: Price = null,
    customAttributes: js.Array[CustomAttribute] = null,
    customGroups: js.Array[CustomGroup] = null,
    customLabel0: java.lang.String = null,
    customLabel1: java.lang.String = null,
    customLabel2: java.lang.String = null,
    customLabel3: java.lang.String = null,
    customLabel4: java.lang.String = null,
    description: java.lang.String = null,
    destinations: js.Array[ProductDestination] = null,
    displayAdsId: java.lang.String = null,
    displayAdsLink: java.lang.String = null,
    displayAdsSimilarIds: js.Array[java.lang.String] = null,
    displayAdsTitle: java.lang.String = null,
    displayAdsValue: scala.Int | scala.Double = null,
    energyEfficiencyClass: java.lang.String = null,
    expirationDate: java.lang.String = null,
    gender: java.lang.String = null,
    googleProductCategory: java.lang.String = null,
    gtin: java.lang.String = null,
    id: java.lang.String = null,
    identifierExists: js.UndefOr[scala.Boolean] = js.undefined,
    imageLink: java.lang.String = null,
    installment: Installment = null,
    isBundle: js.UndefOr[scala.Boolean] = js.undefined,
    itemGroupId: java.lang.String = null,
    kind: java.lang.String = null,
    link: java.lang.String = null,
    loyaltyPoints: LoyaltyPoints = null,
    material: java.lang.String = null,
    maxEnergyEfficiencyClass: java.lang.String = null,
    maxHandlingTime: java.lang.String = null,
    minEnergyEfficiencyClass: java.lang.String = null,
    minHandlingTime: java.lang.String = null,
    mobileLink: java.lang.String = null,
    mpn: java.lang.String = null,
    multipack: java.lang.String = null,
    offerId: java.lang.String = null,
    onlineOnly: js.UndefOr[scala.Boolean] = js.undefined,
    pattern: java.lang.String = null,
    price: Price = null,
    productType: java.lang.String = null,
    promotionIds: js.Array[java.lang.String] = null,
    salePrice: Price = null,
    salePriceEffectiveDate: java.lang.String = null,
    sellOnGoogleQuantity: java.lang.String = null,
    shipping: js.Array[ProductShipping] = null,
    shippingHeight: ProductShippingDimension = null,
    shippingLabel: java.lang.String = null,
    shippingLength: ProductShippingDimension = null,
    shippingWeight: ProductShippingWeight = null,
    shippingWidth: ProductShippingDimension = null,
    sizeSystem: java.lang.String = null,
    sizeType: java.lang.String = null,
    sizes: js.Array[java.lang.String] = null,
    source: java.lang.String = null,
    targetCountry: java.lang.String = null,
    taxes: js.Array[ProductTax] = null,
    title: java.lang.String = null,
    unitPricingBaseMeasure: ProductUnitPricingBaseMeasure = null,
    unitPricingMeasure: ProductUnitPricingMeasure = null,
    validatedDestinations: js.Array[java.lang.String] = null,
    warnings: js.Array[Error] = null
  ): Product = {
    val __obj = js.Dynamic.literal()
    if (additionalImageLinks != null) __obj.updateDynamic("additionalImageLinks")(additionalImageLinks)
    if (additionalProductTypes != null) __obj.updateDynamic("additionalProductTypes")(additionalProductTypes)
    if (!js.isUndefined(adult)) __obj.updateDynamic("adult")(adult)
    if (adwordsGrouping != null) __obj.updateDynamic("adwordsGrouping")(adwordsGrouping)
    if (adwordsLabels != null) __obj.updateDynamic("adwordsLabels")(adwordsLabels)
    if (adwordsRedirect != null) __obj.updateDynamic("adwordsRedirect")(adwordsRedirect)
    if (ageGroup != null) __obj.updateDynamic("ageGroup")(ageGroup)
    if (aspects != null) __obj.updateDynamic("aspects")(aspects)
    if (availability != null) __obj.updateDynamic("availability")(availability)
    if (availabilityDate != null) __obj.updateDynamic("availabilityDate")(availabilityDate)
    if (brand != null) __obj.updateDynamic("brand")(brand)
    if (channel != null) __obj.updateDynamic("channel")(channel)
    if (color != null) __obj.updateDynamic("color")(color)
    if (condition != null) __obj.updateDynamic("condition")(condition)
    if (contentLanguage != null) __obj.updateDynamic("contentLanguage")(contentLanguage)
    if (costOfGoodsSold != null) __obj.updateDynamic("costOfGoodsSold")(costOfGoodsSold)
    if (customAttributes != null) __obj.updateDynamic("customAttributes")(customAttributes)
    if (customGroups != null) __obj.updateDynamic("customGroups")(customGroups)
    if (customLabel0 != null) __obj.updateDynamic("customLabel0")(customLabel0)
    if (customLabel1 != null) __obj.updateDynamic("customLabel1")(customLabel1)
    if (customLabel2 != null) __obj.updateDynamic("customLabel2")(customLabel2)
    if (customLabel3 != null) __obj.updateDynamic("customLabel3")(customLabel3)
    if (customLabel4 != null) __obj.updateDynamic("customLabel4")(customLabel4)
    if (description != null) __obj.updateDynamic("description")(description)
    if (destinations != null) __obj.updateDynamic("destinations")(destinations)
    if (displayAdsId != null) __obj.updateDynamic("displayAdsId")(displayAdsId)
    if (displayAdsLink != null) __obj.updateDynamic("displayAdsLink")(displayAdsLink)
    if (displayAdsSimilarIds != null) __obj.updateDynamic("displayAdsSimilarIds")(displayAdsSimilarIds)
    if (displayAdsTitle != null) __obj.updateDynamic("displayAdsTitle")(displayAdsTitle)
    if (displayAdsValue != null) __obj.updateDynamic("displayAdsValue")(displayAdsValue.asInstanceOf[js.Any])
    if (energyEfficiencyClass != null) __obj.updateDynamic("energyEfficiencyClass")(energyEfficiencyClass)
    if (expirationDate != null) __obj.updateDynamic("expirationDate")(expirationDate)
    if (gender != null) __obj.updateDynamic("gender")(gender)
    if (googleProductCategory != null) __obj.updateDynamic("googleProductCategory")(googleProductCategory)
    if (gtin != null) __obj.updateDynamic("gtin")(gtin)
    if (id != null) __obj.updateDynamic("id")(id)
    if (!js.isUndefined(identifierExists)) __obj.updateDynamic("identifierExists")(identifierExists)
    if (imageLink != null) __obj.updateDynamic("imageLink")(imageLink)
    if (installment != null) __obj.updateDynamic("installment")(installment)
    if (!js.isUndefined(isBundle)) __obj.updateDynamic("isBundle")(isBundle)
    if (itemGroupId != null) __obj.updateDynamic("itemGroupId")(itemGroupId)
    if (kind != null) __obj.updateDynamic("kind")(kind)
    if (link != null) __obj.updateDynamic("link")(link)
    if (loyaltyPoints != null) __obj.updateDynamic("loyaltyPoints")(loyaltyPoints)
    if (material != null) __obj.updateDynamic("material")(material)
    if (maxEnergyEfficiencyClass != null) __obj.updateDynamic("maxEnergyEfficiencyClass")(maxEnergyEfficiencyClass)
    if (maxHandlingTime != null) __obj.updateDynamic("maxHandlingTime")(maxHandlingTime)
    if (minEnergyEfficiencyClass != null) __obj.updateDynamic("minEnergyEfficiencyClass")(minEnergyEfficiencyClass)
    if (minHandlingTime != null) __obj.updateDynamic("minHandlingTime")(minHandlingTime)
    if (mobileLink != null) __obj.updateDynamic("mobileLink")(mobileLink)
    if (mpn != null) __obj.updateDynamic("mpn")(mpn)
    if (multipack != null) __obj.updateDynamic("multipack")(multipack)
    if (offerId != null) __obj.updateDynamic("offerId")(offerId)
    if (!js.isUndefined(onlineOnly)) __obj.updateDynamic("onlineOnly")(onlineOnly)
    if (pattern != null) __obj.updateDynamic("pattern")(pattern)
    if (price != null) __obj.updateDynamic("price")(price)
    if (productType != null) __obj.updateDynamic("productType")(productType)
    if (promotionIds != null) __obj.updateDynamic("promotionIds")(promotionIds)
    if (salePrice != null) __obj.updateDynamic("salePrice")(salePrice)
    if (salePriceEffectiveDate != null) __obj.updateDynamic("salePriceEffectiveDate")(salePriceEffectiveDate)
    if (sellOnGoogleQuantity != null) __obj.updateDynamic("sellOnGoogleQuantity")(sellOnGoogleQuantity)
    if (shipping != null) __obj.updateDynamic("shipping")(shipping)
    if (shippingHeight != null) __obj.updateDynamic("shippingHeight")(shippingHeight)
    if (shippingLabel != null) __obj.updateDynamic("shippingLabel")(shippingLabel)
    if (shippingLength != null) __obj.updateDynamic("shippingLength")(shippingLength)
    if (shippingWeight != null) __obj.updateDynamic("shippingWeight")(shippingWeight)
    if (shippingWidth != null) __obj.updateDynamic("shippingWidth")(shippingWidth)
    if (sizeSystem != null) __obj.updateDynamic("sizeSystem")(sizeSystem)
    if (sizeType != null) __obj.updateDynamic("sizeType")(sizeType)
    if (sizes != null) __obj.updateDynamic("sizes")(sizes)
    if (source != null) __obj.updateDynamic("source")(source)
    if (targetCountry != null) __obj.updateDynamic("targetCountry")(targetCountry)
    if (taxes != null) __obj.updateDynamic("taxes")(taxes)
    if (title != null) __obj.updateDynamic("title")(title)
    if (unitPricingBaseMeasure != null) __obj.updateDynamic("unitPricingBaseMeasure")(unitPricingBaseMeasure)
    if (unitPricingMeasure != null) __obj.updateDynamic("unitPricingMeasure")(unitPricingMeasure)
    if (validatedDestinations != null) __obj.updateDynamic("validatedDestinations")(validatedDestinations)
    if (warnings != null) __obj.updateDynamic("warnings")(warnings)
    __obj.asInstanceOf[Product]
  }
}

