package typings.googleDashAppsDashScript.GoogleAppsScriptNs.AdminGroupsSettingsNs.SchemaNs

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait Groups extends js.Object {
  var allowExternalMembers: js.UndefOr[String] = js.undefined
  var allowGoogleCommunication: js.UndefOr[String] = js.undefined
  var allowWebPosting: js.UndefOr[String] = js.undefined
  var archiveOnly: js.UndefOr[String] = js.undefined
  var customFooterText: js.UndefOr[String] = js.undefined
  var customReplyTo: js.UndefOr[String] = js.undefined
  var customRolesEnabledForSettingsToBeMerged: js.UndefOr[String] = js.undefined
  var defaultMessageDenyNotificationText: js.UndefOr[String] = js.undefined
  var description: js.UndefOr[String] = js.undefined
  var email: js.UndefOr[String] = js.undefined
  var enableCollaborativeInbox: js.UndefOr[String] = js.undefined
  var favoriteRepliesOnTop: js.UndefOr[String] = js.undefined
  var includeCustomFooter: js.UndefOr[String] = js.undefined
  var includeInGlobalAddressList: js.UndefOr[String] = js.undefined
  var isArchived: js.UndefOr[String] = js.undefined
  var kind: js.UndefOr[String] = js.undefined
  var maxMessageBytes: js.UndefOr[Double] = js.undefined
  var membersCanPostAsTheGroup: js.UndefOr[String] = js.undefined
  var messageDisplayFont: js.UndefOr[String] = js.undefined
  var messageModerationLevel: js.UndefOr[String] = js.undefined
  var name: js.UndefOr[String] = js.undefined
  var primaryLanguage: js.UndefOr[String] = js.undefined
  var replyTo: js.UndefOr[String] = js.undefined
  var sendMessageDenyNotification: js.UndefOr[String] = js.undefined
  var showInGroupDirectory: js.UndefOr[String] = js.undefined
  var spamModerationLevel: js.UndefOr[String] = js.undefined
  var whoCanAdd: js.UndefOr[String] = js.undefined
  var whoCanAddReferences: js.UndefOr[String] = js.undefined
  var whoCanApproveMembers: js.UndefOr[String] = js.undefined
  var whoCanApproveMessages: js.UndefOr[String] = js.undefined
  var whoCanAssignTopics: js.UndefOr[String] = js.undefined
  var whoCanAssistContent: js.UndefOr[String] = js.undefined
  var whoCanBanUsers: js.UndefOr[String] = js.undefined
  var whoCanContactOwner: js.UndefOr[String] = js.undefined
  var whoCanDeleteAnyPost: js.UndefOr[String] = js.undefined
  var whoCanDeleteTopics: js.UndefOr[String] = js.undefined
  var whoCanDiscoverGroup: js.UndefOr[String] = js.undefined
  var whoCanEnterFreeFormTags: js.UndefOr[String] = js.undefined
  var whoCanHideAbuse: js.UndefOr[String] = js.undefined
  var whoCanInvite: js.UndefOr[String] = js.undefined
  var whoCanJoin: js.UndefOr[String] = js.undefined
  var whoCanLeaveGroup: js.UndefOr[String] = js.undefined
  var whoCanLockTopics: js.UndefOr[String] = js.undefined
  var whoCanMakeTopicsSticky: js.UndefOr[String] = js.undefined
  var whoCanMarkDuplicate: js.UndefOr[String] = js.undefined
  var whoCanMarkFavoriteReplyOnAnyTopic: js.UndefOr[String] = js.undefined
  var whoCanMarkFavoriteReplyOnOwnTopic: js.UndefOr[String] = js.undefined
  var whoCanMarkNoResponseNeeded: js.UndefOr[String] = js.undefined
  var whoCanModerateContent: js.UndefOr[String] = js.undefined
  var whoCanModerateMembers: js.UndefOr[String] = js.undefined
  var whoCanModifyMembers: js.UndefOr[String] = js.undefined
  var whoCanModifyTagsAndCategories: js.UndefOr[String] = js.undefined
  var whoCanMoveTopicsIn: js.UndefOr[String] = js.undefined
  var whoCanMoveTopicsOut: js.UndefOr[String] = js.undefined
  var whoCanPostAnnouncements: js.UndefOr[String] = js.undefined
  var whoCanPostMessage: js.UndefOr[String] = js.undefined
  var whoCanTakeTopics: js.UndefOr[String] = js.undefined
  var whoCanUnassignTopic: js.UndefOr[String] = js.undefined
  var whoCanUnmarkFavoriteReplyOnAnyTopic: js.UndefOr[String] = js.undefined
  var whoCanViewGroup: js.UndefOr[String] = js.undefined
  var whoCanViewMembership: js.UndefOr[String] = js.undefined
}

object Groups {
  @scala.inline
  def apply(
    allowExternalMembers: String = null,
    allowGoogleCommunication: String = null,
    allowWebPosting: String = null,
    archiveOnly: String = null,
    customFooterText: String = null,
    customReplyTo: String = null,
    customRolesEnabledForSettingsToBeMerged: String = null,
    defaultMessageDenyNotificationText: String = null,
    description: String = null,
    email: String = null,
    enableCollaborativeInbox: String = null,
    favoriteRepliesOnTop: String = null,
    includeCustomFooter: String = null,
    includeInGlobalAddressList: String = null,
    isArchived: String = null,
    kind: String = null,
    maxMessageBytes: Int | Double = null,
    membersCanPostAsTheGroup: String = null,
    messageDisplayFont: String = null,
    messageModerationLevel: String = null,
    name: String = null,
    primaryLanguage: String = null,
    replyTo: String = null,
    sendMessageDenyNotification: String = null,
    showInGroupDirectory: String = null,
    spamModerationLevel: String = null,
    whoCanAdd: String = null,
    whoCanAddReferences: String = null,
    whoCanApproveMembers: String = null,
    whoCanApproveMessages: String = null,
    whoCanAssignTopics: String = null,
    whoCanAssistContent: String = null,
    whoCanBanUsers: String = null,
    whoCanContactOwner: String = null,
    whoCanDeleteAnyPost: String = null,
    whoCanDeleteTopics: String = null,
    whoCanDiscoverGroup: String = null,
    whoCanEnterFreeFormTags: String = null,
    whoCanHideAbuse: String = null,
    whoCanInvite: String = null,
    whoCanJoin: String = null,
    whoCanLeaveGroup: String = null,
    whoCanLockTopics: String = null,
    whoCanMakeTopicsSticky: String = null,
    whoCanMarkDuplicate: String = null,
    whoCanMarkFavoriteReplyOnAnyTopic: String = null,
    whoCanMarkFavoriteReplyOnOwnTopic: String = null,
    whoCanMarkNoResponseNeeded: String = null,
    whoCanModerateContent: String = null,
    whoCanModerateMembers: String = null,
    whoCanModifyMembers: String = null,
    whoCanModifyTagsAndCategories: String = null,
    whoCanMoveTopicsIn: String = null,
    whoCanMoveTopicsOut: String = null,
    whoCanPostAnnouncements: String = null,
    whoCanPostMessage: String = null,
    whoCanTakeTopics: String = null,
    whoCanUnassignTopic: String = null,
    whoCanUnmarkFavoriteReplyOnAnyTopic: String = null,
    whoCanViewGroup: String = null,
    whoCanViewMembership: String = null
  ): Groups = {
    val __obj = js.Dynamic.literal()
    if (allowExternalMembers != null) __obj.updateDynamic("allowExternalMembers")(allowExternalMembers)
    if (allowGoogleCommunication != null) __obj.updateDynamic("allowGoogleCommunication")(allowGoogleCommunication)
    if (allowWebPosting != null) __obj.updateDynamic("allowWebPosting")(allowWebPosting)
    if (archiveOnly != null) __obj.updateDynamic("archiveOnly")(archiveOnly)
    if (customFooterText != null) __obj.updateDynamic("customFooterText")(customFooterText)
    if (customReplyTo != null) __obj.updateDynamic("customReplyTo")(customReplyTo)
    if (customRolesEnabledForSettingsToBeMerged != null) __obj.updateDynamic("customRolesEnabledForSettingsToBeMerged")(customRolesEnabledForSettingsToBeMerged)
    if (defaultMessageDenyNotificationText != null) __obj.updateDynamic("defaultMessageDenyNotificationText")(defaultMessageDenyNotificationText)
    if (description != null) __obj.updateDynamic("description")(description)
    if (email != null) __obj.updateDynamic("email")(email)
    if (enableCollaborativeInbox != null) __obj.updateDynamic("enableCollaborativeInbox")(enableCollaborativeInbox)
    if (favoriteRepliesOnTop != null) __obj.updateDynamic("favoriteRepliesOnTop")(favoriteRepliesOnTop)
    if (includeCustomFooter != null) __obj.updateDynamic("includeCustomFooter")(includeCustomFooter)
    if (includeInGlobalAddressList != null) __obj.updateDynamic("includeInGlobalAddressList")(includeInGlobalAddressList)
    if (isArchived != null) __obj.updateDynamic("isArchived")(isArchived)
    if (kind != null) __obj.updateDynamic("kind")(kind)
    if (maxMessageBytes != null) __obj.updateDynamic("maxMessageBytes")(maxMessageBytes.asInstanceOf[js.Any])
    if (membersCanPostAsTheGroup != null) __obj.updateDynamic("membersCanPostAsTheGroup")(membersCanPostAsTheGroup)
    if (messageDisplayFont != null) __obj.updateDynamic("messageDisplayFont")(messageDisplayFont)
    if (messageModerationLevel != null) __obj.updateDynamic("messageModerationLevel")(messageModerationLevel)
    if (name != null) __obj.updateDynamic("name")(name)
    if (primaryLanguage != null) __obj.updateDynamic("primaryLanguage")(primaryLanguage)
    if (replyTo != null) __obj.updateDynamic("replyTo")(replyTo)
    if (sendMessageDenyNotification != null) __obj.updateDynamic("sendMessageDenyNotification")(sendMessageDenyNotification)
    if (showInGroupDirectory != null) __obj.updateDynamic("showInGroupDirectory")(showInGroupDirectory)
    if (spamModerationLevel != null) __obj.updateDynamic("spamModerationLevel")(spamModerationLevel)
    if (whoCanAdd != null) __obj.updateDynamic("whoCanAdd")(whoCanAdd)
    if (whoCanAddReferences != null) __obj.updateDynamic("whoCanAddReferences")(whoCanAddReferences)
    if (whoCanApproveMembers != null) __obj.updateDynamic("whoCanApproveMembers")(whoCanApproveMembers)
    if (whoCanApproveMessages != null) __obj.updateDynamic("whoCanApproveMessages")(whoCanApproveMessages)
    if (whoCanAssignTopics != null) __obj.updateDynamic("whoCanAssignTopics")(whoCanAssignTopics)
    if (whoCanAssistContent != null) __obj.updateDynamic("whoCanAssistContent")(whoCanAssistContent)
    if (whoCanBanUsers != null) __obj.updateDynamic("whoCanBanUsers")(whoCanBanUsers)
    if (whoCanContactOwner != null) __obj.updateDynamic("whoCanContactOwner")(whoCanContactOwner)
    if (whoCanDeleteAnyPost != null) __obj.updateDynamic("whoCanDeleteAnyPost")(whoCanDeleteAnyPost)
    if (whoCanDeleteTopics != null) __obj.updateDynamic("whoCanDeleteTopics")(whoCanDeleteTopics)
    if (whoCanDiscoverGroup != null) __obj.updateDynamic("whoCanDiscoverGroup")(whoCanDiscoverGroup)
    if (whoCanEnterFreeFormTags != null) __obj.updateDynamic("whoCanEnterFreeFormTags")(whoCanEnterFreeFormTags)
    if (whoCanHideAbuse != null) __obj.updateDynamic("whoCanHideAbuse")(whoCanHideAbuse)
    if (whoCanInvite != null) __obj.updateDynamic("whoCanInvite")(whoCanInvite)
    if (whoCanJoin != null) __obj.updateDynamic("whoCanJoin")(whoCanJoin)
    if (whoCanLeaveGroup != null) __obj.updateDynamic("whoCanLeaveGroup")(whoCanLeaveGroup)
    if (whoCanLockTopics != null) __obj.updateDynamic("whoCanLockTopics")(whoCanLockTopics)
    if (whoCanMakeTopicsSticky != null) __obj.updateDynamic("whoCanMakeTopicsSticky")(whoCanMakeTopicsSticky)
    if (whoCanMarkDuplicate != null) __obj.updateDynamic("whoCanMarkDuplicate")(whoCanMarkDuplicate)
    if (whoCanMarkFavoriteReplyOnAnyTopic != null) __obj.updateDynamic("whoCanMarkFavoriteReplyOnAnyTopic")(whoCanMarkFavoriteReplyOnAnyTopic)
    if (whoCanMarkFavoriteReplyOnOwnTopic != null) __obj.updateDynamic("whoCanMarkFavoriteReplyOnOwnTopic")(whoCanMarkFavoriteReplyOnOwnTopic)
    if (whoCanMarkNoResponseNeeded != null) __obj.updateDynamic("whoCanMarkNoResponseNeeded")(whoCanMarkNoResponseNeeded)
    if (whoCanModerateContent != null) __obj.updateDynamic("whoCanModerateContent")(whoCanModerateContent)
    if (whoCanModerateMembers != null) __obj.updateDynamic("whoCanModerateMembers")(whoCanModerateMembers)
    if (whoCanModifyMembers != null) __obj.updateDynamic("whoCanModifyMembers")(whoCanModifyMembers)
    if (whoCanModifyTagsAndCategories != null) __obj.updateDynamic("whoCanModifyTagsAndCategories")(whoCanModifyTagsAndCategories)
    if (whoCanMoveTopicsIn != null) __obj.updateDynamic("whoCanMoveTopicsIn")(whoCanMoveTopicsIn)
    if (whoCanMoveTopicsOut != null) __obj.updateDynamic("whoCanMoveTopicsOut")(whoCanMoveTopicsOut)
    if (whoCanPostAnnouncements != null) __obj.updateDynamic("whoCanPostAnnouncements")(whoCanPostAnnouncements)
    if (whoCanPostMessage != null) __obj.updateDynamic("whoCanPostMessage")(whoCanPostMessage)
    if (whoCanTakeTopics != null) __obj.updateDynamic("whoCanTakeTopics")(whoCanTakeTopics)
    if (whoCanUnassignTopic != null) __obj.updateDynamic("whoCanUnassignTopic")(whoCanUnassignTopic)
    if (whoCanUnmarkFavoriteReplyOnAnyTopic != null) __obj.updateDynamic("whoCanUnmarkFavoriteReplyOnAnyTopic")(whoCanUnmarkFavoriteReplyOnAnyTopic)
    if (whoCanViewGroup != null) __obj.updateDynamic("whoCanViewGroup")(whoCanViewGroup)
    if (whoCanViewMembership != null) __obj.updateDynamic("whoCanViewMembership")(whoCanViewMembership)
    __obj.asInstanceOf[Groups]
  }
}

