package typings
package reactDashNativeDashLinearDashGradientLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait reactDashNativeDashLinearDashGradientLibProps {
  @scala.inline
  def LinearGradientProps: reactDashNativeDashLinearDashGradientLib.reactDashNativeDashLinearDashGradientMod.LinearGradientProps.type = reactDashNativeDashLinearDashGradientLib.reactDashNativeDashLinearDashGradientMod.LinearGradientProps
  type LinearGradientProps = reactDashNativeDashLinearDashGradientLib.reactDashNativeDashLinearDashGradientMod.LinearGradientProps
  @scala.inline
  def ReactDashNativeDashLinearDashGradientProps: reactDashNativeDashLinearDashGradientLib.reactDashNativeDashLinearDashGradientMod.LinearGradientProps.type = reactDashNativeDashLinearDashGradientLib.reactDashNativeDashLinearDashGradientMod.LinearGradientProps
  type ReactDashNativeDashLinearDashGradientProps = reactDashNativeDashLinearDashGradientLib.reactDashNativeDashLinearDashGradientMod.LinearGradientProps
}

