package typings
package officeDashUiDashFabricDashReactLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object libCommonDirectionalHintMod {
  type DirectionalHint = officeDashUiDashFabricDashReactLib.officeDashUiDashFabricDashReactLibNumbers.`0` | officeDashUiDashFabricDashReactLib.officeDashUiDashFabricDashReactLibNumbers.`1` | officeDashUiDashFabricDashReactLib.officeDashUiDashFabricDashReactLibNumbers.`2` | officeDashUiDashFabricDashReactLib.officeDashUiDashFabricDashReactLibNumbers.`3` | officeDashUiDashFabricDashReactLib.officeDashUiDashFabricDashReactLibNumbers.`4` | officeDashUiDashFabricDashReactLib.officeDashUiDashFabricDashReactLibNumbers.`5` | officeDashUiDashFabricDashReactLib.officeDashUiDashFabricDashReactLibNumbers.`6` | officeDashUiDashFabricDashReactLib.officeDashUiDashFabricDashReactLibNumbers.`7` | officeDashUiDashFabricDashReactLib.officeDashUiDashFabricDashReactLibNumbers.`8` | officeDashUiDashFabricDashReactLib.officeDashUiDashFabricDashReactLibNumbers.`9` | officeDashUiDashFabricDashReactLib.officeDashUiDashFabricDashReactLibNumbers.`10` | officeDashUiDashFabricDashReactLib.officeDashUiDashFabricDashReactLibNumbers.`11` | officeDashUiDashFabricDashReactLib.officeDashUiDashFabricDashReactLibNumbers.`12` | officeDashUiDashFabricDashReactLib.officeDashUiDashFabricDashReactLibNumbers.`13`
}
