package typings
package iframeDashResizerLib.iframeDashResizerMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object iframeResizerNs {
  type HeightCalculationMethod = iframeDashResizerLib.iframeDashResizerLibStrings.bodyOffset | iframeDashResizerLib.iframeDashResizerLibStrings.bodyScroll | iframeDashResizerLib.iframeDashResizerLibStrings.documentElementOffset | iframeDashResizerLib.iframeDashResizerLibStrings.documentElementScroll | iframeDashResizerLib.iframeDashResizerLibStrings.max | iframeDashResizerLib.iframeDashResizerLibStrings.min | iframeDashResizerLib.iframeDashResizerLibStrings.grow | iframeDashResizerLib.iframeDashResizerLibStrings.lowestElement | iframeDashResizerLib.iframeDashResizerLibStrings.taggedElement
  type WidthCalculationMethod = iframeDashResizerLib.iframeDashResizerLibStrings.bodyOffset | iframeDashResizerLib.iframeDashResizerLibStrings.bodyScroll | iframeDashResizerLib.iframeDashResizerLibStrings.documentElementOffset | iframeDashResizerLib.iframeDashResizerLibStrings.documentElementScroll | iframeDashResizerLib.iframeDashResizerLibStrings.max | iframeDashResizerLib.iframeDashResizerLibStrings.min | iframeDashResizerLib.iframeDashResizerLibStrings.scroll | iframeDashResizerLib.iframeDashResizerLibStrings.rightMostElement | iframeDashResizerLib.iframeDashResizerLibStrings.taggedElement
}
