package typings
package reactDashNativeDashPopupDashDialogLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object reactDashNativeDashPopupDashDialogMod {
  type AlignTypes = reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogLibStrings.left | reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogLibStrings.right | reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogLibStrings.center
  type OverlayPointerEventTypes = reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogLibStrings.auto | reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogLibStrings.none
  type SlideFromTypes = reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogLibStrings.top | reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogLibStrings.bottom | reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogLibStrings.left | reactDashNativeDashPopupDashDialogLib.reactDashNativeDashPopupDashDialogLibStrings.right
}
