package typings.atAwsDashSdkClientDashSqsDashNode.typesOutputTypesUnionMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typings.atAwsDashSdkClientDashSqsDashNode.typesAddPermissionOutputMod.AddPermissionOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesChangeMessageVisibilityOutputMod.ChangeMessageVisibilityOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesChangeMessageVisibilityBatchOutputMod.ChangeMessageVisibilityBatchOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesCreateQueueOutputMod.CreateQueueOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesDeleteMessageOutputMod.DeleteMessageOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesDeleteMessageBatchOutputMod.DeleteMessageBatchOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesDeleteQueueOutputMod.DeleteQueueOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesGetQueueAttributesOutputMod.GetQueueAttributesOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesGetQueueUrlOutputMod.GetQueueUrlOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesListDeadLetterSourceQueuesOutputMod.ListDeadLetterSourceQueuesOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesListQueueTagsOutputMod.ListQueueTagsOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesListQueuesOutputMod.ListQueuesOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesPurgeQueueOutputMod.PurgeQueueOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesReceiveMessageOutputMod.ReceiveMessageOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesRemovePermissionOutputMod.RemovePermissionOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesSendMessageOutputMod.SendMessageOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesSendMessageBatchOutputMod.SendMessageBatchOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesSetQueueAttributesOutputMod.SetQueueAttributesOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesTagQueueOutputMod.TagQueueOutput
  - typings.atAwsDashSdkClientDashSqsDashNode.typesUntagQueueOutputMod.UntagQueueOutput
*/
trait OutputTypesUnion extends js.Object

