package typings
package activexDashOutlookLib.OutlookNs

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSGlobal("Outlook.ContactItem")
@js.native
class ContactItem protected () extends js.Object {
  var Account: java.lang.String = js.native
  val Actions: Actions = js.native
  var Anniversary: activexDashInteropLib.VarDate = js.native
  val Application: Application = js.native
  var AssistantName: java.lang.String = js.native
  var AssistantTelephoneNumber: java.lang.String = js.native
  val Attachments: Attachments = js.native
  val AutoResolvedWinner: scala.Boolean = js.native
  var BillingInformation: java.lang.String = js.native
  var Birthday: activexDashInteropLib.VarDate = js.native
  var Body: java.lang.String = js.native
  var Business2TelephoneNumber: java.lang.String = js.native
  var BusinessAddress: java.lang.String = js.native
  var BusinessAddressCity: java.lang.String = js.native
  var BusinessAddressCountry: java.lang.String = js.native
  var BusinessAddressPostOfficeBox: java.lang.String = js.native
  var BusinessAddressPostalCode: java.lang.String = js.native
  var BusinessAddressState: java.lang.String = js.native
  var BusinessAddressStreet: java.lang.String = js.native
  var BusinessCardLayoutXml: java.lang.String = js.native
  val BusinessCardType: OlBusinessCardType = js.native
  var BusinessFaxNumber: java.lang.String = js.native
  var BusinessHomePage: java.lang.String = js.native
  var BusinessTelephoneNumber: java.lang.String = js.native
  var CallbackTelephoneNumber: java.lang.String = js.native
  var CarTelephoneNumber: java.lang.String = js.native
  var Categories: java.lang.String = js.native
  var Children: java.lang.String = js.native
  val Class: OlObjectClass = js.native
  var Companies: java.lang.String = js.native
  val CompanyAndFullName: java.lang.String = js.native
  val CompanyLastFirstNoSpace: java.lang.String = js.native
  val CompanyLastFirstSpaceOnly: java.lang.String = js.native
  var CompanyMainTelephoneNumber: java.lang.String = js.native
  var CompanyName: java.lang.String = js.native
  var ComputerNetworkName: java.lang.String = js.native
  val Conflicts: Conflicts = js.native
  val ConversationID: java.lang.String = js.native
  val ConversationIndex: java.lang.String = js.native
  val ConversationTopic: java.lang.String = js.native
  val CreationTime: activexDashInteropLib.VarDate = js.native
  var CustomerID: java.lang.String = js.native
  var Department: java.lang.String = js.native
  val DownloadState: OlDownloadState = js.native
  var Email1Address: java.lang.String = js.native
  var Email1AddressType: java.lang.String = js.native
  var Email1DisplayName: java.lang.String = js.native
  val Email1EntryID: java.lang.String = js.native
  var Email2Address: java.lang.String = js.native
  var Email2AddressType: java.lang.String = js.native
  var Email2DisplayName: java.lang.String = js.native
  val Email2EntryID: java.lang.String = js.native
  var Email3Address: java.lang.String = js.native
  var Email3AddressType: java.lang.String = js.native
  var Email3DisplayName: java.lang.String = js.native
  val Email3EntryID: java.lang.String = js.native
  val EntryID: java.lang.String = js.native
  var FTPSite: java.lang.String = js.native
  var FileAs: java.lang.String = js.native
  var FirstName: java.lang.String = js.native
  val FormDescription: FormDescription = js.native
  var FullName: java.lang.String = js.native
  val FullNameAndCompany: java.lang.String = js.native
  var Gender: OlGender = js.native
  val GetInspector: Inspector = js.native
  var GovernmentIDNumber: java.lang.String = js.native
  val HasPicture: scala.Boolean = js.native
  var Hobby: java.lang.String = js.native
  var Home2TelephoneNumber: java.lang.String = js.native
  var HomeAddress: java.lang.String = js.native
  var HomeAddressCity: java.lang.String = js.native
  var HomeAddressCountry: java.lang.String = js.native
  var HomeAddressPostOfficeBox: java.lang.String = js.native
  var HomeAddressPostalCode: java.lang.String = js.native
  var HomeAddressState: java.lang.String = js.native
  var HomeAddressStreet: java.lang.String = js.native
  var HomeFaxNumber: java.lang.String = js.native
  var HomeTelephoneNumber: java.lang.String = js.native
  var IMAddress: java.lang.String = js.native
  var ISDNNumber: java.lang.String = js.native
  var Importance: OlImportance = js.native
  var Initials: java.lang.String = js.native
  var InternetFreeBusyAddress: java.lang.String = js.native
  val IsConflict: scala.Boolean = js.native
  val IsMarkedAsTask: scala.Boolean = js.native
  val ItemProperties: ItemProperties = js.native
  var JobTitle: java.lang.String = js.native
  var Journal: scala.Boolean = js.native
  var Language: java.lang.String = js.native
  val LastFirstAndSuffix: java.lang.String = js.native
  val LastFirstNoSpace: java.lang.String = js.native
  val LastFirstNoSpaceAndSuffix: java.lang.String = js.native
  val LastFirstNoSpaceCompany: java.lang.String = js.native
  val LastFirstSpaceOnly: java.lang.String = js.native
  val LastFirstSpaceOnlyCompany: java.lang.String = js.native
  val LastModificationTime: activexDashInteropLib.VarDate = js.native
  var LastName: java.lang.String = js.native
  val LastNameAndFirstName: java.lang.String = js.native
  val Links: Links = js.native
  val MAPIOBJECT: js.Any = js.native
  var MailingAddress: java.lang.String = js.native
  var MailingAddressCity: java.lang.String = js.native
  var MailingAddressCountry: java.lang.String = js.native
  var MailingAddressPostOfficeBox: java.lang.String = js.native
  var MailingAddressPostalCode: java.lang.String = js.native
  var MailingAddressState: java.lang.String = js.native
  var MailingAddressStreet: java.lang.String = js.native
  var ManagerName: java.lang.String = js.native
  var MarkForDownload: OlRemoteStatus = js.native
  var MessageClass: java.lang.String = js.native
  var MiddleName: java.lang.String = js.native
  var Mileage: java.lang.String = js.native
  var MobileTelephoneNumber: java.lang.String = js.native
  var NetMeetingAlias: java.lang.String = js.native
  var NetMeetingServer: java.lang.String = js.native
  var NickName: java.lang.String = js.native
  var NoAging: scala.Boolean = js.native
  var OfficeLocation: java.lang.String = js.native
  var OrganizationalIDNumber: java.lang.String = js.native
  var OtherAddress: java.lang.String = js.native
  var OtherAddressCity: java.lang.String = js.native
  var OtherAddressCountry: java.lang.String = js.native
  var OtherAddressPostOfficeBox: java.lang.String = js.native
  var OtherAddressPostalCode: java.lang.String = js.native
  var OtherAddressState: java.lang.String = js.native
  var OtherAddressStreet: java.lang.String = js.native
  var OtherFaxNumber: java.lang.String = js.native
  var OtherTelephoneNumber: java.lang.String = js.native
  var `Outlook.ContactItem_typekey`: ContactItem = js.native
  val OutlookInternalVersion: scala.Double = js.native
  val OutlookVersion: java.lang.String = js.native
  var PagerNumber: java.lang.String = js.native
  val Parent: js.Any = js.native
  var PersonalHomePage: java.lang.String = js.native
  var PrimaryTelephoneNumber: java.lang.String = js.native
  var Profession: java.lang.String = js.native
  val PropertyAccessor: PropertyAccessor = js.native
  var RTFBody: js.Any = js.native
  var RadioTelephoneNumber: java.lang.String = js.native
  var ReferredBy: java.lang.String = js.native
  var ReminderOverrideDefault: scala.Boolean = js.native
  var ReminderPlaySound: scala.Boolean = js.native
  var ReminderSet: scala.Boolean = js.native
  var ReminderSoundFile: java.lang.String = js.native
  var ReminderTime: activexDashInteropLib.VarDate = js.native
  val Saved: scala.Boolean = js.native
  var SelectedMailingAddress: OlMailingAddress = js.native
  var Sensitivity: OlSensitivity = js.native
  val Session: NameSpace = js.native
  val Size: scala.Double = js.native
  var Spouse: java.lang.String = js.native
  var Subject: java.lang.String = js.native
  var Suffix: java.lang.String = js.native
  var TTYTDDTelephoneNumber: java.lang.String = js.native
  var TaskCompletedDate: activexDashInteropLib.VarDate = js.native
  var TaskDueDate: activexDashInteropLib.VarDate = js.native
  var TaskStartDate: activexDashInteropLib.VarDate = js.native
  var TaskSubject: java.lang.String = js.native
  var TelexNumber: java.lang.String = js.native
  var Title: java.lang.String = js.native
  var ToDoTaskOrdinal: activexDashInteropLib.VarDate = js.native
  var UnRead: scala.Boolean = js.native
  var User1: java.lang.String = js.native
  var User2: java.lang.String = js.native
  var User3: java.lang.String = js.native
  var User4: java.lang.String = js.native
  var UserCertificate: java.lang.String = js.native
  val UserProperties: UserProperties = js.native
  var WebPage: java.lang.String = js.native
  var YomiCompanyName: java.lang.String = js.native
  var YomiFirstName: java.lang.String = js.native
  var YomiLastName: java.lang.String = js.native
  def AddBusinessCardLogoPicture(Path: java.lang.String): scala.Unit = js.native
  def AddPicture(Path: java.lang.String): scala.Unit = js.native
  def ClearTaskFlag(): scala.Unit = js.native
  def Close(SaveMode: OlInspectorClose): scala.Unit = js.native
  def Copy(): js.Any = js.native
  def Delete(): scala.Unit = js.native
  def Display(): scala.Unit = js.native
  def Display(Modal: js.Any): scala.Unit = js.native
  def ForwardAsBusinessCard(): MailItem = js.native
  def ForwardAsVcard(): MailItem = js.native
  def GetConversation(): Conversation = js.native
  def MarkAsTask(MarkInterval: OlMarkInterval): scala.Unit = js.native
  def Move(DestFldr: Folder): js.Any = js.native
  def PrintOut(): scala.Unit = js.native
  def RemovePicture(): scala.Unit = js.native
  def ResetBusinessCard(): scala.Unit = js.native
  def Save(): scala.Unit = js.native
  def SaveAs(Path: java.lang.String): scala.Unit = js.native
  def SaveAs(Path: java.lang.String, Type: js.Any): scala.Unit = js.native
  def SaveBusinessCardImage(Path: java.lang.String): scala.Unit = js.native
  def ShowBusinessCardEditor(): scala.Unit = js.native
  def ShowCategoriesDialog(): scala.Unit = js.native
  def ShowCheckPhoneDialog(PhoneNumber: OlContactPhoneNumber): scala.Unit = js.native
}

