package typings.googleapis.buildSrcApisAppengineV1betaMod.appengine_v1beta

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait Schema$OAuth2ClientInfo extends js.Object {
  /**
    * Application name to be used in OAuth consent screen.
    */
  var applicationName: js.UndefOr[String] = js.native
  /**
    * Nameof the client to be generated. Optional - If not provided, the name
    * will be autogenerated by the backend.
    */
  var clientName: js.UndefOr[String] = js.native
  /**
    * Developer&#39;s information to be used in OAuth consent screen.
    */
  var developerEmailAddress: js.UndefOr[String] = js.native
}

object Schema$OAuth2ClientInfo {
  @scala.inline
  def apply(applicationName: String = null, clientName: String = null, developerEmailAddress: String = null): Schema$OAuth2ClientInfo = {
    val __obj = js.Dynamic.literal()
    if (applicationName != null) __obj.updateDynamic("applicationName")(applicationName.asInstanceOf[js.Any])
    if (clientName != null) __obj.updateDynamic("clientName")(clientName.asInstanceOf[js.Any])
    if (developerEmailAddress != null) __obj.updateDynamic("developerEmailAddress")(developerEmailAddress.asInstanceOf[js.Any])
    __obj.asInstanceOf[Schema$OAuth2ClientInfo]
  }
}

