package typings
package reactDashNativeDashPlatformDashTouchableLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

object reactDashNativeDashPlatformDashTouchableLibComponents {
  @scala.inline
  def ReactDashNativeDashPlatformDashTouchable: reactLib.reactMod.ReactNs.ComponentType[
    reactDashNativeDashPlatformDashTouchableLib.reactDashNativeDashPlatformDashTouchableMod.PlatformTouchableProps
  ] = js.constructorOf[reactDashNativeDashPlatformDashTouchableLib.reactDashNativeDashPlatformDashTouchableMod.default].asInstanceOf[reactLib.reactMod.ReactNs.ComponentType[
  reactDashNativeDashPlatformDashTouchableLib.reactDashNativeDashPlatformDashTouchableMod.PlatformTouchableProps]]
  @scala.inline
  def Touchable: reactLib.reactMod.ReactNs.ComponentType[
    reactDashNativeDashPlatformDashTouchableLib.reactDashNativeDashPlatformDashTouchableMod.PlatformTouchableProps
  ] = js.constructorOf[reactDashNativeDashPlatformDashTouchableLib.reactDashNativeDashPlatformDashTouchableMod.Touchable].asInstanceOf[reactLib.reactMod.ReactNs.ComponentType[
  reactDashNativeDashPlatformDashTouchableLib.reactDashNativeDashPlatformDashTouchableMod.PlatformTouchableProps]]
  @scala.inline
  def PlatformTouchableProps: reactDashNativeDashPlatformDashTouchableLib.reactDashNativeDashPlatformDashTouchableMod.PlatformTouchableProps.type = reactDashNativeDashPlatformDashTouchableLib.reactDashNativeDashPlatformDashTouchableMod.PlatformTouchableProps
  type PlatformTouchableProps = reactDashNativeDashPlatformDashTouchableLib.reactDashNativeDashPlatformDashTouchableMod.PlatformTouchableProps
}

