package typings
package hyperscriptLib.hyperscriptMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait HyperScript extends js.Object {
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.`object`): stdLib.HTMLObjectElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.`object`, attrs: js.Object, children: js.Any*): stdLib.HTMLObjectElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.`var`): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.`var`, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  /** Creates an Element */
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.a): stdLib.HTMLAnchorElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.a, attrs: js.Object, children: js.Any*): stdLib.HTMLAnchorElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.abbr): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.abbr, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.address): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.address, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.applet): stdLib.HTMLAppletElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.applet, attrs: js.Object, children: js.Any*): stdLib.HTMLAppletElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.area): stdLib.HTMLAreaElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.area, attrs: js.Object, children: js.Any*): stdLib.HTMLAreaElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.article): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.article, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.aside): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.aside, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.audio): stdLib.HTMLAudioElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.audio, attrs: js.Object, children: js.Any*): stdLib.HTMLAudioElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.b): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.base): stdLib.HTMLBaseElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.base, attrs: js.Object, children: js.Any*): stdLib.HTMLBaseElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.basefont): stdLib.HTMLBaseFontElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.basefont, attrs: js.Object, children: js.Any*): stdLib.HTMLBaseFontElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.b, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.bdi): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.bdi, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.bdo): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.bdo, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.blockquote): stdLib.HTMLQuoteElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.blockquote, attrs: js.Object, children: js.Any*): stdLib.HTMLQuoteElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.body): stdLib.HTMLBodyElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.body, attrs: js.Object, children: js.Any*): stdLib.HTMLBodyElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.br): stdLib.HTMLBRElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.br, attrs: js.Object, children: js.Any*): stdLib.HTMLBRElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.button): stdLib.HTMLButtonElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.button, attrs: js.Object, children: js.Any*): stdLib.HTMLButtonElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.canvas): stdLib.HTMLCanvasElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.canvas, attrs: js.Object, children: js.Any*): stdLib.HTMLCanvasElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.caption): stdLib.HTMLTableCaptionElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.caption, attrs: js.Object, children: js.Any*): stdLib.HTMLTableCaptionElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.cite): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.cite, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.code): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.code, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.col): stdLib.HTMLTableColElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.col, attrs: js.Object, children: js.Any*): stdLib.HTMLTableColElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.colgroup): stdLib.HTMLTableColElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.colgroup, attrs: js.Object, children: js.Any*): stdLib.HTMLTableColElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.data): stdLib.HTMLDataElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.data, attrs: js.Object, children: js.Any*): stdLib.HTMLDataElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.datalist): stdLib.HTMLDataListElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.datalist, attrs: js.Object, children: js.Any*): stdLib.HTMLDataListElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.dd): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.dd, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.del): stdLib.HTMLModElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.del, attrs: js.Object, children: js.Any*): stdLib.HTMLModElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.details): stdLib.HTMLDetailsElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.details, attrs: js.Object, children: js.Any*): stdLib.HTMLDetailsElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.dfn): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.dfn, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.dialog): stdLib.HTMLDialogElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.dialog, attrs: js.Object, children: js.Any*): stdLib.HTMLDialogElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.dir): stdLib.HTMLDirectoryElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.dir, attrs: js.Object, children: js.Any*): stdLib.HTMLDirectoryElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.div): stdLib.HTMLDivElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.div, attrs: js.Object, children: js.Any*): stdLib.HTMLDivElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.dl): stdLib.HTMLDListElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.dl, attrs: js.Object, children: js.Any*): stdLib.HTMLDListElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.dt): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.dt, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.em): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.em, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.embed): stdLib.HTMLEmbedElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.embed, attrs: js.Object, children: js.Any*): stdLib.HTMLEmbedElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.fieldset): stdLib.HTMLFieldSetElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.fieldset, attrs: js.Object, children: js.Any*): stdLib.HTMLFieldSetElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.figcaption): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.figcaption, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.figure): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.figure, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.font): stdLib.HTMLFontElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.font, attrs: js.Object, children: js.Any*): stdLib.HTMLFontElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.footer): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.footer, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.form): stdLib.HTMLFormElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.form, attrs: js.Object, children: js.Any*): stdLib.HTMLFormElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.frame): stdLib.HTMLFrameElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.frame, attrs: js.Object, children: js.Any*): stdLib.HTMLFrameElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.frameset): stdLib.HTMLFrameSetElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.frameset, attrs: js.Object, children: js.Any*): stdLib.HTMLFrameSetElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.h1): stdLib.HTMLHeadingElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.h1, attrs: js.Object, children: js.Any*): stdLib.HTMLHeadingElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.h2): stdLib.HTMLHeadingElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.h2, attrs: js.Object, children: js.Any*): stdLib.HTMLHeadingElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.h3): stdLib.HTMLHeadingElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.h3, attrs: js.Object, children: js.Any*): stdLib.HTMLHeadingElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.h4): stdLib.HTMLHeadingElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.h4, attrs: js.Object, children: js.Any*): stdLib.HTMLHeadingElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.h5): stdLib.HTMLHeadingElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.h5, attrs: js.Object, children: js.Any*): stdLib.HTMLHeadingElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.h6): stdLib.HTMLHeadingElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.h6, attrs: js.Object, children: js.Any*): stdLib.HTMLHeadingElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.head): stdLib.HTMLHeadElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.head, attrs: js.Object, children: js.Any*): stdLib.HTMLHeadElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.header): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.header, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.hgroup): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.hgroup, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.hr): stdLib.HTMLHRElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.hr, attrs: js.Object, children: js.Any*): stdLib.HTMLHRElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.html): stdLib.HTMLHtmlElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.html, attrs: js.Object, children: js.Any*): stdLib.HTMLHtmlElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.i): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.i, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.iframe): stdLib.HTMLIFrameElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.iframe, attrs: js.Object, children: js.Any*): stdLib.HTMLIFrameElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.img): stdLib.HTMLImageElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.img, attrs: js.Object, children: js.Any*): stdLib.HTMLImageElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.input): stdLib.HTMLInputElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.input, attrs: js.Object, children: js.Any*): stdLib.HTMLInputElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.ins): stdLib.HTMLModElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.ins, attrs: js.Object, children: js.Any*): stdLib.HTMLModElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.kbd): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.kbd, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.label): stdLib.HTMLLabelElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.label, attrs: js.Object, children: js.Any*): stdLib.HTMLLabelElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.legend): stdLib.HTMLLegendElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.legend, attrs: js.Object, children: js.Any*): stdLib.HTMLLegendElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.li): stdLib.HTMLLIElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.li, attrs: js.Object, children: js.Any*): stdLib.HTMLLIElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.link): stdLib.HTMLLinkElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.link, attrs: js.Object, children: js.Any*): stdLib.HTMLLinkElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.main): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.main, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.map): stdLib.HTMLMapElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.map, attrs: js.Object, children: js.Any*): stdLib.HTMLMapElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.mark): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.mark, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.marquee): stdLib.HTMLMarqueeElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.marquee, attrs: js.Object, children: js.Any*): stdLib.HTMLMarqueeElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.menu): stdLib.HTMLMenuElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.menu, attrs: js.Object, children: js.Any*): stdLib.HTMLMenuElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.meta): stdLib.HTMLMetaElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.meta, attrs: js.Object, children: js.Any*): stdLib.HTMLMetaElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.meter): stdLib.HTMLMeterElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.meter, attrs: js.Object, children: js.Any*): stdLib.HTMLMeterElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.nav): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.nav, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.noscript): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.noscript, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.ol): stdLib.HTMLOListElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.ol, attrs: js.Object, children: js.Any*): stdLib.HTMLOListElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.optgroup): stdLib.HTMLOptGroupElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.optgroup, attrs: js.Object, children: js.Any*): stdLib.HTMLOptGroupElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.option): stdLib.HTMLOptionElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.option, attrs: js.Object, children: js.Any*): stdLib.HTMLOptionElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.output): stdLib.HTMLOutputElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.output, attrs: js.Object, children: js.Any*): stdLib.HTMLOutputElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.p): stdLib.HTMLParagraphElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.param): stdLib.HTMLParamElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.param, attrs: js.Object, children: js.Any*): stdLib.HTMLParamElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.p, attrs: js.Object, children: js.Any*): stdLib.HTMLParagraphElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.picture): stdLib.HTMLPictureElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.picture, attrs: js.Object, children: js.Any*): stdLib.HTMLPictureElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.pre): stdLib.HTMLPreElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.pre, attrs: js.Object, children: js.Any*): stdLib.HTMLPreElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.progress): stdLib.HTMLProgressElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.progress, attrs: js.Object, children: js.Any*): stdLib.HTMLProgressElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.q): stdLib.HTMLQuoteElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.q, attrs: js.Object, children: js.Any*): stdLib.HTMLQuoteElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.rp): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.rp, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.rt): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.rt, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.ruby): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.ruby, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.s): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.samp): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.samp, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.s, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.script): stdLib.HTMLScriptElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.script, attrs: js.Object, children: js.Any*): stdLib.HTMLScriptElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.section): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.section, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.select): stdLib.HTMLSelectElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.select, attrs: js.Object, children: js.Any*): stdLib.HTMLSelectElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.slot): stdLib.HTMLSlotElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.slot, attrs: js.Object, children: js.Any*): stdLib.HTMLSlotElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.small): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.small, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.source): stdLib.HTMLSourceElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.source, attrs: js.Object, children: js.Any*): stdLib.HTMLSourceElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.span): stdLib.HTMLSpanElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.span, attrs: js.Object, children: js.Any*): stdLib.HTMLSpanElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.strong): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.strong, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.style): stdLib.HTMLStyleElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.style, attrs: js.Object, children: js.Any*): stdLib.HTMLStyleElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.sub): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.sub, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.summary): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.summary, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.sup): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.sup, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.table): stdLib.HTMLTableElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.table, attrs: js.Object, children: js.Any*): stdLib.HTMLTableElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.tbody): stdLib.HTMLTableSectionElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.tbody, attrs: js.Object, children: js.Any*): stdLib.HTMLTableSectionElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.td): stdLib.HTMLTableDataCellElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.td, attrs: js.Object, children: js.Any*): stdLib.HTMLTableDataCellElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.template): stdLib.HTMLTemplateElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.template, attrs: js.Object, children: js.Any*): stdLib.HTMLTemplateElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.textarea): stdLib.HTMLTextAreaElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.textarea, attrs: js.Object, children: js.Any*): stdLib.HTMLTextAreaElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.tfoot): stdLib.HTMLTableSectionElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.tfoot, attrs: js.Object, children: js.Any*): stdLib.HTMLTableSectionElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.th): stdLib.HTMLTableHeaderCellElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.th, attrs: js.Object, children: js.Any*): stdLib.HTMLTableHeaderCellElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.thead): stdLib.HTMLTableSectionElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.thead, attrs: js.Object, children: js.Any*): stdLib.HTMLTableSectionElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.time): stdLib.HTMLTimeElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.time, attrs: js.Object, children: js.Any*): stdLib.HTMLTimeElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.title): stdLib.HTMLTitleElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.title, attrs: js.Object, children: js.Any*): stdLib.HTMLTitleElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.tr): stdLib.HTMLTableRowElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.track): stdLib.HTMLTrackElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.track, attrs: js.Object, children: js.Any*): stdLib.HTMLTrackElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.tr, attrs: js.Object, children: js.Any*): stdLib.HTMLTableRowElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.u): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.u, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.ul): stdLib.HTMLUListElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.ul, attrs: js.Object, children: js.Any*): stdLib.HTMLUListElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.video): stdLib.HTMLVideoElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.video, attrs: js.Object, children: js.Any*): stdLib.HTMLVideoElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.wbr): stdLib.HTMLElement = js.native
  def apply(tagName: hyperscriptLib.hyperscriptLibStrings.wbr, attrs: js.Object, children: js.Any*): stdLib.HTMLElement = js.native
  def apply[T /* <: stdLib.Element */](tagName: java.lang.String): T = js.native
  def apply[T /* <: stdLib.Element */](tagName: java.lang.String, attrs: js.Object, children: js.Any*): T = js.native
  /** Cleans up any event handlers created by this hyperscript context */
  def cleanup(): scala.Unit = js.native
  /** Creates a new hyperscript context */
  def context(): HyperScript = js.native
}

