package typings.googleapis.buildSrcApisDataflowV1b3Mod.dataflow_v1b3

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/**
  * Description of the composing transforms, names/ids, and input/outputs of a
  * stage of execution.  Some composing transforms and sources may have been
  * generated by the Dataflow service during execution planning.
  */
@js.native
trait Schema$ExecutionStageSummary extends js.Object {
  /**
    * Collections produced and consumed by component transforms of this stage.
    */
  var componentSource: js.UndefOr[js.Array[Schema$ComponentSource]] = js.native
  /**
    * Transforms that comprise this execution stage.
    */
  var componentTransform: js.UndefOr[js.Array[Schema$ComponentTransform]] = js.native
  /**
    * Dataflow service generated id for this stage.
    */
  var id: js.UndefOr[String] = js.native
  /**
    * Input sources for this stage.
    */
  var inputSource: js.UndefOr[js.Array[Schema$StageSource]] = js.native
  /**
    * Type of tranform this stage is executing.
    */
  var kind: js.UndefOr[String] = js.native
  /**
    * Dataflow service generated name for this stage.
    */
  var name: js.UndefOr[String] = js.native
  /**
    * Output sources for this stage.
    */
  var outputSource: js.UndefOr[js.Array[Schema$StageSource]] = js.native
}

object Schema$ExecutionStageSummary {
  @scala.inline
  def apply(
    componentSource: js.Array[Schema$ComponentSource] = null,
    componentTransform: js.Array[Schema$ComponentTransform] = null,
    id: String = null,
    inputSource: js.Array[Schema$StageSource] = null,
    kind: String = null,
    name: String = null,
    outputSource: js.Array[Schema$StageSource] = null
  ): Schema$ExecutionStageSummary = {
    val __obj = js.Dynamic.literal()
    if (componentSource != null) __obj.updateDynamic("componentSource")(componentSource.asInstanceOf[js.Any])
    if (componentTransform != null) __obj.updateDynamic("componentTransform")(componentTransform.asInstanceOf[js.Any])
    if (id != null) __obj.updateDynamic("id")(id.asInstanceOf[js.Any])
    if (inputSource != null) __obj.updateDynamic("inputSource")(inputSource.asInstanceOf[js.Any])
    if (kind != null) __obj.updateDynamic("kind")(kind.asInstanceOf[js.Any])
    if (name != null) __obj.updateDynamic("name")(name.asInstanceOf[js.Any])
    if (outputSource != null) __obj.updateDynamic("outputSource")(outputSource.asInstanceOf[js.Any])
    __obj.asInstanceOf[Schema$ExecutionStageSummary]
  }
}

