package typings.chromeRemoteInterface.anon

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/* Inlined chrome-remote-interface.chrome-remote-interface.OptIfParamNullable<devtools-protocol.devtools-protocol/types/protocol-proxy-api.default.WebAudioApi> */
trait OptIfParamNullableWebAudi extends StObject {
  
  var disable: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any
  
  var enable: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any
  
  var getRealtimeData: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse> : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse> */ js.Any
  
  var on: /* import warning: importer.ImportType#apply Failed type conversion: (event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void>[0]> extends true ? (params : std.Parameters<(event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void>[0] | undefined): std.ReturnType<(event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void> : (event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void : (event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void */ js.Any
}
object OptIfParamNullableWebAudi {
  
  inline def apply(
    disable: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any,
    enable: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any,
    getRealtimeData: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse> : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse> */ js.Any,
    on: /* import warning: importer.ImportType#apply Failed type conversion: (event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void>[0]> extends true ? (params : std.Parameters<(event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void>[0] | undefined): std.ReturnType<(event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void> : (event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void : (event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void */ js.Any
  ): OptIfParamNullableWebAudi = {
    val __obj = js.Dynamic.literal(disable = disable.asInstanceOf[js.Any], enable = enable.asInstanceOf[js.Any], getRealtimeData = getRealtimeData.asInstanceOf[js.Any], on = on.asInstanceOf[js.Any])
    __obj.asInstanceOf[OptIfParamNullableWebAudi]
  }
  
  @scala.inline
  implicit open class MutableBuilder[Self <: OptIfParamNullableWebAudi] (val x: Self) extends AnyVal {
    
    inline def setDisable(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any
    ): Self = StObject.set(x, "disable", value.asInstanceOf[js.Any])
    
    inline def setEnable(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any
    ): Self = StObject.set(x, "enable", value.asInstanceOf[js.Any])
    
    inline def setGetRealtimeData(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse> : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.WebAudio.GetRealtimeDataResponse> */ js.Any
    ): Self = StObject.set(x, "getRealtimeData", value.asInstanceOf[js.Any])
    
    inline def setOn(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void>[0]> extends true ? (params : std.Parameters<(event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void>[0] | undefined): std.ReturnType<(event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void> : (event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void : (event : 'contextCreated', listener : (params : devtools-protocol.devtools-protocol.Protocol.WebAudio.ContextCreatedEvent): void): void */ js.Any
    ): Self = StObject.set(x, "on", value.asInstanceOf[js.Any])
  }
}
