package typings.chromeRemoteInterface.anon

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/* Inlined chrome-remote-interface.chrome-remote-interface.OptIfParamNullable<devtools-protocol.devtools-protocol/types/protocol-proxy-api.default.HeapProfilerApi> */
trait OptIfParamNullableHeapPro extends StObject {
  
  var addInspectedHeapObject: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void> */ js.Any
  
  var collectGarbage: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any
  
  var disable: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any
  
  var enable: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any
  
  var getHeapObjectId: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse> */ js.Any
  
  var getObjectByHeapObjectId: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse> */ js.Any
  
  var getSamplingProfile: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse>>[0]> extends true ? (params : std.Parameters<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse>>[0] | undefined): std.ReturnType<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse>> : (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse> : (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse> */ js.Any
  
  var on: /* import warning: importer.ImportType#apply Failed type conversion: (event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void>[0]> extends true ? (params : std.Parameters<(event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void>[0] | undefined): std.ReturnType<(event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void> : (event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void : (event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void */ js.Any
  
  var startSampling: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void> */ js.Any
  
  var startTrackingHeapObjects: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void> */ js.Any
  
  var stopSampling: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse>>[0]> extends true ? (params : std.Parameters<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse>>[0] | undefined): std.ReturnType<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse>> : (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse> : (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse> */ js.Any
  
  var stopTrackingHeapObjects: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void> */ js.Any
  
  var takeHeapSnapshot: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void> */ js.Any
}
object OptIfParamNullableHeapPro {
  
  inline def apply(
    addInspectedHeapObject: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void> */ js.Any,
    collectGarbage: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any,
    disable: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any,
    enable: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any,
    getHeapObjectId: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse> */ js.Any,
    getObjectByHeapObjectId: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse> */ js.Any,
    getSamplingProfile: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse>>[0]> extends true ? (params : std.Parameters<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse>>[0] | undefined): std.ReturnType<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse>> : (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse> : (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse> */ js.Any,
    on: /* import warning: importer.ImportType#apply Failed type conversion: (event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void>[0]> extends true ? (params : std.Parameters<(event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void>[0] | undefined): std.ReturnType<(event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void> : (event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void : (event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void */ js.Any,
    startSampling: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void> */ js.Any,
    startTrackingHeapObjects: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void> */ js.Any,
    stopSampling: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse>>[0]> extends true ? (params : std.Parameters<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse>>[0] | undefined): std.ReturnType<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse>> : (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse> : (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse> */ js.Any,
    stopTrackingHeapObjects: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void> */ js.Any,
    takeHeapSnapshot: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void> */ js.Any
  ): OptIfParamNullableHeapPro = {
    val __obj = js.Dynamic.literal(addInspectedHeapObject = addInspectedHeapObject.asInstanceOf[js.Any], collectGarbage = collectGarbage.asInstanceOf[js.Any], disable = disable.asInstanceOf[js.Any], enable = enable.asInstanceOf[js.Any], getHeapObjectId = getHeapObjectId.asInstanceOf[js.Any], getObjectByHeapObjectId = getObjectByHeapObjectId.asInstanceOf[js.Any], getSamplingProfile = getSamplingProfile.asInstanceOf[js.Any], on = on.asInstanceOf[js.Any], startSampling = startSampling.asInstanceOf[js.Any], startTrackingHeapObjects = startTrackingHeapObjects.asInstanceOf[js.Any], stopSampling = stopSampling.asInstanceOf[js.Any], stopTrackingHeapObjects = stopTrackingHeapObjects.asInstanceOf[js.Any], takeHeapSnapshot = takeHeapSnapshot.asInstanceOf[js.Any])
    __obj.asInstanceOf[OptIfParamNullableHeapPro]
  }
  
  @scala.inline
  implicit open class MutableBuilder[Self <: OptIfParamNullableHeapPro] (val x: Self) extends AnyVal {
    
    inline def setAddInspectedHeapObject(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddInspectedHeapObjectRequest): std.Promise<void> */ js.Any
    ): Self = StObject.set(x, "addInspectedHeapObject", value.asInstanceOf[js.Any])
    
    inline def setCollectGarbage(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any
    ): Self = StObject.set(x, "collectGarbage", value.asInstanceOf[js.Any])
    
    inline def setDisable(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any
    ): Self = StObject.set(x, "disable", value.asInstanceOf[js.Any])
    
    inline def setEnable(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any
    ): Self = StObject.set(x, "enable", value.asInstanceOf[js.Any])
    
    inline def setGetHeapObjectId(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetHeapObjectIdResponse> */ js.Any
    ): Self = StObject.set(x, "getHeapObjectId", value.asInstanceOf[js.Any])
    
    inline def setGetObjectByHeapObjectId(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetObjectByHeapObjectIdResponse> */ js.Any
    ): Self = StObject.set(x, "getObjectByHeapObjectId", value.asInstanceOf[js.Any])
    
    inline def setGetSamplingProfile(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse>>[0]> extends true ? (params : std.Parameters<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse>>[0] | undefined): std.ReturnType<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse>> : (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse> : (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.GetSamplingProfileResponse> */ js.Any
    ): Self = StObject.set(x, "getSamplingProfile", value.asInstanceOf[js.Any])
    
    inline def setOn(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void>[0]> extends true ? (params : std.Parameters<(event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void>[0] | undefined): std.ReturnType<(event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void> : (event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void : (event : 'addHeapSnapshotChunk', listener : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.AddHeapSnapshotChunkEvent): void): void */ js.Any
    ): Self = StObject.set(x, "on", value.asInstanceOf[js.Any])
    
    inline def setStartSampling(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartSamplingRequest): std.Promise<void> */ js.Any
    ): Self = StObject.set(x, "startSampling", value.asInstanceOf[js.Any])
    
    inline def setStartTrackingHeapObjects(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StartTrackingHeapObjectsRequest): std.Promise<void> */ js.Any
    ): Self = StObject.set(x, "startTrackingHeapObjects", value.asInstanceOf[js.Any])
    
    inline def setStopSampling(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse>>[0]> extends true ? (params : std.Parameters<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse>>[0] | undefined): std.ReturnType<(): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse>> : (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse> : (): std.Promise<devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopSamplingResponse> */ js.Any
    ): Self = StObject.set(x, "stopSampling", value.asInstanceOf[js.Any])
    
    inline def setStopTrackingHeapObjects(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.StopTrackingHeapObjectsRequest): std.Promise<void> */ js.Any
    ): Self = StObject.set(x, "stopTrackingHeapObjects", value.asInstanceOf[js.Any])
    
    inline def setTakeHeapSnapshot(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.HeapProfiler.TakeHeapSnapshotRequest): std.Promise<void> */ js.Any
    ): Self = StObject.set(x, "takeHeapSnapshot", value.asInstanceOf[js.Any])
  }
}
