package typings.chromeRemoteInterface.anon

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/* Inlined chrome-remote-interface.chrome-remote-interface.OptIfParamNullable<devtools-protocol.devtools-protocol/types/protocol-proxy-api.default.IOApi> */
trait OptIfParamNullableIOApi extends StObject {
  
  var close: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void> */ js.Any
  
  var read: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse> : (params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse> */ js.Any
  
  var resolveBlob: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse> : (params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse> */ js.Any
}
object OptIfParamNullableIOApi {
  
  inline def apply(
    close: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void> */ js.Any,
    read: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse> : (params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse> */ js.Any,
    resolveBlob: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse> : (params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse> */ js.Any
  ): OptIfParamNullableIOApi = {
    val __obj = js.Dynamic.literal(close = close.asInstanceOf[js.Any], read = read.asInstanceOf[js.Any], resolveBlob = resolveBlob.asInstanceOf[js.Any])
    __obj.asInstanceOf[OptIfParamNullableIOApi]
  }
  
  @scala.inline
  implicit open class MutableBuilder[Self <: OptIfParamNullableIOApi] (val x: Self) extends AnyVal {
    
    inline def setClose(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.IO.CloseRequest): std.Promise<void> */ js.Any
    ): Self = StObject.set(x, "close", value.asInstanceOf[js.Any])
    
    inline def setRead(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse> : (params : devtools-protocol.devtools-protocol.Protocol.IO.ReadRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ReadResponse> */ js.Any
    ): Self = StObject.set(x, "read", value.asInstanceOf[js.Any])
    
    inline def setResolveBlob(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse> : (params : devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.IO.ResolveBlobResponse> */ js.Any
    ): Self = StObject.set(x, "resolveBlob", value.asInstanceOf[js.Any])
  }
}
