package typings.chromeRemoteInterface.anon

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/* Inlined chrome-remote-interface.chrome-remote-interface.OptIfParamNullable<devtools-protocol.devtools-protocol/types/protocol-proxy-api.default.LayerTreeApi> */
trait OptIfParamNullableLayerTr extends StObject {
  
  var compositingReasons: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse> */ js.Any
  
  var disable: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any
  
  var enable: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any
  
  var loadSnapshot: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse> */ js.Any
  
  var makeSnapshot: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse> */ js.Any
  
  var on: /* import warning: importer.ImportType#apply Failed type conversion: (event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void>[0]> extends true ? (params : std.Parameters<(event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void>[0] | undefined): std.ReturnType<(event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void> : (event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void : (event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void */ js.Any
  
  var profileSnapshot: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse> */ js.Any
  
  var releaseSnapshot: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void> */ js.Any
  
  var replaySnapshot: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse> */ js.Any
  
  var snapshotCommandLog: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse> */ js.Any
}
object OptIfParamNullableLayerTr {
  
  inline def apply(
    compositingReasons: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse> */ js.Any,
    disable: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any,
    enable: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any,
    loadSnapshot: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse> */ js.Any,
    makeSnapshot: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse> */ js.Any,
    on: /* import warning: importer.ImportType#apply Failed type conversion: (event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void>[0]> extends true ? (params : std.Parameters<(event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void>[0] | undefined): std.ReturnType<(event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void> : (event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void : (event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void */ js.Any,
    profileSnapshot: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse> */ js.Any,
    releaseSnapshot: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void> */ js.Any,
    replaySnapshot: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse> */ js.Any,
    snapshotCommandLog: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse> */ js.Any
  ): OptIfParamNullableLayerTr = {
    val __obj = js.Dynamic.literal(compositingReasons = compositingReasons.asInstanceOf[js.Any], disable = disable.asInstanceOf[js.Any], enable = enable.asInstanceOf[js.Any], loadSnapshot = loadSnapshot.asInstanceOf[js.Any], makeSnapshot = makeSnapshot.asInstanceOf[js.Any], on = on.asInstanceOf[js.Any], profileSnapshot = profileSnapshot.asInstanceOf[js.Any], releaseSnapshot = releaseSnapshot.asInstanceOf[js.Any], replaySnapshot = replaySnapshot.asInstanceOf[js.Any], snapshotCommandLog = snapshotCommandLog.asInstanceOf[js.Any])
    __obj.asInstanceOf[OptIfParamNullableLayerTr]
  }
  
  @scala.inline
  implicit open class MutableBuilder[Self <: OptIfParamNullableLayerTr] (val x: Self) extends AnyVal {
    
    inline def setCompositingReasons(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.CompositingReasonsResponse> */ js.Any
    ): Self = StObject.set(x, "compositingReasons", value.asInstanceOf[js.Any])
    
    inline def setDisable(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any
    ): Self = StObject.set(x, "disable", value.asInstanceOf[js.Any])
    
    inline def setEnable(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(): std.Promise<void>>[0] | undefined): std.ReturnType<(): std.Promise<void>> : (): std.Promise<void> : (): std.Promise<void> */ js.Any
    ): Self = StObject.set(x, "enable", value.asInstanceOf[js.Any])
    
    inline def setLoadSnapshot(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.LoadSnapshotResponse> */ js.Any
    ): Self = StObject.set(x, "loadSnapshot", value.asInstanceOf[js.Any])
    
    inline def setMakeSnapshot(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.MakeSnapshotResponse> */ js.Any
    ): Self = StObject.set(x, "makeSnapshot", value.asInstanceOf[js.Any])
    
    inline def setOn(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void>[0]> extends true ? (params : std.Parameters<(event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void>[0] | undefined): std.ReturnType<(event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void> : (event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void : (event : 'layerPainted', listener : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.LayerPaintedEvent): void): void */ js.Any
    ): Self = StObject.set(x, "on", value.asInstanceOf[js.Any])
    
    inline def setProfileSnapshot(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ProfileSnapshotResponse> */ js.Any
    ): Self = StObject.set(x, "profileSnapshot", value.asInstanceOf[js.Any])
    
    inline def setReleaseSnapshot(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReleaseSnapshotRequest): std.Promise<void> */ js.Any
    ): Self = StObject.set(x, "releaseSnapshot", value.asInstanceOf[js.Any])
    
    inline def setReplaySnapshot(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.ReplaySnapshotResponse> */ js.Any
    ): Self = StObject.set(x, "replaySnapshot", value.asInstanceOf[js.Any])
    
    inline def setSnapshotCommandLog(
      value: /* import warning: importer.ImportType#apply Failed type conversion: (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse> extends (params : any): any ? chrome-remote-interface.chrome-remote-interface.IsNullableObj<std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse>>[0]> extends true ? (params : std.Parameters<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse>>[0] | undefined): std.ReturnType<(params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse>> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse> : (params : devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogRequest): std.Promise<devtools-protocol.devtools-protocol.Protocol.LayerTree.SnapshotCommandLogResponse> */ js.Any
    ): Self = StObject.set(x, "snapshotCommandLog", value.asInstanceOf[js.Any])
  }
}
