package typings.instagramDashPrivateDashApi

import typings.instagramDashPrivateDashApi.instagramDashPrivateDashApiStrings.`0a3ae4c88248863609c67e278f34af44673cff300bc76add965a9fb036bd3ca3`
import typings.instagramDashPrivateDashApi.instagramDashPrivateDashApiStrings.`117Dot0Dot0Dot28Dot123`
import typings.instagramDashPrivateDashApi.instagramDashPrivateDashApiStrings.`124024574287414`
import typings.instagramDashPrivateDashApi.instagramDashPrivateDashApiStrings.`180322814`
import typings.instagramDashPrivateDashApi.instagramDashPrivateDashApiStrings.`4`
import typings.instagramDashPrivateDashApi.instagramDashPrivateDashApiStrings.`567067343352427`
import typings.instagramDashPrivateDashApi.instagramDashPrivateDashApiStrings.a86109795736d73c9a94172cd9b736917d7d94ca61c9101164894b3f0d43bef4
import typings.instagramDashPrivateDashApi.instagramDashPrivateDashApiStrings.iDotinstagramDotcom
import typings.instagramDashPrivateDashApi.instagramDashPrivateDashApiStrings.iN4$aGr0m
import typings.instagramDashPrivateDashApi.instagramDashPrivateDashApiStrings.ig_android_fci_onboarding_friend_searchCommaig_android_kotlinCommaig_android_device_detection_info_uploadCommaig_android_account_linking_upsell_universeCommaig_android_direct_main_tab_universe_v2Commaig_android_allow_account_switch_once_media_upload_finish_universeCommaig_android_sms_retriever_backtest_universeCommaig_android_direct_add_direct_to_android_native_photo_share_sheetCommaig_android_spatial_account_switch_universeCommaig_growth_android_profile_pic_prefill_with_fb_pic_2Commaig_account_
import typings.instagramDashPrivateDashApi.instagramDashPrivateDashApiStrings.ig_android_video_ssim_fix_pts_universeCommaig_shopping_checkout_improvements_universeCommaig_android_stories_seen_state_serializationCommaig_android_mqtt_foreground_state_universeCommaig_android_stories_music_search_typeaheadCommaandroid_ard_ig_use_brotli_effect_universeCommaig_android_delayed_commentsCommaig_android_igtv_crop_topCommaig_android_direct_reshare_chainingCommaig_shopping_merchant_profile_bag_androidCommaig_android_feedback_requiredCommaig_android_zero_rating_carrier_signalCommaig_d
import typings.instagramDashPrivateDashApi.instagramDashPrivateDashApiStrings.updatePercentsign7Bdownload_uriPercentsign2Cdownload_uri_delta_basePercentsign2Cversion_code_delta_basePercentsign2Cdownload_uri_deltaPercentsign2Cfallback_to_full_updatePercentsign2Cfile_size_deltaPercentsign2Cversion_codePercentsign2Cpublished_datePercentsign2Cfile_sizePercentsign2Cota_bundle_typePercentsign2Cresources_checksumPercentsign2Callowed_networksPercentsign2Crelease_idPercentsign7D
import typings.instagramDashPrivateDashApi.instagramDashPrivateDashApiStrings.wwwDotinstagramDotcom
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("instagram-private-api/dist/core/constants", JSImport.Namespace)
@js.native
object distCoreConstantsMod extends js.Object {
  val APP_VERSION: `117Dot0Dot0Dot28Dot123` = js.native
  val APP_VERSION_CODE: `180322814` = js.native
  val BLOKS_VERSION_ID: `0a3ae4c88248863609c67e278f34af44673cff300bc76add965a9fb036bd3ca3` = js.native
  val BREADCRUMB_KEY: iN4$aGr0m = js.native
  val EXPERIMENTS: ig_android_video_ssim_fix_pts_universeCommaig_shopping_checkout_improvements_universeCommaig_android_stories_seen_state_serializationCommaig_android_mqtt_foreground_state_universeCommaig_android_stories_music_search_typeaheadCommaandroid_ard_ig_use_brotli_effect_universeCommaig_android_delayed_commentsCommaig_android_igtv_crop_topCommaig_android_direct_reshare_chainingCommaig_shopping_merchant_profile_bag_androidCommaig_android_feedback_requiredCommaig_android_zero_rating_carrier_signalCommaig_d = js.native
  val FACEBOOK_ANALYTICS_APPLICATION_ID: `567067343352427` = js.native
  val FACEBOOK_ORCA_APPLICATION_ID: `124024574287414` = js.native
  val FACEBOOK_OTA_FIELDS: updatePercentsign7Bdownload_uriPercentsign2Cdownload_uri_delta_basePercentsign2Cversion_code_delta_basePercentsign2Cdownload_uri_deltaPercentsign2Cfallback_to_full_updatePercentsign2Cfile_size_deltaPercentsign2Cversion_codePercentsign2Cpublished_datePercentsign2Cfile_sizePercentsign2Cota_bundle_typePercentsign2Cresources_checksumPercentsign2Callowed_networksPercentsign2Crelease_idPercentsign7D = js.native
  val HOST: String = js.native
  val HOSTNAME: iDotinstagramDotcom = js.native
  val LOGIN_EXPERIMENTS: ig_android_fci_onboarding_friend_searchCommaig_android_kotlinCommaig_android_device_detection_info_uploadCommaig_android_account_linking_upsell_universeCommaig_android_direct_main_tab_universe_v2Commaig_android_allow_account_switch_once_media_upload_finish_universeCommaig_android_sms_retriever_backtest_universeCommaig_android_direct_add_direct_to_android_native_photo_share_sheetCommaig_android_spatial_account_switch_universeCommaig_growth_android_profile_pic_prefill_with_fb_pic_2Commaig_account_ = js.native
  val SIGNATURE_KEY: a86109795736d73c9a94172cd9b736917d7d94ca61c9101164894b3f0d43bef4 = js.native
  val SIGNATURE_VERSION: `4` = js.native
  val WEBHOST: String = js.native
  val WEB_HOSTNAME: wwwDotinstagramDotcom = js.native
}

