package typings
package semanticDashUiDashDimmerLib.SemanticUINs

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object DimmerSettingsNs {
  type Param = ((stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.opacity]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.variation]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.dimmerName]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.closable]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.on]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.useCSS]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.duration]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.transition]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.onShow]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.onHide]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.onChange]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.selector]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.template]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.className]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.error]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.namespace]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.name]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.silent]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.debug]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.performance]) | (stdLib.Pick[_Impl, semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.verbose])) with (stdLib.Partial[
    stdLib.Pick[
      _Impl, 
      semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.opacity | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.variation | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.dimmerName | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.closable | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.on | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.useCSS | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.duration | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.transition | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.selector | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.template | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.className | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.error | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.namespace | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.name | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.silent | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.debug | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.performance | semanticDashUiDashDimmerLib.semanticDashUiDashDimmerLibStrings.verbose
    ]
  ])
}
