package typings.csstype.mod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait VendorProperties[TLength]
  extends VendorLonghandProperties[TLength]
     with VendorShorthandProperties[TLength]

object VendorProperties {
  @scala.inline
  def apply[TLength](
    MozAnimation: AnimationProperty = null,
    MozAnimationDelay: GlobalsString = null,
    MozAnimationDirection: AnimationDirectionProperty = null,
    MozAnimationDuration: GlobalsString = null,
    MozAnimationFillMode: AnimationFillModeProperty = null,
    MozAnimationIterationCount: AnimationIterationCountProperty = null,
    MozAnimationName: AnimationNameProperty = null,
    MozAnimationPlayState: AnimationPlayStateProperty = null,
    MozAnimationTimingFunction: AnimationTimingFunctionProperty = null,
    MozAppearance: MozAppearanceProperty = null,
    MozBackfaceVisibility: BackfaceVisibilityProperty = null,
    MozBorderBottomColors: MozBorderBottomColorsProperty = null,
    MozBorderEndColor: BorderInlineEndColorProperty = null,
    MozBorderEndStyle: BorderInlineEndStyleProperty = null,
    MozBorderEndWidth: BorderInlineEndWidthProperty[TLength] = null,
    MozBorderImage: BorderImageProperty = null,
    MozBorderLeftColors: MozBorderLeftColorsProperty = null,
    MozBorderRightColors: MozBorderRightColorsProperty = null,
    MozBorderStartColor: BorderInlineStartColorProperty = null,
    MozBorderStartStyle: BorderInlineStartStyleProperty = null,
    MozBorderTopColors: MozBorderTopColorsProperty = null,
    MozBoxSizing: BoxSizingProperty = null,
    MozColumnCount: ColumnCountProperty = null,
    MozColumnFill: ColumnFillProperty = null,
    MozColumnGap: ColumnGapProperty[TLength] = null,
    MozColumnRule: ColumnRuleProperty[TLength] = null,
    MozColumnRuleColor: ColumnRuleColorProperty = null,
    MozColumnRuleStyle: ColumnRuleStyleProperty = null,
    MozColumnRuleWidth: ColumnRuleWidthProperty[TLength] = null,
    MozColumnWidth: ColumnWidthProperty[TLength] = null,
    MozColumns: ColumnsProperty[TLength] = null,
    MozContextProperties: MozContextPropertiesProperty = null,
    MozFloatEdge: MozFloatEdgeProperty = null,
    MozFontFeatureSettings: FontFeatureSettingsProperty = null,
    MozFontLanguageOverride: FontLanguageOverrideProperty = null,
    MozForceBrokenImageIcon: GlobalsNumber = null,
    MozHyphens: HyphensProperty = null,
    MozImageRegion: MozImageRegionProperty = null,
    MozMarginEnd: MarginInlineEndProperty[TLength] = null,
    MozMarginStart: MarginInlineStartProperty[TLength] = null,
    MozOrient: MozOrientProperty = null,
    MozOutlineRadiusBottomleft: MozOutlineRadiusBottomleftProperty[TLength] = null,
    MozOutlineRadiusBottomright: MozOutlineRadiusBottomrightProperty[TLength] = null,
    MozOutlineRadiusTopleft: MozOutlineRadiusTopleftProperty[TLength] = null,
    MozOutlineRadiusTopright: MozOutlineRadiusToprightProperty[TLength] = null,
    MozPaddingEnd: PaddingInlineEndProperty[TLength] = null,
    MozPaddingStart: PaddingInlineStartProperty[TLength] = null,
    MozPerspective: PerspectiveProperty[TLength] = null,
    MozPerspectiveOrigin: PerspectiveOriginProperty[TLength] = null,
    MozStackSizing: MozStackSizingProperty = null,
    MozTabSize: TabSizeProperty[TLength] = null,
    MozTextSizeAdjust: TextSizeAdjustProperty = null,
    MozTransformOrigin: TransformOriginProperty[TLength] = null,
    MozTransformStyle: TransformStyleProperty = null,
    MozTransition: TransitionProperty = null,
    MozTransitionDelay: GlobalsString = null,
    MozTransitionDuration: GlobalsString = null,
    MozTransitionProperty: TransitionPropertyProperty = null,
    MozTransitionTimingFunction: TransitionTimingFunctionProperty = null,
    MozUserFocus: MozUserFocusProperty = null,
    MozUserModify: MozUserModifyProperty = null,
    MozUserSelect: UserSelectProperty = null,
    MozWindowDragging: MozWindowDraggingProperty = null,
    OObjectFit: ObjectFitProperty = null,
    OObjectPosition: ObjectPositionProperty[TLength] = null,
    OTabSize: TabSizeProperty[TLength] = null,
    OTextOverflow: TextOverflowProperty = null,
    OTransformOrigin: TransformOriginProperty[TLength] = null,
    WebkitAlignContent: AlignContentProperty = null,
    WebkitAlignItems: AlignItemsProperty = null,
    WebkitAlignSelf: AlignSelfProperty = null,
    WebkitAnimation: AnimationProperty = null,
    WebkitAnimationDelay: GlobalsString = null,
    WebkitAnimationDirection: AnimationDirectionProperty = null,
    WebkitAnimationDuration: GlobalsString = null,
    WebkitAnimationFillMode: AnimationFillModeProperty = null,
    WebkitAnimationIterationCount: AnimationIterationCountProperty = null,
    WebkitAnimationName: AnimationNameProperty = null,
    WebkitAnimationPlayState: AnimationPlayStateProperty = null,
    WebkitAnimationTimingFunction: AnimationTimingFunctionProperty = null,
    WebkitAppearance: WebkitAppearanceProperty = null,
    WebkitBackdropFilter: BackdropFilterProperty = null,
    WebkitBackfaceVisibility: BackfaceVisibilityProperty = null,
    WebkitBackgroundClip: BackgroundClipProperty = null,
    WebkitBackgroundOrigin: BackgroundOriginProperty = null,
    WebkitBackgroundSize: BackgroundSizeProperty[TLength] = null,
    WebkitBorderBefore: WebkitBorderBeforeProperty[TLength] = null,
    WebkitBorderBeforeColor: WebkitBorderBeforeColorProperty = null,
    WebkitBorderBeforeStyle: WebkitBorderBeforeStyleProperty = null,
    WebkitBorderBeforeWidth: WebkitBorderBeforeWidthProperty[TLength] = null,
    WebkitBorderBottomLeftRadius: BorderBottomLeftRadiusProperty[TLength] = null,
    WebkitBorderBottomRightRadius: BorderBottomRightRadiusProperty[TLength] = null,
    WebkitBorderImage: BorderImageProperty = null,
    WebkitBorderImageSlice: BorderImageSliceProperty = null,
    WebkitBorderRadius: BorderRadiusProperty[TLength] = null,
    WebkitBorderTopLeftRadius: BorderTopLeftRadiusProperty[TLength] = null,
    WebkitBorderTopRightRadius: BorderTopRightRadiusProperty[TLength] = null,
    WebkitBoxDecorationBreak: BoxDecorationBreakProperty = null,
    WebkitBoxReflect: WebkitBoxReflectProperty[TLength] = null,
    WebkitBoxShadow: BoxShadowProperty = null,
    WebkitBoxSizing: BoxSizingProperty = null,
    WebkitClipPath: ClipPathProperty = null,
    WebkitColorAdjust: ColorAdjustProperty = null,
    WebkitColumnCount: ColumnCountProperty = null,
    WebkitColumnFill: ColumnFillProperty = null,
    WebkitColumnGap: ColumnGapProperty[TLength] = null,
    WebkitColumnRule: ColumnRuleProperty[TLength] = null,
    WebkitColumnRuleColor: ColumnRuleColorProperty = null,
    WebkitColumnRuleStyle: ColumnRuleStyleProperty = null,
    WebkitColumnRuleWidth: ColumnRuleWidthProperty[TLength] = null,
    WebkitColumnSpan: ColumnSpanProperty = null,
    WebkitColumnWidth: ColumnWidthProperty[TLength] = null,
    WebkitColumns: ColumnsProperty[TLength] = null,
    WebkitFilter: FilterProperty = null,
    WebkitFlex: FlexProperty[TLength] = null,
    WebkitFlexBasis: FlexBasisProperty[TLength] = null,
    WebkitFlexDirection: FlexDirectionProperty = null,
    WebkitFlexFlow: FlexFlowProperty = null,
    WebkitFlexGrow: GlobalsNumber = null,
    WebkitFlexShrink: GlobalsNumber = null,
    WebkitFlexWrap: FlexWrapProperty = null,
    WebkitFontFeatureSettings: FontFeatureSettingsProperty = null,
    WebkitFontKerning: FontKerningProperty = null,
    WebkitFontVariantLigatures: FontVariantLigaturesProperty = null,
    WebkitHyphens: HyphensProperty = null,
    WebkitJustifyContent: JustifyContentProperty = null,
    WebkitLineBreak: LineBreakProperty = null,
    WebkitLineClamp: WebkitLineClampProperty = null,
    WebkitMarginEnd: MarginInlineEndProperty[TLength] = null,
    WebkitMarginStart: MarginInlineStartProperty[TLength] = null,
    WebkitMask: WebkitMaskProperty[TLength] = null,
    WebkitMaskAttachment: WebkitMaskAttachmentProperty = null,
    WebkitMaskClip: WebkitMaskClipProperty = null,
    WebkitMaskComposite: WebkitMaskCompositeProperty = null,
    WebkitMaskImage: WebkitMaskImageProperty = null,
    WebkitMaskOrigin: WebkitMaskOriginProperty = null,
    WebkitMaskPosition: WebkitMaskPositionProperty[TLength] = null,
    WebkitMaskPositionX: WebkitMaskPositionXProperty[TLength] = null,
    WebkitMaskPositionY: WebkitMaskPositionYProperty[TLength] = null,
    WebkitMaskRepeat: WebkitMaskRepeatProperty = null,
    WebkitMaskRepeatX: WebkitMaskRepeatXProperty = null,
    WebkitMaskRepeatY: WebkitMaskRepeatYProperty = null,
    WebkitMaskSize: WebkitMaskSizeProperty[TLength] = null,
    WebkitMaxInlineSize: MaxInlineSizeProperty[TLength] = null,
    WebkitOrder: GlobalsNumber = null,
    WebkitOverflowScrolling: WebkitOverflowScrollingProperty = null,
    WebkitPaddingEnd: PaddingInlineEndProperty[TLength] = null,
    WebkitPaddingStart: PaddingInlineStartProperty[TLength] = null,
    WebkitPerspective: PerspectiveProperty[TLength] = null,
    WebkitPerspectiveOrigin: PerspectiveOriginProperty[TLength] = null,
    WebkitScrollSnapType: ScrollSnapTypeProperty = null,
    WebkitShapeMargin: ShapeMarginProperty[TLength] = null,
    WebkitTapHighlightColor: WebkitTapHighlightColorProperty = null,
    WebkitTextCombine: TextCombineUprightProperty = null,
    WebkitTextDecorationColor: TextDecorationColorProperty = null,
    WebkitTextDecorationLine: TextDecorationLineProperty = null,
    WebkitTextDecorationSkip: TextDecorationSkipProperty = null,
    WebkitTextDecorationStyle: TextDecorationStyleProperty = null,
    WebkitTextEmphasis: TextEmphasisProperty = null,
    WebkitTextEmphasisColor: TextEmphasisColorProperty = null,
    WebkitTextEmphasisPosition: GlobalsString = null,
    WebkitTextEmphasisStyle: TextEmphasisStyleProperty = null,
    WebkitTextFillColor: WebkitTextFillColorProperty = null,
    WebkitTextOrientation: TextOrientationProperty = null,
    WebkitTextSizeAdjust: TextSizeAdjustProperty = null,
    WebkitTextStroke: WebkitTextStrokeProperty[TLength] = null,
    WebkitTextStrokeColor: WebkitTextStrokeColorProperty = null,
    WebkitTextStrokeWidth: WebkitTextStrokeWidthProperty[TLength] = null,
    WebkitTouchCallout: WebkitTouchCalloutProperty = null,
    WebkitTransform: TransformProperty = null,
    WebkitTransformOrigin: TransformOriginProperty[TLength] = null,
    WebkitTransformStyle: TransformStyleProperty = null,
    WebkitTransition: TransitionProperty = null,
    WebkitTransitionDelay: GlobalsString = null,
    WebkitTransitionDuration: GlobalsString = null,
    WebkitTransitionProperty: TransitionPropertyProperty = null,
    WebkitTransitionTimingFunction: TransitionTimingFunctionProperty = null,
    WebkitUserModify: WebkitUserModifyProperty = null,
    WebkitUserSelect: UserSelectProperty = null,
    WebkitWritingMode: WritingModeProperty = null,
    msAccelerator: MsAcceleratorProperty = null,
    msAlignSelf: AlignSelfProperty = null,
    msBlockProgression: MsBlockProgressionProperty = null,
    msContentZoomChaining: MsContentZoomChainingProperty = null,
    msContentZoomLimit: GlobalsString = null,
    msContentZoomLimitMax: GlobalsString = null,
    msContentZoomLimitMin: GlobalsString = null,
    msContentZoomSnap: MsContentZoomSnapProperty = null,
    msContentZoomSnapPoints: GlobalsString = null,
    msContentZoomSnapType: MsContentZoomSnapTypeProperty = null,
    msContentZooming: MsContentZoomingProperty = null,
    msFilter: GlobalsString = null,
    msFlex: FlexProperty[TLength] = null,
    msFlexDirection: FlexDirectionProperty = null,
    msFlexPositive: GlobalsNumber = null,
    msFlowFrom: MsFlowFromProperty = null,
    msFlowInto: MsFlowIntoProperty = null,
    msGridColumns: GridAutoColumnsProperty[TLength] = null,
    msGridRows: GridAutoRowsProperty[TLength] = null,
    msHighContrastAdjust: MsHighContrastAdjustProperty = null,
    msHyphenateLimitChars: MsHyphenateLimitCharsProperty = null,
    msHyphenateLimitLines: MsHyphenateLimitLinesProperty = null,
    msHyphenateLimitZone: MsHyphenateLimitZoneProperty[TLength] = null,
    msHyphens: HyphensProperty = null,
    msImeAlign: MsImeAlignProperty = null,
    msLineBreak: LineBreakProperty = null,
    msOrder: GlobalsNumber = null,
    msOverflowStyle: MsOverflowStyleProperty = null,
    msOverflowX: OverflowXProperty = null,
    msOverflowY: OverflowYProperty = null,
    msScrollChaining: MsScrollChainingProperty = null,
    msScrollLimit: GlobalsString = null,
    msScrollLimitXMax: MsScrollLimitXMaxProperty[TLength] = null,
    msScrollLimitXMin: MsScrollLimitXMinProperty[TLength] = null,
    msScrollLimitYMax: MsScrollLimitYMaxProperty[TLength] = null,
    msScrollLimitYMin: MsScrollLimitYMinProperty[TLength] = null,
    msScrollRails: MsScrollRailsProperty = null,
    msScrollSnapPointsX: GlobalsString = null,
    msScrollSnapPointsY: GlobalsString = null,
    msScrollSnapType: MsScrollSnapTypeProperty = null,
    msScrollSnapX: GlobalsString = null,
    msScrollSnapY: GlobalsString = null,
    msScrollTranslation: MsScrollTranslationProperty = null,
    msScrollbar3dlightColor: MsScrollbar3dlightColorProperty = null,
    msScrollbarArrowColor: MsScrollbarArrowColorProperty = null,
    msScrollbarBaseColor: MsScrollbarBaseColorProperty = null,
    msScrollbarDarkshadowColor: MsScrollbarDarkshadowColorProperty = null,
    msScrollbarFaceColor: MsScrollbarFaceColorProperty = null,
    msScrollbarHighlightColor: MsScrollbarHighlightColorProperty = null,
    msScrollbarShadowColor: MsScrollbarShadowColorProperty = null,
    msScrollbarTrackColor: MsScrollbarTrackColorProperty = null,
    msTextAutospace: MsTextAutospaceProperty = null,
    msTextCombineHorizontal: TextCombineUprightProperty = null,
    msTextOverflow: TextOverflowProperty = null,
    msTouchAction: TouchActionProperty = null,
    msTouchSelect: MsTouchSelectProperty = null,
    msTransform: TransformProperty = null,
    msTransformOrigin: TransformOriginProperty[TLength] = null,
    msTransition: TransitionProperty = null,
    msTransitionDelay: GlobalsString = null,
    msTransitionDuration: GlobalsString = null,
    msTransitionProperty: TransitionPropertyProperty = null,
    msTransitionTimingFunction: TransitionTimingFunctionProperty = null,
    msUserSelect: MsUserSelectProperty = null,
    msWordBreak: WordBreakProperty = null,
    msWrapFlow: MsWrapFlowProperty = null,
    msWrapMargin: MsWrapMarginProperty[TLength] = null,
    msWrapThrough: MsWrapThroughProperty = null,
    msWritingMode: WritingModeProperty = null
  ): VendorProperties[TLength] = {
    val __obj = js.Dynamic.literal()
    if (MozAnimation != null) __obj.updateDynamic("MozAnimation")(MozAnimation.asInstanceOf[js.Any])
    if (MozAnimationDelay != null) __obj.updateDynamic("MozAnimationDelay")(MozAnimationDelay.asInstanceOf[js.Any])
    if (MozAnimationDirection != null) __obj.updateDynamic("MozAnimationDirection")(MozAnimationDirection.asInstanceOf[js.Any])
    if (MozAnimationDuration != null) __obj.updateDynamic("MozAnimationDuration")(MozAnimationDuration.asInstanceOf[js.Any])
    if (MozAnimationFillMode != null) __obj.updateDynamic("MozAnimationFillMode")(MozAnimationFillMode.asInstanceOf[js.Any])
    if (MozAnimationIterationCount != null) __obj.updateDynamic("MozAnimationIterationCount")(MozAnimationIterationCount.asInstanceOf[js.Any])
    if (MozAnimationName != null) __obj.updateDynamic("MozAnimationName")(MozAnimationName.asInstanceOf[js.Any])
    if (MozAnimationPlayState != null) __obj.updateDynamic("MozAnimationPlayState")(MozAnimationPlayState.asInstanceOf[js.Any])
    if (MozAnimationTimingFunction != null) __obj.updateDynamic("MozAnimationTimingFunction")(MozAnimationTimingFunction.asInstanceOf[js.Any])
    if (MozAppearance != null) __obj.updateDynamic("MozAppearance")(MozAppearance.asInstanceOf[js.Any])
    if (MozBackfaceVisibility != null) __obj.updateDynamic("MozBackfaceVisibility")(MozBackfaceVisibility.asInstanceOf[js.Any])
    if (MozBorderBottomColors != null) __obj.updateDynamic("MozBorderBottomColors")(MozBorderBottomColors.asInstanceOf[js.Any])
    if (MozBorderEndColor != null) __obj.updateDynamic("MozBorderEndColor")(MozBorderEndColor.asInstanceOf[js.Any])
    if (MozBorderEndStyle != null) __obj.updateDynamic("MozBorderEndStyle")(MozBorderEndStyle.asInstanceOf[js.Any])
    if (MozBorderEndWidth != null) __obj.updateDynamic("MozBorderEndWidth")(MozBorderEndWidth.asInstanceOf[js.Any])
    if (MozBorderImage != null) __obj.updateDynamic("MozBorderImage")(MozBorderImage.asInstanceOf[js.Any])
    if (MozBorderLeftColors != null) __obj.updateDynamic("MozBorderLeftColors")(MozBorderLeftColors.asInstanceOf[js.Any])
    if (MozBorderRightColors != null) __obj.updateDynamic("MozBorderRightColors")(MozBorderRightColors.asInstanceOf[js.Any])
    if (MozBorderStartColor != null) __obj.updateDynamic("MozBorderStartColor")(MozBorderStartColor.asInstanceOf[js.Any])
    if (MozBorderStartStyle != null) __obj.updateDynamic("MozBorderStartStyle")(MozBorderStartStyle.asInstanceOf[js.Any])
    if (MozBorderTopColors != null) __obj.updateDynamic("MozBorderTopColors")(MozBorderTopColors.asInstanceOf[js.Any])
    if (MozBoxSizing != null) __obj.updateDynamic("MozBoxSizing")(MozBoxSizing.asInstanceOf[js.Any])
    if (MozColumnCount != null) __obj.updateDynamic("MozColumnCount")(MozColumnCount.asInstanceOf[js.Any])
    if (MozColumnFill != null) __obj.updateDynamic("MozColumnFill")(MozColumnFill.asInstanceOf[js.Any])
    if (MozColumnGap != null) __obj.updateDynamic("MozColumnGap")(MozColumnGap.asInstanceOf[js.Any])
    if (MozColumnRule != null) __obj.updateDynamic("MozColumnRule")(MozColumnRule.asInstanceOf[js.Any])
    if (MozColumnRuleColor != null) __obj.updateDynamic("MozColumnRuleColor")(MozColumnRuleColor.asInstanceOf[js.Any])
    if (MozColumnRuleStyle != null) __obj.updateDynamic("MozColumnRuleStyle")(MozColumnRuleStyle.asInstanceOf[js.Any])
    if (MozColumnRuleWidth != null) __obj.updateDynamic("MozColumnRuleWidth")(MozColumnRuleWidth.asInstanceOf[js.Any])
    if (MozColumnWidth != null) __obj.updateDynamic("MozColumnWidth")(MozColumnWidth.asInstanceOf[js.Any])
    if (MozColumns != null) __obj.updateDynamic("MozColumns")(MozColumns.asInstanceOf[js.Any])
    if (MozContextProperties != null) __obj.updateDynamic("MozContextProperties")(MozContextProperties.asInstanceOf[js.Any])
    if (MozFloatEdge != null) __obj.updateDynamic("MozFloatEdge")(MozFloatEdge.asInstanceOf[js.Any])
    if (MozFontFeatureSettings != null) __obj.updateDynamic("MozFontFeatureSettings")(MozFontFeatureSettings.asInstanceOf[js.Any])
    if (MozFontLanguageOverride != null) __obj.updateDynamic("MozFontLanguageOverride")(MozFontLanguageOverride.asInstanceOf[js.Any])
    if (MozForceBrokenImageIcon != null) __obj.updateDynamic("MozForceBrokenImageIcon")(MozForceBrokenImageIcon.asInstanceOf[js.Any])
    if (MozHyphens != null) __obj.updateDynamic("MozHyphens")(MozHyphens.asInstanceOf[js.Any])
    if (MozImageRegion != null) __obj.updateDynamic("MozImageRegion")(MozImageRegion.asInstanceOf[js.Any])
    if (MozMarginEnd != null) __obj.updateDynamic("MozMarginEnd")(MozMarginEnd.asInstanceOf[js.Any])
    if (MozMarginStart != null) __obj.updateDynamic("MozMarginStart")(MozMarginStart.asInstanceOf[js.Any])
    if (MozOrient != null) __obj.updateDynamic("MozOrient")(MozOrient.asInstanceOf[js.Any])
    if (MozOutlineRadiusBottomleft != null) __obj.updateDynamic("MozOutlineRadiusBottomleft")(MozOutlineRadiusBottomleft.asInstanceOf[js.Any])
    if (MozOutlineRadiusBottomright != null) __obj.updateDynamic("MozOutlineRadiusBottomright")(MozOutlineRadiusBottomright.asInstanceOf[js.Any])
    if (MozOutlineRadiusTopleft != null) __obj.updateDynamic("MozOutlineRadiusTopleft")(MozOutlineRadiusTopleft.asInstanceOf[js.Any])
    if (MozOutlineRadiusTopright != null) __obj.updateDynamic("MozOutlineRadiusTopright")(MozOutlineRadiusTopright.asInstanceOf[js.Any])
    if (MozPaddingEnd != null) __obj.updateDynamic("MozPaddingEnd")(MozPaddingEnd.asInstanceOf[js.Any])
    if (MozPaddingStart != null) __obj.updateDynamic("MozPaddingStart")(MozPaddingStart.asInstanceOf[js.Any])
    if (MozPerspective != null) __obj.updateDynamic("MozPerspective")(MozPerspective.asInstanceOf[js.Any])
    if (MozPerspectiveOrigin != null) __obj.updateDynamic("MozPerspectiveOrigin")(MozPerspectiveOrigin.asInstanceOf[js.Any])
    if (MozStackSizing != null) __obj.updateDynamic("MozStackSizing")(MozStackSizing.asInstanceOf[js.Any])
    if (MozTabSize != null) __obj.updateDynamic("MozTabSize")(MozTabSize.asInstanceOf[js.Any])
    if (MozTextSizeAdjust != null) __obj.updateDynamic("MozTextSizeAdjust")(MozTextSizeAdjust.asInstanceOf[js.Any])
    if (MozTransformOrigin != null) __obj.updateDynamic("MozTransformOrigin")(MozTransformOrigin.asInstanceOf[js.Any])
    if (MozTransformStyle != null) __obj.updateDynamic("MozTransformStyle")(MozTransformStyle.asInstanceOf[js.Any])
    if (MozTransition != null) __obj.updateDynamic("MozTransition")(MozTransition.asInstanceOf[js.Any])
    if (MozTransitionDelay != null) __obj.updateDynamic("MozTransitionDelay")(MozTransitionDelay.asInstanceOf[js.Any])
    if (MozTransitionDuration != null) __obj.updateDynamic("MozTransitionDuration")(MozTransitionDuration.asInstanceOf[js.Any])
    if (MozTransitionProperty != null) __obj.updateDynamic("MozTransitionProperty")(MozTransitionProperty.asInstanceOf[js.Any])
    if (MozTransitionTimingFunction != null) __obj.updateDynamic("MozTransitionTimingFunction")(MozTransitionTimingFunction.asInstanceOf[js.Any])
    if (MozUserFocus != null) __obj.updateDynamic("MozUserFocus")(MozUserFocus.asInstanceOf[js.Any])
    if (MozUserModify != null) __obj.updateDynamic("MozUserModify")(MozUserModify.asInstanceOf[js.Any])
    if (MozUserSelect != null) __obj.updateDynamic("MozUserSelect")(MozUserSelect.asInstanceOf[js.Any])
    if (MozWindowDragging != null) __obj.updateDynamic("MozWindowDragging")(MozWindowDragging.asInstanceOf[js.Any])
    if (OObjectFit != null) __obj.updateDynamic("OObjectFit")(OObjectFit.asInstanceOf[js.Any])
    if (OObjectPosition != null) __obj.updateDynamic("OObjectPosition")(OObjectPosition.asInstanceOf[js.Any])
    if (OTabSize != null) __obj.updateDynamic("OTabSize")(OTabSize.asInstanceOf[js.Any])
    if (OTextOverflow != null) __obj.updateDynamic("OTextOverflow")(OTextOverflow.asInstanceOf[js.Any])
    if (OTransformOrigin != null) __obj.updateDynamic("OTransformOrigin")(OTransformOrigin.asInstanceOf[js.Any])
    if (WebkitAlignContent != null) __obj.updateDynamic("WebkitAlignContent")(WebkitAlignContent.asInstanceOf[js.Any])
    if (WebkitAlignItems != null) __obj.updateDynamic("WebkitAlignItems")(WebkitAlignItems.asInstanceOf[js.Any])
    if (WebkitAlignSelf != null) __obj.updateDynamic("WebkitAlignSelf")(WebkitAlignSelf.asInstanceOf[js.Any])
    if (WebkitAnimation != null) __obj.updateDynamic("WebkitAnimation")(WebkitAnimation.asInstanceOf[js.Any])
    if (WebkitAnimationDelay != null) __obj.updateDynamic("WebkitAnimationDelay")(WebkitAnimationDelay.asInstanceOf[js.Any])
    if (WebkitAnimationDirection != null) __obj.updateDynamic("WebkitAnimationDirection")(WebkitAnimationDirection.asInstanceOf[js.Any])
    if (WebkitAnimationDuration != null) __obj.updateDynamic("WebkitAnimationDuration")(WebkitAnimationDuration.asInstanceOf[js.Any])
    if (WebkitAnimationFillMode != null) __obj.updateDynamic("WebkitAnimationFillMode")(WebkitAnimationFillMode.asInstanceOf[js.Any])
    if (WebkitAnimationIterationCount != null) __obj.updateDynamic("WebkitAnimationIterationCount")(WebkitAnimationIterationCount.asInstanceOf[js.Any])
    if (WebkitAnimationName != null) __obj.updateDynamic("WebkitAnimationName")(WebkitAnimationName.asInstanceOf[js.Any])
    if (WebkitAnimationPlayState != null) __obj.updateDynamic("WebkitAnimationPlayState")(WebkitAnimationPlayState.asInstanceOf[js.Any])
    if (WebkitAnimationTimingFunction != null) __obj.updateDynamic("WebkitAnimationTimingFunction")(WebkitAnimationTimingFunction.asInstanceOf[js.Any])
    if (WebkitAppearance != null) __obj.updateDynamic("WebkitAppearance")(WebkitAppearance.asInstanceOf[js.Any])
    if (WebkitBackdropFilter != null) __obj.updateDynamic("WebkitBackdropFilter")(WebkitBackdropFilter.asInstanceOf[js.Any])
    if (WebkitBackfaceVisibility != null) __obj.updateDynamic("WebkitBackfaceVisibility")(WebkitBackfaceVisibility.asInstanceOf[js.Any])
    if (WebkitBackgroundClip != null) __obj.updateDynamic("WebkitBackgroundClip")(WebkitBackgroundClip.asInstanceOf[js.Any])
    if (WebkitBackgroundOrigin != null) __obj.updateDynamic("WebkitBackgroundOrigin")(WebkitBackgroundOrigin.asInstanceOf[js.Any])
    if (WebkitBackgroundSize != null) __obj.updateDynamic("WebkitBackgroundSize")(WebkitBackgroundSize.asInstanceOf[js.Any])
    if (WebkitBorderBefore != null) __obj.updateDynamic("WebkitBorderBefore")(WebkitBorderBefore.asInstanceOf[js.Any])
    if (WebkitBorderBeforeColor != null) __obj.updateDynamic("WebkitBorderBeforeColor")(WebkitBorderBeforeColor.asInstanceOf[js.Any])
    if (WebkitBorderBeforeStyle != null) __obj.updateDynamic("WebkitBorderBeforeStyle")(WebkitBorderBeforeStyle.asInstanceOf[js.Any])
    if (WebkitBorderBeforeWidth != null) __obj.updateDynamic("WebkitBorderBeforeWidth")(WebkitBorderBeforeWidth.asInstanceOf[js.Any])
    if (WebkitBorderBottomLeftRadius != null) __obj.updateDynamic("WebkitBorderBottomLeftRadius")(WebkitBorderBottomLeftRadius.asInstanceOf[js.Any])
    if (WebkitBorderBottomRightRadius != null) __obj.updateDynamic("WebkitBorderBottomRightRadius")(WebkitBorderBottomRightRadius.asInstanceOf[js.Any])
    if (WebkitBorderImage != null) __obj.updateDynamic("WebkitBorderImage")(WebkitBorderImage.asInstanceOf[js.Any])
    if (WebkitBorderImageSlice != null) __obj.updateDynamic("WebkitBorderImageSlice")(WebkitBorderImageSlice.asInstanceOf[js.Any])
    if (WebkitBorderRadius != null) __obj.updateDynamic("WebkitBorderRadius")(WebkitBorderRadius.asInstanceOf[js.Any])
    if (WebkitBorderTopLeftRadius != null) __obj.updateDynamic("WebkitBorderTopLeftRadius")(WebkitBorderTopLeftRadius.asInstanceOf[js.Any])
    if (WebkitBorderTopRightRadius != null) __obj.updateDynamic("WebkitBorderTopRightRadius")(WebkitBorderTopRightRadius.asInstanceOf[js.Any])
    if (WebkitBoxDecorationBreak != null) __obj.updateDynamic("WebkitBoxDecorationBreak")(WebkitBoxDecorationBreak.asInstanceOf[js.Any])
    if (WebkitBoxReflect != null) __obj.updateDynamic("WebkitBoxReflect")(WebkitBoxReflect.asInstanceOf[js.Any])
    if (WebkitBoxShadow != null) __obj.updateDynamic("WebkitBoxShadow")(WebkitBoxShadow.asInstanceOf[js.Any])
    if (WebkitBoxSizing != null) __obj.updateDynamic("WebkitBoxSizing")(WebkitBoxSizing.asInstanceOf[js.Any])
    if (WebkitClipPath != null) __obj.updateDynamic("WebkitClipPath")(WebkitClipPath.asInstanceOf[js.Any])
    if (WebkitColorAdjust != null) __obj.updateDynamic("WebkitColorAdjust")(WebkitColorAdjust.asInstanceOf[js.Any])
    if (WebkitColumnCount != null) __obj.updateDynamic("WebkitColumnCount")(WebkitColumnCount.asInstanceOf[js.Any])
    if (WebkitColumnFill != null) __obj.updateDynamic("WebkitColumnFill")(WebkitColumnFill.asInstanceOf[js.Any])
    if (WebkitColumnGap != null) __obj.updateDynamic("WebkitColumnGap")(WebkitColumnGap.asInstanceOf[js.Any])
    if (WebkitColumnRule != null) __obj.updateDynamic("WebkitColumnRule")(WebkitColumnRule.asInstanceOf[js.Any])
    if (WebkitColumnRuleColor != null) __obj.updateDynamic("WebkitColumnRuleColor")(WebkitColumnRuleColor.asInstanceOf[js.Any])
    if (WebkitColumnRuleStyle != null) __obj.updateDynamic("WebkitColumnRuleStyle")(WebkitColumnRuleStyle.asInstanceOf[js.Any])
    if (WebkitColumnRuleWidth != null) __obj.updateDynamic("WebkitColumnRuleWidth")(WebkitColumnRuleWidth.asInstanceOf[js.Any])
    if (WebkitColumnSpan != null) __obj.updateDynamic("WebkitColumnSpan")(WebkitColumnSpan.asInstanceOf[js.Any])
    if (WebkitColumnWidth != null) __obj.updateDynamic("WebkitColumnWidth")(WebkitColumnWidth.asInstanceOf[js.Any])
    if (WebkitColumns != null) __obj.updateDynamic("WebkitColumns")(WebkitColumns.asInstanceOf[js.Any])
    if (WebkitFilter != null) __obj.updateDynamic("WebkitFilter")(WebkitFilter.asInstanceOf[js.Any])
    if (WebkitFlex != null) __obj.updateDynamic("WebkitFlex")(WebkitFlex.asInstanceOf[js.Any])
    if (WebkitFlexBasis != null) __obj.updateDynamic("WebkitFlexBasis")(WebkitFlexBasis.asInstanceOf[js.Any])
    if (WebkitFlexDirection != null) __obj.updateDynamic("WebkitFlexDirection")(WebkitFlexDirection.asInstanceOf[js.Any])
    if (WebkitFlexFlow != null) __obj.updateDynamic("WebkitFlexFlow")(WebkitFlexFlow.asInstanceOf[js.Any])
    if (WebkitFlexGrow != null) __obj.updateDynamic("WebkitFlexGrow")(WebkitFlexGrow.asInstanceOf[js.Any])
    if (WebkitFlexShrink != null) __obj.updateDynamic("WebkitFlexShrink")(WebkitFlexShrink.asInstanceOf[js.Any])
    if (WebkitFlexWrap != null) __obj.updateDynamic("WebkitFlexWrap")(WebkitFlexWrap.asInstanceOf[js.Any])
    if (WebkitFontFeatureSettings != null) __obj.updateDynamic("WebkitFontFeatureSettings")(WebkitFontFeatureSettings.asInstanceOf[js.Any])
    if (WebkitFontKerning != null) __obj.updateDynamic("WebkitFontKerning")(WebkitFontKerning.asInstanceOf[js.Any])
    if (WebkitFontVariantLigatures != null) __obj.updateDynamic("WebkitFontVariantLigatures")(WebkitFontVariantLigatures.asInstanceOf[js.Any])
    if (WebkitHyphens != null) __obj.updateDynamic("WebkitHyphens")(WebkitHyphens.asInstanceOf[js.Any])
    if (WebkitJustifyContent != null) __obj.updateDynamic("WebkitJustifyContent")(WebkitJustifyContent.asInstanceOf[js.Any])
    if (WebkitLineBreak != null) __obj.updateDynamic("WebkitLineBreak")(WebkitLineBreak.asInstanceOf[js.Any])
    if (WebkitLineClamp != null) __obj.updateDynamic("WebkitLineClamp")(WebkitLineClamp.asInstanceOf[js.Any])
    if (WebkitMarginEnd != null) __obj.updateDynamic("WebkitMarginEnd")(WebkitMarginEnd.asInstanceOf[js.Any])
    if (WebkitMarginStart != null) __obj.updateDynamic("WebkitMarginStart")(WebkitMarginStart.asInstanceOf[js.Any])
    if (WebkitMask != null) __obj.updateDynamic("WebkitMask")(WebkitMask.asInstanceOf[js.Any])
    if (WebkitMaskAttachment != null) __obj.updateDynamic("WebkitMaskAttachment")(WebkitMaskAttachment.asInstanceOf[js.Any])
    if (WebkitMaskClip != null) __obj.updateDynamic("WebkitMaskClip")(WebkitMaskClip.asInstanceOf[js.Any])
    if (WebkitMaskComposite != null) __obj.updateDynamic("WebkitMaskComposite")(WebkitMaskComposite.asInstanceOf[js.Any])
    if (WebkitMaskImage != null) __obj.updateDynamic("WebkitMaskImage")(WebkitMaskImage.asInstanceOf[js.Any])
    if (WebkitMaskOrigin != null) __obj.updateDynamic("WebkitMaskOrigin")(WebkitMaskOrigin.asInstanceOf[js.Any])
    if (WebkitMaskPosition != null) __obj.updateDynamic("WebkitMaskPosition")(WebkitMaskPosition.asInstanceOf[js.Any])
    if (WebkitMaskPositionX != null) __obj.updateDynamic("WebkitMaskPositionX")(WebkitMaskPositionX.asInstanceOf[js.Any])
    if (WebkitMaskPositionY != null) __obj.updateDynamic("WebkitMaskPositionY")(WebkitMaskPositionY.asInstanceOf[js.Any])
    if (WebkitMaskRepeat != null) __obj.updateDynamic("WebkitMaskRepeat")(WebkitMaskRepeat.asInstanceOf[js.Any])
    if (WebkitMaskRepeatX != null) __obj.updateDynamic("WebkitMaskRepeatX")(WebkitMaskRepeatX.asInstanceOf[js.Any])
    if (WebkitMaskRepeatY != null) __obj.updateDynamic("WebkitMaskRepeatY")(WebkitMaskRepeatY.asInstanceOf[js.Any])
    if (WebkitMaskSize != null) __obj.updateDynamic("WebkitMaskSize")(WebkitMaskSize.asInstanceOf[js.Any])
    if (WebkitMaxInlineSize != null) __obj.updateDynamic("WebkitMaxInlineSize")(WebkitMaxInlineSize.asInstanceOf[js.Any])
    if (WebkitOrder != null) __obj.updateDynamic("WebkitOrder")(WebkitOrder.asInstanceOf[js.Any])
    if (WebkitOverflowScrolling != null) __obj.updateDynamic("WebkitOverflowScrolling")(WebkitOverflowScrolling.asInstanceOf[js.Any])
    if (WebkitPaddingEnd != null) __obj.updateDynamic("WebkitPaddingEnd")(WebkitPaddingEnd.asInstanceOf[js.Any])
    if (WebkitPaddingStart != null) __obj.updateDynamic("WebkitPaddingStart")(WebkitPaddingStart.asInstanceOf[js.Any])
    if (WebkitPerspective != null) __obj.updateDynamic("WebkitPerspective")(WebkitPerspective.asInstanceOf[js.Any])
    if (WebkitPerspectiveOrigin != null) __obj.updateDynamic("WebkitPerspectiveOrigin")(WebkitPerspectiveOrigin.asInstanceOf[js.Any])
    if (WebkitScrollSnapType != null) __obj.updateDynamic("WebkitScrollSnapType")(WebkitScrollSnapType.asInstanceOf[js.Any])
    if (WebkitShapeMargin != null) __obj.updateDynamic("WebkitShapeMargin")(WebkitShapeMargin.asInstanceOf[js.Any])
    if (WebkitTapHighlightColor != null) __obj.updateDynamic("WebkitTapHighlightColor")(WebkitTapHighlightColor.asInstanceOf[js.Any])
    if (WebkitTextCombine != null) __obj.updateDynamic("WebkitTextCombine")(WebkitTextCombine.asInstanceOf[js.Any])
    if (WebkitTextDecorationColor != null) __obj.updateDynamic("WebkitTextDecorationColor")(WebkitTextDecorationColor.asInstanceOf[js.Any])
    if (WebkitTextDecorationLine != null) __obj.updateDynamic("WebkitTextDecorationLine")(WebkitTextDecorationLine.asInstanceOf[js.Any])
    if (WebkitTextDecorationSkip != null) __obj.updateDynamic("WebkitTextDecorationSkip")(WebkitTextDecorationSkip.asInstanceOf[js.Any])
    if (WebkitTextDecorationStyle != null) __obj.updateDynamic("WebkitTextDecorationStyle")(WebkitTextDecorationStyle.asInstanceOf[js.Any])
    if (WebkitTextEmphasis != null) __obj.updateDynamic("WebkitTextEmphasis")(WebkitTextEmphasis.asInstanceOf[js.Any])
    if (WebkitTextEmphasisColor != null) __obj.updateDynamic("WebkitTextEmphasisColor")(WebkitTextEmphasisColor.asInstanceOf[js.Any])
    if (WebkitTextEmphasisPosition != null) __obj.updateDynamic("WebkitTextEmphasisPosition")(WebkitTextEmphasisPosition.asInstanceOf[js.Any])
    if (WebkitTextEmphasisStyle != null) __obj.updateDynamic("WebkitTextEmphasisStyle")(WebkitTextEmphasisStyle.asInstanceOf[js.Any])
    if (WebkitTextFillColor != null) __obj.updateDynamic("WebkitTextFillColor")(WebkitTextFillColor.asInstanceOf[js.Any])
    if (WebkitTextOrientation != null) __obj.updateDynamic("WebkitTextOrientation")(WebkitTextOrientation.asInstanceOf[js.Any])
    if (WebkitTextSizeAdjust != null) __obj.updateDynamic("WebkitTextSizeAdjust")(WebkitTextSizeAdjust.asInstanceOf[js.Any])
    if (WebkitTextStroke != null) __obj.updateDynamic("WebkitTextStroke")(WebkitTextStroke.asInstanceOf[js.Any])
    if (WebkitTextStrokeColor != null) __obj.updateDynamic("WebkitTextStrokeColor")(WebkitTextStrokeColor.asInstanceOf[js.Any])
    if (WebkitTextStrokeWidth != null) __obj.updateDynamic("WebkitTextStrokeWidth")(WebkitTextStrokeWidth.asInstanceOf[js.Any])
    if (WebkitTouchCallout != null) __obj.updateDynamic("WebkitTouchCallout")(WebkitTouchCallout.asInstanceOf[js.Any])
    if (WebkitTransform != null) __obj.updateDynamic("WebkitTransform")(WebkitTransform.asInstanceOf[js.Any])
    if (WebkitTransformOrigin != null) __obj.updateDynamic("WebkitTransformOrigin")(WebkitTransformOrigin.asInstanceOf[js.Any])
    if (WebkitTransformStyle != null) __obj.updateDynamic("WebkitTransformStyle")(WebkitTransformStyle.asInstanceOf[js.Any])
    if (WebkitTransition != null) __obj.updateDynamic("WebkitTransition")(WebkitTransition.asInstanceOf[js.Any])
    if (WebkitTransitionDelay != null) __obj.updateDynamic("WebkitTransitionDelay")(WebkitTransitionDelay.asInstanceOf[js.Any])
    if (WebkitTransitionDuration != null) __obj.updateDynamic("WebkitTransitionDuration")(WebkitTransitionDuration.asInstanceOf[js.Any])
    if (WebkitTransitionProperty != null) __obj.updateDynamic("WebkitTransitionProperty")(WebkitTransitionProperty.asInstanceOf[js.Any])
    if (WebkitTransitionTimingFunction != null) __obj.updateDynamic("WebkitTransitionTimingFunction")(WebkitTransitionTimingFunction.asInstanceOf[js.Any])
    if (WebkitUserModify != null) __obj.updateDynamic("WebkitUserModify")(WebkitUserModify.asInstanceOf[js.Any])
    if (WebkitUserSelect != null) __obj.updateDynamic("WebkitUserSelect")(WebkitUserSelect.asInstanceOf[js.Any])
    if (WebkitWritingMode != null) __obj.updateDynamic("WebkitWritingMode")(WebkitWritingMode.asInstanceOf[js.Any])
    if (msAccelerator != null) __obj.updateDynamic("msAccelerator")(msAccelerator.asInstanceOf[js.Any])
    if (msAlignSelf != null) __obj.updateDynamic("msAlignSelf")(msAlignSelf.asInstanceOf[js.Any])
    if (msBlockProgression != null) __obj.updateDynamic("msBlockProgression")(msBlockProgression.asInstanceOf[js.Any])
    if (msContentZoomChaining != null) __obj.updateDynamic("msContentZoomChaining")(msContentZoomChaining.asInstanceOf[js.Any])
    if (msContentZoomLimit != null) __obj.updateDynamic("msContentZoomLimit")(msContentZoomLimit.asInstanceOf[js.Any])
    if (msContentZoomLimitMax != null) __obj.updateDynamic("msContentZoomLimitMax")(msContentZoomLimitMax.asInstanceOf[js.Any])
    if (msContentZoomLimitMin != null) __obj.updateDynamic("msContentZoomLimitMin")(msContentZoomLimitMin.asInstanceOf[js.Any])
    if (msContentZoomSnap != null) __obj.updateDynamic("msContentZoomSnap")(msContentZoomSnap.asInstanceOf[js.Any])
    if (msContentZoomSnapPoints != null) __obj.updateDynamic("msContentZoomSnapPoints")(msContentZoomSnapPoints.asInstanceOf[js.Any])
    if (msContentZoomSnapType != null) __obj.updateDynamic("msContentZoomSnapType")(msContentZoomSnapType.asInstanceOf[js.Any])
    if (msContentZooming != null) __obj.updateDynamic("msContentZooming")(msContentZooming.asInstanceOf[js.Any])
    if (msFilter != null) __obj.updateDynamic("msFilter")(msFilter.asInstanceOf[js.Any])
    if (msFlex != null) __obj.updateDynamic("msFlex")(msFlex.asInstanceOf[js.Any])
    if (msFlexDirection != null) __obj.updateDynamic("msFlexDirection")(msFlexDirection.asInstanceOf[js.Any])
    if (msFlexPositive != null) __obj.updateDynamic("msFlexPositive")(msFlexPositive.asInstanceOf[js.Any])
    if (msFlowFrom != null) __obj.updateDynamic("msFlowFrom")(msFlowFrom.asInstanceOf[js.Any])
    if (msFlowInto != null) __obj.updateDynamic("msFlowInto")(msFlowInto.asInstanceOf[js.Any])
    if (msGridColumns != null) __obj.updateDynamic("msGridColumns")(msGridColumns.asInstanceOf[js.Any])
    if (msGridRows != null) __obj.updateDynamic("msGridRows")(msGridRows.asInstanceOf[js.Any])
    if (msHighContrastAdjust != null) __obj.updateDynamic("msHighContrastAdjust")(msHighContrastAdjust.asInstanceOf[js.Any])
    if (msHyphenateLimitChars != null) __obj.updateDynamic("msHyphenateLimitChars")(msHyphenateLimitChars.asInstanceOf[js.Any])
    if (msHyphenateLimitLines != null) __obj.updateDynamic("msHyphenateLimitLines")(msHyphenateLimitLines.asInstanceOf[js.Any])
    if (msHyphenateLimitZone != null) __obj.updateDynamic("msHyphenateLimitZone")(msHyphenateLimitZone.asInstanceOf[js.Any])
    if (msHyphens != null) __obj.updateDynamic("msHyphens")(msHyphens.asInstanceOf[js.Any])
    if (msImeAlign != null) __obj.updateDynamic("msImeAlign")(msImeAlign.asInstanceOf[js.Any])
    if (msLineBreak != null) __obj.updateDynamic("msLineBreak")(msLineBreak.asInstanceOf[js.Any])
    if (msOrder != null) __obj.updateDynamic("msOrder")(msOrder.asInstanceOf[js.Any])
    if (msOverflowStyle != null) __obj.updateDynamic("msOverflowStyle")(msOverflowStyle.asInstanceOf[js.Any])
    if (msOverflowX != null) __obj.updateDynamic("msOverflowX")(msOverflowX.asInstanceOf[js.Any])
    if (msOverflowY != null) __obj.updateDynamic("msOverflowY")(msOverflowY.asInstanceOf[js.Any])
    if (msScrollChaining != null) __obj.updateDynamic("msScrollChaining")(msScrollChaining.asInstanceOf[js.Any])
    if (msScrollLimit != null) __obj.updateDynamic("msScrollLimit")(msScrollLimit.asInstanceOf[js.Any])
    if (msScrollLimitXMax != null) __obj.updateDynamic("msScrollLimitXMax")(msScrollLimitXMax.asInstanceOf[js.Any])
    if (msScrollLimitXMin != null) __obj.updateDynamic("msScrollLimitXMin")(msScrollLimitXMin.asInstanceOf[js.Any])
    if (msScrollLimitYMax != null) __obj.updateDynamic("msScrollLimitYMax")(msScrollLimitYMax.asInstanceOf[js.Any])
    if (msScrollLimitYMin != null) __obj.updateDynamic("msScrollLimitYMin")(msScrollLimitYMin.asInstanceOf[js.Any])
    if (msScrollRails != null) __obj.updateDynamic("msScrollRails")(msScrollRails.asInstanceOf[js.Any])
    if (msScrollSnapPointsX != null) __obj.updateDynamic("msScrollSnapPointsX")(msScrollSnapPointsX.asInstanceOf[js.Any])
    if (msScrollSnapPointsY != null) __obj.updateDynamic("msScrollSnapPointsY")(msScrollSnapPointsY.asInstanceOf[js.Any])
    if (msScrollSnapType != null) __obj.updateDynamic("msScrollSnapType")(msScrollSnapType.asInstanceOf[js.Any])
    if (msScrollSnapX != null) __obj.updateDynamic("msScrollSnapX")(msScrollSnapX.asInstanceOf[js.Any])
    if (msScrollSnapY != null) __obj.updateDynamic("msScrollSnapY")(msScrollSnapY.asInstanceOf[js.Any])
    if (msScrollTranslation != null) __obj.updateDynamic("msScrollTranslation")(msScrollTranslation.asInstanceOf[js.Any])
    if (msScrollbar3dlightColor != null) __obj.updateDynamic("msScrollbar3dlightColor")(msScrollbar3dlightColor.asInstanceOf[js.Any])
    if (msScrollbarArrowColor != null) __obj.updateDynamic("msScrollbarArrowColor")(msScrollbarArrowColor.asInstanceOf[js.Any])
    if (msScrollbarBaseColor != null) __obj.updateDynamic("msScrollbarBaseColor")(msScrollbarBaseColor.asInstanceOf[js.Any])
    if (msScrollbarDarkshadowColor != null) __obj.updateDynamic("msScrollbarDarkshadowColor")(msScrollbarDarkshadowColor.asInstanceOf[js.Any])
    if (msScrollbarFaceColor != null) __obj.updateDynamic("msScrollbarFaceColor")(msScrollbarFaceColor.asInstanceOf[js.Any])
    if (msScrollbarHighlightColor != null) __obj.updateDynamic("msScrollbarHighlightColor")(msScrollbarHighlightColor.asInstanceOf[js.Any])
    if (msScrollbarShadowColor != null) __obj.updateDynamic("msScrollbarShadowColor")(msScrollbarShadowColor.asInstanceOf[js.Any])
    if (msScrollbarTrackColor != null) __obj.updateDynamic("msScrollbarTrackColor")(msScrollbarTrackColor.asInstanceOf[js.Any])
    if (msTextAutospace != null) __obj.updateDynamic("msTextAutospace")(msTextAutospace.asInstanceOf[js.Any])
    if (msTextCombineHorizontal != null) __obj.updateDynamic("msTextCombineHorizontal")(msTextCombineHorizontal.asInstanceOf[js.Any])
    if (msTextOverflow != null) __obj.updateDynamic("msTextOverflow")(msTextOverflow.asInstanceOf[js.Any])
    if (msTouchAction != null) __obj.updateDynamic("msTouchAction")(msTouchAction.asInstanceOf[js.Any])
    if (msTouchSelect != null) __obj.updateDynamic("msTouchSelect")(msTouchSelect.asInstanceOf[js.Any])
    if (msTransform != null) __obj.updateDynamic("msTransform")(msTransform.asInstanceOf[js.Any])
    if (msTransformOrigin != null) __obj.updateDynamic("msTransformOrigin")(msTransformOrigin.asInstanceOf[js.Any])
    if (msTransition != null) __obj.updateDynamic("msTransition")(msTransition.asInstanceOf[js.Any])
    if (msTransitionDelay != null) __obj.updateDynamic("msTransitionDelay")(msTransitionDelay.asInstanceOf[js.Any])
    if (msTransitionDuration != null) __obj.updateDynamic("msTransitionDuration")(msTransitionDuration.asInstanceOf[js.Any])
    if (msTransitionProperty != null) __obj.updateDynamic("msTransitionProperty")(msTransitionProperty.asInstanceOf[js.Any])
    if (msTransitionTimingFunction != null) __obj.updateDynamic("msTransitionTimingFunction")(msTransitionTimingFunction.asInstanceOf[js.Any])
    if (msUserSelect != null) __obj.updateDynamic("msUserSelect")(msUserSelect.asInstanceOf[js.Any])
    if (msWordBreak != null) __obj.updateDynamic("msWordBreak")(msWordBreak.asInstanceOf[js.Any])
    if (msWrapFlow != null) __obj.updateDynamic("msWrapFlow")(msWrapFlow.asInstanceOf[js.Any])
    if (msWrapMargin != null) __obj.updateDynamic("msWrapMargin")(msWrapMargin.asInstanceOf[js.Any])
    if (msWrapThrough != null) __obj.updateDynamic("msWrapThrough")(msWrapThrough.asInstanceOf[js.Any])
    if (msWritingMode != null) __obj.updateDynamic("msWritingMode")(msWritingMode.asInstanceOf[js.Any])
    __obj.asInstanceOf[VendorProperties[TLength]]
  }
}

