package typings.devtoolsProtocol.mod.Protocol.Audits

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/* Rewritten from type alias, can be one of: 
  - typings.devtoolsProtocol.devtoolsProtocolStrings.CrossOriginPortalPostMessageError
  - typings.devtoolsProtocol.devtoolsProtocolStrings.FormLabelForNameError
  - typings.devtoolsProtocol.devtoolsProtocolStrings.FormDuplicateIdForInputError
  - typings.devtoolsProtocol.devtoolsProtocolStrings.FormInputWithNoLabelError
  - typings.devtoolsProtocol.devtoolsProtocolStrings.FormAutocompleteAttributeEmptyError
  - typings.devtoolsProtocol.devtoolsProtocolStrings.FormEmptyIdAndNameAttributesForInputError
  - typings.devtoolsProtocol.devtoolsProtocolStrings.FormAriaLabelledByToNonExistingId
  - typings.devtoolsProtocol.devtoolsProtocolStrings.FormInputAssignedAutocompleteValueToIdOrNameAttributeError
  - typings.devtoolsProtocol.devtoolsProtocolStrings.FormLabelHasNeitherForNorNestedInput
  - typings.devtoolsProtocol.devtoolsProtocolStrings.FormLabelForMatchesNonExistingIdError
  - typings.devtoolsProtocol.devtoolsProtocolStrings.FormInputHasWrongButWellIntendedAutocompleteValueError
*/
trait GenericIssueErrorType extends StObject
object GenericIssueErrorType {
  
  inline def CrossOriginPortalPostMessageError: typings.devtoolsProtocol.devtoolsProtocolStrings.CrossOriginPortalPostMessageError = "CrossOriginPortalPostMessageError".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.CrossOriginPortalPostMessageError]
  
  inline def FormAriaLabelledByToNonExistingId: typings.devtoolsProtocol.devtoolsProtocolStrings.FormAriaLabelledByToNonExistingId = "FormAriaLabelledByToNonExistingId".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.FormAriaLabelledByToNonExistingId]
  
  inline def FormAutocompleteAttributeEmptyError: typings.devtoolsProtocol.devtoolsProtocolStrings.FormAutocompleteAttributeEmptyError = "FormAutocompleteAttributeEmptyError".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.FormAutocompleteAttributeEmptyError]
  
  inline def FormDuplicateIdForInputError: typings.devtoolsProtocol.devtoolsProtocolStrings.FormDuplicateIdForInputError = "FormDuplicateIdForInputError".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.FormDuplicateIdForInputError]
  
  inline def FormEmptyIdAndNameAttributesForInputError: typings.devtoolsProtocol.devtoolsProtocolStrings.FormEmptyIdAndNameAttributesForInputError = "FormEmptyIdAndNameAttributesForInputError".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.FormEmptyIdAndNameAttributesForInputError]
  
  inline def FormInputAssignedAutocompleteValueToIdOrNameAttributeError: typings.devtoolsProtocol.devtoolsProtocolStrings.FormInputAssignedAutocompleteValueToIdOrNameAttributeError = "FormInputAssignedAutocompleteValueToIdOrNameAttributeError".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.FormInputAssignedAutocompleteValueToIdOrNameAttributeError]
  
  inline def FormInputHasWrongButWellIntendedAutocompleteValueError: typings.devtoolsProtocol.devtoolsProtocolStrings.FormInputHasWrongButWellIntendedAutocompleteValueError = "FormInputHasWrongButWellIntendedAutocompleteValueError".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.FormInputHasWrongButWellIntendedAutocompleteValueError]
  
  inline def FormInputWithNoLabelError: typings.devtoolsProtocol.devtoolsProtocolStrings.FormInputWithNoLabelError = "FormInputWithNoLabelError".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.FormInputWithNoLabelError]
  
  inline def FormLabelForMatchesNonExistingIdError: typings.devtoolsProtocol.devtoolsProtocolStrings.FormLabelForMatchesNonExistingIdError = "FormLabelForMatchesNonExistingIdError".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.FormLabelForMatchesNonExistingIdError]
  
  inline def FormLabelForNameError: typings.devtoolsProtocol.devtoolsProtocolStrings.FormLabelForNameError = "FormLabelForNameError".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.FormLabelForNameError]
  
  inline def FormLabelHasNeitherForNorNestedInput: typings.devtoolsProtocol.devtoolsProtocolStrings.FormLabelHasNeitherForNorNestedInput = "FormLabelHasNeitherForNorNestedInput".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.FormLabelHasNeitherForNorNestedInput]
}
