package typings.devtoolsProtocol.mod.Protocol.Audits

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/* Rewritten from type alias, can be one of: 
  - typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteUnspecifiedCrossSiteContext
  - typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteNoneInsecure
  - typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteUnspecifiedLaxAllowUnsafe
  - typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteStrictLaxDowngradeStrict
  - typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteStrictCrossDowngradeStrict
  - typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteStrictCrossDowngradeLax
  - typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteLaxCrossDowngradeStrict
  - typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteLaxCrossDowngradeLax
*/
trait SameSiteCookieWarningReason extends StObject
object SameSiteCookieWarningReason {
  
  inline def WarnSameSiteLaxCrossDowngradeLax: typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteLaxCrossDowngradeLax = "WarnSameSiteLaxCrossDowngradeLax".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteLaxCrossDowngradeLax]
  
  inline def WarnSameSiteLaxCrossDowngradeStrict: typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteLaxCrossDowngradeStrict = "WarnSameSiteLaxCrossDowngradeStrict".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteLaxCrossDowngradeStrict]
  
  inline def WarnSameSiteNoneInsecure: typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteNoneInsecure = "WarnSameSiteNoneInsecure".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteNoneInsecure]
  
  inline def WarnSameSiteStrictCrossDowngradeLax: typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteStrictCrossDowngradeLax = "WarnSameSiteStrictCrossDowngradeLax".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteStrictCrossDowngradeLax]
  
  inline def WarnSameSiteStrictCrossDowngradeStrict: typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteStrictCrossDowngradeStrict = "WarnSameSiteStrictCrossDowngradeStrict".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteStrictCrossDowngradeStrict]
  
  inline def WarnSameSiteStrictLaxDowngradeStrict: typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteStrictLaxDowngradeStrict = "WarnSameSiteStrictLaxDowngradeStrict".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteStrictLaxDowngradeStrict]
  
  inline def WarnSameSiteUnspecifiedCrossSiteContext: typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteUnspecifiedCrossSiteContext = "WarnSameSiteUnspecifiedCrossSiteContext".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteUnspecifiedCrossSiteContext]
  
  inline def WarnSameSiteUnspecifiedLaxAllowUnsafe: typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteUnspecifiedLaxAllowUnsafe = "WarnSameSiteUnspecifiedLaxAllowUnsafe".asInstanceOf[typings.devtoolsProtocol.devtoolsProtocolStrings.WarnSameSiteUnspecifiedLaxAllowUnsafe]
}
